### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by kentaroy47** [open-mmlab/mmdetection3d#10]
Thanks for the great project.
While it says that the project is released under Apache license, the file is missing..

**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by ZwwWayne** [comment]
Hi @kentaroy47 ,
Thanks for your notification, we will add it ASAP.

**Comment by ZwwWayne** [comment]
Fixed.
