### ISSUE TITLE
error show result with Open3D 

### ISSUE THREAD

**Issue by fellen88** [open-mmlab/mmdetection3d#1000]
I use docker install and run docker as below:

xhost +
sudo docker run --gpus all --shm-size=8g --name 3dshow -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY -e GDK_SCALE -e GDK_DPI_SCALE -v data:/mmdetection3d/data mmdetection3d_torch1.8

when l show the result with Open3D , error report as below：

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
[Open3D WARNING] GLFW Error: GLX: Failed to create context: BadMatch (invalid parameter attributes)
[Open3D WARNING] Failed to create window

**Comment by ZCMax** [comment]
It seems like your environment does not support OpenGL. Does your graphical hardware correctly setup? Aren't you working with remote machine? It would be helpful for others if you share your environment, or configuration for compilation.
