### ISSUE TITLE
Multisweeps on Waymo.

### ISSUE THREAD

**Issue by Abyssaledge** [open-mmlab/mmdetection3d#1002]
It seems that the current codes do not support multi sweeps on Waymo Open Dataset. 
There are no entries about `sweeps` or `timestamp` in input data initialization: https://github.com/open-mmlab/mmdetection3d/blob/60ce864ff76af4316fb9ae56a2a5b7741bfdd9ab/mmdet3d/datasets/waymo_dataset.py#L121
And the `timestamp` in `waymo_infos_val.pkl` seems wrong, because all frames in a sequence share a same timestamp. This might be caused by timestamp is saved as float32 together with points data.
Is there an elegant way to implement multi-sweep loading?

**Comment by Tai-Wang** [comment]
You can refer to #296 for the problem of saving timestamps. We currently only support multi-frame loading on nuScenes and do not have enough resources to support it on Waymo recently. We can discuss it under this issue. Any PRs and discussions are welcome.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
