### ISSUE TITLE
How can I change kitti_calib?

### ISSUE THREAD

**Issue by ggomac** [open-mmlab/mmdetection3d#1004]
### **kitti calib** 
P0: 	7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 0.000000000000e+00 
	0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 0.000000000000e+00 
	0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00

P1: 	7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 -3.797842000000e+02 
	0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 0.000000000000e+00 
	0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00

P2: 	7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 4.575831000000e+01 
	0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 -3.454157000000e-01 
	0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 4.981016000000e-03

P3: 	7.070493000000e+02 0.000000000000e+00 6.040814000000e+02 -3.341081000000e+02 
	0.000000000000e+00 7.070493000000e+02 1.805066000000e+02 2.330660000000e+00 
	0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 3.201153000000e-03

3x3 rectifying rotation to make image planes co-planar
R0_rect:	 9.999128000000e-01 1.009263000000e-02 -8.511932000000e-03 
	        -1.012729000000e-02 9.999406000000e-01 -4.037671000000e-03 
	        8.470675000000e-03 4.123522000000e-03 9.999556000000e-01

calib_velo_to_cam.txt: Velodyne-to-camera registration
Tr_velo_to_cam:
         	 6.927964000000e-03 -9.999722000000e-01 -2.757829000000e-03 
		-2.457729000000e-02 -1.162982000000e-03 2.749836000000e-03 
		-9.999955000000e-01 -6.127237000000e-02 9.999753000000e-01              R: 3x3 rotation matrix   
		 6.931141000000e-03 -1.143899000000e-03 -3.321029000000e-01		T: 1x3 translation vector

calib_imu_to_velo.txt: GPS/IMU-to-Velodyne registration
Tr_imu_to_velo: 	
                 9.999976000000e-01 7.553071000000e-04 -2.035826000000e-03 
		-8.086759000000e-01 -7.854027000000e-04 9.998898000000e-01 
		-1.482298000000e-02 3.195559000000e-01 2.024406000000e-03  		R: 3x3 rotation matrix 
		 1.482454000000e-02 9.998881000000e-01 -7.997231000000e-01		T: 1x3 translation vector

_All calib are laid out in a matrix for easy viewing.
I don't have p0, p1, p3, R0_rect and Tr_imu_to_velo calib.
So I change them to unit matrix_

**my_calib**
P0: 1.000000000000e+00 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 
      0.000000000000e+00 1.000000000000e+00 0.000000000000e+00 0.000000000000e+00 
      0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00
P1: 1.000000000000e+00 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 
      0.000000000000e+00 1.000000000000e+00 0.000000000000e+00 0.000000000000e+00
      0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00
P2: 1.435578400000e+03 0.000000000000e+00 9.600000000000e+02 0.000000000000e+00
     0.000000000000e+00 1.445207670000e+02 5.400000000000e+02 0.000000000000e+00 
     0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00
P3: 1.000000000000e+00 0.000000000000e+00 0.000000000000e+00 0.000000000000e+00 
      0.000000000000e+00 1.000000000000e+00 0.000000000000e+00 0.000000000000e+00 
      0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+00
R0_rect: 1.000000000000e+00 0.000000000000e+00 0.000000000000e+00 
              0.000000000000e+00 1.000000000000e+00 0.000000000000e+00 
              0.000000000000e+00 0.000000000000e+00 1.000000000000e+00
Tr_velo_to_cam: 
                  9.989881800000e-01 -4.346468000000e-02 -1.155129000000e-02 
                -1.009945000000e-02 3.347534000000e-02 -9.993885100000e-01 
                 4.382479000000e-02 9.984939800000e-01 3.300250000000e-02 
                 3.620099000000e-02 1.233898990000e+00 1.351976560000e+00
Tr_imu_to_velo: 
    1.000000000000e+00 0.000000000000e+00 0.000000000000e+00 
    0.000000000000e+00 1.000000000000e+00 0.000000000000e+00 
    0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 
    0.000000000000e+00 0.000000000000e+00 0.000000000000e+00

**But I got the following error:**
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1

How can I fix it?

**Comment by ggomac** [comment]
> Do you mean that you set the calibration matrix to identity matrix on your customized dataset? Can you show more details and follow the issue template?

yes, I set the calibration matrix to identity matrix and use my pcd_data. But others use kitti dataset. 

│   ├── kitti
│   │   ├── ImageSets
│   │   ├── testing
│   │   │   ├── calib
│   │   │   ├── image_2
│   │   │   ├── velodyne
│   │   ├── training
│   │   │   ├── calib                  <-- my calibration
│   │   │   ├── image_2            <-- kitti_image
│   │   │   ├── label_2              <-- unnecessary values    ex) DontCare -1 -1 -10 706.29 ............. -1000 -10
│   │   │   ├── velodyne           <--  I change my_pcd file to bin.file format

this datasets succeeded in implementing ```create_data.py```
```bash
(open-mmlab) @@@@@@:~/mmdetection3d$ python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti
Generate info. this may take several minutes.
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1/1, 1.4 task/s, elapsed: 1s, ETA:     0s
Kitti info train file is saved to data/kitti/kitti_infos_train.pkl
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1/1, 618.4 task/s, elapsed: 0s, ETA:     0s
Kitti info val file is saved to data/kitti/kitti_infos_val.pkl
Kitti info trainval file is saved to data/kitti/kitti_infos_trainval.pkl
Kitti info test file is saved to data/kitti/kitti_infos_test.pkl
create reduced point cloud for training set
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1/1, 860.2 task/s, elapsed: 0s, ETA:     0s
create reduced point cloud for validation set
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1/1, 1073.0 task/s, elapsed: 0s, ETA:     0s
create reduced point cloud for testing set
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1/1, 555.5 task/s, elapsed: 0s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1/1, 131.9 task/s, elapsed: 0s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1/1, 135.2 task/s, elapsed: 0s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2/2, 135.8 task/s, elapsed: 0s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1/1, 134.1 task/s, elapsed: 0s, ETA:     0s
Create GT Database of KittiDataset
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1/1, 6.5 task/s, elapsed: 0s, ETA:     0s
```

But when I'm implementing ```test.py``` 
```bash
(open-mmlab) s@su20300:~/mmdetection3d$ python tools/test.py configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --eval mAP --show --show-dir ./data/kitti/show_results/
Use load_from_local loader
[                                                  ] 0/1, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 221, in <module>
    main()
  File "tools/test.py", line 191, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/home/s/mmdetection3d/mmdet3d/apis/test.py", line 39, in single_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/s/mmdetection3d/mmdet3d/models/detectors/base.py", line 61, in forward
    return self.forward_test(**kwargs)
  File "/home/s/mmdetection3d/mmdet3d/models/detectors/base.py", line 42, in forward_test
    return self.simple_test(points[0], img_metas[0], img[0], **kwargs)
  File "/home/s/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 100, in simple_test
    x = self.extract_feat(points, img_metas)
  File "/home/s/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 42, in extract_feat
    voxels, num_points, coors = self.voxelize(points)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 186, in new_func
    return old_func(*args, **kwargs)
  File "/home/s/mmdetection3d/mmdet3d/models/detectors/voxelnet.py", line 57, in voxelize
    res_voxels, res_coors, res_num_points = self.voxel_layer(res)
  File "/home/s/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/s/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 138, in forward
    self.deterministic)
  File "/home/s/mmdetection3d/mmdet3d/ops/voxel/voxelize.py", line 65, in forward
    deterministic)
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
this error occured

So I think my_calib is wrong. Do you know how can i fix it?

**Comment by Tai-Wang** [comment]
Please feel free to reopen this issue if there are any further questions.

**Comment by ggomac** [comment]
I had difficulty changing calibration, so I reopen it.  I'm sorry for bothering you.
The document below is a note of the problem I have.
Please tell us what you think is wrong with it.

https://docs.google.com/document/d/1ri_KvcjXDqpbJr3ZNWdt3XZAC9Ivfrid3-8nnJKo1ho/edit?usp=sharing

**Comment by ggomac** [comment]
I had difficulty changing calibration. I'm sorry for bothering you.
The document below is a note of the problem I have.
Please tell us what you think is wrong with it.

https://docs.google.com/document/d/1ri_KvcjXDqpbJr3ZNWdt3XZAC9Ivfrid3-8nnJKo1ho/edit?usp=sharing

**Comment by DavidWZX** [comment]
@ggomac Have you successfully changed the calib files fitted with your own lidar dataset? Can you share your method or some hints please?

**Comment by yypark21** [comment]
@DavidWZX sorry for late answer.
I have successfully changed the calib with my own dataset. 
I refer to this site and document.
[The KITTI Dataset](http://www.cvlibs.net/publications/Geiger2013IJRR.pdf)
[KITTI label](https://github.com/bostondiditeam/kitti/blob/master/resources/devkit_object/readme.txt)

Please explain in more detail which part of your calib is the problem.

**Comment by amineboujnah-dev** [comment]
@yypark21 can you help me doing that for my custom dataset ?

**Comment by comverser** [comment]
Hi @amineboujnah-dev, you can view an example code of the conversion here:
https://github.com/comverser/gnlabs-converter/blob/main/src/libs/gnlabs2kitti.py

**Comment by amineboujnah-dev** [comment]
I am using one camera and one vlp-16 lidar, my calib file should contain what ?
