### ISSUE TITLE
The annotation centers2d pipeline ERROR in training FCOS3D on waymo datasets

### ISSUE THREAD

**Issue by idontlikelongname** [open-mmlab/mmdetection3d#1008]
MMDetection3d commit 180ad042
MMDetection commit 7bd39044

Im training FCOS3D using waymo datasets. The datasets contains centers2d labels in 1920x1080 pixel resolution.
The images is resized to 1200x800 to put into netwok in datasets pipeline. 
I noticed that gt_bboxes is resized in pipeline according to the resize factor, but not the centers2d. 
centers2d will influence the centerness output in assigner step. 
I want to know whether its bug or the wrong params in my config. 

this is my train pipeline
```
train_pipeline = [
    dict(type="LoadImageFromFileMono3D"),
    dict(
        type="LoadAnnotations3D",
        with_bbox=True,
        with_label=True,
        with_bbox_3d=True,
        with_label_3d=True,
        with_bbox_depth=True,
    ),
    dict(type="Resize", img_scale=(1200, 800), keep_ratio=True),
    # dict(type="RandomFlip3D", flip_ratio_bev_horizontal=0.5),
    dict(type="Normalize", **img_norm_cfg),
    dict(type="Pad", size_divisor=32, pad_val=0),
    dict(type="DefaultFormatBundle3D", class_names=class_names),
    dict(
        type="Collect3D",
        keys=[
            "img",
            "gt_bboxes",
            "gt_labels",
            "gt_bboxes_3d",
            "gt_labels_3d",
            "centers2d",
            "depths",
        ],
    ),
]
```

**Comment by xiaowenhe** [comment]
@idontlikelongname, Do you get right detect box when you  changed reszie ops? Can you share you change?
