### ISSUE TITLE
create_data error

### ISSUE THREAD

**Issue by fellenB** [open-mmlab/mmdetection3d#1009]
when I run :
python tools/create_data.py kitti --root-path ./data/kitti_own/ --out-dir ./data/kitti_own/ --extra-tag kitti

there is an error as below:

 File "/mmdetection3d/tools/data_converter/kitti_data_utils.py", line 227, in map_func
    float(info) for info in lines[4].split(' ')[1:10]
IndexError: list index out of range

**Comment by ZCMax** [comment]
Your R0_rect annotations should include 3*4 = 12 numbers. It seems that you own training data annotations just include 3*3 numbers.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
