### ISSUE TITLE
visualization code

### ISSUE THREAD

**Issue by ChunmianLin** [open-mmlab/mmdetection3d#101]
**Describe the feature**
The script or code is required to visualize the validation and test result on image and LiDAR, like mayavi, open3d, etc. 

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].
It is intuitive that we observe the detection performance when testing the model, I think.

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.
Sorry, I don't have good idea. When reading other references, I envy so beautiful figures attached in the paper but don't know how to get them.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.
No, thanks! And the aim of this issue, is that I want to consult about the time you release the code. 
Thanks again for your great works!

**Comment by ZwwWayne** [comment]
Better visualization API will be released in the next month.
