### ISSUE TITLE
the result is bad that I train the fcos3d with nuscenes v1.0-mini

### ISSUE THREAD

**Issue by Will-yh** [open-mmlab/mmdetection3d#1011]
Hello mmdetection3d team,

I want to train fcos3d with nuscenes dataset, while the whole datasets is really huge, sometimes it is hard for me to download all the data. Therefore, I train the fcos3d with nuscenes v1.0-mini data. The following is the steps:

mmdetection3d version: release v0.17.1

1. I downloaded the data from nuscenes website:
![2021-10-25_14-16](https://user-images.githubusercontent.com/33858216/138643850-ca6cc659-77ca-4f1b-af62-f4410e7d03d5.png)
2. unzip the v1.0-mini.tgz
3. modify the v1.0-mini inside v1.0-mini to v1.0-trainval
4. symbolic link the datasets: ln -s v1.0-mini mmdetection3d/data
5. modify tools/create_data.py 
    elif args.dataset == 'nuscenes' and args.version != 'v1.0-mini':
        train_version = f'{args.version}-trainval'
        nuscenes_data_prep(
            root_path=args.root_path,
            info_prefix=args.extra_tag,
            version=train_version,
            dataset_name='NuScenesDataset',
            out_dir=args.out_dir,
            max_sweeps=args.max_sweeps)
        #test_version = f'{args.version}-test'
        #nuscenes_data_prep(
        #    root_path=args.root_path,
        #    info_prefix=args.extra_tag,
        #    version=test_version,
        #    dataset_name='NuScenesDataset',
        #    out_dir=args.out_dir,
        #    max_sweeps=args.max_sweeps)
6. Create the date with: python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --workers 20
7. the created folder as follow:
![2021-10-25_14-24](https://user-images.githubusercontent.com/33858216/138645403-a5166731-37ac-4170-9188-52cdfde6f3a8.png)
8. the trained model:
![2021-10-25_14-31](https://user-images.githubusercontent.com/33858216/138646559-643052f0-f48e-43e1-acbd-0dab5c2c4715.png)
9. test the model: python demo/mono_det_demo.py demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525.jpg demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525_mono3d.coco.json configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.py work_dirs/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d/latest.pth

   The result shows as below:
![n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525_pred](https://user-images.githubusercontent.com/33858216/138647020-52dde61e-de9b-4e16-8656-9fa8841464b3.png)
 Compare with the result of the demo, this result is really bad.

I'm wondering if the bad result is caused by the training datasets?

**Comment by Tai-Wang** [comment]
There is only one minor problem in your implementation: you can set --version to v1.0-mini to generate infos only for that mini-data version, but I guess this point won't affect your results.

I did not try to train the model with the mini version, but I guess it is possible that the limited data results in such bad performance. Someone has tried with 1/10 full dataset before and there was also a serious performance degradation. If you are interested in training models with a small dataset, you can try with KITTI, and the PRs #964 and #1014 for FCOS3D++ are ready to be merged into v1.0.0.dev0.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
