### ISSUE TITLE
Some questions about corner rotation to camera coordinate system

### ISSUE THREAD

**Issue by qfwysw** [open-mmlab/mmdetection3d#1012]
def rotation_3d_in_axis(points, angles, axis=0):
    """Rotate points in specific axis.
    Args:
        points (np.ndarray, shape=[N, point_size, 3]]):
        angles (np.ndarray, shape=[N]]):
        axis (int, optional): Axis to rotate at. Defaults to 0.
    Returns:
        np.ndarray: Rotated points.
    """
    # points: [N, point_size, 3]
    rot_sin = np.sin(angles)
    rot_cos = np.cos(angles)
    ones = np.ones_like(rot_cos)
    zeros = np.zeros_like(rot_cos)
    if axis == 1:
        rot_mat_T = np.stack([[rot_cos, zeros, -rot_sin], [zeros, ones, zeros],
                              [rot_sin, zeros, rot_cos]])
    elif axis == 2 or axis == -1:
        rot_mat_T = np.stack([[rot_cos, -rot_sin, zeros],
                              [rot_sin, rot_cos, zeros], [zeros, zeros, ones]])
    elif axis == 0:
        rot_mat_T = np.stack([[zeros, rot_cos, -rot_sin],
                              [zeros, rot_sin, rot_cos], [ones, zeros, zeros]])
    else:
        raise ValueError('axis should in range')

    return np.einsum('aij,jka->aik', points, rot_mat_T)

#####################################################
The question is that, I make a standard boxes in camera coordinate system(1, 8, 3). I want to rotate the box by the rotation y.
As I know, I can use the rotation matrix to time the corners. However, I get the different result by using the function. If I replace  np.einsum('aij,jka->aik', points, rot_mat_T) with points@rot_mat_T, I get the same result.

**Comment by ZCMax** [comment]
For you problems, we double check the code, we find that it indeed has some problems, the right code should be like this, and you will get the same results:
```
from pyquaternion import Quaternion
import numpy as np

def rotation_3d_in_axis(points, angles, axis=0):
    """Rotate points in specific axis.
    Args:
    points (np.ndarray, shape=[N, point_size, 3]]):
    angles (np.ndarray, shape=[N]]):
    axis (int, optional): Axis to rotate at. Defaults to 0.
    Returns:
    np.ndarray: Rotated points.
    """
    # points: [N, point_size, 3]
    rot_sin = np.sin(angles)
    rot_cos = np.cos(angles)
    ones = np.ones_like(rot_cos)
    zeros = np.zeros_like(rot_cos)
    if axis == 1:
        rot_mat_T = np.stack([[rot_cos, zeros, -rot_sin],
                              [zeros, ones, zeros],
                              [rot_sin, zeros, rot_cos]])
    elif axis == 2 or axis == -1:
        rot_mat_T = np.stack([[rot_cos, rot_sin, zeros],
                              [-rot_sin, rot_cos, zeros],
                              [zeros, zeros, ones]])
    elif axis == 0:
        rot_mat_T = np.stack([[ones, zeros, zeros],
                              [zeros, rot_cos, rot_sin],
                              [zeros, -rot_sin, rot_cos]])
    else:
        raise ValueError('axis should in range')
    print(rot_mat_T)
    return np.einsum('aij,jka->aik', points, rot_mat_T)

if __name__ == '__main__':
    angles = -1
    x = np.array([1.2, 1.8, 3.2]).reshape(3, 1)
    y = np.array([1.2, 1.8, 3.2]).reshape(1, 1, 3)
    rotation_y = Quaternion(axis=[0, 1, 0], radians=angles)
    a = np.matmul(rotation_y.rotation_matrix, x)
    print(rotation_y.inverse.rotation_matrix)
    print("*"*100)
    a1 = rotation_3d_in_axis(y, np.array(angles).reshape(-1), axis=1)
    print(a)
    print(a1)
```
1. The `rot_mat_T` actually represents the transpose of rotation matrix. For rotation matrix, the transpose equals to the inverse. 
2. When `axis=0` and `axis=2`, the original code of `rotation_3d_in_axis` is wrong.
3. About `np.einsum`, to get a better understanding of it, you can add `rot_mat = rot_mat_T.transpose(0, 1)`, and replace `np.einsum('aij,jka->aik', points, rot_mat_T)` to `np.einsum('aij,kja->aik', points, rot_mat_T)`, it should get the same results.
4. the code actually has been deprecated in our now developing branch, you can refer to the new version of the it in [here](https://github.com/open-mmlab/mmdetection3d/blob/bf4396ec1c3c0a78730bdcc850e346f261d4f1ba/mmdet3d/core/bbox/structures/utils.py#L28)
5. If you are still confused, just leave comments.

**Comment by ZCMax** [comment]
For master branch, 
`axis=2` will only be used when rotate box in LiDAR coordinates, and in master branch,  we follow the LiDAR coordinate system of SECOND original code which is left-handed, so there is no problem in the original code.
`axis=1` will only be used when rotate box in Camera coordinates, which is a right-handed coordinate.
`axis=0` is not used in our entire code, although it's indeed not right.

We refactor all the coordinates to be right-hand in v1.0.0.dev0 branch, so the code of `axis=2` should be modified like what I change above. 
For `Quaternion`, the default coordinate is right-handed, the default rotation direction should be an counter-clockwise.

Besides, here's a tutorial about the 3D rotation calculation in Chinese, https://zhuanlan.zhihu.com/p/183973440, and you can also find some other English doc. for reference if you don't know Chinese.

**Comment by qfwysw** [comment]
Thanks for your help. I can understand that in kitti, rotation_y is about the y axis, so we need to turn the vehicle clockwise to achieve the goal. The default direction of Quaternion is counterclockwise, so we need to reverse its conversion matrix. This rule is in camera coordinates Both the radar coordinate system and the radar coordinate system are applicable.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
