### ISSUE TITLE
CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by jacktkk** [open-mmlab/mmdetection3d#1020]
When I added os.environ['CUDA_VISIBLE_DEVICES']='1' (or any gpu id that is not 0) in train.py,
the code will always use cuda:0,
However, if I set CUDA_VISIBLE_DEVICES=1 in bash command, 
the code will use cuda:1

**Comment by ZCMax** [comment]
Did you put the os.environ['CUDA_VISIBLE_DEVICES']='1'  right after import os and before import torch? like this:
```
import os 
os.environ['CUDA_VISIBLE_DEVICES']='1'
import torch
```

**Comment by kt-nlpr** [comment]
Thanks, that solves my problem

**Comment by jacktkk** [comment]
Thx, that solves my question.
