### ISSUE TITLE
How open my pcd file without loss.

### ISSUE THREAD

**Issue by ggomac** [open-mmlab/mmdetection3d#1023]
When I run my pcd data to use ```tools/test.py``` and SECOND 3d-car model.
It show only a part of my pcd data. 
How can I show it without loss?

**Comment by ZCMax** [comment]
For sinlge .bin pcd file, you can run `demo.py` to show the whole pcd data. 
And if you want to use `tools/test.py`, you can try to change `pts_prefix='velodyne_reduced'` to `pts_prefix='velodyne' `in https://github.com/open-mmlab/mmdetection3d/blob/99ad831a8b04a7f5622c366d8e60745f92a62008/configs/_base_/datasets/kitti-3d-car.py

**Comment by ggomac** [comment]
Thank you for the reply!!
I try it and I still show a part of pcd data.
This document is attached with pictures for easy understanding.
https://docs.google.com/document/d/1DpHdUFAPTxKUJyavuIEx1RhOXkKpmkGjPllki9gZJcM/edit?usp=sharing
