### ISSUE TITLE
Update mmcv version in dockerfile

### ISSUE THREAD

**Issue by DeclK** [open-mmlab/mmdetection3d#1025]
Hi! Thanks for providing Dockerfile to install the project, it's been very helpful to me.
When I was building the dockerfile, I found that it needs mmcv version >= 1.3.13 to be compatible with other dependencies.
Here is part of the error message:
```
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 4, in <module>
    from mmdet3d.apis import inference_detector, init_model, show_result_meshlab
  File "/mmdetection3d/mmdet3d/__init__.py", line 5, in <module>
    import mmseg
  File "/opt/conda/lib/python3.7/site-packages/mmseg/__init__.py", line 59, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.3.8 is used but incompatible. Please install mmcv>=(1, 3, 13, 0, 0, 0), <=(1, 4, 0, 0, 0, 0).
```
So I changed mmcv version 1.3.8 to 1.3.13 in dockerfile, and rebuilt it. Though some small warnings were given, they seemed not to be very harmful.
Looking forward to your official update

**Comment by iyuner** [comment]
Thank you! I also met the problem, and after changing, it works :)

**Comment by wHao-Wu** [comment]
@DeclK 
Thanks for your feedback. We will fix the problem as soon as possible.
