### ISSUE TITLE
pip install mmdet3d fails

### ISSUE THREAD

**Issue by iyuner** [open-mmlab/mmdetection3d#1027]
**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
`pip install mmdet3d` fails

**Reproduction**
I tried the dockerfile below, it works. 
```
ARG PYTORCH="1.6.0"
ARG CUDA="10.1"
ARG CUDNN="7"

FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel

ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"

RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install MMCV, MMDetection and MMSegmentation
RUN pip install mmcv-full==1.3.13 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html
RUN pip install mmdet==2.17.0
RUN pip install mmsegmentation==0.18.0

# Install MMDetection3D
RUN conda clean --all
RUN git clone https://github.com/open-mmlab/mmdetection3d.git /mmdetection3d
WORKDIR /mmdetection3d
ENV FORCE_CUDA="1"
RUN pip install -r requirements/build.txt
RUN pip install --no-cache-dir -e .
```
However, my final installation goal is not to use docker file (I use it to quickly check what combination of different modules version works in the beginning), and don't clone the mmdet3d repo, but import it instead, so I want to use `pip install mmdet3d`. (I see you also support this according to your changelog from v0.6.0 (20/9/2020)). Hence I changed the last part of "Install MMDetection3D" from 
```
RUN conda clean --all
RUN git clone https://github.com/open-mmlab/mmdetection3d.git /mmdetection3d
WORKDIR /mmdetection3d
ENV FORCE_CUDA="1"
RUN pip install -r requirements/build.txt
RUN pip install --no-cache-dir -e .
```
to 
```
ENV FORCE_CUDA="1"
RUN pip install mmdet3d==0.17.2
```
but it doesn't work. **I don't see why it happens.** The `git clone` the today's master branch is the same version of `0.17.2`. Do you have an idea?

The part of the error message is 
```
 ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1lynz5zt/mmdet3d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1lynz5zt/mmdet3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-wvf3izgz
       cwd: /tmp/pip-install-1lynz5zt/mmdet3d/
  Complete output (668 lines):
  No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
...
...
...
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  /tmp/pip-install-1lynz5zt/mmdet3d/mmdet3d/ops/spconv/src/reordering.cc:15:10: fatal error: spconv/reordering.h: No such file or directory
   #include <spconv/reordering.h>
            ^~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
...
/tmp/pip-install-1lynz5zt/mmdet3d/mmdet3d/ops/spconv/src/indice.cc:15:10: fatal error: spconv/geometry.h: No such file or directory
   #include <spconv/geometry.h>
            ^~~~~~~~~~~~~~~~~~~
...
/tmp/pip-install-1lynz5zt/mmdet3d/mmdet3d/ops/spconv/src/maxpool.cc:15:10: fatal error: spconv/maxpool.h: No such file or directory
   #include <spconv/maxpool.h>
            ^~~~~~~~~~~~~~~~~~
...
  compilation terminated.
#include <spconv/fused_spconv_ops.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
...
...
...
File "/opt/conda/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
        raise RuntimeError(message)
    RuntimeError: Error compiling objects for extension
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1lynz5zt/mmdet3d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1lynz5zt/mmdet3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2jm06zi8/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.7m/mmdet3d Check the logs for full command output.
```
Do you have an idea how I can install it without cloning it? Thanks!

**Comment by Tai-Wang** [comment]
For your error message, it seems no CUDA runtime is found. Could you please check your cuda environment (both driver and other related environments)? Please also re-describe your issue with the corresponding template (Following the instructions will provide more information to help us locate your problems).

**Comment by eyabesbes** [comment]
> For your error message, it seems no CUDA runtime is found. Could you please check your cuda environment (both driver and other related environments)? Please also re-describe your issue with the corresponding template (Following the instructions will provide more information to help us locate your problems).

Hi,
I have also been facing the same problem.

I have already installed CUDA 
``
Wed Apr 17 03:16:14 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.120                Driver Version: 537.58       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650 ...    On  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8               5W /  40W |   1786MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     23522      C   /python3.7                                N/A      |
+---------------------------------------------------------------------------------------+
```
and also when I run
```
nvcc --version
```
I get this message
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
```
but I still the same error mentioned above do you have any idea how to resolve it ?

**Comment by eyabesbes** [comment]
> For your error message, it seems no CUDA runtime is found. Could you please check your cuda environment (both driver and other related environments)? Please also re-describe your issue with the corresponding template (Following the instructions will provide more information to help us locate your problems).

Hi,
I have also been facing the same problem.
I have already installed CUDA 

```
Wed Apr 17 03:16:14 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.120                Driver Version: 537.58       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650 ...    On  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8               5W /  40W |   1786MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     23522      C   /python3.7                                N/A      |
+---------------------------------------------------------------------------------------+
```

and also when I run

``
nvcc --version
``

I get this message


``
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
``

but I still the same error mentioned above do you have any idea how to resolve it ?
