### ISSUE TITLE
How to test the smoke model on the Kitti dataset ？

### ISSUE THREAD

**Issue by 24werewolf** [open-mmlab/mmdetection3d#1030]
How to run the smoke pre-trained model on the KiTTi dataset? 

I run the following script
'''
python demo/mono_det_demo.py  /demo/data/nuscenes/n008-2018-08-27-11-48-51-0400__CAM_BACK__1535385092137558.jpg  /demo/data/nuscenes/n008-2018-08-27-11-48-51-0400__CAM_BACK__1535385092137558mono3d.coco.json   configs/smoke/smoke_dla34_pytorch_dlaneck_gn-all_8x4_6x_kitti-mono3d.py checkpoints/smoke_dla34_pytorch_dlaneck_gn-all_8x4_6x_kitti-mono3d_20210929_015553-d46d9bb0.pth --out-dir ./smoke_result
'''
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [256, 64, 3, 3], but got 3-dimensional input of size [64, 96, 320] instead

**Comment by ZCMax** [comment]
Hi! Can you show the detailed error information?

**Comment by ZCMax** [comment]
We will fix the issue in PR #1029

**Comment by ZCMax** [comment]
You can change your code following the PR, or wait until the PR is merged into v1.0.0.dev0 branch.

**Comment by ZCMax** [comment]
Beside, we only provide the checkpoints of SMOKE trained on KITTI, and training SMOKE on Nuscenes is not officially tried ( experimented).

**Comment by ZCMax** [comment]
If you want to run demo on kitti datasets:
you need add two file under `/demo/data/kitti`, one is the image (e.g. `000008.png`) you want to test, the other should be the json file (e.g. `kitti_000008_mono3d.coco.json`) to provide image info. Here's an example:

kitti_000008_mono3d.coco.json:
`{"images": [{"file_name": "training/image_2/000008.png", "cam_intrinsic": [[721.5377, 0.0, 609.5593, 44.85728], [0.0, 721.5377, 172.854, 0.2163791], [0.0, 0.0, 1.0, 0.002745884], [0.0, 0.0, 0.0, 1.0]]}]}
`

Then run the command:
`python demo/mono_det_demo.py /demo/data/kitti/000008.png /demo/data/kitti/kitti_000008_mono3d.coco.json configs/smoke/smoke_dla34_pytorch_dlaneck_gn-all_8x4_6x_kitti-mono3d.py checkpoints/smoke_dla34_pytorch_dlaneck_gn-all_8x4_6x_kitti-mono3d_20210929_015553-d46d9bb0.pth --out-dir ./smoke_result`

**Comment by 24werewolf** [comment]
it is work, thank you very much!

**Comment by hunagjingwei** [comment]
> 

how to generate the kitti_000008_mono3d.coco.json? The kitti dataset only have .txt file
