### ISSUE TITLE
how to visualize using open3d inside docker development environment in vscode?

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmdetection3d#1033]
I am running this script inside docker developemnt environment: https://github.com/open-mmlab/mmdetection3d/blob/master/docs/getting_started.md#synchronous-interface

Getting this error:
```bash
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW
```

How can I visualize the result in vscode development docker?

**Comment by filaPro** [comment]
I think the only option for visualization inside `docker` without access to display is the **offline** visualization for [here](https://mmdetection3d.readthedocs.io/en/latest/useful_tools.html#visualization).

**Comment by ZCMax** [comment]
Maybe you can follow this [issue](https://github.com/isl-org/Open3D/issues/4174) to check whether there's a solution.
