### ISSUE TITLE
Will CUDA10.0 be supported by MMCV and mmcv-full?

### ISSUE THREAD

**Issue by fanxiaochen-123** [open-mmlab/mmdetection3d#1047]
I used VirtualEnv to create a virtual environment, CUDA 10.0, install torch PIP instead of Conda.
He reported the following error:
 from mmcv.runner import (get_dist_info, init_dist, load_checkpoint,
ImportError: cannot import name 'wrap_fp16_model'
Is this still a problem with MMCV or MMCV-full?

**Comment by ZCMax** [comment]
mmcv supports cuda10.0, what's your mmcv version?

**Comment by fanxiaochen-123** [comment]
@ZCMax Hello, at first, the MMCV version was 1.3.16 according to the installation requirements, then MMCV1.0.5 was installed according to the error prompt, and MMCV-full was also changed to 1.0.5, but the same error is reported.

**Comment by ZCMax** [comment]
From mmdetection3d v0.6.0, we did not support mmcv-full 1.0.5, whats your error while using mmcv 1.3.16?

**Comment by fanxiaochen-123** [comment]
@ZCMax ，My error with MMCV1.3.16 is still "WARp_fp_16_model"，Either MMDetection or MMDetection3D。

**Comment by zwl8979** [comment]
你好，请问我的cuda=10.0, torchvision=0.5.0, mmdetection3D默认下载的是master版本，mmcls=0.24.1, mmcv-ful1.7.0, mmdet=2.25.3, mmsegmentation=0.29.1, 会显示ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory, 更换mmcv-full=1.2.1之后，会显示不兼容，该怎么处理呢？
