### ISSUE TITLE
problem of custom dataset(KITTI format) during evaluation

### ISSUE THREAD

**Issue by who1129** [open-mmlab/mmdetection3d#1051]
I am going to training about 3DSSD ‘car’ class by converting my custom data into KITTI format. 
The coordinates of the KITTI point cloud dataset are known in the camera coordinate system, but my custom data is in the Lidar coordinate system.
Therefore, the calibration parameters of the custom dataset were converted into a unit matrix.
However, in this case, there seems to be a problem with the BEV calculation when evaluating.
Is there a slick way other than converting custom data to KITTI camera coordinates to create a dataset?

**Comment by ZCMax** [comment]
@who1129 Sorry for the late reply, for now we recommend you to convert your data into KITTI coordinates for convenience. Or you can rewrite a Dataset Class for your own datasets.
