### ISSUE TITLE
Issue with extras_require while running setup.py

### ISSUE THREAD

**Issue by gayathri81** [open-mmlab/mmdetection3d#1052]
Getting below error while running the below command to setup mmdetection3d.
pip install -v -e .

error in mmdet3d setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

In setup.py extras_require field in setup is given like this.

extras_require={
            'all': parse_requirements('requirements.txt'),
            'tests': parse_requirements('requirements/tests.txt'),
            'build': parse_requirements('requirements/build.txt'),
            'optional': parse_requirements('requirements/optional.txt'),
        },
Can you please help me understand the issue and how to fix this.

**Comment by Tai-Wang** [comment]
Please follow the issue template for installation/reimplementation to re-describe your problem.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
