### ISSUE TITLE
Clean unnecessary custom_imports in entrypoints

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmdetection3d#1058]
As MMCV already supports custom_imports since PR open-mmlab/mmcv#606. The entrypoints in MMDet no longer need to handle the custom_imports manually. The codes like below should be cleaned.

https://github.com/open-mmlab/mmdetection3d/blob/0cd000bf5b04057234d67af476118984bc29ed10/tools/train.py#L101-L103

Similar issues are in MMDet as mentioned in open-mmlab/mmdetection#6543 and should also be resolved in MMDet3D.

**Comment by ZCMax** [comment]
#1068
