### ISSUE TITLE
Test KITTI-trained PGD model on nuScenes

### ISSUE THREAD

**Issue by Yibin122** [open-mmlab/mmdetection3d#1062]
score_thr = 0.9:
![n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525_pred](https://user-images.githubusercontent.com/56641930/142562065-204e2fae-63d0-4c87-8e2b-b069800532e5.png)

I checked the class labels of those FP predictions and there are not only pedestrians but also cars.
Then I checked the scores and found all of them are > 1. That's why increasing the score threshold does not suppress the bad results.

Why would the score value be greater than 1 (even after Sigmoid)?

**Comment by Tai-Wang** [comment]
That's because PGD involves a strong uncertainty score on KITTI to suppress those predictions with inaccurate depth estimations. Please refer to the discussion in issue #1024 for more details.

**Comment by Tai-Wang** [comment]
Close due to inactivity and duplication.
