### ISSUE TITLE
Question about coverted Waymo Dataset and Custom Dataset format

### ISSUE THREAD

**Issue by hz3014** [open-mmlab/mmdetection3d#1071]
Hi, I am trying to combine Waymo Dataset with my Custom Dataset(Kitti format). My understanding is that Training will work if Custom Dataset visualize perfectly in Kitti Visualizer (https://github.com/kuixu/kitti_object_vis).

I have visualize my custom dataset which bounding box and pointcloud matches. However, When i visualize the converted Waymo dataset, it seems All bounding box is 2m under the pointcloud and 1m behind the pointcloud.

Just wonder if you have different dataloader settings for Kitti and Waymo training? OR is it expected behavior? When I make custom dataset should I also add offset to the labels?

![snapshot](https://user-images.githubusercontent.com/35603799/143154742-7a0d6e57-64f5-4651-a223-da9be42c48c8.png)
![snapshot2](https://user-images.githubusercontent.com/35603799/143154856-7a6cffe2-8b0b-4e87-86a4-354aee7beaf3.png)

**Comment by Tai-Wang** [comment]
It's abnormal. We should convert Waymo data to KITTI format rigorously and the following networks are all the same. Maybe you can try the original KITTI dataset. I guess there might be also a gap/offset between your custom dataset and KITTI (can be a different definition of coordinate systems.)

**Comment by hz3014** [comment]
> It's abnormal. We should convert Waymo data to KITTI format rigorously and the following networks are all the same. Maybe you can try the original KITTI dataset. I guess there might be also a gap/offset between your custom dataset and KITTI (can be a different definition of coordinate systems.)

Thanks for your reply, do you use any kitti visualizer? Could you tell me which visualizer that you used?
I indeed used your Waymo to kitti conversion code but took some feature away and leave point cloud in (x, y, z, intensity) format for visualization.
By the way, i have visualized Kitti Dataset too. KITTI and my custom dataset align perfectly in the previously mentioned visualizer. It's just the Waymo seems have the offset.

**Comment by moon5ye** [comment]
I face the same problem. The visualizaion of converted waymo dataset looks wired.

The bounding boxes are under point cloud.

At first, I thought it was the problem of visulization tools.

However, the visualization of original kitti is correct.

I am wondering whether you solved this problem?

@hz3014 @Tai-Wang

**Comment by DurbinLiu** [comment]
Hi, I faced the same problem, did u find out the reason and how to solve it? @moon5ye @hz3014
