### ISSUE TITLE
 previous version

### ISSUE THREAD

**Issue by chenshi3** [open-mmlab/mmdetection3d#1079]
How can I install previous version? like 0.15.0

**Comment by ZCMax** [comment]
@chenshi3 Hai, you can use `git clone -b v0.15.0 git@github.com:open-mmlab/mmdetection3d.git`

**Comment by wHao-Wu** [comment]
Hi, @chenshi3 
Please remind that the version of `mmcv` and `mmdetection` should be consistent with the previous version of `mmdetection3d`.
