### ISSUE TITLE
Transformation from lidar to image

### ISSUE THREAD

**Issue by Jiayi719** [open-mmlab/mmdetection3d#1084]
Hello, I wonder why we should do this when computing transformation from lidar to image.
`lidar2cam_t = cam_info['sensor2lidar_translation'] @ lidar2cam_r.T`
That is I think it should be
`lidar2cam_t = cam_info['sensor2lidar_translation'] `
[https://github.com/open-mmlab/mmdetection3d/blob/ed81c6cc326a33f927d4455c219bb7715591b08b/mmdet3d/datasets/nuscenes_dataset.py#L226-L235](url)
I think I have some mistakes. But someone can give me a clear explaination? Than you.

**Comment by Tai-Wang** [comment]
I agree with you. It seems like a bug and we will fix it ASAP. BTW, because this piece of code is used when the modality is "use_camera=True", it does not influence any models or results currently.

**Comment by wHao-Wu** [comment]
@Jiayi719 
Sorry for the late reply.
We found that the original transformation is right. We can draw this conclusion by visualizing the NuScenes dataset under two different transformations as below:

Under changed transformation:
![n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951 pcd_gt](https://user-images.githubusercontent.com/79644370/152716783-acf13024-bb92-4067-834e-351ff8b83313.png)
![n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951 pcd_gt](https://user-images.githubusercontent.com/79644370/152716803-dd8f90b2-f553-4c16-99cb-4739d5a75176.png)
![n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951 pcd_gt](https://user-images.githubusercontent.com/79644370/152716820-cf051e3d-b0cf-448a-a0c3-7bdc318dd1a3.png)

Under original transformation:
![n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951 pcd_gt](https://user-images.githubusercontent.com/79644370/152716862-7b46288f-1d3a-437d-9403-a7447a5df340.png)
![n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951 pcd_gt](https://user-images.githubusercontent.com/79644370/152716868-a96bb003-79f5-42af-b3f1-8f2dde2f53b2.png)
![n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951 pcd_gt](https://user-images.githubusercontent.com/79644370/152716969-c5c68f48-cd1b-4b0e-a3a1-b70c99364884.png)

From the visualization, we can find that the changed transformation will deviate the bboxes from the detection targets.

**Comment by Jiayi719** [comment]
Thanks for your really rigorous verification. I think I had some mistakes. Thanks again.

**Comment by YTEP-ZHI** [comment]
@wHao-Wu What is the purpose to multiply the rotation matrix (lidar2cam_r.T) instead of directly using translation vector?
