### ISSUE TITLE
When will release FCOS3D pretrain weights?

### ISSUE THREAD

**Issue by Senwang98** [open-mmlab/mmdetection3d#1090]
Hi, 
Have you released FCOS3D pretrained weights kiiti? I can't find the corresponding weights file.
BTW, FCOS3D is superior than monoflex and monodle?
Wishing for your reply!

**Comment by ZCMax** [comment]
@Senwang98 We release PGD weights on kitti datasets in v1.0.0.dev0 branch, PGD is also called FCOS3D++, the performace of PGD on kitti stays tuned, the current performance is inferior to MonoFlex. Besides, MonoFlex based on MMDetection3D will be released soon.

**Comment by Senwang98** [comment]
@ZCMax 
Okay and thanks for your reply.
Wishing for monoflex mmdet3d version!!
