### ISSUE TITLE
Support spconv 2.x?

### ISSUE THREAD

**Issue by BB88Lee** [open-mmlab/mmdetection3d#1091]
Is support for version 2.x of spconv in your short-term plans?

**Comment by Tai-Wang** [comment]
We will consider updating it after migrating all the ops to mmcv (can be expected finished in 2 weeks).

**Comment by Tai-Wang** [comment]
The spconv op has been migrated to mmcv via its [PR #1581](https://github.com/open-mmlab/mmcv/pull/1581/files). We will begin refining it and study the usage of spconv 2.x in the following weeks.

**Comment by lemondante** [comment]
> The spconv op has been migrated to mmcv via its [PR #1581](https://github.com/open-mmlab/mmcv/pull/1581/files). We will begin to refine it and study the usage of spconv 2.x in the following weeks.

Is support spconv 2.x possible? Now sparse_conv in mmcv may allocate too much memory due to large spatial shape. I think migrate the overwrite code and add spconv to optional requirement  is a good way.
