### ISSUE TITLE
How to inference the model provided by nuimages

### ISSUE THREAD

**Issue by MintGreen-hub** [open-mmlab/mmdetection3d#1097]
It seems that the inference in api not matches with the model provided by nuimages.
So I  wonder how to  inference the model provided by nuimages?
Thanks so much !

**Comment by Tai-Wang** [comment]
It follows the typical way in mmdet to run both training and inference on nuimages. Please refer to the [documentation](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html).
