### ISSUE TITLE
Background sampling

### ISSUE THREAD

**Issue by Code-Gratefully** [open-mmlab/mmdetection3d#1101]
In CenterPoint original paper, the authors cited Faster R-CNN on sampling 128 boxes in 1:1 positive to negative ratio.  May I ask if this is implemented in the current version of CenterPoint in mmDetection3D?  I am trying to find the code but I cannot find it.  If this is not implemented, may I ask if there is any similar piece of code that comes into your mind that I can start with, to add this feature to the CenterPoint in mmdetection3D repo, please?

![image](https://user-images.githubusercontent.com/10594624/144941499-aacd59e3-3853-4b2e-9ef9-47f10f4e4569.png)

**Comment by Code-Gratefully** [comment]
May I ask if the orignal authors adding CenterPoint to the repo can kindly comment @yinchimaoliang @zhezhao1989

**Comment by yinchimaoliang** [comment]
For the time being, two stage version of `CenterPoint` is not supported. If you want to implement the above features, you may have to implement the second stage of `CenterPoint` first. FYI, you can add the second stage head under `roi_heads` and extend the `centerpoint.py` under the `detectors` to two stages. As for your question, you can refer to the related samplers in `mmdetection` project.

**Comment by Code-Gratefully** [comment]
@yinchimaoliang Thank you for getting back to me, Yinhao.  Are you referring to the db_sampler that add samples onto the scene?  So are you suggesting us to also store the background points and add them randomly to the scene?  

Also, for the current implementation, do you mean we do not backprop with any negative samples?  

Thank you so much!

**Comment by yinchimaoliang** [comment]
> 
@Code-Gratefully You are welcome.
1. db_sampler is a kind of augmentation method, I'm afraid that's not what I was refering to. I was suggesting that you can refer to the samplers in `mmdetection` project like `random_sampler` to help you to implement the functions you mentioned before .
2. Since we have not implemented two stage version of CenterPoint, we do not backprop with any negative samples.

**Comment by yinchimaoliang** [comment]
> For the time being, two stage version of `CenterPoint` is not supported. If you want to implement the above features, you may have to implement the second stage of `CenterPoint` first. FYI, you can add the second stage head under `roi_heads` and extend the `centerpoint.py` under the `detectors` to two stages. As for your question, you can refer to the related samplers in `mmdetection` project.


In addition, `random_sampler` is for reference only, it is used for sample gt, you need to use it to sample predictions.

**Comment by Code-Gratefully** [comment]
Thanks for the detailed comment, I will look into those.
