### ISSUE TITLE
ERROR on compiling for  scatter_points_cuda.o

### ISSUE THREAD

**Issue by yrj88351** [open-mmlab/mmdetection3d#1105]
Hi,
I meet an error when i setup environment.  I want to build mmdet3d from source.

torch version:1.4.0
my cmd:
python setup.py build 

-c mmdet3d/ops/voxel/src/scatter_points_cuda.cu -o build/temp.linux-x86_64-3.7/mmdet3d/ops/voxel/src/scatter_points_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=voxel_layer -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_75,code=sm_75 -std=c++11

......

mmdet3d/ops/voxel/src/scatter_points_cuda.cu(207): error: more than one instance of constructor "c10::ArrayRef<T>::ArrayRef [with T=at::Tensor]" matches the argument list:
            function "c10::ArrayRef<T>::ArrayRef(const T *, size_t) [with T=at::Tensor]"
            function "c10::ArrayRef<T>::ArrayRef(const T *, const T *) [with T=at::Tensor]"
            argument types are: (int, int)

**Comment by ZCMax** [comment]
Please run python `mmdet3d/utils/collect_env.py` to collect necessary environment infomation.

**Comment by Hby907634225** [comment]
I have the same problem.

**Comment by yrj88351** [comment]
sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce RTX 2080 SUPER
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.0, V10.0.130
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.4.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_50,code=compute_50
  - CuDNN 7.6.5
    - Built with CuDNN 7.6
  - Magma 2.5.0
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS=-fvisibility-inlines-hidden -std=c++11 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/conda-bld/pytorch_1584364664130/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/include -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1584364664130/work=/usr/local/src/conda/pytorch-1.4.0 -fdebug-prefix-map=/opt/conda/conda-bld/pytorch_1584364664130/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place=/usr/local/src/conda-prefix -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.2.1
OpenCV: 4.2.0
MMCV: 1.4.0
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.0
MMDetection: 2.19.0
MMSegmentation: 0.19.0
MMDetection3D: 0.17.2+f95d1e5

**Comment by yrj88351** [comment]
> Please run python `mmdet3d/utils/collect_env.py` to collect necessary environment infomation.
@ZCMax 

It seems not works for me .
i first try
`python mmdet3d/utils/collect_env.py`
then
`python setup.py build `

Do i miss somethings ?

**Comment by yrj88351** [comment]
> I have the same problem.

Hello, Have you solved it now ?

**Comment by yrj88351** [comment]
> > Please run python `mmdet3d/utils/collect_env.py` to collect necessary environment infomation.
> > @ZCMax
> 
> It seems not works for me . i first try `python mmdet3d/utils/collect_env.py` then `python setup.py build `
> 
> Do i miss somethings ?

BTW, 
i build the 
mmcv, mmdet, mmseg 
all by 
`python setup.py build`

**Comment by ZCMax** [comment]
Please refer to #790, it may caused by your GCC version.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
