### ISSUE TITLE
DATASET PREPARATION: about Waymo dataset split

### ISSUE THREAD

**Issue by xxlbigbrother** [open-mmlab/mmdetection3d#1106]
![image](https://user-images.githubusercontent.com/42771087/145588623-6386cd3c-2d0e-4799-a227-641b422a7f5c.png)

I find the link to download Waymo data split can't open, can you share the train.txt、val.txt and test.txt by other ways?
Thanks!

**Comment by ZCMax** [comment]
This link can be accessed normally, a temporary baidu netdisk:

link: https://pan.baidu.com/s/17erw7RC2gWBLHQ4YIaOGGQ
password: w1u1

**Comment by xxlbigbrother** [comment]
> This link can be accessed normally, a temporary baidu netdisk:
> 
> link: https://pan.baidu.com/s/17erw7RC2gWBLHQ4YIaOGGQ password: w1u1

thanks! I have got  files through this link.
