### ISSUE TITLE
error: command 'g++' failed with exit status 1 with the last step pip install -v -e .  # or "python setup.py develop"

### ISSUE THREAD

**Issue by pkudba** [open-mmlab/mmdetection3d#1108]
I strictly follow the getting_started.md, with cuda 10.1, pytorch 1.5.0, however there is always the g++ error said no some .o file, but i think there is no wrong operation with my compiling process:
    g++: error: /home/mm/new/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/all.o: No such file or directory
    g++: error: /home/mm/new/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering.o: No such file or directory
    g++: error: /home/mm/new/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/reordering_cuda.o: No such file or directory
    g++: error: /home/mm/new/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice.o: No such file or directory
    g++: error: /home/]mm/new/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice_cuda.o: No such file or directory
    g++: error: /home/mm/new/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool.o: No such file or directory
    g++: error: /home/mm/new/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/maxpool_cuda.o: No such file or directory
    error: command 'g++' failed with exit status 1
ERROR: Command errored out with exit status 1: /home/pkudba/.conda/envs/new_open-mmlab/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pkudba/mm/new/mmdetection3d/setup.py'"'"'; __file__='"'"'/home/pkudba/mm/new/mmdetection3d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by ZCMax** [comment]
I think you may need to rebuild MMDetection3D:
```
pip uninstall mmdet3d
rm -rf ./build
find . -name "*.so" | xargs rm
```

**Comment by pkudba** [comment]
> I think you may need to rebuild MMDetection3D:
> 
> ```
> pip uninstall mmdet3d
> rm -rf ./build
> find . -name "*.so" | xargs rm
> ```

thank you, but actually my problem is that i can't successfully install mmdet3d(the last compiling step failed), so there is nothing for me to  pip uninstall...

**Comment by ZCMax** [comment]
Sorry, could you please run python `mmdet3d/utils/collect_env.py` to collect necessary environment infomation?

**Comment by Tai-Wang** [comment]
Close due to inactivity.
