### ISSUE TITLE
Website in chinese even when pointing to "en"

### ISSUE THREAD

**Issue by scrouzet** [open-mmlab/mmdetection3d#1128]
**Describe the bug**
When going to https://mmdetection3d.readthedocs.io/en/latest/, which points toward "en", most of the text is still in Chinese

**Reproduction**
1. What command or script did you run?
Just go to https://mmdetection3d.readthedocs.io/en/latest/, reproduced by my and another person from a different computer. Reproduced from Firefox and Chromium.

**Comment by Tai-Wang** [comment]
We have PR #1121 ready to merge to fix this problem. Sorry for the inconvenience.
