### ISSUE TITLE
Questions about the data augmentation of MVX-Net

### ISSUE THREAD

**Issue by lmomoy** [open-mmlab/mmdetection3d#1131]
When the point cloud is augmented, how is the corresponding RGB image augmented, can you tell me where the corresponding code is?

**Comment by ZCMax** [comment]
For example, a [`RandomFlip3D` ](https://github.com/open-mmlab/mmdetection3d/blob/92d5a87e97b058621fa55a6f073a287e5ecd1a27/configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py#L153) data augmentation pipeline is used while training, you can find the code [here](https://github.com/open-mmlab/mmdetection3d/blob/92d5a87e97b058621fa55a6f073a287e5ecd1a27/mmdet3d/datasets/pipelines/transforms_3d.py#L67), it will flip points, 3D bboxes and 2D images and bboxes at the same time.

**Comment by lmomoy** [comment]
> For example, a [`RandomFlip3D` ](https://github.com/open-mmlab/mmdetection3d/blob/92d5a87e97b058621fa55a6f073a287e5ecd1a27/configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py#L153) data augmentation pipeline is used while training, you can find the code [here](https://github.com/open-mmlab/mmdetection3d/blob/92d5a87e97b058621fa55a6f073a287e5ecd1a27/mmdet3d/datasets/pipelines/transforms_3d.py#L67), it will flip points, 3D bboxes and 2D images and bboxes at the same time.

Thanks for your answer, but how about GlobalRotScaleTrans? It seems that doesn't process 2D images and points at the same time.

**Comment by ZCMax** [comment]
For `GlobalRotScale` and `Resize` in pipeline, 2D and 3D data augmentation are done independently.

**Comment by lmomoy** [comment]
> For `GlobalRotScale` and `Resize` in pipeline, 2D and 3D data augmentation are done independently.

Could you tell me where they are specifically?

**Comment by ZCMax** [comment]
`GlobalRotScale` is in [pipelines/transforms_3d.py](https://github.com/open-mmlab/mmdetection3d/blob/92d5a87e97b058621fa55a6f073a287e5ecd1a27/mmdet3d/datasets/pipelines/transforms_3d.py#L511), `Resize` is directly used from [mmdet package](https://github.com/open-mmlab/mmdetection/blob/df212e7505e1004d82e6882eeb9466a2156972fb/mmdet/datasets/pipelines/transforms.py#L30)

**Comment by FANGZHENGFA** [comment]
Could you tell me where the MOCA(Multi-modality cut and paste) code is?

**Comment by Tai-Wang** [comment]
The final conversation is a duplicated version of #1143 . Close this issue because the original problem is resolved primarily.
