### ISSUE TITLE
Photo context for visualization of LIDAR predictions in nuscenes

### ISSUE THREAD

**Issue by scrouzet** [open-mmlab/mmdetection3d#1133]
Is there any implemented procedure to visualize the predictions made by a LIDAR model trained on nuscenes with photographic context?

I've succesfully used `./tools/test.py` `--show` option or `tools/misc/visualize_results.py` that allows to generate appropriate .obj files (that I can visualize with Meshlab):
![B_model-A_with_sep_conv](https://user-images.githubusercontent.com/432568/147083775-c85d7fb2-36fc-4dab-9621-a46c5cacdc16.png)

But I would be looking for something that allows to rather do something like this (less exhaustive, but easier to get an insight about how well the model is performing):
![image](https://user-images.githubusercontent.com/432568/147083653-19f5a01c-244f-4203-a527-0752afc5533c.png)

Thanks in advance for your help!

**Comment by ZCMax** [comment]
Do you mean you want to visualize the 3d bboxes generated by LiDAR model on 2D images?

**Comment by scrouzet** [comment]
Yes, I'd like to produce exactly the type of image that I copied above, when you have a picture and you see how 3D boxes are predicted. I understand this is limited but it's so much easier to communicate to other people, to be able to show how good/bad is a model.

**Comment by ZCMax** [comment]
Actually, for now, we support  showing 2D images with 3D bounding boxes projected onto them only for datasets ground truth visualization, and you can see [here](https://mmdetection3d.readthedocs.io/en/latest/useful_tools.html#visualization) for details.  The feature you mentioned is not supported yet, but it would be supported in a short term. For now, you can refer to our code `browse_dataset.py` to modify the `visualize_results.py`  to achieve it.

**Comment by scrouzet** [comment]
Thanks for the answer. I'll try that then.
