### ISSUE TITLE
Export Model to Standard PyTorch Network Format

### ISSUE THREAD

**Issue by stanleyshly** [open-mmlab/mmdetection3d#1136]
While working with mmdetection3d, I wanted to view the model in a standard pytorch model format like this since it helps me visualize the data flow eaier:
```
class VanillaPytorchModel(torch.nn.Module):
    def __init__(self, input_dimension, output_dimension):
        super(VanillaPytorchModel, self).__init__()
        self.linear1 = torch.nn.Linear(input_dimension, output_dimension)
    def forward(self, x):
        h_relu = self.linear1(x).clamp(min=0)
        return y_pred
```
However, within, mmdetection3d, models seems to be intialized through builder.py, which, in the example of an object detector network, calls DETECTORS.build. However, inside all of this, I can not find an easy way to "dump" the model to the format above, which would make models easier to read and understand, and make models developed and configured with mmdetection3d easier to reuse with other frameworks like PyTorch lightning.

I'm not sure if either is actually a way to dump models to a standard PyTorch format, but I think this feature would make mmdetection3d more flexible to use.

**Comment by ZCMax** [comment]
I'm sorry that this feature is now not supported in mmdetection3d. In fact, we will consider whether to support the feature in mmcv.  Beside, a PR is welcomed for supporting this feature.

**Comment by stanleyshly** [comment]
I see. I should I create an issue in the mmcv repo? Also, how would you recommend to start to implement this feature, given that I can't see any straightforward way to export in a standard network format.

**Comment by ZCMax** [comment]
From my opinion, it's really hard to export model to the standard pytorch network format by a conversion script, maybe you need to rewrite pytorch network format by yourself, and if you want to to know the data flow of MMDetection3D, for now, only an official Chinese article is provided to tell the details of data flow in MMDetection (not MMDetection3D, but they are quite similar) for reference.

**Comment by stanleyshly** [comment]
Oh I see, if that's the case I guess I'll have to leave it up to you guys to implement that feature, I'm not really sure I understand how the whole MM ecosystem works well enough to do that. Thank you for the help and advice though, I know you guys are really busy with a whole lot of refactoring right now.
