### ISSUE TITLE
Feeding return_loss parameter to model during ONNX export 

### ISSUE THREAD

**Issue by OrcunCanDeniz** [open-mmlab/mmdetection3d#1139]
I've been trying to export "hv_second_secfpn_kitti.py" model to ONNX by refering to a [mmdetection script](https://github.com/open-mmlab/mmdetection/blob/master/tools/deployment/pytorch2onnx.py). 
Ran inference as below to get meta info easily:
` outs = inference_detector(model, data_path)`
`boxes = outs[0]`
`meta = outs[1]`
`one_pcd = meta['points']`
`img_meta_list = meta['img_metas'] `

Using a partial object to replace forward() function of the model, [ref](https://github.com/open-mmlab/mmdetection/blob/df212e7505e1004d82e6882eeb9466a2156972fb/tools/deployment/pytorch2onnx.py#L59)
`model.forward = functools.partial(model.forward,
        img_metas=img_meta_list,
        points = one_pcd,
        return_loss=False
        )`

` torch.onnx.export(
      model,
      one_pcd,
      output_file,
      input_names=['input_features'],
      output_names= output_names,
      export_params=True,
      keep_initializers_as_inputs=True,
      do_constant_folding=True,
      verbose=True,
      opset_version=opset_version,
      dynamic_axes = None)`

Results:
`TypeError: forward() got multiple values for argument 'return_loss'`

If I modify `model.forward()` without `return_loss=False` as:
 `model.forward = functools.partial(model.forward, img_metas=img_meta_list, points = one_pcd)`

This time it results with:
`TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes_3d' and 'gt_labels_3d'
`

How can i avoid calling forward_train() method to enable onnx export?

**Comment by ZCMax** [comment]
Sorry that I'm not familiar with onnx, since we have released the new codebase: [mmdeploy](https://github.com/open-mmlab/mmdeploy), the official onnx export of SECOND / PointPillars will be supported soon. For now, maybe you can seek for solutions there.

**Comment by OrcunCanDeniz** [comment]
Nice to hear that you will be providing ways to deploy all these models. Any information on when MMDet3d models will be supported in MMDeploy?

**Comment by Tai-Wang** [comment]
We will first consider supporting PointPillars because there is no need to deal with the spconv op and then will be FCOS3D or SECOND.

**Comment by XianminMo** [comment]
Have you ever fixed this problem? I 'm trying to deploy the MVXnet model and I'm running into some issues when I just use the torch.onnx.export( ) function. I can not figure out what the input really is.

**Comment by OrcunCanDeniz** [comment]
You can refer to MMDeploy

**Comment by Songhuilun** [comment]
> I've been trying to export "hv_second_secfpn_kitti.py" model to ONNX by refering to a [mmdetection script](https://github.com/open-mmlab/mmdetection/blob/master/tools/deployment/pytorch2onnx.py). Ran inference as below to get meta info easily: ` outs = inference_detector(model, data_path)` `boxes = outs[0]` `meta = outs[1]` `one_pcd = meta['points']` `img_meta_list = meta['img_metas'] `
> 
> Using a partial object to replace forward() function of the model, [ref](https://github.com/open-mmlab/mmdetection/blob/df212e7505e1004d82e6882eeb9466a2156972fb/tools/deployment/pytorch2onnx.py#L59) `model.forward = functools.partial(model.forward, img_metas=img_meta_list, points = one_pcd, return_loss=False )`
> 
> ` torch.onnx.export( model, one_pcd, output_file, input_names=['input_features'], output_names= output_names, export_params=True, keep_initializers_as_inputs=True, do_constant_folding=True, verbose=True, opset_version=opset_version, dynamic_axes = None)`
> 
> Results: `TypeError: forward() got multiple values for argument 'return_loss'`
> 
> If I modify `model.forward()` without `return_loss=False` as: `model.forward = functools.partial(model.forward, img_metas=img_meta_list, points = one_pcd)`
> 
> This time it results with: `TypeError: forward_train() missing 2 required positional arguments: 'gt_bboxes_3d' and 'gt_labels_3d' `
> 
> How can i avoid calling forward_train() method to enable onnx export?





Hello, can you solve this problem?
