### ISSUE TITLE
Question about local-global yaw transformation in monocular 3D detection

### ISSUE THREAD

**Issue by prismformore** [open-mmlab/mmdetection3d#1142]
https://github.com/open-mmlab/mmdetection3d/blob/92d5a87e97b058621fa55a6f073a287e5ecd1a27/mmdet3d/models/dense_heads/fcos_mono3d_head.py#L660

Hi there, I am confused by a question about the transformation from local yaw to global yaw. If I understand the CAM coordinate system correctly, yaw angle starts from the x-axis and goes clockwise. In this case, the angle of ray direction here should be 
**-atan(fx / (x-u0)).** 

However, it seems the code thinks it should be 
**atan((x-u0) /fx).** 

![image](https://user-images.githubusercontent.com/14089338/147414085-cfa26e4c-5235-4910-a855-48b10ef35ff1.png)

May I know where did I go wrong about the coordinate system? Thank you very much.

**Comment by ZCMax** [comment]
![20181204101648283](https://user-images.githubusercontent.com/36950400/147431740-817edeea-b1c9-420d-80d9-8052423569ce.png)

 r_y + pi/2 -theta = alpha +pi/2（Since the purple angles equal）

so:  alpha = r_y - theta

Actually ray direction in your picture should be theta3.

**Comment by prismformore** [comment]
@ZCMax Hi thank you for your reply. Your formula actually says "global_yaw=theta3+theta2" in my drawing (sorry for the bad handwriting). 

However, your addition didn't consider the coordinate system. In MMDetection [3D camera coordinate system](https://github.com/open-mmlab/mmdetection3d/blob/92d5a87e97b058621fa55a6f073a287e5ecd1a27/mmdet3d/core/bbox/structures/cam_box3d.py#L10) (if my understanding is correct) the yaw angle is the angle **between the direction vector and x-axis** instead of the z-axis. So shouldn't the global yaw be "theta4+theta2" as shown in my drawing?

![image](https://user-images.githubusercontent.com/14089338/147445768-3d62f9d4-37f3-4a41-9ca8-73dffd1d7ba7.png)

**Comment by ZCMax** [comment]
the local yaw and global yaw both indeed follow the formulation: yaw angle is the angle between the direction vector and x-axis. 
`global yaw`: The angle between object direction and x-axis.
`local yaw`: **Observation angle**,  In the camera coordinate system, with the camera origin as the center and the [line connecting the camera origin and the object center] as the radius, the object is rotated around the camera y-axis to the camera z-axis. **At this moment, the angle between the object direction and the camera x axis is called local yaw (illustrated in my picture is alpha).**
`theta` in my provided image:  This angle is actually the angle between the [line which connects the camera and object center] and z-axis.

In you image,  local yaw (theta2) is the angle between ray direction (line which connects the camera and object center) and object heading direction, which is not right.

**Comment by prismformore** [comment]
@ZCMax I see where I was wrong now. Thanks a lot.
