### ISSUE TITLE
Error on training PointRCNN with v1.0.0.dev0

### ISSUE THREAD

**Issue by Machine97** [open-mmlab/mmdetection3d#1151]
Hi, thank you for your contribution about PointRCNN. In order to reimplement PointRCNN, at the suggestion of @wHao-Wu , I took the following steps:
1. Build an image of v1.0.0.dev0 branch based on the Dockerfile https://github.com/open-mmlab/mmdetection3d/blob/v1.0.0.dev0/docker/Dockerfile.
2. Update my KITTI data with v1.0.0.dev0 by running /tools/create_data.py file.
3. Pull the latest code from v1.0.0.dev0 branch and rerun the PointRCNN again.
However, the eval results are shown in this log file [20211217_104132.log](https://github.com/open-mmlab/mmdetection3d/files/7798783/20211217_104132.log). The accuracy is very low. Compare with the log file https://github.com/open-mmlab/mmdetection3d/tree/v1.0.0.dev0/configs/point_rcnn, it must be something wrong. I carefully compared the log file you provided with the latest code from v1.0.0.dev0 branch, there are many differences in /configs/base/models/point_rcnn.py, like 'enlarge_width=0.1' which doesn't appear in the log file you provided. I'm so confused about this. Would you please explain this problem? I'm looking forward to your reply.

**Comment by wHao-Wu** [comment]
Hi, @Machine97,
Very sorry for the late reply. We have searched the problem when training PointRCNN for several days. We found that there is a possible bug: the NMS in RPN-stage may contribute to this problem. We will fix the problem asap.

**Comment by Machine97** [comment]
> Hi, @Machine97, Very sorry for the late reply. We have searched the problem when training PointRCNN for several days. We found that there is a possible bug: the NMS in RPN-stage may contribute to this problem. We will fix the problem asap.

Thank you very much for your reply. By the way, I am trying to test my 3D object detection fusion method based on PointRCNN. So, could you please provide the code that can be trained normally first? If it's not convenient, I will wait for you to fix this problem. I am looking forward to your reply. Thank you.

**Comment by wHao-Wu** [comment]
Hi, @Machine97 
Sorry for my late response and for your long waiting. I'm pushing a commit to solve the bugs when training PointRCNN. More details can be seen in this [PR](https://github.com/open-mmlab/mmdetection3d/pull/1224). We will merge this PR asap. Thanks for your patience and waiting.

**Comment by Tai-Wang** [comment]
Fixed by #1224 .
