### ISSUE TITLE
ImportError:~/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l

### ISSUE THREAD

**Issue by qiujien** [open-mmlab/mmdetection3d#1152]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**
1. What command or script did you run?
Verify with point cloud demo
```
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
```
ImportError: /home/hkuit164/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l

2. Did you make any modifications on the code or config? Did you understand what you have modified?
NO

3. What dataset did you use?

**Environment**
cuda 10.1
python 3.8
pytorch 1.7.0+cu101
mmcv-full 1.4.0
mmdet 2.19.0
mmsegmentation 0.20.0
mmdet3d 0.17.3

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
The same error occurs.

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    pip install torch-1.7.0+cu101-cp38-cp38-linux_x86_64.whl

    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
    /usr/local/cuda-10.1/bin
    LD_LIBRARY_PATH:     /usr/local/cuda-10.1/lib64

**Error traceback**
If applicable, paste the error trackback here.

```
File "demo/pcd_demo.py", line 4, in <module>
    from mmdet3d.apis import inference_detector, init_model, show_result_meshlab
  File "/media/hkuit164/WD20EJRX/lidar/mmdetection3d/mmdet3d/apis/__init__.py", line 2, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/media/hkuit164/WD20EJRX/lidar/mmdetection3d/mmdet3d/apis/inference.py", line 11, in <module>
    from mmdet3d.core import (Box3DMode, CameraInstance3DBoxes,
  File "/media/hkuit164/WD20EJRX/lidar/mmdetection3d/mmdet3d/core/__init__.py", line 2, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/media/hkuit164/WD20EJRX/lidar/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 2, in <module>
    from mmdet.core.anchor import build_prior_generator
  File "/home/hkuit164/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/hkuit164/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/hkuit164/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmdet/core/bbox/samplers/__init__.py", line 10, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/hkuit164/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/home/hkuit164/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/hkuit164/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/hkuit164/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/hkuit164/anaconda3/envs/mmdetection3d/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/hkuit164/anaconda3/envs/mmdetection3d/lib/python3.8/site-packages/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by ZCMax** [comment]
Please refer to https://github.com/open-mmlab/mmdetection/issues/4291

**Comment by 459737087** [comment]
Did you solve it ? I also met this problem.
and I checked my version, it still didn't work

**Comment by IamSVP94** [comment]
if yo use conda:
`conda install -c conda-forge mmcv-full`

**Comment by DenChenn** [comment]
In latest version, if u run `conda install -c conda-forge mmcv-full` and it respond with some version compatibility problem, run the following command instead :
`conda install -c conda-forge mmcv==2.0.1`
replace with any other version u need : )

**Comment by YuRui-Learning** [comment]
Hello，i also meet a same problem，like that
`
ImportError: /root/anaconda3/envs/open-mmlab-new/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE
`

**Comment by VLadImirluren** [comment]
> Hello，i also meet a same problem，like that `ImportError: /root/anaconda3/envs/open-mmlab-new/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE`

Could you please tell me how you solve it, please..

Best wishes

**Comment by Pashisfisuta** [comment]
degrade peft version peft==0.8.2 solved..

**Comment by lix19937** [comment]
+1

**Comment by lix19937** [comment]
ref  https://github.com/open-mmlab/mmdetection/issues/4291#issuecomment-946909608

**Comment by af-74413592** [comment]
pip install -U apex
