### ISSUE TITLE
A possible bug in pgd_head

### ISSUE THREAD

**Issue by PinkViolet** [open-mmlab/mmdetection3d#1154]
I'm implementing a custom pgd_head based on the pgd_head you provide. However, I found that in [line #790](https://github.com/open-mmlab/mmdetection3d/blob/e92268bf79ee66a04799165d9c008814f8d3f50b/mmdet3d/models/dense_heads/pgd_head.py#L781), loss_fuse_depth *= something while loss_fuse_depth is not assigned before. I might misunderstand the code, but please take a look.

**Comment by Tai-Wang** [comment]
Fixed by #1157.
