### ISSUE TITLE
Strange prediction results of SECOND model

### ISSUE THREAD

**Issue by yypark21** [open-mmlab/mmdetection3d#1165]
I ran the SECOND model to transfer learning(start at SECOND model to learning kitti data set 20epoch, + 180 epoch to my original dataset(Lidar Sensor, Parking Car))

This is my result image to detection 3D-Box

![image](https://user-images.githubusercontent.com/96404926/148740003-9b23de49-b22f-45ee-b381-06b47790ed40.png)

How can I fix the model?

**Comment by ZCMax** [comment]
It seems that the model you trained works, since there are two matching predicted bboxes and ground truth bboxes in you results. As for the other predicted bboxes, can you check their predicted corresponding scores?

**Comment by skJin-gnict** [comment]
How can check predicted corresponing score?

**Comment by ZCMax** [comment]
you can print the detection results of https://github.com/open-mmlab/mmdetection3d/blob/c7272063e818bcf33aebc498a017a95c8d065143/mmdet3d/models/detectors/voxelnet.py#L104 to check the detected objects score.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
