### ISSUE TITLE
how can i save det result in remote server without display?

### ISSUE THREAD

**Issue by rightchose** [open-mmlab/mmdetection3d#1170]
how can i save det image in remote server?  or how can i save det result as kitti format in txt file?

**Comment by rightchose** [comment]
I wonder if the single modal method,(for example, second) can only generate XX.obj files but not XX.png  ?

**Comment by ZCMax** [comment]
Please check https://mmdetection3d.readthedocs.io/en/latest/useful_tools.html#visualization, SECOND is a point cloud detector which won't save xx.png while inference, feel free to leave comments if it cannot solve your problems.

**Comment by rightchose** [comment]
thank your for answer. But how can i get result like kitti format? just like `Pedestrian 0.00 0 -0.20 712.40 143.00 810.73 307.92 1.89 0.48 1.20 1.84 1.47 8.41 0.01`

**Comment by ZCMax** [comment]
You can find it in the last part of https://mmdetection3d.readthedocs.io/en/latest/datasets/kitti_det.html.

**Comment by rightchose** [comment]
thank you. I will have a try.

**Comment by Lime2333** [comment]
> thank you. I will have a try.

hello, I also meet this problem. Have you solved this issue?

**Comment by Lime2333** [comment]
> > thank you. I will have a try.
> 
> hello, I also meet this problem. Have you solved this issue?

And how do I output this test result as a txt file？Can you share your solution or code?

**Comment by rightchose** [comment]
> > > thank you. I will have a try.
> > 
> > 
> > hello, I also meet this problem. Have you solved this issue?
> 
> And how do I output this test result as a txt file？Can you share your solution or code?

https://github.com/charlesq34/frustum-pointnets/tree/master/mayavi I use this repo.

**Comment by rightchose** [comment]
> > > thank you. I will have a try.
> > 
> > 
> > hello, I also meet this problem. Have you solved this issue?
> 
> And how do I output this test result as a txt file？Can you share your solution or code?

two step:
1、generate kitti det result txt file. (using mm3d, but detail cmd I forget.
2、parse det result and draw the 3d boxes on image. (follow this repo https://github.com/charlesq34/frustum-pointnets/blob/2ffdd345e1fce4775ecb508d207e0ad465bcca80/kitti/kitti_util.py#L365
