### ISSUE TITLE
Unmatching Result / Visualization

### ISSUE THREAD

**Issue by skJin-gnict** [open-mmlab/mmdetection3d#1171]
run code

> ./tools/dist_test.sh configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py results/epoch_199.pth 2 --out results/kitti-3class/results_eval.pkl --format-only --eval-options 'pklfile_prefix=results/kitti-3class/kitti_results' 'submission_prefix=results/kitti-3class/kitti_results'

Result file
![image](https://user-images.githubusercontent.com/76027831/149250746-65e4f4b3-ae7f-41a8-9cd0-83b9ce0e4a93.png)

Visualization of result file
![image](https://user-images.githubusercontent.com/76027831/149250784-36848849-5a06-43cd-8789-4a5063b4e639.png)

I think the Blue boxes are correct answer, and Green boxes are predicted result of Visualized image

I wonder why the  results and visualizations don't match.

**Comment by ZCMax** [comment]
It should be related to the score_threshold while generating the txt file. You can check the box results and their corresponding scores.

**Comment by skJin-gnict** [comment]
Thank you for response.
And one more question.
Are the objects removed by the 'score_threshold', not used for AP calculation?

**Comment by ZCMax** [comment]
Remove objects by score should be done for AP calculation. Besides, we should have support setting score_threshold since v0.17.2.

**Comment by skJin-gnict** [comment]
is that score_threshold's "score" is the

**Comment by skJin-gnict** [comment]
I'd like to ask you a new question about this question.
In the picture above, I don't want to display the box that didn't exceed 'score_threshold' even during the visualization.

what should I do in this case?

**Comment by ZCMax** [comment]
In #1050, we support setting score_threshold when visualizing the results during single gpu test. You can run the following command:
```
# single-gpu testing
python tools/test.py ${CONFIG_FILE} ${CHECKPOINT_FILE} [--out ${RESULT_FILE}] [--eval ${EVAL_METRICS}] [--show] [--show-dir ${SHOW_DIR}]
```
If you want to change the score_threshold, you can modify in [here](https://github.com/open-mmlab/mmdetection3d/blob/c0d009044af7f643f08cc1373925c6ce7bbd0fce/mmdet3d/apis/test.py#L15)

**Comment by Tai-Wang** [comment]
Close due to inactivity.
