### ISSUE TITLE
Adapting KITTI evaluation protocol to custom 3D dataset

### ISSUE THREAD

**Issue by luca-b94** [open-mmlab/mmdetection3d#1173]
Hi, 
I want to adapt the evaluation protocol used by KITTI to my custom 3D dataset.
The dataset has the same structure as KITTI, except that I do not use images. Thus I am not able to provide any information regarding truncation and box height in the label files to compute difficulty scores. Now values for truncation, occlusion, and 2D bboxes in the label files are all zeros. 
What I see when I train some models is that mAP scores are all zeros (even though visualizing model predictions after training gives me promising results). Do you have any idea on how to modify the evaluation protocol in my case?
Any help would be much appreciated, and thanks for the amazing repository.

**Comment by ZCMax** [comment]
Do you have calib file for your datasets?

**Comment by luca-b94** [comment]
Yes, they contain all identity matrices

**Comment by ZCMax** [comment]
calib file should include:  P2 \ R0_rect \ Tr_velo_to_cam,  actually, only R0_rect can be set to identity.

**Comment by luca-b94** [comment]
Hi everybody, 
I found a solution to get reasonable mAP values when training on my custom 3d dataset.
I noticed that when the mAP is computed, both the detection and ground truth boxes are filtered according to the height of the box in the image (all 2D boxes with a height less than 25 px are not considered).
In my case, having all zeros for the 2D boxes in the label files resulted in all gt boxes being filtered out before evaluation could start. So to overcome this, either you have to put a 'dummy' height value in the label files or either hardcode a value greater than 25 here 
https://github.com/open-mmlab/mmdetection3d/blob/b4240bd665686b062e987a61ff33c4d5a57242cd/mmdet3d/core/evaluation/kitti_utils/eval.py#L42 and here 
https://github.com/open-mmlab/mmdetection3d/blob/b4240bd665686b062e987a61ff33c4d5a57242cd/mmdet3d/core/evaluation/kitti_utils/eval.py#L73

Hope this could help somebody that may have stumbled upon the same issue as me.

**Comment by Petros626** [comment]
@luca-b94 is the KITTI evaluation protocol completely implemented now?
