### ISSUE TITLE
Bug in BasePoints.rotate

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#1178]
Looks like the rotation matrix [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/points/base_points.py#L168) is wrong. The `1` value should be in (0, 0) coordinates, not (2, 0). Am i right?

**Comment by ZCMax** [comment]
Yeah, you are right, and it has been modified in dev branch.

**Comment by ZCMax** [comment]
#1182
