### ISSUE TITLE
0 (zero) semantic_loss during training groupfree

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmdetection3d#1179]
Hello,

I have a custom pointcloud dataset of single class. I convert it into scannet format as:
- I assign `instance_mask=-1` for background points and `instance_mask=0,1,2...` for object points. 
- I assign `semantic_mask=0` for background points and `semantic_mask=1` for object points.

Then I set `valid_cat_ids=[1]` in config.

I use scannet dataset config and groupfree model config.

Center/objectness/size_res losses are non-zero and converging but `semantic_loss`'es are always zero.

How do I fix it? What am I doing wrong?

**Comment by ZCMax** [comment]
Can you provide your config? and have you ever checked the prediction and gt which are used to calculate the `semantic_loss` while training?

**Comment by Tai-Wang** [comment]
Close due to inactivity. Please feel free to reopen it if there is any further question.
