### ISSUE TITLE
How to add loss branch

### ISSUE THREAD

**Issue by qfwysw** [open-mmlab/mmdetection3d#1186]
I want to calculate multiple losses, a dictionary of losses returned in the model.
Is it possible to just add the loss to be calculated to the dictionary?
![image](https://user-images.githubusercontent.com/53482524/150264013-fe4a1eca-7d9d-4c70-bda3-863feb1f1758.png)

**Comment by ZCMax** [comment]
You only need to add your loss into returned loss dict in `loss` function of head.
