### ISSUE TITLE
Why does dist_train take longer than single gpu training

### ISSUE THREAD

**Issue by qfwysw** [open-mmlab/mmdetection3d#1188]
dist_train
![image](https://user-images.githubusercontent.com/53482524/150308250-f2cfad90-133d-4ea7-a964-69d094adac4c.png)
single gpu
![image](https://user-images.githubusercontent.com/53482524/150309309-cfc84ede-ac4e-42f0-864b-f94b88ec5f8c.png)

**Comment by ZCMax** [comment]
I think it is due to the multi-gpu communication time consumption. Theoretically,  8 gpu training does not mean 8x faster than 1 gpu training while samples_per_gpu remains same.

**Comment by qfwysw** [comment]
The time of distributed training is not stable, and the time of each training is different. 
![image](https://user-images.githubusercontent.com/53482524/150534051-b56571f1-75ed-4a5c-ae74-23f78701b2b1.png)
![image](https://user-images.githubusercontent.com/53482524/150534099-9c28045c-697b-42bb-930b-b32628ce8900.png)

**Comment by Tai-Wang** [comment]
Which config do you use? It is normal that the first several iterations are a little slower than others. Besides, the unstable data_time and training time can be caused by IO limitations or other machine settings.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
