### ISSUE TITLE
Problem with FCOS3D

### ISSUE THREAD

**Issue by MalignusCN** [open-mmlab/mmdetection3d#1189]
Hi, I'm a beginner of 3D detection on vehicle, I've just ran a test with FCOS3D pretrained model with follow command:
`python tools/test.py configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d.py checkpoints/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_20210715_235813-4bed5239.pth --show --show-dir ./data/nuscenes/show_results/`
It turns out a error as follows:
FileNotFoundError: NuScenesMonoDataset: [Errno 2] No such file or directory: 'data/nuscenes/nuscenes_infos_val_mono3d.coco.json' 
I thought this problem is probably related to the dataset, the MMDETECTION3D I cloned from git didn't have nuscenes folder in data, I wanna know how to set the dataset under your skeleton.
Thx a lot~!

**Comment by ZCMax** [comment]
Yes, you need to set the datasets following our doc: https://mmdetection3d.readthedocs.io/en/latest/datasets/nuscenes_det.html.
