### ISSUE TITLE
如何使用demo/mono_det_demo.py 进行多个图片的测试以及输出预测信息

### ISSUE THREAD

**Issue by zouzouwei** [open-mmlab/mmdetection3d#1192]
如上,我打算使用循环遍历图片与json文件，但这样效率太低，还没有实施，想着有没有更好的想法，我也会自己思考。如果有建议，欢迎指点一下，谢谢啦

**Comment by ZCMax** [comment]
We introduce how to save results during inference, you can see it in our doc: https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html

**Comment by zouzouwei** [comment]
> 
谢谢你的回复，不过我想做的是，用预训练模型对自己收集的无标注照片进行推理，官方文档以及相关资料我都找了，test.py文件好像针对现有标注好的数据集。

**Comment by ZCMax** [comment]
单纯只有图片是没法推理的，你需要一些calib文件，包含camera intrinsic，从而获得 3D 框结果
