### ISSUE TITLE
When using PointPillars, is the "Calibration" of kitti data a needed only for 2d_image visualization?

### ISSUE THREAD

**Issue by ekzmzm79-github** [open-mmlab/mmdetection3d#1194]
Hello.

I'm trying to use 'PointPillars', but I have doubts about the use of "calibration".

If only 3D visualization is needed, can the "calibration" be omitted?

In conclusion, I want to use pointpillars without calibration.
Is it possible?

**Comment by ZCMax** [comment]
The calibration is not only used for visualization, but only used for filtering the point cloud not in fov. We are doing the code refactor, so that the calib file won't be a necessary component while training on custom datasets for easier use.

**Comment by ekzmzm79-github** [comment]
thank you for your reply.
sorry to ask again, but when will the calib you mentioned be updated?

**Comment by ZCMax** [comment]
This feature should be supported in 1-2 months.

**Comment by ekzmzm79-github** [comment]
@ZCMax 

If I create a new dataset and use Pointpillars only with point cloud data without calib information, are there any other differences other than visualization?
( I don't need 2D image visualization. Just like the demo, I just want 3D visualization. )

and thank you for the reply.

**Comment by Tai-Wang** [comment]
Please refer to #260, #334, #429 .
