### ISSUE TITLE
Bug with tools/test.py, when no 3dbox, the program can't run.

### ISSUE THREAD

**Issue by MalignusCN** [open-mmlab/mmdetection3d#1198]
Hi, I just found that when I run tools/test.py with your pretrained model as follow command:
`python tools/test.py /wangyh12/mmdetection3D/configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d.py /wangyh12/mmdetection3D/checkpoints/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_20210715_235813-4bed5239.pth --eval mAP --show --show-dir/wangyh12/mmdetSave`
It turns out that with pic '../nuScenes/samples/CAM_BACK_RIGHT/n015-2018-08-02-17-16-37+0800__CAM_BACK_RIGHT__1533201470427893.jpg', the model can't predict a 3dbox, which with your code in _mmdet3d/core/bbox/structures/cam_box3d.py_. There is a command  in 129 lines, to assert that there must be at least one 3dbox. I'm afraid that this should be a bug, plz help to fix that problem. Thx

**Comment by ZCMax** [comment]
Sorry for the late reply, could you please offer the error log so that we could fix it ASAP?

**Comment by ZCMax** [comment]
After rechecking the code, the assertion problem in 129 lines have been modified in v1.0.0.dev0 branch, we will fix the bug in master branch.
