### ISSUE TITLE
I can't carry out the demo.

### ISSUE THREAD

**Issue by JeongJoon1** [open-mmlab/mmdetection3d#1199]
I entered the following command to make sure that everything necessary for the conda was installed.

python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

I downloaded the model well and made a checkpoints folder.
However, the following has been printed out.

load checkpoint from local path: checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

Nothing is done as it is printed. What's the problem?

**Comment by ekzmzm79-github** [comment]
try this
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth **--show**

**Comment by ZCMax** [comment]
@JeongJoon1 Sorry for the late reply, have you solved the problem following @ekzmzm79-github 's suggestion?

**Comment by JeongJoon1** [comment]
> try this python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth **--show**

Thank you. I solved.



> @JeongJoon1 Sorry for the late reply, have you solved the problem following @ekzmzm79-github 's suggestion?

Yes. I didn't know "--show" was need to test

**Comment by thelandord** [comment]
> > try this python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth **--show**
> 
> Thank you. I solved.
> 
> > @JeongJoon1 Sorry for the late reply, have you solved the problem following @ekzmzm79-github 's suggestion?
> 
> Yes. I didn't know "--show" was need to test

could you tell me where can I download "hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth"? thanks!! The official address--the model zoo is no longer working.

**Comment by SmBito** [comment]
y

> > > try this python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth **--show**
> > 
> > 
> > Thank you. I solved.
> > > @JeongJoon1 Sorry for the late reply, have you solved the problem following @ekzmzm79-github 's suggestion?
> > 
> > 
> > Yes. I didn't know "--show" was need to test
> 
> could you tell me where can I download "hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth"? thanks!! The official address--the model zoo is no longer working.

you can find it here: https://github.com/open-mmlab/mmdetection3d/tree/master/configs/second
![image](https://user-images.githubusercontent.com/34525406/203306428-be1735d5-e8dc-48f5-b3f5-2d64f6a1aeb6.png)
