### ISSUE TITLE
Error in calculating mAP, when using the TEST dataset

### ISSUE THREAD

**Issue by hely4609** [open-mmlab/mmdetection3d#1203]
I modified it from the existing code to use the test dataset.
![Screenshot from 2022-01-31 20-28-34](https://user-images.githubusercontent.com/48938847/151786259-eb323fbd-2ad2-4c4f-af9d-cda4187e4ce3.png)

and it work!

So, I try to get submission and show the result, and calculate mAP

![Screenshot from 2022-01-31 20-24-49](https://user-images.githubusercontent.com/48938847/151785962-c3339db6-079a-4d96-b4d5-25c338d434d0.png)

It was possible to create submission files and showing, but error occurred in calculating the mAP.

KeyError: 'annos'

This was error message that I couldn't find in other issues.

I want to get mAP score to using test dataset.

**Comment by Wuziyi616** [comment]
That's because KITTI dataset doesn't provide labels (the `annos` in the error message). You need to submit the submission file to the evaluation server to get the mAP score.
