### ISSUE TITLE
Instance segmentation on ScanNet

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#1204]
HI,

I've adapted `ScanNetSegDataset` to `ScanNetInstanceSegDataset` with (almost) original ScanNet evaluator. Will it be interesting for the community? If yes, to which branch (`master` or `v1-dev`) should I make a PR?

**Comment by ZCMax** [comment]
Yes, of course, you can make a PR to v1-dev branch, great works!

**Comment by Tai-Wang** [comment]
Temporarily close this issue. Please refer to PR #1230 for more details.
