### ISSUE TITLE
How to train 360 lidar annotation?

### ISSUE THREAD

**Issue by Comverser** [open-mmlab/mmdetection3d#1215]
I am training with custom KITTI data that has 360 degree lidar annotations. (i.e. Not only for front, but also left/right/back).

By default, your toolkit trims outside of FoV and makes velodyne-reduced. And even lidar-only models (e.g. SECOND) perform train/test/val with only front part data (i.e. trimmed data excluding left/right/back annotations).

Is there a way to train/val/test 360 degree lidar annotations?

I know that there were related issues, but I couldn't find the detailed way.
- https://github.com/open-mmlab/mmdetection3d/issues/1023#issuecomment-957262996
- https://github.com/open-mmlab/mmdetection3d/issues/76#issue-684231702

### Sensor setup
- 360-degree lidar
- **Single** RGB camera

### Example of the 360-lidar annotations in KITTI format
Car 0.00 0 -1.37 **0 0 0 0** 1.60 1.88 5.28 -6.45 1.16 1.28 -0.04  **<-- Outside of FoV**
Car 0.00 1 0.26 1048.20 561.57 1593.11 767.63 2.10 3.26 5.73 3.42 1.88 12.82 -0.24
Car 0.00 0 0.65 **0 0 0 0** 1.87 1.81 5.31 4.48 1.57 5.91 -0.04   **<-- Not fusioned**

**Comment by ZCMax** [comment]
I think there must be more details should be changed:
1. the `point_cloud_range`  in config should be changed to cover the whole scene, not only the front view ( x>0 ).
2. the `convert_valid_bboxes` function should be changed or discarded, to keep all the annotations while training.
3. the `pkl` file generated during data conversion should be should be changed to save all the annotations for training. It seems that now it only saves the fov box labels.
4. Since the point_cloud_range is much larger than now, considering the memory consumption, you may need to enlarge the voxel_size.

Maybe more details could be revised for whole scene training and inference. I recommend you can first try to test on the 360 degree point cloud data with our provided well-trained model. If it works, you can further go on training.

**Comment by Comverser** [comment]
> I think there must be more details should be changed:
> 
> 1. the `point_cloud_range`  in config should be changed to cover the whole scene, not only the front view ( x>0 ).
> 2. the `convert_valid_bboxes` function should be changed or discarded, to keep all the annotations while training.
> 3. the `pkl` label file generated during data conversion should have saved all the annotations for training. You can recheck it.
> 4. Since the point_cloud_range is much larger than now, considering the memory consumption, you may need to enlarge the voxel_size.
> 
> Maybe more details could be revised for whole scene training and inference. I recommend you can first try to test on the 360 degree point cloud data with our provided well-trained model. If it works, you can further go on training.

I will try to follow your advice with small sample data, soon.

Before that, I want to check right label method for the two cases of **Outside of FoV** and **Not fusioned**. I currently fill the bbox labels with `0 0 0 0`. Is it right value for this?

For example, which of the following is the best way?
(1) Car 0.00 0 -1.37 `0 0 0 0` 1.60 1.88 5.28 -6.45 1.16 1.28 -0.04
(2) Car 0.00 0 -1.37 `0 0 1920 1080` 1.60 1.88 5.28 -6.45 1.16 1.28 -0.04
(3) Car 0.00 0 -1.37 `1920 1080 1920 1080` 1.60 1.88 5.28 -6.45 1.16 1.28 -0.04
(4) Car 0.00 0 -1.37 `0 0 1 1` 1.60 1.88 5.28 -6.45 1.16 1.28 -0.04

**Comment by Comverser** [comment]
**It doesn't seem to predict the back.**
![Screenshot from 2022-02-15 10-21-47](https://user-images.githubusercontent.com/24600425/153974758-c27e0bb0-12d8-4d27-9f1d-507ef625b28a.png)

**What i have done.**
1. Changed `point_cloud_range` to `[-70, -70, -3, 70, 70, 3] `
2. Changed `convert_valid_bboxes`
```js
valid_inds = valid_pcd_inds.all(-1)  # [original] valid_inds = valid_cam_inds & valid_pcd_inds.all(-1)
```
3. Changed `pts_prefix='velodyne_reduced'` to `pts_prefix='velodyne'` in https://github.com/open-mmlab/mmdetection3d/blob/99ad831a8b04a7f5622c366d8e60745f92a62008/configs/_base_/datasets/kitti-3d-car.py

**Comment by Tai-Wang** [comment]
You need also modify the anchor_range to 360-degree. If you have done this, please add breakpoints in the forward process to observe:
1. Is the input point cloud 360-degree as expected? Is it still correct after preprocessing pipelines and voxelization?
2. Is the feature map and predicted results located in 360-degree?

**Comment by Tai-Wang** [comment]
Close due to inactivity.

**Comment by Petros626** [comment]
@comverser did you finally implement the 360° detection succesfully?
