### ISSUE TITLE
How to count GT?

### ISSUE THREAD

**Issue by Comverser** [open-mmlab/mmdetection3d#1216]
I have custom KITTI dataset that has 360-degree lidar annotations.

During the model development, I compared the evaluation mAP reaults between your toolkit result and my calculation.

I found that there is big difference in GT counts.

In my calcuation, I counted all the 360-degree lidar annoations for GT that leaded the difference and very low score.

But your toolkit seems to count GT from the following file that has reduced GTs:
- kitti_infos_val_mono3d.coco.json

I have questions:
1. Your toolkit seems to trim annotations outside of FoV. Is it right? What is the criteria for include/exclude? Is the criteria the alpha (i.e. Observation angle of object) in annotation only?
2. What is the file of kitti_infos_val_mono3d.coco.json? Does this file contain right number of GTs information as I guessed?
3. What is the right way to get no of GTs for each class using your toolkit?

### Sensor setup
- 360-degree lidar
- **Single** RGB camera

### Example of the 360-lidar annotations in KITTI format
Car 0.00 0 -1.37 **0 0 0 0** 1.60 1.88 5.28 -6.45 1.16 1.28 -0.04  **<-- Outside of FoV**
Car 0.00 1 0.26 1048.20 561.57 1593.11 767.63 2.10 3.26 5.73 3.42 1.88 12.82 -0.24
Car 0.00 0 0.65 **0 0 0 0** 1.87 1.81 5.31 4.48 1.57 5.91 -0.04   **<-- Not fusioned**

**Comment by ZCMax** [comment]
1. Yes, only the bboxes whose projected 2D bboxes have intersection with the front image can be kept.
2. `kitti_infos_val_mono3d.coco.json` will only be used in monocular 3D object detection method, for point cloud 3D detection model, the `pkl` file is used.
3.  the `pkl` file should include all the labels, not only the fov labels.

**Comment by Comverser** [comment]
> 1. Yes, only the bboxes whose projected 2D bboxes have intersection with the front image can be kept.
> 2. `kitti_infos_val_mono3d.coco.json` will only be used in monocular 3D object detection method, for point cloud 3D detection model, the `pkl` file is used.
> 3. the `pkl` file should include all the labels, not only the fov labels.

1. More questions about `kitti_infos_val_mono3d.coco.json`:
- Are **GTs in `kitti_infos_val_mono3d.coco.json`** and **GTs that have intersection with the front image** the same?
- The bbox in `kitti_infos_val_mono3d.coco.json` is not same with bbox in `label_2/*.txt`. Why?

2. Could you please tell me more about the intersection filltering? All the pcd labels in my custom dataset is 100% linked with image, so that all labels have bbox infomation. But the the number of GT didn't seem to match with your GTs count, as mAP results between my calculation and your toolkit calculation were different.

**Comment by ZCMax** [comment]
1. GTs in kitti_infos_val_mono3d.coco.json are filtered with depth > 0 and having intersection with the front image.
2. The bbox values in .json file format is (x1, x2, w, h), which follows the coco format.
3. Is the number of GTs in `pkl` file same with your original GTs? `pkl` to `json` is processed in https://github.com/open-mmlab/mmdetection3d/blob/dabe3ff4deaedef4c030b026c6f5a131d3d9be70/tools/data_converter/kitti_converter.py#L332,
 During the process, we will filter the GTs by https://github.com/open-mmlab/mmdetection3d/blob/dabe3ff4deaedef4c030b026c6f5a131d3d9be70/tools/data_converter/kitti_converter.py#L435 and filter the GTs whose depth < 0 in https://github.com/open-mmlab/mmdetection3d/blob/dabe3ff4deaedef4c030b026c6f5a131d3d9be70/tools/data_converter/kitti_converter.py#L478.

**Comment by Tai-Wang** [comment]
Close due to inactivity.

**Comment by gmt710** [comment]
This may be helpful.
https://mmdetection3d.readthedocs.io/zh_CN/latest/datasets/kitti_det.html
