### ISSUE TITLE
what is the unit related to distance considered for voxel_size (tuple or float): 

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/mmdetection3d#1220]
It will be much appreciated if I can get help!
In `mmlab/mmdetection3d/tree/master/mmdet3d/core/voxel)/voxel_generator.py`, I want to use a voxel size of height, width and length of [2,2,4] in meters. However, I am a little confused with the `voxel_size (tuple or float)` should I have to set it to (0.2,0.2,0.4) or (2,2,4) ?

**Comment by ZCMax** [comment]
You can the `voxel_size` in config directly, like https://github.com/open-mmlab/mmdetection3d/blob/c0d009044af7f643f08cc1373925c6ce7bbd0fce/configs/_base_/models/hv_pointpillars_secfpn_kitti.py#L1, and it should be (2, 2, 4)

**Comment by ammaryasirnaich** [comment]
> You can the `voxel_size` in config directly, like
> 
> https://github.com/open-mmlab/mmdetection3d/blob/c0d009044af7f643f08cc1373925c6ce7bbd0fce/configs/_base_/models/hv_pointpillars_secfpn_kitti.py#L1
> 
> , and it should be (2, 2, 4)

Thanks a lot ZCMax
