### ISSUE TITLE
How to change a pcd file to a bin file.

### ISSUE THREAD

**Issue by JeongJoon1** [open-mmlab/mmdetection3d#1221]
I am using Ouster's lidar and extracted pcd from rosbag. Do I have to put a bin file in the input value to detect it? Then, what is the code for changing to bin file?

**Comment by ZCMax** [comment]
Please refer to this https://github.com/open-mmlab/mmdetection3d/issues/916.

**Comment by Comverser** [comment]
You can refer [this code](https://github.com/Comverser/gnlabs_converter/blob/5af2472f2b43ffd1b609d56f4972ccb8ded86f21/src/libs/convert_format.py#L17) too.
