### ISSUE TITLE
No seg_label extracted from sunrgbd dataset

### ISSUE THREAD

**Issue by Teaksters** [open-mmlab/mmdetection3d#1229]
I am currently working on a object detection model and need to fine-tune it on the sunrgbd dataset. Luckily enough for me, this github provided a extraction method to python files. So first of all, thanks for that! 

The problem that remains is that the seg_labels folder remains empty and I believe no segmentation masks are extracted. I did look through the matlab files and see that the loading of the segmentation files (or class in matlab?) is commented out. Is this on purpose? And is it possible to include the segmenation masks (preferably 2D) into the final generated pickle?

**Comment by 459737087** [comment]
I also met this problem

**Comment by wHao-Wu** [comment]
Hi, @Teaksters @459737087 ,

SUN RGB-D only provides the 2D segmentation annotation, which is not needed in mmdetection3d for now. If you want this annotation, you can download the data from [here](https://github.com/ankurhanda/sunrgbd-meta-data).
