### ISSUE TITLE
how to extract a small waymo dataset

### ISSUE THREAD

**Issue by QYChan** [open-mmlab/mmdetection3d#1231]
It takes a whole day to train the model when using 20% waymo dataset(load_interval=5). How can I extract a smaller dataset? Just set the config load_interval greater than 5?

**Comment by ZCMax** [comment]
You can refer to this https://github.com/open-mmlab/mmdetection3d/blob/ed81c6cc326a33f927d4455c219bb7715591b08b/mmdet3d/datasets/waymo_dataset.py#L82, generally speaking, you can set larger number for `load_Interval`.
