### ISSUE TITLE
calculate 3d giou

### ISSUE THREAD

**Issue by TianhaoFu** [open-mmlab/mmdetection3d#1232]
Hello, 

I want to calculate 3d giou, I now have bbox of prediction and bbox of gt, which format is [batchsize, max_object_number, 7].7 means that [x, y, z, h, w, l, ry].
how should I calculate 3d giou use my result? Function  axis_aligned_bbox_overlaps_3d  seems to be unable to meet my needs because it needs input format like <x1, y1, z1, x2, y2, z2>.

thanks.

**Comment by ZCMax** [comment]
Sorry for the late reply, 3D GIOU has not been supported in MMDetection3D, we will consider to support it in the future, besides, a PR is welcomed.
