### ISSUE TITLE
Extracting precision/recall dictionaries for evaluation

### ISSUE THREAD

**Issue by luca-b94** [open-mmlab/mmdetection3d#1239]
Hello,
I would like to save the complete precision/recall/orientation dictionaries computed during the evaluation pipeline on the KITTI dataset because I want to visualize the precision/recall curves.
Do you have any hints on how to do so? 
Thank you very much

**Comment by Tai-Wang** [comment]
You can save related intermediate results in the functions like [this](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/evaluation/kitti_utils/eval.py#L451) (such as precision vs. recall) during evaluation and just plot them afterward.

**Comment by luca-b94** [comment]
Thank you very much for the support, I managed to extract what I wanted

**Comment by holtvogt** [comment]
I receive a recall array of multiple equal values instead of increasing values in the original implementation using KITTI dataset. How did you do it?
