### ISSUE TITLE
Unable to visualize the obj file generated when executing demo/pcd_demo.py

### ISSUE THREAD

**Issue by sparshgarg23** [open-mmlab/mmdetection3d#1247]
I was able to install mmdetection3d on colab ,however when I executed demo/pcd_demo.py as mentioned in the documentation,I ran into the following error
```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
load checkpoint from local path: checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
/usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
```
After the execution,I have the following files in the demo folder
```
kitti_000008_points.obj and kitti_000008_pred.obj
```
So my question is how can I visualize these files ,and what steps can I take to resolve the torch.meshgrid warning
Finally,in order to deal with the runtime error,I uninstalled pycocotools and then installed mmpycocotools.But the error still persiss.Any suggestions on what I can do to solve this?

My MMCV,MMDet,MMSegmentation and MMDetection3d versions are as follows
MMDet:2.21
MMSegmentation 0.21.1
Cuda 11.1
Pytorch 1.10.0
Platform Colab

**Comment by hadilou** [comment]
You can use [Meshlab](https://www.meshlab.net/) , `torch.meshgrid ` seems to be a warning not an error, your error might have happened before that.

**Comment by sparshgarg23** [comment]
I have blender,will that work?

**Comment by Tai-Wang** [comment]
The warning does not matter. You can use meshlab to visualize these generated results. If you want to visualize online, please refer to our [documentation](https://mmdetection3d.readthedocs.io/en/latest/useful_tools.html#visualization) to adjust your command and setting.
