### ISSUE TITLE
Getting coordinates of 3d bounding boxes  and depth information

### ISSUE THREAD

**Issue by Kwame261** [open-mmlab/mmdetection3d#1249]
First of all I would like to thank the creators for providing such a useful package, Thank You.

I'm using a pretrained FCOS3D based model to detect cars . The results seem to be very promising. I now want to get the coordinates of the 3d  bounding box  and the depth information as stated in 
https://arxiv.org/pdf/2107.14160.pdf 
result, data = inference_mono_3d_detector(model,image,ann_file)
However I do not understand the contents of result due to my limited knowledge of python and being new to this platform.
Which of them contain the 3d bounding box coordinates. And How do I read the cordinates

**Comment by ZCMax** [comment]
```
[{'img_bbox': {'boxes_3d': CameraInstance3DBoxes(
    tensor([[ 3.7423e+00,  1.6317e+00,  1.2660e+01,  ...,  3.5362e+00,
         -1.3254e-01, -1.2332e-01],
        [-8.8514e+00,  2.0887e+00,  1.7982e+01,  ...,  4.7302e+00,
          6.1145e-02,  1.4581e+00],
        [ 3.7695e+00,  1.6390e+00,  1.2763e+01,  ...,  3.5919e+00,
         -1.4215e-01, -1.5090e-01],
        ...,
        [-6.1145e+00,  1.7160e+00,  8.1271e+00,  ...,  6.2478e+00,
         -1.6470e-02,  6.9995e-03],
        [ 8.5329e+00,  2.0529e+00,  5.0737e+01,  ...,  1.6284e+00,
         -1.2220e-02,  2.3871e-02],
        [-2.8016e+01,  2.6054e+00,  4.1474e+01,  ...,  1.7494e+00,
         -7.4245e-02, -7.4915e-02]])), 'scores_3d': tensor([0.4225, 0.3931, 0.3723, 0.3560, 0.3337, 0.3333, 0.3077, 0.3035, 0.3010,
        0.2938, 0.2854, 0.2690, 0.2314, 0.2231, 0.2135, 0.2012, 0.1997, 0.1989,
        0.1870, 0.1805, 0.1788, 0.1776, 0.1722, 0.1634, 0.1618, 0.1593, 0.1581,
        0.1564, 0.1515, 0.1507, 0.1505, 0.1486, 0.1460, 0.1454, 0.1447, 0.1415,
        0.1398, 0.1368, 0.1357, 0.1339, 0.1331, 0.1322, 0.1317, 0.1315, 0.1315,
        0.1282, 0.1265, 0.1253, 0.1251, 0.1250, 0.1237, 0.1236, 0.1221, 0.1217,
        0.1215, 0.1208, 0.1204, 0.1202, 0.1197, 0.1181, 0.1177, 0.1158, 0.1126,
        0.1107, 0.1099, 0.1093, 0.1070, 0.1070, 0.1069, 0.1054, 0.1046, 0.1045,
        0.1034, 0.1033, 0.1033, 0.1025, 0.1024, 0.1022, 0.1021, 0.1021, 0.1014,
        0.1005, 0.0997, 0.0989, 0.0987, 0.0971, 0.0962, 0.0960, 0.0957, 0.0945,
        0.0939, 0.0935, 0.0930, 0.0911, 0.0909, 0.0906, 0.0891, 0.0883, 0.0877,
        0.0873, 0.0872, 0.0872, 0.0871, 0.0870, 0.0860, 0.0858, 0.0857, 0.0857,
        0.0847, 0.0846, 0.0845, 0.0829, 0.0828, 0.0824, 0.0818, 0.0815, 0.0810,
        0.0807, 0.0800, 0.0800, 0.0798, 0.0798, 0.0795, 0.0793, 0.0792, 0.0788,
        0.0784, 0.0784, 0.0781, 0.0780, 0.0776, 0.0768, 0.0767, 0.0762, 0.0757,
        0.0754, 0.0753, 0.0750, 0.0740, 0.0735, 0.0731, 0.0724, 0.0717, 0.0714,
        0.0708, 0.0704, 0.0702, 0.0701, 0.0696, 0.0696, 0.0691, 0.0691, 0.0679,
        0.0668, 0.0668, 0.0667, 0.0665, 0.0664, 0.0662, 0.0661, 0.0661, 0.0659,
        0.0658, 0.0655, 0.0652, 0.0650, 0.0639, 0.0636, 0.0634, 0.0634, 0.0628,
        0.0625, 0.0621, 0.0620, 0.0618, 0.0616, 0.0614, 0.0613, 0.0612, 0.0612,
        0.0611, 0.0611, 0.0609, 0.0605, 0.0602, 0.0602, 0.0601, 0.0591, 0.0590,
        0.0589, 0.0585, 0.0583, 0.0581, 0.0581, 0.0578, 0.0577, 0.0575, 0.0575,
        0.0574, 0.0574]), 'labels_3d': tensor([7, 0, 7, 7, 7, 7, 7, 8, 7, 7, 7, 9, 8, 0, 7, 8, 7, 9, 3, 9, 7, 3, 3, 9,
        7, 3, 8, 7, 7, 9, 8, 9, 9, 3, 7, 8, 7, 9, 7, 9, 9, 0, 1, 1, 9, 9, 7, 9,
        0, 9, 7, 7, 7, 0, 7, 9, 8, 9, 9, 9, 9, 9, 9, 9, 7, 7, 0, 7, 0, 7, 9, 7,
        7, 7, 0, 9, 7, 7, 7, 9, 9, 7, 7, 9, 7, 9, 9, 9, 0, 3, 7, 7, 7, 9, 0, 7,
        0, 7, 0, 9, 9, 9, 7, 9, 7, 0, 9, 0, 8, 9, 8, 8, 9, 9, 9, 9, 3, 8, 8, 8,
        8, 9, 7, 7, 1, 9, 8, 7, 9, 9, 7, 0, 7, 1, 9, 7, 0, 3, 7, 7, 8, 8, 7, 0,
        7, 9, 0, 8, 0, 8, 9, 9, 7, 0, 0, 0, 9, 1, 7, 9, 0, 0, 8, 7, 7, 9, 9, 0,
        0, 0, 8, 8, 0, 9, 0, 0, 7, 7, 1, 8, 9, 9, 3, 0, 8, 8, 8, 9, 1, 0, 3, 8,
        1, 8, 9, 7, 9, 9, 7, 7]), 'attrs_3d': tensor([2, 5, 2, 2, 2, 2, 2, 8, 2, 2, 2, 8, 8, 5, 2, 8, 2, 8, 5, 8, 2, 5, 7, 8,
        2, 5, 8, 2, 2, 8, 8, 8, 8, 5, 2, 8, 2, 8, 2, 8, 8, 5, 7, 7, 8, 8, 2, 8,
        5, 8, 2, 3, 2, 5, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 3, 5, 2, 5, 3, 8, 2,
        2, 2, 5, 8, 2, 2, 2, 8, 8, 2, 2, 8, 2, 8, 8, 8, 5, 5, 3, 2, 3, 8, 5, 2,
        5, 2, 7, 8, 8, 8, 2, 8, 2, 5, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 5, 8, 8, 8,
        8, 8, 3, 3, 7, 8, 8, 2, 8, 8, 2, 7, 2, 5, 8, 3, 5, 5, 2, 2, 8, 8, 3, 5,
        3, 8, 5, 8, 5, 8, 8, 8, 3, 5, 5, 7, 8, 5, 2, 8, 5, 7, 8, 2, 3, 8, 8, 7,
        5, 5, 8, 8, 5, 8, 5, 7, 2, 2, 7, 8, 8, 8, 5, 5, 8, 8, 5, 8, 5, 5, 5, 8,
        5, 8, 8, 2, 8, 8, 2, 2])}}]
```
the `result` includes the detected bboxes information, the `CameraInstance3DBoxes` includes all the detected bboxes info in format `x, y, z, l, w, h, r`.  `z` is the depth info.

**Comment by Kwame261** [comment]
Thank You for your quick response. Please what info does the 'scores_3d': tensor’ section contain? Kwame From: ChaimZhuSent: Friday, February 18, 2022 1:51 AMTo: open-mmlab/mmdetection3dCc: Kwame261; AuthorSubject: Re: [open-mmlab/mmdetection3d] Getting coordinates of 3d bounding boxes and depth information (Issue #1249) [{'img_bbox': {'boxes_3d': CameraInstance3DBoxes(    tensor([[ 3.7423e+00,  1.6317e+00,  1.2660e+01,  ...,  3.5362e+00,         -1.3254e-01, -1.2332e-01],        [-8.8514e+00,  2.0887e+00,  1.7982e+01,  ...,  4.7302e+00,          6.1145e-02,  1.4581e+00],        [ 3.7695e+00,  1.6390e+00,  1.2763e+01,  ...,  3.5919e+00,         -1.4215e-01, -1.5090e-01],        ...,        [-6.1145e+00,  1.7160e+00,  8.1271e+00,  ...,  6.2478e+00,         -1.6470e-02,  6.9995e-03],        [ 8.5329e+00,  2.0529e+00,  5.0737e+01,  ...,  1.6284e+00,         -1.2220e-02,  2.3871e-02],        [-2.8016e+01,  2.6054e+00,  4.1474e+01,  ...,  1.7494e+00,         -7.4245e-02, -7.4915e-02]])), 'scores_3d': tensor([0.4225, 0.3931, 0.3723, 0.3560, 0.3337, 0.3333, 0.3077, 0.3035, 0.3010,        0.2938, 0.2854, 0.2690, 0.2314, 0.2231, 0.2135, 0.2012, 0.1997, 0.1989,        0.1870, 0.1805, 0.1788, 0.1776, 0.1722, 0.1634, 0.1618, 0.1593, 0.1581,        0.1564, 0.1515, 0.1507, 0.1505, 0.1486, 0.1460, 0.1454, 0.1447, 0.1415,        0.1398, 0.1368, 0.1357, 0.1339, 0.1331, 0.1322, 0.1317, 0.1315, 0.1315,        0.1282, 0.1265, 0.1253, 0.1251, 0.1250, 0.1237, 0.1236, 0.1221, 0.1217,        0.1215, 0.1208, 0.1204, 0.1202, 0.1197, 0.1181, 0.1177, 0.1158, 0.1126,        0.1107, 0.1099, 0.1093, 0.1070, 0.1070, 0.1069, 0.1054, 0.1046, 0.1045,        0.1034, 0.1033, 0.1033, 0.1025, 0.1024, 0.1022, 0.1021, 0.1021, 0.1014,        0.1005, 0.0997, 0.0989, 0.0987, 0.0971, 0.0962, 0.0960, 0.0957, 0.0945,        0.0939, 0.0935, 0.0930, 0.0911, 0.0909, 0.0906, 0.0891, 0.0883, 0.0877,        0.0873, 0.0872, 0.0872, 0.0871, 0.0870, 0.0860, 0.0858, 0.0857, 0.0857,        0.0847, 0.0846, 0.0845, 0.0829, 0.0828, 0.0824, 0.0818, 0.0815, 0.0810,        0.0807, 0.0800, 0.0800, 0.0798, 0.0798, 0.0795, 0.0793, 0.0792, 0.0788,        0.0784, 0.0784, 0.0781, 0.0780, 0.0776, 0.0768, 0.0767, 0.0762, 0.0757,        0.0754, 0.0753, 0.0750, 0.0740, 0.0735, 0.0731, 0.0724, 0.0717, 0.0714,        0.0708, 0.0704, 0.0702, 0.0701, 0.0696, 0.0696, 0.0691, 0.0691, 0.0679,        0.0668, 0.0668, 0.0667, 0.0665, 0.0664, 0.0662, 0.0661, 0.0661, 0.0659,        0.0658, 0.0655, 0.0652, 0.0650, 0.0639, 0.0636, 0.0634, 0.0634, 0.0628,        0.0625, 0.0621, 0.0620, 0.0618, 0.0616, 0.0614, 0.0613, 0.0612, 0.0612,        0.0611, 0.0611, 0.0609, 0.0605, 0.0602, 0.0602, 0.0601, 0.0591, 0.0590,        0.0589, 0.0585, 0.0583, 0.0581, 0.0581, 0.0578, 0.0577, 0.0575, 0.0575,        0.0574, 0.0574]), 'labels_3d': tensor([7, 0, 7, 7, 7, 7, 7, 8, 7, 7, 7, 9, 8, 0, 7, 8, 7, 9, 3, 9, 7, 3, 3, 9,        7, 3, 8, 7, 7, 9, 8, 9, 9, 3, 7, 8, 7, 9, 7, 9, 9, 0, 1, 1, 9, 9, 7, 9,        0, 9, 7, 7, 7, 0, 7, 9, 8, 9, 9, 9, 9, 9, 9, 9, 7, 7, 0, 7, 0, 7, 9, 7,        7, 7, 0, 9, 7, 7, 7, 9, 9, 7, 7, 9, 7, 9, 9, 9, 0, 3, 7, 7, 7, 9, 0, 7,        0, 7, 0, 9, 9, 9, 7, 9, 7, 0, 9, 0, 8, 9, 8, 8, 9, 9, 9, 9, 3, 8, 8, 8,        8, 9, 7, 7, 1, 9, 8, 7, 9, 9, 7, 0, 7, 1, 9, 7, 0, 3, 7, 7, 8, 8, 7, 0,        7, 9, 0, 8, 0, 8, 9, 9, 7, 0, 0, 0, 9, 1, 7, 9, 0, 0, 8, 7, 7, 9, 9, 0,        0, 0, 8, 8, 0, 9, 0, 0, 7, 7, 1, 8, 9, 9, 3, 0, 8, 8, 8, 9, 1, 0, 3, 8,        1, 8, 9, 7, 9, 9, 7, 7]), 'attrs_3d': tensor([2, 5, 2, 2, 2, 2, 2, 8, 2, 2, 2, 8, 8, 5, 2, 8, 2, 8, 5, 8, 2, 5, 7, 8,        2, 5, 8, 2, 2, 8, 8, 8, 8, 5, 2, 8, 2, 8, 2, 8, 8, 5, 7, 7, 8, 8, 2, 8,        5, 8, 2, 3, 2, 5, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 3, 5, 2, 5, 3, 8, 2,        2, 2, 5, 8, 2, 2, 2, 8, 8, 2, 2, 8, 2, 8, 8, 8, 5, 5, 3, 2, 3, 8, 5, 2,        5, 2, 7, 8, 8, 8, 2, 8, 2, 5, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 5, 8, 8, 8,        8, 8, 3, 3, 7, 8, 8, 2, 8, 8, 2, 7, 2, 5, 8, 3, 5, 5, 2, 2, 8, 8, 3, 5,        3, 8, 5, 8, 5, 8, 8, 8, 3, 5, 5, 7, 8, 5, 2, 8, 5, 7, 8, 2, 3, 8, 8, 7,        5, 5, 8, 8, 5, 8, 5, 7, 2, 2, 7, 8, 8, 8, 5, 5, 8, 8, 5, 8, 5, 5, 5, 8,        5, 8, 8, 2, 8, 8, 2, 2])}}]the result includes the detected bboxes information, the CameraInstance3DBoxes includes all the detected bboxes info in format x, y, z, l, w, h, r. z is the depth info.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ZCMax** [comment]
You can find the meaning of `attribute` in our doc https://mmdetection3d.readthedocs.io/en/latest/datasets/nuscenes_det.html.

**Comment by Tai-Wang** [comment]
Close due to inactivity.

**Comment by hygxy** [comment]
Given ```1*3*900*1600``` input, the network has in total 25 outputs of the following shape:
```bash
1*10*113*200------1*10*57*100------1*10*29*50--------1*10*15*25---------1*10*8*13
1*9*113*200-------1*9*57*100-------1*9*29*50---------1*9*15*25---------1*9*8*13
1*2*113*200-------1*2*57*100-------1*2*29*50---------1*2*15*25---------1*2*8*13
1*9*113*200-------1*9*57*100-------1*9*29*50---------1*9*15*25---------1*2*8*13
1*1*113*200-------1*1*57*100-------1*1*29*50---------1*1*15*25---------1*1*8*13
```
Could you please explain which information are stored in the corresponding second channels? i.e., these channels of shape 10,9,2,9,1?
