### ISSUE TITLE
Meaning of Printed KITTI Evaluation

### ISSUE THREAD

**Issue by tydpan** [open-mmlab/mmdetection3d#1250]
In your [documentation](https://mmdetection3d.readthedocs.io/en/latest/datasets/kitti_det.html), the example of KITTI metrics is as the following: 

Car AP@0.70, 0.70, 0.70:
bbox AP:97.9252, 89.6183, 88.1564
bev  AP:90.4196, 87.9491, 85.1700
3d   AP:88.3891, 77.1624, 74.4654
aos  AP:97.70, 89.11, 87.38

Car AP@0.70, 0.50, 0.50:
bbox AP:97.9252, 89.6183, 88.1564
bev  AP:98.3509, 90.2042, 89.6102
3d   AP:98.2800, 90.1480, 89.4736
aos  AP:97.70, 89.11, 87.38

What does this output exactly mean?
From my understanding, columns are easy, moderate, and hard using IOU thresholds 0.7, 0.7, 0.7 in the first row. But then in the second group of the output, it used 0.7 for easy again but got different results, i.e. 88.3891 vs 98.2800 for 3d. 
Could someone kindly explain how to read the metrics? Thank you!

**Comment by Tai-Wang** [comment]
Please refer to [#185](https://github.com/open-mmlab/mmdetection3d/issues/185).
