### ISSUE TITLE
Prediction files

### ISSUE THREAD

**Issue by LucyXH** [open-mmlab/mmdetection3d#1251]
Hi authors,

I want to run mmdetection to do some fusion work, but I met some errors that were reported in a past Issue and have not got resolved. I actually only need the prediction files (.json file). Could you send the files to me that have predictions on Nuscenes-mini or Nuscenes-full if that is possible? 

Thank you so much for your help!

**Comment by ZCMax** [comment]
Problems should be fixed in #1234

**Comment by Tai-Wang** [comment]
Close due to inactivity.
