### ISSUE TITLE
 [Open3D ERROR] GLFW Error: X11: Failed to open display :0.0

### ISSUE THREAD

**Issue by HuangZhe885** [open-mmlab/mmdetection3d#1252]

**Comment by HuangZhe885** [comment]
[Open3D ERROR] GLFW Error: X11: Failed to open display :0.0

**Comment by wHao-Wu** [comment]
Hi, @HuangZhe885,

I suppose that you want to online visualize the results in the remote. But badly, the `open3d` cannot support this function for now.

**Comment by HuangZhe885** [comment]
> Hi, @HuangZhe885,
> 
> I suppose that you want to online visualize the results in the remote. But badly, the `open3d` cannot support this function for now.

I can run the results using a Windows computer to connect to the server, but I get an error when I use a Mac computer, which I can't understand.

**Comment by wHao-Wu** [comment]
In my case (Linux), this error will occur when I want to visualize the result with open3d from the terminal connected to the remote.

**Comment by HuangZhe885** [comment]
> In my case (Linux), this error will occur when I want to visualize the result with open3d from the terminal connected to the remote.

Both computers are connected to the server, and the Mac can't produce results. After checking the reason, it seems that the local visualization needs to be called. so weird, Windows is working

so ,if  I want to visualize the results, do I need to install open3D locally？

**Comment by ZCMax** [comment]
> 

If you want to visualize the results, you can save to detection results to .obj file, and visualize it using meshlab locally.

**Comment by HuangZhe885** [comment]
> 

thanks ,I can see the result on meshlab ,but looks uglier than open3D, I like images with lots of colors, maybe I need to learn how to use meshlab

**Comment by HuangZhe885** [comment]
> 

thanks ,I can see the result on meshlab ,but looks uglier than open3D, I like images with lots of colors, maybe I need to learn how to use meshlab

**Comment by ghb0224** [comment]
> > 
> 
> 如果要可视化结果，可以将检测结果保存到 .obj 文件，并在本地使用 meshlab 进行可视化。

请问怎么保存到.obj?能否保存到其他格式，例如pcd

**Comment by EricLina** [comment]
> Hi, @HuangZhe885,
> 
> I suppose that you want to online visualize the results in the remote. But badly, the `open3d` cannot support this function for now.

You can refer to this: [The Web_Visualization](http://www.open3d.org/docs/release/tutorial/visualization/web_visualizer.html)

**Comment by 13717630148** [comment]
@ghb0224 @HuangZhe885 @ZCMax 
I got the same question. how to same results as .obj file?
