### ISSUE TITLE
Where is or How to generate the annotation file: nuscenes_infos_train_mono3d.coco.json in FCOS3D ?

### ISSUE THREAD

**Issue by caichuang0415** [open-mmlab/mmdetection3d#1257]
I am training fcos3d and the config file indicates the annotation file path is data/nuscenes/nuscenes_infos_train_mono3d.coco.json, but I do not find it? Is this needed to be generated first by myself(if so, how?) or is it somewhere else? Thanks.

**Comment by konyul** [comment]
you can generate json file by running nuscenes_converter.py in mmdetection3d/tools/data_converter folder

**Comment by caichuang0415** [comment]
> you can generate json file by running nuscenes_converter.py in mmdetection3d/tools/data_converter folder
OK, thank you for replying
