### ISSUE TITLE
Error Occurs when I add new NECKS and so on. 

### ISSUE THREAD

**Issue by zhangchbin** [open-mmlab/mmdetection3d#1266]
Firstly, I train the model.
Then I need to modify the code again.
Specifically, I add new NECKS or HEADS.
During my debugging, the newly added NECKS reports 'compile error'.
Then I find that the running model will report the error due to 'compile error' caused by my modification.
I think the running code before my modification is loaded in CPU Memory, but why does the running program report the same error?
So how can solve this case?

**Comment by zhangchbin** [comment]
Thanks for your help. @ZCMax

**Comment by ZCMax** [comment]
Sorry for the late reply, `compile error` should not appear after only adding necks and heads, pleas post your error log, and what code have you added in details.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
