### ISSUE TITLE
wrap_fp16_model is not in mmdet.core 

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#127]
Looks like `tools/test.py` is not working with `mmdet` master as `wrap_fp16_model` was moved to `mmcv` in this [commit](https://github.com/open-mmlab/mmdetection/commit/14b5d8eb426ebdf102a2906626f610e25e91866b).

**Comment by ZwwWayne** [comment]
Thanks for your kind report. PR https://github.com/open-mmlab/mmdetection/pull/3822 will fix this issue. We accelerate the fix process.

**Comment by ZwwWayne** [comment]
Fixed in https://github.com/open-mmlab/mmdetection/pull/3822
