### ISSUE TITLE
Question about SparseEncoder for 3D detection

### ISSUE THREAD

**Issue by xyaochen** [open-mmlab/mmdetection3d#1281]
I find that the shape of feature map produced by SparseEncoder is [200, 176] while the orginal voxel grid is [1408, 1600, 40] of KITTI dataset. So the x, y coordination is transposed after middle encoder?
And why the flipped map can generate right bboxes in aligned with ground-truth bboxes in velodyne coordinates? If there any code that transposed the x, y coordination back?
refer to the config: https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/hv_second_secfpn_kitti.py#L14
https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/hv_second_secfpn_kitti.py#L36

**Comment by Tai-Wang** [comment]
You can refer to [anchor_generator](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/anchor/anchor_3d_generator.py) for more details. We generate the anchors following the order of first x and then y.
