### ISSUE TITLE
Elegant way to disable data augmentation at last few epochs.

### ISSUE THREAD

**Issue by Abyssaledge** [open-mmlab/mmdetection3d#1284]
Some algorithms might get better performances if data augmentation is disabled before the last few epochs. So I wonder if it is possible to provide an option in config to meet this need.

**Comment by ZCMax** [comment]
You can achieve this by hook, a good example is YOLOX in MMDetection:
In the YOLOX algorithm, the author uses data augmentations including Mosaic, MixUp, ColorJit, etc. After 285 epochs, the two data augmentations of Mosaic and MixUp are turned off, and a new L1Loss is added. You can refer to the code: https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/hook/yolox_mode_switch_hook.py

**Comment by Abyssaledge** [comment]
Thanks, I'll try it.
