### ISSUE TITLE
Confusion definition in kitti_dataset

### ISSUE THREAD

**Issue by Xiangxu-0103** [open-mmlab/mmdetection3d#1289]
Hi, the definition of `result_files` and `result_files_` [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/kitti_dataset.py#L308-L315) are quitely confusion. Whether it is a bug?

**Comment by ZCMax** [comment]
I  think it's type error, a PR is welcomed to fix the problem.

**Comment by ZCMax** [comment]
It's indeed an error, but the code is not used at least for now. A PR is welcomed to fix the bug.

**Comment by Xiangxu-0103** [comment]
Ok, I will try to use the code and pull the pr when free.
