### ISSUE TITLE
How to get a 2D bbox features from a 3D bbox(I have solved this problem, you can just close the issue, thanks.)

### ISSUE THREAD

**Issue by MalignusCN** [open-mmlab/mmdetection3d#1291]
Hi, sorry to interrupt. After get a result from FCOS3d, I get a dict result with key['boxes_3d'], the value is a CameraInstance3DBoxes with a lot attributes. I have several problems, hope you can solve it.

1. The tensor's shape is [num_bboxes, 9] as I see, I wanna know if this tensor is [x, y, z, x_size, y_size, z_size, yaw, velo_x, velo_y]
2. I wanna know how to convert the 3D boxes into 2D boxes features, like xmin, ymin, xmax, ymax, 2d_center and so on~~

Thx for your help.

**Comment by ZCMax** [comment]
Yes, and you can refer to https://github.com/open-mmlab/mmdetection3d/blob/145e592ebab29fd9f4aac54501cefd7a84706c1e/tools/data_converter/nuscenes_converter.py#L454 for converting 3d boxes into 2d boxes in nuscenes datasets.

**Comment by MalignusCN** [comment]
Thx for your reply, but I didn't use nuscenes as our dataset, The results I get is actually that the model's output, which like this.
![image](https://user-images.githubusercontent.com/49176066/156710011-41d0b67b-fdae-4698-a05b-4b23446aabb0.png)
I think I didn't need to get_box, actually I have already get the box and corresponding 'cam2img'. The key:boxes_3d with function variables as follows, I didn't find any function can change the 3dbox into 2d~
![image](https://user-images.githubusercontent.com/49176066/156709189-17be3a4d-c8eb-489a-a79b-fa48e5d5a8e4.png)
I wanna know which method maybe I should apply, a demo perhaps is the most needed thing.

**Comment by Bincle-Yin** [comment]
> Thx for your reply, but I didn't use nuscenes as our dataset, The results I get is actually that the model's output, which like this. ![image](https://user-images.githubusercontent.com/49176066/156710011-41d0b67b-fdae-4698-a05b-4b23446aabb0.png) I think I didn't need to get_box, actually I have already get the box and corresponding 'cam2img'. The key:boxes_3d with function variables as follows, I didn't find any function can change the 3dbox into 2d~ ![image](https://user-images.githubusercontent.com/49176066/156709189-17be3a4d-c8eb-489a-a79b-fa48e5d5a8e4.png) The attributes boxes_3d with: ![image](https://user-images.githubusercontent.com/49176066/156711624-86e64773-0e3f-4ae0-8392-2934c150bb05.png)
> 
> I wanna know which method maybe I should apply, a demo perhaps is the most needed thing.

Hi , how do you solve this problem

**Comment by Bincle-Yin** [comment]
> Thx for your reply, but I didn't use nuscenes as our dataset, The results I get is actually that the model's output, which like this. ![image](https://user-images.githubusercontent.com/49176066/156710011-41d0b67b-fdae-4698-a05b-4b23446aabb0.png) I think I didn't need to get_box, actually I have already get the box and corresponding 'cam2img'. The key:boxes_3d with function variables as follows, I didn't find any function can change the 3dbox into 2d~ ![image](https://user-images.githubusercontent.com/49176066/156709189-17be3a4d-c8eb-489a-a79b-fa48e5d5a8e4.png) The attributes boxes_3d with: ![image](https://user-images.githubusercontent.com/49176066/156711624-86e64773-0e3f-4ae0-8392-2934c150bb05.png)
> 
> I wanna know which method maybe I should apply, a demo perhaps is the most needed thing.

Hi , how do you solve this problem

**Comment by Jue0** [comment]
> 

Hi. I have the same problem. How did you solve?
