### ISSUE TITLE
自定义数据集转sunrgbd

### ISSUE THREAD

**Issue by hjm0613** [open-mmlab/mmdetection3d#1293]
采用自己相机采集的pcd文件，转换为sunrgbd标准格式，在标准的sunrgbd 每一张图像都存在一个calib文件，请问它的这个calib文件是每采集一次数据都做了标定吗？

**Comment by ZCMax** [comment]
个人理解应该是每次采集数据都做了标定的

**Comment by Tai-Wang** [comment]
一般相机内参是固定的，出厂即定；外参例如相机位置和旋转每次不同，需重新标定。
