### ISSUE TITLE
How to resume the training with FCOS3D

### ISSUE THREAD

**Issue by MalignusCN** [open-mmlab/mmdetection3d#1305]
Hi, I've just train a job with 6 epochs, the 6th.pth has been saved. But it seems that our model still need more epochs to train, I wanna know how to start a training process with 6 epochs as the start. Thanks a lot.

**Comment by ZCMax** [comment]
you can add `resume_from = '/nfs/fcos3d/epoch_6.pth' (your checkpoint dir)` in your config.
