### ISSUE TITLE
What's the function of legacy in pillar encoder ?

### ISSUE THREAD

**Issue by zhulf0804** [open-mmlab/mmdetection3d#1307]
Hi, I want to know what's the function of `legacy` in `https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/voxel_encoders/pillar_encoder.py#L116` ?

Legacy is set True in default, so we will run `https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/voxel_encoders/pillar_encoder.py#L128`:

```
              f_center = features[:, :, :3]
              f_center[:, :, 0] = f_center[:, :, 0] - (
                  coors[:, 3].type_as(features).unsqueeze(1) * self.vx +
                  self.x_offset)
              f_center[:, :, 1] = f_center[:, :, 1] - (
                  coors[:, 2].type_as(features).unsqueeze(1) * self.vy +
                  self.y_offset)
              f_center[:, :, 2] = f_center[:, :, 2] - (
                  coors[:, 1].type_as(features).unsqueeze(1) * self.vz +
                  self.z_offset)
```

Here, I find **raw** `features[..., :3]` has been changed and features[..., :3] == features[..., -3:], is there a bug ? 

Looking forward to your reply.

**Comment by ZCMax** [comment]
`        legacy (bool, optional): Whether to use the new behavior or
            the original behavior. Defaults to True.`
Turning on the legacy option actually violates the original paper implementation, because we do not want to make inplace operations while computing the center features. It is a little interesting that previous experiments seem to show that setting legacy to True can yield better performance, you can regard it as a training trick.

**Comment by zhulf0804** [comment]
Thanks for your quick reply.

I'm still confused. As you mentioned above, `inplace operations` is an empirical trick to yield better performance.

However, it can cause data redundancy between the first 3 dimensions and the last 3 dimension in the encoded pillar features(10 dimensions), as shown in the following figure.

<img width="740" alt="0313-mmdet3d" src="https://user-images.githubusercontent.com/36033208/158039686-0de73606-6167-44ab-a4a0-466552ee5840.png">

Here, I debuged an older mmdet3d, where the encoded pillar features are in 9 dimensions, and the first 2 dimensions and the last 2 dimension are the same.  Then, my questions are: 

1. The raw point coordinate information (the first 2 or 3 dimensions) is lost and replaced with relative coordinate. Will it affect the features ?
2. Why don't you use features[:-2] or features[:-3] instead of features ?

I'm a beginner to 3d detection, and sorry to bother you.
Looking forward to your reply.

**Comment by ZCMax** [comment]
You can refer to https://github.com/open-mmlab/mmdetection3d/issues/1150 , maybe it would be helpful.
