### ISSUE TITLE
Get points included in a specific bounding box (nuScenes)

### ISSUE THREAD

**Issue by springto** [open-mmlab/mmdetection3d#1310]
Hi, 

thanks for providing this awesome repository, great work!

I want to get a subset of points from the whole point cloud which are part of one specific predicted bounding box. I am using the nuScenes Dataset with the pretrained PointPillars model. 

I stumbled across the `remove_points_in_boxes` function in `transforms_3d.py` which seems well suited for this task. 
However, this function calls `box_np_ops.points_in_rbbox` 

https://github.com/open-mmlab/mmdetection3d/blob/fd3112bc4954071456660dbb3904a6c9b7a54d86/mmdet3d/core/bbox/box_np_ops.py#L353-L376

Since the first called function `center_to_corner_box3d`  is only for the KITTI Dataset, but I am using the nuScenes dataset, I wanted to ask if I can just replace the `center_to_corner_box3d` function with the `corner` property method of the LiDARInstance3DBoxes? 

Or is there a better way to get a subset of points from a nuScenes point cloud (LiDARPoints) contained in a single predicted bounding box (LiDARInstance3DBoxes)?

This would be my approach: 

```
def points_in_rbbox(points, rbbox, z_axis=2, origin=(0.5, 0.5, 0)):
    Check points in rotated bbox and return indicces.

    Args:
        points (np.ndarray, shape=[N, 3+dim]): Points to query.
        rbbox (np.ndarray, shape=[M, 7]): Boxes3d with rotation.
        z_axis (int, optional): Indicate which axis is height.
            Defaults to 2.
        origin (tuple[int], optional): Indicate the position of
            box center. Defaults to (0.5, 0.5, 0).

    Returns:
        np.ndarray, shape=[N, M]: Indices of points in each box.
    """
    # TODO: this function is different from PointCloud3D, be careful
    # when start to use nuscene, check the input
    rbbox_corners = rbbox.corners
    surfaces = corner_to_surfaces_3d(rbbox_corners)
    indices = points_in_convex_polygon_3d_jit(points[:, :3], surfaces)
    return indices
```

**Comment by Tai-Wang** [comment]
I think you can feel free to have a try. It seems suitable for your case, but you need to carefully check the coordinate system of different boxes and their corners.

**Comment by Tai-Wang** [comment]
Close due to inactivity. Please feel free to reopen it if there is any further question.
