### ISSUE TITLE
Update anchor_generator type for kitti dataset

### ISSUE THREAD

**Issue by Xiangxu-0103** [open-mmlab/mmdetection3d#1311]
Hi, I notice that you have updated the anchor_generator type to `AlignedAnchor3DRangeGenerator` for pointpillars_kitti-3class, while pp_kitti-car, second_kitti-3class and second_kitti-car still use the original type `Anchor3DRangeGenerator`. Whether these models should be fixed in the future?

**Comment by Tai-Wang** [comment]
The replacement of the anchor generator is one of the modifications when upgrading PointPillars performance. From another perspective, we can also keep the original one if we would like to follow the original implementation. So I think it is optional on your side. We may currently add notes for this detail in the corresponding README while keeping the current implementation.

**Comment by ZCMax** [comment]
And you can try to use the `AlignedAnchor3DRangeGenerator` for other models by yourself for possible peformance improvement.
