### ISSUE TITLE
How to finetune instance segmentation model(nuimage) with self dataset?

### ISSUE THREAD

**Issue by Shaoqing26** [open-mmlab/mmdetection3d#1316]
Hi, all,
 
 There has a question that how to finetune instance segmentation model which trained on nuimage  with our private dataset？
 Thanks～

**Comment by ZCMax** [comment]
For nuimages, it typically follows the pipeline of general 2d detection and instance segmentation, please follow the dochttps://mmdetection.readthedocs.io/en/latest/tutorials/finetune.html
