### ISSUE TITLE
Performance on pp_waymo

### ISSUE THREAD

**Issue by Xiangxu-0103** [open-mmlab/mmdetection3d#1322]
Hi, I use pointpillars to train on WaymoD5-3class. Performance on Car and Pedestrian is normal while Cyclist has large gap compared to the results you provide.
The following is the results I get:

| Backbone | Load Interval | mAP@L1 | mAPH@L1 |  mAP@L2 | mAPH@L2 |
|:-----------:|:---------------:|:----------:|:------------:|:-----------:|:------------:|
| SECFPN | 5 | 60.7 | 52.1 | 54.8 | 47.0 |
| above @ Car | | 68.6 | 68.0 | 60.5 | 60.0 |
| above @ Pedestrian | | 68.2 | 49.1 | 60.3 | 43.2 |
| above @ Cyclist | | 45.3 | 39.3 | 43.6 | 37.8 |

**Comment by ZCMax** [comment]
Did you train on the latest branch, which means after coordinates refactoring? And could you please offer the the training config?

**Comment by Xiangxu-0103** [comment]
Yes, I train it on the latest branch.  [Here](https://github.com/open-mmlab/mmdetection3d/files/8283818/20220316_090739.log) is my training log.

**Comment by Xiangxu-0103** [comment]
By the way, current branch has conflict with mmcv 1.4.6 as spconv has been implemented in mmcv.ops.

**Comment by Tai-Wang** [comment]
> By the way, current branch has conflict with mmcv 1.4.6 as spconv has been implemented in mmcv.ops.

We will also adjust the requirement and remove ops when releasing the next version of mmdet3d.

**Comment by Tai-Wang** [comment]
> Yes, I train it on the latest branch. [Here](https://github.com/open-mmlab/mmdetection3d/files/8283818/20220316_090739.log) is my training log.

The performance of cyclists can fluctuate a little due to fewer training samples, but I think the performance is abnormally too low. Have you trained the model multiple times? Does it still perform so terribly?

**Comment by Xiangxu-0103** [comment]
I will train the model multiple times to check the performance of cyclists.

**Comment by Tai-Wang** [comment]
Temporarily close due to inactivity.
