### ISSUE TITLE
Question about `dir_limit_offset` in Anchor3DHead

### ISSUE THREAD

**Issue by Xiangxu-0103** [open-mmlab/mmdetection3d#1326]
pointpillars_kitti and second_kitti set `dir_limit_offset` in Anchor3DHead as default value `-pi / 2` while other datasets set the value as `-0.78554`(-pi / 4). Since the coordinate system has been refactored, whether the different settings of `dir_limit_offset` can affect the estimation of angles largely?

**Comment by Tai-Wang** [comment]
The `dir_limit_offset` setting should be modified accordingly after coordinate system refactoring. Could you please point out specific files or configs that you feel are incorrect?

**Comment by Xiangxu-0103** [comment]
The `dir_limit_offset` in [hv_pointpillars_fpn_nus.py](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/hv_pointpillars_fpn_nus.py), [hv_pointpillars_secfpn_kitti.py](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/hv_pointpillars_secfpn_kitti.py) and [hv_second_secfpn_waymo.py](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/hv_second_secfpn_waymo.py) is set as  `-0.78554`, while in [hv_pointpillars_secfpn_kitti.py](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/hv_pointpillars_secfpn_kitti.py) and [hv_second_secfpn_kitti.py](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/hv_second_secfpn_kitti.py) not set, which means use the default value `-pi / 2`. I'm not sure whether they are really incorrect and need to be checked. I will also check it ASAP.

**Comment by Tai-Wang** [comment]
We just set it to the default `-pi/2` to keep the direction classification the same as that before coordinate system refactoring. It has been a long time since we tested this setting before. We will also double-check it and also look forward to your feedback on using other settings.

**Comment by Xiangxu-0103** [comment]
I set `dir_limit_offset` as `-pi/2`, `-pi/4` and `pi/2` respectively for pp_kitti, and it seems to have no effect on performance of orientation estimation.

**Comment by Tai-Wang** [comment]
Thanks for your share! I guess our colleagues also tried before and observed such results. It may play a more important role in other datasets.
