### ISSUE TITLE
How can we use the logger, same as in mmdetection ?

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/mmdetection3d#1328]
In mmdetection we can use logger to log loss values by modifying the config file 
```
log_config = dict(
interval=50,
hooks=[dict(type='TextLoggerHook'),
dict(type='TensorboardLoggerHook')])
```
Can we also use the same with the models in mmdetection3 to log loss values while training and validation?

**Comment by Tai-Wang** [comment]
Of course. You can refer to this [file](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/default_runtime.py) for details of our default settings.

**Comment by ammaryasirnaich** [comment]
> Of course. You can refer to this [file](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/default_runtime.py) for details of our default settings.

Thanks for the response, one thing more, apart from logging the losses, can we also log predicted bounding box images in the validation phase using `TensorboardLoggerHook`? As the TensorboardLoggerHook only has the implementation for logging text and scaler values only.

**Comment by ZwwWayne** [comment]
In this case, you need to implement a new logger hook and use that.

**Comment by ammaryasirnaich** [comment]
> In this case, you need to implement a new logger hook and use that.

Thanks, @ZwwWayne, I will really appreciate it if you can point to any resources where I can find how to use the customer loggers in the workflow?

**Comment by Tai-Wang** [comment]
You can refer to mmcv [documentation](https://mmcv.readthedocs.io/en/latest/api.html#mmcv.runner.LoggerHook) for more details about different logger hooks.
