### ISSUE TITLE
Error for bin file

### ISSUE THREAD

**Issue by mreece813** [open-mmlab/mmdetection3d#1335]
Hello i am receiving this error at the moment.

![image](https://user-images.githubusercontent.com/29603698/159982030-dac2374b-e0f5-4692-b0fb-09b126d31b7c.png)

i am trying to run the command on my 0.bin file. The format is not in either kitti or nuScenes. Is there a way i am able to run this as a pcd file?

**Comment by Tai-Wang** [comment]
You'd better reformat your bin file similar to our provided example file, or you may encounter multiple unexpected errors caused by the inconsistency of model settings (such as the input feature dimension).
