### ISSUE TITLE
Difference between  Inference and Test for FCOS3D

### ISSUE THREAD

**Issue by Kwame261** [open-mmlab/mmdetection3d#1336]
Hello Please  I will like to know the  difference  between  "  inference_mono_3d_detector(model, image, ann_file):" 
and "single_gpu_test(model,data_loader, show=False,out_dir=None,show_score_thr=0.3):".  The inference method seems to load an annotation file containing camera parameters for each image. but the test method does not.Please can you explain or does  data_loader
contain the ann files too.

**Comment by ZCMax** [comment]
For `single_gpu_test`,  we construct the dataset class using the config:
```
    val=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file=data_root + 'kitti_infos_val_mono3d.coco.json',
        info_file=data_root + 'kitti_infos_val.pkl',
        img_prefix=data_root,
        classes=class_names,
        pipeline=test_pipeline,
        modality=input_modality,
        test_mode=True,
        box_type_3d='Camera'),
```
the anno file is loaded in the dataset, and can be obtained by data_loader

**Comment by Tai-Wang** [comment]
Intrinsic parameters are required for inference. Please check the format of your reply for a more clear discussion.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
