### ISSUE TITLE
size mismatch for voxel_encoder.pfn_layers.0.linear.weight: copying a param with shape torch.Size([64, 9]) from checkpoint, the shape in current model is torch.Size([64, 10]).

### ISSUE THREAD

**Issue by chengjunlongwhusgg** [open-mmlab/mmdetection3d#1339]
Hi,  I  received this error when I ran the following command:
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20200620_230421-aa0f3adb.pth --show

The "hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20200620_230421-aa0f3adb.pth" is downloaded form https://download.openmmlab.com/mmdetection3d/v0.1.0_models/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20200620_230421-aa0f3adb.pth

And the same error occurs when I ran the following command:
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20200620_230614-77663cd6.pth --show

Any ideas? Thanks!

**Comment by ArchipLab-LinfengZhang** [comment]
I have found the same problem, looking for help

**Comment by chengjunlongwhusgg** [comment]
邮件已收到！！！

**Comment by Tai-Wang** [comment]
Thanks for your report. It's because of a modification of PointPillars in #1166 , involving a new feature dimension into the voxel encoder. We will update models ASAP.

**Comment by Tai-Wang** [comment]
Models should be updated.

**Comment by chengjunlongwhusgg** [comment]
邮件已收到！！！

**Comment by chengjunlongwhusgg** [comment]
邮件已收到！！！
