### ISSUE TITLE
which optimizer is used in pointpillars 

### ISSUE THREAD

**Issue by Jsijon** [open-mmlab/mmdetection3d#134]
in the config file
hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py
doesn't define which type of optimizer( like adam or else) is used in contrast to other methods which is defined

it defines just the learning rate 
lr = 0.001
optimizer = dict(lr=lr)

**Comment by Tai-Wang** [comment]
We use inheritance in the configuration system. The type of optimizer is defined in the file `_base_/schedules/cyclic_40e.py`, where AdamW optimizer is utilized.
