### ISSUE TITLE
How to get  kitti _000008_infos.pkl when run demo.py

### ISSUE THREAD

**Issue by Chenfanqing** [open-mmlab/mmdetection3d#1341]
When I try to test MVX-net on kitti data, I followed the official instructions to execute the command

`python demo/multi_modality_demo.py demo/data/kitti/kitti_000008.bin demo/data/kitti/kitti_000008.png demo/data/kitti/kitti_000008_infos.pkl configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py checkpoints/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class_20200621_003904-10140f2d.pth`

But I find nobody tell me how to get **kitti_000008_infos.pkl** . In other words, what is the specific format of this pkl file?
I searched some information buf found nothing.
Can someone kindly tell me, I would be very grateful ! Thank you

**Comment by ZCMax** [comment]
We provide the the file, and about the pkl format, here is the reference https://mmdetection3d.readthedocs.io/en/latest/datasets/kitti_det.html

**Comment by Chenfanqing** [comment]
> We provide the the file, and about the pkl format, here is the reference https://mmdetection3d.readthedocs.io/en/latest/datasets/kitti_det.html

Thank you， It's true that I didn't notice here

**Comment by ZCMax** [comment]
Close due to issue be solved, feel free to reopen it if you still have other questions.

**Comment by JunjieWang0528** [comment]
> We provide the the file, and about the pkl format, here is the reference https://mmdetection3d.readthedocs.io/en/latest/datasets/kitti_det.html


The link has expired. Could you tell me how to generate it again?
