### ISSUE TITLE
ImportError: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.9/fractions.py)

### ISSUE THREAD

**Issue by ouening** [open-mmlab/mmdetection3d#1343]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I have installed the `mmdet3d` but can't be used. Some error occured:
<pre><font color="#26A269"><b>     17</b></font> <font color="#AF0000"><i>Note that most of these functions are only guaranteed to work for DAGs.</i></font>
<font color="#26A269"><b>     18</b></font> <font color="#AF0000"><i>In general, these functions do not check for acyclic-ness, so it is up</i></font>
<font color="#26A269"><b>     19</b></font> <font color="#AF0000"><i>to the user to check for that.</i></font>
<font color="#26A269"><b>     20</b></font> <font color="#AF0000"><i>&quot;&quot;&quot;</i></font>
<font color="#26A269"><b>     22</b></font> <font color="#008700"><b>from</b></font> <font color="#0000FF"><b>collections</b></font> <font color="#008700"><b>import</b></font> defaultdict, deque
<font color="#26A269">---&gt; 23</font> <font color="#008700"><b>from</b></font> <font color="#0000FF"><b>fractions</b></font> <font color="#008700"><b>import</b></font> gcd
<font color="#26A269"><b>     24</b></font> <font color="#008700"><b>from</b></font> <font color="#0000FF"><b>functools</b></font> <font color="#008700"><b>import</b></font> partial
<font color="#26A269"><b>     25</b></font> <font color="#008700"><b>from</b></font> <font color="#0000FF"><b>itertools</b></font> <font color="#008700"><b>import</b></font> chain

<font color="#C01C28">ImportError</font>: cannot import name &apos;gcd&apos; from &apos;fractions&apos; (/usr/lib/python3.9/fractions.py)
</pre>

**Reproduction**
1. What command or script did you run?

```
from mmdet3d.apis import *
```

**Environment**

<pre>sys.platform: linux
Python: 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 2080
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Build cuda_11.3.r11.3/compiler.29920130_0
GCC: gcc (Ubuntu 9.4.0-3ubuntu1.1) 9.4.0
PyTorch: 1.11.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0+cu113
OpenCV: 4.5.4
MMCV: 1.4.5
MMCV Compiler: GCC 11.2
MMCV CUDA Compiler: 11.1
MMDetection: 2.22.0
MMSegmentation: 0.22.1
MMDetection3D: 1.0.0rc0+2f88c12
</pre>

**Comment by ouening** [comment]
I solved it by upgrading the `networkx` package. But another error occured:
<pre><font color="#C01C28">ImportError</font>: cannot import name &apos;SparseModule&apos; from &apos;mmcv.ops&apos; (/usr/local/lib/python3.9/dist-packages/mmcv/ops/__init__.py)
</pre>

**Comment by ZCMax** [comment]
Please update mmcv verison to 1.4.7

**Comment by ouening** [comment]
Yes, I just solved it by upgrading mmcv to 1.4.7
