### ISSUE TITLE
kitti bin file out of point cloud range

### ISSUE THREAD

**Issue by QYChan** [open-mmlab/mmdetection3d#1344]
I train a dynamic voxelize model on kitti dataset. And get follwoing error when preparing point cloud data. In file `transforms_3d.py`, the `points_mask` get all `False` after `points.in_range_3d(self.pcd_range)`.

```python
dynamic_voxelize(points, coors, voxel_size, coors_range, 3)
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 
```
My mmdetection3d version is 0.15.0.

**Comment by ZCMax** [comment]
Please follow the issue template, did  you make any changes in config or code?

**Comment by Tai-Wang** [comment]
Close due to inactivity.
