### ISSUE TITLE
What does scale_factor mean in FCOS3d?  

### ISSUE THREAD

**Issue by caichuang0415** [open-mmlab/mmdetection3d#1347]
In the decoding outputs of the model to boxes process, there is a code :  bbox_pred[:, :2] /= bbox_pred[:, :2].new_tensor(scale_factor)
I don't quite understand the scale_factor's meaning. Here, bbox_pred[:, :2] stands for the predicted x, y for the 3d box.

**Comment by Tai-Wang** [comment]
It is used to recover the scale of predicted 2D offsets when the input is augmented with rescaling during inference. You can temporarily ignore it because we do not use it right now because the Resize3D is not supported yet.

**Comment by caichuang0415** [comment]
> 

OK I see it, thank you

**Comment by xiaowenhe** [comment]
when I change Resize in train_cfg, like Resize(1600,900) to (1200, 675), other param3ters do not change. After training, I cannot get right detect box. Maybe only can use origin size of image to train?

**Comment by rlczddl** [comment]
@tchittesh @xiaowenhe 我也想知道这个问题，比如当不采用原图分辨率而是降低两倍的分辨率训练时，该head里的scale_factor是否需要调整?看作者的意思，训练时应该不需要调整？
