### ISSUE TITLE
Chinese documentation for LiDAR-based 3D detection

### ISSUE THREAD

**Issue by jshilong** [open-mmlab/mmdetection3d#1358]
This is a development requirement documentation of a feature we wish to collaborate with the community.
In this issue, we wish to welcome the community developers to participate in the improvement of Chinese documentation.

## Steps
- First, take a look at our English document at [LiDAR-Based 3D Detection](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/supported_tasks/lidar_det3d.md) 
- According to your understanding of the relevant content, translate it into the corresponding Chinese version

## Resources
The doc should be released at [基于Lidar的3D检测](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/zh_cn/supported_tasks/lidar_det3d.md)

**Comment by JoeyforJoy** [comment]
Hello, I want to pick up this issue and hope to be familiar with the development process.

**Comment by ZCMax** [comment]
> Hello, I want to pick up this issue and hope to be familiar with the development process.

Great!

**Comment by ZwwWayne** [comment]
Hi @JoeyforJoy ,
Thanks! We are looking forward to your PR. Feel free to ask if you have any questions about this issue or your PR. We will arrange review A.S.A.P once the PR is created.

**Comment by JoeyforJoy** [comment]
I created a PR(#1368) for this issue. Could you review it for me?
