### ISSUE TITLE
Chinese documentation for LiDAR-Based 3D Semantic Segmentation

### ISSUE THREAD

**Issue by jshilong** [open-mmlab/mmdetection3d#1359]
This is a development requirement documentation of a feature we wish to collaborate with the community.
In this issue, we wish to welcome the community developers to participate in the improvement of Chinese documentation.

## Steps
- First, take a look at our English document at [LiDAR-Based 3D Semantic Segmentation](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/supported_tasks/lidar_sem_seg3d.md) 
- According to your understanding of the relevant content, translate it into the corresponding Chinese version

## Resources
The doc should be released at [基于Lidar的3D语义分割](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/zh_cn/supported_tasks/lidar_sem_seg3d.md)

**Comment by ZwwWayne** [comment]
added in #1420
