### ISSUE TITLE
Chinese documentation for speed benchmark 

### ISSUE THREAD

**Issue by jshilong** [open-mmlab/mmdetection3d#1361]
This is a development requirement documentation of a feature we wish to collaborate with the community.
In this issue, we wish to welcome the community developers to participate in the improvement of Chinese documentation.

## Steps
- First, take a look at our English document at [Benchmarks](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/benchmarks.md) 
- According to your understanding of the relevant content, translate it into the corresponding Chinese version

## Resources
The doc should be released at [基准测试](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/zh_cn/benchmarks.md)

**Comment by HanaRo** [comment]
Hi, I'd like to pick up this task.

**Comment by ZCMax** [comment]
> Hi, I'd like to pick up this task.

Great!

**Comment by ZwwWayne** [comment]
resolved in #1379
