### ISSUE TITLE
waymo info file

### ISSUE THREAD

**Issue by xyupeng** [open-mmlab/mmdetection3d#1370]
Hi, thank you all for the great codebase.

I find a potential bug in generating waymo info file.

Location: in ` _calculate_num_points_in_gt()` (called in `create_waymo_info_file()` in line 160 [kitti_converter.py](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/kitti_converter.py))

https://github.com/open-mmlab/mmdetection3d/blob/9c7270d00dbdd0599b6b6bf816c3ff2dd17d4878/tools/data_converter/kitti_converter.py#L62-L67

To remove outside points, the intrinsic matrix is P2 (cam 2) but the extrinsic matrix Trv2c correpsonds to cam 0. 

Is this a bug? Or I misunderstood sth?

**Comment by Tai-Wang** [comment]
Yes, it seems like a bug that may not affect currently supported models. Could you please help check one sample and create a PR to fix it?

**Comment by xyupeng** [comment]
hi, to make some more comments,
I find in `create_waymo_info_file()` the `remove_outside` flag passed to `_calculate_num_points_in_gt()` is set to Flase. So currently the bug is not triggered. But I'm not sure if in any case `remove_outside=True` for waymo.

**Comment by Tai-Wang** [comment]
Thanks for your feedback. Currently, we do not have any cases using this option but I think there is a possibility in the future. So it would be better to make it more compatible. If you use it, welcome to create a PR to fix it at any time :)
