### ISSUE TITLE
Regarding config files

### ISSUE THREAD

**Issue by mreece813** [open-mmlab/mmdetection3d#1372]
Can someone explain quickly or a brief overview of what each of the configs file mean. Like why us one over the other?

**Comment by ZCMax** [comment]
You can get the basic understanding of config file in https://mmcv.readthedocs.io/en/latest/understand_mmcv/config.html.
Then you can know the config file meaning from https://mmdetection3d.readthedocs.io/en/latest/tutorials/config.html.
