### ISSUE TITLE
Wrong test results of FCOS3d

### ISSUE THREAD

**Issue by caichuang0415** [open-mmlab/mmdetection3d#1374]
I had been training FCOS3d model on a mini dataset of Nuscense, however, whatever I did, the test results showed that the mAP of some categories is 0, while other categories were 1. This can be seen in the picture below:
![微信截图_20220405231436](https://user-images.githubusercontent.com/50684798/161786941-bcbe518d-c63d-4724-8deb-5daf489c3ed5.png)
I have tried much but can not figure it out, can anyone give me any help? thanks.

**Comment by Tai-Wang** [comment]
How do you train the model on nuScenes-mini? Could you please show your log and provide more details of your modifications?

**Comment by caichuang0415** [comment]
> How do you train the model on nuScenes-mini? Could you please show your log and provide more details of your modifications?

Thanks for your reply,  I did not use the  nuScenes-mini, I use the nuScenes-train but only select part of the data, below is a picture that I modified the export_2d_annotation function in the tools/data_converter/nuscenes_converter.py file:
![image](https://user-images.githubusercontent.com/50684798/161918651-5ba721de-7a01-4693-8e01-87366e04610a.png)
As you can see, I only select the first 100 infos.
And this is the link of  my log file:
[https://github.com/caichuang0415/Files/blob/main/20220405_213221.log](url)

**Comment by Tai-Wang** [comment]
Hmm, I am not sure if such a way can be successful or not. Have you successfully trained other models on KITTI or nuScenes? BTW, the log is not available for me. Please check it.

**Comment by caichuang0415** [comment]
> Hmm, I am not sure if such a way can be successful or not. Have you successfully trained other models on KITTI or nuScenes? BTW, the log is not available for me. Please check it.

Thank you for replying me. I have not tried other models and I will try it.
The link can not be directed, sorry for that. I find you can copy it and paste it in your browser to open it:
https://github.com/caichuang0415/Files/blob/main/20220405_213221.log

**Comment by Tai-Wang** [comment]
Oh, I guess the limited size of the dataset is a really big problem here. You can try to use more epochs for training (such as 48 epochs like KITTI) and have a look at how the model performs.

**Comment by caichuang0415** [comment]
> Oh, I guess the limited size of the dataset is a really big problem here. You can try to use more epochs for training (such as 48 epochs like KITTI) and have a look at how the model performs.

ok thanks I 'll try it

**Comment by caichuang0415** [comment]
> Oh, I guess the limited size of the dataset is a really big problem here. You can try to use more epochs for training (such as 48 epochs like KITTI) and have a look at how the model performs.

One more question, when you train it, do you use the train-val version? And how many epochs do you set, and How much time is the training phase? If tried if I use the train-val version of nuscense on a RTX 3090, it would cost me about 10 days to train it.

**Comment by Tai-Wang** [comment]
Our final model submitted to the test server uses the trainval set to fine-tune for 24 epochs with 8 or 16 GPUs. It should cost 1-2 days to finish it.
