### ISSUE TITLE
About fcos3d_mono for nuscenes

### ISSUE THREAD

**Issue by shudct** [open-mmlab/mmdetection3d#1377]
I notice that in nus-mono3d.py:

train_pipeline = [
    dict(type='LoadImageFromFileMono3D'),
    dict(
        type='LoadAnnotations3D',
        with_bbox=True,
        with_label=True,
        with_attr_label=True,
        with_bbox_3d=True,
        with_label_3d=True,
        with_bbox_depth=True),
    dict(type='Resize', img_scale=(1600, 900), keep_ratio=True),
    dict(type='RandomFlip3D', flip_ratio_bev_horizontal=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle3D', class_names=class_names),
    dict(
        type='Collect3D',
        keys=[
            'img', 'gt_bboxes', 'gt_labels', 'attr_labels', 'gt_bboxes_3d',
            'gt_labels_3d', 'centers2d', 'depths'
        ]),

'RandomFlip3D' transforms the bbox_2d, bbox_3d, centers2d and cam_intrinsic.
However, 'Resize' and 'Pad' still use the function in mmdet which only has bbox_2d's tranfromer. Is that normal?
Also, following this pipeline the image's shape is 3x928x1600, but the real output is 3x960x1600. I wonder is that something wrong?
hope for your reply!

**Comment by Tai-Wang** [comment]
1. We do not support Resize3D yet and padding zeros on the right/bottom of the image should not affect 3D bounding boxes. More transformations will be added soon.
2. Could you please point out specifically where you feel the image shape is unexpected?

**Comment by Tai-Wang** [comment]
Close due to inactivity.
