### ISSUE TITLE
FCOS3D Single GPU Test

### ISSUE THREAD

**Issue by Kwame261** [open-mmlab/mmdetection3d#1381]
For single_gpu_test, we construct the dataset class using the config:

    val=dict(

        type=dataset_type,

        data_root=data_root,

        ann_file=data_root + 'kitti_infos_val_mono3d.coco.json',

        info_file=data_root + 'kitti_infos_val.pkl',

        img_prefix=data_root,

        classes=class_names,

        pipeline=test_pipeline,

        modality=input_modality,

        test_mode=True,

        box_type_3d='Camera'),

Hello are the intrinsic camera parameters required   to make predictions using the 'single_gpu_test' function? Is that the reason for uploading the annotation file?  Thank you

**Comment by Tai-Wang** [comment]
1. Intrinsic parameters are used.
2. The coco-style json file is used to load input data while the pkl file is used for evaluation.

**Comment by Kwame261** [comment]
Thank You
