### ISSUE TITLE
Regarding Value Error

### ISSUE THREAD

**Issue by mreece813** [open-mmlab/mmdetection3d#1382]
I have been trying to run the pcd_demo on my files and i am getting this error. I have tried using both .pcd and .bin. this is the command 
!python demo/pcd_demo.py 0_with.bin configs/centerpoint/centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus.py checkpoint/centerpoint_01voxel_second_secfpn_circlenms_4x8_cyclic_20e_nus_20201001_135205-5db91e00.pth

This is the error i get. It is coming from the line of code 'result, data = inference_detector(model, pcd)'

ERROR:
![image](https://user-images.githubusercontent.com/29603698/162458575-13c46b0b-6935-4b77-afeb-68b9396b8c90.png)

**Comment by hansolo12334** [comment]
Have you solved this problem? I use the bin file under mmdetection3d-master\demo\kitti_000008 to run the demo without any error, but using the bin file converted by myself with ply will report the same error as you.

**Comment by hansolo12334** [comment]
May only allow input points that are integer multiples of dim

**Comment by Tai-Wang** [comment]
You need to guarantee the bin file contains the correct dimensions of point features, such as 4 in our provided demo case. If you use nuScenes config, you also need to make sure the point contains 5 feature dimensions.
