### ISSUE TITLE
Visualize 3d boxes in image

### ISSUE THREAD

**Issue by xyupeng** [open-mmlab/mmdetection3d#1387]
Hi,
I tried to project and visualize 3d boxes in the image plane, using `draw_lidar_bbox3d_on_img()` in `mmdet3d/core/visualizer/image_vis.py`. But it seems that the boxes are not very accurate. Here are what they look like:

NuScenes
<img width="914" alt="0c7826bb17d584254aa097aef2f3829" src="https://user-images.githubusercontent.com/99191637/162619637-4ab7b2ce-44f8-4999-a7ba-fdd78516d073.png">

Waymo:
![debug_0](https://user-images.githubusercontent.com/99191637/162619647-b8616f42-af9c-4ef0-a8fc-58fae2c4ae38.png)

The lidar boxes are from input_dict['anno_info']['gt_bboxes_3d'] (return of get_data_info(), before applying pipelines). Do you have any ideas about that?

**Comment by ZCMax** [comment]
It seems a little strange while visualizing nuscenes, more details should be offered to be reimplemented. As for waymo dataset, actually it's reasonable, the 3D Box label tend to be a little bit large, so the projected 3D label tend to be larger than usual.
