### ISSUE TITLE
The training log of the model PointPillars on the website cannot be opened

### ISSUE THREAD

**Issue by ansonlcy** [open-mmlab/mmdetection3d#1389]
I am using PointPillar (Backbone:FPN) to train on the Lyft dataset and would like to compare the experimental results, but I cannot open the training log file you have provided. The link is as follows: 
[https://download.openmmlab.com/mmdetection3d/v1.0.0_models/pointpillars/hv_pointpillars_fpn_sbn-all_2x8_2x_lyft-3d/hv_pointpillars_fpn_sbn-all_2x8_2x_lyft-3d_20210822.log.json](url)

**Comment by ZCMax** [comment]
It should be this link: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/pointpillars/hv_pointpillars_fpn_sbn-all_2x8_2x_lyft-3d/hv_pointpillars_fpn_sbn-all_2x8_2x_lyft-3d_20210822_095429.log.json

**Comment by ZCMax** [comment]
A PR is welcomed to fix the link error if you are willing and have time!

**Comment by ansonlcy** [comment]
> A PR is welcomed to fix the link error if you are willing and have time!

Thank you very much! I have submitted a PR.

**Comment by ZwwWayne** [comment]
resolved in https://github.com/open-mmlab/mmdetection3d/pull/1391
