### ISSUE TITLE
Pillar encoder cluster center calculation logic

### ISSUE THREAD

**Issue by dakey860831** [open-mmlab/mmdetection3d#1390]
Hi folks, recently looking into pillar encoding logic and just found [this section](https://github.com/open-mmlab/mmdetection3d/blob/333536f696264082813b404656eb3c2f0aca1c20/mmdet3d/models/voxel_encoders/pillar_encoder.py#L109-L111) a bit counter intuitive. Specifically, the denominator is taking valid number of points per-pillar into account, yet the numerator is not a masked sum. Checked the original impl, and seems this is consistent. I'd imagine the distance to cluster center would be quite over-valued if there is only a few valid points within the voxel.

**Comment by Tai-Wang** [comment]
Suppose we set a voxel that can contain up to 5 points, if we have 3 points for a voxel, then the other 2 point features should be padded with zeros. So the masked sum is equal to the direct sum of all the point features. I am not sure whether this is what you want to ask?
