### ISSUE TITLE
Error while trying ViViD Dataset

### ISSUE THREAD

**Issue by youssefAlaaThabet** [open-mmlab/mmdetection3d#1396]
I was trying to make a demo using  mvxnet model on  ViViD dataset "https://visibilitydataset.github.io/1_about.html" instead of kitti. I updated the annotation file with new calibration matrices. when i run this on the terminal. 

python3 demo/multi_modality_demo.py demo/data/kitti/kitti_000008.bin demo/data/kitti/kitti_000008.png demo/data/kitti/kitti_000008_infos.pkl configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py checkpoints/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class_20200621_003904-10140f2d.pth --show

I got this error:
Traceback (most recent call last):
  File "demo/multi_modality_demo.py", line 48, in <module>
    main()
  File "demo/multi_modality_demo.py", line 37, in main
    show_result_meshlab(
  File "/home/youssef/mmdetection3d/mmdet3d/apis/inference.py", line 493, in show_result_meshlab
    file_name = show_proj_det_result_meshlab(data, result, out_dir,
  File "/home/youssef/mmdetection3d/mmdet3d/apis/inference.py", line 410, in show_proj_det_result_meshlab
    show_multi_modality_result(
  File "/home/youssef/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 271, in show_multi_modality_result
    show_img = draw_bbox(
  File "/home/youssef/mmdetection3d/mmdet3d/core/visualizer/image_vis.py", line 126, in draw_lidar_bbox3d_on_img
    return plot_rect3d_on_img(img, num_bbox, imgfov_pts_2d, color, thickness)
  File "/home/youssef/mmdetection3d/mmdet3d/core/visualizer/image_vis.py", line 82, in plot_rect3d_on_img
    cv2.line(img, (corners[start, 0], corners[start, 1]),
OverflowError: signed integer is greater than maximum

**Comment by Tai-Wang** [comment]
It may be because no valid boxes can be projected and plotted on the image? Could you please add breakpoints to have a look at what happened on the intermediate outputs?

**Comment by youssefAlaaThabet** [comment]
when i tried to make a print of the line causing the error.  (corners[start, 0], corners[start, 1]) and (corners[end, 0], corners[end, 1])
i got this numbers 
(-93367133355785, -88569883078723)
(-93601507674339, -100912213577823)

**Comment by youssefAlaaThabet** [comment]
the output from printing the predicted result in show_result_meshlab in inference.py 
[{'pts_bbox': {'boxes_3d': LiDARInstance3DBoxes(
    tensor([[ 19.9958,   5.9103,  -1.8645,   0.6485,   0.7684,   1.7303,  -0.2628],
        [ 11.3112,  -7.3996,  -1.9930,   1.5801,   4.0521,   1.4246,   1.6837],
        [  2.9479,   4.0670,  -1.8037,   1.6974,   4.5353,   1.4247,  -1.5341],
        [ 20.7246,   3.0372,  -2.0806,   1.5779,   3.4585,   1.4838,  -1.5645],
        [ 16.8295,  -7.7401,  -2.0487,   1.6441,   4.1207,   1.4245,   1.6747],
        [ 22.0585,  -8.3004,  -2.0520,   1.5606,   3.5337,   1.4530,   1.7710],
        [ 56.5083, -21.9008,  -0.9682,   1.5860,   4.0138,   1.4439,   1.6769],
        [ 50.2853, -18.2986,  -1.3149,   1.6179,   3.7922,   1.5150,   2.8976],
        [ 34.1739,   0.5832,  -1.8599,   1.7518,   4.4573,   1.9286,  -1.2765],
        [ 34.5756,  35.9744,  -1.6112,   1.6238,   3.9421,   1.4881,   2.6870],
        [ 31.7996,  15.7422,  -1.6433,   1.6398,   3.8908,   1.5033,   2.8327],
        [ 24.4482,  18.4249,  -1.5973,   1.6467,   4.3765,   1.3558,  -2.5684]])), 'scores_3d': tensor([0.1708, 0.9381, 0.8592, 0.7604, 0.4859, 0.4173, 0.2216, 0.1257, 0.1215,
        0.1158, 0.1156, 0.1149]), 'labels_3d': tensor([0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])}}]

**Comment by Tai-Wang** [comment]
Sorry for the late reply. It's really strange that the boxes are normal while the corners have so large numbers. Have you traced the path of deriving these large numbers from these normal boxes?

**Comment by Tai-Wang** [comment]
Close due to inactivity.
