### ISSUE TITLE
Getting coordinates of 3d bounding boxes

### ISSUE THREAD

**Issue by Kwame261** [open-mmlab/mmdetection3d#1399]
{'boxes_3d': CameraInstance3DBoxes(
      tensor([[-2.3594e-01,  2.7743e+00,  1.1703e+01,  4.6064e+00,  1.4333e+00,
            1.8611e+00,  6.8023e+00,  4.5283e-02,  1.9048e-02],
          [-2.4122e-01,  2.7782e+00,  1.1508e+01,  4.4704e+00,  1.4654e+00,
            1.8735e+00,  6.5789e+00,  7.2991e-02,  1.0336e-02],
          [ 1.2031e+01,  4.3623e+00,  2.1965e+01,  4.0906e+00,  1.5845e+00,
            1.7902e+00,  3.4308e+00, -4.4967e-02,  1.1049e-02],
          [-2.8212e-01,  2.7348e+00,  1.1955e+01,  4.5655e+00,  1.4252e+00,
            1.8411e+00,  6.7001e+00,  1.8674e-02,  2.1849e-03],
          [ 1.1837e+01,  4.2633e+00,  2.1499e+01,  4.1025e+00,  1.5504e+00,
            1.7994e+00,  3.4418e+00, -3.9151e-02,  3.2802e-02],
          [-1.8281e-01,  2.6627e+00,  1.0745e+01,  4.5939e+00,  1.4981e+00,
            1.9038e+00,  6.5942e+00,  5.7417e-02,  1.7167e-02],
          [ 1.2192e+01,  4.4645e+00,  2.2295e+01,  4.0706e+00,  1.5864e+00,
            1.7937e+00,  3.4564e+00, -5.6807e-02,  1.3556e-02],
          [ 1.1680e+01,  4.1759e+00,  2.1098e+01,  4.0951e+00,  1.5746e+00,
            1.7934e+00,  3.4443e+00, -7.0537e-02,  3.2294e-03],
          [-1.9955e-01,  2.8441e+00,  1.2229e+01,  4.6245e+00,  1.4414e+00,
            1.8602e+00,  6.6655e+00, -7.5281e-03,  3.1128e-02],
          [ 1.1720e+01,  4.1254e+00,  2.0564e+01,  4.1770e+00,  1.5162e+00,
            1.8358e+00,  3.4372e+00, -3.1346e-02,  2.2138e-02],
          [ 4.9063e+00,  5.5173e-01,  1.1131e+01,  6.6752e-01,  1.8426e+00,
            6.1721e-01,  1.9229e+00, -3.0011e-01, -1.9632e-01],
          [-3.7075e+00,  1.7741e-01,  1.7110e+01,  6.3611e-01,  1.7913e+00,
            6.5560e-01,  1.0700e+00, -1.0996e-01, -6.9721e-01],
          [ 4.7996e+00,  5.3463e-01,  1.0918e+01,  6.8560e-01,  1.8636e+00,
            6.1712e-01,  2.3941e+00, -3.4258e-01, -2.0007e-01],
          [-4.2084e+00,  2.5156e-01,  1.5661e+01,  6.8072e-01,  1.7645e+00,
            6.8131e-01,  1.0361e+00, -5.1468e-02, -7.1910e-01],
          [-2.5194e+00,  2.8878e-01,  1.5766e+01,  6.6977e-01,  1.7861e+00,
            6.5454e-01,  1.1905e+00, -2.6416e-02, -6.4584e-02],
          [-2.4956e+00,  3.0091e-01,  1.5532e+01,  6.4946e-01,  1.7664e+00,
            6.7268e-01,  1.1720e+00, -2.3534e-02, -6.8875e-02],
          [ 4.7860e+00,  5.6563e-01,  1.0839e+01,  6.5850e-01,  1.8291e+00,
            6.0116e-01,  2.6650e+00, -3.5861e-01, -1.3425e-01],
          [-3.7457e+00,  1.7344e-01,  1.7303e+01,  6.3089e-01,  1.7863e+00,
            6.3621e-01,  1.0299e+00, -9.4412e-02, -5.0116e-01],
          [-4.1582e+00,  2.8276e-01,  1.5475e+01,  6.4530e-01,  1.7771e+00,
            6.9903e-01,  1.0515e+00, -8.0765e-02, -3.0611e-01],
          [-3.6525e+00,  2.0676e-01,  1.6878e+01,  5.9894e-01,  1.7937e+00,
            6.3543e-01,  1.0486e+00, -1.0532e-01, -2.0979e-01],
          [ 4.8628e+00,  4.8933e-01,  1.1267e+01,  7.1491e-01,  1.9184e+00,
            6.3298e-01,  2.1030e+00, -2.4584e-01, -2.2448e-01],
          [-2.5134e+00,  3.0901e-01,  1.5634e+01,  6.3797e-01,  1.7787e+00,
            6.5193e-01,  1.1375e+00,  2.6782e-02, -9.7134e-02],
          [-3.7364e+00,  1.3692e-01,  1.7232e+01,  6.3828e-01,  1.7902e+00,
            6.5700e-01,  1.0309e+00, -1.1361e-01, -2.9072e-01],
          [ 4.9482e+00,  5.1181e-01,  1.1428e+01,  7.2150e-01,  1.9057e+00,
            6.3678e-01,  1.7533e+00, -2.2583e-01, -1.9532e-01],
          [-3.6657e+00,  2.1085e-01,  1.6989e+01,  6.0609e-01,  1.8080e+00,
            6.3105e-01,  1.0282e+00, -8.5642e-02, -3.5804e-01],
          [ 5.0772e+00,  3.8609e-01,  1.1767e+01,  7.1803e-01,  1.8680e+00,
            6.5112e-01,  2.8873e+00, -3.5727e-01, -1.6497e-01],
          [-4.3630e+00,  1.9436e-01,  1.6236e+01,  6.9043e-01,  1.7817e+00,
            6.7894e-01,  1.0285e+00, -4.9707e-02, -1.3098e-01],
          [ 5.1636e+00,  3.5456e-01,  1.2189e+01,  7.1968e-01,  1.8820e+00,
            6.4643e-01,  2.5062e+00, -3.0686e-01, -1.6875e-01],
          [ 4.7493e+00,  4.7145e-01,  1.1997e+01,  7.4270e-01,  1.9725e+00,
            6.2147e-01,  1.7490e+00, -1.0951e-01, -1.8740e-01],
          [-4.5165e+00,  1.9095e-01,  1.6770e+01,  6.7811e-01,  1.8279e+00,
            6.5435e-01,  1.2098e+00, -5.9256e-02, -4.7501e-01],
          [-3.9171e+00,  1.8195e-01,  1.6838e+01,  6.9773e-01,  1.8139e+00,
            6.5306e-01,  1.2168e+00, -6.9339e-02, -1.0637e+00],
          [-4.3437e+00,  1.6557e-01,  1.6169e+01,  6.4724e-01,  1.7868e+00,
            6.2737e-01,  1.1503e+00, -5.7561e-02, -6.1163e-01],
          [-3.7730e+00,  1.7542e-01,  1.6495e+01,  6.4814e-01,  1.7947e+00,
            6.1771e-01,  1.1713e+00, -4.2796e-03, -3.4419e-01],
          [-3.6478e+00,  2.3343e-01,  1.6645e+01,  6.6701e-01,  1.8204e+00,
            6.3541e-01,  1.2993e+00, -7.6752e-02, -7.3087e-01],
          [-2.2824e+00,  5.1766e-01,  1.4576e+01,  6.7419e-01,  1.8822e+00,
            6.0315e-01,  1.3340e+00, -7.5299e-02, -1.8536e-01],
          [-2.5858e+00,  2.0531e-01,  1.6232e+01,  6.7065e-01,  1.7576e+00,
            6.5926e-01,  1.2242e+00, -1.7878e-02, -5.1106e-02],
          [-4.3120e+00,  2.5438e-01,  1.5924e+01,  6.6992e-01,  1.7981e+00,
            6.9561e-01,  1.0993e+00, -8.4697e-02, -4.3945e-01],
          [ 5.5106e+00,  1.2730e-01,  1.4118e+01,  5.6001e-01,  1.8170e+00,
            5.5196e-01,  1.5953e+00, -3.4209e-02, -1.2886e-01],
          [-3.6046e+00,  2.2729e-01,  1.6488e+01,  6.0341e-01,  1.8232e+00,
            6.3006e-01,  1.0941e+00, -9.0382e-02, -2.1657e-01],
          [-2.7014e+00,  2.7657e-01,  1.6534e+01,  6.8818e-01,  1.8291e+00,
            6.8412e-01,  1.2423e+00, -2.1291e-02, -4.6822e-02],
          [ 5.0399e+00,  3.1302e-01,  1.2764e+01,  6.8770e-01,  1.8566e+00,
            6.1511e-01,  1.9016e+00, -1.6390e-01, -9.3916e-02],
          [ 4.7238e+00,  6.2057e-01,  1.0675e+01,  6.3794e-01,  1.8524e+00,
            5.9061e-01,  2.0720e+00, -2.9217e-01, -8.6043e-02],
          [ 5.5669e+00,  1.0960e-01,  1.4270e+01,  5.9237e-01,  1.8107e+00,
            5.8321e-01,  1.6409e+00, -4.9989e-03, -1.2262e-01],
          [ 4.8866e+00,  4.8977e-01,  1.2281e+01,  7.7629e-01,  2.0356e+00,
            6.4169e-01,  1.6540e+00, -1.2779e-01, -1.8406e-01],
          [-2.5234e+00,  2.6387e-01,  1.6000e+01,  6.8814e-01,  1.7922e+00,
            6.3880e-01,  1.3507e+00, -1.0029e-01, -3.6801e-01],
          [-2.6090e+00,  3.2799e-01,  1.5967e+01,  6.5255e-01,  1.8415e+00,
            6.7690e-01,  1.2014e+00,  1.2935e-02, -5.3778e-02],
          [-2.5565e+00,  2.0771e-01,  1.5940e+01,  6.3085e-01,  1.7360e+00,
            6.1889e-01,  1.1230e+00, -4.5574e-02, -5.7171e-02],
          [ 4.8010e+00,  6.0344e-01,  1.0797e+01,  6.1713e-01,  1.8259e+00,
            5.8885e-01,  2.4532e+00, -3.2404e-01, -1.5095e-01],
          [-2.4373e+00,  3.1343e-01,  1.5534e+01,  6.5705e-01,  1.7818e+00,
            6.3349e-01,  1.1030e+00, -6.1909e-02, -1.0215e-01],
          [-2.7709e+00,  4.3952e-01,  1.5213e+01,  6.9620e-01,  1.8782e+00,
            6.0932e-01,  1.2824e+00, -3.8406e-02, -2.4326e-01],
          [-4.2299e+00,  2.4074e-01,  1.6080e+01,  6.7170e-01,  1.7873e+00,
            6.4744e-01,  1.0473e+00, -6.7717e-02, -2.3280e-01],
          [-3.6364e+00,  1.8879e-01,  1.6532e+01,  6.8357e-01,  1.7851e+00,
            6.3574e-01,  1.2360e+00, -2.8241e-02, -1.6412e-01],
          [ 4.9848e+00,  4.1130e-01,  1.1415e+01,  7.0492e-01,  1.8114e+00,
            6.3996e-01,  2.9594e+00, -3.5997e-01, -1.0490e-01],
          [-3.0398e+00,  2.3615e-01,  1.6209e+01,  6.8568e-01,  1.8055e+00,
            6.2646e-01,  1.2308e+00, -4.5631e-02, -2.2849e-01],
          [-3.5290e+00,  2.1005e-01,  1.6867e+01,  6.5015e-01,  1.7732e+00,
            6.3256e-01,  1.1423e+00, -1.2403e-01, -5.3854e-01],
          [-3.1657e+00,  2.2241e-01,  1.6419e+01,  6.8177e-01,  1.7999e+00,
            6.3759e-01,  1.2677e+00, -6.5506e-02, -8.1838e-01],
          [ 5.1033e+00,  5.8840e-01,  1.1274e+01,  6.6129e-01,  1.8128e+00,
            6.1829e-01,  2.7934e+00, -2.4223e-01, -1.2875e-01],
          [-4.1211e+00,  2.7020e-01,  1.5622e+01,  6.3585e-01,  1.7973e+00,
            6.4153e-01,  1.0650e+00, -9.2806e-02, -2.0520e-01],
          [ 5.1601e+00,  5.2569e-01,  1.1630e+01,  5.4567e-01,  1.6922e+00,
            5.8033e-01,  2.4158e+00, -2.3272e-01, -5.4384e-02],
          [-4.1663e+00,  2.9066e-01,  1.5332e+01,  6.2035e-01,  1.7863e+00,
            6.9185e-01,  1.1148e+00, -8.2096e-02, -1.4360e-01],
          [ 5.6821e+00,  1.1973e-02,  1.4556e+01,  5.6300e-01,  1.7751e+00,
            5.5516e-01,  1.5715e+00, -7.7879e-03, -1.6746e-01],
          [-3.4448e+00,  2.4006e-01,  1.6487e+01,  6.0567e-01,  1.7723e+00,
            6.2120e-01,  1.1125e+00, -1.0125e-01, -1.5568e-01],
          [ 4.8748e+00,  1.1685e-01,  1.7436e+01,  6.4967e-01,  1.7164e+00,
            6.0229e-01,  1.4853e+00, -3.1019e-02,  1.2395e-01],
          [-2.4644e+00,  3.7424e-01,  1.5333e+01,  6.0059e-01,  1.7226e+00,
            5.8530e-01,  1.2446e+00, -8.6425e-02, -8.1215e-01],
          [-3.6123e+00,  3.8179e-01,  1.6077e+01,  6.9785e-01,  1.8901e+00,
            6.2600e-01,  1.2453e+00, -3.1532e-02, -2.5694e-01]])),
  'scores_3d': tensor([0.4651, 0.1555, 0.1534, 0.1436, 0.1376, 0.1002, 0.0873, 0.0775, 0.0722,
          0.0703, 0.2813, 0.2712, 0.2545, 0.2327, 0.2054, 0.1682, 0.1600, 0.1590,
          0.1536, 0.1394, 0.1346, 0.1298, 0.1277, 0.1123, 0.1112, 0.1109, 0.0981,
          0.0979, 0.0830, 0.0821, 0.0808, 0.0796, 0.0756, 0.0753, 0.0747, 0.0725,
          0.0710, 0.0690, 0.0673, 0.0670, 0.0664, 0.0662, 0.0642, 0.0636, 0.0630,
          0.0611, 0.0611, 0.0609, 0.0603, 0.0595, 0.0588, 0.0586, 0.0576, 0.0574,
          0.0563, 0.0560, 0.0549, 0.0548, 0.0547, 0.0535, 0.0524, 0.0520, 0.0517,
          0.0512, 0.0506]),
  'labels_3d': tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
          7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
          7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]),
  'attrs_3d': tensor([6, 6, 7, 6, 7, 6, 7, 7, 6, 7, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 3, 2, 2,
          2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 3, 3, 2, 2, 2, 3, 2, 3, 2, 2, 3, 3, 3, 3,
          3, 2, 2, 2, 2, 2, 2, 3, 3, 2, 3, 2, 2, 2, 2, 3, 2])}]

                                                                   INFO:
 From : "the result includes the detected bboxes information, the CameraInstance3DBoxes includes all the detected bboxes info in format x, y, z, l, w, h, r. z is the depth info."

the parameters in the cordinates 'CameraInstance3DBoxes'  in are  9 compared compared to the  7 listed above in INFO. Please are are the extra parameters?

**Comment by Tai-Wang** [comment]
There can be additional attributes appended after the commonly defined 7 parameters, such as velocity along the x/y axis here on nuScenes.
