### ISSUE TITLE
Does anyone reproduce PETR or want to reproduce PETR?

### ISSUE THREAD

**Issue by qfwysw** [open-mmlab/mmdetection3d#1401]
Is there a big guy who reproduces PETR? Or a small partner who wants to reproduce PETR can contact me to reproduce him together.

**Comment by Guocode** [comment]
interested about bev transformer methods

**Comment by ywfwyht** [comment]
> reproduces

Hi, bro. @qfwysw 
 Is the reproduces PETR finished？ where is the code repository ?
