### ISSUE TITLE
Receiving Value Error when running inference command

### ISSUE THREAD

**Issue by mreece813** [open-mmlab/mmdetection3d#1402]
I am getting an error when trying to run the mmdet pcd_demo.py on my .bin files.
the file contains: x y z reflectance ring_index
the error is:
![image](https://user-images.githubusercontent.com/29603698/163576774-1d4e4923-1bfe-46bd-b247-c537bd8cbde2.png)

I am running on centerpoint configs. so my dimensions of the file should be correct with what I am using. 

Any help would be great thanks!

**Comment by Tai-Wang** [comment]
It seems your bin file is broken or does not have your mentioned 5-dim features, because 772056 should be equal to num_points * 5, while it can not be reshaped to (-1, 5).

**Comment by mreece813** [comment]
I have a code that create a pcd to bin file. I have confirmed that all of the dimensions were there. If you know of a code that can do that, that i could also use to make sure i am not losing any data during the conversation. That would be great. The points * 5 are the correct number as well.

**Comment by mreece813** [comment]
I have looked in to the size of the array. the number 772056 is only num_points * 4. the correct number should be 965070. does this mean i should change something in code or is it in my file?

**Comment by Tai-Wang** [comment]
Possibly when you convert pcd file to bin, you lose some dimensions. Please check the contents of both files.
