### ISSUE TITLE
What does torch.atan2(centers2d[:, 0] - cam2img[0, 2], cam2img[0, 0]) + bbox[:, 6] represent in FCOS3D decode_yaw function?

### ISSUE THREAD

**Issue by scuizhibin** [open-mmlab/mmdetection3d#1404]

**Comment by Tai-Wang** [comment]
For image-based methods, we regress its allocentric orientation (local yaw, alpha in KITTI) as bbox[:, 6] and derive the global yaw with this relationship. You can refer to [this blog](https://towardsdatascience.com/orientation-estimation-in-monocular-3d-object-detection-f850ace91411) for details of these two concepts.

**Comment by XuDongHecs** [comment]
why not limit global yaw to [-pi, pi]?

**Comment by scuizhibin** [comment]
代码上是0到pai


---Original---
From: ***@***.***&gt;
Date: Mon, Apr 25, 2022 18:58 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmdetection3d] What does torch.atan2(centers2d[:, 0]- cam2img[0, 2], cam2img[0, 0]) + bbox[:, 6] represent in FCOS3D decode_yawfunction? (Issue #1404)




 
why not limit global yaw to [-pi, pi]?
 
&mdash;

**Comment by Tai-Wang** [comment]
Limit the predicted yaw to [0, pi] is because we only regress the yaw offset in the bin and we divide the 360-degree into two bins.
