### ISSUE TITLE
Bazel support

### ISSUE THREAD

**Issue by ytzhao** [open-mmlab/mmdetection3d#1408]
Hi all,

Is there any plan to do bazel support for mmdetection3d? 

Thanks,

**Comment by Tai-Wang** [comment]
We do not have such a plan in a short time. PR is definitely welcome if there is any solution.

**Comment by Tai-Wang** [comment]
I am not familiar with bazel. Out of curiosity, is there any case that bazel is a necessary or preferred choice to install mmdet3d? We will carefully consider this demand if it is important for a number of users.
