### ISSUE TITLE
AssertionError: Input boxes shape should be [N, 5] when train point_rcnn

### ISSUE THREAD

**Issue by zhongxiangzju** [open-mmlab/mmdetection3d#1409]
**Describe the bug**
This error appears when train point_rcnn using kitti.
The input shape of NMS in [point_rpn_head.py](https://github.com/open-mmlab/mmdetection3d/blob/c20b6cb637fa31b88b1c7b523116f4f606010094/mmdet3d/models/dense_heads/point_rpn_head.py#L340) is N\*7, while NMS function in [mmcv](https://github.com/open-mmlab/mmcv/blob/235c0253ab8806a2a2ee6954b4258a95358497ac/mmcv/ops/iou3d.py#L50) only accept input with shape N\*5 

**Reproduction**
mmdetection3d==1.0.0rc1
mmcv==1.4.8

**Comment by zhongxiangzju** [comment]
And I found that boxes3d is converted to bev before nms in origin code of [PointRCNN](https://github.com/sshaoshuai/PointRCNN/blob/1d0dee91262b970f460135252049112d80259ca0/lib/rpn/proposal_layer.py#L103).

**Comment by Tai-Wang** [comment]
Fixed in #1418 .
