### ISSUE TITLE
RuntimeError: hard_voxelize_forward_impl: implementation for device cuda:0 not found.

### ISSUE THREAD

**Issue by SuperDickHead** [open-mmlab/mmdetection3d#1413]

**Comment by SuperDickHead** [comment]
Thank you for your great work! Due to the outbreak in Shanghai, I lost my connection to my ubuntu server,so i have to use my 3060 laptop,I wonder if this is a Windows problem?

**Comment by SuperDickHead** [comment]
File "C:\Software\anaconda3\envs\open-mmlab\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
        return stream.closed
    ValueError: underlying buffer has been detached

This error occur at the last part of the anaconda prompt after i  pip install mm3d. I don't know if it deal with the issue. I 'm looking forward to your help.

**Comment by Tai-Wang** [comment]
Do you use pre-compiled mmcv with ops? If yes, I tried the installation on the Windows and it should be ok. I do not encounter your problem. Could you please provide more information such as your environment, mmcv and mmdet version or something else?

**Comment by SuperDickHead** [comment]
Thank you for your reply! I have solved this problem,it turn out that i have installed the wrong version of mmcv, and i think there is a little bit ambiguity existed in the get_started.md.Thank you for your great work again!

**Comment by Tai-Wang** [comment]
Glad to hear that. Could you please point out which description is a little ambiguous? We can refine the doc accordingly.

**Comment by atinfinity** [comment]
@Tai-Wang I encountered same error.

### Command

```shell
python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py
```

### Error message

The following message was displayed in training.

> RuntimeError: hard_voxelize_forward_impl: implementation for device cuda:0 not found.

### Version

I used this [Dockerfile](https://github.com/open-mmlab/mmdetection3d/blob/v1.0.0rc2/docker/Dockerfile).
And, I changed to the latest version(MMCV, MMDetection, MMSegmentation, MMDetection3D).

```
TorchVision: 0.7.0
OpenCV: 4.5.5
MMCV: 1.5.1
MMCV Compiler: GCC 7.4
MMCV CUDA Compiler: not available
MMDetection: 2.24.1
MMSegmentation: 0.24.1
MMDetection3D: 1.0.0rc2+76e351a
spconv2.0: False
```

### Consideration

> MMCV CUDA Compiler: not available

I found that MMCV(without GPU) was used in this training.
So, I add the following description to Dockerfile(reference: <https://github.com/open-mmlab/mmsegmentation/blob/v0.24.1/docker/Dockerfile#L22-L24>).

```docker
ARG PYTORCH
ARG CUDA
ARG MMCV
```

As a result, I solved this problem.

**Comment by jbohnslav** [comment]
For posterity: I had this issue as well, and I was able to solve it. When I was installing `mmcv-full`, I had to set the environment variables `MMCV_WITH_OPS="1" FORCE_CUDA="1"`.

**Comment by hadihdz** [comment]
@jbohnslav I have the same problem. Could you please tell me how exactly you installed mmcv-full? I am using these commands but no success yet:

export MMCV_WITH_OPS=1
export FORCE_CUDA=1
mim install "mmcv-full==1.6.2"

**Comment by hlnull** [comment]
Just for anyone who might read this issue in the future. 

I encountered the same problem and the following steps solved it.
```shell
mim uninstall mmcv
export MMCV_WITH_OPS=1
export FORCE_CUDA=1
mim install 'mmcv>=2.0.0rc4'
# reinstall mmdetection3d
pip install -v -e .
```

**Comment by RozbiyNick** [comment]
Just for anyone who might read this issue in the future.

I installed mmdetection3d following this official document(https://mmdetection3d.readthedocs.io/en/latest/get_started.html) and met the same problem.

@jbohnslav 's method did **NOT** solve this problem, but assuring the installation of compatible versions of `torch` and `mmcv` helped:

1. Creating environment and installing `torch`. I decided to install `mmcv` following this [instruction](https://mmcv.readthedocs.io/en/latest/get_started/installation.html) and found out that torch 2.1.x is required in this case, that's why I [installed torch 2.1.2](https://pytorch.org/get-started/previous-versions/):
```
conda create --name openmmlab python=3.8 -y
conda activate openmmlab
# My cuda version is 12.1 that's why cu121
pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121
```

2. Installing `mmengine`, `mmcv` and `mmdet`. Everything is the same as in official docs, but `mmcv` is [installed with pip for cuda 12.1 and torch 2.1](https://mmcv.readthedocs.io/en/latest/get_started/installation.html):
```
pip install -U openmim
mim install mmengine
pip install mmcv==2.1.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.1/index.html
mim install 'mmdet>=3.0.0'
```

3. Installing `mmdetection3d ` from source:
```
git clone https://github.com/open-mmlab/mmdetection3d.git -b dev-1.x
cd mmdetection3d
pip install -v -e .
```

Finally you can check the installation as is prescribed [in official docs](https://mmdetection3d.readthedocs.io/en/latest/get_started.html):
```
mim download mmdet3d --config pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car --dest .
python demo/pcd_demo.py demo/data/kitti/000008.bin pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth --show
```

**Comment by 1163710216** [comment]
I also have fixed this error by downgrading the pytorch version from 2.2.2 to 2.1.0
