### ISSUE TITLE
Waymo result

### ISSUE THREAD

**Issue by xyupeng** [open-mmlab/mmdetection3d#1415]
I test `configs\pointpillars\hv_pointpillars_secfpn_sbn_2x16_2x_waymoD5-3d-3class.py` with the given [model](https://download.openmmlab.com/mmdetection3d/v0.1.0_models/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymoD5-3d-3class/hv_pointpillars_secfpn_sbn_2x16_2x_waymoD5-3d-3class_20200831_204144-d1a706b1.pth). But the result is much under expectation.
![image](https://user-images.githubusercontent.com/99191637/164419269-797d45a8-3576-429f-9e2d-4f81624e67ee.png)

Can you check if the model is correct?

**Comment by xyupeng** [comment]
Also this is the test result for `configs\pointpillars\hv_pointpillars_secfpn_sbn_2x16_2x_waymoD5-3d-car.py` with this given [model](https://download.openmmlab.com/mmdetection3d/v0.1.0_models/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymoD5-3d-car/hv_pointpillars_secfpn_sbn_2x16_2x_waymoD5-3d-car_20200901_204315-302fc3e7.pth).
![image](https://user-images.githubusercontent.com/99191637/164452433-aa672e37-50a7-4dd6-aeb4-942e817db42e.png)
This is also abnormal.

**Comment by ZCMax** [comment]
The waymo checkpoints of all the models have not been updated, you need to switch the branch to v0.18.2 or before.

**Comment by xyupeng** [comment]
If I trained a model under v1.0.0r0, do I need to test under v0.18.2?

**Comment by ZCMax** [comment]
> If I trained a model under v1.0.0r0, do I need to test under v0.18.2?

if you trained a model under v1.0.0rc0, you don't need to test under v0.18.2. The checkpoint provided is trained under old coordinate systems (the code v0.18.2 and before)

**Comment by xyupeng** [comment]
May I know which part of code is related to the coordinate system update?

**Comment by ZCMax** [comment]
Actually it's related to too many code, maybe you can see details in this [PR](https://github.com/open-mmlab/mmdetection3d/pull/677).

**Comment by xyupeng** [comment]
Thanks so much for your quick replies. I have got normal test results under v0.18.1
