### ISSUE TITLE
'ConfigDict' object has no attribute 'workers_per_gpu' problem while testing a pretrained model

### ISSUE THREAD

**Issue by DiegoCollado27** [open-mmlab/mmdetection3d#1419]
im new to mmdetection and im trying to test some models, im running this command

`python tools/test.py configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --show
`

but this error shows up:
` File "tools/test.py", line 259, in <module>
    main()
  File "tools/test.py", line 151, in main
    setup_multi_processes(cfg)
  File "/home/diego/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/utils/setup_env.py", line 30, in setup_multi_processes
    if 'OMP_NUM_THREADS' not in os.environ and cfg.data.workers_per_gpu > 1:
  File "/home/diego/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 49, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'workers_per_gpu'
`
i guess its something dumb but i cant see what the problem is

thanks in advanced

**Comment by Tai-Wang** [comment]
Please follow the template for reimplementation problems to redescribe your issue.

**Comment by solidexu** [comment]
Same Issue, Strange
when I test votenet,  training process is ok
`python tools/test.py work_dirs/votenet_16x8_sunrgbd-3d-10class/votenet_16x8_sunrgbd-3d-10class.py work_dirs/votenet_16x8_sunrgbd-3d-10class/latest.pth --eval mAP`

the issue occurred like
`Traceback (most recent call last):
  File "tools/test.py", line 259, in <module>
    main()
  File "tools/test.py", line 151, in main
    setup_multi_processes(cfg)
  File "/home/*****/.local/lib/python3.8/site-packages/mmdet/utils/setup_env.py", line 30, in setup_multi_processes
    if 'OMP_NUM_THREADS' not in os.environ and cfg.data.workers_per_gpu > 1:
  File "/home/******/.local/lib/python3.8/site-packages/mmcv/utils/config.py", line 49, in __getattr__
    raise ex

AttributeError: 'ConfigDict' object has no attribute 'workers_per_gpu'`

**Comment by solidexu** [comment]
Guess what, just delete the workers_per_gpu in the following if condition, then it can move a step. I think maybe the configdict may be parsed not good.

**Comment by longningbo** [comment]
> 
I have the same problem, how did you solve it?

**Comment by VVsssssk** [comment]
Sure, I will fix it later.

**Comment by VVsssssk** [comment]
You can try to pull the newest mmdet master branch to resolve the problem.

**Comment by VVsssssk** [comment]
#1434

**Comment by longningbo** [comment]
> 

I have tried, however, the bug still exists.

**Comment by baowenzhang** [comment]
How is this problem solved? I have the same problem

**Comment by Tai-Wang** [comment]
@longningbo @baowenzhang What version of mmdet3d are you using?

**Comment by baowenzhang** [comment]
my problem has been solved. Thankful for you



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/29/2022 11:36 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [open-mmlab/mmdetection3d] 'ConfigDict' object has no attribute 'workers_per_gpu' problem while testing a pretrained model (Issue #1419) |

@***@***.*** What version of mmdet3d are you using?

**Comment by pinnintipraneethkumar** [comment]
> Guess what, just delete the workers_per_gpu in the following if condition, then it can move a step. I think maybe the configdict may be parsed not good.

hi, can you explain in detail where to change?
