### ISSUE TITLE
Show both prediction & GT boxes in one figure

### ISSUE THREAD

**Issue by YinengXiong** [open-mmlab/mmdetection3d#1424]
I try to use 
```Python
python tools/test.py {CONFIG.py} {CHECKPOINT} --show-dir ./ --show
```
to show both prediction and GT boxes in one image on validation dataset, but I found in `mmdet3d.models.detectors.single_stage_mono3d.py` there is
```Python
show_multi_modality_result(
    img, 
    None, 
    pred_bboxes)
```
How to use test.py to show both my model prediction and GT bboxes in one figure?

**Comment by ZCMax** [comment]
The source code of `show_multi_modality_result` is [here](https://github.com/open-mmlab/mmdetection3d/blob/ff159fe7ea2a45f9138487c1c4977d2f67676ebc/mmdet3d/core/visualizer/show_result.py#L220). It supports visualizing both prediction and GT bboxes together, you need to use `gt_bboxes = data['gt_bboxes_3d']._data.tensor` to extract the gt bboxes.
