### ISSUE TITLE
Data Format

### ISSUE THREAD

**Issue by wangxiyang2022** [open-mmlab/mmdetection3d#1426]
Hi, thanks for your code.

What is the data format of 2D detection for nuScence tracking？

for example:

![image](https://user-images.githubusercontent.com/71493146/165040413-df20c421-8782-46de-b1c2-b2b370bc1f7e.png)

"7e351605549547f8af19432917f23b73"（blue box）: that means frame?

"df3af96318c945c3b23080ced7720aa7"（red box）: I don't know what this is...

“0”：that means pedestrian？and "2" means car?

Thank you for your reply.

**Comment by Tai-Wang** [comment]
I guess they should be tokens for each `sample` and each `sample_data`. We do not support tracking on nuScenes, and I don't know where this result comes from. I think there is a more suitable place (other codebases or nuScenes official devkit repo) to post these issues, so I close this one temporarily.
