### ISSUE TITLE
FCOS3D 测试结果可视化，出现很多冗余框

### ISSUE THREAD

**Issue by chenxu93** [open-mmlab/mmdetection3d#1427]
采用FCOS3D默认配置训练+评测。可视化结果发现几乎每张图都有很多冗余的框，调小了测试nms阈值好像也没有较少冗余框，不知道具体原因。 测试可视化结果如下：
![image](https://user-images.githubusercontent.com/42310082/165063681-fbc38b56-2f6b-434b-8e7a-ab273fe924ab.png)

模型定量评测结果如下：
![image](https://user-images.githubusercontent.com/42310082/165063780-e0ec6883-be64-4c8d-aa3b-148856a84b62.png)

**Comment by Gigalomanicx** [comment]
> 可以参考之前的 issue 进行调整 #1024

我自己训练的模型也出现了这个问题，检测指标正常，但是在相机视图中有很多冗余3d框，请问https://github.com/open-mmlab/mmdetection3d/issues/1024#issuecomment-958705575 指的nms_thr 和score_thr位于哪里？在config里面吗？

**Comment by rlczddl** [comment]
调整了阈值后结果还是一般…
