### ISSUE TITLE
ValueError: buffer size must be a multiple of element size

### ISSUE THREAD

**Issue by zzzzzz-ddddd** [open-mmlab/mmdetection3d#1430]
ython demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py my_checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --out-dir data/output_result/

An error is reported during the execution of the test instruction. Kitti was successfully generated when this statement was executed for the first time_ 00000 8 folder and two files in it. However, this error occurs when this statement is executed.
Thank you for your help！

load checkpoint from local path: my_checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 44, in <module>
    main()
  File "demo/pcd_demo.py", line 31, in main
    result, data = inference_detector(model, args.pcd)
  File "/home/ubuntu/zdq/mmdetection3d/mmdet3d/apis/inference.py", line 140, in inference_detector
    data = test_pipeline(data)
  File "/home/ubuntu/zdq/mmdetection/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "/home/ubuntu/zdq/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 421, in __call__
    points = self._load_points(pts_filename)
  File "/home/ubuntu/zdq/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 398, in _load_points
    points = np.frombuffer(pts_bytes, dtype=np.float32)
ValueError: buffer size must be a multiple of element size

 conda list mmdet
# packages in environment at /home/ubuntu/anaconda3/envs/open-mmlab:
#
# Name                    Version                   Build  Channel
mmdet                     2.23.0                    dev_0    <develop>
mmdet3d                   1.0.0rc1                  dev_0    <develop>
conda list mmcv
# packages in environment at /home/ubuntu/anaconda3/envs/open-mmlab:
#
# Name                    Version                   Build  Channel
mmcv-full                 1.4.8                    pypi_0    pypi

**Comment by ZCMax** [comment]
It's strange, maybe you can try to load the bin file directly to check the file completeness.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
