### ISSUE TITLE
pointpillars detection head

### ISSUE THREAD

**Issue by Jsijon** [open-mmlab/mmdetection3d#144]
The paper of pointpillars uses ssd as detection head,
in mmedtection3d ssd is not used but Anchor3DHead instead.
am i right?

 where i can find more information about Anchor3DHead , and its differences from ssd,
 is it from a paper?

**Comment by ZwwWayne** [comment]
Their implementation is the same, though the name is `Anchor3DHead`. Both SECOND and PointPillars use similar so-called SSD heads in their paper, and the head is implemented and renamed as `Anchor3DHead` in MMDetection3D.
