### ISSUE TITLE
FCOS3D bbox_pred decode question

### ISSUE THREAD

**Issue by shudct** [open-mmlab/mmdetection3d#1442]
I notice in fcos_mono3d_head.py:185, bbox_pred only multiply stride when it is training. I wonder when testing, how is the procedure?
I have checked the function(get_bboxes) and not found similar procedure.
hope for your reply, thx

**Comment by Tai-Wang** [comment]
It should be only multiplying stride during inference because we need to predict the real value during inference while only need to predict the normalized target during training.
