### ISSUE TITLE
Applying bbox labels to a file

### ISSUE THREAD

**Issue by mreece813** [open-mmlab/mmdetection3d#1444]
Hello,
I am working with the mmdet3d code and trying to use the labels_3d that i get in the result file and want to run a for loop to add the labels to a json. i can not find out where and how i can access those numbers.

I already changed the box_3d_mode.py in the mmdet3d/core/bbox folder.

![image](https://user-images.githubusercontent.com/29603698/165863938-da18df6c-26e0-4b52-af00-abb91af1ef5d.png)

This is what i added to create a json and how to change the position values. But i am not able to get the label numbers from this. This is the results when i print it out from the pcd_demo.py file

![image](https://user-images.githubusercontent.com/29603698/165864079-4752b751-2213-4288-a261-7da7ba9f80a2.png)

If there is any idea on how to access the labels_3d that would be great. so i can add this to my json file

**Comment by Tai-Wang** [comment]
Sorry for the late reply. These keys including "boxes_3d", "labels_3d", and "scores_3d" are obtained [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/detectors/mvx_two_stage.py#L396) or similar places in other detectors.

**Comment by Tai-Wang** [comment]
Close due to inactivity. Please feel free to reopen it if there are any further questions.
