### ISSUE TITLE
S3DIS / 3D semantic segmentation

### ISSUE THREAD

**Issue by tjdgus6255** [open-mmlab/mmdetection3d#1455]
Hello.
I'm studying 3d semantic segmentation and I'm new in this field.

https://mmdetection3d.readthedocs.io/en/latest/datasets/s3dis_sem_seg.html

above link, I'm doing Datasets/S3DIS for 3D Semantic Segmentation part

But I don't know what to do after 'create dataset' section

Thanks in advance.

% final goal is visualization

**Comment by Xiangxu-0103** [comment]
After preparing the dataset, you can train the model with the prepared config. More details can be found [here](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/supported_tasks/lidar_sem_seg3d.md).

**Comment by tjdgus6255** [comment]
> After preparing the dataset, you can train the model with the prepared config. More details can be found [here](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/supported_tasks/lidar_sem_seg3d.md).

Thank you. I solved it :)
But there's another problem.
I close this issue and open another.
