### ISSUE TITLE
ValueError: The results file must be a pkl file 

### ISSUE THREAD

**Issue by tjdgus6255** [open-mmlab/mmdetection3d#1459]
py configs/pointnet2/pointnet2_ssg_16x2_cosine_50e_s3dis_seg-3d-13class.py --result work_dirs/pointnet2_ssg_16x2_cosine_50e_s3dis_seg-3d-13class/latest.pth --show-dir results 
Traceback (most recent call last):
  File "tools/misc/visualize_results.py", line 50, in <module>
    main()
  File "tools/misc/visualize_results.py", line 27, in main
    raise ValueError('The results file must be a pkl file.')
ValueError: The results file must be a pkl file.

==========================================================================

Hello.

python tools/misc/visualize_results.py ${CONFIG_FILE} --result ${RESULTS_PATH} --show-dir ${SHOW_DIR}
(EX. 
python tools/misc/visualize_results.py configs/pointnet2/pointnet2_ssg_16x2_cosine_50e_s3dis_seg-3d-13class.py --result work_dirs/pointnet2_ssg_16x2_cosine_50e_s3dis_seg-3d-13class/latest.pth --sho^Cdir results)

After running this command, I got the above ERROR.

What should I do for that?

Thanks in advance.

**Comment by Tai-Wang** [comment]
You should give a .pkl result file to --result instead of the checkpoint file.
