### ISSUE TITLE
attribute recognition in nuScenes

### ISSUE THREAD

**Issue by Fan-Yixuan** [open-mmlab/mmdetection3d#1465]
Dear author and community members, I am curious why the implementation of the attribute recognition task of the nuScenes dataset in mmd3d is achieved by directly specifying it as the default attribute instead of the predicted output of the network, considering that the evaluation metrics of nuScenes include AAE.

https://github.com/open-mmlab/mmdetection3d/blob/76e351a7a6b0b83d7dc729bdfee5f17743c72f76/mmdet3d/datasets/nuscenes_dataset.py#L327-L346

**Comment by Tai-Wang** [comment]
There are many alternative ways to predict attributes. This one in nuscenes_dataset.py is just an option. You can also refer to the [one](https://github.com/open-mmlab/mmdetection3d/blob/76e351a7a6b0b83d7dc729bdfee5f17743c72f76/mmdet3d/datasets/nuscenes_mono_dataset.py#L297) in nuscenes_mono_dataset.py to figure out the attribute predictions.
