### ISSUE TITLE
UserWarning: Please follow `getting_started.md` to install MinkowskiEngine.`

### ISSUE THREAD

**Issue by J0KERCHANCE** [open-mmlab/mmdetection3d#1468]
Hi there,

I'm new to python and pytorch, and I'm now learning to use mmdetection3d on my computer. So when I'm running the code from the verification with point cloud demo section in 'getting_started.md', some user warning came out and I am a bit confused what to do:

(open-mmlab) john@d4ce042gz5:~/mmdetection3d$ python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
/home/john/mmdetection3d/mmdet3d/models/backbones/mink_resnet.py:9: UserWarning: Please follow `getting_started.md` to install MinkowskiEngine.`
  warnings.warn(
/home/john/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py:84: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  warnings.warn(
load checkpoint from local path: checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

Can someone please help me with this? Thank you.

**Comment by ZwwWayne** [comment]
This simply means that MinKowskiEngine is not installed, but it does not affect the training of SECOND. So you are fine.
