### ISSUE TITLE
Convert nuscenes data to KITTI format

### ISSUE THREAD

**Issue by YinengXiong** [open-mmlab/mmdetection3d#1471]
I'm trying to do mono3d training on nuscenes dataset
My purpose is to use only CAM_FRONT in nuscenes data and convert to KITTI format and use similar metrics like AP11 & AP40, is there any scripts and suggestions?

**Comment by Tai-Wang** [comment]
You can either generate infos involving only front-camera data or only read front-camera images when getting image info in the NuScenes Dataset class.

**Comment by YinengXiong** [comment]
When creating the nuScenes dataset, will `create_data.py` use the data in the `sweeps` folder? I didn't down the `sweeps` folder

**Comment by Tai-Wang** [comment]
You can reduce the max_sweeps option to avoid using the sweeps data.

**Comment by Tai-Wang** [comment]
Close due to inactivity.

**Comment by aditya9710** [comment]
How do I convert the entire nuScenes dataset to KITTI? New to the MMDet3D framework so any help would be appreciated.
