### ISSUE TITLE
ensemble code

### ISSUE THREAD

**Issue by TianhaoFu** [open-mmlab/mmdetection3d#1472]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by Tai-Wang** [comment]
Please describe your issue in detail. Which ensemble code do you want?

**Comment by TianhaoFu** [comment]
> Please describe your issue in detail. Which ensemble code do you want?


hi, thanks for your reply

i want to use weighted box fusion(wbf) to ensemble the model,

thanks!

**Comment by Tai-Wang** [comment]
Currently, we only support common nms for merging output boxes from multiple models. As for other methods, we may not have more resources to support recently, and you can find other resources such as [this](https://github.com/ZFTurbo/Weighted-Boxes-Fusion).

**Comment by Tai-Wang** [comment]
Close due to inactivity.
