### ISSUE TITLE
KeyError: "There is no item named 'nbconvert/tests/exporter_entrypoint/eptest-0.1.dist-info/WHEEL' in the archive"

### ISSUE THREAD

**Issue by J0KERCHANCE** [open-mmlab/mmdetection3d#1480]
Hi there,

So when I installed the environment for mmdetection3d, I got this error and I searched on the internet and found nothing.

KeyError: "There is no item named 'nbconvert/tests/exporter_entrypoint/eptest-0.1.dist-info/WHEEL' in the archive"

Can someone please help me with it? Thanks.

**Comment by Tai-Wang** [comment]
Do you follow the instruction provided by mmdet3d and run the command `pip install -v -e .` under mmdetection3d home?

**Comment by Tai-Wang** [comment]
Close due to inactivity.

**Comment by kay-Lifeng** [comment]
Same as you! do you solve this problem now?

**Comment by Roywangj** [comment]
The same problem. Do you solve this problem now?

**Comment by BobLIUliuliu** [comment]
> 
Use 'pip install -v -e.' instead of 'python setup.py develop'


> The same problem. Do you solve this problem now?

**Comment by Roywangj** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
