### ISSUE TITLE
AttributeError: 'PartA2' object has no attribute 'test_cfg' 

### ISSUE THREAD

**Issue by udnqv** [open-mmlab/mmdetection3d#1481]
Hi,
I'm trying to run an evaluation on the PartA2 model. However, when I try run it, I get following error:
![image](https://user-images.githubusercontent.com/51906480/168238764-f0f113b3-9700-49c7-9a71-b17251d547c0.png)

Thanks in advance for the help!

**Comment by Tai-Wang** [comment]
Please follow the template for reimplementation problems to re-describe your issue. We will help reproduce and fix this bug.

**Comment by OSU-Haolin** [comment]
add        
self.train_cfg = train_cfg
self.test_cfg = test_cfg
after line 41 in parta2.py 
and then the problem solved

**Comment by VVsssssk** [comment]
I have fixed it in https://github.com/open-mmlab/mmdetection3d/pull/1538.
