### ISSUE TITLE
Visualization error on nuscene-mono3d-dataset

### ISSUE THREAD

**Issue by YinengXiong** [open-mmlab/mmdetection3d#1485]
I'm trying to use mmdet3d pretrained PGD checkpoint to show results on nuscenes dataset by using the command:

`CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node 4 --master_port 29600 tools/test.py \
configs/pgd/pgd_r101_caffe_fpn_gn-head_2x16_2x_nus-mono3d_finetune.py \
checkpoints/pgd_r101_caffe_fpn-gn-head_2x16_2x_nus-mono3d_finetune_20211114_162135-5ec7c1cd.pth \
--launcher pytorch \
--eval bbox --eval-options 'show=True' 'out_dir=work_dirs/pgd_nus_official'
`
and got an error:
`File "/data/Code/mmdetection3d/mmdet3d/datasets/nuscenes_mono_dataset.py", line 672, in show
    img = img.numpy().transpose(1, 2, 0)
AttributeError: 'numpy.ndarray' object has no attribute 'numpy'
`
 Since `img` is np.ndarray and then I change `img = img.numpy().transpose(1, 2, 0)` to `img = img.transpose(1, 2, 0)` and re-run the test code, another error occurs:

![image](https://user-images.githubusercontent.com/23168598/168531878-883210a2-4008-4e0d-9fcc-f725c150dc6d.png)

**Comment by YinengXiong** [comment]
my environment is:
`
TorchVision: 0.9.0+cu101
OpenCV: 4.5.5
MMCV: 1.4.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.19.0
MMSegmentation: 0.20.0
MMDetection3D: 1.0.0rc2+76e351a
spconv2.0: False
`

**Comment by erwangccc** [comment]
Hi, @YinengXiong, have you solved this problem? What's the solution for this issue?
