### ISSUE TITLE
Pointpillars - kitti modification possibilities

### ISSUE THREAD

**Issue by Jsijon** [open-mmlab/mmdetection3d#149]
if  i wanted to use another backbone or bbox_head from other models in mmdetection3d,
without major changes in code, could i do it ?

and what are those that would be compatible ?

thanks in advance

**Comment by ZwwWayne** [comment]
Yes you can. For backbones supported in MMDet3D, you only need to change the config. The [configs using `RegNet`](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/regnet/hv_pointpillars_regnet-400mf_fpn_sbn-all_4x8_2x_nus-3d.py) are examples. For other backbones like ResNet, you might need to change the stem layers as they are a little bit different, you can also take the regnet as an example [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/backbones/nostem_regnet.py).

**Comment by Jsijon** [comment]
for bbox_head, i can too?
can you give examples also? @ZwwWayne
