### ISSUE TITLE
FCOS3D测试结果不一致

### ISSUE THREAD

**Issue by LinkHS** [open-mmlab/mmdetection3d#1494]
最新代码使用`bash ./tools/dist_test.sh $cfg $ckpt 8 --eval `bbox`测试 [fcos3d预训练模型](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/fcos3d/README.md)，精度匹配不上，例如fineturn模型的测试精度只有mAP: 0.2572、NDS: 0.3617，低于mAP: 32.1、NDS: 39.5，另一个未finetune的模型也差不都掉这么多。

我回退到4.6号commit f747daab633c62f679660a524522a04fb713eecf和4.8号commit 22fdfde61bcbd128672b9dad63a80b98859e14的代码上测试结果一致。

复现命令如下：
```shell
cfg='configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d.py'
ckpt='model_zoo/mmdet3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210717_095645-8d806dc2.pth'
ckpt='model_zoo/mmdet3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_20210715_235813-4bed5239.pth'
bash ./tools/dist_test.sh $cfg $ckpt 8 --eval bbox
```

**Comment by Tai-Wang** [comment]
Please refer to #1483 . That may be caused by a recent update on NMS operations.
