### ISSUE TITLE
cuda error 9 in spconv/src/reordering_cuda.cu when the number of voxels is large.

### ISSUE THREAD

**Issue by Devoe-97** [open-mmlab/mmdetection3d#1495]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
   the same bug: https://github.com/open-mmlab/mmdetection3d/issues/945 
   I guarantee that the GPU is not out of memory.
2. The bug has not been fixed in the latest version.

**Describe the bug**
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mmdetection3d/mmdet3d/ops/spconv/conv.py", line 183, in forward
    out_features = Fsp.indice_subm_conv(features, self.weight,
  File "/home/mmdetection3d/mmdet3d/ops/spconv/functional.py", line 64, in forward
    return ops.indice_conv(features, filters, indice_pairs,
  File "/home/mmdetection3d/mmdet3d/ops/spconv/ops.py", line 116, in indice_conv
    return sparse_conv_ext.indice_conv_fp32(features, filters,
RuntimeError: mmdet3d/ops/spconv/src/reordering_cuda.cu 57
cuda execution failed with error 9

**Reproduction**
1. What command or script did you run?

```
python3 tools/train.py configs/path/to/my/config.py  --work-dir /foo
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
   yes; yes
3. What dataset did you use?
   NuScenes
**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment information and paste it here.
   ```
   sys.platform: linux
Python: 3.8.12 (default, Oct 13 2021, 19:56:45) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
GCC: gcc (GCC) 7.3.0
PyTorch: 1.7.1+cu110
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2+cu110
OpenCV: 4.4.0
MMCV: 1.4.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.3+92d5a87
   ```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]  pip 
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
The error occurs only when the number of voxels is large, e.g.  1500000.
```
out = self.conv(out)
  File "/usr/local/python/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mmdetection3d/mmdet3d/ops/spconv/conv.py", line 183, in forward
    out_features = Fsp.indice_subm_conv(features, self.weight,
  File "/home/mmdetection3d/mmdet3d/ops/spconv/functional.py", line 64, in forward
    return ops.indice_conv(features, filters, indice_pairs,
  File "/home/mmdetection3d/mmdet3d/ops/spconv/ops.py", line 116, in indice_conv
    return sparse_conv_ext.indice_conv_fp32(features, filters,
RuntimeError: mmdet3d/ops/spconv/src/reordering_cuda.cu 57
```

**Comment by Tai-Wang** [comment]
I would suggest you set the max_num of voxels to a similar number of given configs. 1500000 is quite a large number for the GPU to allocate corresponding memories.
