### ISSUE TITLE
what's the difference between mmdetection3d and openpcdet

### ISSUE THREAD

**Issue by mjjdick** [open-mmlab/mmdetection3d#15]
Hi, nice work!
And I am wondering about what is the differences between mmdetection3d and openpcdet?  they are both about pointcloud detection and both in open-mmlab?

**Comment by ZwwWayne** [comment]
Hi @mjjdick ,
1. MMDetection3D trains [faster than all the other codebases](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/benchmarks.md) including OpenPCDet. 
2. MMDetection3D is more than a codebase for LiDAR-based 3D detection. MMDetection3D now supports multi-modality/single-modality and indoor/outdoor 3D detection while OpenPCDet does not.

Overall, MMDetection3D is an officially endorsed project with high quality, while OpenPCDet is experimental.
