### ISSUE TITLE
About 3d detection scenario

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmdetection3d#1505]
Hello. Thanks for your work. I am currently doing some researches about 3d object detection, and I found that most datasets come from autonomous driving, where the cameras are installed in the cars. Are there any current datasets using the cameras fixed by the road, capturing the cars and people in the scene?

**Comment by CheungBH** [comment]
Thank you. I am downloading your dataset like KITTI and nuscenes. However, I feel confused about what to download and how to process when seeing your document in https://github.com/open-mmlab/mmdetection3d/blob/master/docs/zh_cn/data_preparation.md.
Take KITTI as an example, the documents only mentioned that I should **download the files**. However, there are tens of files needed to be downloaded, and I felt confused about which is needed. Also, I am not sure how to place the downloaded files before I process them. 
<img width="1295" alt="Screenshot 2022-05-27 at 12 25 16" src="https://user-images.githubusercontent.com/39186017/170629080-f5ee10a4-f545-4cb4-bdb4-f103029da4bc.png">

And so do nuscenes. I am unsure about which to download and how to place the files.
<img width="1142" alt="Screenshot 2022-05-27 at 12 25 22" src="https://user-images.githubusercontent.com/39186017/170629160-adc8b951-6560-4cc2-b4af-eb1c6bc48c2b.png">

**Comment by Tai-Wang** [comment]
For KITTI, please go to [this page](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d) and download the lidar/images/calib/labels files.
For nuScenes, please download the "Full Dataset (v1.0)" for 3D detection task.

**Comment by Tai-Wang** [comment]
Because the following discussion will not be about the original issue title, we will close it temporarily. Please feel free to pose new ones for other questions.
