### ISSUE TITLE
Wrong 'img_pad_shape'  in PointFusion!

### ISSUE THREAD

**Issue by Sakura1221** [open-mmlab/mmdetection3d#151]
**Describe the bug**
I saw the code about 'MVXNet' which fuses the feature of lidar and image (mmdetection3d.configs.mvxnet). Its  fusion method is 'PointFusion' which associates points and pixels by projection (mmdet3d.models.fusion_layers.point_fusion.py line 322). Its image data augumentation methods include Resizing, Flipping, Padding, so the coordinates on image obtained by projection should perform the same operation (mmdet3d.models.fusion_layers.point_fusion.py line 85). However, the Padding operate outputs tensors with different shapes, the smaller tensor will be padded again to keep the same shape before passed into the model (mmcv.parallel.collate.py line 42). We should adopt the 'input shape' instead of 'pad shape'!

**Reproduction**
I set batchsize to 2, you can view the data when collating the batch data (mmcv.parallel.collate.py line 80). Then you will find the same ori_shape (375, 1242), different pad_shapes (416, 1344) and (576, 1856), the same input_shape (576, 1856).

**Bug fix**
Change the 'pad shape' to 'input shape' (mmdet3d.models.fusion_layers.point_fusion.py line 333).

**Comment by ZwwWayne** [comment]
The pad shape for all images in a batch will be the same as indicated in mmdet [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L485). This is the final and actual sizes of the images sent to the model. We need `pad_shape` to obtain features because `F.grid_sample` uses relative coordinates to obtain the feature maps [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/fusion_layers/point_fusion.py#L105).

**Comment by Sakura1221** [comment]
> The pad shape for all images in a batch will be the same as indicated in mmdet [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/pipelines/transforms.py#L485). This is the final and actual sizes of the images sent to the model. We need `pad_shape` to obtain features because `F.grid_sample` uses relative coordinates to obtain the feature maps [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/fusion_layers/point_fusion.py#L105).

`Padding` operate has two mode, `pad_fixed_size`, `pad_size_divisor`, and `MVXNet` chooses the second which outputs different pad shapes. I have shown you an example that I find the same `ori_shape` (375, 1242, 3) and different `pad_shape` (416, 1344, 3), (576, 1856, 3) in a batch. When the images are sent to the model, they are collated into (2, 3, 576, 1856).

**Comment by ZwwWayne** [comment]
I see your points. The pad shape is not modified when the smaller images are further padded to be the same as the bigger images, which will cause misalignment.

**Comment by Sakura1221** [comment]
Can you retrain the model and update the benchmark? Misalignment has a great impact on the precision. I really want to know the effect of `PointFusion`. Thank you!
