### ISSUE TITLE
About the point cloud demo

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmdetection3d#1514]
Hello. Thanks for your great work. I am running your demos, and I succeeded. However, I have some confusion.
There are some demos using point cloud data as the input, and the point cloud data are stored in the .bin files (like https://github.com/open-mmlab/mmdetection3d/blob/master/demo/data/kitti/kitti_000008.bin & https://github.com/open-mmlab/mmdetection3d/blob/master/demo/data/scannet/scene0000_00.bin).
I wonder that are there any methods to visualize those files? And how I can obtain such files? Also, if I want to deploy the algorithms in a real-world scenario, can I obtain a same point-cloud-data using lidar with different brands and series?

**Comment by Tai-Wang** [comment]
You can load the point cloud data from the bin files with simple np.load function. Please refer to the way in our demo about how to process them. The "bin" file is a friendly format for saving and loading point cloud data, but may not be the best one for visualization, so we save these results in 'pcd' format or others.

When deploying in the real world, you may need to process the raw data output by different lidars and unify them in our provided formats. These are the standard formats commonly used in all the popular public datasets.

**Comment by CheungBH** [comment]
Thank you for your reply. I am clear about the definition now.
BTW, you mentioned that "**need to process the raw data output by different lidars**". Do you have any references about it? For example, which lidar is most-commonly used, and something like its corresponding preprocess code, etc?

**Comment by CheungBH** [comment]
Thank you for your reply. I have another problem about the point cloud.
I am running your pcd_demo.py, and I noticed that the point clouds are in the shape of (16897, 4), and its mode is Coord3DMode.DEPTH. I am not very clear about what the 4 dimensions mean in the actual world. Are there any references?

**Comment by ZCMax** [comment]
The 4th dimension should be `intensity`, and as for the origin of the final image, can you give a more detailed description?

**Comment by CheungBH** [comment]
Thanks for your reply. I am still wondering that what's the meaning of intensity?
As for the origin, maybe what I want to express is, how to find the (0, 0, 0) point in the image among those point clouds?

**Comment by ZCMax** [comment]
1. for `intensity`, you can refer to https://geodetics.com/lidar-intensity-applications/
2. for origin, we use Open3D to render the point cloud scene. And we set it in https://github.com/open-mmlab/mmdetection3d/blob/14c5ded49dd5df7a52368bd54c32a003c2521e1d/mmdet3d/core/visualizer/open3d_vis.py#L169, as for how to plot the origin in the scene, you can refer the open3d library usage.

**Comment by CheungBH** [comment]
The logic may be a little messy. That is, in some repo, there will be a "**webcam**" mode for the image-based algorithms, which allows users to use a connected webcam to capture videos, and conduct inference in a real-time mode. 
Will you provide such a real-time mode? In my opinion, the installation is much harder, right?

**Comment by ZCMax** [comment]
> The logic may be a little messy. That is, in some repo, there will be a "**webcam**" mode for the image-based algorithms, which allows users to use a connected webcam to capture videos, and conduct inference in a real-time mode. Will you provide such a real-time mode? In my opinion, the installation is much harder, right?

For now we do not support a so-called `webcam` mode for the image-based algorithms. You may need to find some other ways to achieve your goal.

**Comment by CheungBH** [comment]
> > The logic may be a little messy. That is, in some repo, there will be a "**webcam**" mode for the image-based algorithms, which allows users to use a connected webcam to capture videos, and conduct inference in a real-time mode. Will you provide such a real-time mode? In my opinion, the installation is much harder, right?
> 
> For now we do not support a so-called `webcam` mode for the image-based algorithms. You may need to find some other ways to achieve your goal.

Thank you for your reply. Have you done any researchers about the lidar itself? Like what kinds of lidar can generate a standard point cloud data, etc.

**Comment by Tai-Wang** [comment]
No. Currently, we mainly conduct experiments on standard benchmarks, where the point cloud data is collected by different standard LiDARs used by different companies.
