### ISSUE TITLE
error report when applied "pip inistall -v -e ."

### ISSUE THREAD

**Issue by Hoyyyaard** [open-mmlab/mmdetection3d#1517]
When I apply the command "pip inistall -v -e ."
It orruried error :" mmdet3d/ops/voxel/src/scatter_points_cuda.cu(272): error: no instance of overloaded function "at::Tensor::index_put_" matches the argument list
                argument types are: (at::Tensor, at::Tensor)
                object type is: at::Tensor"
torch                       1.10.0+cu111
cuda  11.1
ubuntu 20.04

**Comment by Tai-Wang** [comment]
Please follow the template for installation to re-describe your issue.
