### ISSUE TITLE
checkpoint file

### ISSUE THREAD

**Issue by qinsimon** [open-mmlab/mmdetection3d#152]
When I run:
python demo/pcd_demo.py demo/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

Then I got this issue:
UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
'The old API of register_module(module, force=False) '
Traceback (most recent call last):
File "demo/pcd_demo.py", line 28, in
main()
File "demo/pcd_demo.py", line 20, in main
model = init_detector(args.config, args.checkpoint, device=args.device)
File "/home/qindashuai/mmdetection3d/mmdet3d/apis/inference.py", line 35, in init_detector
checkpoint = load_checkpoint(model, checkpoint)
File "/home/qindashuai/anaconda3/envs/mmdet/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 247, in load_checkpoint
checkpoint = _load_checkpoint(filename, map_location)
File "/home/qindashuai/anaconda3/envs/mmdet/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 222, in _load_checkpoint
raise IOError(f'{filename} is not a checkpoint file')
OSError: checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth is not a checkpoint file

Is that the same problem with#27?and how to fix it? it will be nice if anyone could help me. XD

**Comment by ZwwWayne** [comment]
Have you downloaded the checkpoint file before using the demo?

**Comment by qinsimon** [comment]
> Have you downloaded the checkpoint file before using the demo?

I don't find chekcpoint files on the guide,you means I need to download them in somewhere?So could u plz tell me where can I find them?

**Comment by qinsimon** [comment]
> Have you downloaded the checkpoint file before using the demo?

After I downloaded the ckpt file, I still got this issue:
UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
