### ISSUE TITLE
Indoor and outdoor dataset

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmdetection3d#1520]
Hello. Thanks for your work. I noticed that there lots of dataset supported. I wonder which ones are indoor and which are outdoors?

**Comment by ZCMax** [comment]
Scannet \ SUN RGBD and S3DIS are indoor datasets, others are outdoor datasets.

**Comment by Tai-Wang** [comment]
This is what these two kinds of datasets are typically collected or organized.
