### ISSUE TITLE
fcos3d visualization error

### ISSUE THREAD

**Issue by LMerCy** [open-mmlab/mmdetection3d#1521]
fcos3d visualization error still exists after updating mmcv to 1.5.2, and i use dev branch of mmdet3d(commit id is e252ff540ec07d0d226197e2ece864bfdef781c5), according to this issue https://github.com/open-mmlab/mmdetection3d/issues/1483#issuecomment-1127308252

![image](https://user-images.githubusercontent.com/13573827/171101472-7e7ab5d8-4b89-4600-8e1d-376d633cfb02.png)

@filaPro do you have any idea?

**Reproduction**

```
python test.py xxxx/configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.py xxx/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210717_095645-8d806dc2.pth --out xxx/res.pkl --show --show-dir xxx/res

```
I haven't change anything of config and code.

**Environment**

TorchVision: 0.9.1
OpenCV: 4.5.5
MMCV: 1.5.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.24.1
MMSegmentation: 0.24.1
MMDetection3D: 1.0.0rc2+e252ff5
spconv2.0: False

**Comment by VVsssssk** [comment]
Hi, I think you can refer to this issue https://github.com/open-mmlab/mmdetection3d/issues/1024.

**Comment by LMerCy** [comment]
> Hi, I think you can refer to this issue #1024.

Thanks，i may  underrate the difference between 2d detection and 3d detection. I try to increase score_thr to 0.1 and decrese nms_thr to 0.5, some redundant  boxes will be removed which indicates the nms is working(if i contintune to decrease nms_thr to 0.1, most redundant boxes will be removed). It seems due to the depth error, fcos3d need much smaller nms_thr than 2d detection.
