### ISSUE TITLE
Downloading nuScene

### ISSUE THREAD

**Issue by CheungBH** [open-mmlab/mmdetection3d#1523]
I am going to download the nuScene dataset, but I noticed there are too many files to choose. I don't know which to download and how to place to process, since the document doesn't clearly specify it.

![image](https://user-images.githubusercontent.com/39186017/171317204-bc623493-a6db-46b4-a64f-2e4f6e448b98.png)

**Comment by VVsssssk** [comment]
What do you want to do by nus? You can download v1.0 nus at https://www.nuscenes.org/download.

**Comment by CheungBH** [comment]
Oh I am sorry that I uploaded a wrong image. I wonder if I need to download all the files in mini, trainval and test? Or I can simply download some of these? 
Also, I noticed that there are "US" & "Asia". Should I download it both?
![image](https://user-images.githubusercontent.com/39186017/171342604-376761f1-3586-4a36-88cb-51862e7cd878.png)

And what's the folder structure will look like before I process the data using
**python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes**

**Comment by ajinkyakhoche** [comment]
The folder structure is explained in nuscenes-devkit readme: https://github.com/nutonomy/nuscenes-devkit#nuscenes

If you only want to play around, you can download the mini dataset (first down arrow in your image). the functionality remains the same for mini and trainval. if later you do some training then download all the blobs of trainval and test. The US, Asia point to the same data, perhaps they host it in two different places, so you might get diff download speed depending on where you are.
