### ISSUE TITLE
About visualize

### ISSUE THREAD

**Issue by yeminglang** [open-mmlab/mmdetection3d#1530]
Hi,
All bboxs.obj have no label. How to give different colors(or labels) to different classes of bboxs.obj?
Thanks
![5f78459e743a9453ff42bff7cdc7735](https://user-images.githubusercontent.com/78740432/171866668-50ffdc3c-ed9f-467c-9701-4fd04ebf138a.png)

**Comment by Tai-Wang** [comment]
Please refer to #1050 .
