### ISSUE TITLE
Why ap @0.7 0.5 0.5 is worse than @0.7 0.7 0.7 ?

### ISSUE THREAD

**Issue by hustCYQ** [open-mmlab/mmdetection3d#1533]
![18b68815b40763fe5b45955331c1560](https://user-images.githubusercontent.com/39451786/172097607-ebe635b1-8641-425a-95fa-91163f6f78eb.png)

**Comment by Tai-Wang** [comment]
It's really strange. I guess there are some corner cases that the current evaluation code does not take into consideration. Maybe could you please find some specific samples that the 0.7 threshold takes at positive while 0.5 does not?

**Comment by Tai-Wang** [comment]
Temporarily close this issue due to inactivity. Please feel free to re-open it if there is any further question.
