### ISSUE TITLE
Custom/Constrained Bounding Box Loss Function

### ISSUE THREAD

**Issue by vinitveersingh** [open-mmlab/mmdetection3d#1534]
How can I add constrains to the bounding box loss function for CenterPoint?
https://github.com/open-mmlab/mmdetection3d/blob/14c5ded49dd5df7a52368bd54c32a003c2521e1d/mmdet3d/models/detectors/centerpoint.py#L73
I tried looking for the file where this function is located. However, I am unable to find where this function is located in [mmdetection3d](https://github.com/open-mmlab/mmdetection3d).
Also, I wasn't able to find a tutorial to add a custom loss function in the [tutorials](https://mmdetection3d.readthedocs.io/en/latest/tutorials/).

**Comment by Tai-Wang** [comment]
The basic principle is the same as mmdetection. Thanks for your feedback. Please refer to the related [tutorial](https://mmdetection.readthedocs.io/en/latest/tutorials/customize_losses.html) in mmdet and we will supplement it in mmdet3d afterward.
