### ISSUE TITLE
different FCOS3D AP11 results between table1 and table3 in PGD paper 

### ISSUE THREAD

**Issue by zhushibing** [open-mmlab/mmdetection3d#1535]
![image](https://user-images.githubusercontent.com/25739094/172287744-a6016655-7a26-42ec-acde-2ad910053bb1.png)
![image](https://user-images.githubusercontent.com/25739094/172287800-c78e7fca-4b21-4475-9deb-bc8f73c09932.png)

**13.90 11.61 10.98** and **9.55 5.51 4.78**
1) which one is the FCOS3D implementation?
2) if the higher is, what the implementation difference of the lower one? 

thank you for your reply !

**Comment by zhushibing** [comment]
@Tai-Wang

**Comment by Tai-Wang** [comment]
The version for ablation (Table 3) is a basic one of FCOS3D, almost without any modifications when transferring the nuScenes model to KITTI. After some hyperparameter tuning and adding some tricks (such as adding auxiliary 2D box/keypoint targets), it can be enhanced to some extent (results in Table 1). Similarly, you can find the performance of PGD is also improved accordingly in Table 1.

**Comment by zhushibing** [comment]
Thank you very much ! Another  problem， where can i download the supplemental materials mentioned in the pgd paper?

**Comment by zhushibing** [comment]
> The version for ablation (Table 3) is a basic one of FCOS3D, almost without any modifications when transferring the nuScenes model to KITTI. After some hyperparameter tuning and adding some tricks (such as adding auxiliary 2D box/keypoint targets), it can be enhanced to some extent (results in Table 1). Similarly, you can find the performance of PGD is also improved accordingly in Table 1.

**Comment by Tai-Wang** [comment]
You can find it in the [openreview page](https://openreview.net/forum?id=bEito8UUUmf) or in its [arxiv version](https://arxiv.org/abs/2107.14160).

**Comment by zhushibing** [comment]
thank you~

**Comment by zhushibing** [comment]
> You can find it in the [openreview page](https://openreview.net/forum?id=bEito8UUUmf) or in its [arxiv version](https://arxiv.org/abs/2107.14160).

thank you~
