### ISSUE TITLE
fcos3d annotation tool

### ISSUE THREAD

**Issue by Kwame261** [open-mmlab/mmdetection3d#1541]
Hello,

One again thank you for this  repo, I want to train on a custom vision only based dataset just like nuscenes.Please can you share a link on how I can label or annotate data for FCOS3D?

**Comment by Tai-Wang** [comment]
We just use public datasets for training. The public datasets mainly use LiDAR-based annotations to train Mono3D models, while a few (like CityScape3D) may use stereo images to annotate these labels.
