### ISSUE TITLE
FCOS3D and PGD：The finetune results do not achieve expectations.

### ISSUE THREAD

**Issue by WayneMao** [open-mmlab/mmdetection3d#1544]
**Describe the bug**
I find the finetune results of PGD and FCOS3D did not achieve expectations. 
I used the PGD 1x model you provided as a pretrain model to finetune, the final result as follows.
### PGD
  | mAP | NDS
-- | -- | --
mm3d official 1x finetune | 34.6 | 41.1
mm3d official 1x pretrain + finetune | 33.7 | 40.6

As we can see: the final result of mAP 33.7 is less than the official result 34.6. I test with the 1x finetune model you provid and the results is correct. 
In addition, I train the PGD1x model from scratch and the final result is as follows:

  | mAP | NDS
-- | -- | --
mm3d official 1x | 31.7 | 39.3
mm3d 1x(Ours) |32.3 | 39.3

As we can see: the final result of mAP 32.3 is more than the official result 31.7.

### FCOS3D
  | mAP | NDS
-- | -- | --
mm3d official 1x finetune | 32.1 | 39.5
mm3d official 1x pretrain + finetune | 31.8 | 39.2

**Reproduction**
1. What command or script did you run?
```
## PGD official test
bash ./tools/dist_test.sh configs/pgd/pgd_r101_caffe_fpn_gn-head_2x16_1x_nus-mono3d_finetune_official.py work_dirs/official/pgd_r101_caffe_fpn_gn-head_2x16_1x_nus-mono3d_finetune_20211118_093245-fd419681.pth 8 --eval mAP
## PGD train 
rlaunch --cpu=32 --gpu=8 --memory=250000 --preemptible no -- bash ./tools/dist_train.sh configs/pgd/pgd_r101_caffe_fpn_gn-head_2x16_1x_nus-mono3d_finetune.py 8
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
I just change the `load_from`(pretrain model path) in `configs/pgd/pgd_r101_caffe_fpn_gn-head_2x16_1x_nus-mono3d_finetune.py`
4. What dataset did you use?
Nuscenes v1.0

**Environment**
### PGD
```bash
sys.platform: linux
Python: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: GeForce RTX 2080 Ti
CUDA_HOME: /data/cuda/cuda-11.2/cuda
NVCC: Build cuda_11.2.r11.2/compiler.29558016_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.10.0+cu111
OpenCV: 4.5.5
MMCV: 1.4.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.20.0
MMSegmentation: 0.20.2
MMDetection3D: 1.0.0rc1+0cbe8d1
```
PS: We use **8 GPUs** to train models.

**Bug fix**

PPS:
![image](https://user-images.githubusercontent.com/35285052/172529472-e270f8b7-cd15-4baa-aabb-dab13efc85d8.png)
In FCOS3D paper, if `More epochs & ensemble` mean 2x or 3x ?

**Comment by WayneMao** [comment]
Thank you very much, I will try it as soon as possible.

And, another question:
In paper, pgd use lr=0.001 2x8 GPUs, but config is 0.004, see [pgd_lr](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/pgd/pgd_r101_caffe_fpn_gn-head_2x16_1x_nus-mono3d.py#L95).

I would like to know if lr=0.004 performs better?

**Comment by Tai-Wang** [comment]
You can just follow our provided config. It should yield a little better performance, especially when using only 1x schedule.
