### ISSUE TITLE
confuse about the camera projection matrix P in the PGD paper

### ISSUE THREAD

**Issue by zhushibing** [open-mmlab/mmdetection3d#1546]
![image](https://user-images.githubusercontent.com/25739094/172583388-f2573dd5-17cd-42d5-be77-eee39f4ed9c8.png)
![image](https://user-images.githubusercontent.com/25739094/172583463-8bfcd1df-065c-4df6-80e0-946a5b1a41af.png)
![image](https://user-images.githubusercontent.com/25739094/172583512-bf158cd9-a919-4e66-ae4f-46b205d04968.png)
first image is projection matrix P in PGD paper，second one is the projection matrix P in kitti paper，the third is sensor setup of kitti.
1）I guess the matrix in kitti paper assuming that bias between camera0 and camera_i can almost be zero in the y（down） and Z(forward) axis, according to this, i can derive the formula as following:
![image](https://user-images.githubusercontent.com/25739094/172590113-895fefa7-9951-4cb5-9558-97f4fc2b8e25.png)

However, the P in the PGD paper confused me，i think  the proejection formular can be eatablished based on bz=0. please explain the derivation process of this formula. Thank you! @Tai-Wang

**Comment by Tai-Wang** [comment]
Yes, the difference of by and bz in the two formulas is just because of the assumption of KITTI. We keep the by and bz to make this equation more precise. You can also derive the same relationship shown in the paper with non-zero by and bz. Please note that d is not necessarily equal to z.

**Comment by zhushibing** [comment]
> Yes, the difference of by and bz in the two formulas is just because of the assumption of KITTI. We keep the by and bz to make this equation more precise. You can also derive the same relationship shown in the paper with non-zero by and bz. Please note that d is not necessarily equal to z.
DD3D:
![image](https://user-images.githubusercontent.com/25739094/172760021-004ed07d-084c-4252-bdd5-551b4339153a.png)
SMOKE: 
![image](https://user-images.githubusercontent.com/25739094/172760074-0d579927-d422-4189-9977-e5b16bf5f2e0.png)

Thank you ! I may have misunderstood， I saw the depth in other papers like SMOKE or DD3D defines as the z-component of 3D bbox center，but the depth in PGD defines the distance from camera to 3D point ？

**Comment by Tai-Wang** [comment]
Not exactly. I mean z refers to the z-component of 3D center in the referenced camera coordinate system (before projection), while d refers to the depth/z-component of 3D center in the projected camera coordinate system. They are typically the same when the referenced camera is just the projected camera but different in KITTI if we take the minor offset bz into consideration.

**Comment by Tai-Wang** [comment]
The second equation is incorrect, you can have a check.
Actually, there is no need to split K out of P and derive the relationship between (x1,y1,z1) and (x2,y2,z2). You can directly consider the equation between (x1,y1,z1) and d (u', v', 1) as presented in the paper.

**Comment by wangwz6666** [comment]
![d5cd595c966249d81e2c3e208c17adaf-205873](https://user-images.githubusercontent.com/44573624/175256715-61543da7-cd05-45f9-9edd-13d95bf9e7f8.jpg)
I  think  zhushibing is right
