### ISSUE TITLE
Question about Voxel Coors

### ISSUE THREAD

**Issue by abhinavrai44** [open-mmlab/mmdetection3d#1551]
Voxel coors have the shape Nx(1+NDim) as shown here - https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/voxel_encoders/voxel_encoder.py#L232. What is the shape (1 + Ndim) ?

**Comment by ZCMax** [comment]
The Ndim represents the dimension of corresponding voxel coordinates (specifically multi-dim voxel index) of each points. and 1 should be the batch_id.
