### ISSUE TITLE
Does the repo support 2D detection on Waymo Dataset

### ISSUE THREAD

**Issue by kemaloksuz** [open-mmlab/mmdetection3d#1558]
Hi,

I could not see a config file corresponding to Waymo Dataset on 2D detection. Does this repo support this feature? If so, is there any configuration file that I can use to train an example model? 

Else if there is not such a config file, what if I try to generate a config file and train a standard Faster R-CNN, i.e. is that possible here or you recommend using mmdetection repo to do so?

Thanks

**Comment by ZCMax** [comment]
We offer a 2D detection example of training on nuimages, and you can find it in the configs. For waymo dataset, if you want to do 2D detection, you probably need to implement a Waymo2DDatset for loading data.
