### ISSUE TITLE
process multiple files in one run

### ISSUE THREAD

**Issue by tjdgus6255** [open-mmlab/mmdetection3d#1562]
Hello.

python ./demo/pc_seg_demo.py ./bin_folder/scene0000_00.bin configs/pointnet2/pointnet2_ssg_16x2_cosine_200e_scannet_seg-3d-20class.py work_dirs/pointnet2_ssg_16x2_cosine_200e_scannet_seg-3d-20class/latest.pth --device cuda:0

When I run above command line. I get one .pcd file.

But I want to get multiple files at once.

I think it could be possible to get multiple output files by receiving multiple input files.

Could you know how to do that?

Thanks in advance.

**Comment by ZCMax** [comment]
Please refer to this issue: https://github.com/open-mmlab/mmdetection/issues/1527.  And you can simply wrap the `inference_detector()` method.

**Comment by tjdgus6255** [comment]
Thank you for your reply.
I modified the code in a similar way.
