### ISSUE TITLE
Fcos kitti mono_det_demo TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by betterhalfwzm** [open-mmlab/mmdetection3d#1571]
python demo/mono_det_demo.py demo/data/kitti/kitti_000008.png demo/data/kitti/kitti_000008_infos.pkl configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.py models/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210717_095645-8d806dc2.pth
/disk/workspace/wangzhaoming/code/mmdetection3d/mmdet3d/models/backbones/mink_resnet.py:10: UserWarning: Please follow `getting_started.md` to install MinkowskiEngine.`
  'Please follow `getting_started.md` to install MinkowskiEngine.`')
load checkpoint from local path: models/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210717_095645-8d806dc2.pth
Traceback (most recent call last):
  File "demo/mono_det_demo.py", line 46, in <module>
    main()
  File "demo/mono_det_demo.py", line 33, in main
    result, data = inference_mono_3d_detector(model, args.image, args.ann)
  File "/disk/workspace/wangzhaoming/code/mmdetection3d/mmdet3d/apis/inference.py", line 250, in inference_mono_3d_detector
    for x in data_infos['images']:
TypeError: list indices must be integers or slices, not str

**Comment by ZCMax** [comment]
`demo/data/kitti/kitti_000008_infos.pkl` in your command is wrong,  you should use kitti json file. However, for now, we do not support the corresponding kitti demo json file, you can switch to nuscenes mono3d demo.

**Comment by betterhalfwzm** [comment]
> `demo/data/kitti/kitti_000008_infos.pkl` in your command is wrong, you should use kitti json file. However, for now, we do not support the corresponding kitti demo json file, you can switch to nuscenes mono3d demo.

if i train FCOS3d with kitti，how can i inference?

**Comment by ZCMax** [comment]
Please refer to our doc https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html, and you can find how to inference model on datasets
