### ISSUE TITLE
PGD Reimplementation

### ISSUE THREAD

**Issue by wangwz6666** [open-mmlab/mmdetection3d#1578]
When will the code for the depth propagation part of PGD be released in mmdet3D？

**Comment by Tai-Wang** [comment]
We are going through refactoring for mmdet3d recently. After it is done, we will consider adding these related new features to our plan.

**Comment by Tai-Wang** [comment]
> How long does it take to show the code?

It's hard to say because we have many more important features to support, but I will try my best to push this issue. Thanks for your interest.
