### ISSUE TITLE
missing pages in preparation of data

### ISSUE THREAD

**Issue by Jsijon** [open-mmlab/mmdetection3d#158]
The page that show how top prepare sunrgb data is missing
https://github.com/open-mmlab/mmdetection3d/data/sunrgbd/README.md

also for the scannet data too
https://github.com/open-mmlab/mmdetection3d/data/scannet/README.md

**Comment by ZwwWayne** [comment]
They are https://github.com/open-mmlab/mmdetection3d/blob/master/data/scannet/README.md
and https://github.com/open-mmlab/mmdetection3d/blob/master/data/sunrgbd/README.md

**Comment by ZwwWayne** [comment]
@yinchimaoliang Please have a check and update these links in getting_started.md

**Comment by ZwwWayne** [comment]
Fixed in https://github.com/open-mmlab/mmdetection3d/pull/159
