### ISSUE TITLE
Fix camera intrinsic in training?

### ISSUE THREAD

**Issue by voldemortX** [open-mmlab/mmdetection3d#1584]
Do correct me if I'm wrong, I don't know much about 3D.
The FCOS3D model does not explicitly predict camera intrinsic, so it would be better if the intrinsic is fixed?
However, in flip augmentation, it seems the intrinsic can be altered:

https://github.com/open-mmlab/mmdetection3d/blob/bb204696c19ded90121caea82e34fa3ff0bd131f/mmdet3d/datasets/pipelines/transforms_3d.py#L144

would the performance be better if the intrinsic is fixed and that change is transformed and applied to the point coordinates?

@Tai-Wang it seems this was a patch from #744

**Comment by voldemortX** [comment]
I'm doing flipping and affine transformations for monocular 3D prediction tasks (predict in camera coordinates). By searching through popular repos like mmdet3d, currently I'm unsure about whether I should fix the intrinsic matrix (or I should let the network learn that).

**Comment by Tai-Wang** [comment]
Currently, most monocular 3D detectors are not aware of the camera-intrinsic changes. This is indeed a problem, especially for directly estimating object depth from images captured by different cameras.

However, your mentioned code is another story: if we do not change the intrinsic matrix accordingly, the intrinsic perspective projection would be incorrect, i.e., we cannot get correct 2D locations in the image by projecting a 3D point with this matrix. This is a must to guarantee the correct geometric relationship.

**Comment by voldemortX** [comment]
> However, your mentioned code is another story: if we do not change the intrinsic matrix accordingly, the intrinsic perspective projection would be incorrect, i.e., we cannot get correct 2D locations in the image by projecting a 3D point with this matrix. This is a must to guarantee the correct geometric relationship.

Thanks for the quick reply! I mean what if  this adjustment is made directly to the points, instead of the K?

**Comment by Tai-Wang** [comment]
Sorry for the late reply. The adjustment/augmentation for points is also adopted in the RandomFlip3D. In summary, both the points and the projection matrix require the corresponding adjustment to guarantee the correctness of the projection relationship.

**Comment by voldemortX** [comment]
Thanks!
