### ISSUE TITLE
How to report FLOPS, Runtime and Model Size(model paramters) of the Model

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/mmdetection3d#1591]
Is there any method in the test or evaluation phase to measure the FLOPS, Runtime, and Model size or No of Parameters for the Model?

**Comment by Tai-Wang** [comment]
The doc for [benchmark](https://mmdetection3d.readthedocs.io/en/latest/benchmarks.html) and [log analysis](https://mmdetection3d.readthedocs.io/en/latest/useful_tools.html#model-complexity) may be helpful references for you.

**Comment by ammaryasirnaich** [comment]
Thanks @Tai-Wang for sharing the information
