### ISSUE TITLE
Waymo Evaluation Error - gt.bin returned non-zero exit status 127.

### ISSUE THREAD

**Issue by ArchipLab-LinfengZhang** [open-mmlab/mmdetection3d#1594]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help. YES
2. The bug has not been fixed in the latest version. YES

**Describe the bug**
I met problems when evaluating model performance on Waymo dataset. It seems that the detection results have been successfully and converted into the right format, but raise error when calling "waymo_format/gt.bin".

The nearby log is 

```
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 202/202, 0.2 task/s, elapsed: 1071s, ETA:     0s

Finished ...
/bin/sh: 1: mmdet3d/core/evaluation/waymo_utils/compute_detection_metrics_main: not found
Traceback (most recent call last):
  File "./tools/test.py", line 250, in <module>
    main()
  File "./tools/test.py", line 246, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/lthpc/codes/PointDistiller-Private/mmdet3d/datasets/waymo_dataset.py", line 302, in evaluate
    shell=True)
  File "/home/lthpc/anaconda3/envs/sg-point-distiller/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/lthpc/anaconda3/envs/sg-point-distiller/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'mmdet3d/core/evaluation/waymo_utils/compute_detection_metrics_main results/waymo-car/kitti_results.bin data/waymo/waymo_format/gt.bin' returned non-zero exit status 127.
terminate called after throwing an instance of 'std::runtime_error'
  what():  NCCL error in: /pytorch/torch/lib/c10d/../c10d/NCCLUtils.hpp:158, unhandled cuda error, NCCL version 2.7.8
ncclUnhandledCudaError: Call to CUDA function failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 28179) of binary: /home/lthpc/anaconda3/envs/sg-point-distiller/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1, 2, 3, 4, 5, 6, 7]
  role_ranks=[0, 1, 2, 3, 4, 5, 6, 7]
  global_ranks=[0, 1, 2, 3, 4, 5, 6, 7]
  role_world_sizes=[8, 8, 8, 8, 8, 8, 8, 8]
  global_world_sizes=[8, 8, 8, 8, 8, 8, 8, 8]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_ceun4kir/none_qy6sngbz/attempt_1/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_ceun4kir/none_qy6sngbz/attempt_1/1/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker2 reply file to: /tmp/torchelastic_ceun4kir/none_qy6sngbz/attempt_1/2/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker3 reply file to: /tmp/torchelastic_ceun4kir/none_qy6sngbz/attempt_1/3/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker4 reply file to: /tmp/torchelastic_ceun4kir/none_qy6sngbz/attempt_1/4/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker5 reply file to: /tmp/torchelastic_ceun4kir/none_qy6sngbz/attempt_1/5/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker6 reply file to: /tmp/torchelastic_ceun4kir/none_qy6sngbz/attempt_1/6/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker7 reply file to: /tmp/torchelastic_ceun4kir/none_qy6sngbz/attempt_1/7/error.json
```

**Reproduction**

1. What command or script did you run?

```
./tools/dist_test.sh configs/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymoD5-3d-3class.py pretrain/hv_pointpillars_secfpn_sbn_2x16_2x_waymoD5-3d-3class_20200831_204144-d1a706b1.pth 8  --eval waymo --eval-options 'pklfile_prefix=results/waymo-car/kitti_results'     'submission_prefix=results/waymo-car/kitti_results'
```

2. Did you make any modifications on the code or config? Did you understand what you have modified? 
No change.

3. What dataset did you use?
Waymo.

**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment information and paste it here.

sys.platform: linux
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Build cuda_11.1.TC455_06.29069683_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu111
OpenCV: 4.5.5
MMCV: 1.4.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1

2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

PyTorch is installed by pip. Note that experiments on the other datasets such as KITTI and nuScenes can be successfully run. Training on Waymo also has no errors.  

**Error traceback**
If applicable, paste the error trackback here.
Please refer to the attachment. 
[error_log.txt](https://github.com/open-mmlab/mmdetection3d/files/9000488/error_log.txt)

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Tai-Wang** [comment]
Please compile the file `compute_detection_metrics_main` as presented in the [documentation](compute_detection_metrics_main).

**Comment by JennySeidenschwarz** [comment]
Hey everyone :)
actually this [link](https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md/) does not exist anymore which is the one given in the [docs](https://mmdetection3d.readthedocs.io/en/latest/user_guides/train_test.html) here to install compute_detection_metrics_main. Any suggestsions?

**Comment by ddcrseven** [comment]
> Hey everyone :) actually this [link](https://github.com/waymo-research/waymo-open-dataset/blob/master/docs/quick_start.md/) does not exist anymore which is the one given in the [docs](https://mmdetection3d.readthedocs.io/en/latest/user_guides/train_test.html) here to install compute_detection_metrics_main. Any suggestsions?
> 
> EDIT: information now [here](https://mmdetection3d.readthedocs.io/en/latest/advanced_guides/datasets/waymo.html)
> 
> In case url changes again:
> 
> ```
> # download the code and enter the base directory
> git clone https://github.com/waymo-research/waymo-open-dataset.git waymo-od
> # git clone https://github.com/Abyssaledge/waymo-open-dataset-master waymo-od # if you want to use faster multi-thread version.
> cd waymo-od
> git checkout remotes/origin/master
> 
> # use the Bazel build system
> sudo apt-get install --assume-yes pkg-config zip g++ zlib1g-dev unzip python3 python3-pip
> BAZEL_VERSION=3.1.0
> wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
> sudo bash bazel-${BAZEL_VERSION}-installer-linux-x86_64.sh
> sudo apt install build-essential
> 
> # configure .bazelrc
> ./configure.sh
> # delete previous bazel outputs and reset internal caches
> bazel clean
> 
> bazel build waymo_open_dataset/metrics/tools/compute_detection_metrics_main
> cp bazel-bin/waymo_open_dataset/metrics/tools/compute_detection_metrics_main ../mmdetection3d/mmdet3d/evaluation/functional/waymo_utils/
> ```

Where is the file "configure.sh"?

**Comment by JennySeidenschwarz** [comment]
Ah true sorry! For me it worked without the `./configure.sh`, also did not find it...

**Comment by eezhang123** [comment]
@ddcrseven  Did you find  the file `./configure.sh`  ?
