### ISSUE TITLE
Coordinates in CenterPointHead

### ISSUE THREAD

**Issue by zeyuwang615** [open-mmlab/mmdetection3d#1595]
Do correct me if I'm wrong. I am new to 3D Detection.

It seems to me that the xy coordinates in the heatmap target in CenterPointHead are switched compared to the xy coordinates under bev. If that is correct, then the network has to learn how to transpose the feature map to predict the heatmap. Wouldn't it be better to use consistent coordinates?

[https://github.com/open-mmlab/mmdetection3d/blob/bb204696c19ded90121caea82e34fa3ff0bd131f/mmdet3d/core/utils/gaussian.py#L47](url)

**Comment by Tai-Wang** [comment]
Could you please clarify your question with more details? For example, as you observe, where does the feature map have inconsistent xyz orders before/in the CenterPointHead, and which implementation is different from what you expect?

**Comment by Tai-Wang** [comment]
Close due to inactivity.
