### ISSUE TITLE
why not calculate yaw difference based on rt_mat in convert() of box_3d_mode.py

### ISSUE THREAD

**Issue by BoomSky0416** [open-mmlab/mmdetection3d#1599]
When I tried to use BaseInstance3DBoxes.convert() to switch coordinate systems, I found one issue in this function.  The convert() function computed yaw difference with predefined coordinate systems rather than based on rt_mat. And I think the convert() function also should take velocity into account.

**Comment by Tai-Wang** [comment]
Yes, this is a problem for the current mmdet3d. We will support the conversion of yaw angles with rt_mat soon.
