### ISSUE TITLE
CBGSDataset with KITTI Dataset class

### ISSUE THREAD

**Issue by skprot** [open-mmlab/mmdetection3d#1604]
I have custom dataset converted to KITTI format but with class imbalance. Is it possible to use CBGSDataset with KITTI Dataset class?

**Comment by VVsssssk** [comment]
Yes, you need to add a get_cat_ids func in KittiDataset, just like https://github.com/open-mmlab/mmdetection3d/blob/3abd973717978969b0f98c8bfa3228a9ce27176a/mmdet3d/datasets/nuscenes_dataset.py#L154

**Comment by Zhuangyf8** [comment]
could you show the code def get_cat_ids(self, idx) in the kitti?
