### ISSUE TITLE
Outdated dockerfile 

### ISSUE THREAD

**Issue by lorepieri8** [open-mmlab/mmdetection3d#1605]
After the docker build, if I try a demo:

`python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth`

I get 

```
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 4, in <module>
    from mmdet3d.apis import inference_detector, init_model, show_result_meshlab
  File "/mmdetection3d/mmdet3d/__init__.py", line 36, in <module>
    f'MMDET=={mmdet.__version__} is used but incompatible. ' \
AssertionError: MMDET==2.19.0 is used but incompatible. Please install mmdet>=2.24.0, <=3.0.0.
```

It would be great to have docker updated to the latest packages.

**Comment by VVsssssk** [comment]
Thanks for your issue; I have updated dockerfile in https://github.com/open-mmlab/mmdetection3d/pull/1697.
