### ISSUE TITLE
IndexError: list index out of range when using create data for Kitti

### ISSUE THREAD

**Issue by srinivas-6** [open-mmlab/mmdetection3d#1618]
As per the documentation, I have created a symlink  of the dataset root to $MMDETECTION3D/data  and running the create data script to generate info files throws error

```
python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti
```

**Environment**

Using Conda Environment and below is the necessary info

sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-11.6
NVCC: Cuda compilation tools, release 11.6, V11.6.55
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.12.0
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.0
OpenCV: 4.6.0
MMCV: 1.5.3
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.6
MMDetection: 2.25.0
MMSegmentation: 0.26.0
MMDetection3D: 1.0.0rc3+eb5a5a2
spconv2.0: False

**Error traceback**

```
Traceback (most recent call last):
  File "tools/create_data.py", line 238, in <module>
    with_plane=args.with_plane)
  File "tools/create_data.py", line 31, in kitti_data_prep
    kitti.create_kitti_info_file(root_path, info_prefix, with_plane)
  File "/home/ravuri/workspace/mmdetection3d/tools/data_converter/kitti_converter.py", line 194, in create_kitti_info_file
    relative_path=relative_path)
  File "/home/ravuri/workspace/mmdetection3d/tools/data_converter/kitti_data_utils.py", line 294, in get_kitti_image_info
    return list(image_infos)
  File "/home/ravuri/miniconda3/envs/open-mmlab/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/home/ravuri/miniconda3/envs/open-mmlab/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/ravuri/miniconda3/envs/open-mmlab/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/ravuri/miniconda3/envs/open-mmlab/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ravuri/workspace/mmdetection3d/tools/data_converter/kitti_data_utils.py", line 230, in map_func
    annotations = get_label_anno(label_path)
  File "/home/ravuri/workspace/mmdetection3d/tools/data_converter/kitti_data_utils.py", line 137, in get_label_anno
    annotations['truncated'] = np.array([float(x[1]) for x in content])
  File "/home/ravuri/workspace/mmdetection3d/tools/data_converter/kitti_data_utils.py", line 137, in <listcomp>
    annotations['truncated'] = np.array([float(x[1]) for x in content])
IndexError: list index out of range

```

**Comment by VVsssssk** [comment]
Hi, I suggest you check your annotation file is available.
