### ISSUE TITLE
将PGD head 的GN改为BN训练，效果会差很多，越训练越差

### ISSUE THREAD

**Issue by betterhalfwzm** [open-mmlab/mmdetection3d#1623]
这个是什么原因导致的

**Comment by Tai-Wang** [comment]
FCOS3D和PGD改成BN应该收敛会变慢，但之前和其他同事沟通应该可以通过训练时间加长来改善，不过这可能是大规模数据集上的经验，KITTI上可能会有点tricky。

**Comment by clw5180** [comment]
> FCOS3D和PGD改成BN应该收敛会变慢，但之前和其他同事沟通应该可以通过训练时间加长来改善，不过这可能是大规模数据集上的经验，KITTI上可能会有点tricky。

请教下这里有什么理论依据么，即使设置了KITTI的batchsize=16*8gpu，依然和GN差很多；

**Comment by Isaac-xie** [comment]
@Tai-Wang @betterhalfwzm @clw5180 我将FCOS3D的GN修改为SyncBN后，batchsize=8*8GPU=64。
在nuscenes数据集上，NDS和mAP结果很低，MAP从0.35+降低到0.1，请问各位有什么解决建议吗？

**Comment by clw5180** [comment]
同求解答，感谢大佬 @Tai-Wang
