### ISSUE TITLE
the rotation bug in visualization

### ISSUE THREAD

**Issue by SakuraRiven** [open-mmlab/mmdetection3d#1628]
Hi, when I running the demo
```python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth```,

I found that the predicted 3d bboxes are not matched with original points

**Comment by SakuraRiven** [comment]
In addition, I tried to vis the detection results with meshlab by adding ```point.obj and pred.obj``` files. I just wondering that whether the results are matched? Because the bboxes seem donot contain reasonable car shape ...

**Comment by SakuraRiven** [comment]
https://github.com/open-mmlab/mmdetection3d/issues/1287#issuecomment-1184239720

The same issue

**Comment by Tai-Wang** [comment]
Duplicate with #1287 . We will discuss it here and try to fix it ASAP.
