### ISSUE TITLE
Why Pointpillars mAP is different from paper?

### ISSUE THREAD

**Issue by Sukbin-Lim** [open-mmlab/mmdetection3d#1629]
When i trained with mmdetection 3d, its mAP is definitely higher than paper's mAP. Is there any reason for it? Is it from sparse convolution?

**Comment by Tai-Wang** [comment]
There are some tricks found by the community afterward and we just add them in our implementation. You may refer to [this issue](https://github.com/open-mmlab/mmdetection3d/issues/648) for more details.
