### ISSUE TITLE
When resuming training I got an error: AssertionError: If capturable=False, state_steps should not be CUDA tensors.

### ISSUE THREAD

**Issue by Vaaaaaalllll** [open-mmlab/mmdetection3d#1631]
2022-07-15 05:54:34,818 - mmseg - INFO - workflow: [('train', 1)], max: 100 epochs
2022-07-15 05:54:34,822 - mmseg - INFO - Checkpoints will be saved to /content/model_save by HardDiskBackend.
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[<ipython-input-23-7336b75a740f>](https://localhost:8080/#) in <module>()
      6         validate=(not cfg.no_validate),
      7         timestamp=timestamp,
----> 8         meta=meta)

10 frames
[/usr/local/lib/python3.7/dist-packages/torch/optim/adam.py](https://localhost:8080/#) in _single_tensor_adam(params, grads, exp_avgs, exp_avg_sqs, max_exp_avg_sqs, state_steps, amsgrad, beta1, beta2, lr, weight_decay, eps, maximize, capturable)
    253             assert param.is_cuda and step_t.is_cuda, "If capturable=True, params and state_steps must be CUDA tensors."
    254         else:
--> 255             assert not step_t.is_cuda, "If capturable=False, state_steps should not be CUDA tensors."
    256 
    257         # update step

AssertionError: If capturable=False, state_steps should not be CUDA tensors.

I didn't have this error with the previous MMCV version.

Is there a way to fix this? Thank You,

**Comment by Tai-Wang** [comment]
You would better to post this issue under mmsegmentation because it seems a problem related to mmseg.

**Comment by Joaovsky** [comment]
What was it then, could you explain how you solved it? I'm experiencing that when resuming my training of MVXNET from epoch_3 using a dataset which is part from kitti, part from virtual kitti. And I just use detection, not segmentation.
