### ISSUE TITLE
how to overwrite mmdet3d.core.bbox.structures without modified source and re-compile

### ISSUE THREAD

**Issue by xiaoxiao42** [open-mmlab/mmdetection3d#1637]
Hello, thanks for your great work.

I want to add a function to BaseInstance3DBoxes class, but instead of modifing the source codes in mmdet3d, I build a new project with similar folder structures to mmdet3d which named pytrain.

Is there any way to add or midified function in BaseInstance3DBoxes without re-build source codes ?

**Comment by ZCMax** [comment]
Since the `BaseInstance3DBoxes` is not registered in the `Registry`, so it can not be implemented with `force` method, I think it's difficult to achieve your goal with no modification. If you just want to add a function to BaseInstance3DBoxes, I suggest you to directly modify the code.

**Comment by xiaoxiao42** [comment]
Thanks for your reply.
At last, the best way is modify the source code.
