### ISSUE TITLE
multi camera visualization

### ISSUE THREAD

**Issue by AndyYuan96** [open-mmlab/mmdetection3d#1638]
Hi, I want to visualize the multi-modality detector's result with nuscene dataset, but the project 3d result to 2d, and visualize in 2d only support one camera Kitti, I just wonder wether mmdet3d will support multi-camera 2d result visualization.

**Comment by ZCMax** [comment]
Of course, we will support multi-camera 2d result visualization. And it will be achieved before next month.

**Comment by AndyYuan96** [comment]
> Of course, we will support multi-camera 2d result visualization. And it will be achieved before next month.

many thanks.
