### ISSUE TITLE
Why sweeps_num=9 in centerpoint

### ISSUE THREAD

**Issue by lliuz** [open-mmlab/mmdetection3d#164]
I just wondering why it uses a different setting in centerpoint, dose it affect results?

**Comment by ZwwWayne** [comment]
It should be slightly better if you use `sweeps_num=10`. Using `sweeps_num=9` simply because the original CenterPoint uses this setting and we just keep that.

**Comment by tianweiy** [comment]
Yeah, I originally thought the rule requires in total 10 sweeps. (Instead, it only requires to use at most 10 **past** frames)
