### ISSUE TITLE
an error when testing nuscenes-dataset-mini in colab

### ISSUE THREAD

**Issue by RouDanCongJii** [open-mmlab/mmdetection3d#1641]
hallo,
when i use the command
`!python tools/test.py configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py /content/mmdetection3d/checkpoints/hv_pointpillars_secfpn_sbn-all_4x8_2x_nus-3d_20210826_225857-f19d00a3.pth --show-dir /content/mmdetection3d/results```
theres an error:

/content/mmdetection3d/mmdet3d/models/backbones/mink_resnet.py:10: UserWarning: Please follow `getting_started.md` to install MinkowskiEngine.
  'Please follow getting_started.md to install MinkowskiEngine.`')
/usr/local/lib/python3.7/site-packages/mmdet/utils/setup_env.py:39: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting OMP_NUM_THREADS environment variable for each process '
/usr/local/lib/python3.7/site-packages/mmdet/utils/setup_env.py:49: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py:560: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
/content/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py:85: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  'dir_offset and dir_limit_offset will be depressed and be '
load checkpoint from local path: /content/mmdetection3d/checkpoints/hv_pointpillars_secfpn_sbn-all_4x8_2x_nus-3d_20210826_225857-f19d00a3.pth
The model and loaded state dict do not match exactly

size mismatch for pts_bbox_head.conv_cls.weight: copying a param with shape torch.Size([140, 384, 1, 1]) from checkpoint, the shape in current model is torch.Size([80, 256, 1, 1]).
size mismatch for pts_bbox_head.conv_cls.bias: copying a param with shape torch.Size([140]) from checkpoint, the shape in current model is torch.Size([80]).
size mismatch for pts_bbox_head.conv_reg.weight: copying a param with shape torch.Size([126, 384, 1, 1]) from checkpoint, the shape in current model is torch.Size([72, 256, 1, 1]).
size mismatch for pts_bbox_head.conv_reg.bias: copying a param with shape torch.Size([126]) from checkpoint, the shape in current model is torch.Size([72]).
size mismatch for pts_bbox_head.conv_dir_cls.weight: copying a param with shape torch.Size([28, 384, 1, 1]) from checkpoint, the shape in current model is torch.Size([16, 256, 1, 1]).
size mismatch for pts_bbox_head.conv_dir_cls.bias: copying a param with shape torch.Size([28]) from checkpoint, the shape in current model is torch.Size([16]).
unexpected key in source state_dict: pts_neck.deblocks.0.0.weight, pts_neck.deblocks.0.1.weight, pts_neck.deblocks.0.1.bias, pts_neck.deblocks.0.1.running_mean, pts_neck.deblocks.0.1.running_var, pts_neck.deblocks.0.1.num_batches_tracked, pts_neck.deblocks.1.0.weight, pts_neck.deblocks.1.1.weight, pts_neck.deblocks.1.1.bias, pts_neck.deblocks.1.1.running_mean, pts_neck.deblocks.1.1.running_var, pts_neck.deblocks.1.1.num_batches_tracked, pts_neck.deblocks.2.0.weight, pts_neck.deblocks.2.1.weight, pts_neck.deblocks.2.1.bias, pts_neck.deblocks.2.1.running_mean, pts_neck.deblocks.2.1.running_var, pts_neck.deblocks.2.1.num_batches_tracked

missing keys in source state_dict: pts_neck.lateral_convs.0.conv.weight, pts_neck.lateral_convs.0.bn.weight, pts_neck.lateral_convs.0.bn.bias, pts_neck.lateral_convs.0.bn.running_mean, pts_neck.lateral_convs.0.bn.running_var, pts_neck.lateral_convs.1.conv.weight, pts_neck.lateral_convs.1.bn.weight, pts_neck.lateral_convs.1.bn.bias, pts_neck.lateral_convs.1.bn.running_mean, pts_neck.lateral_convs.1.bn.running_var, pts_neck.lateral_convs.2.conv.weight, pts_neck.lateral_convs.2.bn.weight, pts_neck.lateral_convs.2.bn.bias, pts_neck.lateral_convs.2.bn.running_mean, pts_neck.lateral_convs.2.bn.running_var, pts_neck.fpn_convs.0.conv.weight, pts_neck.fpn_convs.0.bn.weight, pts_neck.fpn_convs.0.bn.bias, pts_neck.fpn_convs.0.bn.running_mean, pts_neck.fpn_convs.0.bn.running_var, pts_neck.fpn_convs.1.conv.weight, pts_neck.fpn_convs.1.bn.weight, pts_neck.fpn_convs.1.bn.bias, pts_neck.fpn_convs.1.bn.running_mean, pts_neck.fpn_convs.1.bn.running_var, pts_neck.fpn_convs.2.conv.weight, pts_neck.fpn_convs.2.bn.weight, pts_neck.fpn_convs.2.bn.bias, pts_neck.fpn_convs.2.bn.running_mean, pts_neck.fpn_convs.2.bn.running_var

[                                                  ] 0/81, elapsed: 0s, ETA:/usr/local/lib/python3.7/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352464346/work/aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[>>] 81/81, 1.3 task/s, elapsed: 62s, ETA:     0s`

And theres nothing in my results folder

Environment
sys.platform: linux
Python: 3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla P100-PCIE-16GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.12.0
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.0
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.25.0
MMSegmentation: 0.26.0
MMDetection3D: 1.0.0rc3+eb5a5a2
spconv2.0: False

another question
how can i install the old version of mmdet3d

thanks

**Comment by VVsssssk** [comment]
I have tried to test pp in the mini nus dataset, and it's useful. My cmd is:
```bash
python tools/test.py
configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py
https://download.openmmlab.com/mmdetection3d/v1.0.0_models/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d_20210826_104936-fca299c1.pth
--gpu-id
0
--show-dir
work_dir
```

**Comment by RouDanCongJii** [comment]
@VVsssssk 
hallo,
its cool for the evaluation. but there is nothing in my show dir folder. Can you provide your environment?

**Comment by VVsssssk** [comment]
I have fix it in https://github.com/open-mmlab/mmdetection3d/pull/1699
