### ISSUE TITLE
Errors occur in training pipeline using my own dataset

### ISSUE THREAD

**Issue by erty5852** [open-mmlab/mmdetection3d#1642]
Hello, I got some problems when I tried to train models with my own dataset. I followed tutorial 9 in docs, and dataset is ready in correct formats. After that I modified config in _./configs/_base_/datasets/nus-3d.py_ (the models configs I used are based on nuscenes) as tutorial mentions:

_dataset_A_train = dict(
    type='Custom3DDataset',
    ann_file = 'annotation.pkl',
    pipeline=train_pipeline
)_

After I ran the _tools/train.py_ ..., it reported bugs like:

  _File "/home/user/mmdetection3d/mmdet3d/datasets/pipelines/loading.py", line 202, in __call__
    ts = results['timestamp']
KeyError: 'timestamp'_

My first thinking is I need to modify _type='LoadPointsFromMultiSweeps'_ in train_pipeline in configs, because line 202 comes out from _class LoadPointsFromMultiSweeps_. Besides I don't have "sweeps" as nuscenes in my own dataset for sure, so it's perhaps meaningless for this part in the pipeline in my case.

But after I removed the dict of 'LoadPointsFromMultiSweeps' or make the dict empty (sorry i just give it a try), another error issues come out like _RuntimeError: mat1 dim 1 must match mat2 dim 0_. Bugs are from _torch_, so I really have no ideas to deal with it. 

So I would like to ask if somebody knows how to handle it in my case, if this errors comes out because of _LoadPointsFromMultiSweeps_ truly, and how to fix this so that the training pipeline succeeds. Thanks a lot!!!

**Comment by ZCMax** [comment]
`RuntimeError: mat1 dim 1 must match mat2 dim 0.` means that the rotation matrix dimension does not match, maybe like a situation: [3x3] x [4x3]. Besides, can you provide the error log file? Or it would be better if you can provide your annotation file if it's convienient.
