### ISSUE TITLE
Do benchmark.py and get_flops.py work for point cloud detection models too ?

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/mmdetection3d#1645]
I wanted to know if `tools/analysis_tools/benchmark.py` and `tools/analysis_tools/get_flops.py` also work for point clouds models for performance evaluation? As in the documentation, they are mostly referred with Image-based models.

**Comment by Tai-Wang** [comment]
Yes, you can have a try. Please let us know if there is any problem.
