### ISSUE TITLE
Can more detectors be trained with SUN-RGBD?

### ISSUE THREAD

**Issue by MSTK2014** [open-mmlab/mmdetection3d#1650]
Only 2 detectors(VoteNet and ImVoteNet) can be trained with SUN-RGBD so far. Can more detectors be trained with SUN-RGBD?

**Comment by Tai-Wang** [comment]
Currently no more, because there are still gaps between different datasets and model hyperparameters. I would encourage you to have some attempts by yourself if you have some experiences of using mmdet3d, and that will be interesting to successfully apply some models to a new dataset.
