### ISSUE TITLE
AssertionError: StepLrUpdaterHook: "warmup_iters" must be a positive integer

### ISSUE THREAD

**Issue by tuan97anton** [open-mmlab/mmdetection3d#1655]
My config : 
```
log_config:
  interval: 50
  hooks:
    -
      type: TextLoggerHook
    -
      type: TensorboardLoggerHook

lr_config: 
  policy : step
  warmup : linear
  step : [50]
```
I get error :
```AssertionError: StepLrUpdaterHook: "warmup_iters" must be a positive integer```

Who can help me fixbug? Thank you

**Comment by Tai-Wang** [comment]
This is not a typical format for mmdet3d config. Do you add new configs by yourself? Please show your config and provide more information.
