### ISSUE TITLE
Unknown data appears in training pointpillar

### ISSUE THREAD

**Issue by Fengshihao1** [open-mmlab/mmdetection3d#1656]
The first time the pointpillar was trained on the nuScenes dataset was normal, but the following data appeared during the second training:
‘’...
torch.Size([42917, 64, 128])
torch.Size([42917, 64])
torch.Size([55230, 64, 128])
torch.Size([55230, 64])
torch.Size([42622, 64, 128])
torch.Size([42622, 64])
torch.Size([63691, 64, 128])
torch.Size([63691, 64])
torch.Size([70426, 64, 128])
torch.Size([70426, 64])
torch.Size([83027, 64, 128])
...‘’
And I re-copy the source code from github for training, and this still occurs. How can I solve it please?

**Comment by Tai-Wang** [comment]
It's just because there are some print-debug codes not cleaned. You can just locate and remove them.

**Comment by Fengshihao1** [comment]
Thanks a lot for your answer. I have found the problem and solved it..


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdetection3d"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月3日(星期三) 下午2:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection3d] Unknown data appears in training pointpillar (Issue #1656)





 
It's just because there are some print-debug codes not cleaned. You can just locate and remove them.
