### ISSUE TITLE
The use of ObjectSample

### ISSUE THREAD

**Issue by Shiming94** [open-mmlab/mmdetection3d#1658]
Hi,

I wondered the role of the module `ObjectSample` in the train data pipeline. For example, to train the CenterPoint with the NuScenes dataset (CBGS seetings), `ObjectSample` is used, but the config file to train the PointPillars with the NuScenes doesn't use this module. When I committed this module in the Centerpoint training, it seems nothing influenced.

Thus, I would like to know the role of `ObjectSample` in the train data process and how to use it. Is it neceassary to process training data?

Looking forward to your reply.

Best,
Shiming

**Comment by Tai-Wang** [comment]
It's just a kind of data augmentation. The usage of it sometimes may bring performance gains while sometimes not. We usually add it when it brings some gains. Besides, we will typically respect the original implementations when reproducing other works.
