### ISSUE TITLE
waymo convert about CALIB file in kitti format！

### ISSUE THREAD

**Issue by credoxfromcqut** [open-mmlab/mmdetection3d#1661]
the parameters in camera.intrinsic [0:4] is the projection parameters toward to the waymo camera coordinate, and the tr_velo_to_cam(after transform) contains the transform from waymo camera coor to kitti's (T_front_cam_to_ref),but the projection parameter didnt,you just saved the 4 parameter without any transformation, i wonder if its a issue or some transformation i dont understand?

**Comment by Tai-Wang** [comment]
Could you please describe this issue more clearly with some references to specific codes?

**Comment by xyupeng** [comment]
I wonder in `save_calib()` in `tools/dataset_converters/waymo_converter.py`, why `T_vehicle_to_cam` is renamed as `Tr_velo_to_cam`? I think the vehicle frame and the LiDAR frame are not the same thing in Waymo. `T_vehicle_to_cam` is derived from camera.extrinsic, which is indeed the transformation from vehicle frame to camera frame. But how can it be renamed and used as the transformation from LiDAR to camera? Do I misunderstand anything?

**Comment by credoxfromcqut** [comment]
> I wonder in `save_calib()` in `tools/dataset_converters/waymo_converter.py`, why `T_vehicle_to_cam` is renamed as `Tr_velo_to_cam`? I think the vehicle frame and the LiDAR frame are not the same thing in Waymo. `T_vehicle_to_cam` is derived from camera.extrinsic, which is indeed the transformation from vehicle frame to camera frame. But how can it be renamed and used as the transformation from LiDAR to camera? Do I misunderstand anything?

point_in_cam = point_in_velo@Tr_velo_to_cam, i think the "cam" in Tr_velo_to_cam is just a virtual coordinate in kitti, it is just a bridge, as long as i can get the right point in camera coordinate, and it can be project to the ref image,it works. 
no 1 to 1 definition in this process, just pay attention to the results of transformation.
