### ISSUE TITLE
3DSSD runs in 13.23FPS, it is not reach 25FPS in the article, Does Pytorch runs lower than tensorflow?

### ISSUE THREAD

**Issue by Physu** [open-mmlab/mmdetection3d#167]
Thanks for sharing mmdetection3d framwork, It is gorgeous！
But I found a question，why mmdetection3d  3DSSD implementation runs slower? 
I modified mmdet3d/apis/test.py line29-49 as below:
```
    duration = []
    for i, data in enumerate(data_loader):
        with torch.no_grad():
            # added by physu, calculate the FPS
            start = time.time()
            result = model(return_loss=False, rescale=True, **data)
            end = time.time()
            duration.append(end - start)

        if show:
            model.module.show_results(data, result, out_dir)

        results.extend(result)

        batch_size = len(result)
        for _ in range(batch_size):
            prog_bar.update()
    time_sum = 0
    for i in duration:
        time_sum += i
    print("FPS : %f" % (1.0 / (time_sum / len(duration))))
```

FPS:13.23（official：25fps）

**Comment by ZwwWayne** [comment]
The time calculation in the code is inaccurate because the CUDA computation is asynchronous. To benchmark the speed, you should use [this script](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/benchmark.py). Our implementation basically follows that in TensorFlow but we have not checked the speed yet.

**Comment by ZwwWayne** [comment]
Furthermore, from the paper, we are not sure how they benchmarked their speed, so the speed tested in MMDetection's criterion might be different.

**Comment by Physu** [comment]
Thanks for you reply @ZwwWayne
