### ISSUE TITLE
Questions Related to the Latest Version of Waymo Dataset

### ISSUE THREAD

**Issue by huangzhengxiang** [open-mmlab/mmdetection3d#1672]
Hello! 
Does your code support the latest version of waymo dataset? Does your code support waymo v1.3.2? Is there still any problems related to the coordinate system in terms of waymo dataset now? 
I'll be really grateful if you can give any responses. Thank you!

**Comment by Tai-Wang** [comment]
We will support the latest waymo dataset and related baselines in near future (~1 month).
