### ISSUE TITLE
When I use the pointpillar model to infer my own point cloud data, there are errors. I don't know why.

### ISSUE THREAD

**Issue by zzzzzz-ddddd** [open-mmlab/mmdetection3d#1676]
My environment is as follows：

sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA GeForce GTX 1070 Ti
CUDA_HOME: /usr/local/cuda-11.3/bin
NVCC: Not Available
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.10.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.1+cu113
OpenCV: 4.5.5
MMCV: 1.5.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.23.0
MMSegmentation: 0.24.1
MMDetection3D: 1.0.0rc1+14c5ded

Running instructions：
python demo/pcd_demo.py demo/BIN/000001.bin configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py  checkpoints/epoch_80.pth

Errors occurred：
/home/ubuntu/project/ubuntu/zdq/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py:86: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  'dir_offset and dir_limit_offset will be depressed and be '
voxel_size[0] 0.16
voxel_size[1] 0.16
load checkpoint from local path: checkpoints/epoch_80.pth
voxels:> torch.Size([3384, 32, 4])
num_points:>> torch.Size([3384])
coors_batch:>>>>>- torch.Size([3384, 4])
voxels:>- torch.Size([3384, 32, 4])
num_points:>-- torch.Size([3384])
voxels-: torch.Size([3384, 32, 4])
coors:-- torch.Size([3384, 4])
num_points---: torch.Size([3384])
features torch.Size([3384, 32, 10])
mask-->> torch.Size([3384, 32, 1])
features- torch.Size([3384, 32, 10])
features-- torch.Size([3384, 1, 64])
voxel_features---- torch.Size([3384, 64])
batch_size----- 1
/home/ubuntu/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

I would appreciate your suggestions。

**Comment by Tai-Wang** [comment]
I don't see any error from the provided messages. All are warnings and you can just ignore them.

**Comment by WuYanXingege** [comment]
dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
(open-mmlab) root@96ce7df104e3:/mmdetection3d/mmdetection3d# python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py hv_second_secfpn_fp16_6x8_80e_kitti-3d-car_20200924_211301-1f5ad833.pth
/mmdetection3d/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py:85: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  'dir_offset and dir_limit_offset will be depressed and be '
load checkpoint from local path: hv_second_secfpn_fp16_6x8_80e_kitti-3d-car_20200924_211301-1f5ad833.pth
i have  no result
what is the problem?

> I don't see any error from the provided messages. All are warnings and you can just ignore them.

**Comment by ppsychoo** [comment]
Have solove it I have the same question!
