### ISSUE TITLE
RuntimeError: expected 2 dims but tensor has 3

### ISSUE THREAD

**Issue by Lzc6996** [open-mmlab/mmdetection3d#168]
I try to test your pretrained pointpillars model on waymo datasets, and get:
![Screenshot from 2020-10-16 13-49-43](https://user-images.githubusercontent.com/20632628/96218051-78cb8380-0fb6-11eb-87c3-31016d063829.png)

## Install setting
cuda = 10.1
torch = 1.6.0
mmcv-full = 1.1.5
mmdet = 2.5.0
mmdet3d = 0.6.1
running with docker you provided

**Comment by Tai-Wang** [comment]
Thanks for your bug report. I have just tried it with the same environment but without docker and it is ok, so I think it is related to docker. @ZwwWayne Let's check it.

BTW, please follow the template for bug report for us to better locate the problem.

**Comment by ZwwWayne** [comment]
The bug seems to be reported from the CUDA kernel, did you modify something in the code?

**Comment by Lzc6996** [comment]
@ZwwWayne  I didn't. 
![Screenshot from 2020-10-16 13-54-46](https://user-images.githubusercontent.com/20632628/96218363-2ccd0e80-0fb7-11eb-9f3e-0cd4dfe3b20b.png)

**Comment by Tai-Wang** [comment]
It seems that the points shape is incorrect. It should be [N, 5] and the voxels shape is affected, which should be [32000, 20, 5]. Which batch size and how many gpus do you use for testing?

**Comment by Lzc6996** [comment]
I dont have slurm, so i just run with command:
```
python tools/test.py configs/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car.py checkpoints/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth --out results/waymo-car/results_eval.pkl --eval waymo --options 'pklfile_prefix=results/waymo-car/kitti_results'
```
As shown in ``` tools/test.py Line 129-130```, I think it only used gpu0 and run single_gpu_test

**Comment by ZwwWayne** [comment]
DataParallel might have different and unexpected behaviors. For a single GPU, you can still use distributed training with dist_train.sh and set GPUS=1, the problem should be solved in this way.

**Comment by Lzc6996** [comment]
I'm not involved in training, I just want to test your pretrained models. The error is reported in tools/test.py.

**Comment by Tai-Wang** [comment]
Have you tried other datasets? Is there any bug?

**Comment by Lzc6996** [comment]
Not yet

**Comment by Lzc6996** [comment]
```
python tools/test.py  \ 
configs/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car.py \
checkpoints/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth \
--out results/waymo-car/results_eval.pkl \
--eval waymo --options 'pklfile_prefix=results/waymo-car/kitti_results'
```

**Comment by Tai-Wang** [comment]
> Thanks for your bug report. I have just tried it with the same environment and it is ok. Have you ever modified the code? Maybe you can print out the intermediate results to see the tensor's shape.
> 
> In addition, please follow the template for bug report for us to better locate the problem.

I have tried once I notice your bug report, but unfortunately I do not reproduce your bug. And combined with your error message, I guess it's not a specific bug for waymo.

**Comment by Lzc6996** [comment]
@Tai-Wang @ZwwWayne 
Thanks for your help. I have fixed my problem by using pytorch launcher as follow:
```
python -m torch.distributed.launch --nproc_per_node=4 tools/test.py configs/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car.py  checkpoints/hv_pointpillars_secfpn_sbn_2x16_2x_waymo-3d-car-9fa20624.pth --out  results/waymo-car/results_eval.pkl --eval waymo --options 'pklfile_prefix=results/waymo-car/kitti_results' --launcher pytorch
```
