### ISSUE TITLE
ModuleNotFoundError: No module named 'parrots'

### ISSUE THREAD

**Issue by Joaovsky** [open-mmlab/mmdetection3d#1680]
Thanks for your error report and we appreciate it a lot.

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

I'm trying to run the demo on my PC with CUDA 11.3 and it tells me there is no module parrots, even though parrots is the name of the torch version

What command or script did you run?

python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --show --snapshot

I didn't made any changes to the code.

When I run `python mmdet3d/utils/collect_env.py` or the above command, it prints:

Traceback (most recent call last):
  File "mmdet3d/utils/collect_env.py", line 2, in <module>
    from mmcv.utils import collect_env as collect_base_env
  File "/home/mola/anaconda3/envs/testtorch/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/mola/anaconda3/envs/testtorch/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/home/mola/anaconda3/envs/testtorch/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/home/mola/anaconda3/envs/testtorch/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 41, in <module>
    from .env import collect_env
  File "/home/mola/anaconda3/envs/testtorch/lib/python3.8/site-packages/mmcv/utils/env.py", line 13, in <module>
    from .parrots_wrapper import get_build_config
  File "/home/mola/anaconda3/envs/testtorch/lib/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 99, in <module>
    _ConvNd, _ConvTransposeMixin = _get_conv()
  File "/home/mola/anaconda3/envs/testtorch/lib/python3.8/site-packages/mmcv/utils/parrots_wrapper.py", line 50, in _get_conv
    from parrots.nn.modules.conv import _ConvNd, _ConvTransposeMixin
ModuleNotFoundError: No module named 'parrots'

When I go to line 50 of parrots_wrapper.py:

def _get_conv():
    if TORCH_VERSION == 'parrots':
        from parrots.nn.modules.conv import _ConvNd, _ConvTransposeMixin #This one
    else:
        from torch.nn.modules.conv import _ConvNd, _ConvTransposeMixin
    return _ConvNd, _ConvTransposeMixin

print(TORCH_VERSION) --> 1.10.1+cu102

I don't have pytorch, though with CUDA 10.2 in my other PC the demo works with no problem.

And the strangest is that in the other PC, this condition ( if TORCH_VERSION == 'parrots': ) is false, even though 
TORCH VISION has the same value in both PCs

Some of the packages that I use and their versions:

libtorch                  1.2.0.1                  pypi_0    pypi
torch                     1.5.0                    pypi_0    pypi
torch-scatter             2.0.9                    pypi_0    pypi
torch-tb-profiler         0.4.0                    pypi_0    pypi
torchvision               0.11.2                   pypi_0    pypi
openblas-devel            0.3.2                         0    anaconda
mmcls                     0.23.1                   pypi_0    pypi
mmcv-full                 1.6.0                    pypi_0    pypi
mmdet                     2.25.0                    dev_0    <develop>
mmdet3d                   0.5.2+fd20aab             dev_0    <develop>
mmpycocotools             12.0.3                   pypi_0    pypi
mmsegmentation            0.26.0                   pypi_0    pypi

**Comment by Tai-Wang** [comment]
Please use the latest mmdet3d. You installed mmdet3d is so out-of-date.

**Comment by Joaovsky** [comment]
Solved!
I updated miniconda to latest version which updated pip to latest version too.
That enabled me to install the latest installation of mmdet3d w/ pip install mmdet3d. 
mmdet3d = 1.0.0rc3
