### ISSUE TITLE
Kitti eval - wrong min_overlap

### ISSUE THREAD

**Issue by alexandrealmin** [open-mmlab/mmdetection3d#1685]
Hi, I think there is some bad behavior on model evaluation on kitti dataset.
In the `eval.py` script, the `eval_class` computes precision and recall for each class (pedestrian, cyclist, car), each difficulty (easy, moderate, hard) and each iou_thresholds triplet (strict or loose), but the `min_overlaps` thresholds do not seem to match with the wanted values.

In the following part of the code (`eval.py` file, around line 495), in the last line, I think `min_overlaps[:, metric, m]` should be replaced by `min_overlaps[:, difficulty, m]`, as the metric should not influence the min_overlap threshold chosen.

```
    for m, current_class in enumerate(current_classes):
        for idx_l, difficulty in enumerate(difficultys):
            rets = _prepare_data(gt_annos, dt_annos, current_class, difficulty)
            (gt_datas_list, dt_datas_list, ignored_gts, ignored_dets,
             dontcares, total_dc_num, total_num_valid_gt) = rets
            for k, min_overlap in enumerate(min_overlaps[:, metric, m]):
```

If I'm missing something here, please let me know :)

**Comment by VVsssssk** [comment]
Hi, here are defined min_overlaps https://github.com/open-mmlab/mmdetection3d/blob/c8347b7ed933d70fcfbfb73a3541046b8c8e8f5e/mmdet3d/core/evaluation/kitti_utils/eval.py#L687.  And I think `difficulty` is described of the object whether was occluded, so it's irrelevant of min overlap setting.

**Comment by alexandrealmin** [comment]
Hi @VVsssssk, Thanks for the help, issue https://github.com/open-mmlab/mmdetection3d/issues/185 help me to understand how overlaps thresholds are set
