### ISSUE TITLE
About fcos3d_mono for nuscenes in Config 

### ISSUE THREAD

**Issue by xiaowenhe** [open-mmlab/mmdetection3d#1694]
when I change Resize (1600,900) to (1200,675) in 
train_pipeline = [
dict(type='LoadImageFromFileMono3D'),
dict(
type='LoadAnnotations3D',
with_bbox=True,
with_label=True,
with_attr_label=True,
with_bbox_3d=True,
with_label_3d=True,
with_bbox_depth=True),
#dict(type='Resize', img_scale=(1600, 900), keep_ratio=True),
dict(type='Resize', img_scale=(1200, 675), keep_ratio=True),
dict(type='RandomFlip3D', flip_ratio_bev_horizontal=0.5),
dict(type='Normalize', **img_norm_cfg),
dict(type='Pad', size_divisor=32),
dict(type='DefaultFormatBundle3D', class_names=class_names),
dict(
type='Collect3D',
keys=[
'img', 'gt_bboxes', 'gt_labels', 'attr_labels', 'gt_bboxes_3d',
'gt_labels_3d', 'centers2d', 'depths'
]),
Other training parameters do not change, only change Resize.
T cannot get right detect boxes after finished training, Maybe cannot change Resize? Only must use the origin size of Image to train?

**Comment by ZCMax** [comment]
Please refer to https://github.com/open-mmlab/mmdetection3d/issues/1008
