### ISSUE TITLE
assertion error when changing samples_per_gpu in pointpilllars ( kitti 3class)

### ISSUE THREAD

**Issue by Jsijon** [open-mmlab/mmdetection3d#171]
i changed samples_per_gpu to 2 from default 6
and it gives me assertion error
in anchor_3dhead.py line 330
assert len(featmap_sizes) == self.anchor_generator.num_levels

why this happens?

**Comment by ZwwWayne** [comment]
Please use the `error template` or the `reimplementation issues` to report your bug. The information is limited to debug.

**Comment by Jsijon** [comment]
What command or script did you run?
python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py

Did you make any modifications on the code or config? Did you understand what you have modified?
i changed  the samples_per_gpu  from deafault 6 to 2

What dataset did you use?
Kitti

Enviroment information
sys.platform: linux
Python: 3.8.3 (default, Jul 2 2020, 16:21:59) [GCC 7.3.0]
CUDA available: True
CUDA_HOME: /
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GPU 0: GeForce GTX 1650 SUPER
GCC: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:

GCC 7.3
C++ Version: 201402
Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
OpenMP 201511 (a.k.a. OpenMP 4.5)
NNPACK is enabled
CPU capability usage: AVX2
CUDA Runtime 10.2
NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
CuDNN 7.6.5
Magma 2.5.2
Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,
TorchVision: 0.7.0
OpenCV: 4.3.0
MMCV: 1.0.5
MMDetection: 2.3.0
MMDetection3D: 0.5.0+5f7b31c
MMDetection3D Compiler: GCC 9.3
MMDetection3D CUDA Compiler: 10.1

**Comment by yinchimaoliang** [comment]
Hi! I followed your description and changed 'samples_per_gpu' in `kitti-3d-3class.py`, but I can't reproduce the error, can you be more specific about what you've changed and share your changed config?
