### ISSUE TITLE
 Is Resize3D supported?

### ISSUE THREAD

**Issue by betterhalfwzm** [open-mmlab/mmdetection3d#1712]
Is Resize3D supported?

**Comment by ZCMax** [comment]
Please check https://github.com/Tai-Wang/Depth-from-Motion/blob/ad167ac2a7cbf37df3e85417e6ca1cdf37d42f5d/mmdet3d/datasets/pipelines/transforms_3d.py#L2103

**Comment by Tai-Wang** [comment]
You can first refer to the provided implementation and we will support it in the next version.
