### ISSUE TITLE
a question about SECOND's voxel feature encoding (VFE) process

### ISSUE THREAD

**Issue by tony10101105** [open-mmlab/mmdetection3d#1723]
Hi,

I'm working on your SECOND implementation. I notice that, for the VFE module your SECOND uses, it seems HardSimpleVFE simply takes the average of all points in each voxel. While SECOND's paper mentioned they use fully-connected networks to conduct the voxel-wise feature extraction, same as VoxelNet. 

Could you explain more about your implementation if I miss some points?

**Comment by ZCMax** [comment]
Please refer to https://github.com/open-mmlab/mmdetection3d/issues/1375

**Comment by tony10101105** [comment]
Thanks!
