### ISSUE TITLE
In the validation result after model training, the AP is 0, and the rest of the metrics are 1

### ISSUE THREAD

**Issue by JesseTowne** [open-mmlab/mmdetection3d#1736]
The configuration file I used is hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py, but the dimensions of points and bbox have been added, and the pipeline has been modified accordingly. The data set is NuScenes v1.0-mini, and the verification result of the final model training is I am confused. Among the ten classes, nine classes have APs of 0, only one class has almost zero APs, and the rest of the corresponding metrics are also abnormal. I don't know what the problem is, so asking everyone for help!

The verification results are as follows:
——————————————————————————————————————————
Evaluating bboxes of pts_bbox
mAP: 0.0005
mATE: 1.0053
mASE: 0.9237
mAOE: 1.0125
mAVE: 0.9082
mAAE: 0.8850
NDS: 0.0286
Eval time: 3.0s

Per-class results:
Object Class AP ATE ASE AOE AVE AAE
car 0.005 1.053 0.237 1.112 0.266 0.080
truck 0.000 1.000 1.000 1.000 1.000 1.000
bus 0.000 1.000 1.000 1.000 1.000 1.000
trailer 0.000 1.000 1.000 1.000 1.000 1.000
construction_vehicle 0.000 1.000 1.000 1.000 1.000 1.000
pedestrian 0.000 1.000 1.000 1.000 1.000 1.000
motorcycle 0.000 1.000 1.000 1.000 1.000 1.000
bicycle 0.000 1.000 1.000 1.000 1.000 1.000
traffic_cone 0.000 1.000 1.000 nan nan nan
barrier 0.000 1.000 1.000 1.000 nan nan

**Comment by VVsssssk** [comment]
Hi, I find you have modified bbox dims, can you try to compare your model inference results with our provided model inference results? To make sure there are similar.

**Comment by JesseTowne** [comment]
> Hi, I find you have modified bbox dims, can you try to compare your model inference results with our provided model inference results? To make sure there are similar.

Thanks for your reminder, I used the original configuration file hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py to train on the NuScenes v1.0-mini dataset (without modifying the dimensions of points and bounding boxes), and found that its evaluation results are the same as The evaluation results for my modified model were similar, and I was wondering if it was because of the smaller capacity of the NuScenes v1.0-mini dataset. Do you have similar results?

**Comment by JesseTowne** [comment]
> Hi, I find you have modified bbox dims, can you try to compare your model inference results with our provided model inference results? To make sure there are similar.

Thanks for your reminder, I used the original configuration file hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py to train on the NuScenes v1.0-mini dataset (without modifying the dimensions of points and bounding boxes), and found that its evaluation results are similar to those of my modified model. I guess it is because of the relatively small capacity of the NuScenes v1.0-mini dataset. Do you have similar results?
