### ISSUE TITLE
PGD official Nuscenes pretrained model, test on KITTI Dataset

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection3d#1742]
Hello everyone! I download the official PGD model training on Nuscenes dataset here: https://download.openmmlab.com/mmdetection3d/v1.0.0_models/pgd/pgd_r101_caffe_fpn_gn-head_2x16_1x_nus-mono3d/pgd_r101_caffe_fpn_gn-head_2x16_1x_nus-mono3d_20211116_195350-f4b5eec2.pth
and test on KITTI dataset，also download model trained on KITTI dataset and test on Nuscenes, but the result seems weird:

![image](https://user-images.githubusercontent.com/40362306/185290249-bfaf72b9-ef31-4a03-b1bd-ee3d1807032c.png)
![image](https://user-images.githubusercontent.com/40362306/185290262-c10353b2-c1ac-408e-97ed-226071c6f771.png)

seems CAM_BACK is normal, but other camera like CAM_FRONT the pred_bbox is much bigger than gt:

![image](https://user-images.githubusercontent.com/40362306/185290137-bbff5ebe-2bf7-45b6-9a5d-800dd6c261f0.png)
![image](https://user-images.githubusercontent.com/40362306/185290197-dcbe1f54-60e0-46bd-bcaa-302c6556b5a5.png)

Nuscenes pretrained model and test on KITTI:
![image](https://user-images.githubusercontent.com/40362306/185289908-3dde19fb-fb11-4af6-b58b-aa8fe9b5cd72.png)
![image](https://user-images.githubusercontent.com/40362306/185289948-c3e3f468-2a36-4808-a6f3-372e236b7afc.png)

the pred_bbox is much smaller than gt, why this phenomenon?  Thanks a lot !

**Comment by YinengXiong** [comment]
In my view, mono3D model is very sensitive to camera intrinsics, in nuScenes dataset, different cameras have different intrinsics. The focal length `CAM_BACK` is around 800, similar to the focal length in KITTI dataset, so your 3D bbox is more accurate compared to the `CAM_FRONT` results

**Comment by clw5180** [comment]
> YinengXiong

Thanks, the fov / focal length matters.

**Comment by Verneinender** [comment]
@clw5180 Hi, I am wondering how you make it to test models that trained on Kitti on Nuscenes dataset. Could you please give me some instructions? Thank you so much!

**Comment by clw5180** [comment]
PGD detector already support KITTI and Nuscenes dataset both, you can check the config.
