### ISSUE TITLE
How to view label results for each predicted box?

### ISSUE THREAD

**Issue by damonftl** [open-mmlab/mmdetection3d#176]
I'm sure this is very simple, so hopefully someone can help me. I've successfully run test.py with an existing dataset (SUNRGB-D) on an existing model (VoteNet) all the way through, with an mAP output at the end and everything. I have each test output the point cloud and predictions, and those work too. Here's a screen capture from MeshLab:

![Screenshot from 2020-10-22 11-53-31](https://user-images.githubusercontent.com/61205651/96898049-4362e200-145d-11eb-8b06-b1e2d341f5c7.png)

What I can't figure out is how to get what each of those boxes represents. I know the large box in the middle is a bed, but is that what VoteNet thinks it was in this particular point cloud? How do I connect each box there in MeshLab to a label for each result? There does not seem to be any data output that I can find along those lines.

**Comment by yinchimaoliang** [comment]
For now ,we don't support to show labels during visualization., but in the next version of visualization, we will support it.

**Comment by damonftl** [comment]
Ok, thank you for the quick response! In the meantime I will look into at least outputting that data into a text file or something like that myself.

**Comment by koalaaaaaaaaa** [comment]
> For now ,we don't support to show labels during visualization., but in the next version of visualization, we will support it.

Hello, could you tell me that the visualization of label of boxes is available now？

**Comment by rebeccamart** [comment]
Hello, I have the same question. I get this result in MeshLab. 
@damonftl Did you manage to get the label names for each prediction with any method? Thanks in advance
![image](https://user-images.githubusercontent.com/103591525/166634632-129c3491-b234-4018-9f05-de468f531820.png)

**Comment by damonftl** [comment]
Hi, unfortunately I never did get it completely working. I managed to get it to output the label names into a console window but not in the actual 3D data, so it was still difficult to figure out exactly which box was which label. Sorry I can't really help. We ended up using a completely different neural network for our development.

**Comment by rebeccamart** [comment]
Thank you very much for the information.

**Comment by ApoorvaSuresh** [comment]
Hey @rebeccamart, did you figure out how to add label names to the final detections? Thank you in advance :)
