### ISSUE TITLE
what are the box-parameters when code_size is 9

### ISSUE THREAD

**Issue by ShunliRen** [open-mmlab/mmdetection3d#1766]
1.when code-size = 7, the box is (x,y,z,x_size,y_size,z_size,yaw)
when code-size = 9, what are the nine parameters?

2. Centerpoint implementation use code-size=9, why the output of box regression 10-dimensional?

thanks!

**Comment by ZCMax** [comment]
1. the other two dimension should be (velocity_x, velocity_y) for nuscenes dataset
2. 10-dimension should be task number
