### ISSUE TITLE
There is no implementation of 'sample_2d' in ObjectSample

### ISSUE THREAD

**Issue by YangHan-Morningstar** [open-mmlab/mmdetection3d#1768]
**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
Hi, I see in this [closed issue](https://github.com/open-mmlab/mmdetection3d/issues/36), you said you had supported it but I still can't find the code in the latest version, could your help me? Thanks a lot!

**Comment by Tai-Wang** [comment]
Please refer to the DBSampler in this [PR](https://github.com/open-mmlab/mmdetection3d/pull/327).
