### ISSUE TITLE
The checkpoint download is bad, on the Nuscenes dataset

### ISSUE THREAD

**Issue by KaiLong1** [open-mmlab/mmdetection3d#1772]
I have tried many of the official weighting documents (all published in August of '21), but the results seem to be poor.
--show visualization results are shown below:
![图片](https://user-images.githubusercontent.com/105500850/187058324-48e1024f-351f-44e4-9cfd-a48398bcf2b7.png)
![图片](https://user-images.githubusercontent.com/105500850/187058356-580fdd6e-a4a7-440b-854c-b9ae360dc29c.png)

--eval mAP results are shown below:
Evaluating bboxes of pts_bbox
mAP: 0.4024                                                                                                                                                                     
mATE: 0.4808
mASE: 0.4599
mAOE: 0.5178
mAVE: 0.4125
mAAE: 0.2955
NDS: 0.4846
Eval time: 3.8s

Per-class results:
Object Class	AP	ATE	ASE	AOE	AVE	AAE
car	0.887	0.188	0.155	0.136	0.094	0.080
truck	0.567	0.213	0.174	0.120	0.071	0.000
bus	0.872	0.401	0.116	0.034	0.588	0.172
trailer	0.000	1.000	1.000	1.000	1.000	1.000
construction_vehicle	0.000	1.000	1.000	1.000	1.000	1.000
pedestrian	0.872	0.135	0.283	0.287	0.204	0.099
motorcycle	0.535	0.265	0.324	0.636	0.070	0.013
bicycle	0.289	0.250	0.164	0.448	0.274	0.000
traffic_cone	0.001	0.355	0.383	nan	nan	nan
barrier	0.000	1.000	1.000	1.000	nan	nan

There may be some problems with these checkpoints. Where can I download the reconstructed checkpoint?
Thank you very much. Looking forward to your reply!

**Comment by KaiLong1** [comment]
I have found problems, one is that some Centerpoint weights have some problems, and the other is that the threshold needs to be adjusted in the visualization of the code, which is originally 0.1

**Comment by pengzhi1998** [comment]
Hi, thank you for pointing the problems out!! @KaiLong1 

May I ask which pretrained model (checkpoint) did you choose at last? And regarding the threshold, did you mean `evaluation_distance_treshold` or `score_threshold`? Which value did you set for them?

Thank you again and look forward to your reply!

**Comment by pengzhi1998** [comment]
Hi, thank you for pointing the problems out!! @KaiLong1 @Tai-Wang 

May I ask which pre-trained model (checkpoint) did you choose at last? And regarding the threshold, did you mean `evaluation_distance_treshold` or `score_threshold`? Which values did you set for them?

Thank you again and look forward to your reply!
