### ISSUE TITLE
These codes maybe meaningless and can cause an error in certain circumstances

### ISSUE THREAD

**Issue by medlen** [open-mmlab/mmdetection3d#1774]
Codes is in : https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/voxel_encoders/voxel_encoder.py#L162

```
for i in range(len(feat_channels) - 1):
            in_filters = feat_channels[i]
            out_filters = feat_channels[i + 1]
            if i > 0:                            # here
                in_filters *= 2
            norm_name, norm_layer = build_norm_layer(norm_cfg, out_filters)
            vfe_layers.append(
                nn.Sequential(
                    nn.Linear(in_filters, out_filters, bias=False), norm_layer,
                    nn.ReLU(inplace=True)))
```

These codes maybe cause an error if the feat_channels=[4, 96,  128, 240]

**Comment by Tai-Wang** [comment]
Thanks for your kind reminder. Could you please create a PR to make it more generalizable?

**Comment by medlen** [comment]
I tested this codes today, and I found out that I misunderstood  it, The code is ok. Sorry to bother you.
