### ISSUE TITLE
about the training data of the the pretraind model

### ISSUE THREAD

**Issue by yustaub** [open-mmlab/mmdetection3d#179]
hello, I am new to 3D object detection. I want to know what is the training data of kitti pretrained model, is it all the kitti 3D object training data? Very appreciate for your reply!

**Comment by ZwwWayne** [comment]
We use a specific train/val split following the standard practice. The preparation documentation is [here](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/getting_started.md#prepare-datasets).
