### ISSUE TITLE
TorchPoints3d

### ISSUE THREAD

**Issue by tchaton** [open-mmlab/mmdetection3d#18]
Dear All,

I am one of the main contributor of TorchPoints3d: https://github.com/nicolas-chaulet/torch-points3d
Your framework has lot of synergies with ours and I was wondering if you would have any interest in collaboration ?

We also have a Slack Channel with lot of experts in pointcloud field and would love for you guys to join in.

My email address is thomas . chaton . ai @ gmail . com. Without the spaces

Best regards,
Thomas Chaton

**Comment by ZwwWayne** [comment]
Hi @tchaton ，
Thanks for your invitation. torch-points3d is definitely a good project. Currently, we are still focusing on 3D detection and there are lots of things to do. So maybe in the future when MMDetection3D is more complete we may contact you.

**Comment by tchaton** [comment]
Hi @ZwwWayne,

Yes definitely. I guess I will start to work on integrating MMDetection3D directly with TorchPoints3d and merge both codebase together. I think it could be very beneficial for the community.

Best regards,
Thomas Chaton.
