### ISSUE TITLE
 Influence of point cloud range on results

### ISSUE THREAD

**Issue by TJRadarLab** [open-mmlab/mmdetection3d#1822]
I want to know whether the point cloud range will affect the result. For example, PointPillars and SECOND have different point cloud range, [0, -39.68, -3, 69.12, 39.68, 1] and [0, -40, -3, 70.4, 40, 1]. In addition, I did not find objectrangefilter in the test pipeline of Kitti validation set in mmdet3d. Will this affect the evaluation result? Because some gt boxes may exceed the range of input point cloud.

**Comment by Tai-Wang** [comment]
The minor difference in point cloud ranges is mainly related to the configuration of pillar/voxel sizes and will not affect the performance too much.
The usage of object range filter during training is used to avoid noises from hard samples. It is typically not used for evaluation for the consistency of the official evaluation protocol.
