### ISSUE TITLE
Fail when running a demo

### ISSUE THREAD

**Issue by APX103** [open-mmlab/mmdetection3d#1827]
## I get an error when I run this demo
![image](https://user-images.githubusercontent.com/61487970/189796231-6226877e-a6d9-4419-8266-5adfb05c34e2.png)

## error info
![image](https://user-images.githubusercontent.com/61487970/189796568-8cc9a1c2-c931-4260-b196-6844aa2c96eb.png)

**Comment by ZCMax** [comment]
Which branch are you using ? And the place you mention is `warning` not `error`

**Comment by APX103** [comment]
I'm so sorry that I forgot to specify my env
``` sh
mmcv-full 1.6.1
mmdet 2.25.1
mmseg 0.28.0
mmdet3d 1.0.0rc4
```
All master branch...
And it's an error. I'm sure. It cause program to break

![image](https://user-images.githubusercontent.com/61487970/189863498-4c34a913-5e8d-4ab2-b5cc-e532b2e4eeea.png)

![image](https://user-images.githubusercontent.com/61487970/189864481-e797c40d-9a30-470d-b536-68e884562bdb.png)

![image](https://user-images.githubusercontent.com/61487970/189863341-7b9753bc-e4d6-4b3e-b7e8-3a2de2c19618.png)

**Comment by APX103** [comment]
it fixed... yesterday

**Comment by zhangzirui1998** [comment]
> it fixed... yesterday

how to fixed
