### ISSUE TITLE
pcd demo error

### ISSUE THREAD

**Issue by zhangzirui1998** [open-mmlab/mmdetection3d#1844]
Thanks for your error report and we appreciate it a lot.
when I use pcd_demo.py, encountered a problem, the error is as follows
![2022-09-16 13-39-30屏幕截图](https://user-images.githubusercontent.com/67110568/190564652-5ed3708e-c71f-4bf7-9855-c68830a5237c.png)

**Comment by holtvogt** [comment]
These are not errors but user warnings. You should be good to go

**Comment by zhangzirui1998** [comment]
> These are not errors but user warnings. You should be good to go

thanks a lot
