### ISSUE TITLE
What is the resuls meaning?

### ISSUE THREAD

**Issue by tangjiuqi097** [open-mmlab/mmdetection3d#185]
Hi, I have run the 3dssd method, and its results is:

![image](https://user-images.githubusercontent.com/22868536/97771893-8f5c0800-1b7c-11eb-8b35-42330d011e4a.png)

But I don't know what it is. Why it has two groups of results? What is aos? And which is the main result?

**Comment by Tai-Wang** [comment]
AP@0.70, 0.70, 0.70 refers to the average precision (AP) for 2D detection (bbox), bird-view detection (bev) and 3D detection (3d), where IOU>0.70 would be considered as positive samples. In comparison, AP@0.70, 0.50, 0.50 refers to the IOU thresholds are 0.70 for bbox, 0.50 for bev and 0.50 for 3d. So you can find that bbox results in these two groups are the same, while the bev and 3d results are better in the results below with less strict metrics.

AOS means average orientation similarity. It seems that there exist some problems in terms of orientation estimation in evaluation of 3DSSD. @encore-zhou Please have a look at of this result.

You can mainly focus on the 3D detection precision, which is the main result for this task.

**Comment by tangjiuqi097** [comment]
> AP@0.70, 0.70, 0.70 refers to the average precision (AP) for 2D detection (bbox), bird-view detection (bev) and 3D detection (3d), where IOU>0.70 would be considered as positive samples. In comparison, AP@0.70, 0.50, 0.50 refers to the IOU thresholds are 0.70 for bbox, 0.50 for bev and 0.50 for 3d. So you can find that bbox results in these two groups are the same, while the bev and 3d results are better in the results below with less strict metrics.
> 
> AOS means average orientation similarity. It seems that there exist some problems in terms of orientation estimation in evaluation of 3DSSD. @encore-zhou Please have a look at of this result.
> 
> You can mainly focus on the 3D detection precision, which is the main result for this task.

Thank you. And how to compute the mAP like this? 
![image](https://user-images.githubusercontent.com/22868536/97797475-64df7d00-1c58-11eb-8875-ea1c12c76b87.png)

Is it (88.3100+77.9498+76.5887)/3 or (94.0335+89.9481+89.4462)/3 or others?
 (My results is producted by using the default config on 1 GPU with autoscale_lr and the default config runs 150epoch, so it may be different from your report.)

**Comment by Tai-Wang** [comment]
The three numbers 88.3100, 77.9498, 76.5887 should be AP@different difficulties (Easy, Moderate and Hard, please see the instruction of [KITTI benchmark](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d) for detailed explanation). Typically we report the moderate mAP (77.9498 in your result) in the table, which is the main metric for ranking on the benchmark. Your result is reasonable considering the batch size and GPU numbers you used.

**Comment by tangjiuqi097** [comment]
> The three numbers 88.3100, 77.9498, 76.5887 are AP@different difficulties (Easy, Moderate and Hard, please see the instruction of [KITTI benchmark](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d) for detailed explanation). Typically we report the moderate mAP (77.9498 in your result) in the table, which is the main metric for ranking on the benchmark. Your result is reasonable considering the batch size and GPU numbers you used.

I got it. Thank you very much.

**Comment by up201606808** [comment]
Hi @Tai-Wang, I was wondering why the AOS is always the same for both sets of thresholds. Do you have any insight as to why is that?

**Comment by Gaviaa** [comment]
Hello, do you have the kitti 3class results of 3dssd model?
