### ISSUE TITLE
video inference

### ISSUE THREAD

**Issue by legendary111** [open-mmlab/mmdetection3d#1850]
If I want to use MVXNet to test the video, the picture of each frame has corresponded to the point cloud one by one. Is there any solution?

**Comment by ZCMax** [comment]
You can modify the `pcd_demo.py` to support video demo.  You know, just split the video into multiple image frame can probably solve this

**Comment by Malekithlcx** [comment]
Have you solved thie problem? I also want to use MVXNet to test video.
