### ISSUE TITLE
How can I draw the lidar prediction boxes in cam image?

### ISSUE THREAD

**Issue by jiaminglei-lei** [open-mmlab/mmdetection3d#1855]
I just trained my model and got some prediction boxes after inference. But how can I visualize them on camera image, such as camera front.
Would you give me some idea?

**Comment by ZCMax** [comment]
We provide https://github.com/open-mmlab/mmdetection3d/blob/32a4328b16b85aae26d08d81157ab74b58edcdb1/mmdet3d/core/visualizer/image_vis.py#L89
to draw lidar boxes in cam image

**Comment by jiaminglei-lei** [comment]
@ZCMax  thanks for your reply.
I just followed the function `map_pointcloud_in_image` provided by nuscenes-devkit and obtained the results.  Thank you.
