### ISSUE TITLE
The relationship between voxel/pillar size and detection range

### ISSUE THREAD

**Issue by ChulanZhang** [open-mmlab/mmdetection3d#1859]
Hi there,
I saw that there's a rough description that the voxel/pillar size is related to the detection range in this issue #1822, #382, #336. I have some questions about how to tune the voxel/pillar size and detection range during my learning. More specifically, I am trying to use CenterPoint for 3d object detection now.

1. If I'd like to change the voxel/pillar size at inference time, do I need to train multiple models or do I only need to modify the configuration file? I did some experiments and could see an obvious accuracy drop if I use smaller voxel sizes than what the pre-trained model specified. My guess is that I need to train multiple models or use some other techniques if I want to support different voxel sizes using one model.
 
2. Luckily, I saw that MMDetection3D supports the dynamic voxelization feature and I found  that Centerpoint already supports different sizes of voxel as inherit from here: https://github.com/open-mmlab/mmdetection3d/blob/9556958fe1c6fe432d55a9f98781b8fdd90f4e9c/mmdet3d/models/detectors/mvx_two_stage.py#L213
By comparing the configuration file of Centerpoint and Dynamic Voxelization, seems that I only need to change the model.voxel_encoder from 'HardSimpleVFE' to 'DynamicSimpleVFE'/'DynamicVFE' and train a new model to support different voxel sizes at inference time using only one model. Am I understanding correctly here?

3. Follow up on the aforementioned questions, what voxel size should I choose for training if I use dynamic voxelization? A small one or big one?
I guess I should use a small voxel size for training because a model trained with smaller voxel size will probably achieve higher accuracy than a model trained with bigger voxel size. However, if the model is trained with a bigger voxel\pillar size (e.g. voxel size = [0.075, 0.075, 0.2] ) and we use a smaller voxel\pillar size during inference (e.g. voxel size = [0.050, 0.050, 0.2] ), the accuracy won't increase because the model is not trained with the smaller voxel size. Am I understanding correctly here?
So, I can use bigger voxel/pillar sizes during inference than a pre-trained model original is with some accuracy drop. But not the other way around.

4. May I know when should I update the shape of the intermediate feature map as mentioned here: [issue #382](https://github.com/open-mmlab/mmdetection3d/issues/382#issuecomment-810831507)?
Since it depends on both the voxel size and point cloud range, my understanding is that if any one of these two changes, the sparse_shape (intermediate feature map) should be changed.
But from these 2 configuration files of Centerpoints:
[centerpoint_0075voxel_second_secfpn_4x8_cyclic_20e_nus.py](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/centerpoint/centerpoint_0075voxel_second_secfpn_4x8_cyclic_20e_nus.py)
**When both the voxel size and detection range changed, the model.pts_middle_encoder.sparse_shape changed.**
[centerpoint_01voxel_second_secfpn_4x8_cyclic_20e_nus.py](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/centerpoint/centerpoint_01voxel_second_secfpn_4x8_cyclic_20e_nus.py)
**When only the detection range changed, the model.pts_middle_encoder.sparse_shape remains the same.**
I am a little bit confused about when should this sparse_shape be changed. And there is no hard relationship between the voxel size and detection range, they just influence the intermediate feature map size, right?

I am still learning 3D object detection, so these might be simple questions that people already know. But I don't understand why and any explanation will be appreciated. Thanks so much for your efforts in providing such a great open source repo for 3d object detection. I am looking forward to your reply.

Best,

**Comment by ChulanZhang** [comment]
One more question is when should I update the shape of the intermediate feature map as mentioned here: [issue #382](https://github.com/open-mmlab/mmdetection3d/issues/382#issuecomment-810831507)
Since it depends on both the voxel size and point cloud range, my understanding is that if any one of these two changes, the sparse_shape (intermediate feature map) should be changed.
But from these 2 configuration files of Centerpoints:
[centerpoint_0075voxel_second_secfpn_4x8_cyclic_20e_nus.py](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/centerpoint/centerpoint_0075voxel_second_secfpn_4x8_cyclic_20e_nus.py)
**When both the voxel size and detection range changed, the model.pts_middle_encoder.sparse_shape changed.**

[centerpoint_01voxel_second_secfpn_4x8_cyclic_20e_nus.py](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/centerpoint/centerpoint_01voxel_second_secfpn_4x8_cyclic_20e_nus.py)
**When only the detection range changed, the model.pts_middle_encoder.sparse_shape wasn't updated.**

I am still learning 3D object detection, so this might be a simple question that people already know. But I don't understand why and any explanation will be appreciated.

Thanks in advance!

**Comment by Tony-WJR** [comment]
@ZCMax Thank you for your nice explanation. But regarding the second point I'm not quite clear, you mean dynamic voxelization also use the hard voxelization way to divide the point cloud to fixed size voxels, but will not limit the max number of points in each voxel, and this can reduce the information loss brought by the random dropping(when reach max points per voxel) in hard voxelization right?

**Comment by Tai-Wang** [comment]
@Tony-WJR  Exactly
