### ISSUE TITLE
When I create a conda environment for mmdetection3d,   there are some issue as follows.

### ISSUE THREAD

**Issue by oneway3124** [open-mmlab/mmdetection3d#1860]
pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html

Log information：
AssertionError: MMCV==1.4.0 is used but incompatible. Please install mmcv>=1.5.2, <=1.7.0.
Try fix：
pip install mmcv-full==1.5.2 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html

Log information：
assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.5.0 is used but incompatible. Please install mmcv>=1.5.2, <=1.7.0.
Try fix：
There is no usable method

**Comment by oneway3124** [comment]
Before this log information , I have done some operation.


conda create -n mmdetection3d-wangw python=3.8 -y

conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge

pip install mmcv-full==1.4.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html

pip install mmdet==2.20.0

git clone https://github.com/open-mmlab/mmdetection3d.git
cd mmdetection3d
pip install -e .

pip install mmsegmentation

**Comment by oneway3124** [comment]
I just run the pcd_demo.py as 

python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

**Comment by JingweiZhang12** [comment]
You should uninstall the older mmcv-full before you install the new mmcv-full.
