### ISSUE TITLE
Questions about the recently added LSS View Transformer

### ISSUE THREAD

**Issue by woxihuanjiangguo** [open-mmlab/mmdetection3d#1869]
Hello! I notice that mmdetection3d recently supports the Lift-Splat-Shoot View Transformer. #1598 The model requires several coordinate-related parameters in the forwarding process:
`        Args:
            rots (torch.Tensor): Rotation from camera coordinate system to
                lidar coordinate system in shape (B, N_cams, 3, 3).
            trans (torch.Tensor): Translation from camera coordinate system to
                lidar coordinate system in shape (B, N_cams, 3).
            cam2imgs (torch.Tensor): Camera intrinsic matrixes in shape
                (B, N_cams, 3, 3).
            post_rots (torch.Tensor): Rotation in camera coordinate system in
                shape (B, N_cams, 3, 3). It is derived from the image view
                augmentation.
            post_trans (torch.Tensor): Translation in camera coordinate system
                derived from image view augmentation in shape (B, N_cams, 3).`

Are there any standard ways to derive them in mmdetection3d? I am currently using nuscenes dataset.

**Comment by Tai-Wang** [comment]
It's a part of the implementation of [BEVDet](https://github.com/HuangJunJie2017/BEVDet). We have not completed its support yet, and you can temporarily refer to its official code for now.

**Comment by woxihuanjiangguo** [comment]
OK, thank you for your reply.
