### ISSUE TITLE
about SMOKE 3D detection 

### ISSUE THREAD

**Issue by hitbuyi** [open-mmlab/mmdetection3d#1872]
does the model (smoke_dla34_pytorch_dlaneck_gn-all_8x4_6x_kitti-mono3d_20210929_015553-d46d9bb0.pth)  can be converted to ONNX to deploy directly? since the official SMOKE model contains deformable convolution, which pytorch ONNX may not supporte it

**Comment by JingweiZhang12** [comment]
We have not supported it yet.

**Comment by Tai-Wang** [comment]
We are working on the support of FCOS3D deployment, which is similar to SMOKE. Please stay tuned for recent updates of mmdeploy like this [PR](https://github.com/open-mmlab/mmdeploy/pull/1047).
