### ISSUE TITLE
high CPU load during evaluating

### ISSUE THREAD

**Issue by touristourist** [open-mmlab/mmdetection3d#1873]
Hi, I ran the code of PointPillars on KITTI dataset. I found that the CPU average load is too high when evaluating on KITTI dataset. I don't know how this phenomenon came about, and I want to know if there is a way to decrease CPU load during evaluating. Thanks!

**Comment by ZCMax** [comment]
During KITTI evaluation, all the calculation based on prediction and gt will be done on CPU, and we use `numba` to accelerate calculating speed, which may result in a higher CPU load, you can try to remove `numba` decorator in `kitti_utils.py`
