### ISSUE TITLE
How to use object detection with non dataset pointclouds

### ISSUE THREAD

**Issue by MarvinKlemp** [open-mmlab/mmdetection3d#1876]
I'm trying to use mmdetection3d to detect objects in pointclouds.
Here is an example using a pretrained model on KITTI using `demo/inference_demo.ipynb`:

```
pcd = "data/kitti/kitti_000008.bin"
config_file = '../configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py'
checkpoint_file = '...some_path.../hv_second_secfpn_6x8_80e_kitti-3d-3class_20210831_022017-ae782e87.pth'
```

![Screenshot from 2022-09-28 13-20-26](https://user-images.githubusercontent.com/5558190/192766577-36d7fa6b-7392-4dbc-9095-644317c5e0e4.png)

The results look promising. However, once I try to run the pretrained model on a raw pointcloud (not from KITTI dataset), after I converted it to the KITTI bin format:

![Screenshot from 2022-09-28 13-19-45](https://user-images.githubusercontent.com/5558190/192767470-76474b40-8bf2-45c4-92ca-f8a76adc0de3.png)
![Screenshot from 2022-09-28 13-19-37](https://user-images.githubusercontent.com/5558190/192767486-dc14cf2a-62dd-47b0-a095-ea5cd886ec09.png)

The results are quite bad. I guess that this is due to the case of the config being specific to the KITTI dataset. I didn't directly found specific hints in the docs.
Could someone help me change the basic configuration in a way that the pretrained network also works with the raw pointcloud?

**Comment by holtvogt** [comment]
You're right, the available model was specifically trained using the provided KITTI configurations and the dataset itself. The configuration includes, e.g. point cloud range, anchor range or anchor size. Even the type of LiDAR scanner used to record the point cloud can affect the outcome of your inference

**Comment by MarvinKlemp** [comment]
By coincidence, I also have access to data from the same type LiDAR which is used for KITTI. And the scan is also recorded in Karlsruhe.

![Screenshot from 2022-09-28 15-23-07](https://user-images.githubusercontent.com/5558190/192789848-87fb818b-44d1-46cc-a59b-82aeeab3fca0.png)

And it looks like this results in better predictions.

However, I expected that using a denser pointcloud won't result in such a big performance degradation (not working at all) as they are voxelized anyways. 
Therefore, I still suspect that in the config there are some settings that more or less completely invalidate the detection. Any ideas?

**Comment by tristanhoefer** [comment]
I'm dealing with a similar issue. Have you found a solution?

**Comment by tristanhoefer** [comment]
My results improved a lot by adapting the pointcloud range to my data while staying consistent as much as possible with the kitti dataset. For example, make sure that you only consider points in front of the vehicle. When changing the point cloud range it is important to also adapt the voxel size accordingly. 
Regarding intensity scaling, kitti uses an intensity between [0,1]. My sensor for example used an intensity of [0,255] so scaling it by dividing by 255 improved the results a lot!

**Comment by MattC11** [comment]
Thanks @tristanhoefer I clipped my data to the same bounds as the kitti data and hardcoded all the intensities to 0.1 and the results look much better. I still get a number of false positives on buildings but cars are picked up properly.
Will try to scale the intensity properly and see if it improves things further.
