### ISSUE TITLE
Try to load the RGB-D image of Rope3D and training PGD detector，but the result is not good as expected.

### ISSUE THREAD

**Issue by clw5180** [open-mmlab/mmdetection3d#1879]
I try to concat the depth_map with rgb image both in training and testing pipeline for PGD model, however the AP40 is almost same as before, not as the Rope3D paper. Is there something tricky? Thanks to big olds !

**Comment by ZCMax** [comment]
I think `depth_map` could be used as pretrain data, not just be concerted with rgb image, to achieve better performance

**Comment by Tai-Wang** [comment]
I do not see any experimental results on the Rope3D dataset with the PGD model. Maybe you need to tune the hyperparameters to fit their data distribution or metrics.
