### ISSUE TITLE
the change of point dimension in waymo

### ISSUE THREAD

**Issue by yichaoshen-MS** [open-mmlab/mmdetection3d#1880]
I compared the waymo/kitti-format converted by the old mmdet3d-0.15.0 and mmdet3d-1.0.0rc4, and found that the dimension of points are 5 and 6 separately. Furthermore, only the first two dimensions is consistent. So,
1. what point information do the 5 or 6 dimension  represent? the change is?
2. what are other differences in waymo/kitti-format caused by the change of version?

**Comment by JingweiZhang12** [comment]
The dim of points is 6. The last dim represents the range frame offset now. Details can be seen in https://github.com/open-mmlab/mmdetection3d/blob/dev/docs/en/compatibility.md
