### ISSUE TITLE
When using Smoke, the default size of kitti is 1280，384. If I want to fit my own 1920，1920 size, do I need to scale the internal parameters after resizing the image (image reduced to 960，960)?

### ISSUE THREAD

**Issue by weihongwei-zg** [open-mmlab/mmdetection3d#1884]

**Comment by ZCMax** [comment]
Yes, you need to modify the `cam2img` (camera intrinsic matrix)  and `centers2d` at she same time

**Comment by wobushihuair** [comment]
How to map the prediction results back to the original image during prediction? Do you only need to multiply the 2d results by the scaling ratio?

**Comment by ZCMax** [comment]
> How to map the prediction results back to the original image during prediction? Do you only need to multiply the 2d results by the scaling ratio?

typically multiplying the scaling ratio is OK
