### ISSUE TITLE
KeyError: 'sample_idx' when i prepare nuscenes

### ISSUE THREAD

**Issue by hollow-503** [open-mmlab/mmdetection3d#1887]
hi, it seems that i failed to prepare the nuScenes dataset.
i run the command
`
python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes
`
and the console output is

```
======
Loading NuScenes tables for version v1.0-trainval...
23 category,
8 attribute,
4 visibility,
64386 instance,
12 sensor,
10200 calibrated_sensor,
2631083 ego_pose,
68 log,
850 scene,
34149 sample,
2631083 sample_data,
1166187 sample_annotation,
4 map,
Done loading in 42.665 seconds.
======
Reverse indexing ...
Done reverse indexing in 10.8 seconds.
======
total scene num: 850
exist scene num: 850
train scene: 700, val scene: 150
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 34149/34149, 15.6 task/s, elapsed: 2194s, ETA:     0s
train sample: 28130, val sample: 6019
Create GT Database of NuScenesDataset
[                                                  ] 0/28130, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/create_data.py", line 101, in <module>
    nuscenes_data_prep(
  File "tools/create_data.py", line 45, in nuscenes_data_prep
    create_groundtruth_database(
  File "/root/xxx/workspace/env_run/xxx05/repo/bevfusion/tools/data_converter/create_gt_database.py", line 274, in create_groundtruth_database
    image_idx = example["sample_idx"]
KeyError: 'sample_idx'
```

**Comment by hollow-503** [comment]
When i debug to it, there is no key 'sample_idx' in the dist 'example'. I don't know why.

**Comment by hollow-503** [comment]
Here are all my data downloaded from [https://www.nuscenes.org](url)
<img width="210" alt="截屏2022-10-02 00 10 09" src="https://user-images.githubusercontent.com/57223231/193418285-8846a4c2-b5d1-4572-8a13-b136bc4b49bc.png">
And now my directory structure is
<img width="241" alt="截屏2022-10-02 00 11 29" src="https://user-images.githubusercontent.com/57223231/193418333-2d353857-549c-4c44-869c-bab922b9d1a3.png">

**Comment by hehualin-tut** [comment]
Hi,Have you solved it?

**Comment by freshman-zero** [comment]
I met the same problem, please let me know if you solved it. Thanks a lot!

**Comment by hehualin-tut** [comment]
@freshman-zero You can refer to https://github.com/mit-han-lab/bevfusion/pull/156
