### ISSUE TITLE
Need information about coordinate system.

### ISSUE THREAD

**Issue by IAMShashankk** [open-mmlab/mmdetection3d#1888]
Hi,
I need some information about coordinate system transformation in nuscenes dataset.
I am loading radar data from nuscenes and if we use sensor2lidar_rotation and sensor2lidar_translation on this data. 
Does this bring radar data in the same coordinate system as lidar?

Thanks,
Mishra

**Comment by VVsssssk** [comment]
Hi, Our nuscenes dataset used the consistent coordinate system with other datasets so you can refer to [coord_sys_tutorial.md](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/tutorials/coord_sys_tutorial.md). And about radar data transformation, I think it could use sensor2lidar matric to transform.
