### ISSUE TITLE
Implementation ditails in pointpillars

### ISSUE THREAD

**Issue by Lzc6996** [open-mmlab/mmdetection3d#189]
> Implementation Details: We basically follow the implementation in the paper in terms of the network architecture (having a stride of 1 for the first convolutional block). Different settings of voxelization, data augmentation and hyper parameters make these baselines outperform those in the paper by about 7 mAP for car and 4 mAP for pedestrian with only a subset of the whole dataset. All of these results are achieved without bells-and-whistles, e.g. ensemble, multi-scale training and test augmentation.

I found that ur pointpillars baseline in WOD is very strong.  Could u tell me  what the "Different settings of voxelization, data augmentation and hyper parameters" specifically are.

**Comment by Tai-Wang** [comment]
Basically there are lots of differences in terms of these hyperparameters. To mention only a few, the voxel size/point cloud range/max voxels of voxelization, global random flip/translation/scaling and ground truth sampling settings for augmentation, and iou thresholds in target assigners. You can refer to our base config for [dataset](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/waymoD5-3d-3class.py) and [model](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/hv_pointpillars_secfpn_waymo.py) for more details and compare them with descriptions in these two papers, [waymo dataset](https://arxiv.org/abs/1912.04838) and [dynamic voxelization](https://arxiv.org/abs/1910.06528)

**Comment by Lzc6996** [comment]
@Tai-Wang 
Thank you for your answers.
So, do u have some ablation to show which component works best.

**Comment by Tai-Wang** [comment]
Yes I did, but it may be not convenient to find and present those detailed records.

In my memory, iou thresholds for each target assigner/score threshold and nms threshold in the test config and using stride=1 in the first layer of SECOND backbone (which is also mentioned in the waymo dataset paper) are the most important factors for the improvements.

BTW, experiences of these hyperparameters finetuning are usually dataset specific, so you can simply follow our configs, which have crystallized our much of our efforts in the experiments.

**Comment by Lzc6996** [comment]
@Tai-Wang 
Thank you for your sharing.
BTW, Which paper does your SECFPN refer to.

**Comment by Tai-Wang** [comment]
> @Tai-Wang
> Thank you for your sharing.
> BTW, Which paper does your SECFPN refer to.

It refers to the head used in the SECOND. To distinguish it from the typical FPN proposed from 2D detection, we name it as SECFPN here.
