### ISSUE TITLE
How can i train a mono3D model like smoke by waymo dataset

### ISSUE THREAD

**Issue by Jenny0420** [open-mmlab/mmdetection3d#1906]
i have waymo dateset
then i converter the waymo dataset to kitti_format by create_data.py
and then i want to train a mono3D detection model like smoke 
can i run create_data.py again by kitti_format data and then i can use kitti-mono3d data pipeline?

**Comment by Jenny0420** [comment]
@lindahua

**Comment by JingweiZhang12** [comment]
Just running `create_data.py` once can generate mono3D annotation file.

**Comment by Jenny0420** [comment]
@JingweiZhang12  i run the create_data.py by waymo 
it create the pickle like "waymo_infos_train.pkl" but no json

**Comment by Jenny0420** [comment]
@JingweiZhang12  
thanks for your ans!!
i have tried to run create_data.py once by next:

"python create_data.py waymo --rootp-path ... --out-dir ... --extra-tag waymo "

I got some pickle bag like "waymo_info_train_pkl",but it without json file like "......_infos_train_mono3d_coco.json"

---------------------------------------------
my env:
mm3d:1.01.0rc2
mmdet:2.25.2
mmcv-full:1.4.8
mmseg:0.28.0
---------------------------------------------

i used to try nuscenes dataset ,by create_data.py once and it worked.(i got pkl and json)

**Comment by Xiangxu-0103** [comment]
`master` branch does not support waymo monocular detection task currently. It has been supported in `det-1.x` branch.

**Comment by Jenny0420** [comment]
@Xiangxu-0103 

dev-1.x branch?

**Comment by Tai-Wang** [comment]
Camera-only 3D detection features on Waymo are just supported in the dev-1.x/1.1 branch. It may be unstable for now, but you can have a try first. We will update it in the next release and please stay tuned.

**Comment by JiSuanJiDaWang** [comment]
> Camera-only 3D detection features on Waymo are just supported in the dev-1.x/1.1 branch. It may be unstable for now, but you can have a try first. We will update it in the next release and please stay tuned.

Do we support training smoke on waymo currently on 1.1 branch?
