### ISSUE TITLE
Question about the time consumption of training on the nuScenes

### ISSUE THREAD

**Issue by jialeli1** [open-mmlab/mmdetection3d#191]
Has anyone tried to train a model on the nuScenes? 
I run 32 batches on two GPUs, and each epoch takes nearly 5 hours. Even with 20 epochs, it would take 100 hours, which is about 5 days. This time consumption is too expensive. 
Can someone share the experience of training on nuScenes?

**Comment by Tai-Wang** [comment]
Which config do you use? Generally speaking, from my experience, I can train a PointPillars baseline on nuScenes with 8 2080Ti GPUs in 12 hours. So it is a little strange for you to spend so much time training it. Sometimes not much support from CPU or other parts of machines may affect the efficiency.

**Comment by jialeli1** [comment]
Thanks for your sharing. I trained the model with my own config. I will keep going on it.

**Comment by Son-Goku-gpu** [comment]
Hi @Tai-Wang, can you share the time to train the centerpoint (with CBGS resampling) on nuScenes for 20 epoches with 8 GPUs? Thanks.
