### ISSUE TITLE
Question about GPU memory consumption of spconv implemented in mmdet3d

### ISSUE THREAD

**Issue by GalaxyWM** [open-mmlab/mmdetection3d#192]
thx for ur excellent project!!!
I tried to reimplement pvrcnn in mmdet3d, but i cant train pvrcnn with batchsize=2 because of OOM ERROR. i find the reason is that  GPU memory consumption of  spconv implemented in mmdet3d (about 8000M) if much higer than official version (about 6000M). 
what are the differences between them? and how to solve the problem
wish ur reply, thx  ^v^

**Comment by Tai-Wang** [comment]
Actually some parts of spconv/voxelization are refactored with cuda operations indeed, which would lead to a little more memory costs. But from our experience, I guess it may not be the direct reason for OOM ERROR? A trick to reduce memory costs if you use SECFPN instead of FPN is setting the reshape_out to False, which typically copies a large intermediate feature map.

**Comment by GalaxyWM** [comment]
> Actually some parts of spconv/voxelization are refactored with cuda operations indeed, which would lead to a little more memory costs with better efficiency. But from our experience, I guess it may not be the direct reason for OOM ERROR? A trick to reduce memory costs if you use SECFPN instead of FPN is setting the reshape_out to False, which typically copies a large intermediate feature map.

thx for ur reply.
I set batchsize=2 as OpenPCDet mentioned, and if batchsize=1, there is no OOM ERROR. Actually i use the same config as SECOND (with SECFPN) in sparse conconvolution module.
I compare modules implemented in mmdet3d and pcdet, and find that spconv module  in mmdet3d  cost more gpu memory (about 2000m) than official module imported in pcdet. 
so which version of spconv  implemented in mmdet3d?  and would it be possible to decrease the memory cost of spconv  for greater compatibility  with other models
wish ur reply, thx  XD

**Comment by Tai-Wang** [comment]
Thanks for your feedback. We refactor the voxelization to cuda considering the consistency of input for VoxelNet and other models (all is raw points). There is trade-off here. It could improve the framework efficiency, especially for the transition between epochs while lead to more memory overheads.

A work around is that you can use [FP16 models](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/fp16) to reduce the memory burden. Besides, we also include numpy implementation on cpu [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/voxel/voxel_generator.py), which could generate the same result as the cuda version. You can try to replace the current voxelization in VoxelNet with it, but it needs some modification in dataset pipelines and maybe also somewhere else.

If you finally make it, PRs are also welcome.
