### ISSUE TITLE
Is it possible to train the Lidar segmentation on8 or 16 Layer Lidar data?

### ISSUE THREAD

**Issue by Giofist** [open-mmlab/mmdetection3d#193]

**Comment by ZwwWayne** [comment]
Yes it is possible.

**Comment by Giofist** [comment]
@ZwwWayne may I ask you how can i do it (is there any guide or article)? thanks

**Comment by Giofist** [comment]
@ZwwWayne may I ask you how can i do it (is there any guide or article)? thanks
