### ISSUE TITLE
Support Range-view based Segmentation Methods

### ISSUE THREAD

**Issue by Xiangxu-0103** [open-mmlab/mmdetection3d#1930]
Any plan for supporting Range-view based Segmentation methods, such as [SalsaNext](https://arxiv.org/abs/2003.03653), [SqueezeSegV3](https://arxiv.org/abs/2004.01803), etc.?

**Comment by JingweiZhang12** [comment]
We don't have enough human quota to do it, but any PR about it from the community is welcomed.
