### ISSUE TITLE
Evaluation with different distances on nuscenes dataset

### ISSUE THREAD

**Issue by konyul** [open-mmlab/mmdetection3d#1943]
Is there any config or argument to evalute a model with different distances on nuscenes dataset??

**Comment by ZCMax** [comment]
I'm not quite understand your meaning,  you mean like waymo metric?

**Comment by vehxianfish** [comment]
@konyul . Hi,  do you solve this problem? Looking forward to your reply!

**Comment by Mingqj** [comment]
@konyul. Hi, could you share your code about evaluating a model with different distances on nuScenes dataset?
