### ISSUE TITLE
use nvidia's pytorch_quantization for int8 QAT

### ISSUE THREAD

**Issue by shuyuan-wang** [open-mmlab/mmdetection3d#1944]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
When the pytorch_quantization module is initialized, all the nn module is uspposed to be replaced by quant nn module, and weight should be quantized. However, only head and feature extract is quantized, others are not.
![image](https://user-images.githubusercontent.com/104115572/197397055-37fa2fc0-745a-40f7-a894-4aee26dc83c6.png)
![image](https://user-images.githubusercontent.com/104115572/197397070-af7d3802-3286-4ce8-8138-b012487db259.png)

**Reproduction**
added lines below at the tools/test.py file
```
from pytorch_quantization import nn as quant_nn
from pytorch_quantization import calib
from pytorch_quantization.tensor_quant import QuantDescriptor
quant_desc_input = QuantDescriptor(calib_method='histogram')
quant_nn.QuantConv2d.set_default_quant_desc_input(quant_desc_input)
quant_nn.QuantConvTranspose2d.set_default_quant_desc_input(quant_desc_input)
quant_nn.QuantLinear.set_default_quant_desc_input(quant_desc_input)

from pytorch_quantization import quant_modules
quant_modules.initialize()
```

Use following command line:
```
python tools/test.py configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py ./hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d_20210826_104936-fca299c1.pth --eval nuscenes
```

3. Did you make any modifications on the code or config? Did you understand what you have modified?
4. What dataset did you use?

**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3070 Laptop GPU
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.58
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.10.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.0+cu113
OpenCV: 4.6.0
MMCV: 1.6.2
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.25.2
MMSegmentation: 0.29.0
MMDetection3D: 1.0.0rc5+fcb4545
spconv2.0: False

2. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by humu789** [comment]
@shuyuan-wang 
https://github.com/open-mmlab/mmdetection3d/blob/fcb4545ce719ac121348cab59bac9b69dd1b1b59/mmdet3d/models/detectors/mvx_two_stage.py#L201
I guess that the dynamic judement leads to the neck can not be traced, thus the neck have not been inserted fakequant automatically.
So you can try deleting the line according to your requirement or passing a fixed value to `self.with_pts_neck`

**Comment by jonasdieker** [comment]
Hi @shuyuan-wang, can you explain where exactly you put those lines in `tools/test.py`?

**Comment by jonasdieker** [comment]
> @shuyuan-wang
> 
> https://github.com/open-mmlab/mmdetection3d/blob/fcb4545ce719ac121348cab59bac9b69dd1b1b59/mmdet3d/models/detectors/mvx_two_stage.py#L201
> 
> 
> I guess that the dynamic judement leads to the neck can not be traced, thus the neck have not been inserted fakequant automatically.
> So you can try deleting the line according to your requirement or passing a fixed value to `self.with_pts_neck`

Hi @humu789, this does not seem to have any effect now (a year later). Any idea what else I would have to change to quantize also the backbone and neck?

**Comment by shuyuan-wang** [comment]
This is related to how mmdetection create modules. in mmcv, for example, mmcv/cnn/bricks/conv.py/build_conv_layer, it uses nn.Conv2d, however, in pytorch_quantization/quant_modules.py, it looks for torch.nn.Conv2d. When I changed from nn.Conv2d to torch.nn.Conv2d in mmcv, it works

**Comment by shuyuan-wang** [comment]
> > @shuyuan-wang
> > https://github.com/open-mmlab/mmdetection3d/blob/fcb4545ce719ac121348cab59bac9b69dd1b1b59/mmdet3d/models/detectors/mvx_two_stage.py#L201
> > 
> > I guess that the dynamic judement leads to the neck can not be traced, thus the neck have not been inserted fakequant automatically.
> > So you can try deleting the line according to your requirement or passing a fixed value to `self.with_pts_neck`
> 
> Hi @humu789, this does not seem to have any effect now (a year later). Any idea what else I would have to change to quantize also the backbone and neck?

This is related to how mmdetection create modules. in mmcv, for example, mmcv/cnn/bricks/conv.py/build_conv_layer, it uses nn.Conv2d, however, in pytorch_quantization/quant_modules.py, it looks for torch.nn.Conv2d. When I changed from nn.Conv2d to torch.nn.Conv2d in mmcv, it works

**Comment by jonasdieker** [comment]
@shuyuan-wang Great, thank you for the information. I will take a look at this!
