### ISSUE TITLE
KITTI dataset preparation

### ISSUE THREAD

**Issue by ShreyanshGoyal17** [open-mmlab/mmdetection3d#1963]
### Branch

master branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

I am trying to prepare the KITTI point cloud data using the documentation but when I run the command "python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti" I get the error "ValueError: file not exist: training/image_2/000000.png"

The documentation isn't clear on why is it taking the png file from training/image_2 when I want it to use the point cloud data from training/velodyne and how do I make those changes?

**Comment by ZCMax** [comment]
Since the image info is used to generate pkl info file and it's not optional. I suggest you to download the full Kitti datasets. It could be complex to make changes for not using png file during dataset converter.
