### ISSUE TITLE
[Bug] About metainfo in Nuscenes dataset

### ISSUE THREAD

**Issue by RookieXwc** [open-mmlab/mmdetection3d#1980]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

no matter

### Reproduces the problem - code sample

no matter

### Reproduces the problem - command or script

no matter

### Reproduces the problem - error message

no matter

### Additional information

In the new version of mmdet3d, metainfo is defined in config, but METAINFO is defined in NuScenesDataset. Therefore, when initializing, METAINFO is given to metainfo in base_dataset.py. But the problem is that metainfo should be read from nuscenes_infos_val.pkl. For example, if my nuscenes is v1.0 mini, metainfo in nuscenes_infos_val.pkl is v1.0-mini, but METAINFO is always v1.0-trainval.

**Comment by JingweiZhang12** [comment]
1. The final values in the `self._metainfo` follows the priority (from high to low): `mefainfo` in the conifg > `METAINFO` in the dataset class > `metainfo` in the ann file. 
2. The `self.METAINFO` in the dataset is not overwritten by other metainfo. This is intended. 

May help you!

**Comment by RookieXwc** [comment]
OK, thank you. I think I should modify the config. But, which codes will read `metainfo` in the ann file?

**Comment by JingweiZhang12** [comment]
https://github.com/open-mmlab/mmengine/blob/main/mmengine/dataset/base_dataset.py#L440

**Comment by RookieXwc** [comment]
OK, thank you. I have no other questions.
