### ISSUE TITLE
How to use road_plane information?

### ISSUE THREAD

**Issue by feufhd** [open-mmlab/mmdetection3d#199]
Thanks for your mm3d work!
I want to use road_plane information to get a better performance, but I can't find where to change in the code.

**Comment by Tai-Wang** [comment]
It depends on how you want to use the road plane information. Previous work usually uses the road plane when doing ground truth sampling for more accurate augmentation, but the benefit is very minor. So we remove it from our codebase.

If you want to develop your own methods of using this kind of information, you may need to modify the data preparation and pipelines to include the 'road_plane' data. As for the generation of road plane data, you can refer to the approach of [AVOD](https://github.com/kujason/avod) and its provided [data](https://drive.google.com/drive/folders/1yjCwlSOfAZoPNNqoMtWfEjPCfhRfJB-Z) for KITTI.

BTW, if you get some progress, PRs are welcome.

**Comment by feufhd** [comment]
Thanks for your reply!
I know how to modify the data preparation, but I don't see where to change in the config. Usually in previous work there is a '--use_road_plane=True' to add when training.

**Comment by Tai-Wang** [comment]
Changing the config is very convenient. Taking the case of modifying database sampler as an example, you just need to modify the class/function [HERE](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/dbsampler.py#L94) and adjust the config [correspondingly](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/kitti-3d-3class.py#L7). If you want to make it as an argument in parser, you can refer to [HERE](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/train.py#L22).

A reminder is that you need to adjust the [pipelines](https://github.com/open-mmlab/mmdetection3d/tree/master/mmdet3d/datasets/pipelines) for loading and formatting carefully and config correspondingly (like [HERE](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/kitti-3d-3class.py#L51)) if you introduce new keys/data.

**Comment by feufhd** [comment]
OK, thanks a lot!

**Comment by Tai-Wang** [comment]
Feel free to reopen it if you have new questions.
