### ISSUE TITLE
[Bug] Windows paths not handled correctly by the tools/dataset_converters/update_infos_to_v2.py update_.*?_infos functions

### ISSUE THREAD

**Issue by vavanade** [open-mmlab/mmdetection3d#2001]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

sys.platform: win32
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce GTX 1650
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
MSVC: Microsoft (R) C/C++ Optimizing Compiler Version 19.33.31630 for x64
GCC: n/a
PyTorch: 1.13.0+cu117
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_7
5,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /b
igobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILE
R_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NC
CL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.14.0+cu117
OpenCV: 4.6.0
MMEngine: 0.3.0
MMDetection: 3.0.0rc2
MMDetection3D: 1.1.0rc1+28fe73d
spconv2.0: False

### Reproduces the problem - code sample

.

### Reproduces the problem - command or script

```shell
python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes --version v1.0-mini
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "C:\path\to\mmdetection3d\tools\create_data.py", line 277, in <module>
    nuscenes_data_prep(
  File "C:\path\to\mmdetection3d\tools\create_data.py", line 92, in nuscenes_data_prep
    create_groundtruth_database(dataset_name, root_path, info_prefix,
  File "c:\path\to\mmdetection3d\tools\dataset_converters\create_gt_database.py", line 221, in create_groundtruth_database
    dataset = build_dataset(dataset_cfg)
  File "c:\path\to\mmdetection3d\mmdet3d\datasets\builder.py", line 42, in build_dataset
    dataset = DATASETS.build(cfg, default_args=default_args)
  File "C:\path\to\venv\mmdetection3d\lib\site-packages\mmengine\registry\registry.py", line 454, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\path\to\venv\mmdetection3d\lib\site-packages\mmengine\registry\build_functions.py", line 135, in build_from_cfg
    raise type(e)(
ValueError: class `NuScenesDataset` in mmdet3d/datasets/nuscenes_dataset.py: Annotation must have data_list and metainfo keys
```

### Additional information

![windows_path_problem](https://user-images.githubusercontent.com/24233171/200352496-4dca6d9d-5e85-4442-87d4-319177f21980.PNG)

The `split('/')[-1]` causes the problem. I could provide a MR where it can use `pathlib.Path` (according to `setup.py` Python 3.6 and 3.7 is used where `pathlib` is included).

I think that using `pathlib` is a good idea in general if there is not a severe performance concern.

**Comment by vavanade** [comment]
Quick fix would be to add `import pathlib` to the top of `tools/dataset_converters/update_infos_to_v2.py`

and rewrite `pkl_name = pkl_path.split('/')[-1]` to `pkl_name = pathlib.Path(pkl_path).name` in each function `update_.*?_infos`

**Comment by vavanade** [comment]
Better approach would be to work with `pathlib.Path` instead of `str` in the whole `mmdetection3d` package. But that would take some more work.

**Comment by ZCMax** [comment]
Please have a look at this issue @VVsssssk

**Comment by vavanade** [comment]
@VVsssssk I have created a Pull Request to fix this issue: https://github.com/open-mmlab/mmdetection3d/pull/2031
