### ISSUE TITLE
[Bug] Negtive samples in IoUNegPiecewiseSampler

### ISSUE THREAD

**Issue by oyel** [open-mmlab/mmdetection3d#2004]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.8.2+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.2+cu111
OpenCV: 4.6.0
MMCV: 1.6.0
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.1
MMDetection: 2.25.1
MMSegmentation: 0.27.0
MMDetection3D: 1.0.0rc4+b27185a
spconv2.0: True

### Reproduces the problem - code sample

https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/bbox/samplers/iou_neg_piecewise_sampler.py#L109-L112
`                            
rand_idx = torch.randint(
                                low=0,
                                high=neg_inds_choice.numel(),
                                size=(extend_neg_num, )).long()
`

### Reproduces the problem - command or script

bash tools/dist_train.sh my_own_config.py

### Reproduces the problem - error message

Traceback (most recent call last):
  File "tools/train.py", line 243, in <module>
    main()
  File "tools/train.py", line 239, in main
    meta=meta)
  File "/disk/deepdata/oyel_work_dirs/code/mmdetection3d/mmdet3d/apis/train.py", line 353, in train_model
    meta=meta)
  File "/disk/deepdata/oyel_work_dirs/code/mmdetection3d/mmdet3d/apis/train.py", line 321, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/miniconda3/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 63, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/root/miniconda3/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/disk/deepdata/oyel_work_dirs/code/mmdetection3d/mmdet3d/models/detectors/base.py", line 60, in forward
    return self.forward_train(**kwargs)
  File "./plugins/fsd_plugins/two_stage_fsd.py", line 93, in forward_train
    gt_labels_3d,
  File "./plugins/fsd_plugins/fsd_roi_head.py", line 90, in forward_train
    gt_labels_3d)
  File "./plugins/fsd_plugins/fsd_roi_head.py", line 347, in _assign_and_sample
    cur_gt_labels)
  File "/disk/deepdata/oyel_work_dirs/code/mmdetection3d/mmdet3d/core/bbox/samplers/iou_neg_piecewise_sampler.py", line 173, in sample
    assign_result, num_expected_neg, bboxes=bboxes, **kwargs)
  File "/disk/deepdata/oyel_work_dirs/code/mmdetection3d/mmdet3d/core/bbox/samplers/iou_neg_piecewise_sampler.py", line 112, in _sample_neg
    size=(extend_neg_num, )).long()
RuntimeError: random_ expects 'from' to be less than 'to', but got from=0 >= to=0

### Additional information

Hi, I'm re-factoring "Fully Sparse 3D Object Detection"(FSD) with mmdet3d 1.0.x on waymo dataset based on [https://github.com/tusen-ai/SST](https://github.com/tusen-ai/SST), which is instead implemented with mmdet3d 0.15.0. 

I observed that the updated class "IoUNegPiecewiseSampler" in mmdet3d 1.0.x may produce the above runtime error in `torch.randint` function.  My config for "IoUNegPiecewiseSampler" is:
`
sampler=dict(
        type='IoUNegPiecewiseSampler',
        num=256,
        pos_fraction=0.55,
        neg_piece_fractions=[0.8, 0.2],
        neg_iou_piece_thrs=[0.55, 0.1],
        neg_pos_ub=1,
        add_gt_as_proposals=False,
        return_iou=True
)
`

I think this happens when:
1.  `len(neg_iou_piece_thrs) > 1`;
2. when sampling the last piece of negtive samples, the number of previous negtive samples is 0(which means `neg_inds_choice.numel() == 0`)

then, `torch.randint()` will raise the above error. Therefore I suggest that a protection branch be add here in case that no negtives are sampled before last pieces.

**Comment by JingweiZhang12** [comment]
Werid! could you provide a snippet of code to reproduce this error? 
To my knowledge, this error only occurs in this case: max(neg_iou_piece_thrs) = 0. Thus, `neg_inds_choice.numel() == 0`

**Comment by oyel** [comment]
> Werid! Could you provide a snippet of code to reproduce this error? To my knowledge, this error only occurs in a corner case: `max(neg_iou_piece_thrs) == 0`. Thus, `neg_inds_choice.numel() == 0`

Hi Jingwei, besides the case you mentioned,  when `min(max_overlaps) > max(neg_iou_piece_thrs)`, it would also reproduce this error, and this may happen occasionally in the unstable early training epochs.

**Comment by JingweiZhang12** [comment]
> > Werid! Could you provide a snippet of code to reproduce this error? To my knowledge, this error only occurs in a corner case: `max(neg_iou_piece_thrs) == 0`. Thus, `neg_inds_choice.numel() == 0`
> 
> Hi Jingwei, besides the case you mentioned, when `min(max_overlaps) > max(neg_iou_piece_thrs)`, it would also reproduce this error, and this may happen occasionally in the unstable early training epochs.

But when `min(max_overlaps) > max(neg_iou_piece_thrs)`,  the `len(neg_inds) == 0` and it will not sample results unless the `neg_iou_thr>=min(max_overlaps)` in  `assign`

**Comment by oyel** [comment]
> > > Werid! Could you provide a snippet of code to reproduce this error? To my knowledge, this error only occurs in a corner case: `max(neg_iou_piece_thrs) == 0`. Thus, `neg_inds_choice.numel() == 0`
> > 
> > 
> > Hi Jingwei, besides the case you mentioned, when `min(max_overlaps) > max(neg_iou_piece_thrs)`, it would also reproduce this error, and this may happen occasionally in the unstable early training epochs.
> 
> But when `min(max_overlaps) > max(neg_iou_piece_thrs)`, the `len(neg_inds) == 0` and it will not sample results unless the `neg_iou_thr>=min(max_overlaps)` in `assign` . I have seen the config in FSD, the `neg_iou_thr` in assign is smaller than `max(neg_iou_piece_thr)` and it will not fall into this case.

Yes, you are right. In FSD, `neg_iou_thr` in assign is smaller than `max(neg_iou_piece_thr)` .

I checked the Sampler again and reproduced this error, and please let me share the key intput params/variables for `_sample_neg` func:
- `self.neg_iou_thr :  [0.5, 0.1]`
- `assign_result.max_overlaps : tensor([0.3119, 0.4037, 0.3315])`
- `assign_result.gt_inds : tensor([0, 0, 0])`
- `num_expected : 1`  (No positive samples are selected in `_sample_pos` )

It is expected to sample 1 negtive from all these 3 in **first** piece `[0.1, 0.5)`. However, when calculating `piece_expected_num` in [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/bbox/samplers/iou_neg_piecewise_sampler.py#L77-L79), it assigns `0` to `piece_expected_num` for the first piece, which makes `neg_inds_choice.numel() == 0` when continuing sampling in the **second** piece `[0, 0.1)`, finally it comes to the error in `torch.randint()`  [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/bbox/samplers/iou_neg_piecewise_sampler.py#L109-L112).

**Comment by JingweiZhang12** [comment]
Got it. Maybe the code [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/bbox/samplers/iou_neg_piecewise_sampler.py#L77-L79) should be modified to the following:
```
piece_expected_num = math.ceil(
                        num_expected *
                        self.neg_piece_fractions[piece_inds]) + extend_num
```
Could you please create a PR to fix it?

**Comment by oyel** [comment]
Sure. And it's better to be modified like this(adding `min()` to avoid `len(neg_inds_choice) > num_expected`)
```
piece_expected_num = min(
                        num_expected,
                        math.ceil(
                            num_expected *
                            self.neg_piece_fractions[piece_inds]) + extend_num)
```
btw, it's necessary to add `min`. Suppose that we have 3 pieces `self.neg_iou_thr = [0.5, 0.2, 0.1]`, meanwhile `assign_result.max_overlaps = tensor([0.11, 0.12, 0.13]), num_expected = 1`,  then `min()` would avoid `piece_expected_num = 2` in the **second** piece.

**Comment by JingweiZhang12** [comment]
Yeah, make sense.

**Comment by JingweiZhang12** [comment]
> @JingweiZhang12 Hi Jingwei, should I create the PR to merge into dev-1.x branch? I didn't see mmdet3d/core/bbox/samplers/iou_neg_piecewise_sampler.py file in dev-1.x.

Better to create PRs on both dev-1.x branch and dev branch. The path of `iou_neg_piecewise_sampler.py` in dev-1,x branch: `mmdet3d/models/task_modules/samplers/iou_neg_piecewise_sampler.py`
