### ISSUE TITLE
model inference time measurement tools

### ISSUE THREAD

**Issue by AllenPeng0209** [open-mmlab/mmdetection3d#202]
Hi, 

I found there is a benchmark tool for research measure model inference time.

If I want to know the inference time of each module, like voxelization, middle encoder, or backbone, is there any tools for me to do this?

If not, how to implement it in an elegant way.

**Comment by ZwwWayne** [comment]
For the model inference time, you can use https://github.com/open-mmlab/mmdetection3d/blob/master/tools/benchmark.py. For the inference time of each module, you may use a similar way to insert the timer in the code in [detectors](https://github.com/open-mmlab/mmdetection3d/tree/master/mmdet3d/models/detectors).

**Comment by AllenPeng0209** [comment]
thanks for the reply.

I found some torch.cuda.synchronize() operation in benchmark tools, I want to know whether this operation is corresponding to batch_size, for example, the batch size is more than one, synchronization operation may take longer time?

**Comment by ZwwWayne** [comment]
No. This line of code is necessary only because some CUDA operations might be executed in an unsynchronized manner, which leads to inaccurate time measurement.
