### ISSUE TITLE
How to use DLA-34 to be the backbone of  CenterNet? 

### ISSUE THREAD

**Issue by Murray-Yin** [open-mmlab/mmdetection3d#2029]
### Model/Dataset/Scheduler description

Most original backbone of CenterNet is ResNet18. However, I don't know how to change and use the DLA34 to be the backbone of CenterNet. I am looking forward to some structural suggestions, thanks!

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by JingweiZhang12** [comment]
The quotations about 2d detection could be posed on [MMDet](https://github.com/open-mmlab/mmdetection).

**Comment by ZCMax** [comment]
We have provided an implementation of DLA34 in our repo, you can refer to https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/smoke.py to see how to use it.

**Comment by Murray-Yin** [comment]
> We have provided an implementation of DLA34 in our repo, you can refer to https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/smoke.py to see how to use it.

thanks a lot, it is work
