### ISSUE TITLE
Training on Waymo dataset

### ISSUE THREAD

**Issue by XYAskWhy** [open-mmlab/mmdetection3d#2030]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

none

### Reproduces the problem - code sample

none

### Reproduces the problem - command or script

CUDA_VISIBLE_DEVICES=0 python tools/train.py configs/dfm/multiview-dfm_r101-dcn_16xb2_waymoD5-3d-3class.py --work-dir=work_dirs/test

### Reproduces the problem - error message

11/16 07:14:24 - mmengine - INFO - Result has been saved to -/mmdetection3d/work_dirs/test/modules_statistic_results.json
-/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py:92: UserWarning: dir_offset and dir_limit_offset will be depressed and be incorporated into box coder in the future
  warnings.warn(
11/16 07:14:45 - mmengine - INFO - Distributed training is not used, all SyncBatchNorm (SyncBN) layers in the model will be automatically reverted to BatchNormXd layers if they are used.
11/16 07:15:08 - mmengine - INFO - load 4352210 Car database infos
11/16 07:15:08 - mmengine - INFO - load 2037627 Pedestrian database infos
11/16 07:15:08 - mmengine - INFO - load 49518 Cyclist database infos
11/16 07:15:17 - mmengine - INFO - After filter database:
11/16 07:15:17 - mmengine - INFO - load 4078739 Car database infos
11/16 07:15:17 - mmengine - INFO - load 2037627 Pedestrian database infos
11/16 07:15:17 - mmengine - INFO - load 49518 Cyclist database infos
Traceback (most recent call last):
  File "--/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "-/mmdetection3d/mmdet3d/datasets/waymo_dataset.py", line 100, in __init__
    super().__init__(
  File "-/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 65, in __init__
    super().__init__(
  File "-/mmdetection3d/mmdet3d/datasets/det3d_dataset.py", line 115, in __init__
    super().__init__(
  File "--/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 247, in __init__
    self.full_init()
  File "--/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 298, in full_init
    self.data_list = self.load_data_list()
  File "-/mmdetection3d/mmdet3d/datasets/waymo_dataset.py", line 181, in load_data_list
    data_list = super().load_data_list()
  File "--/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 435, in load_data_list
    raise TypeError(f'The annotations loaded from annotation file '
TypeError: The annotations loaded from annotation file should be a dict, but got <class 'list'>!

During handling of the above exception, another exception occurred:

### Additional information

- It seems like a data loading problem. I wonder if it's because I am using 1.2 version waymo dataset. I tried to debug, and found many key dismatch problems in the latest 1.1 branch code with the loaded data structure.

**Comment by ZCMax** [comment]
We update our info data structure, and please use `tools/dataset_converters/update_infos_to_v2.py` to update your info, if it's generated by 1.0.0rcx code.

**Comment by XYAskWhy** [comment]
Thanks a lot. I know for sure that there should be a converter tool somewhere, but can't find it in the doc.
