### ISSUE TITLE
The provided url of ```centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus.py``` in the metadata is wrong.

### ISSUE THREAD

**Issue by AlmoonYsl** [open-mmlab/mmdetection3d#2054]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection3d

### Environment

TorchVision: 0.9.1+cu111
OpenCV: 4.6.0
MMCV: 1.7.0
MMCV Compiler: GCC 9.4
MMCV CUDA Compiler: 11.2
MMDetection: 2.25.3
MMSegmentation: 0.29.1
MMDetection3D: 1.0.0rc5+
spconv2.0: True

### Reproduces the problem - code sample

There is no code.

### Reproduces the problem - command or script

python tools/test.py configs/centerpoint/centerpoint_0075voxel_second_secfpn_dcn_4x8_cyclic_20e_nus.py xxx.pth --eval mAP

### Reproduces the problem - error message

The provided url of ```centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus.py``` in the doc is ```https://download.openmmlab.com/mmdetection3d/v1.0.0_models/centerpoint/centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus/centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus_20210827_161135-1782af3e.pth```, but the url in the metafile.yaml is ```https://download.openmmlab.com/mmdetection3d/v0.1.0_models/centerpoint/centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus/centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus_20200930_201619-67c8496f.pth```.
I have tested downloaded checkpoints and I think the url in the metafile.yaml is wrong (NDS: 0.5406, mAP: 0.5733).

**Comment by ZCMax** [comment]
Please refer to this https://github.com/open-mmlab/mmdetection3d/pull/2006

**Comment by AlmoonYsl** [comment]
Thanks！
