### ISSUE TITLE
How to use mmdet2d in mmdet3d? Could you give an example? Thx!

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection3d#2057]
### What's the feature?

How to use mmdet2d in mmdet3d? Could you give an example? Thx!

**Comment by carlinds** [comment]
Sorry for hijacking your thread, but I have a use case that fits very well with the question.
What would be the best way for training a 2D-detector from mmdet (for example: https://github.com/open-mmlab/mmdetection/blob/master/configs/swin/mask_rcnn_swin-t-p4-w7_fpn_1x_coco.py) on a dataset supported in mmdet3d (nuscenes for example)?
Preferably for the 2D detection task to begin with, but also extending to training and evaluating the 3D task later on.

**Comment by Tai-Wang** [comment]
Configs under this folder may help you understand how to use mmdet models with mmdet3d supported datasets.

**Comment by zhongqiu1245** [comment]
Thank you, all guys!~
