### ISSUE TITLE
How to get plot as mmdet3d_outdoor_demo.gif ?

### ISSUE THREAD

**Issue by Zhoushanglin100** [open-mmlab/mmdetection3d#206]
HI, just want to know how to get the plot as mmdet3d_outdoor_demo.gif shows? Which dataset is that, and which tools are using to get that gif? Also, is that generated by combining several sequential figures, or directly conduct on a video? Thanks!

**Comment by ZwwWayne** [comment]
It is generated using the API function `render_sample_data` of the [nuscenes official devkit](https://github.com/nutonomy/nuscenes-devkit). It is nuscenes dataset and I simply combine single images to a gif.
