### ISSUE TITLE
[Docs] Policy abbreviation for LR scheduler

### ISSUE THREAD

**Issue by holtvogt** [open-mmlab/mmdetection3d#2067]
### Branch

master branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

While trying out different LR schedulers for training, I was missing the information about the abbreviation of the schedulers used as key `policy` in the `lr_config` dictionary. Unfortunately, I did not find it under https://github.com/open-mmlab/mmcv/blob/v1.3.7/mmcv/runner/hooks/lr_updater.py

Do I have to look somewhere else or is this information missing in the docs?

### Suggest a potential alternative/fix

Add a note for the `policy` in the scheduler documentation.

**Comment by JingweiZhang12** [comment]
Please refer to https://github.com/open-mmlab/mmcv/blob/v1.3.7/mmcv/runner/base_runner.py#L383-L393 and https://github.com/open-mmlab/mmcv/blob/v1.3.7/mmcv/runner/hooks/lr_updater.py
