### ISSUE TITLE
 MMDetection3D:waymo-open-dataset-tf-2-3-0 does not support Windows

### ISSUE THREAD

**Issue by 15598003953** [open-mmlab/mmdetection3d#2088]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection3d

### Environment

mmcls           0.24.1     https://github.com/open-mmlab/mmclassification
mmcv-full       1.6.2      https://github.com/open-mmlab/mmcv
mmdet           2.26.0     https://github.com/open-mmlab/mmdetection
mmdet3d         1.1.0rc1   d:\code\mmdetection3d
mmengine        0.3.2      https://github.com/open-mmlab/mmengine
mmsegmentation  0.29.1     http://github.com/open-mmlab/mmsegmentation

### Reproduces the problem - code sample

pip install waymo-open-dataset-tf-2-3-0

### Reproduces the problem - command or script

pip install waymo-open-dataset-tf-2-3-0

### Reproduces the problem - error message

ERROR: Could not find a version that satisfies the requirement waymo-open-dataset-tf-2-3-0 (from versions: none)
ERROR: No matching distribution found for waymo-open-dataset-tf-2-3-0

### Additional information

waymo-open-dataset-tf-2-3-0能否支持Windows

**Comment by JingweiZhang12** [comment]
Maybe waymo-open-dataset-tf-2-3-0 have some conflicts with other libs rather than the cause of OS.

**Comment by Tai-Wang** [comment]
From my experience, it's hard to use waymo devkit with tensorflow on windows, so we would recommend use ubuntu or mac for waymo experiments.
