### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by m-shahbaz-kharal** [open-mmlab/mmdetection3d#2089]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

sys.platform: linux
Python: 3.9.15 (main, Nov  4 2022, 16:13:54) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3080 Laptop GPU
CUDA_HOME: /home/me/miniconda3/envs/open-mmlab
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.5
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - Built with CUDA Runtime 11.2
  - NVCC architecture flags: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_50,code=compute_50
  - CuDNN 8.2.1  (built against CUDA 11.3)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.2, CUDNN_VERSION=8.2.1, CXX_COMPILER=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1627653194412/_build_env/bin/x86_64-conda-linux-gnu-c++, CXX_FLAGS=-std=c++14 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1627653194412/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/include -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1627653194412/work=/usr/local/src/conda/pytorch-1.9.0 -fdebug-prefix-map=/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1627653194412/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh=/usr/local/src/conda-prefix -I/usr/local/cuda/include -Wno-deprecated-declarations -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=1, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.10.0a0
OpenCV: 4.6.0
MMEngine: 0.3.1
MMDetection: 3.0.0rc3
MMDetection3D: 1.1.0rc1+f599806
spconv2.0: False

### Reproduces the problem - code sample

`
python tools/create_data.py kitti --root-path=<my_dataset_root> --out-dir=<my_dataset_root> --extra-tag kitti
`

### Reproduces the problem - command or script

I am using kitti-style to organize my data.
`
ImageSets
-- test.txt
-- train.txt
-- val.txt
testing
-- calib
-- image_2
-- velodyne
training
-- calib
-- image_2
-- label_2
-- velodyne
`

and I ran this:
`
python tools/create_data.py kitti --root-path=<my_dataset_root> --out-dir=<my_dataset_root> --extra-tag kitti
`

### Reproduces the problem - error message

Generate info. this may take several minutes.
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1218/1218, 180.1 task/s, elapsed: 7s, ETA:     0s
Kitti info train file is saved to data/pedsafe/kitti_format_train_attempt_01/kitti_infos_train.pkl
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1218/1218, 210.8 task/s, elapsed: 6s, ETA:     0s
Kitti info val file is saved to data/pedsafe/kitti_format_train_attempt_01/kitti_infos_val.pkl
Kitti info trainval file is saved to data/pedsafe/kitti_format_train_attempt_01/kitti_infos_trainval.pkl
Kitti info test file is saved to data/pedsafe/kitti_format_train_attempt_01/kitti_infos_test.pkl
create reduced point cloud for training set
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1218/1218, 115.1 task/s, elapsed: 11s, ETA:     0s
create reduced point cloud for validation set
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1218/1218, 119.3 task/s, elapsed: 10s, ETA:     0s
create reduced point cloud for testing set
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 523/523, 76.4 task/s, elapsed: 7s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1218/1218, 64.8 task/s, elapsed: 19s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1218/1218, 65.4 task/s, elapsed: 19s, ETA:     0s
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 2436/2436, 66.4 task/s, elapsed: 37s, ETA:     0s
./data/pedsafe/kitti_format_train_attempt_01/kitti_infos_train.pkl will be modified.
Warning, you may overwriting the original data ./data/pedsafe/kitti_format_train_attempt_01/kitti_infos_train.pkl.
Reading from input file: ./data/pedsafe/kitti_format_train_attempt_01/kitti_infos_train.pkl.
Start updating:
[>>>>>>>>>>>>>                                     ] 341/1218, 684.9 task/s, elapsed: 0s, ETA:     1sTraceback (most recent call last):
  File "/mnt/d/work/urbanity/hands_on/experiments/base-codes/open-mmlab/mmdetection3d/tools/create_data.py", line 269, in <module>
    kitti_data_prep(
  File "/mnt/d/work/urbanity/hands_on/experiments/base-codes/open-mmlab/mmdetection3d/tools/create_data.py", line 41, in kitti_data_prep
    update_pkl_infos('kitti', out_dir=out_dir, pkl_path=info_train_path)
  File "/mnt/d/work/urbanity/hands_on/experiments/base-codes/open-mmlab/mmdetection3d/tools/dataset_converters/update_infos_to_v2.py", line 1054, in update_pkl_infos
    update_kitti_infos(pkl_path=pkl_path, out_dir=out_dir)
  File "/mnt/d/work/urbanity/hands_on/experiments/base-codes/open-mmlab/mmdetection3d/tools/dataset_converters/update_infos_to_v2.py", line 492, in update_kitti_infos
    cam_instances = generate_kitti_camera_instances(ori_info_dict)
  File "/mnt/d/work/urbanity/hands_on/experiments/base-codes/open-mmlab/mmdetection3d/tools/dataset_converters/update_infos_to_v2.py", line 1009, in generate_kitti_camera_instances
    ann_infos = get_kitti_style_2d_boxes(
  File "/mnt/d/work/urbanity/hands_on/experiments/base-codes/open-mmlab/mmdetection3d/mmdet3d/datasets/convert_utils.py", line 288, in get_kitti_style_2d_boxes
    repro_rec = generate_record(ann_rec, min_x, min_y, max_x, max_y,
  File "/mnt/d/work/urbanity/hands_on/experiments/base-codes/open-mmlab/mmdetection3d/mmdet3d/datasets/convert_utils.py", line 402, in generate_record
    if cat_name not in categories:
UnboundLocalError: local variable 'categories' referenced before assignment

### Additional information

I think the problem is fairly simple, if you move these lines in ```mmdet3d/datasets/convert_utils.py":

[405] if dataset == 'kitti':
[406]             categories = kitti_categories
[407]         elif dataset == 'waymo':
[408]             categories = waymo_categories
[409]         else:
[410]             raise NotImplementedError('Unsupported dataset!')

before:

[402] if cat_name not in categories:
[403]           return None

It should be solved.

**Comment by Xiangxu-0103** [comment]
It has been fixed in `dev-1.x` branch, please checkout to `dev-1.x` branch.
