### ISSUE TITLE
[New Models] second_hv_secfpn_8xb6-80e missing

### ISSUE THREAD

**Issue by shanmo** [open-mmlab/mmdetection3d#2101]
### Model/Dataset/Scheduler description

There is no download link for `second_hv_secfpn_8xb6-80e_kitti-3d-car_20200620_230238-393f000c.pth` in [model zoo](https://github.com/open-mmlab/mmdetection3d/tree/1.1/configs/second) used in [demo](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/getting_started.md#verify-with-point-cloud-demo)

### Open source status

- [x] The model implementation is available
- [x] The model weights are available.

**Comment by alexandrefch** [comment]
The model can be found here : https://github.com/open-mmlab/mmdetection3d/tree/1.1/configs/second#results-and-models

The specific one of the demo `second_hv_secfpn_8xb6-80e_kitti-3d-car_20200620_230238-393f000c.pth` correspond to the first one in the table :
|                              Backbone                               |  Class  |  Lr schd   | Mem (GB) | Inf time (fps) |  mAP  |                                                                                                                                                                                             Download                                                                                                                                                                                             |
| :-----------------------------------------------------------------: | :-----: | :--------: | :------: | :------------: | :---: | :----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------: |
|        [SECFPN](./second_hv_secfpn_8xb6-80e_kitti-3d-car.py)        |   Car   | cyclic 80e |   5.4    |                | 79.07 |               [model](https://download.openmmlab.com/mmdetection3d/v0.1.0_models/second/hv_second_secfpn_6x8_80e_kitti-3d-car/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth) \| [log](https://download.openmmlab.com/mmdetection3d/v0.1.0_models/second/hv_second_secfpn_6x8_80e_kitti-3d-car/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238.log.json)               |

**Comment by alexandrefch** [comment]
As mentioned in the Quick start guide : https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/getting_started.md#verification

The demo command is 
```shell
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
```

Here the needed model name is `hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth`, the one that you can download
