### ISSUE TITLE
CUDA out of memory error

### ISSUE THREAD

**Issue by ShreyanshGoyal17** [open-mmlab/mmdetection3d#2116]
### Branch

master branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

I am using 4 GPUs for training PointRCNN network but during training it runs out of memory during the 23rd EPOCH, giving the following error:

RuntimeError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 1; 79.35 GiB total capacity; 76.56 GiB already allocated; 2.62 MiB free; 77.09 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
srun: error: gpu-4-11: task 1: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=36525.0
slurmstepd: error: *** STEP 36525.0 ON gpu-4-11 CANCELLED AT 2022-11-04T18:19:35 ***
srun: error: gpu-4-11: task 0: Terminated
srun: error: gpu-4-11: tasks 2-3: Terminated

Is there any change I need to make in the code to make it work with only 4 GPUs? Any suggestion would be helpful. 
Thanks

### Suggest a potential alternative/fix

Maye be I can turnoff validation after each epoch to save some memory, not sure if it will work.

**Comment by JingweiZhang12** [comment]
https://github.com/open-mmlab/mmdetection3d/issues/1907
