### ISSUE TITLE
RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 0 does not equal 2 (while checking arguments for cudnn_convolution)

### ISSUE THREAD

**Issue by mmmcn** [open-mmlab/mmdetection3d#214]
hello, this error occurred when I try to train a model using `python tools/train.py config/3dssd/3dssd_kitti-3d-car.py --gpu-ids=2`.  
and I found this problem first occurs on through the backbone to extract features,so I set a breakpoints at `mmdet3d/models/detectors/votenet.py:55`, and try to debug, but the outputs suggested that my input_points and model_weight are already on the same device. so I am very confused.
```python
(Pdb) points[0][0,:]
tensor([ 9.5171,  1.8622, -1.5114,  0.2900], device='cuda:2')
(Pdb) print(next(self.SA_modules[0].parameters())
[...], device='cuda:2', requires_grad=True)
```

```python
# votenet.py
    def forward_train(self,
                      points,
                      img_metas,
                      gt_bboxes_3d,
                      gt_labels_3d,
                      pts_semantic_mask=None,
                      pts_instance_mask=None,
                      gt_bboxes_ignore=None):
        """Forward of training.

        Args:
            points (list[torch.Tensor]): Points of each batch.
            img_metas (list): Image metas.
            gt_bboxes_3d (:obj:`BaseInstance3DBoxes`): gt bboxes of each batch.
            gt_labels_3d (list[torch.Tensor]): gt class labels of each batch.
            pts_semantic_mask (None | list[torch.Tensor]): point-wise semantic
                label of each batch.
            pts_instance_mask (None | list[torch.Tensor]): point-wise instance
                label of each batch.
            gt_bboxes_ignore (None | list[torch.Tensor]): Specify
                which bounding.

        Returns:
            dict: Losses.
        """
        points_cat = torch.stack(points)

        x = self.extract_feat(points_cat)
        bbox_preds = self.bbox_head(x, self.train_cfg.sample_mod)
        loss_inputs = (points, gt_bboxes_3d, gt_labels_3d, pts_semantic_mask,
                       pts_instance_mask, img_metas)
        losses = self.bbox_head.loss(
            bbox_preds, *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
        return losses
```
**I can avoid this problem by using `CUDA_VISIBLE_DEVICES=2 python tools/train.py config/3dssd/3dssd_kitti-3d-car.py `, but is there a better solution?**  
  
**environement:**  
TorchVision: 0.6.0+cu101
OpenCV: 4.4.0
MMCV: 1.1.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.5.0
MMDetection3D: 0.6.1+64a8c45

sys.platform: linux
Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3: Tesla V100-PCIE-32GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
PyTorch: 1.5.0+cu101

**Comment by ZwwWayne** [comment]
This means some variables are not in CUDA device 2 without specifying the devices. For now, we suggest keeping using `CUDA_VISIBLE_DEVICES=2`, which is the safest way. We will also check the code in the future.
