### ISSUE TITLE
when I test pcd dataset  collected by oneself use /mmdetection3d/demo/pcd_demo.py ,the result was not as expected.

### ISSUE THREAD

**Issue by cxy86121** [open-mmlab/mmdetection3d#2159]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection3d

### Environment

environment is ok , the output format  is consistent with the KITTI data set。

### Reproduces the problem - code sample

```python
def pcd2bin(input_pcd_path, output_bin_path):
    pcd_data = pypcd.PointCloud.from_path(input_pcd_path)
    points = np.zeros([pcd_data.width, 4], dtype=np.float32)
    points[:, 0] = pcd_data.pc_data['x'].copy()
    points[:, 1] = pcd_data.pc_data['y'].copy()
    points[:, 2] = pcd_data.pc_data['z'].copy()
    points[:, 3] = pcd_data.pc_data['intensity'].copy().astype(np.float32)

    if not os.path.exists(output_bin_path):
        os.mknod(output_bin_path)
    with open(output_bin_path, 'rb+') as f:
        f.write(points.tobytes())
```
I change the dataset use code above -> **pcd2bin**.

Use **hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py** config file
and **hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306-37dc2420.pth** mdoel parameter.

### Reproduces the problem - command or script

...

### Reproduces the problem - error message

The problem description is presented using pictures, please refer to the following [link：](https://blog.csdn.net/qq_43685921/article/details/128373849?spm=1001.2014.3001.5501)

**Comment by JingweiZhang12** [comment]
Could you please provide your file of the processed point cloud?

**Comment by cxy86121** [comment]
> Could you please provide your file of the processed point cloud?
Thank you for replying to my message!!! my  file of the processed point cloud is :
link: https://pan.baidu.com/s/1uQCn1w1Z2F9JNHW46RhEkg 
Extraction code: 1111 
the pcd_file folder is pcd source file，the bin_file folder is converted file from pcd 2 bin ,and the results folder is my test result，I convert pcd 2 bin use pcd2bin.py file,thanks a lot!!!

**Comment by cxy86121** [comment]
> Could you please provide your file of the processed point cloud?

dear author ,I figured it out. When I converted the data use pcd2bin function, need change the method:
points[:, 3] = pcd_data.pc_data['intensity'].copy().astype(np.float32) 
-->
points[:, 3] = pcd_data.pc_data['intensity'].copy().astype(np.float32)/256
and then the result is as expected,thanks!

**Comment by Tai-Wang** [comment]
It's related to the definition of intensity in your collected data. Typically you need to rescale the intensity to the standard interval similar to our provided demo data.
