### ISSUE TITLE
where can download the pretrained-3DSSD models?

### ISSUE THREAD

**Issue by liyang0522** [open-mmlab/mmdetection3d#216]
could you please tell me where i can download the 3DSSD MODELS?

**Comment by RAYRAYRAYRita** [comment]
I have the same question about 3dssd pretrained model, could you please give me some advice?

**Comment by zye1996** [comment]
> I have the same question about 3dssd pretrained model, could you please give me some advice?

I made a released version (here)[https://github.com/zye1996/3DSSD-torch] if you are still interested
