### ISSUE TITLE
[Bug] waymo1.4 create_data.py for testing

### ISSUE THREAD

**Issue by sylcito** [open-mmlab/mmdetection3d#2177]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Cuda compilation tools, release 11.1, V11.1.74
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.9.1+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.1+cu111
OpenCV: 4.6.0
MMEngine: 0.3.2
MMDetection: 3.0.0rc5
MMDetection3D: 1.1.0rc2+edc468b
spconv2.0: False

### Reproduces the problem - code sample

None

### Reproduces the problem - command or script

python tools/create_data.py waymo --root-path ./data/waymo/ --out-dir ./data/waymo/ --workers 128 --extra-tag waymo

### Reproduces the problem - error message

Traceback (most recent call last):
  File "create_data.py", line 319, in <module>
    max_sweeps=args.max_sweeps)
  File "create_data.py", line 203, in waymo_data_prep
    converter.convert()
  File "/data1/work/mmdetection3d/tools/dataset_converters/waymo_converter.py", line 115, in convert
    self.convert_one(i)
  File "/data1/work/mmdetection3d/tools/dataset_converters/waymo_converter.py", line 139, in convert_one
    self.save_lidar(frame, file_idx, frame_idx)
  File "/data1/work/mmdetection3d/tools/dataset_converters/waymo_converter.py", line 242, in save_lidar
    ri_index=0
  File "/data1/work/mmdetection3d/tools/dataset_converters/waymo_converter.py", line 505, in convert_range_image_to_point_cloud
    tf.convert_to_tensor(value=range_image_top_pose.data),
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by JingweiZhang12** [comment]
What is the version of your Tensorflow? Suggest you can profile the returns of this line:  https://github.com/open-mmlab/mmdetection3d/blob/dev-1.x/tools/dataset_converters/waymo_converter.py#L231

**Comment by sylcito** [comment]
> What is the version of your Tensorflow? Suggest you can profile the returns of this line: https://github.com/open-mmlab/mmdetection3d/blob/dev-1.x/tools/dataset_converters/waymo_converter.py#L231

tensorflow                         2.6.0
waymo-open-dataset-tf-2-6-0        1.4.9

Could this be a problem caused by the tensorflow version?

**Comment by JingweiZhang12** [comment]
The version of  `waymo-open-dataset-tf-2-6-0 ` has an influence on returns of some api functions. You can trace the returns of this line: https://github.com/open-mmlab/mmdetection3d/blob/dev-1.x/tools/dataset_converters/waymo_converter.py#L231

**Comment by ZJLi2013** [comment]
> > What is the version of your Tensorflow? Suggest you can profile the returns of this line: https://github.com/open-mmlab/mmdetection3d/blob/dev-1.x/tools/dataset_converters/waymo_converter.py#L231
> 
> tensorflow 2.6.0 waymo-open-dataset-tf-2-6-0 1.4.9
> 
> Could this be a problem caused by the tensorflow version?

is there any suggestions for waymo now ?
