### ISSUE TITLE
SSN

### ISSUE THREAD

**Issue by alsun-oven** [open-mmlab/mmdetection3d#218]
Does the ssn in mmdetection3d have Shape Completion and Shape Embedding。

**Comment by Tai-Wang** [comment]
Not yet. Adding shape signature part needs some adjustments in terms of data pipelines and data converter, so we focus more on the shape-aware grouping heads, which contributes most in the whole framework. You can refer to the [official release](https://github.com/xinge008/SSN) for implementation of that add-on component. PRs are also welcome.
