### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by achao2013** [open-mmlab/mmdetection3d#219]
if use only xyz point(set shift_height=False) for input, error occurs.
The in_channel==3, and the features is none.

![image](https://user-images.githubusercontent.com/5026576/101358374-b7eec480-38d5-11eb-80b2-6a275a2b3739.png)
@ZwwWayne @yinchimaoliang

**Comment by yinchimaoliang** [comment]
In votenet, we set shift_height=True, so we can transfer the shape of the point cloud from [n*3] to [n*4] by adding an extra channel of height. You can see the implementation detal [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/loading.py#L376). If you set shift_height=False, there will be one channel missing.

**Comment by neverrop** [comment]
> In votenet, we set shift_height=True, so we can transfer the shape of the point cloud from (nx3) to (nx4) by adding an extra channel of height. You can see the implementation details [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/loading.py#L376). If you set shift_height=False, there will be one channel missing.

the shifted height channel is only necessary for voetenet and imvotenet? why is it necessary for them.
