### ISSUE TITLE
[Bug] training pv-rcnn: TypeError: forward() takes 6 positional arguments but 8 were given

### ISSUE THREAD

**Issue by DurbinLiu** [open-mmlab/mmdetection3d#2213]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

sys.platform: linux
Python: 3.8.15 (default, Nov 24 2022, 15:19:38) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-11.1
NVCC: Cuda compilation tools, release 11.1, V11.1.74
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.10.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.0+cu111
OpenCV: 4.1.2
MMEngine: 0.1.0
MMDetection: 3.0.0rc1
MMDetection3D: 1.1.0rc2+449ecb0
spconv2.0: False

### Reproduces the problem - code sample

[default config file for pv-rcnn](https://github.com/open-mmlab/mmdetection3d/blob/dev-1.x/configs/pv_rcnn/pv_rcnn_8xb2-80e_kitti-3d-3class.py). I just set use_ground_plane to be False, as my own dataset has no ground plane.

### Reproduces the problem - command or script

`python tools/train.py configs/pv_rcnn/pv_rcnn_8xb2-80e_kitti-3d-3class.py`

### Reproduces the problem - error message

01/10 21:44:15 - mmengine - INFO - Checkpoints will be saved to /home/data1/czp/code/DAIR-V2X/mmdetection3d/work_dirs/pvrcnn_veh by HardDiskBackend.
/home/czp/.conda/envs/det3d/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/czp/.conda/envs/det3d/lib/python3.8/site-packages/mmdet/models/task_modules/samplers/sampling_result.py:133: UserWarning: DeprecationWarning: pos_bboxes is deprecated, please use "pos_priors" instead
  warnings.warn('DeprecationWarning: pos_bboxes is deprecated, '
Traceback (most recent call last):
  File "tools/train.py", line 124, in <module>
    main()
  File "tools/train.py", line 120, in main
    runner.train()
  File "/home/czp/.conda/envs/det3d/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1631, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/czp/.conda/envs/det3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 88, in run
    self.run_epoch()
  File "/home/czp/.conda/envs/det3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 104, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/czp/.conda/envs/det3d/lib/python3.8/site-packages/mmengine/runner/loops.py", line 120, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/czp/.conda/envs/det3d/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/home/czp/.conda/envs/det3d/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 298, in _run_forward
    results = self(**data, mode=mode)
  File "/home/czp/.conda/envs/det3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/data1/czp/code/DAIR-V2X/mmdetection3d/mmdet3d/models/detectors/base.py", line 74, in forward
    return self.loss(inputs, data_samples, **kwargs)
  File "/home/data1/czp/code/DAIR-V2X/mmdetection3d/mmdet3d/models/detectors/pv_rcnn.py", line 224, in loss
    points_feats_dict = self.extract_points_feat(batch_inputs_dict,
  File "/home/data1/czp/code/DAIR-V2X/mmdetection3d/mmdet3d/models/detectors/pv_rcnn.py", line 173, in extract_points_feat
    return self.points_encoder(batch_inputs_dict, feats_dict,
  File "/home/czp/.conda/envs/det3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/data1/czp/code/DAIR-V2X/mmdetection3d/mmdet3d/models/middle_encoders/voxel_set_abstraction.py", line 287, in forward
    pooled_points, pooled_features = self.rawpoints_sa_layer(
  File "/home/czp/.conda/envs/det3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/data1/czp/code/DAIR-V2X/mmdetection3d/mmdet3d/models/layers/pointnet_modules/stack_point_sa_module.py", line 182, in forward
    grouped_features, ball_idxs = self.groupers[k](
  File "/home/czp/.conda/envs/det3d/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/data1/czp/code/DAIR-V2X/mmdetection3d/mmdet3d/models/layers/pointnet_modules/stack_point_sa_module.py", line 62, in forward
    idx = ball_query(0, self.radius, self.sample_nums, xyz, new_xyz,
TypeError: forward() takes 6 positional arguments but 8 were given

### Additional information

- I was using pv-rcnn to train on my own dataset, which was first prepared to have the same format as KITTI dataset and then updated to version v2 using tools/dataset_converters/update_infos_to_v2.py.

- Except for setting use_ground_plane to be False and changing data_root, I didn't change anything in the default config file.

- As I have trained the dataset successfully using point-rcnn and pointpillars with the same environment, I think it was not the problem of my dataset or environment.

**Comment by Xiangxu-0103** [comment]
You need to upgrade mmcv version to v2.0.0rc3 for training `pv_rcnn`
