### ISSUE TITLE
[Bug] PETR batch size > 1 in dev-1.x

### ISSUE THREAD

**Issue by caiqi** [open-mmlab/mmdetection3d#2219]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

Python3.8 

### Reproduces the problem - code sample

https://github.com/open-mmlab/mmdetection3d/blob/341ff9980f624b2fbd3ce2b161590f821056f0a3/projects/PETR/petr/petr.py#L290
This line assume that gt_bboxes_3d contains only one item, i.e., batch size = 1. For batch size >1, this will ignore other items in the batch. 

https://github.com/open-mmlab/mmdetection3d/blob/341ff9980f624b2fbd3ce2b161590f821056f0a3/projects/PETR/petr/petr.py#L268
The lidar2img_rts = [] should be in the loop of for meta in batch_input_metas, otherwise it will updated repeatly.

### Reproduces the problem - command or script

No

### Reproduces the problem - error message

No

**Comment by ZCMax** [comment]
this bug will be fixed in https://github.com/open-mmlab/mmdetection3d/pull/2212/files

**Comment by SekiroRong** [comment]
Hi, thanks very much for pointing out 2 bugs. Please checkout the most recent commit of mine: [https://github.com/open-mmlab/mmdetection3d/pull/2212](url).
