### ISSUE TITLE
Visualization of results

### ISSUE THREAD

**Issue by SimonDoll** [open-mmlab/mmdetection3d#222]
May someone give me a hint on how to visualize results e.g. pointcloud with predictions and ground truth and maybe a camera image for better visibility?
As stated in the getting_started section I've tried out Meshlab for point cloud / mesh visualization but the generated results from a pretrained network can't be opened by meshlab. Are there any other tools available e.g. open3d?

**Comment by Tai-Wang** [comment]
For 3D visualization, a better solution based on other tools like open3d and mayavi is in our plan.
For 2D visualization, it is also in our plan and for now you can temporarily refer to this [repo](https://github.com/kuixu/kitti_object_vis).
If you would like to use the current visualization function, maybe you can provide more information about why the results can not be opened by meshlab. It should work well from my experience.
