### ISSUE TITLE
Nuscenes Multi modality dataset config

### ISSUE THREAD

**Issue by SimonDoll** [open-mmlab/mmdetection3d#223]
May You provide a multi modality configuration  for nuscenes e.g. lidar + single rgb image / multi view images

It is inconvenient not having an example for multi modality datasets especially for kitti or nuscenes.
It would be great to get some hints on how to add multi modalities to a dataset config, only changing the input_modality dict or adding a LoadPointsFromFile layer to the data pipeline does not seem to be sufficient,  (ends in errors in the custom_3d.py dataset class).

**Comment by Tai-Wang** [comment]
You can take this [config](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/mvxnet) as an example for now. We will support new state-of-the-art methods with multi-modality in near future.

**Comment by SimonDoll** [comment]
Thx a lot @Tai-Wang, seems to be a good starting point :+1:

**Comment by HuangDihe** [comment]
> Thx a lot @Tai-Wang, seems to be a good starting point 👍

hi, did you finish the multi modality configuration for nuscenes?
