### ISSUE TITLE
[Bug] mmcv now has version 1.7.1, do we need to modify mmdet3d/__init__.py with mmcv_maximum_version = '1.7.1'?

### ISSUE THREAD

**Issue by qipengh** [open-mmlab/mmdetection3d#2243]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection3d

### Environment

mmcls                   0.25.0
mmcv-full               1.7.1
mmdet                   2.27.0
mmdet3d                 1.0.0rc6
mmsegmentation          0.30.0
pytorch-lightning       1.6.0
torch                   1.9.0
torchmetrics            0.11.0
torchvision             0.10.0a0+300a8a4

### Reproduces the problem - code sample

Based on these versions (mmcv-full==1.7.1, mmdet3d==1.0.0rc6), running any script is reproducible

### Reproduces the problem - command or script

Based on these versions (mmcv-full==1.7.1, mmdet3d==1.0.0rc6), running any script is reproducible

### Reproduces the problem - error message

AssertionError: MMCV==1.7.1 is used but incompatible. Please install mmcv>=1.5.2, <=1.7.0.

### Additional information

modify mmdet3d/__init__.py with mmcv_maximum_version = '1.7.1'?

**Comment by ZwwWayne** [comment]
We should upgrade, we can set maximun version to 1.8.0.

**Comment by ZwwWayne** [comment]
Would you like to create a PR to fix it?

**Comment by qipengh** [comment]
cool！ that's great. i can do it

**Comment by qipengh** [comment]
PR has been submitted, please check and review. @ZwwWayne
