### ISSUE TITLE
PGD some questions

### ISSUE THREAD

**Issue by happyday-lkj** [open-mmlab/mmdetection3d#2245]
### What's the feature?

hello, some questions: 
1. In pgd_r101_caffe_fpn_gn-head_3x4_4x_kitti-mono3d.py, when I set  the "score_thr"  is less than 5, there are many false alrms, why the "score_thr" value is largger  than 1.0?  such as issue https://github.com/open-mmlab/mmdetection3d/issues/1024#issuecomment-975395697
2. I test the PGD and SMOKE, I find SMOKE is much quicker than PGD, but as the paper reported, PDG is about 28ms, and SMOKE is 30ms? It is because the Backbone?

**Comment by happyday-lkj** [comment]
> ### What's the feature?
> 
> hello, some questions:
> 
>     1. In pgd_r101_caffe_fpn_gn-head_3x4_4x_kitti-mono3d.py, when I set  the "score_thr"  is less than 5, there are many false alrms, why the "score_thr" value is largger  than 1.0?  such as issue [Questions about FCOS3D and PGD model 3D box #1024 (comment)](https://github.com/open-mmlab/mmdetection3d/issues/1024#issuecomment-975395697)
> 
>     2. I test the PGD and SMOKE, I find SMOKE is much quicker than PGD, but as the paper reported, PDG is about 28ms, and SMOKE is 30ms? It is because the Backbone?
> 
> 
> ### Any other context?
> 
> _No response_

打印了SMOKE、Fcos3D以及PGD三种算法的backBone、head以及后处理的耗时，发现三者耗时主要区别在 head这块，所以PDG这个耗时这么严重的吗

**Comment by Tai-Wang** [comment]
1. Because the confidence score derived from the uncertainty indicator can be much larger than 1. Please refer to [this comment](https://github.com/open-mmlab/mmdetection3d/issues/1024#issuecomment-972761663).
2. FCOS3D and PGD have heavier detection heads than typical 2D detectors indeed, and it is a characteristic of similar mono3d detectors. We have a lightweight version that has still not been released, but you can try to reduce the model size of the head, like reducing the number of stacked shared conv layers and the feature channels. We will consider updating the model and configs after more models get ready in the next two months.

**Comment by happyday-lkj** [comment]
> 

thanks for your reply!

**Comment by happyday-lkj** [comment]
> 1. Because the confidence score derived from the uncertainty indicator can be much larger than 1. Please refer to [this comment](https://github.com/open-mmlab/mmdetection3d/issues/1024#issuecomment-972761663).
> 
>     2. FCOS3D and PGD have heavier detection heads than typical 2D detectors indeed, and it is a characteristic of similar mono3d detectors. We have a lightweight version that has still not been released, but you can try to reduce the model size of the head, like reducing the number of stacked shared conv layers and the feature channels. We will consider updating the model and configs after more models get ready in the next two months.

thanks!

**Comment by benz725** [comment]
> 1. Because the confidence score derived from the uncertainty indicator can be much larger than 1. Please refer to [this comment](https://github.com/open-mmlab/mmdetection3d/issues/1024#issuecomment-972761663).
> 2. FCOS3D and PGD have heavier detection heads than typical 2D detectors indeed, and it is a characteristic of similar mono3d detectors. We have a lightweight version that has still not been released, but you can try to reduce the model size of the head, like reducing the number of stacked shared conv layers and the feature channels. We will consider updating the model and configs after more models get ready in the next two months.

I have a similar question, in paper you mentioned that the inference on 1080TI, the latency is 28ms (or 36 Hz), is quicker than SMOKE, and AP11 in KITTI is 24.35 18.34 16.90 (easy, moderate, hard). So how to get that result ? (A result run in latency 28ms and AP at 24.35 18.34 16.90 )

**Comment by turtlemicro** [comment]
@Tai-Wang Hey, would it be possible to get those lightweight versions of the PGD and FCOS3D detectors? I am writing a thesis about these models and I have to compare the quality based on speed and accuracy of the pretrained models on my own data. The accuracy is promising, but as already mentioned, the speed is not suitable for real-time inference, although it should be.
