### ISSUE TITLE
LR bug for resumed training?

### ISSUE THREAD

**Issue by BB88Lee** [open-mmlab/mmdetection3d#226]
Hi, I used 'resume-from' flag for a interrupted training process. 
I noticed that the learning rate is from the initial learning rate, it did not inherit the previous learning rate.

**Comment by Tai-Wang** [comment]
Please provide more details about your problem.
From my experience, `resume-from` would help you start from the last epoch before your training procedure gets interrupted. Maybe what you mean is that it does not continue from the last iteration/step before the interruption?

**Comment by BB88Lee** [comment]
I am wrong, the learning rate was inherited from the last checkpoint.
This is no problem, thanks for the reply!
So the question is closed.
