### ISSUE TITLE
Grid search cv on mmdetection

### ISSUE THREAD

**Issue by enesdorukadastec** [open-mmlab/mmdetection3d#2261]
### Model/Dataset/Scheduler description

Hi, how can i use grid search cv on mmdetection, is it possible to use via config?

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by JingweiZhang12** [comment]
MMDetection doesn't support it. If you want to search parameters, you can write a script referring to https://github.com/open-mmlab/mmtracking/blob/dev-1.x/tools/analysis_tools/mot/mot_param_search.py

**Comment by enesdorukadastec** [comment]
thanks @JingweiZhang12
