### ISSUE TITLE
visualizing model network

### ISSUE THREAD

**Issue by enesdorukadastec** [open-mmlab/mmdetection3d#2272]
### What's the feature?

Hi, i want to visualize centerpoint 3d dedector, is there any config or tool in mmdetection3d, how can i visualize?

**Comment by JingweiZhang12** [comment]
`python demo/pcd_demo.py ${PCD_FILE} ${CONFIG} ${CHECKPOINT} --show --score-thr=${SCORE}`

**Comment by enesdorukadastec** [comment]
i know but i want to visualize like torchviz or netron,

**Comment by JingweiZhang12** [comment]
> i know but i want to visualize like torchviz or netron,

We have not supported it yet.
