### ISSUE TITLE
[Feature] Is MMdet3d compatible with OpenPCDet?

### ISSUE THREAD

**Issue by FrontierBreaker** [open-mmlab/mmdetection3d#2293]
### What's the feature?

Hi, I would like to know whether the pretrained models (e.g., pretrained backbone(voxelnet)) trained in OpenPCDet can be load to a model in mmdet3d? Thanks!

**Comment by Xiangxu-0103** [comment]
I think you may need to convert models trained on OpenPCDet to mmdet3d format to ensure the model can be loaded correctly. tools/model_converters/regnet2mmdet.py shows an example.
