### ISSUE TITLE
[Bug] Concatenating Dataset

### ISSUE THREAD

**Issue by enesdorukadastec** [open-mmlab/mmdetection3d#2296]
### What's the feature?

Hi i created 3d lidar dataset as same as Nuscene dataset format. I want to concatenate this dataset for training and i followed mmdetection3d documentation steps but i got error. 

with_velocity = False
dataset_nuscene = dict(
            type=dataset_type,
            data_root=data_root,
            ann_file=data_root + 'nuscenes_infos_train.pkl',
            pipeline=train_pipeline,
            classes=class_names,
            with_velocity=with_velocity,
            test_mode=False,
            use_valid_flag=True,
            box_type_3d='LiDAR')

dataset_adascene = dict(
            type=dataset_type_adas,
            data_root=data_root_adas,
            ann_file=data_root_adas + 'adascenes_infos_train.pkl',
            pipeline=train_pipeline,
            classes=class_names,
            with_velocity=with_velocity,
            test_mode=False,
            use_valid_flag=True,
            box_type_3d='LiDAR')

data = dict(
    train=dict(
        type='CBGSDataset',
        pipeline = train_pipeline,
        dataset=[dataset_nuscene, dataset_adascene]),
    val=dict(
        pipeline=test_pipeline,
        classes=class_names,
        with_velocity=with_velocity),
    test=dict(
        pipeline=test_pipeline,
        classes=class_names,
        with_velocity=with_velocity))

=====================================

Traceback (most recent call last):
  File "tools/train.py", line 303, in <module>
    main()
  File "tools/train.py", line 257, in main
    val_dataset.pipeline = cfg.data.train.dataset.pipeline
AttributeError: 'list' object has no attribute 'pipeline'

**Comment by Xiangxu-0103** [comment]
You may try to Concat datasets with `ConcatDataset` following this [config](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/s3dis-3d-5class.py) as an example.

**Comment by enesdorukadastec** [comment]
Thanks it works


data = dict(
train=dict(
type='ConcatDataset',
pipeline = train_pipeline,
datasets=[dataset_nuscene, dataset_adascene]),
val=dict(
pipeline=test_pipeline,
classes=class_names,
with_velocity=with_velocity),
test=dict(
pipeline=test_pipeline,
classes=class_names,
with_velocity=with_velocity))
