### ISSUE TITLE
Train Smoke on my own dataset

### ISSUE THREAD

**Issue by happyday-lkj** [open-mmlab/mmdetection3d#2298]
### What's the feature?

    hello, I have a question, I want to train SMOKE on my own dataset, and the image size is  1920*1080, I create the dataset format like KITTI format, and set the size of the model is 960*544, however, the result is very bad, the metric result is almost 0, and when I set the input size of model to 1920*1080, the metric result is better.
   so, there is any documents to reference ???  Or , what should I do when create the dataset, Or what should modified in config.py???

**Comment by IntegerNumber01** [comment]
Need help on that aswell!
