### ISSUE TITLE
[New dataset] Train Smoke on my own dataset

### ISSUE THREAD

**Issue by happyday-lkj** [open-mmlab/mmdetection3d#2299]
### Model/Dataset/Scheduler description

hello, I have a question, I want to train SMOKE on my own dataset, and the image size is  1920x1080, I create the dataset format like KITTI format, and set the size of the model is 960x544, however, the result is very bad, the metric result is almost 0, and when I set the input size of model to 1920x1080, the metric result is better.

so, if I need to set the input size of model to 960x544, there is any documents to reference ??? Or , what should I do when create the dataset, Or what should modified in config.py???

### Open source status

- [ ] The model implementation is available
- [ ] The model weights are available.

**Comment by Xiangxu-0103** [comment]
When you resize the image size from `1920x1080` to `960x544`, the camera intrinsic matrix should also be updated accordingly. You may refer to [Resize3D](https://github.com/open-mmlab/mmdetection3d/blob/dev-1.x/mmdet3d/datasets/transforms/transforms_3d.py#L1874) in dev-1.x branch as an example.

**Comment by happyday-lkj** [comment]
> When you resize the image size from `1920x1080` to `960x544`, the camera intrinsic matrix should also be updated accordingly. You may refer to [Resize3D](https://github.com/open-mmlab/mmdetection3d/blob/dev-1.x/mmdet3d/datasets/transforms/transforms_3d.py#L1874) in dev-1.x branch as an example.

OK， thanks
