### ISSUE TITLE
Single RGB 3D detector

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#23]
Hi,

Thanks for the amazing repo. From your point of view is it possible / recommended to implement custom 3d detectors with only 1 RGB as as input (with no point clouds) based on this codebase? Ex.: [SMOKE](https://github.com/lzccccc/SMOKE), [M3D-RPN](https://github.com/garrickbrazil/M3D-RPN).

**Comment by ZwwWayne** [comment]
Hi @filaPro ，
Of course, it is recommended and possible.
We do have plans to support mono-3D detectors in the future. PRs are also welcomed.
