### ISSUE TITLE
h3dnet model config parameter

### ISSUE THREAD

**Issue by achao2013** [open-mmlab/mmdetection3d#232]
what's the meaning of upper_thresh(default 100)?
why num_dims is 2,1,0 respectively in  primitive_z_cfg,primitive_xy_cfg,primitive_line_cfg？

**Comment by achao2013** [comment]
@encore-zhou @Tai-Wang 有人回答吗

**Comment by encore-zhou** [comment]
@achao2013 According to [paper](https://arxiv.org/abs/2006.05682), `primitive_z` means object center, `primitive_xy` means face center and `primitive_line` means edge center, so we use different dimension of vectors to represent the primitive center offset.
As for `upper_thresh`, we invalidate the GT center offset by assigning the this value. For more details, you can refer to [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/roi_heads/mask_heads/primitive_head.py#L784) or the [official implementation](https://github.com/zaiweizhang/H3DNet/blob/f827b19b1e74fa89d58dcbc40f841eec5bac737e/models/proposal_module_refine.py#L224).

**Comment by achao2013** [comment]
@encore-zhou  thanks, but that's not my question.  i want to know why set num_dims is 2,1,0 respectively in primitive_z_cfg,primitive_xy_cfg,primitive_line_cfg？
![image](https://user-images.githubusercontent.com/5026576/102324756-3c6bd200-3fbd-11eb-8fa8-cfd53c4d4c9f.png)

Secondly, i read the code but i still  fill confused why offset center for upper_thresh(100). does it mean a infinity for centers that below the thresh。
![image](https://user-images.githubusercontent.com/5026576/102329146-fc0f5280-3fc2-11eb-90c1-db1e96970b09.png)
