### ISSUE TITLE
question about ssn 

### ISSUE THREAD

**Issue by zzyzzyzz** [open-mmlab/mmdetection3d#233]
I found that in the tasks config of ssn of nuscenes, you put traffic_cones and barrier together unlike the config of centerpoint. But the size difference between them is quite far. I trained the ssn model and the ap of traffic_cones is quite low. Futhermore, i use fpn+regnet+ssn by modify your code, and found that the ap of other classes is higher than fpn+regnet, but traffic_cones and peds is  lower. So i put the traffic_cones and peds in the same task, their ap are rise but still lower than fpn+regnet. Can you tell me why this happens?

**Comment by Tai-Wang** [comment]
The original implementation did not play with too many combinations of groups. Most of these settings are from intuition. For example, traffic cones and barriers are more likely to locate by the road while pedestrians could walk freely in a urban scene. Of course, taking consideration of the objects average size is also a good criterion/intuition to group different categories and you can feel free to have a try.

As for the performance gap in terms of these classes, first you would better to compare it with a model with comparable performance and see which class leads to the gap. Then you can also try different settings of the head (like different `shared_conv_channels` and `shared_conv_strides`) apart from different combinations of classes to achieve a better detector.

**Comment by Tai-Wang** [comment]
Feel free to reopen it if there is any further question.
