### ISSUE TITLE
Cannot duplicate the precision of pointpillars-kitti

### ISSUE THREAD

**Issue by zhangzirui1998** [open-mmlab/mmdetection3d#2353]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: linux
Python: 3.8.10 (default, Jun  4 2021, 15:09:15) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3,4,5: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu111
OpenCV: 4.6.0
MMCV: 1.6.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.28.1
MMSegmentation: 0.30.0
MMDetection3D: 1.0.0rc6+47285b3
spconv2.0: False

### Reproduces the problem - code sample

samples_per_gpu=8,
gup_num=6,
lr=0.001
optimizer = dict(type='AdamW', lr=0.001, betas=(0.95, 0.99), weight_decay=0.01)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='cyclic',
    target_ratio=(10, 0.0001),
    cyclic_times=1,
    step_ratio_up=0.4)
momentum_config = dict(
    policy='cyclic',
    target_ratio=(0.8947368421052632, 1),
    cyclic_times=1,
    step_ratio_up=0.4)

### Reproduces the problem - command or script

hv_pointpillars_secfpn_12x8_160e_kitti-3d-3class.py

### Reproduces the problem - error message

The precision of the reproduction results is very poor. All configurations are the same as the official ones. There are no changes. 
Here is my result
----------- AP11 Results ------------

Pedestrian AP11@0.50, 0.50, 0.50:
bbox AP11:66.0832, 63.0339, 59.8272
bev  AP11:58.9388, 53.3299, 49.6362
3d   AP11:53.2477, 47.5130, 43.4504
aos  AP11:47.88, 46.24, 43.70
Pedestrian AP11@0.50, 0.25, 0.25:
bbox AP11:66.0832, 63.0339, 59.8272
bev  AP11:72.5250, 69.0886, 65.3976
3d   AP11:72.5069, 68.9044, 65.1723
aos  AP11:47.88, 46.24, 43.70
Cyclist AP11@0.50, 0.50, 0.50:
bbox AP11:84.5142, 74.8130, 71.7541
bev  AP11:79.9695, 63.1024, 60.2609
3d   AP11:76.1381, 59.3260, 55.9687
aos  AP11:83.78, 72.04, 68.88
Cyclist AP11@0.50, 0.25, 0.25:
bbox AP11:84.5142, 74.8130, 71.7541
bev  AP11:84.4641, 74.0979, 71.6347
3d   AP11:84.4218, 73.9195, 71.4074
aos  AP11:83.78, 72.04, 68.88
Car AP11@0.70, 0.70, 0.70:
bbox AP11:90.5192, 89.0980, 86.0982
bev  AP11:89.0676, 85.9359, 79.0645
3d   AP11:83.9757, 75.0399, 68.0256
aos  AP11:90.37, 88.56, 85.26
Car AP11@0.70, 0.50, 0.50:
bbox AP11:90.5192, 89.0980, 86.0982
bev  AP11:90.5131, 89.7706, 88.8766
3d   AP11:90.4631, 89.5717, 88.4571
aos  AP11:90.37, 88.56, 85.26

Overall AP11@easy, moderate, hard:
bbox AP11:80.3722, 75.6483, 72.5598
bev  AP11:75.9920, 67.4561, 62.9872
3d   AP11:71.1205, 60.6263, 55.8149
aos  AP11:74.01, 68.94, 65.95

----------- AP40 Results ------------

Pedestrian AP40@0.50, 0.50, 0.50:
bbox AP40:66.2857, 62.8776, 59.1854
bev  AP40:58.7624, 52.4809, 48.1038
3d   AP40:51.7544, 45.7335, 41.0967
aos  AP40:45.21, 43.23, 40.35
Pedestrian AP40@0.50, 0.25, 0.25:
bbox AP40:66.2857, 62.8776, 59.1854
bev  AP40:73.4427, 69.7457, 66.0135
3d   AP40:73.4236, 69.4173, 65.7575
aos  AP40:45.21, 43.23, 40.35
Cyclist AP40@0.50, 0.50, 0.50:
bbox AP40:87.7452, 76.0243, 72.6091
bev  AP40:81.5958, 63.2494, 59.5692
3d   AP40:76.3567, 59.0451, 55.0979
aos  AP40:86.93, 72.81, 69.41
Cyclist AP40@0.50, 0.25, 0.25:
bbox AP40:87.7452, 76.0243, 72.6091
bev  AP40:87.9659, 75.4409, 72.0230
3d   AP40:87.8969, 75.2032, 71.7026
aos  AP40:86.93, 72.81, 69.41
Car AP40@0.70, 0.70, 0.70:
bbox AP40:95.5433, 91.7697, 87.1457
bev  AP40:91.5923, 87.5040, 83.0412
3d   AP40:86.0009, 75.1930, 70.6008
aos  AP40:95.34, 91.18, 86.28
Car AP40@0.70, 0.50, 0.50:
bbox AP40:95.5433, 91.7697, 87.1457
bev  AP40:95.6498, 94.6152, 89.9685
3d   AP40:95.5603, 92.4326, 89.6829
aos  AP40:95.34, 91.18, 86.28

Overall AP40@easy, moderate, hard:
bbox AP40:83.1914, 76.8905, 72.9800
bev  AP40:77.3168, 67.7448, 63.5714
3d   AP40:71.3706, 59.9906, 55.5985
aos  AP40:75.82, 69.07, 65.35

Here are the official results（Test results using the weight provided by the official）
AP11 Results
Pedestrian AP1100.50, 0.50， 0.50:
bbox AP11:65. 9104，61. 8758，58. 0123
bev AP11:61. 7819, 55. 6510, 52.5127
3d AP11:58.1789, 52.2210, 47.4370
aos AP11:46.72, 44.68， 41.96
Pedestrian AP11@0.50, 0.25， 0.25:
bbox AP11:65. 9104，61. 8758，58. 0123
bev AP11: 72.1812, 68. 9343, 65. 0696
3d AP11:71. 8282, 68. 6998，64. 8334
aos AP11:46.72, 44.68, 41.96
Cyclist AP1100.50, 0.50, 0.50:
bbox AP11:86. 4792, 71.0492, 68. 7422
bev AP11:84. 4330, 65. 7989，62.3530
3d AP11:82.5024， 62.1471, 60.1067
aos AP11:85.37， 68.85， 66. 19
Cyclist AP11@0.50, 0.25， 0.25:
bbox AP11:86. 4792, 71.0492, 68. 7422
bev AP11:88. 6199, 68.3525, 66. 6712
3d AP11:88. 4233, 68.2587， 66.3416
aos
AP11:85.37, 68.85， 66. 19
Car AP1100.70, 0.70， 0.70:
bbox AP11:90. 7277，89. 6505，88. 6439
bev AP11:89.8827 87 . 4276, 85. 0129 
3d AP11:87 .4465，77. 6687，75. 7997
aos AP11:90.53, 89.22, 87. 97
Car AP11G0.70, 0.50， 0.50:
bbox AP11:90. 7277，89. 6505，88. 6439
bev AP11:95.6547， 89.9730，89.3473
3d AP11:95. 6116，89.9287, 89. 2290
aos AP11:90.53, 89.22, 87.97
Overall AP11@easy, moderate, hard:
bbox AP11:81.0391，74.1918, 71. 7995 
bev AP11:78.6992, 69. 6258，66.6262
3d AP11:76.0426, 64.0123, 61.1144
aos AP11:74.21, 67.58， 65.37
AP40 Results
Pedestrian AP4000.50， 0.50， 0.50:
bbox AP40:66. 1832，61. 7881，58. 1480
bev
AP40:61.4465，55.5946， 51. 1669
3d
AP40:57.2787, 51.0122， 46. 4568
aos

AP40:44.11, 41.73, 39.16
Pedestrian AP4000.50， 0.25，0.25:
bbox AP40:66.1832， 61. 7881，58. 1480
bev AP40:72. 9945，69. 4064，65 .6549
3d
AP40:72.7771, 69.1260， 65.3567
aos AP40:44.11， 41.73， 39.16
Cyclist AP4000.50，0.50, 0.50:
bbox AP40:90. 0184，71.9174, 69.2624
bev AP40:87 .7514，66. 5930，62. 7008
3d
AP40:83.8912，62. 7914，59. 4984
aos
AP40:88.73，69.47, 66.49
cyclist AP40Q0.50, 0.25， 0.25:
bbox AP40:90. 0184，71.9174, 69.2624
bev AP40:90.5598， 69.5094， 67 .0235
3d
AP40:90.3630，69.3872, 66. 6054
aos
AP40:88.73，69.47， 66.49
Car AP40Q0. 70，0.70，0. 70:
bbox AP40:95 .9000，92.5773, 89. 8560
bev AP40:92.5827， 88.5015， 85. 7504 
3d
AP40:88.5246，79. 2690，76.3330
aos AP40:95.67， 92.09， 89.14
Car AP40Q0.70, 0.50， 0.50:
bbox AP40:95. 9000，92. 5773，89. 8560
bev AP40:97 .5574, 95.0418， 92 .3867
3d
AP40:97.5242, 94. 9216，92.1841
aos AP40:95.67， 92.09, 89.14
overall AP40Geasy, moderate, hard:
bbox AP40:84. 0339，75.4276, 72 .4221
bev AP40:80 .5935，70.2297, 66. 5394
3d
AP40:76.5648, 64.3576, 60. 7627
aos AP40:76.17, 67.76， 64.93

### Additional information

Is it caused by the difference between my GPU and the official one, or the difference between the actual training parameters and the code warehouse, or the accuracy problem caused by the different versions?
 Can the same result be reproduced in the lower version or in the same way as the version of the point-pillars training?

**Comment by JingweiZhang12** [comment]
I will check the checkpoint. Also, we strongly recommend you could use the checkpoint and test on dev-1.x branch.

**Comment by zhangzirui1998** [comment]
> I will check the precision of the checkpoint. Also, we strongly recommend you could use the checkpoint and test on dev-1.x branch.

I use the checkpoint, it really gets  the correct precision. But when I train according to the source code, the precision is reduced.
These two branches will produce different precision during training？（dev-1.x branch and 1.0.0rc6 or rc4）

**Comment by kamiLight** [comment]
I meet the same problem, i train the pointpilars with latest version on my device (4 V100* 12GPU), although the batch size is same as mmdet3d official, which is 48, and i got the lower precision

**Comment by zhangzirui1998** [comment]
> I meet the same problem, i train the pointpilars with latest version on my device (4 V100* 12 batch size), although the batch size is same as mmdet3d official, which is 48, and i got the lower precision

@kamiLight All settings have not been changed, batch size=8*6. From the training log, both grad norm and loss are different from the official. I use the same weight file(pth) as the official 80th epoch's loss to test, and the precision are also different

**Comment by JingweiZhang12** [comment]
@kamiLight @zhangzirui1998 Hi， Thanks for your feedback. The verification of training on dev-1.x is in the progress.

**Comment by JingweiZhang12** [comment]
@kamiLight @zhangzirui1998 I noticed that the checkpoint we provided is trained on a single GPU from the log.

**Comment by kamiLight** [comment]
> @kamiLight @zhangzirui1998 I noticed that the checkpoint we provided is trained on a single GPU from the log.

The provided logs  https://download.openmmlab.com/mmdetection3d/v1.0.0_models/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606.log.json and https://download.openmmlab.com/mmdetection3d/v1.0.0_models/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306.log.json show the information "GPU 0,1,2,3,4,5,6,7: A100-SXM-80GB", it seems like 8 gpus were used

**Comment by JingweiZhang12** [comment]
> > @kamiLight @zhangzirui1998 I noticed that the checkpoint we provided is trained on a single GPU from the log.
> 
> The provided logs https://download.openmmlab.com/mmdetection3d/v1.0.0_models/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606.log.json and https://download.openmmlab.com/mmdetection3d/v1.0.0_models/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306.log.json show the information "GPU 0,1,2,3,4,5,6,7: A100-SXM-80GB", it seems like 8 gpus were used
I guess it trained on a single GPU from the number of iterations.
Anyway, I re-trained using the official config in the dev-1.x branch and the results are the following:
----------- AP40 Results ------------

Pedestrian AP40@0.50, 0.50, 0.50:
bbox AP40:65.2212, 60.7966, 57.5881
bev  AP40:62.2179, 56.3467, 51.8261
3d   AP40:56.5070, 50.7956, 46.1822
aos  AP40:43.94, 41.15, 38.53
Pedestrian AP40@0.50, 0.25, 0.25:
bbox AP40:65.2212, 60.7966, 57.5881
bev  AP40:73.8229, 70.3664, 66.2146
3d   AP40:73.5644, 69.8169, 65.7539
aos  AP40:43.94, 41.15, 38.53
Cyclist AP40@0.50, 0.50, 0.50:
bbox AP40:90.0843, 74.9961, 71.7818
bev  AP40:85.8047, 67.7310, 63.5577
3d   AP40:83.0382, 63.4462, 59.8525
aos  AP40:88.65, 72.84, 69.63
Cyclist AP40@0.50, 0.25, 0.25:
bbox AP40:90.0843, 74.9961, 71.7818
bev  AP40:89.3634, 72.4565, 69.2392
3d   AP40:89.3634, 72.4560, 69.2387
aos  AP40:88.65, 72.84, 69.63
Car AP40@0.70, 0.70, 0.70:
bbox AP40:95.7652, 92.5329, 89.7995
bev  AP40:92.2972, 88.6057, 85.8373
3d   AP40:88.0528, 79.1243, 76.1093
aos  AP40:95.60, 92.09, 89.08
Car AP40@0.70, 0.50, 0.50:
bbox AP40:95.7652, 92.5329, 89.7995
bev  AP40:95.9125, 95.1358, 92.4478
3d   AP40:95.8859, 95.0267, 92.2171
aos  AP40:95.60, 92.09, 89.08

**Comment by zhangzirui1998** [comment]
> > > @kamiLight @zhangzirui1998 I noticed that the checkpoint we provided is trained on a single GPU from the log.
> > 
> > 
> > The provided logs https://download.openmmlab.com/mmdetection3d/v1.0.0_models/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606.log.json and https://download.openmmlab.com/mmdetection3d/v1.0.0_models/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20220301_150306.log.json show the information "GPU 0,1,2,3,4,5,6,7: A100-SXM-80GB", it seems like 8 gpus were used
> 
> I just guess it trained on a single GPU from the number of iterations. Anyway, I re-trained using the official config in the dev-1.x branch and the results are the following: ----------- AP40 Results ------------
> 
> Overall AP40@easy, moderate, hard: bbox AP40:83.6902, 76.1085, 73.0565 bev AP40:80.1066, 70.8945, 67.0737 3d AP40:75.8660, 64.4554, 60.7147 aos AP40:76.06, 68.69, 65.75 The precision has no problem.

ok, I will try on dev-1.x branch, but the logs above show that car log is train on 8GPU and 3class log is train on single GPU.
Can you explain why there is such a large accuracy gap in my training on the rc4 and rc6 version

**Comment by zhangzirui1998** [comment]
@JingweiZhang12  Thanks a lot, I add the plane information in kitti,  then I got the create precision
Overall AP40@easy, moderate, hard:
bbox AP40:83.2407, 75.2108, 72.3419
bev  AP40:79.0966, 69.7652, 66.0986
3d   AP40:74.3743, 63.2301, 59.1449
aos  AP40:75.64, 67.73, 65.21
but the precision still has about 1% gap than the checkpoint(official), especially in car AP40 3d hard(73.9479 than 76.3330), I wonder if this is a normal bias?
