### ISSUE TITLE
[Bug] Invalid out_path in VisualizerHooks in some cases

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#2355]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

-

### Reproduces the problem - code sample

-

### Reproduces the problem - command or script

-

### Reproduces the problem - error message

-

### Additional information

This [line](https://github.com/open-mmlab/mmdetection3d/blob/dev-1.x/mmdet3d/engine/hooks/visualization_hook.py#L164) will ha ve undefined `img_path` for datasets without images.

**Comment by JingweiZhang12** [comment]
Fixed in this PR: https://github.com/open-mmlab/mmdetection3d/pull/2342/files

**Comment by filaPro** [comment]
Got it. Will close
