### ISSUE TITLE
[Bug] multiprocessing get stuck when creating waymo gt_database

### ISSUE THREAD

**Issue by KickCellarDoor** [open-mmlab/mmdetection3d#2364]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://github.com/open-mmlab/mmdetection3d/blob/1.1/docs/en/notes/faq.md) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev)](https://github.com/open-mmlab/mmdetection3d/tree/dev) or [latest version (1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.1x branch https://github.com/open-mmlab/mmdetection3d/tree/1.1

### Environment

In https://github.com/open-mmlab/mmdetection3d/commit/b324f22cbef6172891bef7a85b45b27c51515dc2
```    
import multiprocessing
multiprocessing.set_start_method('spawn')
```
is removed. However, without spawn start method, creating waymo gt_database with multiple workers will stuck. In my case, only 4 processes are actually running when 56  workers are used. Eventually creating Waymo gt database takes about 24 days.

Add back these two lines solved the issue. (but may lead to other issues as mentioned in https://github.com/open-mmlab/mmdetection3d/pull/2143)

### Reproduces the problem - code sample

w/wo
```    
import multiprocessing
multiprocessing.set_start_method('spawn')
```
in tools/create_data.py

### Reproduces the problem - command or script

```
python tools/create_data.py waymo --root-path ./data/waymo/ --out-dir ./data/waymo/ --workers 128 --extra-tag waymo
```

### Reproduces the problem - error message

No error message, process is stuck without showing any information, but only 4 CPU cores are occupied.

### Additional information

Maybe need to change the spawn method after converting waymo to kitti format, but before creating gt database.

**Comment by KickCellarDoor** [comment]
Changing the mp start method didn't solve the issue. I am investigating other possible cause of freezing

**Comment by KickCellarDoor** [comment]
Python's built-in multiprocessing works for me, so this might be an MMEngine issue instead.

**Comment by ammaryasirnaich** [comment]
Hi, did you manage to solve this issue?  i am also having the same problem

**Comment by KickCellarDoor** [comment]
@ammaryasirnaich Please try to set set_start_method as mentioned above. If it doesn't help then you may refer to https://github.com/open-mmlab/mmdetection3d/issues/2371
