### ISSUE TITLE
Dynamic Voxelization Feature

### ISSUE THREAD

**Issue by Mengziyang-Doing** [open-mmlab/mmdetection3d#239]
Why is the information of dynamic voxelization missing in README.md？

I used the dynamic voxelization code provided here in my codebase. But when I use DynamicScatter(voxel_size, point_cloud_range,
 (mode !='max')) in pillar_enconder.py, there is a CUDA error : out of memory.(Obviously out of memory). How many GPUs do you use when using dynamic voxelization?

Is it possible to train three classes instead of just car at the same time when using dynamic voxelization？

**Comment by Tai-Wang** [comment]
You can refer to configs with dynamic voxelization [HERE](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/dynamic_voxelization) for more details. There are only very few differences compared to hard voxelization, including adjustment of voxel_layer and voxel_encoder. We use 8 GPUs with 6 samples per GPU in our experiments, which is the same as hard voxelization version.

**Comment by ZwwWayne** [comment]
The dynamic voxelization might cost many more CUDA memories when the point cloud has a large amount of points within a single voxel, e.g., more than 1k points in a pillar for nuScenes dataset. So it is possible to get OOM. We suggest you to use hard voxelization in such a case.

**Comment by HuangVictorAuto** [comment]
> The dynamic voxelization might cost many more CUDA memories when the point cloud has a large number of points within a single voxel, e.g., more than 1k points in a pillar for nuScenes dataset. So it is possible to get OOM. We suggest you use hard voxelization in such a case.

@ZwwWayne, Is dynamic voxelization much faster than hard voxelization? Do you have a tested result already?  Thanks!
