### ISSUE TITLE
Question about intensity of lidar data

### ISSUE THREAD

**Issue by yustaub** [open-mmlab/mmdetection3d#240]
Hello,
    I am curious about the attribute ‘intensity’ in 3D detection, can you share what is its use in 3D detection, I can not find how it works in training phase. Very appreciate for your reply.
Best wish.

**Comment by Tai-Wang** [comment]
It is usually regarded as one feature of point clouds. For example, points from KITTI have 4 features, x, y, z and intensity. We just process them and forward it through our framework to achieve 3D object detection. So you can find a hint [HERE] (https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/kitti-3d-3class.py#L28), which means we use 4 features of the input points. The same applies to other datasets.

It is only needed to be noted that on nuScenes we empirically find that using intensity would yield worse performance, so we remove it in our implementation. The possible reason may be that intensity value of points from different frames may be unreliable and misleading.

**Comment by yustaub** [comment]
Thanks for your quick reply. I also find that the input of training kitti network is dimension 4 (x, y, z, intensity), x, y, z can represent location, object shape, but I can not figure out what intensity represent, in other words, what is the useness in 3D detection compared to x,y,z. @Tai-Wang

**Comment by Tai-Wang** [comment]
In my view, intensity can reflect the texture and normal of object surface and also entangle the distance information implicitly. It should be a good supplement to basic location information (x, y, z).

**Comment by yustaub** [comment]
got it, thanks for your reply!!
