### ISSUE TITLE
Preparation of primary data

### ISSUE THREAD

**Issue by SMSajadi99** [open-mmlab/mmdetection3d#2418]
Hi, I am working on nuScenes data.
I will proceed with your process, but in the first part you said that:

![image](https://user-images.githubusercontent.com/69210109/230673975-d216e73b-7228-42e2-830d-33451d66e56e.png)

But when I saw the downloads section of the nuScenes site, I did not understand which file to download.

![image](https://user-images.githubusercontent.com/69210109/230674051-93664e86-bb85-4f0a-bb3f-437df3fb7428.png)

Which part should I download?

**Comment by sunjiahao1999** [comment]
Full dataset v1.0

**Comment by SMSajadi99** [comment]
Thanks a lot
