### ISSUE TITLE
How to measure the Mem (GB) of a certain model?

### ISSUE THREAD

**Issue by kamiLight** [open-mmlab/mmdetection3d#2423]
Each model gives the Mem (GB) information as follows:
![Screenshot from 2023-04-10 11-01-27](https://user-images.githubusercontent.com/46705365/230816914-90945bdb-22de-4a2e-bc0e-0c75f40c3bea.png)
I want to know how to measure the Mem (GB) of a certain model? Is there any tool or just checking with nvidia-smi?

**Comment by sunjiahao1999** [comment]
Check with `nvidia-smi` or `gpustat` when training.

**Comment by kamiLight** [comment]
> Check with `nvidia-smi` or `gpustat` when training.

The batch size is set to 1 or other value when testing the Mem?
The pointpillars model with batch size 1 will cost 3.3GB in my device, checking with nvidia-smi, but official docs shows it will cost 5.5GB as shown in the above figure, how to explain this gap?
