### ISSUE TITLE
Working with custom point cloud datasets

### ISSUE THREAD

**Issue by chakri1804** [open-mmlab/mmdetection3d#243]
I'm trying to experiment with the recently released [Pandaset](https://scale.com/open-datasets/pandaset) and study how different point cloud object detection networks interact with it. But I did not find any sort of documentation to deal with new formats of datasets. Can someone help me out with this ?

**Comment by Tai-Wang** [comment]
First, glad to know your attempts with Pandaset. PRs are really welcome if you could make some progress!

Yes, we are aware this urgent need in terms of docs about customized datasets. We will update documentation in v0.9.0 in very near future. Before official release, you can first refer to our preliminary [version](https://github.com/Tai-Wang/mmdetection3d/tree/refactor_doc/docs). Related contents can be found [here](https://github.com/Tai-Wang/mmdetection3d/blob/refactor_doc/docs/tutorials/customize_dataset.md) and [here](https://github.com/Tai-Wang/mmdetection3d/blob/refactor_doc/docs/2_new_data_model.md). Hope they can help you well!

**Comment by Tai-Wang** [comment]
Please feel free to reopen it if necessary.
