### ISSUE TITLE
In the third step of Prepare SUN RGB-D Data, KeyError: 'axis_align_matrix' appears

### ISSUE THREAD

**Issue by Lucien430** [open-mmlab/mmdetection3d#2430]
I followed the data/sunrgbd/README.md file Prepare SUN RGB-D Data, and when I reached the third step "Enter the project root directory, Generate training data by running", I entered the code "python tools/create_data.py sunrgbd" as required --root-path ./data/sunrgbd --out-dir ./data/sunrgbd --extra-tag sunrgbd", it is running normally at the beginning, and the points folder and sunrgbd_infos_train are generated under the data/sunrgbd/ folder. pkl and sunrgbd_infos_val.pkl, but KeyError: 'axis_align_matrix' appears at the end.
Here are some error codes:
val sample_idx: 5047
val sample_idx: 5048
val sample_idx: 5049
val sample_idx: 5050
sunrgbd info val file is saved to ./data/sunrgbd\sunrgbd_infos_val.pkl
./data/sunrgbd\sunrgbd_infos_train.pkl will be modified.
Warning, you may overwrite the original data ./data/sunrgbd\sunrgbd_infos_train.pkl.
Reading from input file: ./data/sunrgbd\sunrgbd_infos_train.pkl.
Start updating:
[ ] 0/5285, elapsed: 0s, ETA:Traceback (most recent call last):
   File "tools/create_data.py", line 347, in <module>
     sunrgbd_data_prep(
   File "tools/create_data.py", line 165, in sunrgbd_data_prep
     update_pkl_infos('scannet', out_dir=out_dir, pkl_path=info_train_path)
   File "d:\lucien\desktop\projects\mmdetection3d\tools\dataset_converters\update_infos_to_v2.py", line 1139, in update_pkl_infos
     update_scannet_infos(pkl_path=pkl_path, out_dir=out_dir)
   File "d:\lucien\desktop\projects\mmdetection3d\tools\dataset_converters\update_infos_to_v2.py", line 635, in update_scannet_infos
     temp_data_info['axis_align_matrix'] = anns[
KeyError: 'axis_align_matrix'

**Comment by JingweiZhang12** [comment]
Suggest you could use the latest code. I could not find this `axis_align_matrix` in the code related to SUNGRGBD conversion. https://github.com/open-mmlab/mmdetection3d/blob/main/tools/dataset_converters/update_infos_to_v2.py#L678

**Comment by Xiangxu-0103** [comment]
It will be fixed in #2332
