### ISSUE TITLE
Trying to prepare kitti dataset - error

### ISSUE THREAD

**Issue by selmadeac** [open-mmlab/mmdetection3d#244]
Hi! 
I am trying to prepare the data for the kitti dataset. After running the last command:
python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti
I receive the following error:
ModuleNotFoundError: No module named 'tools'

The folder however exists and also the *.py file is there. I am able to access it. I also tried to include the whole path and the same error appears.

What could be the problem?

**Comment by Tai-Wang** [comment]
You can try to import mmdet3d or import tools under `mmdetection3d-master` in python to validate its success first. Then please make sure you run the command under the folder `mmdetection3d-master` instead of `mmdetection3d-master/tools/`.

**Comment by Tai-Wang** [comment]
Please feel free to reopen it if you have further questions.

**Comment by selmadeac** [comment]
Thank  you! I have one last question: should the downloaded kitti data in zip format be inside the kitti folder when running the command to prepare the kitti data?

**Comment by selmadeac** [comment]
> You can try to import mmdet3d or import tools under `mmdetection3d-master` in python to validate its success first. Then please make sure you run the command under the folder `mmdetection3d-master` instead of `mmdetection3d-master/tools/`.

I tried this but still get the same error.

**Comment by selmadeac** [comment]
> You can try to import mmdet3d or import tools under `mmdetection3d-master` in python to validate its success first. Then please make sure you run the command under the folder `mmdetection3d-master` instead of `mmdetection3d-master/tools/`.
The complete error looks like this:
│Traceback (most recent call last):
                                                                    │  File "tools/create_data.py", line 4, in <module>
                                                                    │    from tools.data_converter import indoor_converter as i
                                                                    │ndoor
                                                                    │ModuleNotFoundError: No module named 'tools'

**Comment by HuangCongQing** [comment]
You can try: 
```
export PYTHONPATH=$PYTHONPATH:$PWD
```

**Comment by lacie-life** [comment]
I tried it but still error
