### ISSUE TITLE
Why the 'selected' is needed in get_ann_info() for kitti_dataset?

### ISSUE THREAD

**Issue by meng-zha** [open-mmlab/mmdetection3d#245]
Thanks for the codebase.
I'm reading the code and wondering that why we need 'selected' in get_ann_info() after 'remove_dontcare'.
 In mmdet3d/datasets/kitti_dataset.py(159):
```
annos = self.remove_dontcare(annos)
```

After that in mmdet3d/datasets/kitti_dataset.py(172~174):
```
selected = self.drop_arrays_by_name(gt_names, ['DontCare'])
gt_bboxes = gt_bboxes[selected].astype('float32')
gt_names = gt_names[selected]
```

It seems that the last code is useless.

**Comment by Tai-Wang** [comment]
Yes, it seems like redundant code. If you have primarily validate it, PRs are definitely welcome.
