### ISSUE TITLE
MVX-NET issue

### ISSUE THREAD

**Issue by lehnasamia** [open-mmlab/mmdetection3d#2450]
Hello I have some issues when I try to test and to do the demo with the MVXNet model. 
When I run the command to view the demo : python demo/multi_modality_demo.py demo/data/kitti/000008.bin demo/data/kitti/000008.png demo/data/kitti/000008.pkl configs/mvxnet/mvxnet_fpn_dv_second_secfpn_8xb2-80e_kitti-3d-3class.py checkpoints/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class_20210831_060805-83442923.pth  
I don’t understand why the bounding boxes aren’t in their place.  

And when I want to run the test : python tools/test.py configs/mvxnet/mvxnet_fpn_dv_second_secfpn_8xb2-80e_kitti-3d-3class.py checkpoints/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class_20210831_060805-83442923.pth --show --show-dir ./data/kitti/show_results 
 I have this error : KeyError: 'CityScapesMetric is already registered in metric at mmdet.evaluation.metrics.cityscapes_metric' 

This is my environment :  

sys.platform: linux 
Python: 3.9.13 (main, Aug 25 2022, 23:26:10) [GCC 11.2.0] 
CUDA available: True 
numpy_random_seed: 2147483648 
GPU 0: NVIDIA GeForce RTX 3060 Laptop GPU 
CUDA_HOME: /usr/local/cuda-11.4 
NVCC: Cuda compilation tools, release 11.4, V11.4.152 
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0 
PyTorch: 2.0.0+cu117 

PyTorch compiling details: PyTorch built with: 
  - GCC 9.3 
  - C++ Version: 201703 
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications 
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e) 
  - OpenMP 201511 (a.k.a. OpenMP 4.5) 
  - LAPACK is enabled (usually provided by MKL) 
  - NNPACK is enabled 
  - CPU capability usage: AVX2 
  - CUDA Runtime 11.7 
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86 
  - CuDNN 8.5 
  - Magma 2.6.1 
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,  

OpenCV: 4.7.0 
MMEngine: 0.7.2 
MMDetection: 3.0.0 
MMDetection3D: 1.1.0+c0c5007 
spconv2.0: True 

Thank you for your help.

**Comment by JingweiZhang12** [comment]
Indeed, the 3d boxes on the image are misalignment. The fix is in the progress. Why 'CityScapesMetric` is involved in the test of MVXNet on KITTI? Could you please provide more details?

**Comment by lehnasamia** [comment]
Thank you for your response. I've solved this problem.
But now I can't visualize the pkl file. I 've this error : 
AttributeError: 'ConfigDict' object has no attribute 'data' when I run this command python tools/misc/visualize_results.py configs/mvxnet/mvxnet_fpn_dv_second_secfpn_8xb2-80e_kitti-3d-3class.py --result /home/lehna/mmdetection3d/mvx_kitti_results/pred_instances_3d.pkl --show-dir ./works_dirs

**Comment by lehnasamia** [comment]
.

**Comment by moshanghuakia** [comment]
How did you solve the problem that the 3d detection box is not aligned on the image?

**Comment by lehnasamia** [comment]
> How did you solve the problem that the 3d detection box is not aligned on the image?

I changed the fonction inference_multi_modality_detector in the inference file like that.  
![A](https://user-images.githubusercontent.com/105779901/237032227-eda01f4d-d8fc-45e8-9896-1ff535cbd4b8.png)
