### ISSUE TITLE
No models output to work-dir during training MVXNet on kitti datasets

### ISSUE THREAD

**Issue by mynobody** [open-mmlab/mmdetection3d#2455]
Hi 
I trained the MVXNet on kitti datasets with official config file ('./configs/mvxnet/mvxnet_fpn_dv_second_secfpn_8xb2-80e_kitti-3d-3class.py'), and there was no model file /weights output to the work_dir folder, and no result file output to the pklfile_prefix folder (it was set by "--cfg-options pklfile_prefix='./work_dir/results' "). 

Can you please advise on it?

thank you.

**Comment by moshanghuakia** [comment]
In the default_runtime.py file, set interval to checkpoint to 1 to output one weight file for each epoch.

The path to this file is configs/_base_/

**Comment by mynobody** [comment]
thank you.

**Comment by szy4017** [comment]
> In the default_runtime.py file, set interval to checkpoint to 1 to output one weight file for each epoch.
> 
> The path to this file is configs/_base_/

I got the same problem that I can not get the result.pkl file.
I tested the SECOND model in the KITTI dataset.
And this is my command:
`python tools/test.py configs/second/second_hv_secfpn_8xb6-80e_kitti-3d-3class.py checkpoints/second_hv_secfpn_8xb6-80e_kitti-3d-3class.pth --cfg-options pklfile_prefix=./work_dirs/results`
I tried to set intercal to checkpoint to 1 in the default_runtime.py.
And this is my default_runtime.py:
`default_scope = 'mmdet3d'

default_hooks = dict(
    timer=dict(type='IterTimerHook'),
    logger=dict(type='LoggerHook', interval=50),
    param_scheduler=dict(type='ParamSchedulerHook'),
    checkpoint=dict(type='CheckpointHook', interval=1),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    visualization=dict(type='Det3DVisualizationHook'))

env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'),
)

log_processor = dict(type='LogProcessor', window_size=50, by_epoch=True)

log_level = 'INFO'
load_from = None
resume = False

# TODO: support auto scaling lr`
I still got the response in test log file like this:
`Converting 3D prediction to KITTI format
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 3769/3769, 851.0 task/s, elapsed: 4s, ETA:     0s
Result is saved to /tmp/tmptscyq4od/results/pred_instances_3d.pkl.
09/09 17:08:48 - mmengine - INFO - Results of pred_instances_3d:
`
and no result file output to the pklfile_prefix folder.
Can you help me?
Thank you.
