### ISSUE TITLE
how to set the tasks in the centerpoint?

### ISSUE THREAD

**Issue by kamiLight** [open-mmlab/mmdetection3d#2473]
![Screenshot from 2023-04-25 22-19-34](https://user-images.githubusercontent.com/46705365/234308007-f144635c-e366-4a7e-8daf-ce4366de1826.png)
i wonder how to assign the classes in the task, e.g. what will happen if i put the truck and barrier in the same group. Now i train the centerpoint on my custom datasets, is there any rules or suggestions to guide me to group my own classes. Thanks!

**Comment by JingweiZhang12** [comment]
@kamiLight Hi, this grouping setting on NuScenes mainly takes class balances, object sizes and shapes into consideration. Details can be seen at https://arxiv.org/pdf/1908.09492.pdf. You could follow this grouping principle on your own datasets.

**Comment by kamiLight** [comment]
> @kamiLight Hi, this grouping setting on NuScenes mainly takes class balances, object sizes and shapes into consideration. Details can be seen at https://arxiv.org/pdf/1908.09492.pdf. You could follow this grouping principle on your own datasets.

Thank you!
