### ISSUE TITLE
I want to visualize the result by using Mac

### ISSUE THREAD

**Issue by yu8ri1** [open-mmlab/mmdetection3d#2476]
hello
when I train  and test the model, the test result was successfully created in server on gpu. but I want to visualize the predicted Bounding box by using Mac , without gpu. do you know how to visualization and setup mmdetction3d on Mac ? if someone  know this , please tell me .

**Comment by sunjiahao1999** [comment]
We are not sure if open3d can run on Mac. But you can save `.obj` result and view the result on `MeshLab`

**Comment by 13717630148** [comment]
> We are not sure if open3d can run on Mac. But you can save `.obj` result and view the result on `MeshLab`

i'm running the tutorial,but i dont know hot to save as .obj format
`python demo/pcd_demo.py demo/data/kitti/000008.bin pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth --show`

**Comment by DongmingMMM** [comment]
> > We are not sure if open3d can run on Mac. But you can save `.obj` result and view the result on `MeshLab`
> 
> i'm running the tutorial,but i dont know hot to save as .obj format `python demo/pcd_demo.py demo/data/kitti/000008.bin pointpillars_hv_secfpn_8xb6-160e_kitti-3d-car.py hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20220331_134606-d42d15ed.pth --show`

Hello. Are you able to save .obj format now? I can only save .json file using out_dir command. Thank you!
