### ISSUE TITLE
Inference error using kitti pre-training model

### ISSUE THREAD

**Issue by RookieHuang** [open-mmlab/mmdetection3d#2484]
I use the pre-training kitti model and default kitti config,but get the wrong reuslt,anyone can help?
- branch:1.0 or dev-1.0
- script:python tools/test.py configs/pgd/pgd_r101_caffe_fpn_gn-head_3x4_4x_kitti-mono3d.py models/pgd_r101_caffe_fpn_gn-head_3x4_4x_kitti-mono3d_20211022_102608-8a97533b.pth --show --show-dir ./outputs
- visualization:many wrong 3D boxes in the bottom of picture
![1682589868814](https://user-images.githubusercontent.com/48719225/234831822-786cd64d-747a-459d-b321-0f5741e53c8e.jpg)

**Comment by JingweiZhang12** [comment]
This is not an error. If you want to better demo, you can set `--score-thr` to filter some redundant boxes.

**Comment by RookieHuang** [comment]
Thanks for your reply!
But there is no `--score-thr` in `test.py`.
Should I use the `mono_det_demo.py` to inference?

**Comment by JingweiZhang12** [comment]
@JingweiZhang12 https://github.com/open-mmlab/mmdetection3d/blob/dev-1.x/tools/test.py#L32， we have updated the test.py. You could pull the latest code of dev-1.x

**Comment by RookieHuang** [comment]
> 

Thanks.According to your suggestion.I pull the latest code of dev-1.x and use the test.py, but I found some new problems:
1.Even if I specify `--score-thr=1`,there is still a lot wrong 3D boxes as before.When I change score-thre to 10,it looks normal.
2.Some simple samples of cars were misdetected into other categories.
![1682652460096](https://user-images.githubusercontent.com/48719225/235047482-13a85c57-a60b-4630-87b4-802ac5c67f7d.jpg)
- branch:dev-1.x
- config:/pgd_r101-caffe_fpn_head-gn_4xb3-4x_kitti-mono3d.py
- checkpoint:pgd_r101_caffe_fpn_gn-head_3x4_4x_kitti-mono3d_20211022_102608-8a97533b.pth
- score-thr:10
- script:python tools/test.py configs/pgd/pgd_r101-caffe_fpn_head-gn_4xb3-4x_kitti-mono3d.py models/pgd_r101_caffe_fpn_gn-head_3x4_4x_kitti-mono3d_20211022_102608-8a97533b.pth --show --show-dir ./outputs --score-thr 10 --task mono_det

**Comment by JingweiZhang12** [comment]
PGD is special and its prediction score is not among (0, 1). Details can be seen in the code.

**Comment by RookieHuang** [comment]
Ok.Thanks!

**Comment by turtlemicro** [comment]
I have a similar issue. I am running inference on my own data with the pretrained models for KITTI and nuScenes. Thank you for your work btw. For the pretrained model on nuScenes the results are pretty good, but for the model trained on KITTI I have to set a very high threshold to filter those boxes ocurring in the bottom of the image. So should I just accept the fact, that the model is not that good or is there a workaround?
I only have one GPU, could this be a problem?
I am doing inference with the mono_det_demo.py and change input image and .pkl-file with my own projection matrix.
Thanks in advance!
