### ISSUE TITLE
ModuleNotFoundError: No module named 'mmengine'

### ISSUE THREAD

**Issue by xiaomonv111** [open-mmlab/mmdetection3d#2489]
How to solve,thank you
I download dev-1.0
I wanted to debug in vscode and it works in pycharm but vscode is having problems with the single step

**Comment by Xiangxu-0103** [comment]
Have you installed `mmengine` correctly?

**Comment by xiaomonv111** [comment]
no ,thank you

**Comment by Merealtea** [comment]
> no ,thank you



> Have you installed `mmengine` correctly?

Does anywhere show that we need to install mmengine in https://github.com/open-mmlab/mmdetection3d/blob/1.0/docs/en/getting_started.md ?
