### ISSUE TITLE
Compile error for v0.17.3

### ISSUE THREAD

**Issue by SFrav** [open-mmlab/mmdetection3d#2494]
I am currently trying to install MMDetection3D following the steps set out to run [this package](https://github.com/Mrmoore98/VectorMapNet_code/blob/mian/env.md). Unfortunately I encountered a few issues while building the package from source. I've managed to work through most of the issues. Now the build process fails with the following error message:

`/root/anaconda3/envs/compiler_compat/ld: cannot find /root/mmdetection3d-0.17.3/build/temp.linux-x86_64-cpython-38/mmdet3d/ops/spconv/src/reordering_cuda.o: No such file or directory`

I have already checked that the CUDA_HOME and LD_LIBRARY_PATH environment variables are correctly set, and I have also verified that I have the correct version of CUDA installed (11.1). I also revised `torch/utils/cpp_extension.py` to work with the current ninja version. However, I noticed that there were some warnings during the build process about files not being found under the mmdet3d/.mim/ops directory:
```
warning: no files found matching '*.cpp' under directory 'mmdet3d/.mim/ops'
warning: no files found matching '*.cu' under directory 'mmdet3d/.mim/ops'
warning: no files found matching '*.h' under directory 'mmdet3d/.mim/ops'
warning: no files found matching '*.cc' under directory 'mmdet3d/.mim/ops'
```

Could this be related to the error message that I am seeing? If not, could you please advise me on how to troubleshoot this issue?

**Comment by ShaneCan** [comment]
same, have you solved it??

**Comment by SFrav** [comment]
> same, have you solved it??

Yes. I'll dig through my notes and post some suggestions. 
We didn't end up using this as there were issues down stream

**Comment by ShaneCan** [comment]
> > same, have you solved it??
> 
> Yes. I'll dig through my notes and post some suggestions. We didn't end up using this as there were issues down stream

thx, im looking forward to ur suggestion! really apreciate that!!!
