### ISSUE TITLE
中文文档 demo 无法执行

### ISSUE THREAD

**Issue by dailing57** [open-mmlab/mmdetection3d#2496]
`python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth`
报错：`FileNotFoundError: file "/mmdetection3d/configs/second/second_hv_secfpn_6x8_80e_kitti-3d-car.py" does not exist`

**Comment by JingweiZhang12** [comment]
Please use the dev-1.x branch.
