### ISSUE TITLE
Radar pointcloud preparation in NuScenes dataset

### ISSUE THREAD

**Issue by coolcat647** [open-mmlab/mmdetection3d#250]
Hi, thank you for the great codebase.
I am trying to implement radar-camera fusion for object detection.
I want to know if minimal modification is required to collect N-sweeps of radar pointcloud instead of  lidar pointcloud?
One possible way I guessed is from [nuscenes_converter.py#line206](https://github.com/open-mmlab/mmdetection3d/blob/dd74422e1455a6005c75ab73e08a11a8f4f22b92/tools/data_converter/nuscenes_converter.py#L206) and [points loading process](https://github.com/open-mmlab/mmdetection3d/blob/dd74422e1455a6005c75ab73e08a11a8f4f22b92/mmdet3d/datasets/pipelines/loading.py#L332). 
But it seems that I need to deal with the data dimension problem from the difference between lidar pointcloud and radar pointcloud.
Could you give me any hints?

**Comment by coolcat647** [comment]
**[update]**
After following the tutorial for custom data pipeline, I added my radar pointcloud loading module with N-sweeps data collection.
Note that the radar data collection method is from NuScenes official API which provides 18-dims data for a radar point.
I just regarded the radar points as LiDARPoints currently, hope it will be OK...
```python
sample_instance = self.nusc.get('sample', results['sample_idx'])
radar_pointcloud, timestamps_list = RadarPointCloud.from_file_multisweep(self.nusc, sample_instance, chan="RADAR_FRONT", ref_chan="LIDAR_TOP", nsweeps=self.sweeps_num)
# Nuscene official accumulated pointcloud -> mmdet3d LiDARPoints
points = mmdet3d.core.points.LiDARPoints(tensor=torch.from_numpy(radar_pointcloud.points.transpose()), points_dim=self.load_dim)
```
I will keep going and close the issue later if it goes well.

**Comment by Tai-Wang** [comment]
Hi, glad to know your attempts to incorporate radar information. I do not play much with radar points, but I could share some basic experience about it.
1. Typically radar points do not have accurate height information, so we often set it to 0. They are usually used in the bird view where height information is not necessary.

**Comment by Jacky-gsq** [comment]
@coolcat647 
Hi, have you worked out the radar data stream processing? Could you provide more details about that?
I will be very appreciative if you can do me a favor.

**Comment by Jacky-gsq** [comment]
Thanks a lot! Best wishes!
