### ISSUE TITLE
[bug] AssertionError: `use_ground_plane` is True but find plane is None

### ISSUE THREAD

**Issue by Raiden-cn** [open-mmlab/mmdetection3d#2506]
**Describe the bug**
in raw version about kitti model, after run 'python tools/train.py configs/pv_rcnn/pv_rcnn_8xb2-80e_kitti-3d-3class.py --work-dir works_dir/debug', show the following:
AssertionError: `use_ground_plane` is True but find plane is None.
But I already prepare planes files in training floder. 
![image](https://user-images.githubusercontent.com/82763858/236683137-16925305-6617-477e-850c-6e14f55de28c.png)

**Comment by Xiangxu-0103** [comment]
Whether your annotation files have 'plane' information? You can use the annotation file we provided to have a try. 

More details can be found here: https://github.com/open-mmlab/mmdetection3d/blob/dev-1.x/docs/en/user_guides/dataset_prepare.md#summary-of-annotation-files

**Comment by Raiden-cn** [comment]
I forget add '--with-plane' in when 'python tools/create_data.py'. The docs of you mentioned should be updated. 'python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti --only-gt-databse' will occure 'error: unrecognized arguments: --only-gt-databse'

**Comment by Xiangxu-0103** [comment]
Can you create a PR to help us update the docs?

**Comment by Raiden-cn** [comment]
Sure! I`ll do it soon.

**Comment by HXB-1997** [comment]
how to download this kitti plane?

**Comment by Xiangxu-0103** [comment]
@HXB-1997 You can download the road planes [here](https://download.openmmlab.com/mmdetection3d/data/train_planes.zip).

**Comment by HXB-1997** [comment]
> @HXB-1997 You can download the road planes [here](https://download.openmmlab.com/mmdetection3d/data/train_planes.zip).

thanks
