### ISSUE TITLE
Is it necessary to install waymo-open-dataset-tf-2-6-0?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmdetection3d#2519]
Hello, authors!
Thank you for your amazing jobs!
Is it necessary to install waymo-open-dataset-tf-2-6-0 (in requirements/optional.txt)?
Because when I install TF2.6.0, my PyTorch(PyTorch1.12.0+cuda11.3+cudnn8.2.1+ubuntu18.04) can't work and the environment is destroyed. 
If I didn't use the waymo-open-dataset format(for example, I use KITTI format), can I give it up(waymo-open-dataset-tf-2-6-0)? And installing waymo-open-dataset-tf-2-6-0 is only for the format of waymo-open-dataset?
Thank you !

**Comment by JingweiZhang12** [comment]
If you do not use waymo datasets, you don't need to install waymo-open-dataset-tf-2-6-0.

**Comment by zhongqiu1245** [comment]
Thx！
