### ISSUE TITLE
BEVfusion training error

### ISSUE THREAD

**Issue by ahnz7** [open-mmlab/mmdetection3d#2563]
During the model bevfusion training, I encountered this issue “class `NuScenesDataset` in mmdet3d/datasets/nuscenes_dataset.py: class `LoadPointsFromFile` in mmdet3d/datasets/transforms/loading.py: __init__() got an unexpected keyword argument 'reduce_beams”. Does this mean I need to modify this part of class `NuScenesDataset` myself?

**Comment by JingweiZhang12** [comment]
@ahnz7 Hi, the training of bevfusion is under review and will be merged soon. https://github.com/open-mmlab/mmdetection3d/pull/2558

**Comment by ahnz7** [comment]
Thank you very much for your reply.
