### ISSUE TITLE
How to plot a prediction (.ply file) on the rgb image?

### ISSUE THREAD

**Issue by Jaborie203** [open-mmlab/mmdetection3d#257]
I can visualize the .ply file by meshlab,  but i want to plot the .ply file on the original rgb image. can somebody can help me? thank you, very much!

I don't know how to generate a .txt result when i test with a pretrained model.

**Comment by Tai-Wang** [comment]
To plot the point cloud data on the RGB image, you need the transformation matrix from point cloud to camera coordinate and the intrinsic matrix for projection from 3D to 2D. You can refer to this [repo](https://github.com/kuixu/kitti_object_vis) for examples of similar plots.

For txt results generation on KITTI, please refer to this [section](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html#inference-with-existing-models) in our documentation.

**Comment by Tai-Wang** [comment]
Feel free reopen it if there is any further question.
