### ISSUE TITLE
argument out-dir not work

### ISSUE THREAD

**Issue by shichen-wang** [open-mmlab/mmdetection3d#2570]
demo/mono_det_demo.py demo/data/kitti/000008.png demo/data/kitti/000008.pkl configs/pgd/pgd_r101-caffe_fpn_head-gn_4xb3-4x_kitti-mono3d.py checkpoints/pgd_r101_caffe_fpn_gn-head_3x4_4x_kitti-mono3d_20211022_102608-8a97533b.pth --out-dir output
I use this command to get test result. I have already mkdir output but after run, nothing happen

this is my cmd result:
Loads checkpoint by local backend from path: checkpoints/pgd_r101_caffe_fpn_gn-head_3x4_4x_kitti-mono3d_20211022_102608-8a97533b.pth
05/29 15:49:25 - mmengine - INFO - ModulatedDeformConvPack bbox_head.cls_convs.1.conv is upgraded to version 2.
05/29 15:49:25 - mmengine - INFO - ModulatedDeformConvPack bbox_head.reg_convs.1.conv is upgraded to version 2.
05/29 15:49:26 - mmengine - WARNING - `Visualizer` backend is not initialized because save_dir is None.
C:\Users\11195\.conda\envs\torch191py38\lib\site-packages\mmengine\visualization\visualizer.py:828: UserWarning: Warning: The polygon is out of bounds, the drawn polygon may not be in the image
  warnings.warn(
C:\Users\11195\.conda\envs\torch191py38\lib\site-packages\mmengine\visualization\visualizer.py:757: UserWarning: Warning: The bbox is out of bounds, the drawn bbox may not be in the image
  warnings.warn(

**Comment by Zhanggengming-china** [comment]
I have tried many versions, but versions after 1.0 will not be saved. I don't know why

**Comment by Gaviaa** [comment]
Hello, I have encountered the same problem. Have you solved it?

**Comment by yfq512** [comment]
> Hello, I have encountered the same problem. Have you solved it?

I have the same problem, cann't vision segment 3d points result, Have you solved it?
