### ISSUE TITLE
cpu support mmdet3d==0.17.1?

### ISSUE THREAD

**Issue by ms-kumar** [open-mmlab/mmdetection3d#2575]
I install mmdet3d==0.17.1 using pip and using setup.py after git checkout this version but it is checking for cuda, this version only support cuda, it is not support support?

**Comment by Xiangxu-0103** [comment]
Some `operations` do not support cpu version, such as `spconv` etc.

**Comment by ms-kumar** [comment]
with cpu i'm not able to install it, it is getting failed while installing it. Look like with gpu I can' even use?
