### ISSUE TITLE
Mvx-Net config for nuscenes

### ISSUE THREAD

**Issue by SimonDoll** [open-mmlab/mmdetection3d#261]
**Motivation**
It would be great to have an example of multi modality models for nuscenes e.g. Mvx-Net wich at the moment is  available for kitti only.
Can You provide a config for Mvx-Net that is adapted to nuscenes?

**Related resources**
The nuscenes leaderboard features a method called MoCa by @Tai-Wang and @ZwwWayne, described in "Multi-Modality Cut and Paste for 3D Object Detection".
It would be awesome to get a config file for this method as well.

Keep up Your amazing work!

**Comment by ZwwWayne** [comment]
Please stay tuned. We will release in this month.

**Comment by SimonDoll** [comment]
Great, looking forward to this!
Will reopen the issue if needed when its released
