### ISSUE TITLE
Is there any util function to conver 3D feature to BEV ?

### ISSUE THREAD

**Issue by ammaryasirnaich** [open-mmlab/mmdetection3d#2612]
### What is the feature?

Hi, I can anyone guide me on where to find the utility function to convert 3D voxel feature to BEV in this repo ?

**Comment by sunjiahao1999** [comment]
You can check the implementation of PointPillars in `mmdet3d/models/middle_encoders/pillar_scatter.py`.

**Comment by ammaryasirnaich** [comment]
> You can check the implementation of PointPillars in `mmdet3d/models/middle_encoders/pillar_scatter.py`.

Thanks @sunjiahao1999 , i will give it a try.
