### ISSUE TITLE
[Bug] wrong index usage at function _get_pad_shape in data_preprocessor.py

### ISSUE THREAD

**Issue by fengye1966** [open-mmlab/mmdetection3d#2616]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

NA

### Reproduces the problem - code sample

NA

### Reproduces the problem - command or script

NA

### Reproduces the problem - error message

NA

### Additional information

 The potential bug code is over here [https://github.com/open-mmlab/mmdetection3d/blob/d27e65aac658e8e104dbbfd6a55119704010ea79/mmdet3d/models/data_preprocessors/data_preprocessor.py#LL323C1-L323C1](https://github.com/open-mmlab/mmdetection3d/blob/d27e65aac658e8e104dbbfd6a55119704010ea79/mmdet3d/models/data_preprocessors/data_preprocessor.py#LL323C1-L323C1) . for an NCHW tensor, you're trying to get the pad shape from index[1] and [2] which are C and H respectively. This will lead to wrong calculation result and I think it should be [2] and [3]. Please kindly check it. 
Thank you!

**Comment by sunjiahao1999** [comment]
The input is List[Tensor] and the Tensor.shape is CHW (the length of List == batch_size), so this is right. Thank you for your kind checking.

**Comment by fengye1966** [comment]
Thank you  for yr kind reply!

**Comment by EricLiuhhh** [comment]
> The input is List[Tensor] and the Tensor.shape is CHW (the length of List == batch_size), so this is right. Thank you for your kind checking.

Hi, this bug is still not fixed. When process data with `pseudo_collect`, everything works. But, when process data with `default_collate`, you assert `_batch_inputs.dim()==4` which means it's a NCHW tensor and the index should be [2] and [3], not [1] and [2]. Thank you!
