### ISSUE TITLE
[Bug] Path error in tools/create_data.py

### ISSUE THREAD

**Issue by zhangzw12319** [open-mmlab/mmdetection3d#2620]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090 Ti
GPU 1: NVIDIA GeForce RTX 3060
CUDA_HOME: /home/nagisa/cuda-11.7
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
PyTorch: 1.13.1
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.14.1
OpenCV: 4.7.0
MMEngine: 0.7.4
MMDetection: 3.0.0
MMDetection3D: 1.1.1+
spconv2.0: True

### Reproduces the problem - code sample

in tools/create_data.py L74-L87
```python
nuscenes_converter.create_nuscenes_infos(
        root_path, info_prefix, version=version, max_sweeps=max_sweeps)

  if version == 'v1.0-test':
      info_test_path = osp.join(out_dir, f'{info_prefix}_infos_test.pkl')
      update_pkl_infos('nuscenes', out_dir=out_dir, pkl_path=info_test_path)
      return

  info_train_path = osp.join(out_dir, f'{info_prefix}_infos_train.pkl')
  info_val_path = osp.join(out_dir, f'{info_prefix}_infos_val.pkl')
  update_pkl_infos('nuscenes', out_dir=out_dir, pkl_path=info_train_path)
  update_pkl_infos('nuscenes', out_dir=out_dir, pkl_path=info_val_path)
  create_groundtruth_database(dataset_name, root_path, info_prefix,
                              f'{info_prefix}_infos_train.pkl')
```

### Reproduces the problem - command or script

```python
python tools/create_data.py nuscenes --root-path ./data/nuscenes/ --out-dir ./data/nuscenes/nusc_v2/ --extra-tag nuscenes
```

### Reproduces the problem - error message

This kind of info. Error located in `update_pkl_infos()` functions.
```
".pkl" files not found.
```

### Additional information

1. In  `osp.join(out_dir, f'{info_prefix}_infos_test.pkl')` , `osp.join(out_dir, f'{info_prefix}_infos_train.pkl')` and `osp.join(out_dir, f'{info_prefix}_infos_val.pkl')` , `out_dir` should be changed to root_path, since in `nuscenes_converter.create_nuscenes_infos()`, the pkl files are stored in the path with prefix `root_path`, not `out_dir`.

**Comment by zhangzw12319** [comment]
Furthermore, 
```
create_groundtruth_database(dataset_name, root_path, info_prefix,
                              f'{info_prefix}_infos_train.pkl')
```
f'{info_prefix}_infos_train.pkl' should be changed into `osp.join(out_dir, f'{info_prefix}_infos_train.pkl')`. It should  not be assumed that users will store the pkl files into `root_path`. Especially when `out_dir` option is given in the code, it is better to seperate the data path and the pkl path, ortherwise when `root_path` and `out_dir` is not same, it will cause a series of errors and waste of users' time!

**Comment by sunjiahao1999** [comment]
There are no changes to gt_database in our version 1.1. If you want to use the new 1.1 version, the easiest way is to download our latest `infos.pkl` in [here](https://mmdetection3d.readthedocs.io/en/latest/user_guides/dataset_prepare.html#summary-of-annotation-files). We will consider your suggestion and fix it when root_path and out_dir is different, Thank you!

**Comment by zhangzw12319** [comment]
OK, thx~
