### ISSUE TITLE
[Bug] Voxelization of BEVFusion doesn't return anything

### ISSUE THREAD

**Issue by sangjinpark97** [open-mmlab/mmdetection3d#2622]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x

### Environment

sys.platform: linux
Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce GTX 1080 Ti
CUDA_HOME: /home/sangjin/anaconda3/envs/openmmlab
NVCC: Cuda compilation tools, release 11.6, V11.6.124
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.13.1
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.6
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.6, CUDNN_VERSION=8.3.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1
OpenCV: 4.7.0
MMEngine: 0.7.3
MMDetection: 3.0.0
MMDetection3D: 1.1.1+d27e65a
spconv2.0: True

### Reproduces the problem - code sample

File `./projects/BEVFusion/bevfusion/bevfusion.py`, line 171, in `extract_pts_feat`
```python
def extract_pts_feat(self, batch_inputs_dict) -> torch.Tensor:
    points = batch_inputs_dict['points']
    with torch.autocast('cuda', enabled=False):
        points = [point.float() for point in points]
        feats, coords, sizes = self.voxelize(points)
        batch_size = coords[-1, 0] + 1
    x = self.pts_middle_encoder(feats, coords, batch_size)
    return x
```

### Reproduces the problem - command or script

```shell
python demo/multi_modality_demo.py \
    demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402927647951.pcd.bin \
    demo/data/nuscenes/ demo/data/nuscenes/n015-2018-07-24-11-22-45+0800.pkl \
    projects/BEVFusion/configs/bevfusion_lidar-cam_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d.py \
    projects/BEVFusion/bevfusion_lidar-cam_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d-5239b1af.pth \
    --cam-type all \
    --score-thr 0.2 \
    --show
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "tools/test.py", line 149, in <module>
    main()
  File "tools/test.py", line 145, in main
    runner.test()
  File "/home/sangjin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1767, in test
    metrics = self.test_loop.run()  # type: ignore
  File "/home/sangjin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 435, in run
    self.run_iter(idx, data_batch)
  File "/home/sangjin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/sangjin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/runner/loops.py", line 454, in run_iter
    outputs = self.runner.model.test_step(data_batch)
  File "/home/sangjin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 148, in test_step
    return self.module.test_step(data)
  File "/home/sangjin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 145, in test_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/home/sangjin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 340, in _run_forward
    results = self(**data, mode=mode)
  File "/home/sangjin/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/sangjin/3d_det/mmdetection3d/mmdet3d/models/detectors/base.py", line 86, in forward
    return self.predict(inputs, data_samples, **kwargs)
  File "/home/sangjin/3d_det/mmdetection3d/projects/BEVFusion/bevfusion/bevfusion.py", line 232, in predict
    feats = self.extract_feat(batch_inputs_dict, batch_input_metas)
  File "/home/sangjin/3d_det/mmdetection3d/projects/BEVFusion/bevfusion/bevfusion.py", line 273, in extract_feat
    pts_feature = self.extract_pts_feat(batch_inputs_dict)
  File "/home/sangjin/3d_det/mmdetection3d/projects/BEVFusion/bevfusion/bevfusion.py", line 171, in extract_pts_feat
    batch_size = coords[-1, 0] + 1
IndexError: index -1 is out of bounds for dimension 0 with size 0
```

### Additional information

Hi! Thanks for your great effort for 3D detection community !!
I've tried to run the demo of BEVFusion in `projects/`.
But, this error occurs, so I printed the output of `self.voxelize(points)` (i.e. `feats`, `coords`, `sizes`).
I got that the three variables doesn't contain anything (the tensors of size 0).
I've checked the input points tensor is correctly loaded with shape of (N, 5)
I didn't edit the any part of code. I checked the voxelization part but think it's too hard to touch that part.

Can you identify the reason of this results?

Thank you in advance!

**Comment by sunjiahao1999** [comment]
the voxelization in BEVFusion is different from common voxelization in MMDet3D, read the README.md in BEVFusion projects and install their voxelization.

**Comment by sangjinpark97** [comment]
@sunjiahao1999 Thank you for responding! What does **Installing the voxelization of BEVFusion** mean? I'm not very familiar with MMDetection3D. Sorry to bother you.

Thanks

**Comment by sunjiahao1999** [comment]
@sangjinpark97 follow projects/BEVFusion/README.md to install BEVFusion their voxelization and bev_pool. 
**Note** that the voxelization OP in the original implementation of `BEVFusion` is different from the implementation in MMCV.
run this code:
```
python projects/BEVFusion/setup.py develop
```

**Comment by sangjinpark97** [comment]
@sunjiahao1999  Thank you for your time. I already run the code you said.

What I have done so far is as follows:

```shell
git clone https://github.com/open-mmlab/mmdetection3d.git -b dev-1.x && cd mmdetection3d
pip install -v -e .
python projects/BEVFusion/setup.py develop
```

But, the same error occurs and I checked the process is performed through [this line](https://github.com/open-mmlab/mmdetection3d/blob/d27e65aac658e8e104dbbfd6a55119704010ea79/projects/BEVFusion/bevfusion/ops/voxel/voxelize.py#L144).

Thanks again for taking the time to read this.

**Comment by sangjinpark97** [comment]
I solved the problem by constructing the conda environment from scratch and downloading the `info.pkl` [here](https://github.com/open-mmlab/mmdetection3d/blob/main/docs/en/user_guides/dataset_prepare.md#summary-of-annotation-files)

Thank you!
