### ISSUE TITLE
[Docs] How to convert scannet_frames_25K datasets to the format required for training

### ISSUE THREAD

**Issue by LiQianRanOvO** [open-mmlab/mmdetection3d#2626]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

After downloading scannet_frames_25k datasets, find that its structure is different from scannet datsets. Maybe scannet_frames_25k is reduced version of scannet, so they have different structure.

"""""
The structure of scannet_frames_25k is as follow:
|--scannet_frames_25k
    |-- scene0000_00
        |-- color
        |-- depth
        |-- instance
        |-- label
        |-- pose
        |-- intrinsics_color.txt
        |-- intrinsics_depth.txt
   |-- ... ...

The structure of scannet is as follow:
|--scannet
   |-- scene0000_01
        |-- scene0000_01_vh_clean_2.ply
        |-- scene0000_01.aggregation.json
        |-- scene0001_01_vh_clean_2.0.010000.segs.json
        |-- ...
   |-- ... ...
"""""""
https://mmdetection3d.readthedocs.io/zh_CN/latest/advanced_guides/datasets/scannet.html
here, I find how to convert scannet datasets, but converting scannet_frames_25k datasets may use use another way. 
HELP HELP HELP, Thanks

**Comment by ZCMax** [comment]
ScanNet25k dataset consists of image and depth map, which is currently not supported in MMDetection3D, maybe you can refer to some other repositories which use this dataset and write a new script to convert it.

**Comment by LiQianRanOvO** [comment]
> ScanNet25k dataset consists of image and depth map, which is currently not supported in MMDetection3D, maybe you can refer to some other repositories which use this dataset and write a new script to convert it.

Yes, thanks for your helpful suggestions. Today, it's fortunate to find another dataset --- S3DIS dataset, which is currently supported in MMDetection3D and help me finish training pointnet++ model.
Thanks !!!

**Comment by LiQianRanOvO** [comment]
> ScanNet25k dataset consists of image and depth map, which is currently not supported in MMDetection3D, maybe you can refer to some other repositories which use this dataset and write a new script to convert it.
![000](https://github.com/open-mmlab/mmdetection3d/assets/75296131/e485a304-479d-4d5a-bf2a-75d0729ad5a8)So good
So good ! It's running.... Maybe it's a good start.

**Comment by LiQianRanOvO** [comment]
It's running....Thanks

**Comment by Serissa** [comment]
> > ScanNet25k dataset consists of image and depth map, which is currently not supported in MMDetection3D, maybe you can refer to some other repositories which use this dataset and write a new script to convert it.
> > ![000](https://private-user-images.githubusercontent.com/75296131/250013867-e485a304-479d-4d5a-bf2a-75d0729ad5a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTI5NjksIm5iZiI6MTcyMTA5MjY2OSwicGF0aCI6Ii83NTI5NjEzMS8yNTAwMTM4NjctZTQ4NWEzMDQtNDc5ZC00ZDVhLWJmMmEtNzVkMDcyOWFkNWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDAxMTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNjNkMGY4NDBmYzNlNThmMGM5YTMxZGI2N2QzM2UzNjRiZjhhY2NmN2I5NTYyMGY3NDk1OGRlODllNWU4MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0RC1FIEDFOd1ZeJnUjMZffOBgZ6pCTIN45hiKq9w8ZY)So good
> > So good ! It's running.... Maybe it's a good start.

Are you an instance segmentation model for training?
