### ISSUE TITLE
[Bug] pcd_seg_demo assert error

### ISSUE THREAD

**Issue by completezealous** [open-mmlab/mmdetection3d#2628]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

(mmdet3d) lk@sun:~/mmdetection3d$ python mmdet3d/utils/collect_env.py
sys.platform: linux
Python: 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00) [GCC 11.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA GeForce RTX 3060
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.58
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0+cu111
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu111
OpenCV: 4.8.0
MMEngine: 0.8.0
MMDetection: 3.0.0
MMDetection3D: 1.1.1+d27e65a
spconv2.0: True

### Reproduces the problem - code sample

  def transform(self, results: dict) -> dict:
        """Call function to map original semantic class to valid category ids.

        Args:
            results (dict): Result dict containing point semantic masks.

        Returns:
            dict: The result dict containing the mapped category ids.
            Updated key and value are described below.

                - pts_semantic_mask (np.ndarray): Mapped semantic masks.
        """
        assert 'pts_semantic_mask' in results
        pts_semantic_mask = results['pts_semantic_mask']

        assert 'seg_label_mapping' in results
        label_mapping = results['seg_label_mapping']
        converted_pts_sem_mask = label_mapping[pts_semantic_mask]

        results['pts_semantic_mask'] = converted_pts_sem_mask

### Reproduces the problem - command or script

Loads checkpoint by local backend from path: checkpoints/cylinder3d_8xb2-laser-polar-semantickitti.pth
07/04 11:49:06 - mmengine - WARNING - `Visualizer` backend is not initialized because save_dir is None.
Traceback (most recent call last):
  File "demo/pcd_seg_demo.py", line 55, in <module>
    main(args)
  File "demo/pcd_seg_demo.py", line 38, in main
    result, data = inference_segmentor(model, args.pcd)
  File "/home/lk/mmdetection3d/mmdet3d/apis/inference.py", line 403, in inference_segmentor
    data_ = test_pipeline(data_)
  File "/home/lk/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 58, in __call__
    data = t(data)
  File "/home/lk/anaconda3/envs/mmdet3d/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/lk/mmdetection3d/mmdet3d/datasets/transforms/loading.py", line 489, in transform
    assert 'pts_semantic_mask' in results
AssertionError

### Reproduces the problem - error message

 python demo/pcd_seg_demo.py demo/data/000004.bin configs/cylinder3d/cylinder3d_8xb2-laser-polar-mix-3x_semantickitti.py checkpoints/cylinder3d_8xb2-laser-polar-semantickitti.pth

### Additional information

用的semantickitti一张点云  通过pcd_seg_demo.py测试

**Comment by szy4017** [comment]
我也遇到了相同的问题，请问你找到解决方案了么？
I have encountered the same problem as you. Have found the an useful solution now?

**Comment by completezealous** [comment]
> 我也遇到了相同的问题，请问你找到解决方案了么？ I have encountered the same problem as you. Have found the an useful solution now?

没有捏 但是去训练点云语义分割模型是没问题的 包括测试可视化。 Not solved but there is no problem to train the point cloud semantic segmentation model including test visualization

**Comment by szy4017** [comment]
> > 我也遇到了相同的问题，请问你找到解决方案了么？ I have encountered the same problem as you. Have found the an useful solution now?
> 
> 没有捏 但是去训练点云语义分割模型是没问题的 包括测试可视化。 Not solved but there is no problem to train the point cloud semantic segmentation model including test visualization

我刚刚试了一下test是OK的，你知道有什么其他办法可以拿到点云分割结果的标签么？
I tried the test.py in point segmentation task, which worked. Do you know any other method to get the result of point segmentation?

**Comment by sunjiahao1999** [comment]
We not provide the semantic label for kitti `000004.bin`. We will consider add a demo for semanticKITTI in next version. Thank you for reminding this problem.

**Comment by GODBENGAY** [comment]
> > 我也遇到了相同的问题，请问你找到解决方案了么？ I have encountered the same problem as you. Have found the an useful solution now?
> 
> 没有捏 但是去训练点云语义分割模型是没问题的 包括测试可视化。 Not solved but there is no problem to train the point cloud semantic segmentation model including test visualization

你好 我想问一下你的训练和测试可视化是怎么做的啊，我这里一直测试失败，没法可视化带有3D检测框的点云

**Comment by completezealous** [comment]
> > > 我也遇到了相同的问题，请问你找到解决方案了么？ I have encountered the same problem as you. Have found the an useful solution now?
> > 
> > 
> > 没有捏 但是去训练点云语义分割模型是没问题的 包括测试可视化。 Not solved but there is no problem to train the point cloud semantic segmentation model including test visualization
> 
> 你好 我想问一下你的训练和测试可视化是怎么做的啊，我这里一直测试失败，没法可视化带有3D检测框的点云

抱歉，现在才看到消息，你之前发的消息被邮箱归到垃圾箱了，我只尝试了点云语义分割的可视化，带有3d检测框的点云没有用过。

**Comment by completezealous** [comment]
> > > 我也遇到了相同的问题，请问你找到解决方案了么？ I have encountered the same problem as you. Have found the an useful solution now?
> > 
> > 
> > 没有捏 但是去训练点云语义分割模型是没问题的 包括测试可视化。 Not solved but there is no problem to train the point cloud semantic segmentation model including test visualization
> 
> 你好 我想问一下你的训练和测试可视化是怎么做的啊，我这里一直测试失败，没法可视化带有3D检测框的点云

抱歉，现在才看到消息，你之前发的消息被邮箱归到垃圾箱了，我只尝试了点云语义分割的可视化，带有3d检测框的点云没有用过。

**Comment by zhoujixiang** [comment]
> > > 我也遇到了相同的问题，请问你找到解决方案了么？ I have encountered the same problem as you. Have found the an useful solution now?
> > 
> > 
> > 没有捏 但是去训练点云语义分割模型是没问题的 包括测试可视化。 Not solved but there is no problem to train the point cloud semantic segmentation model including test visualization
> 
> 我刚刚试了一下test是OK的，你知道有什么其他办法可以拿到点云分割结果的标签么？ I tried the test.py in point segmentation task, which worked. Do you know any other method to get the result of point segmentation?
how do you save prediction files?
