### ISSUE TITLE
[Feature]  Stop training with runner

### ISSUE THREAD

**Issue by enesdorukadastec** [open-mmlab/mmdetection3d#2646]
### What is the feature?

Hi, I write a hook and I have to add a stop training statement, but I want this with mmcv. How can I do?

I added           

 runner._max_epochs = runner._epoch

is it true or is there any function about it?

**Comment by Xiangxu-0103** [comment]
We have supported `EarlyStopHook` in mmengine, you may use it to stop straining.

**Comment by enesdorukadastec** [comment]
runner.train_loop.stop_training = True
