### ISSUE TITLE
When I create nuscenes dataset, the error is FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by lyy-web** [open-mmlab/mmdetection3d#2674]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

sys.platform: win32
Python: 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:01:59) [MSC v.1929 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce GTX 960M
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
NVCC: Cuda compilation tools, release 11.6, V11.6.55
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.34.31937 版
GCC: n/a
PyTorch: 1.12.1+cu113
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;ar
ch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.e
xe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO
 -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TO
RCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,
USE_ROCM=OFF,

TorchVision: 0.13.1+cu113
OpenCV: 4.8.0
MMEngine: 0.8.2
MMDetection: 3.1.0
MMDetection3D: 1.2.0+
spconv2.0: False

### Reproduces the problem - code sample

python tools/create_data.py nuscenes --root-path ./data/nuscenes --version v1.0-mini --out-dir ./data/nuscenes --extra-tag nuscenes

### Reproduces the problem - command or script

python tools/create_data.py nuscenes --root-path ./data/nuscenes --version v1.0-mini --out-dir ./data/nuscenes --extra-tag nuscenes

### Reproduces the problem - error message

======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 0.985 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.2 seconds.
======
total scene num: 10
exist scene num: 10
train scene: 8, val scene: 2
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 404/404, 7.6 task/s, elapsed: 53s, ETA:     0s
train sample: 323, val sample: 81
./data/nuscenes\nuscenes_infos_train.pkl will be modified.
Warning, you may overwriting the original data ./data/nuscenes\nuscenes_infos_train.pkl.
Reading from input file: ./data/nuscenes\nuscenes_infos_train.pkl.
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 1.078 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.2 seconds.
======
Start updating:
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 323/323, 5.0 task/s, elapsed: 64s, ETA:     0s
Writing to output file: ./data/nuscenes\nuscenes_infos_train.pkl.
ignore classes: set()
./data/nuscenes\nuscenes_infos_val.pkl will be modified.
Warning, you may overwriting the original data ./data/nuscenes\nuscenes_infos_val.pkl.
Reading from input file: ./data/nuscenes\nuscenes_infos_val.pkl.
======
Loading NuScenes tables for version v1.0-mini...
23 category,
8 attribute,
4 visibility,
911 instance,
12 sensor,
120 calibrated_sensor,
31206 ego_pose,
8 log,
10 scene,
404 sample,
31206 sample_data,
18538 sample_annotation,
4 map,
Done loading in 1.170 seconds.
======
Reverse indexing ...
Done reverse indexing in 0.2 seconds.
======
Start updating:
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 81/81, 3.9 task/s, elapsed: 21s, ETA:     0s
Writing to output file: ./data/nuscenes\nuscenes_infos_val.pkl.
ignore classes: set()
Create GT Database of NuScenesDataset
07/28 17:04:04 - mmengine - INFO - ------------------------------
07/28 17:04:04 - mmengine - INFO - The length of the dataset: 323
07/28 17:04:04 - mmengine - INFO - The number of instances per category in the dataset:
+----------------------+--------+
| category             | number |
+----------------------+--------+
| car                  | 5051   |
| truck                | 525    |
| trailer              | 60     |
| bus                  | 369    |
| construction_vehicle | 196    |
| bicycle              | 191    |
| motorcycle           | 212    |
| pedestrian           | 3657   |
| traffic_cone         | 1339   |
| barrier              | 2323   |
+----------------------+--------+
[                                                  ] 1/323, 0.7 task/s, elapsed: 1s, ETA:   458sTraceback (most recent call last):
  File "tools/create_data.py", line 330, in <module>
    nuscenes_data_prep(
  File "tools/create_data.py", line 86, in nuscenes_data_prep
    create_groundtruth_database(dataset_name, root_path, info_prefix,
  File "h:\python_code\mmdetection3d-1.2\tools\dataset_converters\create_gt_database.py", line 241, in create_groundtruth_database
    example = dataset.pipeline(data_info)
  File "G:\python\Anaconda3\envs\mmdet3d-1.2\lib\site-packages\mmengine\dataset\base_dataset.py", line 58, in __call__
    data = t(data)
  File "G:\python\Anaconda3\envs\mmdet3d-1.2\lib\site-packages\mmcv\transforms\base.py", line 12, in __call__
    return self.transform(results)
  File "h:\python_code\mmdetection3d-1.2\mmdet3d\datasets\transforms\loading.py", line 435, in transform
    points_sweep = self._load_points(
  File "h:\python_code\mmdetection3d-1.2\mmdet3d\datasets\transforms\loading.py", line 364, in _load_points
    pts_bytes = get(pts_filename, backend_args=self.backend_args)
  File "G:\python\Anaconda3\envs\mmdet3d-1.2\lib\site-packages\mmengine\fileio\io.py", line 181, in get
    return backend.get(filepath)
  File "G:\python\Anaconda3\envs\mmdet3d-1.2\lib\site-packages\mmengine\fileio\backends\local_backend.py", line 33, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/nuscenes\\sweeps/LIDAR_TOP\\sweeps/LIDAR_TOP/n015-2018-07-24-11-22-45+0800__LIDAR_TOP__1532402928047779.pcd.bin'

### Additional information

Obviously, can't find the cause of the path is "sweeps/LIDAR_TOP \ \" appeared two times, maybe the correct path should be ". / data/nuscenes sweeps/LIDAR_TOP/xxx. pcd. bin"

**Comment by Chenjiayu20220326** [comment]
Has it been solved? I have also encountered this problem

**Comment by Lcl159** [comment]
Has it been solved? I have also encountered this problem

**Comment by xtk8532704** [comment]
Has it been solved? I have also encountered this problem

**Comment by xtk8532704** [comment]
Hi, I figured out this problem was caused by the difference of os.sep between Linux and Windows. You can check #2770
