### ISSUE TITLE
[Feature] Is there any plan to support dataset Argoverse 2 ?

### ISSUE THREAD

**Issue by zzj403** [open-mmlab/mmdetection3d#2680]
### What is the feature?

Is there any plan to support the dataset Argoverse 2 ? Since it's also an amazing dataset including more long-range annonations.
Its api is in [https://github.com/argoverse/av2-api](url) and its homepage is in [https://www.argoverse.org/av2.html](url)

**Comment by sunjiahao1999** [comment]
We have no plans to support it in the near future, but we welcome PRs for Argoverse 2 and related benchmarks!

**Comment by TheCodez** [comment]
This repo has an implementation for Argoverse2 in mmdetection3d: https://github.com/neeharperi/LT3D
Would be nice to have it in the official repo.

**Comment by zzj403** [comment]
Thanks for all your comments! I close this issue.
