### ISSUE TITLE
[Docs] Kitti Dataset Preparation Error: No module found

### ISSUE THREAD

**Issue by NIHALNAVALE** [open-mmlab/mmdetection3d#2693]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

Help I am stuck on this,

Command Run:
python3 tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti

Error:
Traceback (most recent call last):
  File "tools/create_data.py", line 8, in <module>
    from tools.dataset_converters import indoor_converter as indoor
ModuleNotFoundError: No module named 'tools.dataset_converters'

I am using VSCode, and my pylance json file has the following:
    "python.analysis.extraPaths": [
        "/usr/local/lib/python3.8/site-packages",
        "/home/usr/local/lib/python3.8/site-packages/",
        "/home/nihal/miniconda3/envs/mmdet3d/bin"
    ],

**Comment by NIHALNAVALE** [comment]
Resolved, changed the import module directories

**Comment by syd-21** [comment]
> Resolved, changed the import module directories

how do you slove this error   

"tools/create_data.py", line 5, in <module>
    from tools.dataset_converters import indoor_converter as indoor
ModuleNotFoundError: No module named 'tools.dataset_converters'

**Comment by bertaveira** [comment]
I am also struggling here. Seems like either we are missing something or the documentation is outdated. `tools` is not a python package, and is not sinatlled when we do the pip install -e to install mmdet3d.

Are we missing something?

**Comment by muyanqaq** [comment]
> 已解决，更改导入模块目录

how to do

**Comment by WaterHyacinthInNANHU** [comment]
> I am also struggling here. Seems like either we are missing something or the documentation is outdated. `tools` is not a python package, and is not sinatlled when we do the pip install -e to install mmdet3d.
> 
> Are we missing something?

Try `export PYTHONPATH=$PYTHONPATH:$PWD` before running the script as stated in [huang's answer](https://github.com/open-mmlab/mmdetection3d/issues/244#issuecomment-1339220622). For details refer to [here](https://stackoverflow.com/a/2326045).
