### ISSUE TITLE
Invalid link for creating a custom dataset

### ISSUE THREAD

**Issue by EricWiener** [open-mmlab/mmdetection3d#270]
Thanks so much for making this library available! I was trying to figure out how to create a custom dataset and was looking through the documentation. On the dataset preparation page (https://mmdetection3d.readthedocs.io/en/latest/data_preparation.html), there is a link to a document about using a custom dataset:

```
Customized Datasets
For using custom datasets, please refer to Tutorials 2: Customize Datasets.
```

But the link to "Tutorials 2: Customize Datasets" is invalid.

**Comment by EricWiener** [comment]
I believe the correct link should be https://mmdetection3d.readthedocs.io/en/latest/tutorials/customize_dataset.html

**Comment by Tai-Wang** [comment]
Thanks for your reminding. I will fix it and other links with a PR.
