### ISSUE TITLE
Difference between original repo and here in BEVFusion

### ISSUE THREAD

**Issue by sangjinpark97** [open-mmlab/mmdetection3d#2716]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

-

### Reproduces the problem - code sample

-

### Reproduces the problem - command or script

-

### Reproduces the problem - error message

-

### Additional information

Hi,

I've successfully trained the BEVFusion on the KITTI dataset using mmdetection3d (this repo).
I got the reasonable performances of LiDAR-only and fusion models.

And I tried to train the same model in [original repo of BEVFusion](https://github.com/mit-han-lab/bevfusion).
However, the performance of the fusion model was lower than the LiDAR-only model. So I'm, trying to identify the reason.

While doing so, I found a difference between this repo and the origin repo which is `self.prediction heads` of `TransFusionHead` in `transfusion.py`.

In this repo, `self.prediction_heads` contains `SeparateHead` ([here](https://github.com/open-mmlab/mmdetection3d/blob/0f9dfa97a35ef87e16b700742d3c358d0ad15452/projects/BEVFusion/bevfusion/transfusion_head.py#L143)), on the other hand, in the origin repo, they use the `FFN` as the prediction heads ([here](https://github.com/mit-han-lab/bevfusion/blob/601961a903c46d14ece4606b8acfe86e604499df/mmdet3d/models/heads/bbox/transfusion.py#L153)).

Can I know why you modified this part and whether it can be the reason for performance degradation in my case?

**Comment by liyih** [comment]
Hi, have you found the reason for the performance degradation?

**Comment by sangjinpark97** [comment]
@liyih I have not figured out the reason yet. I'm using the model trained on this repository (mmdetection3d).

If you find something about it, I'll appreciate it if you share what you got. Thank you

**Comment by sangjinpark97** [comment]
@Lime2333 Hi, I cannot share the code details now because I wrote it with the company's support.
I cannot memorize the procedure to edit the code perfectly, but the required changes are as follows.

- Remove velocity in the point head.
- Image dataloader (5 or 6 images in nuScenes; `Bx5xCxHxW`, 1 image in KITTI `Bx1xCxHxW`)
- Calibration parameter (e.g. `lidar2image` used in BEVFusion): you need to modify the codes to load the calibration parameter of KITTI so that they are loaded in the same manner as BEVFusion.

* Closed because I'm not focusing on this issue anymore.

**Comment by Lime2333** [comment]
@sangjinpark97 thanks！

**Comment by PaulBigiel** [comment]
@Lime2333 Have you got it to work with the KITTI format? Could you maybe share your code?
