### ISSUE TITLE
Load pretrained model

### ISSUE THREAD

**Issue by alexa19lab** [open-mmlab/mmdetection3d#274]
When I try to train multi-modality model like `dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py`, I need to load pretrained model only for image branch, like your mask-rcnn model on nuimage. And the 'backbone' term goes as 'img_backbone', so I can't simply using `load_from` term in the config file. So how do I load the pretrained model when the term changes? Thanks in advance for your help!

**Comment by ZwwWayne** [comment]
You need to write a script to convert the keys of model.

**Comment by alexa19lab** [comment]
Thanks for replying! I tried and solved this problem!
