### ISSUE TITLE
[Bug] Bevfusion: missing keys in source state_dict (the pretrain parameters in the image backbone are not loaded )

### ISSUE THREAD

**Issue by liyih** [open-mmlab/mmdetection3d#2746]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

absl-py                 1.4.0
addict                  2.4.0
aliyun-python-sdk-core  2.13.36
aliyun-python-sdk-kms   2.16.1
ansi2html               1.8.0
anyio                   3.7.1
argon2-cffi             21.3.0
argon2-cffi-bindings    21.2.0
attrs                   23.1.0
backcall                0.2.0
beautifulsoup4          4.12.2
bev-pool                0.0.0       
black                   23.3.0
bleach                  6.0.0
cachetools              5.3.1
ccimport                0.3.7
certifi                 2022.12.7
cffi                    1.15.1
charset-normalizer      3.2.0
click                   8.1.6
colorama                0.4.6
comm                    0.1.4
ConfigArgParse          1.7
crcmod                  1.7
cryptography            41.0.3
cumm-cu111              0.2.9
cycler                  0.11.0
Cython                  3.0.0
dash                    2.11.1
dash-core-components    2.0.0
dash-html-components    2.0.0
dash-table              5.0.0
debugpy                 1.6.8
decorator               5.1.1
defusedxml              0.7.1
descartes               1.1.0
entrypoints             0.4
exceptiongroup          1.1.2
fastjsonschema          2.18.0
fire                    0.5.0
flake8                  3.9.2
Flask                   2.2.5
fonttools               4.38.0
google-auth             2.22.0
google-auth-oauthlib    0.4.6
grpcio                  1.56.2
idna                    3.4
imageio                 2.31.1
importlib-metadata      6.7.0
importlib-resources     5.12.0
iniconfig               2.0.0
ipykernel               6.16.2
ipython                 7.34.0
ipython-genutils        0.2.0
ipywidgets              8.1.0
itsdangerous            2.1.2
jedi                    0.19.0
Jinja2                  3.1.2
jmespath                0.10.0
joblib                  1.3.1
jsonschema              4.17.3
jupyter                 1.0.0
jupyter_client          7.4.9
jupyter-console         6.6.3
jupyter_core            4.12.0
jupyter-server          1.24.0
jupyterlab-pygments     0.2.2
jupyterlab-widgets      3.0.8
kiwisolver              1.4.4
lark                    1.1.7
llvmlite                0.39.1
lyft-dataset-sdk        0.0.8
Markdown                3.4.4
markdown-it-py          2.2.0
MarkupSafe              2.1.3
matplotlib              3.5.2
matplotlib-inline       0.1.6
mccabe                  0.6.1
mdurl                   0.1.2
mistune                 2.0.5
mmcv                    2.0.1
mmdet                   3.1.0      
mmdet3d                 1.2.0        
mmengine                0.8.3
model-index             0.1.11
mypy-extensions         1.0.0
nbclassic               1.0.0
nbclient                0.7.4
nbconvert               7.4.0
nbformat                5.5.0
nest-asyncio            1.5.7
networkx                2.6.3
ninja                   1.11.1
notebook                6.5.5
notebook_shim           0.2.3
numba                   0.56.4
numpy                   1.21.6
nuscenes-devkit         1.1.10
nvidia-ml-py            12.535.77
nvitop                  1.2.0
oauthlib                3.2.2
open3d                  0.16.0
opencv-python           4.8.0.74
opendatalab             0.0.10
openmim                 0.3.9
openxlab                0.0.10
ordered-set             4.1.0
oss2                    2.17.0
packaging               23.1
pandas                  1.3.5
pandocfilters           1.5.0
parso                   0.8.3
pathspec                0.11.2
pccm                    0.3.4
pexpect                 4.8.0
pickleshare             0.7.5
Pillow                  9.5.0
pip                     22.3.1
pkgutil_resolve_name    1.3.10
platformdirs            3.10.0
plotly                  5.15.0
pluggy                  1.2.0
plyfile                 0.9
portalocker             2.7.0
prometheus-client       0.17.1
prompt-toolkit          3.0.39
protobuf                3.20.3
psutil                  5.9.5
ptyprocess              0.7.0
pyasn1                  0.5.0
pyasn1-modules          0.3.0
pybind11                2.11.1
pycocotools             2.0.6
pycodestyle             2.7.0
pycparser               2.21
pycryptodome            3.18.0
pyflakes                2.3.1
Pygments                2.15.1
pyparsing               3.1.1
pyquaternion            0.9.9
pyrsistent              0.19.3
pytest                  7.4.0
python-dateutil         2.8.2
pytz                    2023.3
PyWavelets              1.3.0
PyYAML                  6.0.1
pyzmq                   24.0.1
qtconsole               5.4.3
QtPy                    2.3.1
requests                2.28.2
requests-oauthlib       1.3.1
retrying                1.3.4
rich                    13.5.2
rsa                     4.9
scikit-image            0.19.3
scikit-learn            1.0.2
scipy                   1.7.3
Send2Trash              1.8.2
setuptools              60.2.0
Shapely                 1.8.5
six                     1.16.0
sniffio                 1.3.0
soupsieve               2.4.1
spconv-cu111            2.1.25
tabulate                0.9.0
tenacity                8.2.2
tensorboard             2.11.2
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
termcolor               2.3.0
terminado               0.17.1
terminaltables          3.1.10
threadpoolctl           3.1.0
tifffile                2021.11.2
tinycss2                1.2.1
tomli                   2.0.1
torch                   1.11.0+cu113
torchvision             0.12.0+cu113
tornado                 6.2
tqdm                    4.65.0
traitlets               5.9.0
trimesh                 3.23.0
typed-ast               1.5.5
typing_extensions       4.7.1
urllib3                 1.26.16
wcwidth                 0.2.6
webencodings            0.5.1
websocket-client        1.6.1
Werkzeug                2.2.3
wheel                   0.38.4
widgetsnbextension      4.0.8
yapf                    0.40.1
zipp                    3.15.0

### Reproduces the problem - code sample

bash tools/dist_train.sh projects/BEVFusion/configs/bevfusion_lidar-cam_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d.py 8 --cfg-options load_from=${LIDAR_PRETRAINED_CHECKPOINT} model.img_backbone.init_cfg.checkpoint=${IMAGE_PRETRAINED_BACKBONE}

### Reproduces the problem - command or script

bash tools/dist_train.sh projects/BEVFusion/configs/bevfusion_lidar-cam_voxel0075_second_secfpn_8xb4-cyclic-20e_nus-3d.py 8 --cfg-options load_from=${LIDAR_PRETRAINED_CHECKPOINT} model.img_backbone.init_cfg.checkpoint=${IMAGE_PRETRAINED_BACKBONE}

### Reproduces the problem - error message

The model and loaded state dict do not match exactly

missing keys in source state_dict: img_backbone.patch_embed.projection.weight, img_backbone.patch_embed.projection.bias, img_backbone.patch_embed.norm.weight, img_backbone.patch_embed.norm.bias, img_backbone.stages.0.blocks.0.norm1.weight, img_backbone.stages.0.blocks.0.norm1.bias, img_backbone.stages.0.blocks.0.attn.w_msa.relative_position_bias_table, img_backbone.stages.0.blocks.0.attn.w_msa.relative_position_index, img_backbone.stages.0.blocks.0.attn.w_msa.qkv.weight, img_backbone.stages.0.blocks.0.attn.w_msa.qkv.bias, img_backbone.stages.0.blocks.0.attn.w_msa.proj.weight, img_backbone.stages.0.blocks.0.attn.w_msa.proj.bias, img_backbone.stages.0.blocks.0.norm2.weight, img_backbone.stages.0.blocks.0.norm2.bias, img_backbone.stages.0.blocks.0.ffn.layers.0.0.weight, img_backbone.stages.0.blocks.0.ffn.layers.0.0.bias, img_backbone.stages.0.blocks.0.ffn.layers.1.weight, img_backbone.stages.0.blocks.0.ffn.layers.1.bias, img_backbone.stages.0.blocks.1.norm1.weight, img_backbone.stages.0.blocks.1.norm1.bias, img_backbone.stages.0.blocks.1.attn.w_msa.relative_position_bias_table, img_backbone.stages.0.blocks.1.attn.w_msa.relative_position_index, img_backbone.stages.0.blocks.1.attn.w_msa.qkv.weight, img_backbone.stages.0.blocks.1.attn.w_msa.qkv.bias, img_backbone.stages.0.blocks.1.attn.w_msa.proj.weight, img_backbone.stages.0.blocks.1.attn.w_msa.proj.bias, img_backbone.stages.0.blocks.1.norm2.weight, img_backbone.stages.0.blocks.1.norm2.bias, img_backbone.stages.0.blocks.1.ffn.layers.0.0.weight, img_backbone.stages.0.blocks.1.ffn.layers.0.0.bias, img_backbone.stages.0.blocks.1.ffn.layers.1.weight, img_backbone.stages.0.blocks.1.ffn.layers.1.bias, img_backbone.stages.0.downsample.norm.weight, img_backbone.stages.0.downsample.norm.bias, img_backbone.stages.0.downsample.reduction.weight, img_backbone.stages.1.blocks.0.norm1.weight, img_backbone.stages.1.blocks.0.norm1.bias, img_backbone.stages.1.blocks.0.attn.w_msa.relative_position_bias_table, img_backbone.stages.1.blocks.0.attn.w_msa.relative_position_index, img_backbone.stages.1.blocks.0.attn.w_msa.qkv.weight, img_backbone.stages.1.blocks.0.attn.w_msa.qkv.bias, img_backbone.stages.1.blocks.0.attn.w_msa.proj.weight, img_backbone.stages.1.blocks.0.attn.w_msa.proj.bias, img_backbone.stages.1.blocks.0.norm2.weight, img_backbone.stages.1.blocks.0.norm2.bias, img_backbone.stages.1.blocks.0.ffn.layers.0.0.weight, img_backbone.stages.1.blocks.0.ffn.layers.0.0.bias, img_backbone.stages.1.blocks.0.ffn.layers.1.weight, img_backbone.stages.1.blocks.0.ffn.layers.1.bias, img_backbone.stages.1.blocks.1.norm1.weight, img_backbone.stages.1.blocks.1.norm1.bias, img_backbone.stages.1.blocks.1.attn.w_msa.relative_position_bias_table, img_backbone.stages.1.blocks.1.attn.w_msa.relative_position_index, img_backbone.stages.1.blocks.1.attn.w_msa.qkv.weight, img_backbone.stages.1.blocks.1.attn.w_msa.qkv.bias, img_backbone.stages.1.blocks.1.attn.w_msa.proj.weight, img_backbone.stages.1.blocks.1.attn.w_msa.proj.bias, img_backbone.stages.1.blocks.1.norm2.weight, img_backbone.stages.1.blocks.1.norm2.bias, img_backbone.stages.1.blocks.1.ffn.layers.0.0.weight, img_backbone.stages.1.blocks.1.ffn.layers.0.0.bias, img_backbone.stages.1.blocks.1.ffn.layers.1.weight, img_backbone.stages.1.blocks.1.ffn.layers.1.bias, img_backbone.stages.1.downsample.norm.weight, img_backbone.stages.1.downsample.norm.bias, img_backbone.stages.1.downsample.reduction.weight, img_backbone.stages.2.blocks.0.norm1.weight, img_backbone.stages.2.blocks.0.norm1.bias, img_backbone.stages.2.blocks.0.attn.w_msa.relative_position_bias_table, img_backbone.stages.2.blocks.0.attn.w_msa.relative_position_index, img_backbone.stages.2.blocks.0.attn.w_msa.qkv.weight, img_backbone.stages.2.blocks.0.attn.w_msa.qkv.bias, img_backbone.stages.2.blocks.0.attn.w_msa.proj.weight, img_backbone.stages.2.blocks.0.attn.w_msa.proj.bias, img_backbone.stages.2.blocks.0.norm2.weight, img_backbone.stages.2.blocks.0.norm2.bias, img_backbone.stages.2.blocks.0.ffn.layers.0.0.weight, img_backbone.stages.2.blocks.0.ffn.layers.0.0.bias, img_backbone.stages.2.blocks.0.ffn.layers.1.weight, img_backbone.stages.2.blocks.0.ffn.layers.1.bias, img_backbone.stages.2.blocks.1.norm1.weight, img_backbone.stages.2.blocks.1.norm1.bias, img_backbone.stages.2.blocks.1.attn.w_msa.relative_position_bias_table, img_backbone.stages.2.blocks.1.attn.w_msa.relative_position_index, img_backbone.stages.2.blocks.1.attn.w_msa.qkv.weight, img_backbone.stages.2.blocks.1.attn.w_msa.qkv.bias, img_backbone.stages.2.blocks.1.attn.w_msa.proj.weight, img_backbone.stages.2.blocks.1.attn.w_msa.proj.bias, img_backbone.stages.2.blocks.1.norm2.weight, img_backbone.stages.2.blocks.1.norm2.bias, img_backbone.stages.2.blocks.1.ffn.layers.0.0.weight, img_backbone.stages.2.blocks.1.ffn.layers.0.0.bias, img_backbone.stages.2.blocks.1.ffn.layers.1.weight, img_backbone.stages.2.blocks.1.ffn.layers.1.bias, img_backbone.stages.2.blocks.2.norm1.weight, img_backbone.stages.2.blocks.2.norm1.bias, img_backbone.stages.2.blocks.2.attn.w_msa.relative_position_bias_table, img_backbone.stages.2.blocks.2.attn.w_msa.relative_position_index, img_backbone.stages.2.blocks.2.attn.w_msa.qkv.weight, img_backbone.stages.2.blocks.2.attn.w_msa.qkv.bias, img_backbone.stages.2.blocks.2.attn.w_msa.proj.weight, img_backbone.stages.2.blocks.2.attn.w_msa.proj.bias, img_backbone.stages.2.blocks.2.norm2.weight, img_backbone.stages.2.blocks.2.norm2.bias, img_backbone.stages.2.blocks.2.ffn.layers.0.0.weight, img_backbone.stages.2.blocks.2.ffn.layers.0.0.bias, img_backbone.stages.2.blocks.2.ffn.layers.1.weight, img_backbone.stages.2.blocks.2.ffn.layers.1.bias, img_backbone.stages.2.blocks.3.norm1.weight, img_backbone.stages.2.blocks.3.norm1.bias, img_backbone.stages.2.blocks.3.attn.w_msa.relative_position_bias_table, img_backbone.stages.2.blocks.3.attn.w_msa.relative_position_index, img_backbone.stages.2.blocks.3.attn.w_msa.qkv.weight, img_backbone.stages.2.blocks.3.attn.w_msa.qkv.bias, img_backbone.stages.2.blocks.3.attn.w_msa.proj.weight, img_backbone.stages.2.blocks.3.attn.w_msa.proj.bias, img_backbone.stages.2.blocks.3.norm2.weight, img_backbone.stages.2.blocks.3.norm2.bias, img_backbone.stages.2.blocks.3.ffn.layers.0.0.weight, img_backbone.stages.2.blocks.3.ffn.layers.0.0.bias, img_backbone.stages.2.blocks.3.ffn.layers.1.weight, img_backbone.stages.2.blocks.3.ffn.layers.1.bias, img_backbone.stages.2.blocks.4.norm1.weight, img_backbone.stages.2.blocks.4.norm1.bias, img_backbone.stages.2.blocks.4.attn.w_msa.relative_position_bias_table, img_backbone.stages.2.blocks.4.attn.w_msa.relative_position_index, img_backbone.stages.2.blocks.4.attn.w_msa.qkv.weight, img_backbone.stages.2.blocks.4.attn.w_msa.qkv.bias, img_backbone.stages.2.blocks.4.attn.w_msa.proj.weight, img_backbone.stages.2.blocks.4.attn.w_msa.proj.bias, img_backbone.stages.2.blocks.4.norm2.weight, img_backbone.stages.2.blocks.4.norm2.bias, img_backbone.stages.2.blocks.4.ffn.layers.0.0.weight, img_backbone.stages.2.blocks.4.ffn.layers.0.0.bias, img_backbone.stages.2.blocks.4.ffn.layers.1.weight, img_backbone.stages.2.blocks.4.ffn.layers.1.bias, img_backbone.stages.2.blocks.5.norm1.weight, img_backbone.stages.2.blocks.5.norm1.bias, img_backbone.stages.2.blocks.5.attn.w_msa.relative_position_bias_table, img_backbone.stages.2.blocks.5.attn.w_msa.relative_position_index, img_backbone.stages.2.blocks.5.attn.w_msa.qkv.weight, img_backbone.stages.2.blocks.5.attn.w_msa.qkv.bias, img_backbone.stages.2.blocks.5.attn.w_msa.proj.weight, img_backbone.stages.2.blocks.5.attn.w_msa.proj.bias, img_backbone.stages.2.blocks.5.norm2.weight, img_backbone.stages.2.blocks.5.norm2.bias, img_backbone.stages.2.blocks.5.ffn.layers.0.0.weight, img_backbone.stages.2.blocks.5.ffn.layers.0.0.bias, img_backbone.stages.2.blocks.5.ffn.layers.1.weight, img_backbone.stages.2.blocks.5.ffn.layers.1.bias, img_backbone.stages.2.downsample.norm.weight, img_backbone.stages.2.downsample.norm.bias, img_backbone.stages.2.downsample.reduction.weight, img_backbone.stages.3.blocks.0.norm1.weight, img_backbone.stages.3.blocks.0.norm1.bias, img_backbone.stages.3.blocks.0.attn.w_msa.relative_position_bias_table, img_backbone.stages.3.blocks.0.attn.w_msa.relative_position_index, img_backbone.stages.3.blocks.0.attn.w_msa.qkv.weight, img_backbone.stages.3.blocks.0.attn.w_msa.qkv.bias, img_backbone.stages.3.blocks.0.attn.w_msa.proj.weight, img_backbone.stages.3.blocks.0.attn.w_msa.proj.bias, img_backbone.stages.3.blocks.0.norm2.weight, img_backbone.stages.3.blocks.0.norm2.bias, img_backbone.stages.3.blocks.0.ffn.layers.0.0.weight, img_backbone.stages.3.blocks.0.ffn.layers.0.0.bias, img_backbone.stages.3.blocks.0.ffn.layers.1.weight, img_backbone.stages.3.blocks.0.ffn.layers.1.bias, img_backbone.stages.3.blocks.1.norm1.weight, img_backbone.stages.3.blocks.1.norm1.bias, img_backbone.stages.3.blocks.1.attn.w_msa.relative_position_bias_table, img_backbone.stages.3.blocks.1.attn.w_msa.relative_position_index, img_backbone.stages.3.blocks.1.attn.w_msa.qkv.weight, img_backbone.stages.3.blocks.1.attn.w_msa.qkv.bias, img_backbone.stages.3.blocks.1.attn.w_msa.proj.weight, img_backbone.stages.3.blocks.1.attn.w_msa.proj.bias, img_backbone.stages.3.blocks.1.norm2.weight, img_backbone.stages.3.blocks.1.norm2.bias, img_backbone.stages.3.blocks.1.ffn.layers.0.0.weight, img_backbone.stages.3.blocks.1.ffn.layers.0.0.bias, img_backbone.stages.3.blocks.1.ffn.layers.1.weight, img_backbone.stages.3.blocks.1.ffn.layers.1.bias, img_backbone.norm1.weight, img_backbone.norm1.bias, img_backbone.norm2.weight, img_backbone.norm2.bias, img_backbone.norm3.weight, img_backbone.norm3.bias, 

### Additional information

It seems that the pretrain parameters in the image backbone are not loaded properly.
And the results I got companying with this problem is worse than the original results in the paper.
How to solve that?
Thanks.

**Comment by timwhity** [comment]
@liyih How did you solve that ? ^^
