### ISSUE TITLE
[Bug] Centerpoint training crash

### ISSUE THREAD

**Issue by enesdorukadastec** [open-mmlab/mmdetection3d#2755]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x

### Environment

addict                    2.4.0                    pypi_0    pypi
aiohttp                   3.8.5                    pypi_0    pypi
aiohttp-retry             2.8.3                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
aliyun-python-sdk-core    2.14.0                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.2                   pypi_0    pypi
amqp                      5.1.1                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.5.0            py38h06a4308_0  
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               20.1.0           py38h27cfd23_1  
asttokens                 2.0.5              pyhd3eb1b0_0  
async-timeout             4.0.2                    pypi_0    pypi
asyncssh                  2.13.2                   pypi_0    pypi
atpublic                  4.0                      pypi_0    pypi
attrs                     22.1.0           py38h06a4308_0  
backcall                  0.2.0              pyhd3eb1b0_0  
backports-zoneinfo        0.2.1                    pypi_0    pypi
beautifulsoup4            4.12.2           py38h06a4308_0  
billiard                  4.1.0                    pypi_0    pypi
black                     23.7.0                   pypi_0    pypi
blas                      1.0                         mkl  
bleach                    4.1.0              pyhd3eb1b0_0  
boto3                     1.28.23                  pypi_0    pypi
botocore                  1.31.23                  pypi_0    pypi
brotlipy                  0.7.0           py38h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.05.30           h06a4308_0  
cachetools                5.3.1                    pypi_0    pypi
celery                    5.3.1                    pypi_0    pypi
certifi                   2023.7.22        py38h06a4308_0  
cffi                      1.15.1           py38h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.6                    pypi_0    pypi
click-didyoumean          0.3.0                    pypi_0    pypi
click-plugins             1.1.1                    pypi_0    pypi
click-repl                0.3.0                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.1.2            py38h06a4308_0  
configobj                 5.0.8                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              39.0.1           py38h9ce1e76_2  
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.5.1            py38h295c915_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
descartes                 1.1.0                    pypi_0    pypi
dictdiffer                0.9.0                    pypi_0    pypi
diskcache                 5.6.1                    pypi_0    pypi
distlib                   0.3.7                    pypi_0    pypi
distro                    1.8.0                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
dpath                     2.1.6                    pypi_0    pypi
dulwich                   0.21.5                   pypi_0    pypi
dvc                       3.13.3                   pypi_0    pypi
dvc-data                  2.12.2                   pypi_0    pypi
dvc-http                  2.30.2                   pypi_0    pypi
dvc-objects               0.25.0                   pypi_0    pypi
dvc-render                0.5.3                    pypi_0    pypi
dvc-studio-client         0.13.0                   pypi_0    pypi
dvc-task                  0.3.0                    pypi_0    pypi
entrypoints               0.4              py38h06a4308_0  
exceptiongroup            1.1.2                    pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0  
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.12.2                   pypi_0    pypi
fire                      0.5.0                    pypi_0    pypi
flake8                    6.1.0                    pypi_0    pypi
flatten-dict              0.4.2                    pypi_0    pypi
flufl-lock                7.1.1                    pypi_0    pypi
fonttools                 4.42.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
frozenlist                1.4.0                    pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
funcy                     2.0                      pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
giflib                    5.2.1                h5eee18b_3  
gitdb                     4.0.10                   pypi_0    pypi
gitpython                 3.1.32                   pypi_0    pypi
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
google-auth               2.22.0                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grandalf                  0.8                      pypi_0    pypi
grpcio                    1.56.2                   pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      3.4              py38h06a4308_0  
imageio                   2.31.1                   pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
importlib_resources       5.2.0              pyhd3eb1b0_1  
iniconfig                 2.0.0                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46305  
ipykernel                 6.19.2           py38hb070fc8_0  
ipython                   8.12.0           py38h06a4308_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                8.0.4            py38h06a4308_0  
iterative-telemetry       0.0.8                    pypi_0    pypi
jedi                      0.18.1           py38h06a4308_1  
jinja2                    3.1.2            py38h06a4308_0  
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.3.1                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1  
jsonpath-ng               1.5.3                    pypi_0    pypi
jsonschema                4.17.3           py38h06a4308_0  
jupyter                   1.0.0                    pypi_0    pypi
jupyter-console           6.6.3                    pypi_0    pypi
jupyter_client            7.4.9            py38h06a4308_0  
jupyter_core              5.3.0            py38h06a4308_0  
jupyter_server            1.13.5             pyhd3eb1b0_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        3.0.5            py38h06a4308_0  
kiwisolver                1.4.4                    pypi_0    pypi
kombu                     5.3.1                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libdeflate                1.17                 h5eee18b_0  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.4                h5eee18b_0  
libpng                    1.6.39               h5eee18b_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.0                h6a678d5_2  
libunistring              0.9.10               h27cfd23_0  
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
libxml2                   2.10.3               hcbfbd50_0  
libxslt                   1.1.37               h2085143_0  
llvmlite                  0.36.0                   pypi_0    pypi
lxml                      4.9.2            py38h5eee18b_0  
lyft-dataset-sdk          0.0.8                    pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.4.4                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.1            py38h7f8727e_0  
matplotlib                3.5.2                    pypi_0    pypi
matplotlib-inline         0.1.6            py38h06a4308_0  
mccabe                    0.7.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistune                   0.8.4           py38h7b6447c_1000  
mkl                       2023.1.0         h6d00ec8_46342  
mkl-service               2.4.0            py38h5eee18b_1  
mkl_fft                   1.3.6            py38h417a72b_1  
mkl_random                1.2.2            py38h417a72b_1  
mmcls                     0.25.0                   pypi_0    pypi
mmcv-full                 1.5.2                    pypi_0    pypi
mmdet                     2.28.0                   pypi_0    pypi
mmdet3d                   1.1.0rc3                  dev_0    <develop>
mmengine                  0.8.4                    pypi_0    pypi
mmsegmentation            0.24.0                   pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nanotime                  0.5.2                    pypi_0    pypi
nbclassic                 0.5.5            py38h06a4308_0  
nbclient                  0.5.13           py38h06a4308_0  
nbconvert                 5.4.1                      py_2  
nbformat                  5.7.0            py38h06a4308_0  
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.5.6            py38h06a4308_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.2                      pypi_0    pypi
ninja                     1.11.1                   pypi_0    pypi
notebook                  6.5.4            py38h06a4308_0  
notebook-shim             0.2.2            py38h06a4308_0  
numba                     0.53.0                   pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
nuscenes-devkit           0.1.0                    pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
onnx                      1.13.1                   pypi_0    pypi
onnx2torch                1.5.11                   pypi_0    pypi
open3d                    0.11.2                   py38_0    open3d-admin
opencv-python             4.8.0.74                 pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openmim                   0.3.9                    pypi_0    pypi
openssl                   3.0.9                h7f8727e_0  
openxlab                  0.0.25                   pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
orjson                    3.9.4                    pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
packaging                 23.0             py38h06a4308_0  
pandas                    1.5.0                    pypi_0    pypi
pandoc                    2.12                 h06a4308_3  
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pathspec                  0.11.2                   pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pbr                       5.11.1                   pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.4.0            py38h6a678d5_0  
pip                       23.1.2           py38h06a4308_0  
pkgutil-resolve-name      1.3.10           py38h06a4308_0  
platformdirs              3.10.0                   pypi_0    pypi
plotly                    5.15.0                   pypi_0    pypi
pluggy                    1.2.0                    pypi_0    pypi
ply                       3.11                     pypi_0    pypi
plyfile                   1.0.1                    pypi_0    pypi
prettytable               3.8.0                    pypi_0    pypi
prometheus_client         0.14.1           py38h06a4308_0  
prompt-toolkit            3.0.36           py38h06a4308_0  
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.0            py38h5eee18b_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycocotools               2.0.6                    pypi_0    pypi
pycodestyle               2.11.0                   pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pycryptodome              3.19.0                   pypi_0    pypi
pydot                     1.4.2                    pypi_0    pypi
pyflakes                  3.1.0                    pypi_0    pypi
pygit2                    1.12.2                   pypi_0    pypi
pygments                  2.15.1           py38h06a4308_1  
pygtrie                   2.3.2                    pypi_0    pypi
pyopenssl                 23.0.0           py38h06a4308_0  
pyparsing                 2.4.7                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pyrsistent                0.18.0           py38heee7806_0  
pysocks                   1.7.1            py38h06a4308_0  
pytest                    7.4.0                    pypi_0    pypi
python                    3.8.17               h955ad1f_0  
python-benedict           0.32.0                   pypi_0    pypi
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-fastjsonschema     2.16.2           py38h06a4308_0  
python-fsutil             0.10.0                   pypi_0    pypi
python-slugify            8.0.1                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     23.2.0           py38h6a678d5_0  
qtconsole                 5.4.3                    pypi_0    pypi
qtpy                      2.3.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.17.32                  pypi_0    pypi
ruamel-yaml-clib          0.2.7                    pypi_0    pypi
s3transfer                0.6.1                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.3.0                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
scmrepo                   1.1.0                    pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1  
sentry-sdk                1.29.2                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                60.2.0                   pypi_0    pypi
shapely                   1.8.5                    pypi_0    pypi
shortuuid                 1.0.11                   pypi_0    pypi
shtab                     1.6.4                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.2.0            py38h06a4308_1  
soupsieve                 2.4              py38h06a4308_0  
sqlite                    3.41.2               h5eee18b_0  
sqltrie                   0.7.0                    pypi_0    pypi
stack_data                0.2.0              pyhd3eb1b0_0  
stevedore                 5.1.0                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0  
tenacity                  8.2.2                    pypi_0    pypi
tensorboard               2.13.0                   pypi_0    pypi
tensorboard-data-server   0.7.1                    pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
terminado                 0.17.1           py38h06a4308_0  
terminaltables            3.1.10                   pypi_0    pypi
testpath                  0.6.0            py38h06a4308_0  
text-unidecode            1.3                      pypi_0    pypi
threadpoolctl             3.2.0                    pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
tinycss2                  1.2.1            py38h06a4308_0  
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tomlkit                   0.12.1                   pypi_0    pypi
torch                     1.11.0+cu113             pypi_0    pypi
torchaudio                0.11.0+cu113             pypi_0    pypi
torchvision               0.12.0+cu113             pypi_0    pypi
tornado                   6.2              py38h5eee18b_0  
tqdm                      4.65.1                   pypi_0    pypi
traitlets                 5.7.1            py38h06a4308_0  
trimesh                   2.35.39                  pypi_0    pypi
typing_extensions         4.6.3            py38h06a4308_0  
tzdata                    2023.3                   pypi_0    pypi
urllib3                   1.26.16          py38h06a4308_0  
vine                      5.0.0                    pypi_0    pypi
virtualenv                20.24.2                  pypi_0    pypi
virtualenv-clone          0.5.7                    pypi_0    pypi
virtualenvwrapper         4.8.4                    pypi_0    pypi
voluptuous                0.13.1                   pypi_0    pypi
wandb                     0.15.8                   pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1                    py38_1  
websocket-client          0.58.0           py38h06a4308_4  
werkzeug                  2.3.6                    pypi_0    pypi
wheel                     0.38.4           py38h06a4308_0  
widgetsnbextension        4.0.5            py38h06a4308_0  
xz                        5.4.2                h5eee18b_0  
yapf                      0.40.1                   pypi_0    pypi
yarl                      1.9.2                    pypi_0    pypi
zc-lockfile               3.0.post1                pypi_0    pypi
zeromq                    4.3.4                h2531618_0  
zipp                      3.11.0           py38h06a4308_0  
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0 

### Reproduces the problem - code sample

_base_ = [
    '../_base_/datasets/nuscenes.py',
    '../_base_/models/centerpoint_02pillar_second_secfpn_nus3d.py',
    '../_base_/schedules/cyclic_20e.py', '../_base_/default_runtime.py'
]

# Refer to variables from base configs
ego_range_ = {{ _base_.ego_range }}
voxel_size_ = {{ _base_.voxel_size }}
point_cloud_range_ = {{ _base_.point_cloud_range }}
point_cloud_range_ = [-30, -40, -5, 90, 40, 3.1]
ego_range_ = [-1.5, -1.5, 0, 7, 1.5, 3.6]

""" x_offset = -6.22
z_offset = -3.12

ego_range_[0::3] = list(map(lambda elem: elem+x_offset, ego_range_[0::3]))
ego_range_[2::3] = list(map(lambda elem: elem+z_offset, ego_range_[2::3]))

point_cloud_range_[0::3] = list(map(lambda elem: elem+x_offset, point_cloud_range_[0::3]))
point_cloud_range_[2::3] = list(map(lambda elem: elem+z_offset, point_cloud_range_[2::3])) """

sweeps_num = 3
# Formula used for below grid_x = (point_cloud_range_[3] - point_cloud_range_[0]) / voxel_size_[0]
# !!!  be sure about the grid sizes below before using this config  !!!
grid_size_x = 600
grid_size_y = 400
grid_size_z = 1
coder_pc_range = [-36.22, -40] # cant slice the first two elements from inherited value (returns first two char of var name string) 
                                # these values are computed automatically in base config.  Config.fromfile(cfg_file) to get them

class_names = ['car', 'truck', 'trailer', 'motorcycle', 'bicycle', 'pedestrian']

model = dict(
            pts_backbone=dict(freeze_stages_0=0, freeze_stages_1=0, freeze_stages_2=0),
            pts_voxel_layer=dict(point_cloud_range=point_cloud_range_),
            pts_voxel_encoder=dict(point_cloud_range=point_cloud_range_),
            pts_middle_encoder=dict(type='PointPillarsScatter', in_channels=64, output_shape=(grid_size_y, grid_size_x)),
            pts_bbox_head=dict( bbox_coder=dict(pc_range=coder_pc_range, code_size=7),
                                common_heads=dict(reg=(2, 2), height=(1, 2), dim=(3, 2), rot=(2, 2), _delete_=True),
                        ),
            # model training and testing settings
            train_cfg=dict(
                pts=dict(
                    point_cloud_range=point_cloud_range_,
                    code_weights=[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
                    grid_size = [grid_size_x, grid_size_y, 1])),
            test_cfg=dict(pts=dict(pc_range=coder_pc_range)
            ))

dataset_type = 'NuScenesDataset'
data_root = 'data/nuscenes/'
file_client_args = dict(backend='disk')

db_sampler = dict(
    data_root=data_root,
    info_path=data_root + 'nuscenes_dbinfos_train.pkl',
    rate=1.0,
    bbox_code_size=7,
    prepare=dict(
        filter_by_difficulty=[-1],
        filter_by_min_points=dict(
            car=5,
            truck=5,
            # bus=5,
            trailer=5,
            # construction_vehicle=5,
            # traffic_cone=5,
            # barrier=5,
            motorcycle=5,
            bicycle=5,
            pedestrian=5
            )),
    classes=class_names,
    sample_groups=dict(
            car=5,
            truck=5,
            # bus=5,
            trailer=5,
            # construction_vehicle=5,
            # traffic_cone=5,
            # barrier=5,
            motorcycle=5,
            bicycle=5,
            pedestrian=5
        ),
    points_loader=dict(
        type='LoadPointsFromFile',
        coord_type='LIDAR',
        load_dim=5,
        use_dim=[0, 1, 2, 3, 4],
        file_client_args=file_client_args,
        ))

train_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='LIDAR',
        load_dim=5,
        use_dim=5,
        file_client_args=file_client_args,),
    dict(
        type='LoadPointsFromMultiSweeps',
        sweeps_num=sweeps_num,
        use_dim=[0, 1, 2, 3, 4],
        file_client_args=file_client_args,
        pad_empty_sweeps=True,
        remove_close=True,),
    dict(type='PointsRangeFilter', point_cloud_range=ego_range_, filter_inside=True),
    dict(type='LoadAnnotations3D', with_bbox_3d=True, with_label_3d=True),
    dict(type='ObjectSample', db_sampler=db_sampler),
    dict(
        type='GlobalRotScaleTrans',
        rot_range=[-0.3925, 0.3925],
        scale_ratio_range=[0.95, 1.05],
        translation_std=[0, 0, 0]),
    dict(
        type='RandomFlip3D',
        sync_2d=False,
        flip_ratio_bev_horizontal=0.5,
        flip_ratio_bev_vertical=0.5),
    dict(type='PointsRangeFilter', point_cloud_range=point_cloud_range_),
    dict(type='ObjectRangeFilter', point_cloud_range=point_cloud_range_),
    dict(type='ObjectNameFilter', classes=class_names),
    dict(type='PointShuffle'),
    dict(type='DefaultFormatBundle3D', class_names=class_names),
    dict(type='Collect3D', keys=['points', 'gt_bboxes_3d', 'gt_labels_3d'])
]
test_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='LIDAR',
        load_dim=5,
        use_dim=5,
        file_client_args=file_client_args,
        use_childs=USE_CHILD_LIDARS,
        use_lidar_concat=USE_CONCAT_LIDAR),
    dict(
        type='LoadPointsFromMultiSweeps',
        sweeps_num=sweeps_num,
        use_dim=[0, 1, 2, 3, 4],
        file_client_args=file_client_args,
        pad_empty_sweeps=True,
        remove_close=True,),
    dict(type='PointsRangeFilter', point_cloud_range=ego_range_, filter_inside=True), #crop points from ego vehicle
    dict(
        type='MultiScaleFlipAug3D',
        img_scale=(1333, 800),
        pts_scale_ratio=1,
        flip=False,
        transforms=[
            dict(
                type='GlobalRotScaleTrans',
                rot_range=[0, 0],
                scale_ratio_range=[1., 1.],
                translation_std=[0, 0, 0]),
            dict(type='RandomFlip3D'),
            dict(
                type='DefaultFormatBundle3D',
                class_names=class_names,
                with_label=False),
            dict(type='Collect3D', keys=['points'])
        ])
]
# construct a pipeline for data and gt loading in show function
# please keep its loading function consistent with test_pipeline (e.g. client)
eval_pipeline = [
    dict(
        type='LoadPointsFromFile',
        coord_type='LIDAR',
        load_dim=5,
        use_dim=5,
        file_client_args=file_client_args),
    dict(
        type='LoadPointsFromMultiSweeps',
        sweeps_num=sweeps_num,
        use_dim=[0, 1, 2, 3, 4],
        file_client_args=file_client_args,
        pad_empty_sweeps=True,
        remove_close=True),
    dict(
        type='DefaultFormatBundle3D',
        class_names=class_names,
        with_label=False),
    dict(type='Collect3D', keys=['points'])
]

# train_load_interval = 1000

with_velocity = False
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=4,
    train=dict(
        type='CBGSDataset',
        pipeline = train_pipeline,
        dataset=dict(
            type=dataset_type,
            data_root=data_root,
            ann_file=data_root + 'nuscenes_infos_train.pkl',
            pipeline=train_pipeline,
            # load_interval=train_load_interval,
            classes=class_names,
            with_velocity=with_velocity,
            test_mode=False,
            use_valid_flag=True,,
            # we use box_type_3d='LiDAR' in kitti and nuscenes dataset
            # and box_type_3d='Depth' in sunrgbd and scannet dataset.
            box_type_3d='LiDAR')),
    val=dict(
        pipeline=test_pipeline,
        classes=class_names,
        with_velocity=with_velocity),
    test=dict(
        pipeline=test_pipeline,
        classes=class_names,
        with_velocity=with_velocity)

log_config = dict(
                  hooks=[
                    dict(type='TextLoggerHook'),
                    dict(type='TensorboardLoggerHook'),
                    dict(type='MMDetWandbHook',
                        init_kwargs= {'project': 'Centerpoint',
                                      'name': 'training1'},
                        interval=5,
                        log_checkpoint=True,
                        log_checkpoint_metadata=True,
                        num_eval_images=3)
                        ]
) 

workflow = [('train', 1), ('val', 1)]

runner = dict(type='EpochBasedRunner', max_epochs=10)
        
checkpoint_config = dict(interval=5, by_epoch=True)

evaluation = dict(interval=5, pipeline=test_pipeline, metric='bbox')

### Reproduces the problem - command or script

python tools/train.py configs/centerpoint/centerpoint_02pillar_second_secfpn_4x8_cyclic_20e_nus.py

### Reproduces the problem - error message

We created custom dataset as nuscenes format and testing nuscenes config, it works correctly until 20 epoch, When we set 60 epoch, after 25 or 40 epoch, it is crashed and error message is just "killed". Until the crashed, training, validation and evaluation works correctly. the 

### Additional information

We use cyclic20e.py optimizer for 100 epoch.

**Comment by randomfforest** [comment]
hi,I meet the same problem,I create custom dataset as kitti and training process killed after several epoch.
The Error message  is:RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
have you solve your problem?

**Comment by enesdorukadastec** [comment]
> hi,I meet the same problem,I create custom dataset as kitti and training process killed after several epoch. The Error message is:RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. have you solve your problem?

this problem happens just using AWS instance, when I run my local, it runs correctly.
