### ISSUE TITLE
Using 2D bounding boxes to estimate 3D

### ISSUE THREAD

**Issue by snachi2s** [open-mmlab/mmdetection3d#2756]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

Is there any implementations in mmdet3d that uses 2D Ground truths(bounding boxes and camera matrix) to detect 3D bounding boxes from RGB images?

You listed SMOKE under camera based methods but when I see the config file it loads 3D annotations.  Is it possible to train the method with 2D ground truths?

**Comment by ZCMax** [comment]
Currently we do not support training using only 2D annotations~ 3D annotations are needed in our training
