### ISSUE TITLE
[Feature]  Remap Annotation Labels 

### ISSUE THREAD

**Issue by OrcunCanDeniz** [open-mmlab/mmdetection3d#2757]
### What is the feature?

Is it possible to easily remap annotation labels to some other label at the runtime. I.e, I would like to pool all vehicle types into 'car' label instead of having 'truck', 'car', 'bus' labels seperately for NuScenes dataset

**Comment by ZCMax** [comment]
Of course, you only need to implement a function like 'merge_classes' in https://github.com/open-mmlab/mmdetection3d/blob/main/mmdet3d/datasets/nuscenes_dataset.py after loading the annotations.
