### ISSUE TITLE
我是真坤巴服了[Docs] 

### ISSUE THREAD

**Issue by devils1741** [open-mmlab/mmdetection3d#2759]
### Branch

main branch  https://mmdetection3d.readthedocs.io/en/latest/

### 📚 The doc issue

mmcv + mmdet + mmdet3D真的是一脉相承的稀烂。
mmcv安装那么多坑，从来没见github官方提示过。他马的你那个mmcv安装要和torch版本对应啊在官网说一句很难吗？mmcv安装之复杂竟然要单独安一个openmim不觉得可笑？他马的之前的版本的mim安装mmcv失败啊，同一个组织开发的两个库真他马5到家了。
mmdet3D更是NB。你那个inference_demo.ipynb自带的配置名字都不对啊。名字改过去后加载模型没问题但是他马的直接报错AttributeError: 'VoxelNet' object has no attribute 'classes'。这就是你们写的demo啊？这就是你们给初学者写的Demo?
你们这个mmdet3D相对路径识别有问题啊。他马的inference_demo从pycharm直接run识别不了相对路径啊。
真的谢谢你们帮助我回忆学习tf1.x版本时候的感觉了哦。垃圾框架屎山代码迟早💊。

**Comment by evelign** [comment]
心累。
配置文件路径没问题但是文件名没对上，改完下完ckpt文件，报warning说和调用的demo模型长相不太一样。
然后报`AttributeError`，去模型里面慢慢找相关的key然后改inference代码，完事儿最后一个函数又`AssertionError: got unexpected vis_task det.`点进去看发现根本就没有这个vis_task，不知道写这个代码的有没有自己跑过。

**Comment by Baolu1998** [comment]
accurate comments

**Comment by 17638759823** [comment]
exactly

**Comment by JialeiXu** [comment]
Strongly Agree

**Comment by xylcbd** [comment]
各种赞同... 被mmcv/mmdet/mmrotate这些折腾

**Comment by saprrow** [comment]
确实，这些框架就是折腾人的

**Comment by Blinkblade** [comment]
给我恶心坏了，nuScenes数据集有多视角的图像，连最简单的resize flip都不能适配，db sampler说着要支持2d ,todo了三年了一行代码都没写，centerpoint支持kitti，人家都给你做完了也不愿意更新。v1.x到现在最基本的功能还没有迁移和适配，要知道v1.x已经发布一年多了，结果annotation连加载2d bbox都报错，弄个新模型结果从数据生成开始几乎都要自己实现，而MM的层层封装却在不断地阻挠你实现正确的功能，如果是个torch项目，你只需要分别写好然后组装在一起就好了，mm不行，他要你把他的封装了一百层的东西全都剥开一环套一环一个一个改，我真不明白你封装了这么多层连一些很基本的功能都没有除了给大伙添加难度还有什么用？？？？

**Comment by CkShibit** [comment]
顶一下，安装一天放弃了，代码自己写了

**Comment by leewhue** [comment]
Support, I am very angry that each version of mmdet3d seems to be unrelated, Tensorflow has change documentation, mmdet3d has no change documentation, the graphics card of the new framework cannot support the old version, but many models are the old version of mmdet3d.

**Comment by zhouyuchong** [comment]
一针见血的

**Comment by Hichengdong** [comment]
啊，谁懂啊，多卡训练KITTI数据集到20多轮就提示xxx文件丢失，应该不是我算法的问题吧，前面都把完整的数据集训练这么多次了，突然就一个找不到image_2/xxxx.png.然后就死了。

**Comment by iamxiaohuang** [comment]
就是一坨屎 纯恶心

**Comment by imzhuhl** [comment]
2024-12-25 圣诞节被恶心到了，各种 register hook 满天飞，mm系列层层依赖，看个实现要跳好几个库，稍微改动一个torch版本又是一堆错误

**Comment by ming132** [comment]
你要笑死我

**Comment by SwaggyPinqi12** [comment]
这傻逼框架，我真服了

**Comment by insomnia2250** [comment]
True dude

**Comment by SophusDavid** [comment]
电子工业垃圾，赛博裹脚布。
明明那么多办法能向后兼容，但是选择最草的一种。
以及代码发布之前maintainer真的自己有做过测试吗？

**Comment by potentialming-google** [comment]
完全赞同！神经

**Comment by jzjizhe** [comment]
支持
