### ISSUE TITLE
Log Analysis without mAP key in log.json

### ISSUE THREAD

**Issue by liyang0522** [open-mmlab/mmdetection3d#276]
In your Log Analysis,  there is an example of comparing he bbox mAP of two runs in the same figure, as following:

`python tools/analyze_logs.py plot_curve log1.json log2.json --keys bbox_mAP --legend run1 run2
`
but there is no bbox_mAP key in any log.json, how can we  plot  the mAP figure ? There are only the 'loss', 'loss_cls', 'loss_bbox', and 'loss_dir' keys.
Thank you for your help!

**Comment by Tai-Wang** [comment]
Thanks for your reminding. I will create a PR to adjust this part for clearer understanding.

**Comment by Tai-Wang** [comment]
Fixed with #285 .
