### ISSUE TITLE
Bug in BaseInstance3DBoxes

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#277]
In my opinion the inplace modification of tensor in this [line](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/bbox/structures/base_box3d.py#L65`) is dangerous for 2 reasons.

1. It may tend to corrupt ground truth data in `numpy` format. It's hardly believable, but i'm going to explain. The thing is, `torch.as_tensor` function in this [line](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/bbox/structures/base_box3d.py#L41) doesn't protect the `tensor` argument of `__init__` from further rewriting of the same memory, allocated by `numpy`. More info can be found in the official documentation of [torch.as_tensor](https://pytorch.org/docs/stable/generated/torch.as_tensor.html). For example, this constructor is called [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/evaluation/indoor_eval.py#L257) in `indoor_eval` function. So after each validation step the `z` coordinate of `gt_anno['gt_boxes_upright_depth']` may be overwritten. One may ask why it doesn't affect current evaluation protocol for `SUNRGBD`? The answer is, by coincidence these coordinates are now stored in `np.float64`. The bug would be present if that is `np.float32`.

2. In many cases `pytorch` doesn't like inplace modifications of variables under the gradient. It tends to `RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: ...` 

If I'm not mistaken something and you agree this is a bug, I can send a PR.
The possible solution may be:
```
self.tensor = torch.cat((self.tensor[:, :3] + self.tensor[:, 3:6] * (dst - src), self.tensor[:, 3:]), dim=-1)
```

**Comment by Tai-Wang** [comment]
Thanks for your kind suggestion. I almost agree with you, but there may be only two concerns:
1. I am not sure whether this inplace modification has affect some current implementation. So it should be able to pass the unit tests and also ensure the other implemented models will not be affected (for example, maybe need rebenchmark).
2. For your given possible solution, I think `.clone()` should be added after self.tensor on the right side of the equation to avoid your mentioned RuntimError caused by inplace modifications?

**Comment by filaPro** [comment]
I'm now running without extra `.clone()`. Do we really need it? The proposed replacement of `+=` to `torch.cat` already avoids this `RuntimeError`.

**Comment by ZwwWayne** [comment]
Hi @filaPro ,
Thanks for you kind suggestion. Would you like to create a PR to fix that?

**Comment by Tai-Wang** [comment]
OK @filaPro . I just think `.clone()` is a general way to avoid the inplace RuntimeError and could protect the original tensor from being unintentionally changed. If without `.clone()` could work in your end, you can feel free to create a PR to fix that.

**Comment by filaPro** [comment]
Hi @Tai-Wang ,
I agree that `.clone()` is a better solution then replacing all inplace operations in all methods of `BaseInstance3DBoxes` and its descendants. So the PR is as simple as adding this `.clone()`.
