### ISSUE TITLE
where 3dssd checkpoints ?

### ISSUE THREAD

**Issue by HongxuZhu** [open-mmlab/mmdetection3d#279]

**Comment by ZwwWayne** [comment]
To be released soon.

**Comment by RolandoAvides** [comment]
Hello! 

Are there any prospects regarding the date of publication of checkpoints?

I really appreciate any help you can provide.

**Comment by zye1996** [comment]
> Hello!
> 
> Are there any prospects regarding the date of publication of checkpoints?
> 
> I really appreciate any help you can provide.

I include my checkpoint (here)[https://github.com/zye1996/3DSSD-torch] if you are interested

**Comment by RolandoAvides** [comment]
> https://github.com/zye1996/3DSSD-torch

Hi! Thank you!! I will check it out!

Do you think changing the number of the input parameters of the 3D backbone would be a hard taks?

**Comment by zye1996** [comment]
> > https://github.com/zye1996/3DSSD-torch
> 
> 
> 
> Hi! Thank you!! I will check it out!
> 
> 
> 
> Do you think changing the number of the input parameters of the 3D backbone would be a hard taks?  Is the code prepared to receive point clouds with differente number of features?

Yes the code takes feature number as one of the configurations so it should be fine

**Comment by RolandoAvides** [comment]
> > > https://github.com/zye1996/3DSSD-torch
> > 
> > 
> > Hi! Thank you!! I will check it out!
> > Do you think changing the number of the input parameters of the 3D backbone would be a hard taks?  Is the code prepared to receive point clouds with differente number of features?
> 
> Yes the code takes feature number as one of the configurations so it should be fine

Ok! I was giving a look to it and I didn't found the code to change the number of initial features of point clouds. For instance, if i wanted to discard the intensity parameter, using only the cartesian coordinates, how could i change the cfg flie?

Thanks in advance!

**Comment by zye1996** [comment]
> > > > https://github.com/zye1996/3DSSD-torch
> 
> > > 
> 
> > > 
> 
> > > Hi! Thank you!! I will check it out!
> 
> > > Do you think changing the number of the input parameters of the 3D backbone would be a hard taks?  Is the code prepared to receive point clouds with differente number of features?
> 
> > 
> 
> > Yes the code takes feature number as one of the configurations so it should be fine
> 
> 
> 
> Ok! I was giving a look to it and I didn't found the code to change the number of initial features of point clouds. For instance, if i wanted to discard the intensity parameter, using only the cartesian coordinates, how could i change the cfg flie?
> 
> 
> 
> Thanks in advance!

it will take all inputs after 4th dimension as features so you can just feed the model with data including only 3 dimension.

**Comment by Tai-Wang** [comment]
Close via #359 .
