### ISSUE TITLE
Finetune on 3D dataset

### ISSUE THREAD

**Issue by fabiopoiesi** [open-mmlab/mmdetection3d#28]
Hi,

I would like to finetune a model on my dataset. The tutorials to do so seems to be for 2D images.
Are you planning to include also those for 3D?

Thanks

**Comment by ZwwWayne** [comment]
The high-level steps are basically the same as those for 2D images, so you still need to do the basic steps, though the details might be different. We did not update it for 3D because currently, we have not find a good example for fine-tuning.

**Comment by fabiopoiesi** [comment]
A possibility could be to get the Scannet model and finetune on SunRGBD.
Would that work?

**Comment by ZwwWayne** [comment]
We have not tried that, you could have a try.

**Comment by fabiopoiesi** [comment]
Without an accurate I think it'll be quite challenging...

**Comment by AllenPeng0209** [comment]
I got the same problem, the high level is the same, but so much detail make it much harder.
Hope someone could write the guild for custom dataset tutorial.
