### ISSUE TITLE
Inference on nuScenes

### ISSUE THREAD

**Issue by StephanieWX** [open-mmlab/mmdetection3d#280]
I modified [this file](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/apis/inference.py) as follows and could get correct inference results on nuScenes.

1. add 'timestamp' and 'sweeps' infos to [data](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/apis/inference.py#L62), using [code](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/nuscenes_converter.py#L205) 205-216
2. replace [this line](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/loading.py#L167) with `ts = results['timestamp'] / 1e6`

Here is the question:
If `results['timestamp']` is not devided by `1e6`, then the detection score would all be 1.0. The detection results after format_bbox are also wrong.
![image](https://user-images.githubusercontent.com/28651487/105147487-388f1a80-5b3c-11eb-813a-b6f33ab67969.png)

However, just devide `results['timestamp']` by `1e6` would fix the problem. 
![image](https://user-images.githubusercontent.com/28651487/105148194-0df19180-5b3d-11eb-9960-3d7297653a60.png)

I don't understand why this is happening, cause when evaluating the whole validation dataset, there is nothing wrong with [this line](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/loading.py#L167) and I don't need to modify anything.

**Comment by ZwwWayne** [comment]
Hi @StephanieWX ,
Would you like to try https://github.com/open-mmlab/mmdetection3d/pull/264 to see if it fixes your bug?

**Comment by StephanieWX** [comment]
> Hi @StephanieWX ,
> Would you like to try #264 to see if it fixes your bug?

Thanks for your response. I've found why the bug exists.

The bug is caused by adding `timestamp=sample['timestamp']` to [data](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/apis/inference.py#L62).
In fact, when training and evaluating the dataset, the `timestamp` is divided by `1e6` during [get_data_info](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/nuscenes_dataset.py#L207), which is not called during the inference.
Thus `timestamp=sample['timestamp']/1e6` should be added to [data](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/apis/inference.py#L62) and [this line](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/loading.py#L167) could remain the same.

**Comment by ZwwWayne** [comment]
Great. Then this issue will be closed as it seems to be resolved. Feel free to reopen it if you have any further questions.
