### ISSUE TITLE
`show_result_meshlab` and `model.show_results` might produce invalid .obj files

### ISSUE THREAD

**Issue by EricWiener** [open-mmlab/mmdetection3d#281]
I'm not totally sure about this one (so I didn't make this an issue for an error), but I think the above-mentioned functions either produce an invalid `.obj` file format or I'm not understanding the formatting.

The `.obj` files produced have the form:
```
v -0.028000 21.554001 0.938000
v -0.094000 21.240000 0.927000
v -0.159000 21.056000 0.921000
v -0.226000 21.132999 0.924000
v -0.304000 21.889999 0.949000
...
```
where each row starts with a `v`. When trying to render this with `open3d`, it complains that:
```
[Open3D INFO] Skipping non-triangle primitive geometry of type: 1
TriangleMesh with 0 points and 0 triangles.
```

If I use `open3d` to save a triangle mesh, it will produce something like:
```
# Created by Open3D 
# object name: output_mesh
# number of vertices: 88
# number of triangles: 132
v 0.85186 16.5752 -1.4654
v 0.85186 16.5752 -0.0415821
v 2.34802 16.0618 -1.4654
v 2.34802 16.0618 -0.0415821
v -0.297365 13.2264 -1.4654
...
f 2 4 1
f 5 2 1
f 1 4 3
f 3 5 1
f 2 8 4
f 6 2 5
...
```
Where there are vertices specified by `v`, but also faces and the vertices they connect specified by `f`.

It seems like the `.obj` files produced by open3d are really point clouds and not triangle meshes since they only have vertices and not faces.

**Comment by Tai-Wang** [comment]
Thanks for your information. From my understanding, it should be an `.obj` file with only vertices information and just can not be recognized by open3d rendering engine? It should work well for other platform/software like meshlab.
New visualization methods like with open3d are in our plan, and we will consider this flaw if necessary.

**Comment by EricWiener** [comment]
Got it. Thanks so much for the reply!
