### ISSUE TITLE
Why is the Z dim size of the sparse shape (specified in SECOND detector's middle-encoder) larger than necessary?

### ISSUE THREAD

**Issue by zhanggefan** [open-mmlab/mmdetection3d#282]
Hi, 

Thank you for your great work. 

When I tried to re-train a SECOND detector, I noticed that inside the forward code of `SparseEncoder`, the voxelized point cloud data are converted to `SparseConvTensor` at the first step and the **sparse shape** is explicitly specified there.

My question is:
 - Though it does not affect the result, **It looks like the Z dimension of the sparse shape is larger than necessary (by exactly +1)**. Did you make it by intention? Did I miss anything? 
 [60, 1280, 1920] seems enough for hv_second_secfpn_waymo.py#L18 
 [40, 1600, 1408] for hv_second_secfpn_kitti.py#L12

https://github.com/open-mmlab/mmdetection3d/blob/ca0faaf047aaec1adc66fb18c199f6dc4316cfba/configs/_base_/models/hv_second_secfpn_waymo.py#L7-L19
https://github.com/open-mmlab/mmdetection3d/blob/ca0faaf047aaec1adc66fb18c199f6dc4316cfba/configs/_base_/models/hv_second_secfpn_kitti.py#L1-L13

**Comment by ZwwWayne** [comment]
1. We follow the typical convention of previous works.
2. SparseEncoder will do downsampling in the hight dimension. So this parameter allows the hight dimension can be downsampled by several times without errors and finally meet the implementation of SECOND.

**Comment by Tai-Wang** [comment]
Please refer to this [line](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/middle_encoders/sparse_encoder.py#L65) in our implementation and this [line](https://github.com/traveller59/second.pytorch/blob/master/second/pytorch/models/middle.py#L153) in SECOND for the detail. Note that there is a padding=1 on the Z dimension.
