### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'projects.BEVFusion' when the pytorch3d is installed

### ISSUE THREAD

**Issue by sangjinpark97** [open-mmlab/mmdetection3d#2832]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I have modified the scripts/configs, or I'm working on my own tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment
```shell
sys.platform: linux
Python: 3.8.10 (default, Nov 22 2023, 10:22:35) [GCC 9.4.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3080 Ti
CUDA_HOME: /usr/local/cuda-11.3
NVCC: Cuda compilation tools, release 11.3, V11.3.58
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 1.11.0+cu113
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0+cu113
OpenCV: 4.7.0
MMEngine: 0.10.1
MMDetection: 3.0.0
MMDetection3D: 1.1.1+bef772a
spconv2.0: True
```

### Reproduces the problem - code sample

None

### Reproduces the problem - command or script

None

### Reproduces the problem - error message
```shell
Traceback (most recent call last):
  File "/home/hkd/.local/lib/python3.8/site-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'projects.BEVFusion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hkd/.local/lib/python3.8/site-packages/mmengine/config/config.py", line 462, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/hkd/.local/lib/python3.8/site-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
    raise ImportError(f'Failed to import {imp}')
ImportError: Failed to import projects.BEVFusion.bevfusion

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "tools/deployment/test.py", line 987, in test_mmdet3d
    cfg = Config.fromfile(args.config)
  File "/home/hkd/.local/lib/python3.8/site-packages/mmengine/config/config.py", line 474, in fromfile
    raise ImportError(err_msg) from e
ImportError: Failed to import custom modules from {'imports': ['projects.BEVFusion.bevfusion'], 'allow_failed_imports': False}, the current sys.path is: 
    /home/hkd/calibration/catkin_ws/devel/lib/python3/dist-packages
    /opt/ros/noetic/lib/python3/dist-packages
    /usr/lib/python38.zip
    /usr/lib/python3.8
    /usr/lib/python3.8/lib-dynload
    /home/hkd/.local/lib/python3.8/site-packages
    /home/hkd/.local/lib/python3.8/site-packages/transforms3d-0.4.1-py3.8.egg
    /home/hkd/.local/lib/python3.8/site-packages/sklearn-0.0.post4-py3.8.egg
    /home/hkd/.local/lib/python3.8/site-packages/SharedArray-3.2.3-py3.8-linux-x86_64.egg
    /home/hkd/.local/lib/python3.8/site-packages/easydict-1.11-py3.8.egg
    /home/hkd/.local/lib/python3.8/site-packages/rabbitvcs-0.19-py3.8.egg
    /home/hkd/fusion/mmdetection3d
    /home/hkd/packages/fvcore
    /home/hkd/packages/iopath
    /home/hkd/packages/pytorch3d
    /usr/local/lib/python3.8/dist-packages
    /usr/lib/python3/dist-packages

You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module
```
### Additional information

I have developed a project using BEVFusion based on MMDet3D without any problem or error from now on.

I installed the [PyTorch3D](https://github.com/facebookresearch/pytorch3d) to use the specific operation of it.

But, after installing it, the error of `ModuleNotFoundError: No module named 'projects.BEVFusion'` raises when running any script which is based on MMDet3D.

This is the commands to install the pytorch3d (I referred to [here](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md#2-install-from-a-local-clone))

```shell
$ https://github.com/facebookresearch/pytorch3d && cd pytorch3d
$ pip install -e .
```

Can you assume the reason?

Thank you in advance!

**Comment by maxiuw** [comment]
@eugenebak solved how ? 
I had this error locally and running `python projects/BEVFusion/setup.py develop` solved the issue but doesnt solve it on Docker

**Comment by lacie-life** [comment]
> @eugenebak solved how ? I had this error locally and running `python projects/BEVFusion/setup.py develop` solved the issue but doesnt solve it on Docker

I met same problem and run your command but I met new error like that:
/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
warning: no files found matching '*.cpp' under directory 'mmdet3d/.mim/ops'
warning: no files found matching '*.cu' under directory 'mmdet3d/.mim/ops'
warning: no files found matching '*.h' under directory 'mmdet3d/.mim/ops'
warning: no files found matching '*.cc' under directory 'mmdet3d/.mim/ops'
writing manifest file 'bev_pool.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "projects/BEVFusion/setup.py", line 70, in <module>
    zip_safe=False,
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 382, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse
    return Version(version)
  File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

Do you have any suggestions for me?

**Comment by BeileiCui** [comment]
> > @eugenebak solved how ? I had this error locally and running `python projects/BEVFusion/setup.py develop` solved the issue but doesnt solve it on Docker
> 
> I met same problem and run your command but I met new error like that: /home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend. warnings.warn(msg.format('we could not find ninja.')) warning: no files found matching '_.cpp' under directory 'mmdet3d/.mim/ops' warning: no files found matching '_.cu' under directory 'mmdet3d/.mim/ops' warning: no files found matching '_.h' under directory 'mmdet3d/.mim/ops' warning: no files found matching '_.cc' under directory 'mmdet3d/.mim/ops' writing manifest file 'bev_pool.egg-info/SOURCES.txt' running build_ext Traceback (most recent call last): File "projects/BEVFusion/setup.py", line 70, in zip_safe=False, File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/**init**.py", line 155, in setup return distutils.core.setup(**attrs) File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup return run_commands(dist) File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands dist.run_commands() File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands self.run_command(cmd) File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command cmd_obj.run() File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run self.install_for_development() File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development self.run_command('build_ext') File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command self.distribution.run_command(command) File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command cmd_obj.run() File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run _build_ext.run(self) File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run self.build_extensions() File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions _check_cuda_version(compiler_name, compiler_version) File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 382, in _check_cuda_version torch_cuda_version = packaging.version.parse(torch.version.cuda) File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 49, in parse return Version(version) File "/home/lacie/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in **init** match = self._regex.search(version) TypeError: expected string or bytes-like object
> 
> Do you have any suggestions for me?

@lacie-life Hi, I met the same error. Did you solve it? Thanks!

**Comment by lacie-life** [comment]
I solved that by clear everything and reinstall by this [link](https://mmdetection3d.readthedocs.io/en/latest/get_started.html#customize-installation)

**Comment by BeileiCui** [comment]
> I solved that by clear everything and reinstall by this [link](https://mmdetection3d.readthedocs.io/en/latest/get_started.html#customize-installation)

@lacie-life Thanks for your quick reply! My situation is a little different but I have solved it!
