### ISSUE TITLE
How to convert multi-view camera waymo dataset to kitti-format

### ISSUE THREAD

**Issue by yyaqi** [open-mmlab/mmdetection3d#2849]
### What is the feature?

Taking the front-left camera as an example, save its Tr_velo_to_cam, 
Tr_velo_to_cam = self.cart_to_homo(T_front_cam_to_ref) @ T_vehicle_to_cam, but when I visualize the box3D, the target box is not very accurate;

**Comment by Xiangxu-0103** [comment]
Can you provide more detailed information, such as where you want to show the 3D box, image or point cloud?

**Comment by yyaqi** [comment]
> Can you provide more detailed information, such as where you want to show the 3D box, image or point cloud?
问题解决了，谢谢！
