### ISSUE TITLE
A potential bug of points_in_boxes_gpu

### ISSUE THREAD

**Issue by caiqi** [open-mmlab/mmdetection3d#289]
https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/ops/roiaware_pool3d/points_in_boxes.py#L6 will not check the dim of points. For example,  points of shape [B, C, 4] will not raise an error but the returned results are wrong. It would be better to assert the dim of points to 3. The commonly used Kitti dataset has 4 dims and will get wrong outputs when directly used the raw points.

**Comment by Tai-Wang** [comment]
Thanks for your information. We will add assertion reminder with a PR ASAP.

**Comment by xiliu8006** [comment]
Thanks for your information. PR #357 fixed this issue.
