### ISSUE TITLE
python tools/train.py ./configs/pointpillars/hv_pointpillars_fpn_sbn-all_2x8_2x_lyft-3d.py

### ISSUE THREAD

**Issue by zyxcambridge** [open-mmlab/mmdetection3d#29]
File "/home/sl/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 187, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
python tools/train.py ./configs/pointpillars/hv_pointpillars_fpn_sbn-all_2x8_2x_lyft-3d.py

**Comment by ZwwWayne** [comment]
This model uses sync BN by default. So if you only have one GPU and want to train this model, you need to change all the SyncBN back to BN.

**Comment by tyjiang1997** [comment]
hi~，I encounter the same question when I run  configs/free_anchor/hv_pointpillars_fpn_sbn-all_free-anchor_4x8_2x_nus-3d.py . Could you tell me how to solve this. Thanks
