### ISSUE TITLE
Failed when with_velocity=False in nuscenes evaluation

### ISSUE THREAD

**Issue by JunrQ** [open-mmlab/mmdetection3d#292]
https://github.com/open-mmlab/mmdetection3d/blob/c556d27444958476f18e81c0a268a42f7a92e7f9/mmdet3d/datasets/nuscenes_dataset.py#L548

If `with_velocity=False`, box3d.tensor will have shape [*, 7] which make velocity length less than 3. It seems that nuscenes Box doesn't support velocity with length less than 3.

**Comment by Tai-Wang** [comment]
We have not trained models without velocity prediction on nuScenes for long. I am not very sure of your situation from your description. Maybe you can try to set velocity to default value (like nan or 0) as nuScenes box does to avoid the potential problem.
If there exist minor bugs when `with_velocity=False`, PRs are definitely welcome. Thanks for your information.
