### ISSUE TITLE
What's the reason about BackgroundPointsFilter in 3DSSD

### ISSUE THREAD

**Issue by JunrQ** [open-mmlab/mmdetection3d#293]
Hello, thanks for the excellent code. Recently I'm working on 3dssd training on Kitti and I noticed one weird situation about `BackgroundPointsFilter`.

In the released configuration `BackgroundPointsFilter` was added as one data augmentation and the model trained with this  default config works well.

But I found that if I removed this data augmentation the AP will be near 0 while bev ap seems to be right. 

So I wonder what's the motivation about add `BackgroundPointsFilter` data augmentation? Is it necessary for 3dssd when training kitti?

**Comment by ZwwWayne** [comment]
The implementation simply follows the [official implementation of 3DSSD](https://github.com/Jia-Research-Lab/3DSSD). This might because the data will be noisy after GT-sampling.
