### ISSUE TITLE
fd_event_list = self._selector.poll(timeout)

### ISSUE THREAD

**Issue by jiangwenj02** [open-mmlab/mmdetection3d#294]
**Describe the bug**
I have generate scannet dataset according to README in data/scannet. But when i run the command python tools/train.py configs/votenet/votenet_8x8_scannet-3d-18class.py, the program will hang in 2021-02-01 15:03:27,855 - mmdet - INFO - workflow: [('train', 1)], max: 36 epochs. So i press ctrl-c, the program print the info as below:

Traceback (most recent call last):
  File "tools/train.py", line 166, in <module>
    main()
  File "tools/train.py", line 162, in main
    meta=meta)
  File "/home/anaconda/envs/mmtrack/lib/python3.7/site-packages/mmdet/apis/train.py", line 150, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/anaconda/envs/mmtrack/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/anaconda/envs/mmtrack/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/anaconda/envs/mmtrack/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/anaconda/envs/mmtrack/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/home/anaconda/envs/mmtrack/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1034, in _get_data
    success, data = self._try_get_data()
  File "/home/anaconda/envs/mmtrack/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/anaconda/envs/mmtrack/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/anaconda/envs/mmtrack/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/anaconda/envs/mmtrack/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/anaconda/envs/mmtrack/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/home/anaconda/envs/mmtrack/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

**Reproduction**
1. What command or script did you run?
```
python tools/train.py configs/votenet/votenet_8x8_scannet-3d-18class.py
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
No
3. What dataset did you use?
scannet

**Environment**

Python: 3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3: GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.2.1
OpenCV: 4.5.1
MMCV: 1.2.6
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.1
MMDetection: 2.8.0
MMDetection3D: 0.9.0+68787e1

**Comment by Tai-Wang** [comment]
It seems that you are in the process of loading the data. Maybe you can set some breaking points to see what happens in the procedure or where it stops?

**Comment by jiangwenj02** [comment]
I dont do anything. To prevent the data problem, I generate the data 3 times according to README in data/scannet.

**Comment by jiangwenj02** [comment]
> It seems that you are in the process of loading the data. Maybe you can set some breaking points to see what happens in the procedure or where it stops?

I dont do anything in code. To prevent the data problem, I generate the data 3 times according to README in data/scannet.

**Comment by jiangwenj02** [comment]
when i adjust the workers_per_gpu to 0, the problem can be solved.

**Comment by ZwwWayne** [comment]
This seems to be an issue that happens when using pre-fetch. This might happen when the CPU memory is limited.
As the issue is solved by setting `workers_per_gpu=0`, the issue will be closed. Feel free to reopen it if you have any further questions.
