### ISSUE TITLE
[Docs] Training models on v1.0-mini nuscenes dataset

### ISSUE THREAD

**Issue by AbdilahiMJama** [open-mmlab/mmdetection3d#2979]
### Branch

dev-1.x branch https://mmdetection3d.readthedocs.io/en/dev-1.x/

### 📚 The doc issue

Hi, I'm fairly new to deep learning and 3D Object Detection and this is more of a question rather than an issue. When working with the nuscenes v1.0-mini dataset which has 10 scenes, do we need to add the v1.0-trainval and v1.0-test folder like below? Or is the trainval and test included in the v1.0-mini dataset?
![nuscenes](https://github.com/open-mmlab/mmdetection3d/assets/131192606/696ae38d-a0de-428f-9ad9-4337183aafc7)

A final question would be how to train any model on the v1.0-mini dataset. I tried training using the centerpoint pillar02 cyclic 20e nus-3d.py file (the name was too long to type) and it has taken about a day to train? I only have one gpu (RTX 3060 Ti).

Thanks.

**Comment by sunpian1** [comment]
you do not need to include  v1.0-trainval and v1.0-test folder

**Comment by AbdilahiMJama** [comment]
Many thanks.
 I trained a centerpoint pillar model and got this error when testing: AssertionError: Database version not found: data/nuscenes/v1.0-trainval. How would I solve this error?

![trainval](https://github.com/open-mmlab/mmdetection3d/assets/131192606/ba172ae2-6143-4438-a13a-ef5afeb93435)

**Comment by AbdilahiMJama** [comment]
> Many thanks. I trained a centerpoint pillar model and got this error when testing: AssertionError: Database version not found: data/nuscenes/v1.0-trainval. How would I solve this error?
> 
> ![trainval](https://private-user-images.githubusercontent.com/131192606/331280543-ba172ae2-6143-4438-a13a-ef5afeb93435.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4OTkwMjIsIm5iZiI6MTcxNTg5ODcyMiwicGF0aCI6Ii8xMzExOTI2MDYvMzMxMjgwNTQzLWJhMTcyYWUyLTYxNDMtNDQzOC1hMTNhLWVmNWFmZWI5MzQzNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQyMjMyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2YzODUyNmY2YzgxOThjMWZlNDVhYWUwZjc4MjkyNDcxMjMxMGFmZDY1N2VlN2NmNzYwZmQyMjI4Zjk0YzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HFSkGPyhcIHqVHeD4v_kQvd0HyewhBCa0MqPVG1QJpk)

Solved it!

**Comment by Barath19** [comment]
> > Many thanks. I trained a centerpoint pillar model and got this error when testing: AssertionError: Database version not found: data/nuscenes/v1.0-trainval. How would I solve this error?
> > ![trainval](https://private-user-images.githubusercontent.com/131192606/331280543-ba172ae2-6143-4438-a13a-ef5afeb93435.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4OTkwMjIsIm5iZiI6MTcxNTg5ODcyMiwicGF0aCI6Ii8xMzExOTI2MDYvMzMxMjgwNTQzLWJhMTcyYWUyLTYxNDMtNDQzOC1hMTNhLWVmNWFmZWI5MzQzNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQyMjMyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2YzODUyNmY2YzgxOThjMWZlNDVhYWUwZjc4MjkyNDcxMjMxMGFmZDY1N2VlN2NmNzYwZmQyMjI4Zjk0YzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HFSkGPyhcIHqVHeD4v_kQvd0HyewhBCa0MqPVG1QJpk)
> 
> Solved it!

how was this error solve??

**Comment by AbdilahiMJama** [comment]
> > > Many thanks. I trained a centerpoint pillar model and got this error when testing: AssertionError: Database version not found: data/nuscenes/v1.0-trainval. How would I solve this error?
> > > ![trainval](https://private-user-images.githubusercontent.com/131192606/331280543-ba172ae2-6143-4438-a13a-ef5afeb93435.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4OTkwMjIsIm5iZiI6MTcxNTg5ODcyMiwicGF0aCI6Ii8xMzExOTI2MDYvMzMxMjgwNTQzLWJhMTcyYWUyLTYxNDMtNDQzOC1hMTNhLWVmNWFmZWI5MzQzNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQyMjMyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2YzODUyNmY2YzgxOThjMWZlNDVhYWUwZjc4MjkyNDcxMjMxMGFmZDY1N2VlN2NmNzYwZmQyMjI4Zjk0YzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HFSkGPyhcIHqVHeD4v_kQvd0HyewhBCa0MqPVG1QJpk)
> > 
> > 
> > Solved it!
> 
> how was this error solve??

In the nuscenes_dataset.py file (which is under mmdet3d/datasets folder) , comment out the line "v1.0-trainval" at line number 63 and add this line "v1.0-mini".

**Comment by HerrSchnapps** [comment]
> > > > 非常感谢。我训练了一个中心点支柱模型，并在测试时出现此错误：AssertionError：未找到数据库版本：data/nuscenes/v1.0-trainval。我该如何解决这个错误？ 
> > > > ![特雷恩瓦尔](https://private-user-images.githubusercontent.com/131192606/331280543-ba172ae2-6143-4438-a13a-ef5afeb93435.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4OTkwMjIsIm5iZiI6MTcxNTg5ODcyMiwicGF0aCI6Ii8xMzExOTI2MDYvMzMxMjgwNTQzLWJhMTcyYWUyLTYxNDMtNDQzOC1hMTNhLWVmNWFmZWI5MzQzNS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNlQyMjMyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2YzODUyNmY2YzgxOThjMWZlNDVhYWUwZjc4MjkyNDcxMjMxMGFmZDY1N2VlN2NmNzYwZmQyMjI4Zjk0YzhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HFSkGPyhcIHqVHeD4v_kQvd0HyewhBCa0MqPVG1QJpk)
> > > 
> > > 
> > > 解决了！
> > 
> > 
> > 这个错误是怎么解决的？？
> 
> 在 nuscenes_dataset.py 文件（位于 mmdet3d/datasets 文件夹下）中，注释掉第 63 行的“v1.0-trainval”行并添加此行“v1.0-mini”。

![image](https://github.com/user-attachments/assets/169e7e14-453f-43f4-b9fb-1c938d6c922a)
![image](https://github.com/user-attachments/assets/434edb10-5420-4627-bf94-165dd972d284)
It seems the line is not at 63 and after I remove the v1.09trainval, it still doesn't work.
