### ISSUE TITLE
The collapse of the AOS evaluation for 3DSSD

### ISSUE THREAD

**Issue by meng-zha** [open-mmlab/mmdetection3d#302]
The evaluation log of 3DSSD for kitti with default config is below.

> Car AP@0.70, 0.70, 0.70:
bbox AP:96.6093, 89.8885, 89.2153
bev  AP:90.2018, 87.8845, 86.5672
3d   AP:88.7361, 78.3761, 77.1837
aos  AP:0.34, 0.52, 0.88
Car AP@0.70, 0.50, 0.50:
bbox AP:96.6093, 89.8885, 89.2153
bev  AP:96.7122, 90.0748, 89.5853
3d   AP:96.6553, 90.0317, 89.5103
aos  AP:0.34, 0.52, 0.88

The result of aos is so weird that I want to know where there are bugs here.
And how about the AOS result of other models?

**Comment by RolandoAvides** [comment]
Hi! How much time took to train the network?

**Comment by meng-zha** [comment]
> Hi! How much time took to train the network?

13 hours on 2 TITAN RTX with evaluation after every epoch.

**Comment by Tai-Wang** [comment]
Hi @meng-zha , thanks for your information. @encore-zhou We will have a closer look into this problem.

**Comment by meng-zha** [comment]
I find that the predicted alpha angle differs from the gt's alpha angle by PI but I have not figured out the reason.

**Comment by Tai-Wang** [comment]
Maybe some hacks of rotations are not compatible with 3DSSD implementation? Have you ever tried to add PI to check the performance? There does exist a hack for KITTI [here](https://github.com/traveller59/second.pytorch/issues/238).
This problem exists for VoxelNet based models previously like this [issue](https://github.com/traveller59/second.pytorch/issues/238), but the rotation encoding seems not to be used in 3DSSD. But I guess the underlying reason maybe similarly subtle.

**Comment by meng-zha** [comment]
@Tai-Wang I find the code [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/kitti_dataset.py#L615) weird that the limit_yaw is conducted for the second time after decoder. Is this for the issue mentioned above for some models like pointpillars? But it's not suitable for 3DSSD.

**Comment by Tai-Wang** [comment]
> @Tai-Wang I find the code [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/kitti_dataset.py#L615) weird that the limit_yaw is conducted for the second time after decoder. Is this for the issue mentioned above for some models like pointpillars? But it's not suitable for 3DSSD.

`limit_yaw` itself will not influence results because it is just make an equivalent conversion of rotation value. The only code that could make a difference is the hack `yaw = yaw - np.pi`.
