### ISSUE TITLE
[Bug] how save vision results

### ISSUE THREAD

**Issue by yfq512** [open-mmlab/mmdetection3d#3021]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

I can run train and test code, environment is ok

### Reproduces the problem - code sample

demo/pcd_seg_demo.py line 75

### Reproduces the problem - command or script

python demo/pcd_seg_demo.py data/s3dis/instance_mask/Area_6_office_25.bin configs/pointnet2/pointnet2_ssg_2xb16-cosine-50e_s3dis-seg.py work_dirs/pointnet2_ssg_2xb16-cosine-50e_s3dis-seg/epoch_2.pth --out-dir results/

### Reproduces the problem - error message

```
/opt/conda/lib/python3.7/site-packages/mmcv/cnn/bricks/conv_module.py:208: UserWarning: Unnecessary conv bias before batch/instance norm
  'Unnecessary conv bias before batch/instance norm')
Loads checkpoint by local backend from path: work_dirs/pointnet2_ssg_2xb16-cosine-50e_s3dis-seg/epoch_2.pth
08/13 07:13:17 - mmengine - WARNING - Failed to search registry with scope "mmdet3d" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmdet3d" is a correct scope, or whether the registry is initialized.
08/13 07:13:26 - mmengine - WARNING - `Visualizer` backend is not initialized because save_dir is None.
Traceback (most recent call last):
  File "demo/pcd_seg_demo.py", line 85, in <module>
    main()
  File "demo/pcd_seg_demo.py", line 75, in main
    inferencer(**call_args)
  File "/mmdetection3d/mmdet3d/apis/inferencers/base_3d_inferencer.py", line 233, in __call__
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/infer/infer.py", line 215, in __call__
    ) = self._dispatch_kwargs(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmengine/infer/infer.py", line 612, in _dispatch_kwargs
    f'unknown argument {unknown_kwargs} for `preprocess`, '
ValueError: unknown argument {'out_dir', 'no_save_vis', 'no_save_pred'} for `preprocess`, `forward`, `visualize` and `postprocess`
```

### Additional information

* I use  config (configs/pointnet2/pointnet2_ssg_2xb16-cosine-50e_s3dis-seg.py) train s3dis datasets and get a model (work_dirs/pointnet2_ssg_2xb16-cosine-50e_s3dis-seg/epoch_2.pth). 
* Now, I want use this model inference a 3d points data(data/s3dis/instance_mask/Area_6_office_25.bin) and save points data segment results.
* I run it on a cloud server. so I have no display device, I have tried some arguments, out_dir..., but It not work.
wish a helpful idea, thanks!

**Comment by yfq512** [comment]
solved it

**Comment by LeoRainly** [comment]
> solved it解决了

how did you solve if ?
