### ISSUE TITLE
[Bug] Docker image cannot be built

### ISSUE THREAD

**Issue by IvDmNe** [open-mmlab/mmdetection3d#3061]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmdetection3d/issues) and [Discussions](https://github.com/open-mmlab/mmdetection3d/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection3d.readthedocs.io/en/latest/notes/faq.html) but cannot get the expected help.
- [x] The bug has not been fixed in the [latest version (dev-1.x)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.x) or [latest version (dev-1.0)](https://github.com/open-mmlab/mmdetection3d/tree/dev-1.0).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmdetection3d

### Environment

Docker env

### Reproduces the problem - code sample

```bash
docker build -t mmdetection3d docker/
```

### Reproduces the problem - command or script

```bash
docker build -t mmdetection3d docker/
```

### Reproduces the problem - error message

 => [5/6] RUN conda clean --all     && git clone https://github.com/open-mmlab/mmdetection3d.git -b dev-1.x /mmdetection3d     && cd /mmdetection3d     && pip install --no-cache-dir -e .                  361.2s 
 => => #   Downloading attrs-24.1.0-py3-none-any.whl (63 kB)                                                                                                                                                       
 => => #   Downloading attrs-23.2.0-py3-none-any.whl (60 kB)                                                                                                                                                       
 => => #   Downloading attrs-23.1.0-py3-none-any.whl (61 kB)                                                                                                                                                       
 => => #   Downloading attrs-22.2.0-py3-none-any.whl (60 kB)                                                                                                                                                       
 => => #   Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)                                                                                                                                                   
 => => #   Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)

### Additional information

Installer cannot find suitable version for pip packages.

**Comment by joelkny97** [comment]
34 |     # Install MMDetection3D
  35 | >>> RUN conda clean --all \
  36 | >>>     && git clone https://github.com/open-mmlab/mmdetection3d.git -b dev-1.x /mmdetection3d \
  37 | >>>     && cd /mmdetection3d \
  38 | >>>     && pip install --no-cache-dir -e .

29316.2 WARNING: jsonschema 3.2.0 does not provide the extra 'format-nongpl'
29318.0   Downloading jupyter_events-0.6.1-py3-none-any.whl (18 kB)

pip._vendor.resolvelib.resolvers.ResolutionTooDeep: 2000000

**Comment by joelkny97** [comment]
Added `RUN python -m pip install --upgrade pip in Dockerfile` to resolve this issue

**Comment by IvDmNe** [comment]
Indeed, updating pip works. @joelkny97 Thank you!

**Comment by tanmay4269** [comment]
This did work, but why isn't this already in the official Dockerfile?
