### ISSUE TITLE
where can I download the checkpoint file in the demo case. Thanks a lot

### ISSUE THREAD

**Issue by FujieLuo** [open-mmlab/mmdetection3d#309]
python demo/pcd_demo.py demo/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

the .pth file.

**Comment by ZwwWayne** [comment]
In the SECOND of [model zoo](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/model_zoo.md).

**Comment by thelandord** [comment]
> In the SECOND of [model zoo](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/model_zoo.md).



> In the SECOND of [model zoo](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/model_zoo.md).

Sorry, this site is no longer available, is there another way?

**Comment by muhemuhe427** [comment]
this is an available lien:
https://github.com/open-mmlab/mmdetection3d/blob/master/configs/pointpillars
