### ISSUE TITLE
AttributeError: module 'pycocotools' has no attribute '__version__'

### ISSUE THREAD

**Issue by fireflying1019** [open-mmlab/mmdetection3d#312]
mmdetection3d安装完成后，运行测试代码：python demo/pcd_demo.py demo/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth，出现以下报错：
![mmdetetcion_3d](https://user-images.githubusercontent.com/79186188/108591232-9b293f80-73a2-11eb-9410-50e7ba8904e5.png)

**Comment by Tai-Wang** [comment]
Please refer to #102 .

**Comment by Tai-Wang** [comment]
Please feel free to reopen it if there is any further question.
