### ISSUE TITLE
How to visualize the results of trained model?

### ISSUE THREAD

**Issue by bobo199830** [open-mmlab/mmdetection3d#313]
Hi,

First of all, thank you for your excellent work.

Now I can get the result such as *.obj & *.ply, but how could I get Visualization Results without using MeshLab? It seems if I want to use kitti_object_vis I need to transform the *.ply to label such as *.txt, but how could I do this?

I would appreciate it if you could give me some advice.

Look to your reply and wish you have a nice day!

**Comment by Tai-Wang** [comment]
New visualization tools based on open3d will be supported. Please refer to #284 .
