### ISSUE TITLE
Is there any performance gap between different sweeps_num in nuscenes experiments?

### ISSUE THREAD

**Issue by DapengFeng** [open-mmlab/mmdetection3d#32]
https://github.com/open-mmlab/mmdetection3d/blob/a5daf209b4e37ee34a9c0135ede7c0b753f7988d/configs/_base_/datasets/nus-3d.py#L35-L38

**Comment by Tai-Wang** [comment]
> https://github.com/open-mmlab/mmdetection3d/blob/a5daf209b4e37ee34a9c0135ede7c0b753f7988d/configs/_base_/datasets/nus-3d.py#L35-L38

Generally speaking, it is right. You can refer to the nuScenes [paper](https://arxiv.org/abs/1903.11027) for detailed ablation studies in terms of sweeps_num. There exists an obvious performance gain from sweeps_num=1 to 5 and to 10.

**Comment by DapengFeng** [comment]
Thanks for your useful comment.
