### ISSUE TITLE
What are the differences between mmdetection3d and OpenPCDet?

### ISSUE THREAD

**Issue by dashidhy** [open-mmlab/mmdetection3d#33]
As titled. From the README it seems that OpenPCDet is or will be a subset of mmdetection3d. Will you finally merge this two repo or will support different features? Thanks!

**Comment by hellock** [comment]
MMDetection3D and OpenPCDet are two different codebases maintained by different teams. Please also refer to #15 for details.

**Comment by dashidhy** [comment]
Got it. Thank you!
