### ISSUE TITLE
ImportError: cannot import name 'wrap_fp16_model' from 'mmdet.core' 

### ISSUE THREAD

**Issue by FujieLuo** [open-mmlab/mmdetection3d#335]
when I test the module using "python tools/test.py configs/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py work_dirs/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/epoch_4.pth --eval mAP"

python tools/test.py configs/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py work_dirs/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class/epoch_4.pth --eval mAP

I met this error:

Traceback (most recent call last):
File "tools/test.py", line 13, in
from mmdet.core import wrap_fp16_model
ImportError: cannot import name 'wrap_fp16_model' from 'mmdet.core' (/home/fujie/MyCode/mycode_2021_1/mmdetection/mmdet/core/init.py)

**Comment by Tai-Wang** [comment]
Please check whether your mmdetection is the latest version. If yes, you can follow the issue template to provide more details of your case.

**Comment by FujieLuo** [comment]
my env is :

TorchVision: 0.8.2
OpenCV: 4.5.1
MMCV: 1.2.4
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.9.0
MMDetection3D: 0.10.0+ac9a3e8


I can run the demo.py and run the train.py

BUT I canot run the test.py , the error:

(mmlab3d) fujie@fujie-System-Product-Name:~/MyCode/mycode_2021_1/mmdetection3d$ python tools/test.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py checkpoints/epoch_2.pth --eval mAP --options 'show=True' 'out_dir=./data/pointpillars/show_results'
Traceback (most recent call last):
  File "tools/test.py", line 13, in <module>
    from mmdet.core import wrap_fp16_model
ImportError: cannot import name 'wrap_fp16_model' from 'mmdet.core' (/home/fujie/MyCode/mycode_2021_1/mmdetection/mmdet/core/__init__.py)

**Comment by FujieLuo** [comment]
I solve this error by changing the test.py：

the original code in test.py:

`
import argparse
import mmcv
import os
import torch
from mmcv import Config, DictAction
from mmcv.parallel import MMDataParallel, MMDistributedDataParallel
from mmcv.runner import get_dist_info, init_dist, load_checkpoint

from mmdet3d.apis import single_gpu_test
from mmdet3d.datasets import build_dataloader, build_dataset
from mmdet3d.models import build_detector
from mmdet.apis import multi_gpu_test, set_random_seed
from mmcv.runner import wrap_fp16_model
from tools.fuse_conv_bn import fuse_module
`

I changed the :
`from mmdet.core import wrap_fp16_model`
into

`from mmcv.runner import wrap_fp16_model`

**Comment by hanquansanren** [comment]
> 

good trial, thanks for your reply, you help me a lot

**Comment by Ricktho1** [comment]
mmcv.runner has been removed in recent mmcv versions. How to import wrap_fp16_model now?

**Comment by osh71** [comment]
> mmcv.runner has been removed in recent mmcv versions. How to import wrap_fp16_model now?

solved?

**Comment by Liumucan** [comment]
> mmcv.runner has been removed in recent mmcv versions. How to import wrap_fp16_model now?

I meet the same issue. Have you found the solution now?

**Comment by kterakura** [comment]
It is written in the mmcv documentation

https://mmcv.readthedocs.io/en/latest/get_started/api_reference.html?highlight=wrap_fp16_model
