### ISSUE TITLE
Is it possible to detect the objects in real-time?

### ISSUE THREAD

**Issue by ChicagoPARK** [open-mmlab/mmdetection3d#341]
I really wonder know it is possible or not, without process to convert bin format..

Thank you !!

**Comment by Tai-Wang** [comment]
Yes. You can refer to this fast real-time [detector](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/pointpillars).

**Comment by baheytharwat** [comment]
@Tai-Wang I think he meant if he can pass a point cloud as a `numpy array` for example instead of a `.bin file` to the `inference_detector` function. So, he won't need to convert an array to bin file then load the bin file to do inference. 
I am interested in this too, if that is possible

**Comment by AmbarishGK** [comment]
@baheytharwat were you able to figure it out?
