### ISSUE TITLE
Question about 3d NMS

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#342]
As I can see [iou3d_utils](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/ops/iou3d/iou3d_utils.py) is based on [iou3d_nms_utils](https://github.com/open-mmlab/OpenPCDet/blob/master/pcdet/ops/iou3d_nms/iou3d_nms_utils.py) of `OpenPCDet`. The implementation in `OpenPCDet` supports fair `iou` and `nms` with full 3d parametrization: `[x, y, z, dx, dy, dz, heading]`. However the implementation in `mmdetection3d` supports only `[x1, y1, x2, y2, ry]`. This design choice brings a couple of disadvantages. For example, for `VoteNet` on `SUNRGBD` we first predict boxes with angles and then [apply](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/dense_heads/vote_head.py#L627) `nms` to the aligned boxes without angle.

So, my question is, why not to use `nms` from `OpenPCDet` instead of applying lifehacks with `aligned_nms` or `bev_nms`?
Thanks in advance.

**Comment by filaPro** [comment]
Also looks like doc string of [box3d_milticlass_nms](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/post_processing/box3d_nms.py#L8) is incorrect. `mlvl_bboxes_for_nms` real shape is `(N, 5)`, not `(N, 4)`. `mlvl_scores` real shape is `(N, n_classes + 1)`, not `(N,)`.

Also this `+ 1` for background looks like a legacy thing, leading to hacks [here](https://github.com/open-mmlab/mmdetection3d/blob/440e44a0e03d575bf682d35ab2771e88f774f4dc/mmdet3d/models/dense_heads/shape_aware_head.py#L466) and [here](https://github.com/open-mmlab/mmdetection3d/blob/440e44a0e03d575bf682d35ab2771e88f774f4dc/mmdet3d/models/dense_heads/anchor3d_head.py#L494). Can make a PR to fix it, if you think it is needed.

**Comment by ZwwWayne** [comment]
For VoteNet we simply follow the official implementation.
The settings of the coordinates system are a legacy issue, we are working on that to provide a more natural and simpler system in the codebases.
For docstring issues, would you like to create a PR to fix that? Thanks in advance for your kind contribution.
