### ISSUE TITLE
KITTI Dataset preparation

### ISSUE THREAD

**Issue by thomas-w-nl** [open-mmlab/mmdetection3d#35]
Hi,

Where does the `create_data.py` expect the kitti dataset to be stored? And does it need to be modified to a specific folder structure? Is it necessary to download all of KITTI? The [docs](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/getting_started.md#prepare-datasets) are not very clear. From what I can understand the data needs to be split into training and test folders for the prepare script, but i thought that is what it was supposed to do for me.

Running `python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti` with the dataset in `data/kitti/2011_09_26/` results in
`ValueError: file not exist: training/velodyne/000000.bin` but the KITTI dataset never includes a `training` folder

**Comment by Tai-Wang** [comment]
From the printed message I guess you may download the KITTI raw data. Instead, please download the image/velodyne/labels/calibration data for 3D detection from this [link](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d).
> Hi,
> 
> Where does the `create_data.py` expect the kitti dataset to be stored? And does it need to be modified to a specific folder structure? Is it necessary to download all of KITTI? The [docs](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/getting_started.md#prepare-datasets) are not very clear. From what I can understand the data needs to be split into training and test folders for the prepare script, but i thought that is what it was supposed to do for me.
> 
> Running `python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti` with the dataset in `data/kitti/2011_09_26/` results in
> `ValueError: file not exist: training/velodyne/000000.bin` but the KITTI dataset never includes a `training` folder

**Comment by thomas-w-nl** [comment]
Thanks! Putting these in the `data/kitti/` folder works perfectly!

**Comment by gaoyuchris** [comment]
As for the image data, do I need to download the right color images?

**Comment by NIHALNAVALE** [comment]
Help I keep getting this error. I have the Kitti dataset with testing and training folders.

mmdetection3d$ python3 tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti
Traceback (most recent call last):
  File "tools/create_data.py", line 8, in <module>
    from tools.dataset_converters import indoor_converter as indoor
ModuleNotFoundError: No module named 'tools.dataset_converters'

**Comment by astehelen** [comment]
Help i also have same problem 
  File "tools/create_data.py", line 7, in <module>
    from tools.dataset_converters import indoor_converter as indoor
ModuleNotFoundError: No module named 'tools.dataset_converters'
