### ISSUE TITLE
pytorch 1.7.0 cuda 11.0 setup Error

### ISSUE THREAD

**Issue by panfengsu** [open-mmlab/mmdetection3d#358]
I need to setup mmdetection3D in the environment  for pytorch1.7.0 cuda11.0.I modify Dockerfile:
ARG PYTORCH="1.7.0"
ARG CUDA="11.0"
ARG CUDNN="8"
FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel
ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"
RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Install MMCV
RUN pip install mmcv-full==latest+torch1.7.0+cu110 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html

But I get error:
ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mmdetection3d/setup.py'"'"'; __file__='"'"'/mmdetection3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps

/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(242): error: class "at::Tensor" has no member "max_values"
/mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: type name is not allowed
 /mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: expected an expression

Do you test setup mmdetection in the  the environment  for pytorch1.7.0 cuda11.0?Can you give some suggestions on this issue？Thanks

**Comment by ConnorMcShane** [comment]
I am having the same issue.

**Comment by Tai-Wang** [comment]
Please refer to #362 .

**Comment by panfengsu** [comment]
@Tai-Wang I compile tag  v0.10.0 and do not get error, thanks.

**Comment by Tai-Wang** [comment]
> @Tai-Wang I compile tag v0.10.0 and do not get error, thanks.

Welcome. So it seems like a compatibility problem introduced by PRs #318 and #326 . Thanks for your feedback.
Close this issue due to duplication.

**Comment by superchenyan** [comment]
> I need to setup mmdetection3D in the environment for pytorch1.7.0 cuda11.0.I modify Dockerfile:
> ARG PYTORCH="1.7.0"
> ARG CUDA="11.0"
> ARG CUDNN="8"
> FROM pytorch/pytorch:${PYTORCH}-cuda${CUDA}-cudnn${CUDNN}-devel
> ENV TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX"
> ENV TORCH_NVCC_FLAGS="-Xfatbin -compress-all"
> ENV CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"
> RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6
> && apt-get clean
> && rm -rf /var/lib/apt/lists/*
> # Install MMCV
> 
> RUN pip install mmcv-full==latest+torch1.7.0+cu110 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html
> 
> But I get error:
> ERROR: Command errored out with exit status 1:
> command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mmdetection3d/setup.py'"'"'; **file**='"'"'/mmdetection3d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' develop --no-deps
> 
> /mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(242): error: class "at::Tensor" has no member "max_values"
> /mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: type name is not allowed
> /mmdetection3d/mmdet3d/ops/voxel/src/scatter_points_cuda.cu(249): error: expected an expression
> 
> Do you test setup mmdetection in the the environment for pytorch1.7.0 cuda11.0?Can you give some suggestions on this issue？Thanks

I meet the same problem, cuda 11.0, torch1.7.1,   when install mmcv-full, I use  the followed commend:
 MMCV_WITH_OPS=1 MMCV_CUDA_ARGS='-gencode=arch=compute_80,code=sm_80' pip install -e
 it sloved, the mmcv hasi sucessfully installed.
 Does it works for mmdetction3d? I don't know how to set '-gencode=arch=compute_80,code=sm_80'  when install mmdetection3d
