### ISSUE TITLE
ObjectSample with option sample_2d=True

### ISSUE THREAD

**Issue by thuyngch** [open-mmlab/mmdetection3d#36]
[ObjectSample](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/transforms_3d.py#L115) in data pipeline has option `sample_2d` for pasting 2D image patches to the current image. However, [DataBaseSampler](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/dbsampler.py#L182) does not implement this feature.

Do you plan to support this?
Thanks!

**Comment by ZwwWayne** [comment]
Yes, this will be supported in the next month.

**Comment by YangHan-Morningstar** [comment]
Hi, have you supported sample_2d in ObjectSampler? I haven't found it

**Comment by YangHan-Morningstar** [comment]
> Yes, this will be supported in the next month.

Hi, have you supported sample_2d in ObjectSampler? I haven't found it

**Comment by Byte247** [comment]
anyone looking, you can find it here: https://github.com/open-mmlab/mmdetection3d/pull/327/files
