### ISSUE TITLE
Confused about the anchor settings in fpn neck when using nuScenes dataset

### ISSUE THREAD

**Issue by SeanZhang777** [open-mmlab/mmdetection3d#366]
I'm confused about the anchor settings in fpn neck when using nuScenes dataset, could you tell me why setting anchor sizes like this?
https://github.com/open-mmlab/mmdetection3d/blob/440e44a0e03d575bf682d35ab2771e88f774f4dc/configs/_base_/models/hv_pointpillars_fpn_nus.py#L51-L56

**Comment by ZwwWayne** [comment]
This is an empirical setting and may not be the best hyper-parameters.
As the scale of objects ranges from 0.5x0.5 to 4 x 8，we design the anchor to have different aspect ratios and scales to cover all the objects. Thus, in the last pyramid level, the biggest anchor will be [0.8660*4, 2.5981*4, 1.*4].
