### ISSUE TITLE
AttributeError:modeule 'pycocotools' has no attribute '__version__'

### ISSUE THREAD

**Issue by liuhuaijjin** [open-mmlab/mmdetection3d#369]
Run demo to report an error:AttributeError:modeule 'pycocotools' has no attribute '__version__'，do not know how to solve please help me

**Comment by wHao-Wu** [comment]
Hi @liuhuaijjin  ,
Have you ever tried  `pip uninstall pycocotools mmpycocotools`, then `pip install mmpycocotools`, which have been mentioned in docs/faq.md ?

This import problem will be fixed in the future.

**Comment by wHao-Wu** [comment]
@liuhuaijjin 
Please refer to the following link:
https://mmdetection3d.readthedocs.io/en/latest/faq.html#mmcv-mmdet-mmdet3d-installation

**Comment by liuhuaijjin** [comment]
OK, thank you very much for your reply




---Original---
From: "Wenhao ***@***.***&gt;
Date: Sun, Mar 21, 2021 18:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmdetection3d] AttributeError:modeule 'pycocotools' has no attribute '__version__' (#369)




 
Hi @liuhuaijjin  ,
 Have you ever tried  pip uninstall pycocotools mmpycocotools, then pip install mmpycocotools, which have been mentioned in docs/faq.md ?
 
This import problem will be fixed in the future.

**Comment by liuhuaijjin** [comment]
Thank you very much.




---Original---
From: "Wenwei ***@***.***&gt;
Date: Mon, Mar 22, 2021 15:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [open-mmlab/mmdetection3d] AttributeError:modeule 'pycocotools' has no attribute '__version__' (#369)




 
Closed #369.
