### ISSUE TITLE
How to get AP@R40 results on KITTI dataset? 

### ISSUE THREAD

**Issue by Michael-Shaw** [open-mmlab/mmdetection3d#372]
hv_second_secfpn_6x8_80e_kitti-3d-car.py

Car AP@0.70, 0.70, 0.70:
bbox AP:95.9276, 89.8848, 88.7942
bev  AP:89.9855, 87.7769, 86.0311
3d   AP:88.6526, 78.2292, 76.8670
aos  AP:95.86, 89.68, 88.39
Car AP@0.70, 0.50, 0.50:
bbox AP:95.9276, 89.8848, 88.7942
bev  AP:96.0137, 90.0790, 89.3071
3d   AP:95.9631, 90.0326, 89.1784
aos  AP:95.86, 89.68, 88.39

Are the results published here based on AP@R11?  If so, how can I get the results based on AP@40? Looking forward to your reply.

**Comment by Tai-Wang** [comment]
Yes, the results are AP@R11. To get AP@R40, you just need to modify this [function](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/evaluation/kitti_utils/eval.py#L571) to calculate the AP from 40 points.
For example, modify it as:
```
def get_mAP(prec):
    sums = 0
    for i in range(1, prec.shape[-1]):
        sums = sums + prec[..., i]
    return sums / 40 * 100
```
