### ISSUE TITLE
Deploy the spconv-based model in C++

### ISSUE THREAD

**Issue by maudzung** [open-mmlab/mmdetection3d#373]
Have you ever deployed the models including the `spconv` libs (such as `SECOND`, `Part-A2`) in C++? Are there examples/tutorials on converting the **`spconv-based`** pre-trained models to `torchscript`, or `onnx` format?
Thank you so much!

**Comment by ZwwWayne** [comment]
Hi @maudzung ,
For now, we have not done that. But we will try it this year and will first start with PointPillars.
