### ISSUE TITLE
How to convert the prediction from PLY points to objects

### ISSUE THREAD

**Issue by alanwanga** [open-mmlab/mmdetection3d#375]
Hi, thanks for the nice work.

The generated prediction is set of points in PLY:

```
[-29.350431442260742, 31.011640548706055, -0.14925014972686768]
[-29.350431442260742, 31.011640548706055, 1.4640859365463257]
...
[-25.711950302124023, 32.56251525878906, 1.4640859365463257]
```

How can we group them together to make some objects? e,g for each object:

```
"position": {
	"x": -8.53696158312415,
	"y": -1.1906569117067272,
	"z": 0.7385136614991175
},
"rotation": {
	"x": 0,
	"y": 0,
	"z": 0.03161379940268021
},
"size": {
	"x": 0.7091922786260889,
	"y": 0.6572706935123045,
	"z": 1.6048293739568908
},
```

Any examples would be very appreciated.

**Comment by ZwwWayne** [comment]
Please @Wuziyi616 to have  a look.

**Comment by Wuziyi616** [comment]
@alanwanga Hi! What do you mean by "grouping them"? Do you mean group the points within each predicted bounding box to form some separated objects? Or do you mean transforming the PLY format of boxes into the format you mentioned (box vertex, rotation and box size)?

**Comment by alanwanga** [comment]
@Wuziyi616 thanks for the comment. I'd like to transform the prediction results into objects of box vertex position, rotation and size just like what I mentioned. Since there are only positions in PLY, I think the first step is to group them into separated objects, isn't it?

**Comment by Wuziyi616** [comment]
I got it! You can have a look [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/visualizer/show_result.py#L29) on how we save the prediction boxes. We save each bounding box as a rectangular mesh with 8 vertices and 6 faces. So every eight points should form a bounding box of one object (points[0:8], points[8:16], etc.).
I think the size of the box can be simply obtained by subtracting max and min coordinates if the boxes are axis-aligned. If not, you can calculate the rotation angle first (simply arctan I think).

**Comment by Wuziyi616** [comment]
@alanwanga feel free to reopen this issue if you have further questions!
