### ISSUE TITLE
What's the purpose of this line inside for loop

### ISSUE THREAD

**Issue by zehuichen123** [open-mmlab/mmdetection3d#383]
https://github.com/open-mmlab/mmdetection3d/blob/4eed122de544dd7ca9582642bbdcfac03fb7debc/mmdet3d/models/voxel_encoders/voxel_encoder.py#L166

**Comment by Tai-Wang** [comment]
You need to change the `list` to `ModuleList` to make it work as a network in pytorch.

**Comment by zehuichen123** [comment]
Yes, I mean why does this line inside for-loop? If we just want to convert list to ModuleList lastly, just write it outside for loop, right?

**Comment by Tai-Wang** [comment]
> Yes, I mean why does this line inside for-loop? If we just want to convert list to ModuleList lastly, just write it outside for loop, right?

Exactly. Writing it outside of loop should be more efficient. The current implementation does not influence result so we do not notice this problem. Have you ever changed it to validate it? If no influence on the result as expected, I think a quick PR will fix it.

**Comment by ZwwWayne** [comment]
Hi @zehuichen123 ,
Thanks for your kind suggestion. Would you like to create a PR to fix that?
