### ISSUE TITLE
Clarifications for CenterPoint results

### ISSUE THREAD

**Issue by haotian-liu** [open-mmlab/mmdetection3d#395]
Hi, thank you for your implementation of CenterPoint. However, I have a few questions regarding the [results](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/centerpoint/README.md#centerpoint) section.

(1) On which split are those numbers evaluated? Is it the validation split of nuScenes dataset?
(2) Is config "SECFPN + pillar (0.2) w/o DCN, w/cnms" in this table the same as the config in the CenterPoint paper Table 6. last row "pillar, center-based"? I noticed a difference of 1.2 in AP. Is there any other differences in the configuration?

Thank you!

**Comment by tianweiy** [comment]
(1) it is validation split 

(2) cnms <- this means center nms which is in our last version. I just found it is quite slow on GPU so I removed it in the current version of the paper.

**Comment by haotian-liu** [comment]
Thank you for your reply!

For the second point, does it mean that this row `above w/o circle nms | pillar (0.2) | ✗ | ✗ |   |   | 49.12 | 59.66` corresponds to the result in paper Table 6. last row `pillar, center-based, 50.3, 60.2`? There is a 1.2 AP gap between them, and what is the difference in the configuration?

Thank you again for the great work!

**Comment by tianweiy** [comment]
check my reply above

**Comment by haotian-liu** [comment]
Thank you for the update!

**Comment by haotian-liu** [comment]
Thank you for the update. 

(1) For PFN, do you mean filters [here](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/centerpoint_02pillar_second_secfpn_nus.py#L9) is `[64]` instead of `[64,64]`?

(2) For maximum number of pillars, do you mean [here](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/centerpoint_02pillar_second_secfpn_nus.py#L5)?

Any reasons for doing the parameter change? Thank you again!

**Comment by tianweiy** [comment]
(1) (2) yes. 

Not much reason for the first one, just small tweaks on the way. 

For the second one, it is just if you set a large enough max_voxel, it will basically use all non-empty voxels and doesn't loss any information. It may be slightly slower (due to larger amounts of voxels)

**Comment by haotian-liu** [comment]
Thank you for the clarification!
