### ISSUE TITLE
3DSSD all 3 kitti classes

### ISSUE THREAD

**Issue by RolandoAvides** [open-mmlab/mmdetection3d#400]
Hi!

Is 3DSSD model configuration able to train with the KITTI 3 main classes?

Thanks in advance!

**Comment by junhaozhang98** [comment]
Thanks for your interests in MMDetection3d! We follow the official implementation with only 'Car' class to train our released model. You can add other classes to train the model. However, you may need to explore by yourself which hyperparameters are more suitable for other classes.

**Comment by RolandoAvides** [comment]
Thanks! Do you think this change in the 3DSSD python configuration file would be sufficient for a simple initial training?

```
class_names = ['Pedestrian', 'Cyclist', 'Car']
```

**Comment by Tai-Wang** [comment]
Close due to inactivity.
