### ISSUE TITLE
nuImage relation parameters

### ISSUE THREAD

**Issue by Shaoqing26** [open-mmlab/mmdetection3d#401]
a general question of nuImage models,:
   HTC | R-50 | IN+COCO-20e,is that means  backbone is first pre-trained on ImageNet, and then the detector is pre-trained on COCO train2017 dataset by 20 epochs?and how many epochs is the model training on nuImage dataset?

AND Is there has any plan to fix it and prove traning code of nuImage dataset,I found that there just has inference code in project,and also have no evaluate code,is there any plan to complete it?

**Comment by ZwwWayne** [comment]
Yes, the number of epochs on nuImages dataset are indicated by `lr schedule` column.

**Comment by THU17cyz** [comment]
@Shaoqing26 

You can take a look at the [tutorials](https://mmdetection3d.readthedocs.io/en/latest/tutorials/config.html) to understand the configs.

For example, [`htc_r50_fpn_1x_nuim.py`](https://github.com/open-mmlab/mmdetection3d/blob/e38131857b0ee7e20a15e890b3ca6d80c42d80a1/configs/nuimages/htc_r50_fpn_1x_nuim.py#L1) inherits from [`htc_without_semantic_r50_fpn_1x_nuim.py`], which inherits the learning schedule from [`mmdet_schedule_1x.py`](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/schedules/mmdet_schedule_1x.py), where you can find the answer to your first question.

As for your second question, please refer to @ #402 .
