### ISSUE TITLE
Semantic segmentation on nuImage dataset

### ISSUE THREAD

**Issue by Shaoqing26** [open-mmlab/mmdetection3d#402]
First,Thanks the exllent job in this open source project.
and ,I found there has only have instance segmantation on nuImage dataset,and few training details,but semantic segmantation semantic is also popular and helpful reserch work,is there has any plan to add semantic segmentation modals?

also there have no training and evaluation code for nuImage dataset,is will complete it recently?

**Comment by ZwwWayne** [comment]
The training and evaluation code for instance segmentation is `train.py` and `test.py`. You can use them to train/test nuImages models as other 3D detectors in MMDet3D because MMDet3D inherits MMDet.
For semantic segmentation, we will release examples this month, using MMSegmentation. Please stay tuned.

**Comment by THU17cyz** [comment]
> The training and evaluation code for instance segmentation is `train.py` and `test.py`. You can use them to train/test nuImages models as other 3D detectors in MMDet3D because MMDet3D inherits MMDet.
> For semantic segmentation, we will release examples this month, using MMSegmentation. Please stay tuned.

As to help you understand how this works, please note that our `train.py` uses a function [`build_detector`](https://github.com/open-mmlab/mmdetection3d/blob/e38131857b0ee7e20a15e890b3ca6d80c42d80a1/tools/train.py#L173). This function consists of [`build`](https://github.com/open-mmlab/mmdetection3d/blob/e38131857b0ee7e20a15e890b3ca6d80c42d80a1/mmdet3d/models/builder.py#L48) from [mmdet](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/builder.py#L15), which uses MMCV Registry. Please then refer to the [tutorial](https://mmcv.readthedocs.io/en/latest/registry.html) of MMCV Registry.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
