### ISSUE TITLE
question about points_to_voxel

### ISSUE THREAD

**Issue by gillbam** [open-mmlab/mmdetection3d#406]
Hi,

Thanks for your great work.

I noticed that you modified the spconv code, one of the modifications is [https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/ops/spconv/include/spconv/point2voxel.h](url). This is related to the voxelization, line 73:
`if (voxel_num >= max_voxels) break;`

while the original code of spconv:
```
if (voxel_num >= max_voxels)
        continue;
```

Same change happens in your python version voxel_generator.py. As I understood, when we have enough number of voxels, we should stop making new voxels, but this does not mean we should stop traversing the remaining points. Because some of the remaining points can locate in the existing voxels. **break** will kill the entire loop and ignore those points. **continue** ensures  that all points can be checked and allocated in the corresponding voxels if necessary.

In my dataset, if I use **break** , the total number of points in my voxelized data is about 20% less than the **continue** version.  So I think the current version of your code generates incomplete voxelized data.

**Comment by gillbam** [comment]
Can somebody explain this......

**Comment by Tai-Wang** [comment]
Hi @gillbam , thanks for your information. It seems a legacy issue because the original spconv fixed this problem with this [PR](https://github.com/traveller59/spconv/commit/54faa1c64af9e10ae62592111e486980ba6084da#diff-6072ee1adfbe57c0eab67b9c4197de7eedce4b3bb0596bd681233f34735b31b1). Could you please create a PR to fix it? also the python version?

**Comment by gillbam** [comment]
> Hi @gillbam , thanks for your information. It seems a legacy issue because the original spconv fixed this problem with this [PR](https://github.com/traveller59/spconv/commit/54faa1c64af9e10ae62592111e486980ba6084da#diff-6072ee1adfbe57c0eab67b9c4197de7eedce4b3bb0596bd681233f34735b31b1). Could you please create a PR to fix it? also the python version?

Thanks for your reply. Sure, I'll update those files later.

**Comment by Tai-Wang** [comment]
Close #406 via #423.

**Comment by Tai-Wang** [comment]
Fixed in #423
