### ISSUE TITLE
Question about lidar box

### ISSUE THREAD

**Issue by thangvubk** [open-mmlab/mmdetection3d#409]
I have a question related to lidar box. In lidar system, Ox has yaw of pi/2, Oy has yaw of pi. If i have a box described in below figure. The yaw value of the box would be theta1 or theta2. 

Besides, it would be nice if some docs related to coordinate system and convention in mmdet3d are provided.
![image](https://user-images.githubusercontent.com/20570053/113575708-43484e80-9659-11eb-92a9-8edc60347a06.jpeg)

**Comment by THU17cyz** [comment]
This depends on which side of the box is _w_. If the longer side is, then yaw should be theta2; else, yaw should be theta2 - pi/2, which is theta1.

**Comment by THU17cyz** [comment]
Please refer to #410 for more details.

**Comment by Tai-Wang** [comment]
Feel free to reopen it if there is any further question.

**Comment by THU17cyz** [comment]
Just updated the docstrings to avoid confusion.
