### ISSUE TITLE
Should use `isinstance` to determine whether the detector is a 2D detector or a 3D detector.

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmdetection3d#419]
Should use `isinstance` to determine whether the detector is a 2D detector or a 3D detector.

_Originally posted by @ZwwWayne in https://github.com/open-mmlab/mmdetection3d/pull/408#discussion_r608511426_

**Comment by xiliu8006** [comment]
It was fixed by PR #542
