### ISSUE TITLE
Errors when compiling mmdetection3d

### ISSUE THREAD

**Issue by jytime** [open-mmlab/mmdetection3d#42]
Hi,

Thanks for your work. When compiling mmdet3d,  I have successfully completed the previous operations (e.g., install mmcv). However,  once I try to compile mmdet3d by 'pip install -v -e .', it would encounter an error with regard to SPconv. It looks like _nvcc_ is not correctly included. I have checked that nvcc is activated using 'nvcc -V'. 

My environment is: Cuda 10.1, PyTorch 1.5.0, Python 3.7, GCC 5.3. Any suggestion is welcome. 

![image](https://user-images.githubusercontent.com/37647961/88456633-b2a65580-ceb1-11ea-90cc-a2c32b466a27.png)
![image](https://user-images.githubusercontent.com/37647961/88456653-d2d61480-ceb1-11ea-90f8-832c420a7ab3.png)

Best,
Jianyuan

**Comment by Tai-Wang** [comment]
Please follow the template for 'error report' to redescribe the issue. More information is needed to debug.
Note: Since you have not successfully installed mmdet3d, you can print the environment from mmdet by running `python mmdet/utils/collect_env.py`.

**Comment by ZwwWayne** [comment]
It seems that `nvcc` is installed but it is not fully included. You need to set the following variables in your environment: `CUDA_ROOT`, `CUDA_HOME`, `LD_LIBRARY_PATH`, and `PATH`.

**Comment by ZwwWayne** [comment]
Furthermore, have you successfully installed `mmcv-full`?

**Comment by jytime** [comment]
Thanks for your quick reply. The problem is solved after I rebuilt the conda env totally and chose pytorch 1.3 instead of 1.5. It is weird that why I could successfully install mmcv-full but not mmdet3d. I guess it was raised by wrong pointers from various conda envs.
