### ISSUE TITLE
ImportError:'ball_query_ext.cpython-37m-x86_64-linux-gnu.so'

### ISSUE THREAD

**Issue by J-nan816** [open-mmlab/mmdetection3d#420]
Thanks for your nice work at first. Some errors in installing here.

File "/home/an/mmdetection3d-master/mmdet3d/ops/__init__.py", line 5, in <module>
    from .ball_query import ball_query
  File "/home/an/mmdetection3d-master/mmdet3d/ops/ball_query/__init__.py", line 1, in <module>
    from .ball_query import ball_query
  File "/home/an/mmdetection3d-master/mmdet3d/ops/ball_query/ball_query.py", line 4, in <module>
    from . import ball_query_ext
ImportError: /home/an/mmdetection3d-master/mmdet3d/ops/ball_query/ball_query_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexINS2_4HalfEEEEEPKNS_6detail12TypeMetaDataEv

When I run 'ball_query.py',it comes out
File "ball_query.py", line 4, in <module>
    from . import ball_query_ext
ImportError: attempted relative import with no known parent package

Install setting
cuda = 10.1
pytorch = 1.5.0
mmcv-full = 1.3.0
mmdet = 2.5.0
mmdet3d = 0.11.0
I have compiled it a few times and I think I have used the correct steps.
I am really hard to solve the problem, hope your help, thanks you very much!

**Comment by Tai-Wang** [comment]
Have you successfully installed mmdet3d with no errors? Please follow the issue template to describe your situation. The current information is not enough for us to help you debug.

**Comment by J-nan816** [comment]
Thank you for your attention to my question.
 
The following is the code that I ran when I installed it, and I put some screenshots of the results of the operation in the attachment.
 
If necessary, I hope to communicate privately, my QQ: 1530404947.
 
Thank you very much. 
 
&nbsp;
 
conda create -n mmlab python=3.7 -y
 
conda activate mmlab
 
conda install pytorch==1.5.0 cudatoolkit=10.1 torchvision==0.6.0 -c pytorch
 
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.5.0/index.html
 
Manually download the folder “mmdetection-master” and “mmdetection3d-master”.
 
cd mmdetection
 
pip install -r requirements/build.txt
 
pip install -v -e .&nbsp; &nbsp;&nbsp; (I think my question is here.)
 
cd mmdetection3d
 
pip install -v -e .&nbsp; &nbsp; &nbsp;(I think my question is here.)





I got two questions as follows:

ImportError: /home/an/mmdetection3d-master/mmdet3d/ops/ball_query/ball_query_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIN3c107complexINS2_4HalfEEEEEPKNS_6detail12TypeMetaDataEv




File "/share/home/jinan/nan/mmdetection-master/mmdet/datasets/coco.py", line 21, in <module&gt;
&nbsp; &nbsp; assert pycocotools.__version__ &gt;= '12.0.2'
AttributeError: module 'pycocotools' has no attribute '__version__'





Please check the attachment for more specific information.Wish you a good day~








Looking forward to your reply.


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "open-mmlab/mmdetection3d"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 晚上7:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdetection3d] ImportError:'ball_query_ext.cpython-37m-x86_64-linux-gnu.so' (#420)





 
Have you successfully installed mmdet3d with no errors? Please follow the issue template to describe your situation. The current information is not enough for us to help you debug.

**Comment by Tai-Wang** [comment]
Please follow the template for 'Reimplementation Questions' (You can see it when creating a new issue) to redescribe. Finishing it can help us get the most important information about your building environment.

**Comment by Wuziyi616** [comment]
@J-nan816 Hi! I have encountered similar questions before (not sure if it's the same with yours). For the first question, try downloading the source code of MMDet and MMDet3d from the **release** page of their repos because they are more stable. For the second question, you should uninstall pycocotools, and then install mmpycocotools by running:
```
pip uninstall pycocotools
pip install mmpycocotools
```
You may also need to adjust the version of numpy (I forgot, maybe numpy-19.5 works?).

**Comment by Tai-Wang** [comment]
Close due to inactivity.

**Comment by wHao-Wu** [comment]
@J-nan816 

There may be a solution for your first question:

If you pull some updates from any of mmcv, mmdet, mmdet3d, or if you update the environment like pytorch or cuda, please remove the ./build folder in mmdetection3d:

```shell
pip uninstall mmdet3d
rm -rf ./build
find . -name "*.so" | xargs rm
```

Then recompiling from scratch as described in the instructions: https://mmdetection3d.readthedocs.io/en/latest/getting_started.html
