### ISSUE TITLE
Question in MVXNet point fusion

### ISSUE THREAD

**Issue by kathy-lee** [open-mmlab/mmdetection3d#424]
Hi,
I am reading the implementation of MVXNet model, and noted in class PointFusion, the feature fusion is done as follows:
`fuse_out = img_pre_fuse + pts_pre_fuse`. But in the paper of MVXNet, the point fusion does concat of img features and pts features, so I am confused with this key step, could any help me to make this clear? Many thanks in advance!

**Comment by ZwwWayne** [comment]
Concatenation or direct addition does not bring essential difference, so we use a simple way. You can replace this part by concatenation, the results does not change much.

**Comment by kathy-lee** [comment]
Thanks a lot for your reply, that's very helpful.
