### ISSUE TITLE
fatal error: cuda_runtime_api.h: No such file or directory

### ISSUE THREAD

**Issue by tryphena-p** [open-mmlab/mmdetection3d#427]
fatal error: cuda_runtime_api.h: No such file or directory
I get this error while trying to install and build mmdetection3d in my system.

**Comment by Tai-Wang** [comment]
Please check the cuda and GPU driver on your machine. You can follow the instructions (like running the collect_env.py) given in the issue template of reimplementation.

**Comment by Tai-Wang** [comment]
Close due to inactivity.

**Comment by zhang787jun** [comment]
> fatal error: cuda_runtime_api.h: No such file or directory I get this error while trying to install and build mmdetection3d in my system.

```shell
 export CUDA_HOME='/usr/local/cuda'
python setup.py develop
```
