### ISSUE TITLE
How to train with my own lidar dataset?

### ISSUE THREAD

**Issue by minghaohsu410168** [open-mmlab/mmdetection3d#429]
Hello,

Thank you for the nice repo, I want to train with my custom lidar data (Velodyne VLP 16) for the PointPillars model, how could I label the object (People, Car) like Kitti dataset?

I have only a VLP 16 lidar and try not to have camera, how could I do? I have collected several .pcd file and can convert to .bin file

**Comment by Tai-Wang** [comment]
Please refer to #334 and #260 , or you can set the `calib` and `image` information to be something random.

**Comment by minghaohsu410168** [comment]
Thank you for your quick reply,

But would you please tell me how to implement a dataset class or a data converter in detail? It means to create the `kitti_converter.py ` with only velodyne and label information?
Or are there any tutorial for reference?

**Comment by minghaohsu410168** [comment]
@Tai-Wang,
Set the calib and image information to be something random means I can set the two information to be 0 or other value if I don' t use it?

**Comment by Tai-Wang** [comment]
Yes, you can simply set them share the shape with those used in KITTI. Because you do not use them, I guess it can work well in your case.

**Comment by Tai-Wang** [comment]
> Thank you for your quick reply,
> 
> But would you please tell me how to implement a dataset class or a data converter in detail? It means to create the `kitti_converter.py ` with only velodyne and label information?
> Or are there any tutorial for reference?

Dataset class refers to files like [this](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/kitti_dataset.py). It is the basic API to read the data and do evaluation. Data converter is those in `tools/data_converter/` that is used to convert data to compact infos. You just need to implement these two or either of them to achieve a compatible data reader.

**Comment by minghaohsu410168** [comment]
> Yes, you can simply set them share the shape with those used in KITTI. Because you do not use them, I guess it can work well in your case.

So can I just replace the file in velodyne and label_2 dictionary to my own bin file and label file so that I can run create_data and train simply?
Have you recommend some label tool to label my data like KITTI format?

**Comment by Tai-Wang** [comment]
You can have a try. I do not know exactly whether there will be any unexpected errors.
As for the label tool, although I have done a related [project](https://arxiv.org/abs/2011.10174), it is typically inconvenient to open source such tools because there are many commercial use about it. So I guess you need to find some paid services provided by those annotation companies if you would like to obtain high-quality labels.

**Comment by minghaohsu410168** [comment]
Very thank you for your advice, it helped me a lot. I will try annotate my data first.

**Comment by clytze0216** [comment]
> Very thank you for your advice, it helped me a lot. I will try annotate my data first.

Hi@minghaohsu410168 
Did you success to train with your own lidar dataset?
Could I just replace the file in velodyne and label_2 dictionary to my own bin file and label file?
Looking forward to your reply ! Thanks a lot!

**Comment by Wuziyi616** [comment]
For those who are interested in annotation tools of LiDAR dataset, can have a look at this [repo](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor)

**Comment by INF800** [comment]
> For those who are interested in annotation tools of LiDAR dataset, can have a look at this [repo](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor)

+1 One of very good tools

**Comment by INF800** [comment]
> For those who are interested in annotation tools of LiDAR dataset, can have a look at this [repo](https://github.com/Hitachi-Automotive-And-Industry-Lab/semantic-segmentation-editor)

@Wuziyi616 Can you help me with what to do once I generate annotation PCD file using the tool?
