### ISSUE TITLE
Adapting Velodyne HDL32e data to KITTI format

### ISSUE THREAD

**Issue by mihsamusev** [open-mmlab/mmdetection3d#432]
Hi, thanks for your great work. Id like to use `mmdet3d.apis` to run a pre-trained model on my own dataset that was collected with HDL32e which is 2-3 times less dense. My dataset was collected from a static pole but i can translate and rotate it to any coordinate system. 
If XY is parallel to a ground plane, should i translate the dataset so that lidar is at the same height as in KITTI, or it is okay to edit 
`point_cloud_range=[0, -39.68, -3, 69.12, 39.68, 1]` to fit my dataset? I guess those are `[xmin, ymax, zmin, xmax, ymax, zmax]`?

Will those interventions affect inference using a checkpoint from a model zoo? I'm planning to use one of the `hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class`

Do i understand correctly that `inference_detector` of `mmdet3d.apis` uses the test pipeline defined in config file?

Thats how my cloud looks like when i transform the coordinate system to ground plane.
![image](https://user-images.githubusercontent.com/40422737/114300306-f5e83900-9abf-11eb-8808-f48a9ab9b623.png)

thanks

**Comment by Tai-Wang** [comment]
Yes, you can have a try. Nevertheless, current 3D detectors always have the problem of domain adaptation, so the result can be reasonable but maybe not very good.
You can also try some models for nuScenes and Lyft, where the point cloud is collected via 32-line LiDARs while merged in 10 consecutive frames.

**Comment by Tai-Wang** [comment]
Close due to inactivity.
