### ISSUE TITLE
Behavior of points_in_boxes

### ISSUE THREAD

**Issue by XuyangBai** [open-mmlab/mmdetection3d#434]
Hi I found the `points_in_boxes` functions returns an index tensor indicating the index of box where each point is in, so this function only works when the boxes have no overlap? If the boxes may have overlap, do I have to use this function for each box in a for loop? Is there any better solutions? 

https://github.com/open-mmlab/mmdetection3d/blob/e37f5d5edd04ef7b2e4f5e0a9c09fab4068ccf2e/mmdet3d/core/bbox/structures/lidar_box3d.py#L242-L254

**Comment by Wuziyi616** [comment]
Yes, currently we suppose the boxes are not overlapped (see the comment [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/ops/roiaware_pool3d/src/points_in_boxes_cuda.cu#L159)). If multiple boxes hit, it will return the first one (see [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/ops/roiaware_pool3d/src/points_in_boxes_cuda.cu#L73-L74)).

If the boxes you use may have overlap, you can loop over each box. Also you can use [points_in_boxes_cpu](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/ops/roiaware_pool3d/points_in_boxes.py#L53) which returns all `in` boxes, but it may be slow.

**Comment by Wuziyi616** [comment]
Hi, have a look at [this function](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/ops/roiaware_pool3d/points_in_boxes.py#L85). I think it returns 0/1 indicating whether one box overlaps with one points rather than box_idx. You may manually take the ```box.tensor``` out, unsqueeze a batch dimension, and use this function with points.

**Comment by XuyangBai** [comment]
Hi, thanks for your quick reply. I think the `points_in_boxes_batch` best suits my need.
