### ISSUE TITLE
How to train dataset without camera data?

### ISSUE THREAD

**Issue by HUI11126** [open-mmlab/mmdetection3d#435]
I want to train the DeepRoute Open Dataset. Here is the website: https://gas.graviti.cn/dataset/graviti-open-dataset/DeepRoute

There is no camera data in the dataset, only lidar data. It is different with KITTI.

**Comment by filaPro** [comment]
Most of detectors here doesn't use camera data. You can check [PointPillars](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/pointpillars) of [Second](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/second) for example.

**Comment by Wuziyi616** [comment]
Thank @filaPro for your kind help! And @HUI11126 thank you for your interest in our work. You can definitely train a dataset without camera data, but you may need to slightly modify the data pre-processing scripts we provided. Please refer to #429 for more details.

**Comment by HUI11126** [comment]
OK, thank you for your reply. @Wuziyi616 @filaPro  I will try.
