### ISSUE TITLE
Any plan to support 3D semantic/instance/panoptic segmentation?

### ISSUE THREAD

**Issue by ZCMax** [open-mmlab/mmdetection3d#445]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by THU17cyz** [comment]
Hi @ZCMax, please refer to #402 . We are planning this feature.

**Comment by THU17cyz** [comment]
@Wuziyi616 is working on this.

**Comment by Wuziyi616** [comment]
Hi @ZCMax , we are indeed planning to add 3D semantic segmentation, which a big goal in this month's plan (another plan is about mono-3d tasks). However, we are still on our early stage (preparing dataset, implementing baselines). So it may take a while before there are strong baselines/SOTA methods in this repo.

**Comment by Wuziyi616** [comment]
Feel free to reopen if you have any further questions about our plan :)

**Comment by davodogster** [comment]
@Wuziyi616 Hi Are you planning on adding Instance or Panoptic Segmentation?
