### ISSUE TITLE
Possible bug in nuscenes evaluation?

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#449]
Is [this](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/nuscenes_dataset.py#L437) `if` correct?
Typical 3d detector returns `list(dict('boxes_3d':..., 'scores': ..., 'labels_3d': ...), ...)`. If i'm not missing something, in this case we want to go to the `if` branch here, not `else`.

**Comment by Tai-Wang** [comment]
Actually we will give a key like 'pts_bbox' to each prediction (an example is [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/detectors/mvx_two_stage.py#L411)), so the result should be like `list(dict('pts_bbox': dict('boxes_3d':..., 'scores': ..., 'labels_3d': ...), 'img_bbox': dict('boxes_3d':..., 'scores': ..., 'labels_3d': ...)), ...)`. Hence, it should enter the `else`.

**Comment by filaPro** [comment]
Yes, I saw it. But for `KITTI` detectors (ex. VoxelNet, SSD3D) the result doesn't have this `pts_bbox` and `img_bbox` keys, so they can not be used for `NuScenes` without modifying this `if` condition.

**Comment by Tai-Wang** [comment]
OK I see. Maybe we should use a more compatible condition to distinguish these two cases, like `if not ('pts_bbox' in results[0] or 'img_bbox' in results[0])`(although it's a little hack). Do you have such cases? If yes, could you please help us fix and test it?

**Comment by filaPro** [comment]
Yes, I'm experimenting with custom single stage detector. Your solution works fine. Can make a one line PR from it.
