### ISSUE TITLE
Obtaining point cloud range data of alternative lidar dataset

### ISSUE THREAD

**Issue by FredrikG94** [open-mmlab/mmdetection3d#454]
Hi, I'm wondering how I would go about obtaining "point_cloud_range" in my dataset. Thanks!

**Comment by Tai-Wang** [comment]
You can basically read the point cloud data and see the maximum/minimum value for each dimension, or to be more accurate, make a statistics about the coordinates of point cloud and the center of ground truths (if available).

**Comment by Wuziyi616** [comment]
Also, I think you need to be aware of the GPU memory usage. If you use larger point cloud range without changing the voxel_size in models like SECOND (which use voxel encoder), the GPU memory may be a limit.
