### ISSUE TITLE
Error Training 3dssd

### ISSUE THREAD

**Issue by RolandoAvides** [open-mmlab/mmdetection3d#460]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help. Yes
2. The bug has not been fixed in the latest version.

**Describe the bug**

Last week I trained 3DSSD model. However, I no longer can train this model due to a new error.

**Reproduction**
1. What command or script did you run?
```
srun python train.py /home/rmoreira/mmdetection3d/configs/3dssd/3dssd_kitti-3d-3car.py
```
2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, I modified the config file and the dataset config file. I changed the data root.

3. What dataset did you use?
The Kitti dataset
**Environment**
```
sys.platform: linux
Python: 3.8.8 (default, Feb 24 2021, 21:46:12) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce GTX 1080
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2
OpenCV: 4.5.1
MMCV: 1.3.0
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.11.0
MMDetection3D: 0.12.0+b035bc8
```

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.
```
2021-04-18 19:01:10,637 - mmdet - INFO - load 56 Person_sitting database infos
Traceback (most recent call last):
  File "train.py", line 212, in <module>
    main()
  File "train.py", line 201, in main
    train_detector(
  File "/home/rmoreira/mmdetection/mmdet/apis/train.py", line 102, in train_detector
    runner = build_runner(
  File "/home/rmoreira/mmcv/mmcv/runner/builder.py", line 7, in build_runner
    return build_from_cfg(cfg, RUNNERS, default_args=default_args)
  File "/home/rmoreira/mmcv/mmcv/utils/registry.py", line 23, in build_from_cfg
    raise KeyError(
KeyError: '`cfg` or `default_args` must contain the key "type", but got {\'.......** and goes on **....
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by RolandoAvides** [comment]
**Bug Fix**

**Comment by Divadi** [comment]
I think it would be useful if you could post the entire new config file (perhaps the one generated by the training script, with everything filled in)

**Comment by RolandoAvides** [comment]
> I think it would be useful if you could post the entire new config file (perhaps the one generated by the training script, with everything filled in)

Hi! I edited comment of mine after this post.

**Comment by RolandoAvides** [comment]
This could happen because the default_runtime does not define the parameter 'type' of the runner....

**Comment by THU17cyz** [comment]
Hi @RolandoAvides ,

This is indeed a mistake made when we updated the config files. `3dssd_kitti-3d-car.py` did not inherit from a basic schedule config. Sorry for the inconvenience.

**Comment by THU17cyz** [comment]
> **Bug Fix**
> 
> I think I managed to fix the problem. I added the following expression in **line 111** of mmdetection3d/configs/3dssd/3dssd_kitti-3d-car.py
> 
> ```python
> runner = dict(max_epochs=150, type='EpochBasedRunner')
> ```
> 
> The original line of code was:
> 
> ```python
> runner = dict(max_epochs=150)
> ```
> 
> I don't know why I could train last week...I have never changed this parameter...

And the reason why you could train last week is because the update in config files was merged a few days ago.

**Comment by RolandoAvides** [comment]
Thank you! No problem!
