### ISSUE TITLE
CenterPoint tracking and scores

### ISSUE THREAD

**Issue by alanwanga** [open-mmlab/mmdetection3d#464]
Hey, thanks for the nice work.

I've successfully predicted on a single frame of my own point cloud data. How to make it work on all the sequence of data and get a tracking ID just like the official CenterPoint repo does? Also, where can we get the detection and tracking scores to filter out the boxes with low confidence?

Best,
Alan

**Comment by Tai-Wang** [comment]
Do you use the way given in the deom to make it work for single frame? If you would like to make it work on all sequences, you can either follow the demo way and traverse your data or follow the data formats of our supported datasets and use dataset specific APIs. How you get the detection scores also depends on which approach you choose.

For the tracking ID, currently we only focus on detection and segmentation, so it has not been supported yet. PRs are welcome.

**Comment by alanwanga** [comment]
@tianweiy please correct me if I'm wrong.

To enable the tracking feature, we'll have to implement a temporal model to predict the velocity. With the detection result, detection score, and velocity, it might be possible to run the modified tracking script ([pub_test.py](https://github.com/tianweiy/CenterPoint/blob/master/tools/nusc_tracking/pub_test.py)) to generate the tracking ID and tracking score.

For custom data, we'll still need to transform to global coordinate or it might not work well. In that case, we can probably find an existing KF filter based tracker like [AB3DMOT](https://github.com/xinshuoweng/AB3DMOT) instead.

**Comment by tianweiy** [comment]
Yeah, you are right

**Comment by alanwanga** [comment]
Cool, @Tai-Wang @tianweiy can you point out which part of code in mmdect3D and official CenterPoint should I look into? Any hints to get started with the temporal model?

**Comment by tianweiy** [comment]
Any hints to get started with the temporal model? <- all nuScenes model are temporal models as it uses ten sweeps as input. You just need to get get the velocity prediction and then you can do the tracking.

**Comment by Tai-Wang** [comment]
@alanwanga If you use pcd_demo.py to get the detection results, please refer to this [line](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/apis/inference.py#L205) for the way to get detection scores.

For the temporal model, maybe organizing the data as nuScenes and generate corresponding infos will make it more convenient. Currently only nuScenes models support the prediction of velocity with the consecutive point cloud input.

**Comment by alanwanga** [comment]
Thanks @Tai-Wang ,

I think this is the command to generate nuScenes style infos:

`python tools/create_data.py nuscenes --root-path ./data/nuscenes --version "v1.0-mini" --out-dir ./data/nuscenes --extra-tag nuscenes`

Then can we run pcd_demo.py on it? I found this [PR](https://github.com/open-mmlab/mmdetection3d/pull/264) from @xiliu8006 but not quite sure if it still works since I don't see it in the latest code.

You also mentioned we can call nuScenes specific APIs. Is it something like this:

```
./tools/slurm_test.sh v1.0-mini ${JOB_NAME} configs/centerpoint/centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus.py \
checkpoints/centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus_20200930_201619-67c8496f.pthhv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d_20200620_230405-2fa62f3d.pth --format-only --options 'jsonfile_prefix=./centerpoint_nuscenes_results'
```

**Comment by Tai-Wang** [comment]
If you would like to generate nuScenes style infos, you firstly need to organize your raw data as the metadata of nuscenes. It maybe a little complicated because you need to generate some json files.
Your mentioned PR could be a potential way to quickly leverage multi-sweep point clouds, but it is just a reference for you. For your specific usage, corresponding adjustments should be required.

**Comment by alanwanga** [comment]
>  For your specific usage, corresponding adjustments should be required.

I think one of the adjustments will be this https://github.com/open-mmlab/mmdetection3d/issues/280

**Comment by Tai-Wang** [comment]
Yes, you can have a try following that approach.
