### ISSUE TITLE
import and compile error

### ISSUE THREAD

**Issue by Liaoqing-up** [open-mmlab/mmdetection3d#475]
### - error:

hello, when i run demo, i get the error: **ImportError: cannot import name 'ball_query_ext' from 'mmdet3d.ops.ball_query'** (/opt/sdatmp/lq/project/gitproject/mmdetection3d/mmdet3d/ops/ball_query/init.py).
It seems come from these error when i run pip install -v -e . to **install MMDetection3D**:
warning: no files found matching 'mmdet3d/ops//.cpp'
warning: no files found matching 'mmdet3d/ops//.cu'
warning: no files found matching 'mmdet3d/ops//.h'
warning: no files found matching 'mmdet3d/ops//.cc'
FAILED: /opt/sdatmp/lq/project/gitproject/mmdetection3d/build/temp.linux-x86_64-3.7/mmdet3d/ops/spconv/src/indice_cuda.o
error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable()
Traceback (most recent call last):
  File "setup.py", line 253, in <module>zip_safe=False)
  File "/opt/sdatmp/lq/anaconda/envs/open_mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/opt/sdatmp/lq/anaconda/envs/open_mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

### - My environment:
ubuntu 18.04
cuda 10.1
pytorch 1.5.0
mmcv-full 1.3.1
mmdet 2.11.0
mmdet3d 0.12.0
numpy 1.20.2
pycocotools 2.0.2
cuDNN 7.6.03
gcc 7.5.0 
besides, i have tested `torch.cuda.is_available()` and got True

I ran **mmdet3d.utils.collect_env.py**, and got the following print message:

![image](https://user-images.githubusercontent.com/68799516/115811974-3c745680-a423-11eb-8942-1d39b881fb4d.png)

Have you encounter these errors before? I need your help, thankyou

**Comment by Tai-Wang** [comment]
Please refer to #420 . If there is any further question, please follow the template for reimplementation issue to redescribe your problem.

**Comment by Tai-Wang** [comment]
Can you successfully import mmcv and mmdet? Please strictly follow the way given in the [documentation](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#install-mmdetection3d) to install these two packages. For your compilation error, it maybe related to your gcc or cuda version. Please search for some information about the error message like [this](https://github.com/pytorch/vision/issues/1893#issuecomment-618873387)
