### ISSUE TITLE
what is implement of 3D CNN in MVXNet?

### ISSUE THREAD

**Issue by liyang0522** [open-mmlab/mmdetection3d#48]
The MVXNet fuses multi-modal data based on VoxelNet ,and the 3D CNN in VoxelNet is ordinary 3D CONV not the sparseconv,so  your implements of the MVXNet  uses the sparseconv which is proposed by the Second,  could this be Not in accord with the meaning of the original paper?Thank you for your reply

**Comment by ZwwWayne** [comment]
SECOND performs better than VoxelNet, so we implement the model based on the SECOND. The basic architecture is the same. https://github.com/open-mmlab/mmdetection3d/tree/master/configs/mvxnet
