### ISSUE TITLE
PartA2's find_unused_parameters = True

### ISSUE THREAD

**Issue by Divadi** [open-mmlab/mmdetection3d#488]
I was developing a two-stage network following the outline of the parta2 implementation in this repo, but I got this error:
```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
```
And I found that indeed, it could be resolved by passing setting find_unused_parameters = True like parta2
https://github.com/open-mmlab/mmdetection3d/blob/f7356f4baf1393d1c73dfbdd05944b925247b85e/configs/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-car.py#L137
However, I was wondering why this might have been necessary for parta2, and whether having this flag slows down training.

**Comment by Tai-Wang** [comment]
Typically it is used for the case when there is no positive samples when calculating losses. This is a relatively convenient way to deal with the case in PartA2, and will not influence the efficiency I guess (because it always needs to wait for all the computation finished). If there is no obvious influence in your experiments, just turning on it would be ok.

**Comment by Wuziyi616** [comment]
Feel free to reopen it if you have any further questions.

**Comment by liuyuansheng624** [comment]
> I was developing a two-stage network following the outline of the parta2 implementation in this repo, but I got this error:
> 
> ```
> RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
> ```
> 
> And I found that indeed, it could be resolved by passing setting find_unused_parameters = True like parta2
> 
> https://github.com/open-mmlab/mmdetection3d/blob/f7356f4baf1393d1c73dfbdd05944b925247b85e/configs/parta2/hv_PartA2_secfpn_2x8_cyclic_80e_kitti-3d-car.py#L137
> 
> 
> However, I was wondering why this might have been necessary for parta2, and whether having this flag slows down training.

Hello, I would like to ask if adding this parameter will affect the final experimental results, after all, some parameters are ignored

**Comment by liuyuansheng624** [comment]
> Typically it is used for the case when there is no positive samples when calculating losses. This is a relatively convenient way to deal with the case in PartA2, and will not influence the efficiency I guess (because it always needs to wait for all the computation finished). If there is no obvious influence in your experiments, just turning on it would be ok.

Hello, I would like to ask if adding this parameter will affect the final experimental results, after all, some parameters are ignored
