### ISSUE TITLE
Import Error in `mmdet3d.models.builder`

### ISSUE THREAD

**Issue by xiangruhuang** [open-mmlab/mmdetection3d#506]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I'm trying to run `tools/test.py` under `mmdetection3d` folder for evaluating mAP on some checkpoints for kitti dataset.
I received an import error (pasted below) where `mmdet3d.model.builder` [(this line)](https://github.com/open-mmlab/mmdetection3d/blob/86ef23d437f4d919412d41219b3b2fbe6c596fbe/mmdet3d/models/builder.py#L5)
tries to import `build` from `mmdet.models.builder.py`. But the function is no longer there due to a recent update of `mmdetection`. (See [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/builder.py)).

**Reproduction**
1. What command or script did you run?
```
python tools/test.py configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-3class_20200620_230238-9208083a.pth --out results/second.pkl --eval mAP
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No.

3. What dataset did you use?
Kitti

**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
```
sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
GPU 0: GeForce GTX 1080
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28540450_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.7.1+cu110
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.2+cu110
OpenCV: 4.5.1
MMCV: 1.3.2
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.11.0
MMDetection3D: 0.12.0+0d417e8
```
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    pip
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)
    I don't think there is anything relavent.

**Error traceback**
If applicable, paste the error trackback here.

```
Traceback (most recent call last):
  File "tools/test.py", line 12, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/mnt/xrhuang/mmdetection3d/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/mnt/xrhuang/mmdetection3d/mmdet3d/apis/inference.py", line 15, in <module>
    from mmdet3d.models import build_detector
  File "/mnt/xrhuang/mmdetection3d/mmdet3d/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/mnt/xrhuang/mmdetection3d/mmdet3d/models/backbones/__init__.py", line 3, in <module>
    from .nostem_regnet import NoStemRegNet
  File "/mnt/xrhuang/mmdetection3d/mmdet3d/models/backbones/nostem_regnet.py", line 2, in <module>
    from ..builder import BACKBONES
  File "/mnt/xrhuang/mmdetection3d/mmdet3d/models/builder.py", line 3, in <module>
    from mmdet.models.builder import (BACKBONES, DETECTORS, HEADS, LOSSES, NECKS,
ImportError: cannot import name 'build' from 'mmdet.models.builder' (/mnt/xrhuang/miniconda3/envs/lidar3d/lib/python3.7/site-packages/mmdet/models/builder.py)
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by Dinghow** [comment]
I've met the same issue yesterday, and I solved it by downgrade mmdet to 2.10.0, since I noticed that in v2.11.0, the build function is removed from mmdet.models.builder, while it exists in v2.10.0

**Comment by Wuziyi616** [comment]
@Dinghow Thank you for your kind reply. Yes, mmdet is going through a refactor about model `builder,py`. However, mmdet3d hasn't incorporated with their migration, so we should use mmdet<=2.11.0. See the compatibility document [here](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/getting_started.md).

**Comment by Wuziyi616** [comment]
Feel to re-open this issue if you have any further question :)

**Comment by sidiangongyuan** [comment]
> Feel to re-open this issue if you have any further question :)

Where did the build function go? Do I need to downgrade the version to solve this problem?
