### ISSUE TITLE
3D detector could not achieve good generalization effect？

### ISSUE THREAD

**Issue by T800GHB** [open-mmlab/mmdetection3d#510]
I collected some data with 32-line lidar
When I train this dataset with classical model like pointpillar, the model could not converge.
I use pointpillar with pre-trained model by KITTI to test on my dateset, get bad result like this.
<img width="895" alt="截屏2021-04-30 下午5 30 35" src="https://user-images.githubusercontent.com/5126190/116676676-d74bd280-a9d9-11eb-8ec1-e21beb3bfabf.png">
I used the default parameter settings of this repo, but I couldn't find the problem
There is a sample from my dataset, output result.
[sample.zip](https://github.com/open-mmlab/mmdetection3d/files/6404371/sample.zip)

**Comment by Wuziyi616** [comment]
Indeed the generalization ability of 3D detectors is not good. For example, if the point density varies or the height of objects is different from training dataset.
Regarding the model convergence issue on your dataset, I suggest you to check your data by e.g. visualizing 3D bbox on point clouds?

**Comment by Wuziyi616** [comment]
Feel free to re-open this issue if you have any further questions.
