### ISSUE TITLE
Loading painted KITTI

### ISSUE THREAD

**Issue by AfonsoSalgadoSousa** [open-mmlab/mmdetection3d#518]
Hi. I have never used this tool, so I am sorry in advance if this seems basic. I am trying to train a model in a painted KITTI dataset with N x 8 points, but the loading is not being done properly. The shape that reaches the BasePoint class is either 8 or 4 (when it breaks). In my config, I have a load_dim and use_dim of 8 for every pipeline, pts_prefix are 'velodyne' for when the cropping disallows reshaping and the rest is standard (config template used from SECOND in configs/benchmark). Does anyone have some insight on how can I circumvent this issue? Thank you!

**Comment by THU17cyz** [comment]
Hi @AfonsoSalgadoSousa ,

Have you checked that the data `pts_prefix` leads to do have a dim of 8? And can you provide more details (error trace or modified script)?

**Comment by Wuziyi616** [comment]
You may have a look in the point loading function [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/loading.py#L328), and using it in the command line to debug. There are indeed some hard-coded part in the code, for example [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/loading.py#L421-L430), we assume the rgb color channels lie on the last 3 channels of input points (in your case that should be points[:, [5, 6, 7]]). Maybe you need to modify the code a little bit to fit in your usage.

**Comment by AfonsoSalgadoSousa** [comment]
Hi. Thanks for the fast reply. I don't necessarily want to specify those extra features as colour, as I intend to decorate the point clouds with information other than pixel-wise segmentation prediction. Printing the _load_dim_ and _use_dim_ from the LoadPointsFromFile class, I get:
- [LoadPointsFromFile] Load dim: 8 Use dim: 8
-   [LoadPointsFromFile] Load dim: 4 Use dim: [0, 1, 2, 3]

Somehow the validation set has different settings, even though the config file seems correct: [my_config.txt](https://github.com/open-mmlab/mmdetection3d/files/6433258/my_config.txt)
I changed the tools/create_data.py to cope with the increased dimension dataset. The dataset is stored exactly like the regular kitti, with a "painted" prefix.

**Comment by THU17cyz** [comment]
Hi, it is actually because of the `dict(type='ObjectSample', db_sampler=db_sampler)` in the train pipeline. Please refer to the definition of [`DataBaseSampler`](https://github.com/open-mmlab/mmdetection3d/blob/b255d16b9f8a19a8f1065a1ae6c88fd2a03dc325/mmdet3d/datasets/pipelines/dbsampler.py#L80) and modify the corresponding part in the config.

**Comment by AfonsoSalgadoSousa** [comment]
Thank you. That solved the problem.
