### ISSUE TITLE
error while executing the test.py code

### ISSUE THREAD

**Issue by Latha-13** [open-mmlab/mmdetection3d#522]
Hi

When i was executing :
python demo/pcd_demo.py demo/kitti_000008.bin configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py checkpoints/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class_20200620_230421-aa0f3adb.pth 

I got a issue name "no module named":
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 3, in <module>
    from mmdet3d.apis import inference_detector, init_detector, show_result_meshlab
ModuleNotFoundError: No module named 'mmdet3d'

but already the folder exists. can any please help me in resolving this issue.

**Comment by wHao-Wu** [comment]
Hi, @Latha-13 

Have you installed the mmdet3d in your environment? The existence of the folder 'mmdet3d' doesn't mean you have install mmdet3d successfully. Please refer to [here](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#installation).

**Comment by wHao-Wu** [comment]
* Have you successfully compiled the module (mmdet3d) and related module (mmcv, mmdet)? Or have you got the information that you have installed all modules successfully? If facing any error, would you mind posting your error report?
* If you installed the mmdet3d successfully, please type in `python` followed by `import mmcv`, `import mmdet`, `import mmdet3d` to check whether these modules can be imported.

**Comment by celeste-1** [comment]
> 
> 
> Hi
> I have followed the steps given to install the mmdetection3d , Then how the module mmdet3d is not installed. can you please help me in solving the problem i have installed 2 times but the same error occurs .
> I have followed each and every steps in the installation process , That particular module alone is not installed is there any step for that.

I think it might be : can't find the path,maybe you can try to add :
import sys
sys.path.append('.')
in pcd_demo.py
