### ISSUE TITLE
Disabling RGB modality in MVXNet

### ISSUE THREAD

**Issue by manonthegithub** [open-mmlab/mmdetection3d#524]
Hello! 

I am currently working with MVXNet. I would like to disable RGB modality for one of my experiments, so that only the VoxelNet part of the net is working.
Can you please help, what would be the best option? Is there a simple way of doing it? 

Thank the team for really good support and help!

**Comment by wHao-Wu** [comment]
Hi, @manonthegithub 

Have you try using Dynamic VoxelNet with [config](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/dynamic_voxelization/dv_second_secfpn_6x8_80e_kitti-3d-car.py)? You can customize the config with your datasets or other configuration, referring to [here](https://mmdetection3d.readthedocs.io/en/latest/tutorials/). Hope this can solve your problem.

**Comment by manonthegithub** [comment]
Hi @wHao-Wu 
My goal is to compare how RGB modality improves the performance of the network, so I am looking for exactly the same configuration, just with the RGB modality disabled.
Is the configuration of Dynamic Voxel net exactly the same as MVXNet without RGB modality?

**Comment by wHao-Wu** [comment]
Hi, @manonthegithub 
Dynamic VoxelNet is similar to MVXNet except for the image backbone and multi-modality fusion layer and some configurations. So the Dynamic VoxelNet may conform to your expectation. More details can be found in [config](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/dynamic_voxelization).

**Comment by manonthegithub** [comment]
@wHao-Wu I have checked the configuration.... The Dynamic VoxelNet uses DynamicSimpleVFE as voxel encoder, but MVXNet uses DynamicVFE voxel encoder, the implementations are different. I don't think it is comparable then. Do you think I can change Dynamic VoxelNet to use  DynamicVFE? Is it a good idea?

**Comment by mhmodayman** [comment]
I know it is quite late, but one way to disable RGB is to multiply the input image by zero after it is read by the code and converted to a numpy_array

x1 = np.array(input_lidar_points) # shape -1, 4
x2 = np.array(input_pixels_image) # shape -1, 3

--> I suggest doing the following
x2 = x2 * 0

this way, the input image is an array of zeros

another way to disable RGB is to replace the following line in class PointFusion, responsible for the feature fusion between lidar and camera:

fuse_out = img_pre_fuse + pts_pre_fuse  # <-- replace this

and use this one instead:

fuse_out = pts_pre_fuse  # <-- use this
