### ISSUE TITLE
Please upload a pointpillars pre-trained model for the lyft dataset

### ISSUE THREAD

**Issue by mohamed11981198** [open-mmlab/mmdetection3d#525]

**Comment by THU17cyz** [comment]
Hi @mohamed11981198 ,

The Lyft dataset is very large and it takes several days to train one model. We have already trained a few settings, and some are yet to be done. The models will be ready soon, please stay tuned.

**Comment by wHao-Wu** [comment]
Hi, @mohamed11981198 

Thanks for your patience. We have uploaded the pre-trained pointpillars model for the Lyft dataset in [here](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/pointpillars).
