### ISSUE TITLE
Strategies of DB Sampling

### ISSUE THREAD

**Issue by XuyangBai** [open-mmlab/mmdetection3d#526]
Hi, thanks for this great codebase.  I find that you currently perform database sampling by first sample gt boxes from the database, and then remove the points inside the sample boxes to avoid potential conflict. But I wonder will the original gt boxes and the sampled boxes conflict with each other (i.e. the two sets of boxes are overlapped, then the points in the original gt boxes will be removed)? Besides, why do not you check the occlusion relationship between the original boxes and sampled boxes ( if one truck is in front of the car, then there should be no boxes augmented behind the truck? otherwise there might lead to more false negative during inference?)

**Comment by Tai-Wang** [comment]
1. There should be a collision test for sampled boxes and original ground truth boxes. We will only keep those sampled boxes that do not collide with the original ones.
2. The occlusion does affect the distribution of point clouds in reality, but it will also bring some computational costs to judge it. We basically follow the general and naive approach proposed by SECOND currently. It is definitely a promising direction to design the augmentation tricks more carefully though it can not easily affect the final performance too much.

**Comment by XuyangBai** [comment]
Thanks a lot for the quick reply !
