### ISSUE TITLE
Invalid point cloud shape

### ISSUE THREAD

**Issue by AfonsoSalgadoSousa** [open-mmlab/mmdetection3d#527]
Hi there. I am using a painted version of the KITTI dataset with 8 dimensions, with the first 4 dimensions as the regular ones.
While loading the data, I am facing the following error:
- cannot reshape array of size 3444 into shape (8)

I checked to see if any of my augmented point clouds could not be reshaped as (N, 8), but all could. I also checked if it could be from the range filtering augmentation truncating data, but the problem persists. 
I do not yet understand all the inner workings of this framework and, as such, would like to ask you if you have any insights on what could be the issue.

This issue is a follow up from [this one](https://github.com/open-mmlab/mmdetection3d/issues/518), where I am using the same configurations.

**Comment by Tai-Wang** [comment]
Please show more details of your error log, e.g. where do you get this error message.

**Comment by AfonsoSalgadoSousa** [comment]
Hi. Thanks for the reply. This is [my stack trace](https://github.com/open-mmlab/mmdetection3d/files/6445632/stack_trace.txt). I also leave [my config](https://github.com/open-mmlab/mmdetection3d/files/6445631/my_config.txt).

**Comment by Tai-Wang** [comment]
Obviously the most important information is that the error is triggered here:
```
  File "/home/afonso/projects/uncertainty_painting/detector/mmdet3d/datasets/pipelines/dbsampler.py", line 256, in sample_all
    s_points = self.points_loader(results)['points']
  File "/home/afonso/projects/uncertainty_painting/detector/mmdet3d/datasets/pipelines/loading.py", line 402, in __call__
    points = points.reshape(-1, self.load_dim)
ValueError: cannot reshape array of size 3444 into shape (8)
```
Then according to the traceback you can basically check whether the file loaded [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/pipelines/dbsampler.py#L256) contains points with expected dimensions.

**Comment by AfonsoSalgadoSousa** [comment]
Hi. I printed the shape o _s_points_ in that line and got:
[DataBaseSampler] Shape: torch.Size([12, 8])
[DataBaseSampler] Shape: torch.Size([1057, 8])
[DataBaseSampler] Shape: torch.Size([3, 8])
[DataBaseSampler] Shape: torch.Size([12, 8])
[DataBaseSampler] Shape: torch.Size([1057, 8])
[DataBaseSampler] Shape: torch.Size([3, 8])
[DataBaseSampler] Shape: torch.Size([142, 8])
[DataBaseSampler] Shape: torch.Size([12, 8])
[DataBaseSampler] Shape: torch.Size([1057, 8])
[DataBaseSampler] Shape: torch.Size([3, 8])
[DataBaseSampler] Shape: torch.Size([12, 8])
[DataBaseSampler] Shape: torch.Size([1057, 8])
[DataBaseSampler] Shape: torch.Size([3, 8])
[DataBaseSampler] Shape: torch.Size([142, 8])
Traceback (most recent call last):
...
 
Did the same for the regular KITTI dataset using [this benchmark config](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/benchmark/hv_second_secfpn_4x8_80e_pcdet_kitti-3d-3class.py) I based my config on and got:
[DataBaseSampler] Shape: torch.Size([200, 4])
[DataBaseSampler] Shape: torch.Size([1263, 4])
[DataBaseSampler] Shape: torch.Size([276, 4])
[DataBaseSampler] Shape: torch.Size([72, 4])
[DataBaseSampler] Shape: torch.Size([1263, 4])
[DataBaseSampler] Shape: torch.Size([276, 4])
[DataBaseSampler] Shape: torch.Size([60, 4])
[DataBaseSampler] Shape: torch.Size([34, 4])
[DataBaseSampler] Shape: torch.Size([2114, 4])
[DataBaseSampler] Shape: torch.Size([2114, 4])
[DataBaseSampler] Shape: torch.Size([29, 4])
[DataBaseSampler] Shape: torch.Size([17, 4])
[DataBaseSampler] Shape: torch.Size([734, 4])
[DataBaseSampler] Shape: torch.Size([200, 4])
...
Should these pairs be the same?

**Comment by Tai-Wang** [comment]
Your traceback indicates that some of your loaded files possibly contain points with the incorrect feature dimension, so you need to check which one leads to it.

**Comment by AfonsoSalgadoSousa** [comment]
The dataset I use was already preprocessed to remove the points not projected into the corresponding image, because of the added pixel-wise segmentation predictions. Is there a hard constraint on the number of points per cloud? I tried both the pts_prefix='velodyne_reduced' and pts_prefix='velodyne'.

**Comment by Tai-Wang** [comment]
There is no hard constraints. 'reduced' means that the points outside of the scope have been filtered out.
Your problem is the point file loaded contains wrong feature dimensions. Please try to print the file name after the line I mentioned before and have a closer look into that file.

**Comment by AfonsoSalgadoSousa** [comment]
Hi there. I tried maintaining all points: I now have a painted KITTI with point clouds of size (N, 8) where N is the same as the original KITTI (on the corresponding generation I made sure to guarantee this). Yet, the problem still persists. I tried printing the file name as you suggested and got:
  Filename: data/painted_kitti/painted_kitti_gt_database/2662_Car_13.bin
  [DataBaseSampler] Shape: torch.Size([100, 8])
  Filename: data/painted_kitti/painted_kitti_gt_database/275_Car_2.bin
  Filename: data/painted_kitti/painted_kitti_gt_database/5071_Car_1.bin
  Filename: data/painted_kitti/painted_kitti_gt_database/3017_Car_2.bin
  [DataBaseSampler] Shape: torch.Size([36, 8])
  Filename: data/painted_kitti/painted_kitti_gt_database/275_Car_2.bin
  Filename: data/painted_kitti/painted_kitti_gt_database/2092_Car_1.bin
  Filename: data/painted_kitti/painted_kitti_gt_database/3017_Car_2.bin
  [DataBaseSampler] Shape: torch.Size([36, 8])
  Filename: data/painted_kitti/painted_kitti_gt_database/275_Car_2.bin
  Traceback...
I do not understand how does this work. The same point cloud crops are loaded several times for different LiDAR? These prints seem to suggest that the same "275_Car_2.bin" is correctly loaded in the first two LiDAR, but crashes in the third. Is that right?

**Comment by Tai-Wang** [comment]
It's strange that the number of your printed shapes is inconsistent with the number of printed file names. Maybe use batch size=1 and only a single gpu to make the correspondence clearer?

**Comment by DongmingMMM** [comment]
Thank you so much for your detailed explanation! The problem has troubled me for a long time
