### ISSUE TITLE
Error while executing in google collab

### ISSUE THREAD

**Issue by Latha-13** [open-mmlab/mmdetection3d#536]
Hi

I tired to run the MMdetection3d in google collab i successfully installed mmdet3d but the issue is when i tried to
run "mmdetection3d/demo/inference_demo.ipynb" i got the error ,

The code ran:
from mmdet3d.apis import init_detector, inference_detector, show_result_meshlab

Choose to use a config and initialize the detector
config = 'configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py'

Setup a checkpoint file to load
checkpoint = 'checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth'

Error:
ModuleNotFoundError Traceback (most recent call last)
in ()
----> 1 from mmdet3d.apis import init_detector, inference_detector, show_result_pyplot
2 # Choose to use a config and initialize the detector
3 config = 'configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py'
4 # Setup a checkpoint file to load
5 checkpoint = 'checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth'

/content/mmdetection/mmdetection3d/mmdetection/mmdetection3d/mmdetection/mmdetection3d/mmdet3d/init.py in ()
2
3 import mmdet
----> 4 import mmseg
5 from .version import version, short_version
6

ModuleNotFoundError: No module named 'mmseg'

Is there any google collab notebook for testing like MMdetection? If there is any please share the link of that.

Thank you

**Comment by wHao-Wu** [comment]
Hi, @Latha-13 

Now we are supporting the 3D segmentation in our repo. We need mmsegmentation as the base for our 3D segmentation. Please clone the repo from [mmsegmentation](https://github.com/open-mmlab/mmsegmentation) and following the guidance as [here](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html):

```
cd mmsegmentation
pip install -e .
```
