### ISSUE TITLE
Whether the mmd3d support visualize 3d bbox

### ISSUE THREAD

**Issue by ustbzjf1** [open-mmlab/mmdetection3d#545]
As I have trained the fcos on nuscenes dataset, I want to visualize the prediction for analyzing. I found that mmd3d seems only support visualize the 2d bbox. 

![image](https://user-images.githubusercontent.com/59607228/118225229-4e439980-b4b7-11eb-997f-25306aad6f7d.png)

**Comment by wHao-Wu** [comment]
Hi, @ustbzjf1 

You can set the `--show` to True when testing. Then the prediction results will be visualized based on Open3d online or based on MeshLab offline.

**Comment by ustbzjf1** [comment]
Yeah, I have set the --show when testing, but then I found that a series bug happened in mmdet/core/visualization/image.py.
I don't find the code visualize 3d bbox with Open3d.

**Comment by wHao-Wu** [comment]
The codes to visualize 3d bbox are in [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/nuscenes_dataset.py#L518) and [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/visualizer/show_result.py#L73).

**Comment by ustbzjf1** [comment]
OK, I found the bug:  mmdet3d/models/detectors/base.py inherit BaseDetector in mmdet/models/detectors/base.py and it try to rewrite the show_result function in base class. However the it writes the function name wrong(show_results), which cause the show_result function not rewriten successfully. When I want to show the result, mmdet/apis/test/single_gpu_test call show_result function, which is designed in mmdet for 2d bbox visualization.

**Comment by wHao-Wu** [comment]
Thanks for your report. I found that FCOS based on monocular data is inherited from the single-stage detector from mmdet. So FCOS will use the show_results from mmdet instead of mmdet3d, which cause incorrect visualization in 3D detection.

**Comment by ustbzjf1** [comment]
Yes, I have tried define show_results function in fcos_mono3d.py, but it raise another bug, know I am trying to make SingleStageMono3DDetector inherit from SingleStage3DDetector

**Comment by Wuziyi616** [comment]
@ustbzjf1 Hi, I am currently working on a PR to add visualization functions to Mono-3D dataset and models. But it may take a while because I also encountered some errors. May be merged to MMDet3D in next week. It would be great if you can create a PR if you succeed in doing visualization.

**Comment by ustbzjf1** [comment]
OK，I will try to solve this bug in the weekend, if I solved this problem, I will update the comment.

**Comment by Wuziyi616** [comment]
Hi, the errors are solved now. You can refer to [this](https://github.com/Wuziyi616/mmdetection3d/tree/mono_vis_demo) branch of my repo if you want to use this feature in advance. The merge of this PR may not be very soon.

**Comment by ustbzjf1** [comment]
Yeah,  I modify the code accordding to the branch of mono_vis_demo, but the visualize result is show as bellow:
![image](https://user-images.githubusercontent.com/59607228/118444014-31110400-b71f-11eb-9b76-b597d682855c.png)
![image](https://user-images.githubusercontent.com/59607228/118444076-45ed9780-b71f-11eb-90ae-e4a22e6e6300.png)

**Comment by Wuziyi616** [comment]
@ustbzjf1 It's true that there are many false positives here. Maybe you can try setting a `score_thr` to filter low confidence boxes? Note that if you filter too much boxes, the AP will be lower.

**Comment by ustbzjf1** [comment]
If it's convenient to add your wechat, I found that after modify the code as branch mono_vis_demo. the show_score_thr is not used in the show_results function.

**Comment by Wuziyi616** [comment]
@ustbzjf1 Can give me your email and I will send my wechat account there? I don't want to show it public here after all :)

**Comment by ustbzjf1** [comment]
@Wuziyi616 I have sent you the email. My email address is ustbzjf@gmail.com. You can sent me your wechat, I will add you. Thanks

**Comment by DMing11** [comment]
Hi @Wuziyi616 , I got the result as below when run demo/mono_det_demo.py in the master branch 
![image](https://user-images.githubusercontent.com/44012690/126451067-5c138874-c303-44af-bd17-08c4893c64d6.png)
I have tried setting several --score-thr to filter low confidence boxes, but don't got the same results as you do  https://github.com/open-mmlab/mmdetection3d/pull/542  
Are you using NMS to filter detection results? Thanks
