### ISSUE TITLE
SECOND sparse shape for point cloud of size 9

### ISSUE THREAD

**Issue by AfonsoSalgadoSousa** [open-mmlab/mmdetection3d#553]
Hi. I am trying to train a SECOND model with an augment KITTI with point clouds of 9 dimensions. 
[This](https://github.com/open-mmlab/mmdetection3d/files/6494323/my_config.txt) is the config I use.
I am getting the following error:
File "/home/afonso/projects/uncertainty_painting/detector/mmdet3d/models/middle_encoders/sparse_encoder.py", line 112, in forward
    x = self.conv_input(input_sp_tensor)
  File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/afonso/projects/uncertainty_painting/detector/mmdet3d/ops/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/afonso/projects/uncertainty_painting/detector/mmdet3d/ops/spconv/conv.py", line 186, in forward
    outids.shape[0])
  File "/home/afonso/projects/uncertainty_painting/detector/mmdet3d/ops/spconv/functional.py", line 65, in forward
    indice_pair_num, num_activate_out, False, True)
  File "/home/afonso/projects/uncertainty_painting/detector/mmdet3d/ops/spconv/ops.py", line 119, in indice_conv
    int(subm))
RuntimeError: shape '[-1, 4, 16]' is invalid for input of size 3888
The problem seems to be with the middle encoder. My model config follows the default config from [the benchmark config](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/benchmark/hv_second_secfpn_4x8_80e_pcdet_kitti-3d-3class.py). What is the intuition behind the setting of the sparse shape? What should be optimal value be for point clouds of (N, 9)? Thank you in advance.

**Comment by Tai-Wang** [comment]
You need to specify the `num_features` [here](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/benchmark/hv_second_secfpn_4x8_80e_pcdet_kitti-3d-3class.py#L12) if you don't use the default setting `num_features=4` as given [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/models/voxel_encoders/voxel_encoder.py). The `in_channels` in the `middle_encoder` should be the same as `num_features` in `voxel_encoder`. In your case, they should be both set to 9.

**Comment by AfonsoSalgadoSousa** [comment]
Thank you very much. That solved the problem. Before closing the issue, I would like to ask you what happened in a successful training routine using a KITTI dataset with 8 dimensions. I managed to train a baseline using a painted KITTI successfully, and, at the time, I did not make the change you suggested and yet it worked. Did it only use 4 dimensions from the middle encoder on, or did it also happen to work because 8 is a multiple of 4? Should I remake the 8-dimension experiment using this tweak you suggested?

**Comment by Wuziyi616** [comment]
I think this is because 8 is a multiple of 4, so the pipeline load points successfully. I would suggest you remake the experiment. Maybe you can post the results here if it really make a difference? I am actually quite interested in how much performance gain will color information brings in outdoor detection task.
