### ISSUE TITLE
Is there a best model saved somewhere?

### ISSUE THREAD

**Issue by manonthegithub** [open-mmlab/mmdetection3d#554]
Hi! I am training the MVXNet, and got a question if there is the best model save somewhere. I mean it saves the model from the current epoch, but I don't see how to get the best model, because its not always the last one? 
Can you please help! Thank you a lot in advance.

**Comment by Tai-Wang** [comment]
Currently we only save the link to the latest model. You can refer to [gather_models.py](https://github.com/open-mmlab/mmdetection3d/blob/master/.dev_scripts/gather_models.py) for the way to find the best model according to a specific metric, which is usually used to find the logs/checkpoints of the best model when we set a new benchmark.

**Comment by Wuziyi616** [comment]
Feel free to reopen this issue if you have any further questions :)

**Comment by manonthegithub** [comment]
Looks good! Thank you!
