### ISSUE TITLE
Voxel segmentation/detection model

### ISSUE THREAD

**Issue by Heonjin** [open-mmlab/mmdetection3d#557]
Hi. I'm looking for a voxel segmentation/detection model.
If it is in the other open-mmlab github repository, then please refer it to me.
Thanks in advance.
please ping @hihunjin

**Comment by Wuziyi616** [comment]
I am not sure what do you mean by voxel model. Do you mean input 3D voxels and output detection or segmentation results? Currently all models in MMDet3D don't support voxel input. But there is indeed some sub-models use voxel representation, such as voxel encoders [here](https://github.com/open-mmlab/mmdetection3d/tree/master/mmdet3d/models/voxel_encoders). However, I don't think that's something you are looking for?

**Comment by hihunjin** [comment]
I was looking for 3D segmentation models. If you have any chance to create such a model or open a new github repository, please let me know.
Thanks.
