### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by qfwysw** [open-mmlab/mmdetection3d#558]
My environment:
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
GPU 0,1: GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-11.2
NVCC: Build cuda_11.2.r11.2/compiler.29558016_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.7.1+cu110
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.8.2+cu110
OpenCV: 4.5.1
MMCV: 1.2.7
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.2
MMDetection: 2.10.0
MMDetection3D: 0.12.0+
######################################################
Commend: python tools/train.py configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py
#######################################################
It's very strange, I could run it successfully yesterday. Today, I run it again, I get the error.

**Comment by Wuziyi616** [comment]
It's very hard to debug for error messages like 'segmentation fault'. The only thing I find strange from your environment is that, you have a different NVCC version (11.2) with your runtime cuda (also the cuda your pytorch is built with, 11.0). You said you ran it successfully yesterday, which seems more strange to me.

My only suggestion is to use a consistent CUDA version. Maybe you should install cuda-11.0 and use its NVCC to compile our operations, or compile torch from source with CUDA 11.2?

**Comment by qfwysw** [comment]
How do I recompile the mmdect? I want to check if I modified the mmdect.

**Comment by qfwysw** [comment]
Path: mmdet\apis\train.py
model = MMDataParallel(model.cuda(cfg.gpu_ids[0]), device_ids=cfg.gpu_ids)
The error is caused by this code.

**Comment by Wuziyi616** [comment]
Hi, in order to re-compile mmdet, you can simply use `pip uninstall mmdet` and remove the `build` and `egg info` files under `mmdetection/` (of course the safest way is to `pip uninstall mmdet` and `rm -rf ` the mmdet's directory). Then you can follow the instruction again and use `pip install -e .` to re-compile it.

**Comment by Wuziyi616** [comment]
> 
> 
> Path: mmdet\apis\train.py
> model = MMDataParallel(model.cuda(cfg.gpu_ids[0]), device_ids=cfg.gpu_ids)
> The error is caused by this code.

This is definitely an error related to GPU and cuda, but still it's hard to tell what exactly the problem is given current information.

**Comment by Wuziyi616** [comment]
Feel free to re-open this issue should you have any further questions :)
