### ISSUE TITLE
Second Performance on KITTI

### ISSUE THREAD

**Issue by jytime** [open-mmlab/mmdetection3d#56]
Hi,

I noticed that the performance of the provided SECOND model is 79.07 Car MAP on the KITTI validation dataset, while the official number in its paper is 76.48. May I ask what's the difference between the implementations, e.g., training schedule or structure?

Best,
Jianyuan

**Comment by LittleYuanzi** [comment]
This is also much higher than other code-base. Do you have any trick?

**Comment by ZwwWayne** [comment]
The second model in our model zoo is consistent with the SECOND v1.5 in the [SECOND.Pytorch](https://github.com/traveller59/second.pytorch).
