### ISSUE TITLE
Visualise in headless server and installation with incompatible mmdet version

### ISSUE THREAD

**Issue by AfonsoSalgadoSousa** [open-mmlab/mmdetection3d#568]
Hi. I am trying to visualise the results of my experiences which were trained in a headless server. Do you have any suggestion on how to save the visualisations in such cases?
To do this, I am trying to run the test script in a local machine, which requires a fresh installation of the mmlab's toolboxes. I have the following error:
AssertionError: MMDET==2.12.0 is used but incompatible. Please install mmdet>=2.10.0, <=2.11.0.
From https://github.com/open-mmlab/mmdetection3d/issues/519, I am aware that downgrading mmdet should fix the problem, but I am not sure how to do it since its compilation is done via Github. I followed the [installation guidelines](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/getting_started.md).

**Comment by wHao-Wu** [comment]
Hi, @AfonsoSalgadoSousa 

You can clone the repo from [mmdet](https://github.com/open-mmlab/mmdetection) and use the command `git checkout v2.11.0`. Then you can recompile the mmdet with a downgraded version.

**Comment by wHao-Wu** [comment]
Besides, if I take your meaning rightly, what you want is to visualize the results offline. So you can specify the `--show` to True when using the test script. Then you can use [MeshLab](https://www.meshlab.net/) to visualize the files with the postfix `.obj`.

**Comment by Wuziyi616** [comment]
Feel free to re-open this issue should you have any further questions :)
