### ISSUE TITLE
How to generate test results to Kitti?

### ISSUE THREAD

**Issue by JeffWang987** [open-mmlab/mmdetection3d#569]
After SECOND is trained based on config (hv_second_secfpn_6x8_80e_kitti-3d-car.py), it automatically produces another config file in the result file(the file that saves logs). In this config file, the test pipeline uses augmentation like random flip, 

<img width="383" alt="image" src="https://user-images.githubusercontent.com/49095445/119070085-f0183880-ba19-11eb-8fe2-59a2f4b03a1d.png">

My question is, do we have to modify the test pipeline to "no augmentation mode" before we test the result?
<img width="497" alt="image" src="https://user-images.githubusercontent.com/49095445/119070218-1fc74080-ba1a-11eb-8e2f-d979f3b71806.png">

**Comment by Wuziyi616** [comment]
Hi, you don't need to modify the pipeline. This `MultiScaleFlipAug3D` is a wrapper for test-time augmentation, and you won't be able to successfully run the code if you remove it.

Actually, this pipeline doesn't do any augmentation, as you can see `rot_range=[0, 0]` means no rotation will be performed, and `scale_ratio_range=[1.0, 1.0]` means the points will be scaled by `1` which equals to no scaling. Also the same to `translation_std=[0, 0, 0]`.

**Comment by Wuziyi616** [comment]
Even if the test_pipeline does any augmentations, we will use post-processing to merge them into predictions in the original coordinates. So no need to worry if you want to submit online test results.
