### ISSUE TITLE
Kiiti dataset bbox visulaization

### ISSUE THREAD

**Issue by kitty-1308** [open-mmlab/mmdetection3d#572]
Hi 

I have downloaded the raw dataset and I have converted into the required format by using create_data.py 
After converting i have used python tools/test.py to test the converted format datas I have attached the error i got while running in the middle of the code it got aborted.

![Capture](https://user-images.githubusercontent.com/84569900/119121927-9a5c8400-ba4b-11eb-8b33-1eb5942c1aea.JPG)

and i have also tried python tools/misc/browse_dataset.py to vizulaize the 3d bbox on the corresponding images but it piece of code didnt take the images which are inside my data/kitti/testing/images_02 , This code is taking some random images and showing the results.

Can anyone help me to resolve this issue. I read the doc i have tried all the procedure given but i couldnt solve the issue.
I need the 3d bbox on the image and the corresponding predicted file in json format. for this kitti dataset. 

Thank you.

**Comment by Wuziyi616** [comment]
Do you download the data correctly? From your posted image, I see you successfully tested on the first 1000 images and failed later. Maybe something is wrong with your data?

Also, I have tried browse_dataset on KITTI with multi-modality mode (which is the `3d bbox on the image` you want) and everything works well. I am not sure what do you mean by random images? Can you post some examples here?

**Note**: `browse_dataset` loads and visualizes training data. If you want to browse test data, you need to modify the config file by changing the `kitti_train_info.pkl` to `kitti_test_info.pkl`.

**Comment by kitty-1308** [comment]
Hi @Wuziyi616 yes when i tried to train the kitti dataset it show error like 
![Capture1](https://user-images.githubusercontent.com/84569900/119270434-4b187e00-bc1a-11eb-8457-8bc10f974909.JPG)

In case of nuscenes dataset i tried to train the dataset by using "python tools/train.py --gpus 1 configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py" pointpillars  and the following error occurs
![Capture2](https://user-images.githubusercontent.com/84569900/119270549-d2fe8800-bc1a-11eb-85d1-2d918493218e.JPG)
would you please help me in solving this issue?

Thank you.

**Comment by Wuziyi616** [comment]
The first problem is because your GPU doesn't have enough memory. We use V100 which has ~16G while you may use a GPU with less memory.

For the second problem, I am a little confused. Can you try `python tools/train.py configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py` without the `--gpus 1` args?

For the third question, I really think your processed KITTI data has some errors. I tried `browse_dataset` with my own data and everything works well. Maybe you should check it? Where did you download KITTI from?

**Comment by kitty-1308** [comment]
Hi @Wuziyi616 

yes i tired without --gpus1 and the same error occurs
![Capture4](https://user-images.githubusercontent.com/84569900/119272750-24ac1000-bc25-11eb-8988-fe22d4c992aa.JPG)

**Comment by kitty-1308** [comment]
Hi @Wuziyi616  and one more doubt is that i have a  kitti dataset with 100 images and calibration ,veloydyne info but i dont know why the database is not created it throws error
![Capture5](https://user-images.githubusercontent.com/84569900/119275113-d7ce3680-bc30-11eb-82bc-6f72a632b6fa.JPG)

**Comment by Wuziyi616** [comment]
For your first question, thank you for your report, I think that may be a bug in the codebase! We will fix it later. A workaround is using `dist_train.sh` (tutorial [here](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/1_exist_data_model.md#train-with-multiple-gpus)), can you please try:
```
./tools/dist_train.sh configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py 1
```
This will call distributed training and I think will solve your problem.

For your second problem, the code is working well. The error message said `000101.bin` doesn't exist which means the first 100 data had been processed. As 100 is the number of data in your dataset (is it your custom dataset?), you may need to modify some values about the number of data. I think it should be [this](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/kitti_data_utils.py#L145) args in the function, which come from [here](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/kitti_converter.py#L101-L103). Maybe you can have a look?

**Comment by Wuziyi616** [comment]
Okay I think that's not a bug. The error is because the model uses `SyncBN` like [here](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/hv_pointpillars_fpn_nus.py#L23). As you use `python tools/train.py`, that's not distributed training and `SyncBN` will certainly fail.

**Comment by kitty-1308** [comment]
> For your second problem, the code is working well. The error message said `000101.bin` doesn't exist which means the first 100 data had been processed. As 100 is the number of data in your dataset (is it your custom dataset?), you may need to modify some values about the number of data. I think it should be [this](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/kitti_data_utils.py#L145) args in the function, which come from [here](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/kitti_converter.py#L101-L103). Maybe you can have a look?

So, I have to change the image_idx to the number of images i have is that so?

**Comment by Wuziyi616** [comment]
Yes, I think that's it. But don't you have something like `ImageSets/train.txt` that will indicate the number of data as [here](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/kitti_converter.py#L101)?

**Comment by kitty-1308** [comment]
> Okay I think that's not a bug. The error is because the model uses `SyncBN` like [here](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/models/hv_pointpillars_fpn_nus.py#L23). As you use `python tools/train.py`, that's not distributed training and `SyncBN` will certainly fail.

How can i overcome that?

and the thing is when i tried to execute the ./tools/dist_train.sh configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py 1
it shows something like
bash: ./tools/dist_train.sh: Permission denied

**Comment by Wuziyi616** [comment]
Oh, then try with
```
sh ./tools/dist_train.sh configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py 1
```

**Comment by kitty-1308** [comment]
Hi @Wuziyi616 thank you so much for your response.

The thing is why i couldnt train the model by using python train.py is that necessary to train each time? i have tested the kity dataset with only 25 images alone i 1st created the database and i trained to train it doesnot work and i used python test.py to generate the result for the training dataset when i tried to visulaize the results only the training datasets has the 3d bounding box on the image on the test images.

Is this issue can be soughted out since im in to using this network for project activity im keen in generating the results .

Thank you

**Comment by Wuziyi616** [comment]
So first of all do you succeed in using `dist_train.sh` to train the model now?

Errr, I should say I am a little confused about your English. Are you trying on your own dataset or something else? Can you train the model on the KITTI dataset we provide in the codebase now?

**Comment by kitty-1308** [comment]
> So first of all do you succeed in using `dist_train.sh` to train the model now?
> 
> Errr, I should say I am a little confused about your English. Are you trying on your own dataset or something else? Can you train the model on the KITTI dataset we provide in the codebase now?

Hi @Wuziyi616  I'm so sorry for that ,
1. I couldnt train the dataset i tried with "sh ./tools/dist_train.sh configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py 1"
the following error occurs "./tools/dist_train.sh: 7: ./tools/dist_train.sh: Bad substitution"
and then i tried "chmod 777 tools/dist_train.sh configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py" it doesnot show any error or output, it showed to terminal to execute the next command.

**Comment by Wuziyi616** [comment]
No, I mean first run `chmod 777 tools/dist_train.sh`, then run `./tools/dist_train.sh configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py 1`.
If that doesn't work, try `bash ./tools/dist_train.sh configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py 1`.

**Comment by kitty-1308** [comment]
> No, I mean first run `chmod 777 tools/dist_train.sh`, then run `./tools/dist_train.sh configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py 1`.
> If that doesn't work, try `bash ./tools/dist_train.sh configs/pointpillars/hv_pointpillars_fpn_sbn-all_4x8_2x_nus-3d.py 1`.

![Screenshot (68)](https://user-images.githubusercontent.com/84569900/119869615-13714500-bf3e-11eb-91bd-084722db18d7.png)


Hi @Wuziyi616 This was the error i got when i ran the above 2 commands.

**Comment by Wuziyi616** [comment]
Okay, it seems that your GPU memory is not enough to train the model. What GPU and how many memory do you have? Maybe you need to change the batch size but that may harm the performance.

**Comment by kitty-1308** [comment]
Hi @Wuziyi616 
There is some issue with my local machine , so i tried to run it in google collab, now it could the  train the dataset.

Thank you so much for your help to solve those issue.

**Comment by Wuziyi616** [comment]
Glad it helps :)
