### ISSUE TITLE
Trying to visualize bbx after training and testing

### ISSUE THREAD

**Issue by selmadeac** [open-mmlab/mmdetection3d#573]
Hi!

I have successfully trained and tested pointpillars on 3 classes for kitti dataset.

I am trying to visualize the results, but I don't quite understand how.

The syntax I use in command line is:
python ./tools/misc/visualize_results.py ./tests/test_data/test_datasets/test_kitti_dataset.py --results ./tmp/test/results.pkl --show-dir ./tmp/test

But I get the folowing error: AttributeError: 'ConfigDict' object has no attribute 'data'

is there a tutorial on how to visualize detection results?
Is it available for all datasets?

**Comment by Wuziyi616** [comment]
Hi, you need to input the **config** of that dataset to the command line rather the .py file. In your case, I think you should use:
```
python ./tools/misc/visualize_results.py ./configs/_base_/datasets/kitti-3d-3class.py --results ./tmp/test/results.pkl --show-dir ./tmp/test
```

**Comment by selmadeac** [comment]
Thank you very much for your response! It almost worked. Now I get the following error:

Traceback (most recent call last):
  File "./tools/misc/visualize_results.py", line 48, in <module>
    main()
  File "./tools/misc/visualize_results.py", line 38, in main
    dataset.show(results, args.show_dir, pipeline=eval_pipeline)
  File "/home/selma/workspace/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 725, in show
    file_name, show)
  File "/home/selma/workspace/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 83, in show_result
    from .open3d_vis import Visualizer
  File "/home/selma/workspace/mmdetection3d/mmdet3d/core/visualizer/open3d_vis.py", line 8, in <module>
    import open3d as o3d
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/open3d/__init__.py", line 64, in <module>
    _CDLL(next((_Path(__file__).parent / 'cpu').glob('pybind*')))
  File "/home/selma/anaconda3/envs/open-mmlab/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc++.so.1: cannot open shared object file: No such file or directory

**Comment by Wuziyi616** [comment]
Hi, do you install open3d in your python environment? If not, please install open3d.

This error may also happen if you use Ubuntu 16 but install open3d>=0.10.0. You can try installing open3d==0.9.0. See [here](https://github.com/intel-isl/Open3D/issues/2037) for more discussions.

**Comment by selmadeac** [comment]
Thank you! I installed version 0.9.0. The error does not appear anymore. But now it says: 
free(): invalid pointer
Aborted (core dumped)

**Comment by Wuziyi616** [comment]
See the discussion [here](https://github.com/pytorch/pytorch/issues/19739), I think your command is right but this is still a problem related to open3d. Can you try with `open3d==0.5.0`?

If that doesn't work, maybe you need to create a new virtual environment... I am not sure yet. Can you run `python mmdet3d/utils/collect_env.py` and show me your current environment?

**Comment by selmadeac** [comment]
Thank you! Sure:

sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - CuDNN 8.0.5
  - Magma 2.5.2

TorchVision: 0.9.0
OpenCV: 4.5.2
MMCV: 1.3.4
MMCV Compiler: GCC 9.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.11.0
MMDetection3D: 0.12.0+973ffe1

As a side project, I started working on my own visualization using open3d and it works quite well. So I don't know if open3d is really the issue here.

**Comment by Wuziyi616** [comment]
Sorry for the late reply. I tried to replicate your environment but didn't meet the error you reported. Can you try some other functions that requires `open3d` to confirm if it works well on your machine? For example [this one](https://mmdetection3d.readthedocs.io/en/latest/useful_tools.html#dataset).

**Comment by selmadeac** [comment]
Hi! I am sorry for the late reply also! Now it appears to be working. I have updated the framework with the latest changes. Thank you!

**Comment by Fabrent** [comment]
where do you obtain the results.pkl when you obtain the results, actually i only have .json results
