### ISSUE TITLE
data prepare for lyft dataset should be update?

### ISSUE THREAD

**Issue by AromaticJ** [open-mmlab/mmdetection3d#587]
Hi, I download lyft dataset and found that there aren't train.txt val.txt test.txt but a train.csv, should the data prepare code for lyft dataset be update? I have no idea how to get train.txt val.txt test.txt or generate them from train.csv???

**Comment by wHao-Wu** [comment]
Hi, @AromaticJ 

The official Lyft dataset does not provide train.txt, val.txt, and test.txt. But our repo provides these files in [here](https://github.com/open-mmlab/mmdetection3d/tree/master/data/lyft).

**Comment by Wuziyi616** [comment]
Feel free to re-open this issue should you have any further questions :)
