### ISSUE TITLE
调用centerpoint模型训练时，类型转换错误

### ISSUE THREAD

**Issue by 123world** [open-mmlab/mmdetection3d#588]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
是的
2. The bug has not been fixed in the latest version.
是的

**Describe the bug**
调用centerpoint模型进行训练的时候，在文件mmdetection3d/mmdet3d/models/dense_heads/centerpoint_head.py下的line 410, in get_targets
    heatmaps = np.array(heatmaps).transpose(1, 0).tolist()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Reproduction**
1. What command or script did you run?

```
python tools/train.py configs/centerpoint/centerpoint_02pillar_second_secfpn_dcn_4x8_cyclic_20e_nus.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
我在mmdetection3d/mmdet3d/models/dense_heads/centerpoint_head.py文件的类CenterHead的get_targets函数下修改
![2021-05-26 14-16-51 的屏幕截图](https://user-images.githubusercontent.com/46485739/119611360-2ba56f00-be2d-11eb-98aa-4a675e981897.png)
再次运行python tools/train.py configs/centerpoint/centerpoint_02pillar_second_secfpn_dcn_4x8_cyclic_20e_nus.py，出现，
![2021-05-26 14-19-39 的屏幕截图](https://user-images.githubusercontent.com/46485739/119611603-80e18080-be2d-11eb-82b5-94dfcb2d7d68.png)

3. What dataset did you use?
我使用的是nuscenes数据集

**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment infomation and paste it here.
![2021-05-26 14-22-12 的屏幕截图](https://user-images.githubusercontent.com/46485739/119611867-d0c04780-be2d-11eb-8a75-a3e290ec5604.png)

2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    pip方式
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by THU17cyz** [comment]
Please check your `numpy` version. In `numpy` versions `1.16.4, 1.18.1, 1.19.2`, `np.array(t)` won't cause an error if `t` is a list of CUDA tensors. For example:

```
>>> a = torch.tensor([1], device='cuda')
>>> np.array([[a]])
array([[tensor([1], device='cuda:0')]], dtype=object)
```

**Comment by 123world** [comment]
thank your replay

**Comment by 123world** [comment]
安装numpy<1.20.0, train或test会出现以下问题
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ganzhi/mmdetection3d/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/home/ganzhi/mmdetection3d/mmdet3d/apis/inference.py", line 10, in <module>
    from mmdet3d.core import (Box3DMode, DepthInstance3DBoxes,
  File "/home/ganzhi/mmdetection3d/mmdet3d/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/ganzhi/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 1, in <module>
    from mmdet.core.anchor import build_anchor_generator
  File "/home/ganzhi/mmdetection/mmdet/core/__init__.py", line 5, in <module>
    from .mask import *  # noqa: F401, F403
  File "/home/ganzhi/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/ganzhi/mmdetection/mmdet/core/mask/structures.py", line 6, in <module>
    import pycocotools.mask as maskUtils
  File "/home/ganzhi/xqq_station/miniconda3/envs/det3d2/lib/python3.8/site-packages/pycocotools-2.0.2-py3.8-linux-x86_64.egg/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
python-BaseException
网上找了以下，解决方法是更新numpy，更新到numpy>1.20.0就不会出现此问题，但是会出现TypeError: can't convert CUDA tensor to numpy，我自己的解决方式
修改/home/ganzhi/mmdetection3d/mmdet3d/models/dense_heads/centerpoint_head.py
def cuda_to_cpu(self, heatmaps, anno_boxes, inds, masks):
        for idx, ht in enumerate(heatmaps):
            for idy in range(len(ht)):
                # print(heatmaps[idx])
                heatmaps[idx][idy] = heatmaps[idx][idy].cpu()

        for idx, ht in enumerate(anno_boxes):
            for idy in range(len(ht)):
                # print(heatmaps[idx])
                anno_boxes[idx][idy] = anno_boxes[idx][idy].cpu()

        for idx, ht in enumerate(inds):
            for idy in range(len(ht)):
                # print(heatmaps[idx])
                inds[idx][idy] = inds[idx][idy].cpu()

        for idx, ht in enumerate(masks):
            for idy in range(len(ht)):
                # print(heatmaps[idx])
                masks[idx][idy] = masks[idx][idy].cpu()
        return heatmaps, anno_boxes, inds, masks

 def get_targets(self, gt_bboxes_3d, gt_labels_3d):
        """Generate targets.

        Args:
            gt_bboxes_3d (list[:obj:`LiDARInstance3DBoxes`]): Ground
                truth gt boxes.
            gt_labels_3d (list[torch.Tensor]): Labels of boxes.

        Returns:
            Returns:
                tuple[list[torch.Tensor]]: Tuple of target including \
                    the following results in order.

                    - list[torch.Tensor]: Heatmap scores.
                    - list[torch.Tensor]: Ground truth boxes.
                    - list[torch.Tensor]: Indexes indicating the \
                        position of the valid boxes.
                    - list[torch.Tensor]: Masks indicating which \
                        boxes are valid.
        """
        heatmaps, anno_boxes, inds, masks = multi_apply(
            self.get_targets_single, gt_bboxes_3d, gt_labels_3d)
        heatmaps, anno_boxes, inds, masks = self.cuda_to_cpu(
            heatmaps, anno_boxes, inds, masks)

        # transpose heatmaps, because the dimension of tensors in each task is
        # different, we have to use numpy instead of torch to do the transpose.
        heatmaps = np.array(heatmaps).transpose(1, 0).tolist()
        # heatmaps = [torch.stack(hms_) for hms_ in heatmaps]
        heatmaps = [torch.stack(hms_).cuda() for hms_ in heatmaps]

        # transpose anno_boxes
        anno_boxes = np.array(anno_boxes).transpose(1, 0).tolist()
        # anno_boxes = [torch.stack(anno_boxes_) for anno_boxes_ in anno_boxes]
        anno_boxes = [torch.stack(anno_boxes_).cuda() for anno_boxes_ in anno_boxes]

        # transpose inds
        inds = np.array(inds).transpose(1, 0).tolist()
        # inds = [torch.stack(inds_) for inds_ in inds]
        inds = [torch.stack(inds_).cuda() for inds_ in inds]

        # transpose inds
        masks = np.array(masks).transpose(1, 0).tolist()
        # masks = [torch.stack(masks_)for masks_ in masks]
        masks = [torch.stack(masks_).cuda() for masks_ in masks]
        return heatmaps, anno_boxes, inds, masks
虽然问题我自己解决了，但是我还是希望mmdetetion3d框架有更加完美优雅的解决方式

**Comment by 123world** [comment]
安装numpy<1.20.0, train或test会出现以下问题
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ganzhi/mmdetection3d/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/home/ganzhi/mmdetection3d/mmdet3d/apis/inference.py", line 10, in <module>
    from mmdet3d.core import (Box3DMode, DepthInstance3DBoxes,
  File "/home/ganzhi/mmdetection3d/mmdet3d/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/ganzhi/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 1, in <module>
    from mmdet.core.anchor import build_anchor_generator
  File "/home/ganzhi/mmdetection/mmdet/core/__init__.py", line 5, in <module>
    from .mask import *  # noqa: F401, F403
  File "/home/ganzhi/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/ganzhi/mmdetection/mmdet/core/mask/structures.py", line 6, in <module>
    import pycocotools.mask as maskUtils
  File "/home/ganzhi/xqq_station/miniconda3/envs/det3d2/lib/python3.8/site-packages/pycocotools-2.0.2-py3.8-linux-x86_64.egg/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
python-BaseException
网上找了以下，解决方法是更新numpy，更新到numpy>1.20.0就不会出现此问题，但是会出现TypeError: can't convert CUDA tensor to numpy，我自己的解决方式
修改/home/ganzhi/mmdetection3d/mmdet3d/models/dense_heads/centerpoint_head.py
def cuda_to_cpu(self, heatmaps, anno_boxes, inds, masks):
        for idx, ht in enumerate(heatmaps):
            for idy in range(len(ht)):
                # print(heatmaps[idx])
                heatmaps[idx][idy] = heatmaps[idx][idy].cpu()

        for idx, ht in enumerate(anno_boxes):
            for idy in range(len(ht)):
                # print(heatmaps[idx])
                anno_boxes[idx][idy] = anno_boxes[idx][idy].cpu()

        for idx, ht in enumerate(inds):
            for idy in range(len(ht)):
                # print(heatmaps[idx])
                inds[idx][idy] = inds[idx][idy].cpu()

        for idx, ht in enumerate(masks):
            for idy in range(len(ht)):
                # print(heatmaps[idx])
                masks[idx][idy] = masks[idx][idy].cpu()
        return heatmaps, anno_boxes, inds, masks

 def get_targets(self, gt_bboxes_3d, gt_labels_3d):
        """Generate targets.

        Args:
            gt_bboxes_3d (list[:obj:`LiDARInstance3DBoxes`]): Ground
                truth gt boxes.
            gt_labels_3d (list[torch.Tensor]): Labels of boxes.

        Returns:
            Returns:
                tuple[list[torch.Tensor]]: Tuple of target including \
                    the following results in order.

                    - list[torch.Tensor]: Heatmap scores.
                    - list[torch.Tensor]: Ground truth boxes.
                    - list[torch.Tensor]: Indexes indicating the \
                        position of the valid boxes.
                    - list[torch.Tensor]: Masks indicating which \
                        boxes are valid.
        """
        heatmaps, anno_boxes, inds, masks = multi_apply(
            self.get_targets_single, gt_bboxes_3d, gt_labels_3d)
        heatmaps, anno_boxes, inds, masks = self.cuda_to_cpu(
            heatmaps, anno_boxes, inds, masks)

        # transpose heatmaps, because the dimension of tensors in each task is
        # different, we have to use numpy instead of torch to do the transpose.
        heatmaps = np.array(heatmaps).transpose(1, 0).tolist()
        # heatmaps = [torch.stack(hms_) for hms_ in heatmaps]
        heatmaps = [torch.stack(hms_).cuda() for hms_ in heatmaps]

        # transpose anno_boxes
        anno_boxes = np.array(anno_boxes).transpose(1, 0).tolist()
        # anno_boxes = [torch.stack(anno_boxes_) for anno_boxes_ in anno_boxes]
        anno_boxes = [torch.stack(anno_boxes_).cuda() for anno_boxes_ in anno_boxes]

        # transpose inds
        inds = np.array(inds).transpose(1, 0).tolist()
        # inds = [torch.stack(inds_) for inds_ in inds]
        inds = [torch.stack(inds_).cuda() for inds_ in inds]

        # transpose inds
        masks = np.array(masks).transpose(1, 0).tolist()
        # masks = [torch.stack(masks_)for masks_ in masks]
        masks = [torch.stack(masks_).cuda() for masks_ in masks]
        return heatmaps, anno_boxes, inds, masks
虽然问题我自己解决了，但是我还是希望mmdetetion3d框架有更加完美优雅的解决方式

**Comment by THU17cyz** [comment]
> 网上找了以下，解决方法是更新numpy，更新到numpy>1.20.0就不会出现此问题，但是会出现TypeError: can't convert CUDA tensor to numpy，我自己的解决方式

https://github.com/open-mmlab/mmdetection3d/blob/master/docs/faq.md#mmcvmmdetmmdet3d-installation

**Comment by wangyakunn** [comment]
> heatmaps, anno_boxes, inds, masks = self.cuda_to_cpu(
>         heatmaps, anno_boxes, inds, masks)

ValueError: only one element tensors can be converted to Python scalars

**Comment by wangyakunn** [comment]
> 安装numpy<1.20.0, train或test会出现以下问题 Traceback (most recent call last): File "", line 991, in _find_and_load File "", line 975, in _find_and_load_unlocked File "", line 671, in _load_unlocked File "", line 848, in exec_module File "", line 219, in _call_with_frames_removed File "/home/ganzhi/mmdetection3d/mmdet3d/apis/**init**.py", line 1, in from .inference import (convert_SyncBN, inference_detector, File "/home/ganzhi/mmdetection3d/mmdet3d/apis/inference.py", line 10, in from mmdet3d.core import (Box3DMode, DepthInstance3DBoxes, File "/home/ganzhi/mmdetection3d/mmdet3d/core/**init**.py", line 1, in from .anchor import * # noqa: F401, F403 File "/home/ganzhi/mmdetection3d/mmdet3d/core/anchor/**init**.py", line 1, in from mmdet.core.anchor import build_anchor_generator File "/home/ganzhi/mmdetection/mmdet/core/**init**.py", line 5, in from .mask import * # noqa: F401, F403 File "/home/ganzhi/mmdetection/mmdet/core/mask/**init**.py", line 2, in from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks File "/home/ganzhi/mmdetection/mmdet/core/mask/structures.py", line 6, in import pycocotools.mask as maskUtils File "/home/ganzhi/xqq_station/miniconda3/envs/det3d2/lib/python3.8/site-packages/pycocotools-2.0.2-py3.8-linux-x86_64.egg/pycocotools/mask.py", line 3, in import pycocotools._mask as _mask File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject python-BaseException 网上找了以下，解决方法是更新numpy，更新到numpy>1.20.0就不会出现此问题，但是会出现TypeError: can't convert CUDA tensor to numpy，我自己的解决方式 修改/home/ganzhi/mmdetection3d/mmdet3d/models/dense_heads/centerpoint_head.py def cuda_to_cpu(self, heatmaps, anno_boxes, inds, masks): for idx, ht in enumerate(heatmaps): for idy in range(len(ht)): # print(heatmaps[idx]) heatmaps[idx][idy] = heatmaps[idx][idy].cpu()
> 
> ```
>     for idx, ht in enumerate(anno_boxes):
>         for idy in range(len(ht)):
>             # print(heatmaps[idx])
>             anno_boxes[idx][idy] = anno_boxes[idx][idy].cpu()
> 
>     for idx, ht in enumerate(inds):
>         for idy in range(len(ht)):
>             # print(heatmaps[idx])
>             inds[idx][idy] = inds[idx][idy].cpu()
> 
>     for idx, ht in enumerate(masks):
>         for idy in range(len(ht)):
>             # print(heatmaps[idx])
>             masks[idx][idy] = masks[idx][idy].cpu()
>     return heatmaps, anno_boxes, inds, masks
> ```
> 
> def get_targets(self, gt_bboxes_3d, gt_labels_3d): """Generate targets.
> 
> ```
>     Args:
>         gt_bboxes_3d (list[:obj:`LiDARInstance3DBoxes`]): Ground
>             truth gt boxes.
>         gt_labels_3d (list[torch.Tensor]): Labels of boxes.
> 
>     Returns:
>         Returns:
>             tuple[list[torch.Tensor]]: Tuple of target including \
>                 the following results in order.
> 
>                 - list[torch.Tensor]: Heatmap scores.
>                 - list[torch.Tensor]: Ground truth boxes.
>                 - list[torch.Tensor]: Indexes indicating the \
>                     position of the valid boxes.
>                 - list[torch.Tensor]: Masks indicating which \
>                     boxes are valid.
>     """
>     heatmaps, anno_boxes, inds, masks = multi_apply(
>         self.get_targets_single, gt_bboxes_3d, gt_labels_3d)
>     heatmaps, anno_boxes, inds, masks = self.cuda_to_cpu(
>         heatmaps, anno_boxes, inds, masks)
> 
>     # transpose heatmaps, because the dimension of tensors in each task is
>     # different, we have to use numpy instead of torch to do the transpose.
>     heatmaps = np.array(heatmaps).transpose(1, 0).tolist()
>     # heatmaps = [torch.stack(hms_) for hms_ in heatmaps]
>     heatmaps = [torch.stack(hms_).cuda() for hms_ in heatmaps]
> 
>     # transpose anno_boxes
>     anno_boxes = np.array(anno_boxes).transpose(1, 0).tolist()
>     # anno_boxes = [torch.stack(anno_boxes_) for anno_boxes_ in anno_boxes]
>     anno_boxes = [torch.stack(anno_boxes_).cuda() for anno_boxes_ in anno_boxes]
> 
>     # transpose inds
>     inds = np.array(inds).transpose(1, 0).tolist()
>     # inds = [torch.stack(inds_) for inds_ in inds]
>     inds = [torch.stack(inds_).cuda() for inds_ in inds]
> 
>     # transpose inds
>     masks = np.array(masks).transpose(1, 0).tolist()
>     # masks = [torch.stack(masks_)for masks_ in masks]
>     masks = [torch.stack(masks_).cuda() for masks_ in masks]
>     return heatmaps, anno_boxes, inds, masks
> ```
> 
> 虽然问题我自己解决了，但是我还是希望mmdetetion3d框架有更加完美优雅的解决方式

def trans(self, heatmaps, anno_boxes, inds, masks):
        for idx, ht in enumerate(heatmaps):
            for idy in range(len(ht)):
                heatmaps[idx][idy] = np.array(heatmaps[idx][idy])
                for i in range(heatmaps[idx][idy].shape[0]):
                    heatmaps[idx][idy][i].transpose(1, 0)
                heatmaps[idx][idy]=torch.from_numpy(heatmaps[idx][idy])
        for idx, ht in enumerate(anno_boxes):
            for idy in range(len(ht)):
                anno_boxes[idx][idy] = np.array(anno_boxes[idx][idy])
                
                anno_boxes[idx][idy].transpose(1, 0)
                anno_boxes[idx][idy]=torch.from_numpy(anno_boxes[idx][idy])
        for idx, ht in enumerate(inds):
            for idy in range(len(ht)):
                inds[idx][idy].view(-1,1)
        for idx, ht in enumerate(masks):
            for idy in range(len(ht)):
                masks[idx][idy].view(-1,1)
        return heatmaps, anno_boxes, inds, masks

    def assign_targets(self, gt_boxes):
        """Generate targets.

        Args:
            gt_boxes: (B, M, 8) box + cls 

        Returns:
            Returns:
                tuple[list[torch.Tensor]]: Tuple of target including \
                    the following results in order.

                    - list[torch.Tensor]: Heatmap scores.
                    - list[torch.Tensor]: Ground truth boxes.
                    - list[torch.Tensor]: Indexes indicating the \
                        position of the valid boxes.
                    - list[torch.Tensor]: Masks indicating which \
                        boxes are valid.
        """
        gt_bboxes_3d, gt_labels_3d = gt_boxes[..., :-1], gt_boxes[..., -1]

        heatmaps, anno_boxes, inds, masks = multi_apply(
            self.get_targets_single, gt_bboxes_3d, gt_labels_3d)
        
        heatmaps, anno_boxes, inds, masks = self.cuda_to_cpu(
            heatmaps, anno_boxes, inds, masks)
        print("masks=",masks)
        heatmaps, anno_boxes, inds, masks = self.trans(
            heatmaps, anno_boxes, inds, masks)
        # transpose heatmaps, because the dimension of tensors in each task is
        # different, we have to use numpy instead of torch to do the transpose.

        
        heatmaps = [torch.stack(hms_).cuda() for hms_ in heatmaps]

        # transpose anno_boxes
        # anno_boxes = np.array(anno_boxes).transpose(1, 0).tolist()
        # anno_boxes = [torch.stack(anno_boxes_) for anno_boxes_ in anno_boxes]
        anno_boxes = [torch.stack(anno_boxes_).cuda() for anno_boxes_ in anno_boxes]

        # transpose inds
        # inds = np.array(inds).transpose(1, 0).tolist()
        # inds = [torch.stack(inds_) for inds_ in inds]
        inds = [torch.stack(inds_).cuda() for inds_ in inds]

        # transpose inds
        # masks = np.array(masks).transpose(1, 0).tolist()
        # masks = [torch.stack(masks_) for masks_ in masks]
        masks = [torch.stack(masks_).cuda() for masks_ in masks]

        
        all_targets_dict = {
            'heatmaps': heatmaps,
            'anno_boxes': anno_boxes,
            'inds': inds,
            'masks': masks
        }
        
        return all_targets_dict在作者的基础上基于自己的numpy版本1.23.0改了一些保存的处理可以训练了

**Comment by yaobaishen** [comment]
It's strange that I can fix it by @123world 's solution, but failed with @wangyakunn 's
