### ISSUE TITLE
how to visualize both GTbox and Predbox with 'tools/misc/visualize_results.py'

### ISSUE THREAD

**Issue by gujiaqivadin** [open-mmlab/mmdetection3d#590]
Hello!
     I am trying to visualize the 3d detection results as well as 3d GTBox projected on the  image plane.  After i get .pkl by inference the given pointpillars model. I try to run the following script to get image.
     But something about the content of pkl file is wrong. I am wondering what the pkl file means in visualize_results.py and how to use current code to see both projected GTBox and Predbox on the same image.

```
python tools/misc/visualize_results.py ./configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py --result pointpillars_kitti_results.pkl --show-dir ../vis_test/
```

```
[gujiaqi.gjq@gpu1037.sqa.eu95 /home/gujiaqi.gjq/project/mmdetection3d]
$python tools/misc/visualize_results.py ./configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py --result pointpillars_kitti_results.pkl --show-dir ./vis/
which: no hipcc in (/home/gujiaqi.gjq/anaconda3/envs/mmcv/bin:/home/gujiaqi.gjq/anaconda3/condabin:/home/gujiaqi.gjq/tool/gcc-5.4/bin:/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/X11R6/bin:/usr/local/cuda/bin:/home/gujiaqi.gjq/.local/bin:/home/gujiaqi.gjq/bin)
Traceback (most recent call last):
  File "tools/misc/visualize_results.py", line 48, in <module>
    main()
  File "tools/misc/visualize_results.py", line 38, in main
    dataset.show(results, args.show_dir, pipeline=eval_pipeline)
  File "/home/gujiaqi.gjq/project/mmdetection3d/mmdet3d/datasets/kitti_dataset.py", line 721, in show
    pred_bboxes = result['boxes_3d'].tensor.numpy()
KeyError: 'boxes_3d'
```

**Comment by Wuziyi616** [comment]
Can you load the saved pkl file and see if its content is correct?
```
results = mmcv.load('pointpillars_kitti_results.pkl')  # should be a list, each element is a prediction on one data
print(len(results))
print(results[0].keys())
```

**Comment by Wuziyi616** [comment]
Another thing is that, `pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py` is a single-modality detection model so you won't be able to see `3d GTBox projected on the image plane`. You need to input a multi-modality config such as [this](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py).

**Comment by Tai-Wang** [comment]
It seems the dict is similar with the data info pkl for KITTI. Please check the process of the generation of this pkl file.

**Comment by Wuziyi616** [comment]
Yes there is something wrong with the inference process. Can you post your command used in pkl file generation?

**Comment by gujiaqivadin** [comment]
To generate the pkl file, I use the inference code provided in .markdown file and run:
```
python tools/test.py ./config/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py ./pretrained_models/hv_pointpillars_secfpn_6x8_160e_kitti-3d-car_20200620_230614-77663cd6.pth --format-only --options 'pklfile_prefix=./pointpillars_kitti_results' 'submission_prefix=./pointpillars_kitti_results'
```

**Comment by Wuziyi616** [comment]
Oh, that's the question. `format-only` is when you want to submit results to online benchmark. You should use `--out xxx` instead.

**Comment by Wuziyi616** [comment]
`--out` and `--format-only` have no difference other than the saved pkl files format. `--out` directly saves a list, while `--format-only` will convert to the official required format.

**Comment by gujiaqivadin** [comment]
thanks a lot! it really helps me a lot

**Comment by Wuziyi616** [comment]
Glad it helps :)
