### ISSUE TITLE
Any plan to support 3D semantic segmentation on NuScenes dataset?

### ISSUE THREAD

**Issue by yaodongC** [open-mmlab/mmdetection3d#591]
**Describe the feature**

**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by Wuziyi616** [comment]
Can you point me to any papers that have conducted sem seg experiments on NuScenes?

**Comment by yaodongC** [comment]
> Can you point me to any papers that have conducted sem seg experiments on NuScenes?

Sure.
1. Cylinder3D (Cylindrical and Asymmetrical 3D Convolution Networks for LiDAR Segmentation) https://arxiv.org/pdf/2011.10033v1.pdf 
https://github.com/xinge008/Cylinder3D
2. (AF)-S3Net: Attentive Feature Fusion with Adaptive Feature Selection for Sparse Semantic Segmentation Network
https://arxiv.org/abs/2102.04530
3. AMVNet: Assertion-based Multi-View Fusion Network for LiDAR Semantic Segmentation 
https://arxiv.org/pdf/2012.04934.pdf

And here is the unofficial leader board: https://paperswithcode.com/sota/lidar-semantic-segmentation-on-nuscenes

**Comment by Wuziyi616** [comment]
Thank you for your suggestions. Cylinder3D is in our plan (maybe in July). For now, we do not have enough resources to do that. PRs are welcomed.
