### ISSUE TITLE
Inferring my own RGBD Dataset based on voteNet

### ISSUE THREAD

**Issue by mmmcn** [open-mmlab/mmdetection3d#592]
Hi, is there any transfomation of coordinates needed on my own RGBD data before sending it to the net?  
Thanks in advance.

**Comment by THU17cyz** [comment]
Hi, please refer to the depth coordinate system [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/bbox/structures/depth_box3d.py). VoteNet uses ScanNet and SUN RGB-D, and these two datasets are converted to this coordinate system. For example, you can see how SUN RGB-D raw data is converted to bounding boxes in depth coordinate system [here](https://github.com/open-mmlab/mmdetection3d/blob/e65772d4d8b22ed4819a73c324d07637674db65b/tools/data_converter/sunrgbd_data_utils.py#L32)

**Comment by ThePassedWind** [comment]
Could you please give a demo script to process own RGBD data?
