### ISSUE TITLE
why is hard_voxelize slower in gpu than in cpu

### ISSUE THREAD

**Issue by turboxin** [open-mmlab/mmdetection3d#593]
Hi all,

I noticed that hard_voxelize_gpu takes about 0.04s while hard_voxelize_cpu takes 0.02~0.03s, according to annotation:

https://github.com/open-mmlab/mmdetection3d/blob/926beda832c6e7deaa4a9467d22243936e488916/mmdet3d/ops/voxel/src/voxelization_cpu.cpp#L111
https://github.com/open-mmlab/mmdetection3d/blob/926beda832c6e7deaa4a9467d22243936e488916/mmdet3d/ops/voxel/src/voxelization_cuda.cu#L190

I'm wondering why is this case since normally it's faster in gpu.

**Comment by Tai-Wang** [comment]
It should be a typo. Although it has been a long time since we tested that (s.t. we can not exactly remember the number for the efficiency), we are sure the cuda version is faster than the cpu version at that time. With the update of cuda and GPUs, we believe it should be much faster now.
