### ISSUE TITLE
PartA2 Pointwise Semantic Head rotation direction

### ISSUE THREAD

**Issue by Divadi** [open-mmlab/mmdetection3d#594]
Hello, I was looking at PartA2's "pointwise-semantic-head" implementation, and I had a question regarding the following lines:
https://github.com/open-mmlab/mmdetection3d/blob/e65772d4d8b22ed4819a73c324d07637674db65b/mmdet3d/models/roi_heads/mask_heads/pointwise_semantic_head.py#L116-L122
here, we get the voxel centers inside ground truth 3D boxes, then translate them to GT bbox bottom center. Then, a rotation is done, rotating _negative yaw_. However, I thought that the points should be rotated _positive yaw_ to go from world coordinate orientation to orientation of the GT bbox, since I thought GT bbox yaw is positive yaw from world
I apologize if I am misunderstanding something - I see a similar thing done in OpenPCDet's repository 
https://github.com/open-mmlab/OpenPCDet/blob/7efdf026a341b5d9862ca419f9c5e08a3acc0577/pcdet/models/dense_heads/point_head_template.py#L114-L122
However, I adapted this same logic for another project but got odd results.

Thank you very much for your time

**Comment by THU17cyz** [comment]
Hi @Divadi, GT bbox yaw is positive yaw **from box to world**.

**Comment by Divadi** [comment]
Thank you for your response; I was using an outdated version of the repository with the wrong docstrings.
