### ISSUE TITLE
Higher numpy version request

### ISSUE THREAD

**Issue by RangiLyu** [open-mmlab/mmdetection3d#597]
mmpose requires numpy>1.20.0 but mmdet3d requires numpy<1.20.0. Is there any plan to upgrade the numpy version in this repo so that pose and det3d can run in the same environment?

related issue:
https://github.com/open-mmlab/mmpose/issues/677

**Comment by Tai-Wang** [comment]
It will be related to PR #378 for initialization refactor. After merging that, we can integrate with the latest mmdet then the latest numpy will be compatible. The refactor needs a little complicated benchmark regression and also the synchronized progress of some other codebases (like mmseg), so we expect it would be finished in the next month. We will push forward ASAP.
