### ISSUE TITLE
How long does it take to prepare Waymo dataset (and how much space the prepared dataset will take)?

### ISSUE THREAD

**Issue by haotian-liu** [open-mmlab/mmdetection3d#601]
Hi, thank you for the great work. I am trying to train and evaluate 3D models on Waymo dataset. I followed the instructions [here](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/data_preparation.md) to convert `tfrecord` files to KITTI format with the following command (I ran it on Google Cloud with a 96-core VM instance):

```Shell
python tools/create_data.py waymo --root-path ./data/waymo/ --out-dir ./data/waymo/ --workers 96 --extra-tag waymo
```

It takes around 2 days now, and `kitti_format` folder is around 3.1TB but it is still doing the conversion. Sometimes there is progressbar and sometimes there is not any updates.

May I ask how long usually does it take (what I should expect) to finish the data preparation for Waymo dataset, and how large I should expect it to be? The information might give some helpful anticipations. Thank you so much!

**Comment by wHao-Wu** [comment]
Hi, @haotian-liu 

I have pre-processed the Waymo dataset before. Unfortunately, it takes at least more than 5 days or even a week if smoothly. The `kitti_format` folder will take around ~3.8TB(~500G for testing, ~670G for validation, ~2.7T for training).

**Comment by Tai-Wang** [comment]
It does take a lot of time to pre-process the Waymo dataset. As @wHao-Wu mentioned, from my memory, it can take about at least 3 days depending on how many `workers` are used. It's really a heavy burden for a general computer, so we would consider to further optimize it in the future.

**Comment by haotian-liu** [comment]
Thanks @wHao-Wu and @Tai-Wang, I just got my jobs finished recently. The information is really helpful, thanks.

**Comment by demerzel1** [comment]
> It does take a lot of time to pre-process the Waymo dataset. As @wHao-Wu mentioned, from my memory, it can take about at least 3 days depending on how many `workers` are used. It's really a heavy burden for a general computer, so we would consider to further optimize it in the future.

Hi, is there any update on optimizing create Waymo data? It seems still need long processing time.

**Comment by wessam611** [comment]
I'm currently looking into using the Waymo dataset but unfortunately, storage is a problem for my case. I was wondering if it's possible to implement a new Dataset such that it reads from tf-records directly from Waymo's google drive storage (maybe pre-downloading tf-records and deleting them when they're not needed). I want to work on that but I'm not sure if it's possible so please tell me if you know about the possibility of that as I couldn't find much info about it anywhere.
