### ISSUE TITLE
Can you give some advise about how to understand the prepareSubMGridKernel ?

### ISSUE THREAD

**Issue by qfwysw** [open-mmlab/mmdetection3d#610]
path: mmdet3d/ops/spconv/include/spconv/indice.cu.h
I want to know how the Sparse Convolution works. I can't debug the code with cuda c, so I really don't know how to under the following code. If you can, can you give me some hints so that I can understand what the whole code does.

template <typename Index, typename IndexGrid, unsigned NDim>
__global__ void prepareSubMGridKernel(
    tv::TensorView<const Index> indicesIn, tv::TensorView<IndexGrid> gridsOut,
    const tv::SimpleVector<Index, NDim> outSpatialShape) {
  auto numActIn = indicesIn.dim(0);
  Index spatialVolume = 1;
#pragma unroll
  for (int i = 0; i < NDim; ++i) {
    spatialVolume *= outSpatialShape[i];  // outSpatialShape: [41, 1600, 1408]
  }
  Index index = 0;
  for (int ix : tv::KernelLoopX<int>(numActIn)) {  
    index = tv::rowArrayIdx<Index, NDim>(indicesIn.data() + ix * (NDim + 1) + 1, outSpatialShape.data()) +
            spatialVolume * indicesIn(ix, 0);
    gridsOut[index] = ix;
  }
}

**Comment by Wuziyi616** [comment]
I think you can refer to the SECOND paper for how the Sparse Conv works? It's proposed in their work.

**Comment by qfwysw** [comment]
Thank you very much for your reply. I have read the SECOND paper, I want to know how the code works.Is there any way to let me see the values of these variables in the code with cuda c?

**Comment by Wuziyi616** [comment]
Unfortunately no. It's really hard to debug the cuda code. You can add some output function in the cuda code and re-compile it, but I don't recommend doing so.
If I remember correctly, the spconv code of SECOND is modified from [this paper](https://github.com/facebookresearch/SparseConvNet), which has more detailed description of the sparse conv operation. Maybe you can refer to that paper?

**Comment by qfwysw** [comment]
I am really thanks for your help. I have read the paper, it makes me clear about how the sparse convolution works. Maybe I should learn some knowledge about cuda c, so that I can know how the code works. Anyway, thank you for your generous helpAnyway, thank you for your generous help.

**Comment by Wuziyi616** [comment]
Glad it helps :)
