### ISSUE TITLE
KITTI  calibration Intrinsic parameters

### ISSUE THREAD

**Issue by HosseinSheikhi** [open-mmlab/mmdetection3d#614]
I am trying to test FCOS3D on KITTI mono data set. After following test and train on customize data to make KITTI as same as NuScenes. After running ` python tools/test.py  configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_kitti-mono3d.py checkpoints/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210427_091419-35aaaad0.pth --show --show-dir ./data/kitti/show_results` 
I faced with the following error:

```
loading annotations into memory...
Done (t=0.11s)
creating index...
index created!
/home/mh/anaconda3/lib/python3.8/site-packages/mmcv/cnn/bricks/conv_module.py:107: UserWarning: ConvModule has norm and bias at the same time
  warnings.warn('ConvModule has norm and bias at the same time')
Use load_from_local loader
[                                                  ] 0/7518, elapsed: 0s, ETA:

Traceback (most recent call last):
  File "tools/test.py", line 214, in <module>
    main()
  File "tools/test.py", line 184, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/home/mh/mmdetection3d/mmdet3d/apis/test.py", line 46, in single_gpu_test
    model.module.show_results(data, result, out_dir)
  File "/home/mh/mmdetection3d/mmdet3d/models/detectors/single_stage_mono3d.py", line 213, in show_results
    show_multi_modality_result(
  File "/home/mh/mmdetection3d/mmdet3d/core/visualizer/show_result.py", line 250, in show_multi_modality_result
    show_img = draw_bbox(
  File "/home/mh/mmdetection3d/mmdet3d/core/visualizer/image_vis.py", line 205, in draw_camera_bbox3d_on_img
    cam_intrinsic = cam_intrinsic.reshape(3, 3).float().cpu()
RuntimeError: shape '[3, 3]' is invalid for input of size 16
```

The cam_intrinsic is `[[721.5377, 0.0, 609.5593, 44.85728], [0.0, 721.5377, 172.854, 0.2163791], [0.0, 0.0, 1.0, 0.002745884], [0.0, 0.0, 0.0, 1.0]]` - a 4x4 matrix, and I dont know how a intrinsic matrix could be 4x4- while when running FCOS3D on NuScenes successfully, the intrinsic matrix is  ` [[1272.5979470598488, 0.0, 826.6154927353808], [0.0, 1272.5979470598488, 479.75165386361925], [0.0, 0.0, 1.0]]` that makes more sense. 

More info: For FCOS3D config I use the following base configurations:
```
_base_ = [
    '../_base_/datasets/kitti-mono3d-3class.py', '../_base_/models/fcos3d_kitti.py',
    '../_base_/schedules/mmdet_schedule_1x.py', '../_base_/default_runtime.py'
]
```

**Comment by Tai-Wang** [comment]
Since there are some parameters to transform the coordinate to the referenced camera (like the translation between camera 2 and referenced camera 0), the intrinsic matrix in KITTI is 4x4. In contrast, this problem does not exist in nuScenes. Please refer to the KITTI [paper](http://www.cvlibs.net/publications/Geiger2013IJRR.pdf) and issue #490 , #517 for related information and [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/scripts/export_kitti.py#L144) for the relationship between intrinsic matrices of nuScenes and KITTI.

**Comment by HosseinSheikhi** [comment]
I still could not figure it out. For now, am using the `[721.5377, 0.0, 609.5593], [0.0, 721.5377, 172.854], [0.0, 0.0, 1.0]` for drawing bounding boxes. However, the intrinsic must be a little different from the projection matrix.

**Comment by lyuwenyu** [comment]
> I still could not figure it out. For now, am using the `[721.5377, 0.0, 609.5593], [0.0, 721.5377, 172.854], [0.0, 0.0, 1.0]` for drawing bounding boxes. However, the intrinsic must be a little different from the projection matrix.

Hi, Do you training KITTI successful? Can you share the final performance results. 
Thanks a lot.
