### ISSUE TITLE
Some problems about centerpoint

### ISSUE THREAD

**Issue by HzzzW** [open-mmlab/mmdetection3d#626]
When i just run 

**./tools/dist_test.sh configs/centerpoint/centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus.py checkpoints/centerpoint_0075voxel_second_secfpn_dcn_circlenms_4x8_cyclic_20e_nus_20200930_201619-67c8496f.pth  6 --eval mAP**

I can get the following results

**mAP: 0.5720                                                                     
mATE: 0.2918
mASE: 0.2558
mAOE: 0.2995
mAVE: 0.2760
mAAE: 0.1886
NDS: 0.6549**

How can i  get  the indicators for evaluating tracking performance,such as **MOTA,MOTP**?

**Comment by wHao-Wu** [comment]
Hi, @HzzzW 

We cannot support tracking evaluation but only 3D detection and 3D segmentation evaluation in our repo for now.
