### ISSUE TITLE
batch size

### ISSUE THREAD

**Issue by Jsijon** [open-mmlab/mmdetection3d#63]
is there a way to define batch size, in order to be able to run in gpus with lower ram ?
i didn't find anything related tin config files

**Comment by Tai-Wang** [comment]
You can adjust the 'samples_per_gpu' in dataset configs (like configs/_base_/datasets/kitti-3d-car.py).

**Comment by Jsijon** [comment]
i had changed samples_per_gpu to 1,
but i still have issues with vram.

i see that when i set samples_per_gpu =1 ,
it uses 50 samples per iteration.
Can i get lower than that, to manage yo run it ?
