### ISSUE TITLE
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'

### ISSUE THREAD

**Issue by jasmine202106** [open-mmlab/mmdetection3d#631]
when i try to run: 
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
i got such a TypeError.

Traceback (most recent call last):
  File "demo/pcd_demo.py", line 3, in <module>
    from mmdet3d.apis import inference_detector, init_model, show_result_meshlab
  File "/home/liey/3D_multiview/mmdetection3d/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/home/liey/3D_multiview/mmdetection3d/mmdet3d/apis/inference.py", line 10, in <module>
    from mmdet3d.core import (Box3DMode, DepthInstance3DBoxes,
  File "/home/liey/3D_multiview/mmdetection3d/mmdet3d/core/__init__.py", line 3, in <module>
    from .evaluation import *  # noqa: F401, F403
  File "/home/liey/3D_multiview/mmdetection3d/mmdet3d/core/evaluation/__init__.py", line 2, in <module>
    from .kitti_utils import kitti_eval, kitti_eval_coco_style
  File "/home/liey/3D_multiview/mmdetection3d/mmdet3d/core/evaluation/kitti_utils/__init__.py", line 1, in <module>
    from .eval import kitti_eval, kitti_eval_coco_style
  File "/home/liey/3D_multiview/mmdetection3d/mmdet3d/core/evaluation/kitti_utils/eval.py", line 3, in <module>
    import numba
  File "/home/liey/.local/lib/python3.7/site-packages/numba/__init__.py", line 196, in <module>
    import numba.typed
  File "/home/liey/.local/lib/python3.7/site-packages/numba/typed/__init__.py", line 3, in <module>
    from .typeddict import Dict
  File "/home/liey/.local/lib/python3.7/site-packages/numba/typed/typeddict.py", line 19, in <module>
    @njit
  File "/home/liey/.local/lib/python3.7/site-packages/numba/decorators.py", line 238, in njit
    return jit(*args, **kws)
  File "/home/liey/.local/lib/python3.7/site-packages/numba/decorators.py", line 175, in jit
    return wrapper(pyfunc)
  File "/home/liey/.local/lib/python3.7/site-packages/numba/decorators.py", line 191, in wrapper
    **dispatcher_args)
  File "/home/liey/.local/lib/python3.7/site-packages/numba/dispatcher.py", line 650, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/home/liey/.local/lib/python3.7/site-packages/numba/targets/registry.py", line 50, in target_context
    return self._toplevel_target_context
  File "/home/liey/.local/lib/python3.7/site-packages/numba/utils.py", line 399, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/liey/.local/lib/python3.7/site-packages/numba/targets/registry.py", line 34, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/home/liey/.local/lib/python3.7/site-packages/numba/targets/base.py", line 260, in __init__
    self.init()
  File "/home/liey/.local/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/liey/.local/lib/python3.7/site-packages/numba/targets/cpu.py", line 51, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/home/liey/.local/lib/python3.7/site-packages/numba/targets/codegen.py", line 628, in __init__
    self._init(self._llvm_module)
  File "/home/liey/.local/lib/python3.7/site-packages/numba/targets/codegen.py", line 637, in _init
    tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'

could anybody help me to solve this? thanks a lot.

**Comment by Wuziyi616** [comment]
Please first run `python mmdet3d/utils/collect_env.py` to show your environment. It may be version error of numba.

**Comment by jasmine202106** [comment]
python mmdet3d/utils/collect_env.py
sys.platform: linux
Python: 3.7.2 (default, Oct 25 2019, 11:16:13) [GCC 5.4.0 20160609]
CUDA available: True
GPU 0,1: TITAN RTX
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.168
GCC: gcc (Ubuntu 7.5.0-6ubuntu3) 7.5.0
PyTorch: 1.8.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.1 Product Build 20200208 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.3, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.1
OpenCV: 4.1.1
MMCV: 1.3.5
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.11.0
MMSegmentation: 0.14.0
MMDetection3D: 0.14.0+c33d4ec

**Comment by Wuziyi616** [comment]
What about the numpy version? We currently only support numpy < 1.20.0 (1.19.5 and lower)

**Comment by jasmine202106** [comment]
python
Python 3.7.2 (default, Oct 25 2019, 11:16:13) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.19.1'
>>> 

the numpy version is 1.19.1

**Comment by jasmine202106** [comment]
maybe the issue is cased by the incompatible of numba and llvmlite. 
but when i install llvmlite0.31.0, it shows "Successfully installed llvmlite-0.36.0", and from python import llvmlite, it shows llvmlite version is 0.33.0???
how can i install llvmlite0.31.0?


python -m pip install **llvmlite==0.31.0**
Defaulting to user installation because normal site-packages is not writeable
Collecting llvmlite==0.31.0
Using cached llvmlite-0.31.0-cp37-cp37m-manylinux1_x86_64.whl (20.2 MB)
Installing collected packages: llvmlite
Successfully installed **llvmlite-0.36.0**
WARNING: You are using pip version 20.3.4; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/bin/python3.7 -m pip install --upgrade pip' command.
liey@liey-HP-Z840-Workstation:~$ python
Python 3.7.2 (default, Oct 25 2019, 11:16:13)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.

            import llvmlite
            **llvmlite.version
            '0.33.0+1.g022ab0f'**

**Comment by Wuziyi616** [comment]
Sorry for the late reply. I agree this may be related to llvmlite. It's very strange you can't downgrade it.
Can you try first `pip uninstall llvmlite`. Then import it in python to make sure it's uninstalled. Then use `pip install llvmlite==0.31.0`?
If that doesn't work, try other version of llvmlite like 0.32.1?

**Comment by Wuziyi616** [comment]
Seems that [this](https://github.com/rapidsai/cuml/issues/2389#issuecomment-656787029) is a good setting? Can have a try.

**Comment by jasmine202106** [comment]
**python -m pip install -U llvmlite==0.31.0** 
Defaulting to user installation because normal site-packages is not writeable
Collecting llvmlite==0.31.0
  Using cached llvmlite-0.31.0-cp37-cp37m-manylinux1_x86_64.whl (20.2 MB)
Installing collected packages: llvmlite
Successfully installed llvmlite-0.36.0
WARNING: You are using pip version 20.3.4; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/bin/python3.7 -m pip install --upgrade pip' command.


**python -m pip uninstall llvmlite** 
Found existing installation: llvmlite 0.33.0+1.g022ab0f
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.


**python -m pip install -U llvmlite==0.32.1** 
Defaulting to user installation because normal site-packages is not writeable
Collecting llvmlite==0.32.1
  Using cached llvmlite-0.32.1-cp37-cp37m-manylinux1_x86_64.whl (20.2 MB)
Installing collected packages: llvmlite
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
**numba 0.48.0 requires llvmlite<0.32.0,>=0.31.0dev0, but you have llvmlite 0.32.1 which is incompatible.**
Successfully installed llvmlite-0.36.0
WARNING: You are using pip version 20.3.4; however, version 21.1.2 is available.
You should consider upgrading via the '/usr/bin/python3.7 -m pip install --upgrade pip' command.

they all doesn't work.  :( :( :(

**Comment by Wuziyi616** [comment]
From this line "numba 0.48.0 requires llvmlite<0.32.0,>=0.31.0dev0, but you have llvmlite 0.32.1 which is incompatible.", I think the bug is indeed caused by the incompatibility of llvmlite and numba. The installed (0.31.0), showed (0.36.0) and installed (0.33.0) versions of llvmlite are so confusing to me. I will try to look into this tomorrow.

**Comment by Wuziyi616** [comment]
Sorry for the late reply. I check my workspace, it's llvmlite 0.31.0 and numba 0.48.0. I tried to search why you can't install this version of llvmlite but failed... The last solution may be to re-create a new and clean conda environment. You can try installing llvmlite 0.31.0 and numba 0.48.0 first in this new environment?

**Comment by jasmine202106** [comment]
I searched llvmlite files and delete those whose version are 0.32 or 0.36. Then i reinstall the llvmlite 0.31.0. Then llvmlite is ok now. i don't know the reason, but it actually work.

python
Python 3.7.2 (default, Oct 25 2019, 11:16:13) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import llvmlite
>>> llvmlite.__version__
'0.31.0'

thanks very much for your hard work.

**Comment by Wuziyi616** [comment]
Glad that works :)
