### ISSUE TITLE
Can not get the same performance in 'SECOND'.

### ISSUE THREAD

**Issue by JeffWang987** [open-mmlab/mmdetection3d#632]
In mmdet3d's model zoo, SECOND can achieve 79.07 mAP on car moderate.
However, in my implementation, to train with config 'hv_second_secfpn_6x8_80e_kitti-3d-car.py' with no parameter changed(GPU:8 ; batch size:6). I only got 77.2320 mAP.

Really need advice! Thx in advance.

More details:
epoch 37: 77.6471
epoch 38: 77.7228
epoch 39: 77.4195
epoch 40: 77.2320

**Comment by THU17cyz** [comment]
Hi @JeffWang987 , 

I've run the code and got 78.55. Perhaps it's just caused by randomness in training.
