### ISSUE TITLE
gpu memory used error

### ISSUE THREAD

**Issue by mrqrs** [open-mmlab/mmdetection3d#636]
I have trained the second model in different GPU（2070 and v100），the GPU memory used was different。
batch_size：2
RTX2070：
![image](https://user-images.githubusercontent.com/26370029/121631500-cc449180-cab1-11eb-96ea-9d7610111b50.png)
V100:
![image](https://user-images.githubusercontent.com/26370029/121631542-dcf50780-cab1-11eb-925e-170e85c46dc3.png)

mmdetection3d:0.13.0

**Comment by Wuziyi616** [comment]
The GPU memory may change dynamically during training process. Is the memory printed in the commandline the same? Also just to make sure, you use same number of card and same batch size?

**Comment by mrqrs** [comment]
Thanks for your reply. the commandline is the same. RTX2070: memory: 2993, V100: memory: 2880, and the batch size is 2. But in nvidia-smi, the V100 outputs the momory as the figure shows

**Comment by mrqrs** [comment]
> The GPU memory may change dynamically during training process. Is the memory printed in the commandline the same? Also just to make sure, you use same number of card and same batch size?

Thanks for your reply. the commandline is the same. RTX2070: memory: 2993, V100: memory: 2880, and the batch size is 2. But in nvidia-smi, the V100 outputs the momory as the figure shows

**Comment by Wuziyi616** [comment]
Maybe related to different torch version? Also GPU usage could vary among different GPU architecture (although I agree it shouldn't be this large). But I don't think this is a big issue or a bug?

**Comment by mrqrs** [comment]
> Maybe related to different torch version? Also GPU usage could vary among different GPU architecture (although I agree it shouldn't be this large). But I don't think this is a big issue or a bug?

After debug，I found it is the problem of the spconv. When i used the spconv 1.2.1, the memory used is the same in different gpus.

**Comment by Wuziyi616** [comment]
Thank you for your effort. Let's continue the discussion in #639
