### ISSUE TITLE
How to create semantickitti_infos.pkl?

### ISSUE THREAD

**Issue by abhinavagarwalla** [open-mmlab/mmdetection3d#638]
I wanted to train a network on SemanticKITTI. I noticed that a dataset class is provided for SemanticKITTI. However, there is no way to extract the info pkl file "" as in [testing](https://github.com/open-mmlab/mmdetection3d/tree/4002f06cc0e42e79528a04992fa35847b971077c/tests/data/semantickitti).
Am I missing something?

**Comment by Wuziyi616** [comment]
SemanticKITTI is not currently supported. We planned to support Cylinder3D model on SemanticKITTI but that was blocked by some accident. We will try to support it in July (or August).
