### ISSUE TITLE
the issue of spconv

### ISSUE THREAD

**Issue by mrqrs** [open-mmlab/mmdetection3d#639]
I run the custom model on the mmdet3d. As the same model, when i use mmdet3d's spconv , the used GPU memory is the 3823 MB, and the [spconv1.2.1](https://github.com/traveller59/spconv) 's is the 2223 MB.

**Comment by Wuziyi616** [comment]
If I remember correctly, we use spconv 1.0. It's possible that spconv 1.2.1 make some improvements to decrease GPU memory usage. But the behavior of these two versions of spconv should be identical.

**Comment by mrqrs** [comment]
> If I remember correctly, we use spconv 1.0. It's possible that spconv 1.2.1 make some improvements to decrease GPU memory usage. But the behavior of these two versions of spconv should be identical.
> 
> Also I don't this is a bug or a big issue.

As the question #636 ,the mmdet3d’s spconv will make different collected gpu memory in different gpu.

**Comment by Wuziyi616** [comment]
I am not familiar with CUDA programming. But I know sometimes we read in some parameters about THREAD or BLOCK of current GPU, and allocate variables according to these numbers. Is it because V100's params are larger than 2070, so it allocates larger memory to variables. As a result, it uses more memory (of course, it will run faster)?

**Comment by mrqrs** [comment]
Thanks for your replay. I have tested the mmdet3d's spconv and spconv1.2.1 on 2080ti, the result is:
batch_size=2
mmdet3d:
![image](https://user-images.githubusercontent.com/26370029/121762692-3caee980-cb6a-11eb-99e5-88b5a88bd4f2.png)
50 iters: about 20s, time: 0.563~, used gpu memory: 9517MB
spconv1.2.1:
![image](https://user-images.githubusercontent.com/26370029/121762774-9d3e2680-cb6a-11eb-8adb-bb6fe46108dc.png)
50 iters: about 29s, time:0.565~, used gpu memory: 4635MB

**Comment by Wuziyi616** [comment]
Thank you so much for the info you provided. Both training behavior seems normal to me. SPConv 1.0 even runs faster?

I have checked their changelog and indeed SPConv 1.2.1 optimize their GPU efficiency. But the input output running behavior is the same. So this won't affect our model or benchmark. We may replace our SPConv with newest version in the future.

**Comment by mrqrs** [comment]
> Thank you so much for the info you provided. Both training behavior seems normal to me. SPConv 1.0 even runs faster?
> 
> I have checked their changelog and indeed SPConv 1.2.1 optimize their GPU efficiency. But the input output running behavior is the same. So this won't affect our model or benchmark. We may replace our SPConv with newest version in the future.
Do you find the allocated GPU memory is the different in different GPU?

**Comment by Wuziyi616** [comment]
I have tried mmdet3d on Titan XP and 2080Ti before. The GPU memory is indeed different, though the gap is not that large as you posted before.

**Comment by mrqrs** [comment]
> I have tried mmdet3d on Titan XP and 2080Ti before. The GPU memory is indeed different, though the gap is not that large as you posted before.
> 
> If you really worry about the code behavior, I think the simplest way is to train one model under the same setting using two versions of spconv (or two different gpu) respectively and compare the performance?

Thanks for your reply. I am training the code using the spconv1.2.1. I will compare the results and reply this issue.

**Comment by Wuziyi616** [comment]
Yeah looking forward to that! Would be great if you could also report the training time, etc. And just out of curiosity, may I ask why you care about this issue so much? Because from my perspective, both SPConv is ok to run as long as their behavior are the same. Are you going to deploy mmdet3d so that the GPU consumption is a key factor?

**Comment by mrqrs** [comment]
> Yeah looking forward to that! Would be great if you could also report the training time, etc. And just out of curiosity, may I ask why you care about this issue so much? Because from my perspective, both SPConv is ok to run as long as their behavior are the same. Are you going to deploy mmdet3d so that the GPU consumption is a key factor?

I just use mmdet3d to train custom model. When i trained the model on 4 GPUS, and  enlarged the bath_size, i found the batch size <=2 was valid. Bath size > 2 will cause the memory error.  When using spconv1.2.1, the batch size can be set 8.

**Comment by Wuziyi616** [comment]
Oh I got it. Again thank you for your effort by looking into this issue deeply! We really appreciate your effort and looking forward to your results.

**Comment by mrqrs** [comment]
> Oh I got it. Again thank you for your effort by looking into this issue deeply! We really appreciate your effort and looking forward to your results.

After trained the custom model with different spconv, the results of model are same. I think the spconv model in the mmdet3d may be needed to improve in the future. Tanks for your reply about this issue.

**Comment by Wuziyi616** [comment]
Yeah sure for that! I will raise this in this week's discussion. Thank you for your effort and good job!
