### ISSUE TITLE
The result for benchmark is strange.

### ISSUE THREAD

**Issue by coralemon** [open-mmlab/mmdetection3d#640]
I run the code with configuration file 'mmdetection3d/configs/pointpillars/hv_pointpillars_secfpn_6x8_160e_kitti-3d-3class.py' 
but get the bad performance on pedestrian and cyclist.
Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:0.9885, 1.0556, 1.0224
bev  AP:52.6360, 48.6358, 46.3628
**3d   AP:4.7276, 4.7371, 4.7490**
aos  AP:0.85, 0.89, 0.86
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:0.9885, 1.0556, 1.0224
bev  AP:66.5513, 64.3058, 60.8306
3d   AP:33.9663, 31.5340, 29.3592
aos  AP:0.85, 0.89, 0.86
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0201
bev  AP:68.5603, 56.8919, 54.4505
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.02
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:0.0000, 0.0000, 0.0201
bev  AP:77.4139, 63.7899, 61.8875
3d   AP:38.2034, 28.1662, 27.2001
aos  AP:0.00, 0.00, 0.02

the code and configuration(except for path) are not modified.

**Comment by THU17cyz** [comment]
Hi @coralemon , I have run the benchmark and the result is correct:

```Pedestrian AP@0.50, 0.50, 0.50:
bbox AP:63.7022, 59.9143, 56.3094
bev  AP:58.9039, 53.2491, 48.1826
3d   AP:50.1291, 44.8227, 40.9976
aos  AP:44.80, 42.39, 39.82
Pedestrian AP@0.50, 0.25, 0.25:
bbox AP:63.7022, 59.9143, 56.3094
bev  AP:70.6633, 67.8437, 63.5928
3d   AP:70.5493, 66.4137, 63.2846
aos  AP:44.80, 42.39, 39.82
Cyclist AP@0.50, 0.50, 0.50:
bbox AP:83.5030, 73.0496, 69.5579
bev  AP:80.6365, 65.9354, 61.6035
3d   AP:78.8606, 61.1495, 57.8799
aos  AP:82.36, 69.38, 66.00
Cyclist AP@0.50, 0.25, 0.25:
bbox AP:83.5030, 73.0496, 69.5579
bev  AP:83.9682, 71.1222, 67.6369
3d   AP:83.9673, 71.1168, 67.6369
aos  AP:82.36, 69.38, 66.00
Car AP@0.70, 0.70, 0.70:
bbox AP:90.7281, 89.1073, 86.5109
bev  AP:89.8881, 84.9321, 79.3786
3d   AP:83.6882, 72.6839, 67.5085
aos  AP:90.67, 88.67, 85.74
Car AP@0.70, 0.50, 0.50:
bbox AP:90.7281, 89.1073, 86.5109
bev  AP:90.7786, 89.9947, 89.2161
3d   AP:90.7786, 89.8991, 88.9348
aos  AP:90.67, 88.67, 85.74

Overall AP@easy, moderate, hard:
bbox AP:79.3111, 74.0238, 70.7927
bev  AP:76.4762, 68.0389, 63.0549
3d   AP:70.8926, 59.5520, 55.4620
aos  AP:72.61, 66.82, 63.85

```

Please check your KITTI data (refer to the [docs](https://mmdetection3d.readthedocs.io/en/latest/data_preparation.html#kitti)) and perhaps pull the lastest version and recompile.

**Comment by Wuziyi616** [comment]
I also trained a model and the results are good. Maybe you should pull mmdet3d and have a try again.

**Comment by coralemon** [comment]
Thanks for your response and I have solved this problem! Thanks a lot!

在 2021年6月17日，下午8:42，Ziyi Wu ***@***.******@***.***>> 写道：



Closed #640<https://github.com/open-mmlab/mmdetection3d/issues/640>.

**Comment by Gaviaa** [comment]
Hello, how did you solve this problem? I also encountered this problem on other models.

**Comment by coralemon** [comment]
It may be that the definition of the center point is different, for example, some takes the bottom center as the z-center, and some takes the center of the 3D bounding box, so it is necessary to subtract half of the height or check the loader during the evaluation.

**Comment by coralemon** [comment]
> Hello, how did you solve this problem? I also encountered this problem on other models.

It may be that the definition of the center point is different, for example, some takes the bottom center as the z-center, and some takes the center of the 3D bounding box, so it is necessary to subtract half of the height or check the loader during the evaluation.
