### ISSUE TITLE
Problem in replicating the repo

### ISSUE THREAD

**Issue by Ironman1508** [open-mmlab/mmdetection3d#643]
hi, Can someone help me out how to resolve the error when i'm replicating the repo.

Using Azure ubuntu18.02 VM with teslak80gpu

- installed Anaconda
- Installed cuda 10.1
- Created virtual environment in name"open-mmlab"
- followed steps in **getting started.md**
- installed pytorch=1.5.0 using the command in the **getting started.md**
- in step **F** , I run the below command
git clone https://github.com/open-mmlab/mmdetection3d.git
cd mmdetection3d
**python setup.py develop**

getting this below message

(base) das@lidar3d:~$ conda activate open-mmlab
(open-mmlab) das@lidar3d:~$ cd mmdetection3d
(open-mmlab) das@lidar3d:~/mmdetection3d$ python setup.py develop
running develop
running egg_info
writing mmdet3d.egg-info/PKG-INFO
writing dependency_links to mmdet3d.egg-info/dependency_links.txt
writing requirements to mmdet3d.egg-info/requires.txt
writing top-level names to mmdet3d.egg-info/top_level.txt
reading manifest file 'mmdet3d.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'mmdet3d/model_zoo.yml'
warning: no files found matching '*.py' under directory 'mmdet3d/configs'
warning: no files found matching '*.yml' under directory 'mmdet3d/configs'
warning: no files found matching '*.sh' under directory 'mmdet3d/tools'
warning: no files found matching '*.py' under directory 'mmdet3d/tools'
warning: no files found matching '*.png' under directory 'mmdet3d/demo'
warning: no files found matching '*.jpg' under directory 'mmdet3d/demo'
warning: no files found matching '*.bin' under directory 'mmdet3d/demo'
warning: no files found matching '*.pkl' under directory 'mmdet3d/demo'
warning: no files found matching '*.py' under directory 'mmdet3d/demo'
writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.7/mmdet3d/ops/spconv/sparse_conv_ext.cpython-37                                                                                        m-x86_64-linux-gnu.so -> mmdet3d/ops/spconv
copying build/lib.linux-x86_64-3.7/mmdet3d/ops/iou3d/iou3d_cuda.cpython-37m-x86_                                                                                        64-linux-gnu.so -> mmdet3d/ops/iou3d
copying build/lib.linux-x86_64-3.7/mmdet3d/ops/voxel/voxel_layer.cpython-37m-x86                                                                                        _64-linux-gnu.so -> mmdet3d/ops/voxel
copying build/lib.linux-x86_64-3.7/mmdet3d/ops/roiaware_pool3d/roiaware_pool3d_e                                                                                        xt.cpython-37m-x86_64-linux-gnu.so -> mmdet3d/ops/roiaware_pool3d
copying build/lib.linux-x86_64-3.7/mmdet3d/ops/ball_query/ball_query_ext.cpython                                                                                        -37m-x86_64-linux-gnu.so -> mmdet3d/ops/ball_query
copying build/lib.linux-x86_64-3.7/mmdet3d/ops/knn/knn_ext.cpython-37m-x86_64-li                                                                                        nux-gnu.so -> mmdet3d/ops/knn
copying build/lib.linux-x86_64-3.7/mmdet3d/ops/paconv/assign_score_withk_ext.cpy                                                                                        thon-37m-x86_64-linux-gnu.so -> mmdet3d/ops/paconv
copying build/lib.linux-x86_64-3.7/mmdet3d/ops/group_points/group_points_ext.cpy                                                                                        thon-37m-x86_64-linux-gnu.so -> mmdet3d/ops/group_points
copying build/lib.linux-x86_64-3.7/mmdet3d/ops/interpolate/interpolate_ext.cpyth                                                                                        on-37m-x86_64-linux-gnu.so -> mmdet3d/ops/interpolate
copying build/lib.linux-x86_64-3.7/mmdet3d/ops/furthest_point_sample/furthest_po                                                                                        int_sample_ext.cpython-37m-x86_64-linux-gnu.so -> mmdet3d/ops/furthest_point_sam                                                                                        ple
copying build/lib.linux-x86_64-3.7/mmdet3d/ops/gather_points/gather_points_ext.c                                                                                        python-37m-x86_64-linux-gnu.so -> mmdet3d/ops/gather_points
Creating /home/das/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet3d                                                                                        .egg-link (link to .)
mmdet3d 0.14.0 is already the active version in easy-install.pth

Installed /home/das/mmdetection3d
Processing dependencies for mmdet3d==0.14.0
**error: importlib-metadata 4.5.0 is installed but importlib-metadata<4 is require                                                                                        d by {'ipykernel'}**

**Comment by Wuziyi616** [comment]
Can you follow the error message and downgrade importlib-metadata to lower than 4? I believe this is package related to conda.

**Comment by Ironman1508** [comment]
> Can you follow the error message and downgrade importlib-metadata to lower than 4? I believe this is package related to conda.

I was able to avoid this error, by running ### **pip install -v -e .**

but after this when i run the demo command to verify the installation, I ended up with new issue. so can you tell me what how to degrade to the version mentioned in the error message. or something wrong am I doing.

I run the below command
- python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

output: was
**### _No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "demo/pcd_demo.py", line 3, in <module>
    from mmdet3d.apis import inference_detector, init_model, show_result_meshlab
  File "/home/das/mmdetection3d/mmdet3d/__init__.py", line 35, in <module>
    f'MMDET=={mmdet.__version__} is used but incompatible. ' \
AssertionError: MMDET==2.13.0 is used but incompatible. Please install mmdet>=2.10.0, <=2.11.0._**

**Comment by Wuziyi616** [comment]
Oh, that's very simple. If you install mmdet via pip, simply run `pip uninstall mmdet` to uninstall mmdet 2.13.0 and then run `pip install mmdet==2.11.0` to install mmdet 2.11.0.

**Comment by Wuziyi616** [comment]
Hi @Ironman1508, have you successfully solved the problem?

**Comment by Ironman1508** [comment]
> Hi @Ironman1508, have you successfully solved the problem?

Hi @Wuziyi616 , Just didn't try the solution yet, as i'm facing some issue in cuda and nvidia driver(As you see in the previous error output itself,  ### **No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda**) so, I'm trying resolve this first. And I'm using a Azure virtual machine so which is common to have this problem. And immediately try to resolve the previous problem as per you solution and suggestion.

**Comment by Ironman1508** [comment]
> Hi @Ironman1508, have you successfully solved the problem?

Hi @Wuziyi616, sorry for asking so many question. I'm just new into this field, Actually I'm trying to implement this repo in a Azure virtual machine(ubuntu18.04 & NC6 promo machine(Tesla k80GPU)) and there is some problem with cuda10.1 and cudnn7.6.5. So can you please prefer any other machine which would work out for this repo and tell which cudnn is required for this?

**Comment by Wuziyi616** [comment]
K80 might a bit old for CUDA 10.1. What about a machine with 1080Ti or Titan XP or 2080 Ti or newer GPUs? The cudnn version doesn't matter too much for pytorch because you can use conda to install them. You only need a CUDA (actually the nvcc compiler in it).

**Comment by Wuziyi616** [comment]
Feel free to re-open this PR should you have any further questions :)
