### ISSUE TITLE
How do I use Waymo's test criteria (AP/APH) to test my own data set?

### ISSUE THREAD

**Issue by clytze0216** [open-mmlab/mmdetection3d#649]
Hello! mmdetection3d Team
I want to ask How do I use Waymo's test criteria (AP/APH) to test my own data set?
Looking forward to your reply! Thanks a lot!

**Comment by Wuziyi616** [comment]
We currently use the official C++ program provided by Waymo to calculate their metrics. You may need to refer to their [repo](https://github.com/waymo-research/waymo-open-dataset) for how to prepare GT labels and how to save the prediction results for evaluation. We also have a tutorial [here](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/tutorials/waymo.md) about how to train and test on Waymo.

**Comment by clytze0216** [comment]
@Wuziyi616 Thanks for your reply!!!!
Sorry to bother you again. I'm a green hand in this field.
 would like to ask if I want to use my own .bag or .lvx file to inference with the Livox Detection model, there are 5 classes of detection data.But I want to test the AP/APH values,  how do I do that?Thank you very much!
(The Livox Detection model does not test AP/APH, but only outputs the number of detected objects and uses RVIZ for visualization)
Looking forward to your reply! Thanks a lot!!!!!!!!!

**Comment by Wuziyi616** [comment]
I am not familiar with Livox Detection. And I don't know what's .bag or .lvx file format. Maybe you need to convert them into some common formats?

My main question is, why you open this PR under mmdet3d? Do you want to adopt our evaluation code? I don't think Waymo test criteria is necessary (I think KITTI like criteria is also good). Maybe you can convert the GT and saved results into our mmdet3d format and call our KITTI evaluate code?
