### ISSUE TITLE
numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by superchenyan** [open-mmlab/mmdetection3d#650]
when run :    python tools/test.py configs/votenet/votenet_8x8_scannet-3d-18class.py \
    checkpoints/votenet_8x8_scannet-3d-18class_20200620_230238-2cea9c3a.pth \
    --show --show-dir ./data/scannet/show_results

*Traceback (most recent call last):
  File "tools/test.py", line 12, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/apis/inference.py", line 10, in <module>
    from mmdet3d.core import (Box3DMode, DepthInstance3DBoxes,
  File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 1, in <module>
    from mmdet.core.anchor import build_anchor_generator
  File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/__init__.py", line 5, in <module>
    from .mask import *  # noqa: F401, F403
  File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/mask/structures.py", line 6, in <module>
    import pycocotools.mask as maskUtils
  File "/home/chenyan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by superchenyan** [comment]
cuda 11.0 + pytorch 1.7.1 + with '-gencode=arch=compute_80,code=sm_80' ,installl the mmdetection3d

**Comment by superchenyan** [comment]
Installed /media/chenyan/DATA/baidu/mmdetection3d
Successfully installed mmdet3d-0.14.0 numpy-1.19.5

**Comment by Wuziyi616** [comment]
Duplicate #301 and #425, can you post your numpy version here? Also what's the output of `python -m pip show pycocotools` and `python -m pip show mmpycocotools`?

**Comment by superchenyan** [comment]
> Duplicate #301 and #425, can you post your numpy version here? Also what's the output of `python -m pip show pycocotools` and `python -m pip show mmpycocotools`?

installed mmdet3d-0.14.0 numpy-1.19.5

**Comment by Wuziyi616** [comment]
What about pycocotools and mmpycocotools? You can run `python -m pip uninstall pycocotools` and then `python -m pip install mmpycocotools`.

**Comment by superchenyan** [comment]
Name: mmpycocotools
Version: 12.0.3
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/chenyan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages
Requires: matplotlib, setuptools, cython
Required-by: mmdet


Name: pycocotools
Version: 2.0.2
Summary: Official APIs for the MS-COCO dataset
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /home/chenyan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages
Requires: cython, setuptools, matplotlib
Required-by: nuscenes-devkit

**Comment by Wuziyi616** [comment]
Yes I think you should uninstall pycocotools and have a try.

**Comment by superchenyan** [comment]
> Yes I think you should uninstall pycocotools and have a try.

Traceback (most recent call last):
  File "tools/test.py", line 12, in <module>
    from mmdet3d.apis import single_gpu_test
  File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/apis/inference.py", line 10, in <module>
    from mmdet3d.core import (Box3DMode, DepthInstance3DBoxes,
  File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 1, in <module>
    from mmdet.core.anchor import build_anchor_generator
  File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/__init__.py", line 5, in <module>
    from .mask import *  # noqa: F401, F403
  File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/mask/structures.py", line 6, in <module>
    import pycocotools.mask as maskUtils
ModuleNotFoundError: No module named 'pycocotools'

Do I have to reinstall mmdetection3d?

**Comment by Wuziyi616** [comment]
You don't need to re-install mmdet3d. You should first uninstall both mmpycocotools and pycocotools, and then install mmpycocotools. Due to some reasons, if you install both and uninstall one, python can't find this package (mmpycocotools is also called as pycocotools via import).

**Comment by superchenyan** [comment]
> You don't need to re-install mmdet3d. You should first uninstall both mmpycocotools and pycocotools, and then install mmpycocotools. Due to some reasons, if you install both and uninstall one, python can't find this package (mmpycocotools is also called as pycocotools via import).


python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth

Traceback (most recent call last):
  File "demo/pcd_demo.py", line 3, in <module>
    from mmdet3d.apis import inference_detector, init_model, show_result_meshlab
  File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/apis/__init__.py", line 1, in <module>
    from .inference import (convert_SyncBN, inference_detector,
  File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/apis/inference.py", line 10, in <module>
    from mmdet3d.core import (Box3DMode, DepthInstance3DBoxes,
  File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/core/anchor/__init__.py", line 1, in <module>
    from mmdet.core.anchor import build_anchor_generator
  File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/__init__.py", line 5, in <module>
    from .mask import *  # noqa: F401, F403
  File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/mask/structures.py", line 6, in <module>
    import pycocotools.mask as maskUtils
  File "/home/chenyan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by Wuziyi616** [comment]
One thing I need to make sure, what mmdet version do you installed?

**Comment by superchenyan** [comment]
> One thing I need to make sure, what mmdet version do you installed?

tag:2.11.0

**Comment by Wuziyi616** [comment]
It seems that your environment is all correct, very strange to me. Can you re-create a new conda environment (python 3.7), pip install numpy 1.19.5 first and then clone install mmdet3d?

**Comment by superchenyan** [comment]
I got "RuntimeError: Error compiling objects for extension" when I install mmdetection3d 
pytorch 1.7.1 cuda 11.0  when fisrst setup mmdetection

and I change the setup.py by  add the ['-gencode=arch=compute_80,code=sm_80']

if torch.cuda.is_available() or os.getenv('FORCE_CUDA', '0') == '1':
define_macros += [('WITH_CUDA', None)]
extension = CUDAExtension
extra_compile_args['nvcc'] = extra_args + [
'-D__CUDA_NO_HALF_OPERATORS__',
'-D__CUDA_NO_HALF_CONVERSIONS__',
'-D__CUDA_NO_HALF2_OPERATORS__',
] + ['-gencode=arch=compute_80,code=sm_80']

it seems to install sucessully. 
When I test with the followed command:
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
it occuer error. May be the setup is wrong?

**Comment by Wuziyi616** [comment]
It's possible this setup is wrong, while I am not familiar with these CUDA settings, I will ask one of my teammate. How's the new environment? Installing numpy 1.19.5 first still failed?

**Comment by Wuziyi616** [comment]
Hi @superchenyan I forget that another workaround for me is to install mmpycocotools and **pycocotools==2.0.1**. You can also try it.

**Comment by lucky-fzy** [comment]
> when run : python tools/test.py configs/votenet/votenet_8x8_scannet-3d-18class.py
> checkpoints/votenet_8x8_scannet-3d-18class_20200620_230238-2cea9c3a.pth
> --show --show-dir ./data/scannet/show_results
> 
> *Traceback (most recent call last):
> File "tools/test.py", line 12, in
> from mmdet3d.apis import single_gpu_test
> File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/apis/**init**.py", line 1, in
> from .inference import (convert_SyncBN, inference_detector,
> File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/apis/inference.py", line 10, in
> from mmdet3d.core import (Box3DMode, DepthInstance3DBoxes,
> File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/core/**init**.py", line 1, in
> from .anchor import * # noqa: F401, F403
> File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/core/anchor/**init**.py", line 1, in
> from mmdet.core.anchor import build_anchor_generator
> File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/**init**.py", line 5, in
> from .mask import * # noqa: F401, F403
> File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/mask/**init**.py", line 2, in
> from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
> File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/mask/structures.py", line 6, in
> import pycocotools.mask as maskUtils
> File "/home/chenyan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in
> import pycocotools._mask as _mask
> File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
> ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

Hi,I have the same problem. Have you solved it?

**Comment by superchenyan** [comment]
> Hi @superchenyan I forget that another workaround for me is to install mmpycocotools and **pycocotools==2.0.1**. You can also try it.

it works ths!!!

**Comment by superchenyan** [comment]
> > when run : python tools/test.py configs/votenet/votenet_8x8_scannet-3d-18class.py
> > checkpoints/votenet_8x8_scannet-3d-18class_20200620_230238-2cea9c3a.pth
> > --show --show-dir ./data/scannet/show_results
> > *Traceback (most recent call last):
> > File "tools/test.py", line 12, in
> > from mmdet3d.apis import single_gpu_test
> > File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/apis/**init**.py", line 1, in
> > from .inference import (convert_SyncBN, inference_detector,
> > File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/apis/inference.py", line 10, in
> > from mmdet3d.core import (Box3DMode, DepthInstance3DBoxes,
> > File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/core/**init**.py", line 1, in
> > from .anchor import * # noqa: F401, F403
> > File "/media/chenyan/DATA/baidu/mmdetection3d/mmdet3d/core/anchor/**init**.py", line 1, in
> > from mmdet.core.anchor import build_anchor_generator
> > File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/**init**.py", line 5, in
> > from .mask import * # noqa: F401, F403
> > File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/mask/**init**.py", line 2, in
> > from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
> > File "/media/chenyan/DATA/baidu/mmdetection/mmdet/core/mask/structures.py", line 6, in
> > import pycocotools.mask as maskUtils
> > File "/home/chenyan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools/mask.py", line 3, in
> > import pycocotools._mask as _mask
> > File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
> > ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
> 
> Hi,I have the same problem. Have you solved it?

install mmpycocotools and pycocotools==2.0.1.

**Comment by Wuziyi616** [comment]
Glad it helps :)

**Comment by lijain** [comment]
Hi, I was just wondering. My environment is mmdetect3d==0.15.0，cuda==9.2,torch==1.7.0; MMDetection== 2.14.0, MMSegmentation ==0.14.1 and MMCV-full== 1.3.9
run it :python demo/mono_det_demo.py demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525.jpg demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525_mono3d.coco.json configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.py weights/pretain/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210427_091419-35aaaad0.pth --out-dir /home/mnt_abc004-data/mq/Project/mmdetection3d-15/result/output
there is question :
 File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Segmentation fault (core dumped)
i change pycocotools but it is not function. Under the guidance of please

**Comment by Wuziyi616** [comment]
`numpy==1.19.5` and `pycocotools==2.0.1` should work. Actually MMDet3D has deprecated `mmpycocotools` since `0.15.0` so you may update mmcv, mmdet and mmseg versions and use `pycocotools` to replace `mmpycocotools`.

**Comment by lijain** [comment]
I have changed it according to your question, and the error is: Segmentation fault (core handling).
I changed the environment again,
mmcv-full                   1.3.9
mmdet                       2.14.0
mmdet3d                     0.15.0          
mmsegmentation              0.15.0
It still has this problem：Segmentation fault (core handling).
I have installed the environment to heart tired,please guide, thank you

**Comment by Wuziyi616** [comment]
Let's continue our discussion in #769 since this issue is closed.

**Comment by lijain** [comment]
769 The problem is that python and Opencv - Python version conflicts have been resolved.Then encountered this problem, really can not find the answer, please solve.This environment has been installed for almost a d
