### ISSUE TITLE
How to test MVX-Net?

### ISSUE THREAD

**Issue by Balazizo** [open-mmlab/mmdetection3d#655]
I'm trying to output results from MVX-Net but I understand that it uses 2 modalities to output results. How do I initialize the parameters required and are they outputted in KITTI format?

**Comment by Wuziyi616** [comment]
I don't understand your question. Do you want to test MVX-Net on KITTI dataset? Yes it will output in KITTI format. See this [doc](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html#test-existing-models-on-standard-datasets) for how to test it. Also there is a demo for MVX-Net as described [here](https://mmdetection3d.readthedocs.io/en/latest/0_demo.html#multi-modality-demo).

**Comment by abhishek-t-naive** [comment]
@Wuziyi616 The link above for the demos takes us to "This page does not exist" message. Is it possible for you to share the new link for the MVX-Net demo?

**Comment by Wuziyi616** [comment]
See [here](https://mmdetection3d.readthedocs.io/en/latest/demo.html#multi-modality-demo), the MVXNet on KITTI

**Comment by abhishek-t-naive** [comment]
I see that in Fusion Layers we have all sorts of implementation. If I want to implement VoxelFusion, do I need to start from scratch or are you aware of any other implementations?
