### ISSUE TITLE
Error while seeing the config file 

### ISSUE THREAD

**Issue by marcadel** [open-mmlab/mmdetection3d#657]
When i try to run python tools/misc/print_config.py /PATH/TO/CONFIG to see the whole config file this error pop up 
FileNotFoundError: file "/PATH/TO/CONFIG" does not exist

**Comment by wHao-Wu** [comment]
Hi, @marcadel 

The `/PATH/TO/CONFIG` means the specific config files which you want to analyze. For example, if you want to analyze the detail of SECOND config on KITTI dataset, you can use the following command:

```shell
python tools/misc/print_config.py configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py
```
