### ISSUE TITLE
RuntimeError Dataloader worker (pid ***) is killed by signal: killed

### ISSUE THREAD

**Issue by agent-sgs** [open-mmlab/mmdetection3d#658]
When retrain the PointPillar on the WAYMO dataset with 4x8 config (batch_size=4, GPUs=8), we encounter some errors. 
There is enough shared memory for the following problems. 

num_workers_per_gpu >= 2, cannot run train.py
when num_workers_per_gpu=1, it conduct training about 2000 steps and then interrupt with following log:
![image](https://user-images.githubusercontent.com/71326860/122508724-032c2180-d035-11eb-9354-e137317b072b.png)

**Comment by Tai-Wang** [comment]
I guess this problem is not specific to our codebase or the waymo training procedure. Please try to check other problems related to your machines or something.
