### ISSUE TITLE
Why add offset in KITTI preprocessing

### ISSUE THREAD

**Issue by lianqing11** [open-mmlab/mmdetection3d#660]
Dear author,

Thanks for your releasing the the code. I am confused about the data generation file. Could you kindly help me figure it out?
 
In kitti convert file why add an offset between 0 and 2 camera?  It seems the labels are based on camera 2. And when generate center2d, the location is used from the orginal "loc" variable.
    https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/kitti_converter.py#L428

**Comment by Tai-Wang** [comment]
Please refer to issue #490 .

**Comment by lianqing11** [comment]
Thanks for your reply. I have understood that.
