### ISSUE TITLE
Testing on the Canadian Adverse Driving Conditions Dataset (CADCD)

### ISSUE THREAD

**Issue by Balazizo** [open-mmlab/mmdetection3d#661]
I'm trying to test PointPillars, Second, and MVXNet on the CADCD. However, the models only support KITTI, Waymo and NuScenes. What changes should I make in order to test these models on my dataset. Please note: I have already converted the CADCD to KITTI format.

**Comment by Wuziyi616** [comment]
Mainly these two functions [this](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/kitti_dataset.py#L95) and [this](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/kitti_dataset.py#L138) to load data and labels.

If your data format is really the same as KITTI (e.g. data_infos and folder structure), all the evaluation code and training code can be re-used.

**Comment by Balazizo** [comment]
The folder structure is the same except there is no pred folder, the 3D anotations/labels are typed in the same format. The only difference is in the calibration files; the calibration parameters are different and I haven't been able to convert those. 
This can be seen in the secreenshots attached (CADCD on the left and KITTI on the right)
![Screenshot from 2021-06-19 10-33-12](https://user-images.githubusercontent.com/47889543/122636609-7479dc00-d0ea-11eb-8849-9d8144d4013f.png)
![Screenshot from 2021-06-19 10-33-20](https://user-images.githubusercontent.com/47889543/122636655-a5f2a780-d0ea-11eb-898d-f2a17776457d.png)

**Comment by Balazizo** [comment]
Since I'm only interested in CAM00 in the CADCD, I've removed the un-needed matrices so it looks as follows:




![Screenshot from 2021-06-19 12-14-25](https://user-images.githubusercontent.com/47889543/122639025-e9074780-d0f7-11eb-99a5-cdd10a491e15.png)

**Comment by Wuziyi616** [comment]
You may refer to the KITTI paper to see what these matrices represent and how to convert them. For point cloud based methods, calib is not necessary and you should be successfully to test them. For MVX-Net, calib is required.

**Comment by Balazizo** [comment]
Alright, thank you very much. After I'm done with the conversion which part of the script lets the model know where the directory of the dataset is?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by Balazizo** [comment]
Alright, thank you very much. After I'm done with the conversion which part of the script lets the model know where the directory of the dataset is, to load the data from? Also, is all I need is to do is to specify a directory for the dataset, a backbone and a checkpoint and I can expect results then, correct?

**Comment by Wuziyi616** [comment]
Can have a look at [this](https://github.com/Wuziyi616/mmdetection3d/blob/master/configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py) config file. As you can see, it iherits from a `model`, a `dataset`, a `training schedule` and a `runtime` config. You can refer to the dataset and the model one for more details (they are used in testing). For example, [here](https://github.com/Wuziyi616/mmdetection3d/blob/master/configs/_base_/datasets/kitti-3d-3class.py#L3) specify the data directory.

**Comment by Balazizo** [comment]
Hello @Wuziyi616, I've modified the directory, the annotation format, and the calibration files of the CADCD into the format of KITTI. I've changed the root directory of the dataset in the code to match the directory of mine. After running `python3 test.py mmdetection3d/configs/second/hv_second_secfpn_6x8_80e_kitti-3d-3class.py mmdetecion3d/checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --out RESULTS.pkl --eval mAP --show` 
I ended up getting this error:
FileNotFoundError: KittiDataset: [Errno 2] No such file or directory: '/home/ubuntu/Repos/cadc_devkit/cadcd/objectkitti_infos_val.pkl' . How do I produce the pkl file
in order to run Second on my dataset?

**Comment by Wuziyi616** [comment]
Have a look at [this](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/create_data.py) script. The command is presented in the [doc](https://mmdetection3d.readthedocs.io/en/latest/data_preparation.html#kitti).

**Comment by Wuziyi616** [comment]
Feel free to re-open this PR should you have any further questions :)

**Comment by Balazizo** [comment]
Hello @Wuziyi616, I'd like some insight as to what should be done with the text files in the ImageSets folder. I'm only interested in testing and do not intend on training. Does this mean I can set the train.txt, val.txt and trainval.txt folders to empty and only keep the test.txt file containing numbers of frames? I've done this and I'm not sure if it's correct. Also, I'm trying to run create_data.py but I keep running into this error:  
`File "/home/ubuntu/Repos/mmdetection3d/mmdet3d/ops/ball_query/ball_query.py", line 4, in <module>
    from . import ball_query_ext
ImportError: cannot import name 'ball_query_ext' from partially initialized module 'mmdet3d.ops.ball_query' (most likely due to a circular import) (/home/ubuntu/Repos/mmdetection3d/mmdet3d/ops/ball_query/__init__.py)` . Please note, I moved create_data.py into the main directory of mmdetection3d from mmdetection3d/tools. As when trying to run it from withing the tools directory, I would always end up with `ModuleNotFoundError: No module named 'tools.data_converter' at line 4. Thank you for your support up till this point.

**Comment by Wuziyi616** [comment]
Don't run `create_data` from within the `tools/` directory, just run `python tools/create_data.py` in the `mmdetection3d/` folder. The import error is quite strange, have you successfully build and install mmdet3d (e.g. can you run demo)?

If you only want to test (which means running inference and saving the predictions), setting train and val txt files to empty is okay. But if you do have GT and also want to evaluate, you also need to set the val txt files.

**Comment by Balazizo** [comment]
Hello @Wuziyi616, the CADCD unfortunately has claases that are different from KITTI so instead of "car", "pedestrians", "cyclists"; there's trucks instead of cyclists, I changed the classes arrays in Kitti_dataset.py by replacing 'cyclist' with 'truck' and the same withh kitti_converter.py. Would this be enough to test on truck instead of cyclist?

**Comment by Wuziyi616** [comment]
Yes, I think that should be enough. Don't forget to change the config of KITTI [here](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py#L135).

**Comment by Balazizo** [comment]
Hello @Wuziyi616, I've tried evaluating second 3d on car labels using the backbone and checkpoint for car detection. However, the output is as follows:
`Car AP@0.70, 0.70, 0.70:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00
Car AP@0.70, 0.50, 0.50:
bbox AP:0.0000, 0.0000, 0.0000
bev  AP:0.0000, 0.0000, 0.0000
3d   AP:0.0000, 0.0000, 0.0000
aos  AP:0.00, 0.00, 0.00`
I think the labels aren't being detected. I've checked the "kitti_gt_database" folder after running create_data.py but it's empty even though the txt file used was val.txt and all the data is labelled. Any suggestions?

**Comment by Tai-Wang** [comment]
Please add some breakpoints in this [function](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/data_converter/create_gt_database.py#L108) to check what happens when creating ground truth database. If kitti_gt_database is empty, there must be something wrong with your pre-processing of labels.

**Comment by Balazizo** [comment]
Hello @Tai-Wang, I was able to produce evaluation results. However, some of the results have exceeded 100% mAP as shown in the attached screenshot. What could be the reason for this? Thanks, in advance.
![Screenshot from 2021-07-05 20-43-19](https://user-images.githubusercontent.com/47889543/124509152-b769ce00-ddd1-11eb-840a-876f72de1e9a.png)

**Comment by Balazizo** [comment]
Hello @Tai-Wang , I just noticed that these values are 0% accuracy. The dataset I'm using is comprised solely of adverse weather conditions such as rain, cloudy and snow. A 32 ring lidar was used. Could these be the reason why the results are so low? If so, how do I solve this?

**Comment by Tai-Wang** [comment]
The printed values are percentages. For example, 25.1032 means about 25% accuracy.
Of course adverse weather conditions and less lines of lidar will make it more difficult, but the main reason should be the domain adaptation. When adapting to a new dataset with a new setting, tuning parameters and error analysis are definitely required for this task currently.

**Comment by fcakyon** [comment]
> Hello @Wuziyi616, I'd like some insight as to what should be done with the text files in the ImageSets folder. I'm only interested in testing and do not intend on training. Does this mean I can set the train.txt, val.txt and trainval.txt folders to empty and only keep the test.txt file containing numbers of frames? I've done this and I'm not sure if it's correct. Also, I'm trying to run create_data.py but I keep running into this error: `File "/home/ubuntu/Repos/mmdetection3d/mmdet3d/ops/ball_query/ball_query.py", line 4, in <module> from . import ball_query_ext ImportError: cannot import name 'ball_query_ext' from partially initialized module 'mmdet3d.ops.ball_query' (most likely due to a circular import) (/home/ubuntu/Repos/mmdetection3d/mmdet3d/ops/ball_query/__init__.py)` . Please note, I moved create_data.py into the main directory of mmdetection3d from mmdetection3d/tools. As when trying to run it from within the tools directory, I would always end up with `ModuleNotFoundError: No module named 'tools.data_converter' at line 4. Thank you for your support up till this point.

How did you solve this circular import error? I am having the same..
