### ISSUE TITLE
How to test the kitti's testing dataset?

### ISSUE THREAD

**Issue by mrqrs** [open-mmlab/mmdetection3d#662]
I have followed the configs of kitti-3d-3class setting to generate the kitti testing data's result. But the config file only sets the training split. How to set the testing split?

**Comment by THU17cyz** [comment]
Hi @mrqrs , what do you mean by testing split? You can change https://github.com/open-mmlab/mmdetection3d/blob/a6ee9335682967ad2d697f80cb79991028bb966b/configs/_base_/datasets/kitti-3d-3class.py#L131

to `ann_file=data_root + 'kitti_infos_test.pkl' `

**Comment by mrqrs** [comment]
> Hi @mrqrs , what do you mean by testing split? You can change
> 
> https://github.com/open-mmlab/mmdetection3d/blob/a6ee9335682967ad2d697f80cb79991028bb966b/configs/_base_/datasets/kitti-3d-3class.py#L131
> 
> to `ann_file=data_root + 'kitti_infos_test.pkl' `

Thanks for your reply, i have solved this problem.

**Comment by Joaovsky** [comment]
Hey, did you managed to test without getting the error: KeyError: 'annos' ? If so, how did you solve it?
