### ISSUE TITLE
How to test monocular 3D detection on KITTI dataset?

### ISSUE THREAD

**Issue by morrolinux** [open-mmlab/mmdetection3d#668]
The example in the documentation refers to nuscenes:
```
python demo/mono_det_demo.py demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525.jpg demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525_mono3d.coco.json configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.py checkpoints/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210427_091419-35aaaad0.pth
```

I've tried changing the image to a KITTI image and the annotation file to its `calib` file:
```
python demo/mono_det_demo.py ~/Kitti/object/training/image_2/000000.png ~/Kitti/object/training/calib/000000.txt configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.py checkpoints/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210427_091419-35aaaad0.pth
```
but I've got this:

```
Traceback (most recent call last):
  File "demo/mono_det_demo.py", line 43, in <module>
    main()
  File "demo/mono_det_demo.py", line 30, in main
    result, data = inference_mono_3d_detector(model, args.image, args.ann)
  File "/home/morro/mmdetection3d/mmdet3d/apis/inference.py", line 213, in inference_mono_3d_detector
    data_infos = mmcv.load(ann_file)
  File "/home/morro/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/fileio/io.py", line 37, in load
    raise TypeError(f'Unsupported format: {file_format}')
TypeError: Unsupported format: txt
```
So the parser only works with nuscene annotations format?
If so, how can I convert KITTI's calib files to nuscene ann format?

Thanks for your amazing work!

**Comment by Wuziyi616** [comment]
Hi! Mono-3D on KITTI dataset is an ongoing feature. Actually, @Tai-Wang is working on releasing FCOS3D on KITTI. So we are going to see this feature in the near future I believe :)

**Comment by lyuwenyu** [comment]
> The example in the documentation refers to nuscenes:
> 
> ```
> python demo/mono_det_demo.py demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525.jpg demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525_mono3d.coco.json configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.py checkpoints/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210427_091419-35aaaad0.pth
> ```
> 
> I've tried changing the image to a KITTI image and the annotation file to its `calib` file:
> 
> ```
> python demo/mono_det_demo.py ~/Kitti/object/training/image_2/000000.png ~/Kitti/object/training/calib/000000.txt configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.py checkpoints/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210427_091419-35aaaad0.pth
> ```
> 
> but I've got this:
> 
> ```
> Traceback (most recent call last):
>   File "demo/mono_det_demo.py", line 43, in <module>
>     main()
>   File "demo/mono_det_demo.py", line 30, in main
>     result, data = inference_mono_3d_detector(model, args.image, args.ann)
>   File "/home/morro/mmdetection3d/mmdet3d/apis/inference.py", line 213, in inference_mono_3d_detector
>     data_infos = mmcv.load(ann_file)
>   File "/home/morro/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/fileio/io.py", line 37, in load
>     raise TypeError(f'Unsupported format: {file_format}')
> TypeError: Unsupported format: txt
> ```
> 
> So the parser only works with nuscene annotations format?
> If so, how can I convert KITTI's calib files to nuscene ann format?
> 
> Thanks for your amazing work!

@morrolinux ,  Hi, have you solved this problem -.-

**Comment by Wuziyi616** [comment]
@lyuwenyu Maybe you can wait for our future release, which will support this feature.

**Comment by chetanmreddy** [comment]
Hi Any expected date on this release?

**Comment by Tai-Wang** [comment]
We are working on an advanced version FCOS3D, which has shown more promising performance both on KITTI and nuScenes. However, before releasing the model on KITTI and the new feature, we need to deal with some issues to make them ready.
I hope the related paper and code can be available before September. Thanks for your patience and I will try my best to push it.

**Comment by chetanmreddy** [comment]
Thank you very much @Tai-Wang  for your effort. 
I think if possible you can first release some support for current fcos3d on KITTI dataset.

Looking forward to the advanced version of fcos3d.

**Comment by Tai-Wang** [comment]
From my basic attempts, the vanilla FCOS3D itself can not achieve very promising performance similar to nuScenes. The underlying reason can include:
1. Data is much more limited on KITTI, so it would be much harder to learn such model in a simple regression manner.
2. The KITTI metrics are quite strict in terms of the accuracy of 3D bounding boxes, so it has really different requirements for the models.
On this basis, the original model must be equipped with some specific designs/tricks tailored to KITTI to achieve better, which is part of our advanced version, although they maybe not necessary designs for practical applications.

For the basic version that can not perform very well, please feel free to generate infos, modify the configs of nuScenes and have a try. All the APIs are compatible.

**Comment by htdung167** [comment]
I had same problem when using monocular 3D detection with SMOKE and KITTI dataset.

What dataset can I use monocular 3D detection for?

![image](https://user-images.githubusercontent.com/73953274/198497766-aad6bedc-c570-435a-bfac-6f52b05c9a51.png)
