### ISSUE TITLE
How to convert model trained by mmdetection3d to onnx?

### ISSUE THREAD

**Issue by xinghuokang** [open-mmlab/mmdetection3d#672]
Hi, I want to convert the model trained by mmdetection3d to onnx, how to do it, can you give me some advices?

**Comment by Wuziyi616** [comment]
This is indeed a planned feature. But currently we don't have enough people to work on it. Can refer to #203 for more information.

**Comment by williamhyin** [comment]
> by the way, How to convert model trained by focs3D model to onnx? I want to run it in tensorrt. following https://mmdetection.readthedocs.io/en/latest/tutorials/onnx2tensorrt.html this guide will work?
> 
> Thanks! @Wuziyi616

Hi,

Have you successfully converted to onnx?

@ideafold 

Thanks

**Comment by scuizhibin** [comment]
Is the conversion successful?

**Comment by clw5180** [comment]
Is the conversion successful?
