### ISSUE TITLE
How to do inference on custom test samples

### ISSUE THREAD

**Issue by Mohamed209** [open-mmlab/mmdetection3d#673]
i have 4 files 
`image.png`
`lidar.bin`
`lid_to_cam: 0.08088629 -0.99590131 -0.04047205 -0.15610122 0.06293044 0.04562682 -0.9969744 -0.3785559 0.99473472 0.07809463 0.06636309 -0.59070911 0. 0. 0. 1.  `
`cam_intrinsic: 649.65825827 0. 302.21275333 0. 656.18334152 244.27286533 0. 0. 1.`
i am testing `MVX-Net` : https://github.com/open-mmlab/mmdetection3d/blob/master/configs/mvxnet/README.md

while running  `python demo/multi_modality_demo.py demo/data/kitti/kitti_000008.bin demo/data/kitti/kitti_000008.png demo/data/kitti/kitti_000008_infos.pkl configs/mvxnet/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class.py checkpoints/dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class_20200621_003904-10140f2d.pth --show`

i think `infos.pkl` file is where i can add my custom camera params
while loading *pkl in memory
i got these matrices and their shapes
`P0 (4, 4) 
P1 (4, 4) 
P2 (4, 4) 
P3 (4, 4) 
R0_rect (4, 4) 
Tr_velo_to_cam (4, 4) 
Tr_imu_to_velo (4, 4)`
 
how to override these values with my lidar to cam `4*4` matrix and internsic `3*3` camera matrix

`# LiDAR to image conversion`
      `if box_mode_3d == Box3DMode.LIDAR:`
        `for item in info['calib']:`
            `print(item, info['calib'][item].shape, "\n")`
        `rect = info['calib']['R0_rect'].astype(np.float32)`
        `#Trv2c = info['calib']['Tr_velo_to_cam'].astype(np.float32)`
        `Trv2c = np.array([0.08088629, -0.99590131, -0.04047205, -0.15610122, 0.06293044,`
                          `0.04562682, -0.9969744, -0.3785559, 0.99473472, 0.07809463, 0.06636309, -0.59070911, 0., 0., 0., 1.]).reshape(4, 4)`
        `#P2 = info['calib']['P2'].astype(np.float32)`
        `P2 = np.pad(np.array([649.65825827, 0., 302.21275333, 0.,`
                              `656.18334152, 244.27286533, 0., 0., 1.]).reshape(3, 3), (0, 1))`
tried to replace trv2c and P2 but still projected boxes to the image are incorrect

**Comment by Wuziyi616** [comment]
Simply replacing `lidar2img` with your `lid_to_cam` [here](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/apis/inference.py#L170)? If that doesn't work, try replacing `lidar2img` with your `lid_to_cam @ cam_intrinsic` (you may need to pad `cam_intrinsic` to `4x4`)?
