### ISSUE TITLE
Possible bug with 'with_distance = True' in DynamicVFE

### ISSUE THREAD

**Issue by Abyssaledge** [open-mmlab/mmdetection3d#675]
https://github.com/open-mmlab/mmdetection3d/blob/d0d3d944ee7874e53eeea4ce9801a8e2c289e6ea/mmdet3d/models/voxel_encoders/voxel_encoder.py#L334
Should it be `in_channels += 1`?

**Comment by Tai-Wang** [comment]
Yes I guess it's a typo. Have you encountered any bugs because of it? If you have checked the results, could you please create a PR to fix it?
