### ISSUE TITLE
WOD timestamp truncated error

### ISSUE THREAD

**Issue by lhcalibur** [open-mmlab/mmdetection3d#678]
version: 
v0.14.0
bug:
In tools/data_converter/waymo_converter.py:247 
`        point_cloud = np.column_stack(
            (points, intensity, elongation, timestamp))`
`point_cloud.astype(np.float32).tofile(pc_path)`
Which will truncate the timestamp and get an inaccurate result in tools/data_converter/kitti_data_utils.py
line 321 `info['timestamp'] = np.int64(points[0, -1])`
line 422 `prev_info['timestamp'] = np.int64(prev_points[0, -1])`

**Comment by Tai-Wang** [comment]
Yes it's a potential bug due to some legacy issue. Please refer to issue #296 . If you have any good ideas, PR is definitely welcome.
