### ISSUE TITLE
How can we get the FLOPs of one model? and How can we test model's inferring speed?

### ISSUE THREAD

**Issue by lihua213** [open-mmlab/mmdetection3d#68]
Dear friends, thanks for the nice codebase. Are there scripts for the above questions? thanks

**Comment by ZwwWayne** [comment]
To test inference speed, you can use [benchmark.py](https://github.com/open-mmlab/mmdetection3d/blob/master/tools/benchmark.py). For now, we do not support calculating flops since usually, the input of models varies a lot. We will plan to calculate flops in the future.

**Comment by lihua213** [comment]
Thanks so much.
