### ISSUE TITLE
Annotation results format

### ISSUE THREAD

**Issue by ta984ia** [open-mmlab/mmdetection3d#681]
Hi,
Can I get the annotation results in any other formats like json other than .pkl ?

**Comment by Tai-Wang** [comment]
Of course you can. From my point of view, pkl and json files are used just for different base formats (pkl for lists while json for dicts typically). We just use pkl files as the unified annotation format for some tasks like LiDAR-based detection while follow coco-style json format for convenient API in vision-only methods. You can refer to them and reorganize the infos in your own way.

**Comment by ta984ia** [comment]
Thank you for the explanation.
