### ISSUE TITLE
Inferencing with existing models and standard datasets

### ISSUE THREAD

**Issue by chetanmreddy** [open-mmlab/mmdetection3d#685]
Hello,
I am trying to evaluate the fcos3d model on nuscenes dataset as shown [here](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html)

but keep getting this error: 
FileNotFoundError: NuScenesMonoDataset: [Errno 2] No such file or directory: 'data/nuscenes/nuscenes_infos_val_mono3d.coco.json'

Where do I get these files?

Thank You for your help.

**Comment by Tai-Wang** [comment]
Please generate nuscenes infos following the doc [here](https://mmdetection3d.readthedocs.io/en/latest/data_preparation.html). The json files will be generated with the pkl files together.
