### ISSUE TITLE
Using just parts of the MMDetection3d pipeline

### ISSUE THREAD

**Issue by AfonsoSalgadoSousa** [open-mmlab/mmdetection3d#691]
Hi. I have a training routine with adversarial processes, and I would like to use some of your modules to extract feature maps from both image and point clouds to use in my use case.
I have the following [config file](https://github.com/open-mmlab/mmdetection3d/files/6750630/my_config.txt) based on the MVX-Net config.
I created a [new detector](https://github.com/open-mmlab/mmdetection3d/files/6750634/my_detector.txt) with two feature extraction branches (one for images and one for point clouds), and for now, I want to return the two corresponding embeddings that would then be fed into my pipeline.
Do I need to create a new training routine to achieve this? I am also not sure how to use the train_cfg and test_cfg for my use case.

**Comment by Tai-Wang** [comment]
You can basically return the required feature maps after forward computation and add a auxiliary module for head or something to achieve that. From my understanding, there is no need to add any pipelines for your planned feature?

**Comment by AfonsoSalgadoSousa** [comment]
Thank you for the reply. I think the MMDet train_detector() method does not perfectly suit my needs. As such, I am trying to build a new training routine after instantiating the model and data loaders with the mmdet3d functions. I now want to pass a batch through the model but cannot manage to do so. How does the EpochBasedRunner map the DataContainer to the model's positional arguments? How can I use a "standard" Pytorch training routine on a model inheriting from BaseDetector from MMDet?
Thanks in advance.
