### ISSUE TITLE
Inference using existing models and standard datasets - imvoxelnet - Kitti

### ISSUE THREAD

**Issue by chetanmreddy** [open-mmlab/mmdetection3d#694]
Hello @Tai-Wang @filaPro 

I am trying to do inference using the instructions [here](https://mmdetection3d.readthedocs.io/en/latest/1_exist_data_model.html)

`python tools/test.py configs/imvoxelnet/imvoxelnet_kitti-3d-car.py checkpoints/imvoxelnet_kitti-3d-car_20210610_152323-b9abba85.pth --show --show-dir ./data/kitti/show_results/`

I have prepared the KITTI dataset as required.

But getting the following error:

`(open-mmlab) root@cmudi001-nx-interactive-pod-1:/cmudi001-nx-1/mmdetection3d# python tools/test.py configs/imvoxelnet/imvoxelnet_kitti-3d-car.py checkpoints/imvoxelnet_kitti-3d-car_20210610_152323-b9abba85.pth --show --show-dir ./data/kitti/show_results/

/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/anchor/builder.py:16: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator`` 
  '``build_anchor_generator`` would be deprecated soon, please use '

Use load_from_local loader
[                                                  ] 0/3769, elapsed: 0s, ETA:/opt/conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448224956/work/c10/core/TensorImpl.h:1156.)

  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "tools/test.py", line 214, in <module>
    main()
  File "tools/test.py", line 184, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/cmudi001-nx-1/mmdetection3d/mmdet3d/apis/test.py", line 51, in single_gpu_test
    if batch_size == 1 and isinstance(data['img'][0],
TypeError: 'DataContainer' object is not subscriptable`

Can you please help me with this?
Thank you

UPDATE:
When I use --out instead of --show and --show-dir as shown above, it works fine.

**Comment by filaPro** [comment]
Hi @chetanmreddy,
Unfortunately current version of `ImVoxelNet` is not ready for visualization, as in is not inherited [from](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/apis/test.py#L43) `Base3DDetector` and does not [have](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/apis/test.py#L46) `show_results` method.
