### ISSUE TITLE
FCOS3D, CUDA out of memory

### ISSUE THREAD

**Issue by yangxpeijiu** [open-mmlab/mmdetection3d#697]
When i try to train FCOS3D in my dataset.
RuntimeError: CUDA out of memory. Tried to allocate 1.41 GiB (GPU 0; 31.75 GiB total capacity; 28.72 GiB already allocated; 685.50 MiB free; 30.02 GiB reserved in total by PyTorch)
I have set the samples_per_gpu = 1

**Comment by Tai-Wang** [comment]
Please check the initial usage of the GPU memory. The released FCOS3D model should be trained successfully with a general 12GB GPU.

**Comment by yangxpeijiu** [comment]
另外一个问题是，在运行的过程中，会出现某两张卡的显存突然占用扩大的情况。正常情况下8张卡基本都是占用5、6G左右（在sample_per_gpu=1的情况下），但是突然会出现一张卡占用20多G，看起来是因为这种突然增大导致的显存不够。我确认该服务器当时只有我一个人在使用

**Comment by yangxpeijiu** [comment]
正常情况：
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:5A:00.0 Off |                    0 |
| N/A   57C    P0   148W / 250W |   **_5685MiB / 32510MiB_** |     90%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:5E:00.0 Off |                    0 |
| N/A   55C    P0   157W / 250W |   5769MiB / 32510MiB |     90%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  Off  | 00000000:62:00.0 Off |                    0 |
| N/A   55C    P0   162W / 250W |   5691MiB / 32510MiB |     90%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-PCIE...  Off  | 00000000:66:00.0 Off |                    0 |
| N/A   56C    P0   173W / 250W |   5671MiB / 32510MiB |     75%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-PCIE...  Off  | 00000000:B5:00.0 Off |                    0 |
| N/A   56C    P0   181W / 250W |   5685MiB / 32510MiB |     81%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-PCIE...  Off  | 00000000:B9:00.0 Off |                    0 |
| N/A   60C    P0   167W / 250W |   5771MiB / 32510MiB |     82%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-PCIE...  Off  | 00000000:BD:00.0 Off |                    0 |
| N/A   57C    P0   169W / 250W |   5769MiB / 32510MiB |     87%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-PCIE...  Off  | 00000000:C1:00.0 Off |                    0 |
| N/A   57C    P0   171W / 250W |   5691MiB / 32510MiB |     77%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
非正常情况：
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:5A:00.0 Off |                    0 |
| N/A   39C    P0    40W / 250W |  **_24637MiB / 32510MiB_** |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  Off  | 00000000:5E:00.0 Off |                    0 |
| N/A   40C    P0    41W / 250W |   5769MiB / 32510MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-PCIE...  Off  | 00000000:62:00.0 Off |                    0 |
| N/A   38C    P0    41W / 250W |   5691MiB / 32510MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-PCIE...  Off  | 00000000:66:00.0 Off |                    0 |
| N/A   39C    P0    39W / 250W |   5937MiB / 32510MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-PCIE...  Off  | 00000000:B5:00.0 Off |                    0 |
| N/A   39C    P0    41W / 250W |   5723MiB / 32510MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-PCIE...  Off  | 00000000:B9:00.0 Off |                    0 |
| N/A   42C    P0    41W / 250W |   5771MiB / 32510MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-PCIE...  Off  | 00000000:BD:00.0 Off |                    0 |
| N/A   36C    P0    25W / 250W |     12MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-PCIE...  Off  | 00000000:C1:00.0 Off |                    0 |
| N/A   39C    P0    39W / 250W |   5691MiB / 32510MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by Tai-Wang** [comment]
We never met this problem before. I guess it is not a MMDet3D-specific problem, so you need to check something other than FCOS3D codes. At least, if it happens regularly, try to add some breakpoints to see what happens during the computation.

**Comment by yangxpeijiu** [comment]
It is a regularly problem. Well, i just modify the input data. I will check codes.
Besides, can u tell me your  environment configuration?
Me: cuda 10.0 + pytoch 1.4.0 + torchvision 0.5.0 + Master MMdetection3D
I try to train in one GPU, it is running good. Seems like a distributed problem. I will check.
Thank u

**Comment by Tai-Wang** [comment]
You environment should be ok. I used pytorch 1.4-1.7 with corresponding torchvision and cuda and never met this problem before. If you have modified the data, please first guarantee you can run it successfully with the original nuScenes data. Then it should be a bug related to your data.
