### ISSUE TITLE
I met the error: RuntimeError: CUDA error: invalid configuration argument".

### ISSUE THREAD

**Issue by clytze0216** [open-mmlab/mmdetection3d#698]
Clytze:
Hi @mmdetection3d team
I use the datasets made by myself. But I have not image and calib data. I did not use the image and use the calib information of kitti. I also have no box data(xmin,ymin,xmax,ymax) in labels. I set all 0 of them.
But I found the gt_databases almost 0 bytes. And I run "tools/train.py" I met the error: RuntimeError: CUDA error: invalid configuration argument".
Could you know how could I do to train the model?  
Looking forward to your reply. Thanks a lot!

**Comment by Tai-Wang** [comment]
1. Calib information is used when creating the reduced point clouds, so you can not directly use that of KITTI, or you need to guarantee that will not influence all the procedure related to that data.
2. The reason for 'gt_databases almost 0 bytes' is maybe some inconsistency of your coordinates. We will filter the ground truth boxes by their names and contained points, so you need to check the procedure of generating ground truth database.
3. The error `RuntimeError: CUDA error: invalid configuration argument` is so general and common. After all the previous things being fixed, please provide more details about it.

**Comment by clytze0216** [comment]
> 1. Calib information is used when creating the reduced point clouds, so you can not directly use that of KITTI, or you need to guarantee that will not influence all the procedure related to that data.
> 2. The reason for 'gt_databases almost 0 bytes' is maybe some inconsistency of your coordinates. We will filter the ground truth boxes by their names and contained points, so you need to check the procedure of generating ground truth database.
> 3. The error `RuntimeError: CUDA error: invalid configuration argument` is so general and common. After all the previous things being fixed, please provide more details about it.

Thanks for your reply!! my label for my own data only has "class,x,y,z,w,h,l" 7 values, I set all 0 for the else in label. I want to know if I just want to get the accuracy of the model , not to visualize. could I use this values I have? Thanks again!

**Comment by Tai-Wang** [comment]
You would better also provide the accurate yaw angle in the labels. Setting all 0 for 2D annotations should be ok.
