### ISSUE TITLE
PCD files outdoor

### ISSUE THREAD

**Issue by aidonchuk** [open-mmlab/mmdetection3d#7]
Hi! I have only PCD files with outdoor scenes(buildings). Can you give me some directions how to start with mmdetection3d? Please

**Comment by ZwwWayne** [comment]
Hi @aidonchuk ,
MMDetection3D mainly focuses on 3D object detection for now. If you want to detect some common objects in your PCD files, you can either choose to use a pre-trained detector or train a new one with your own annotations. You can follow the [docs](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#inference-with-pretrained-models) to see whether the they meet your need.

**Comment by aidonchuk** [comment]
Thx
