### ISSUE TITLE
FPN in ImVoxelNet

### ISSUE THREAD

**Issue by AfonsoSalgadoSousa** [open-mmlab/mmdetection3d#700]
Hi. As far as I understand from this line: https://github.com/open-mmlab/mmdetection3d/blob/7fec1d533bacf5b5c89d456f65c775c3cc458c72/mmdet3d/models/detectors/imvoxelnet.py#L47
ImVoxelNet only uses one feature map from the FPN's multi-scale feature maps. Am I miss-interpreting something? Can you enlighten me?

**Comment by filaPro** [comment]
Hi @AfonsoSalgadoSousa ,
As an author of ImVoxelNet can confirm that you are right. This design choice follow the original implementation. However this is probably not the best aggregation method and for sure can be improved.
