### ISSUE TITLE
Why set relative coordinate of bottom center LiDAR box is (0.5, 0.5, 0) ?

### ISSUE THREAD

**Issue by Physu** [open-mmlab/mmdetection3d#703]
I notice that in  mmdet3d/core/bbox/structures/box_3d_mode.py, the illustration of different ways to represent a box, 

> ` The relative coordinate of bottom center in a LiDAR box is (0.5, 0.5, 0),
    and the yaw is around the z axis, thus the rotation axis=2.`
I don't understand why the relative coordinate of bottom center in a LIDAR box is (0.5,0.5,0)? In CAM box and In DEPTH box are (0.5,0.5,1.0), (0.5,0.5,0), which confusing me a lot.
Hope I can know the reason with your help!
Thank open-mmlab for your extraordinary work!

**Comment by Tai-Wang** [comment]
We just define boxes' bottom centers as their default centers, which is consistent with the definition of KITTI. Due to the positive direction of z-axis is up in LiDAR and DEPTH while that of y-axis is down in CAM, their centers are set to (0.5, 0.5, 0) and (0.5, 1.0, 0.5) respectively.

**Comment by Physu** [comment]
![image](https://user-images.githubusercontent.com/32857082/124538806-d3f81b80-de4e-11eb-901c-709d7923326a.png)
In liDAR coordinate, the relative center shown in the picture, I just don't know what is the usage of relative coordinate of bottom center?
![image](https://user-images.githubusercontent.com/32857082/124540425-f17ab480-de51-11eb-86b8-19995ba476cc.png)
A Geiger, P Lenz, C Stiller, and R Urtasun. 2013. Vision meets robotics: The KITTI dataset. Int. J. Rob. Res. 32, 11 (September 2013), 1231–1237. DOI:https://doi.org/10.1177/0278364913491297
I found information about bottom center definition in LiDAR, just as you pointed out above. 
Thanks again~

**Comment by Physu** [comment]
In liDAR coordinate, we set relative coordinate of bottom center LiDAR box is (0.5, 0.5, 0), if we set relative coordinate of bottom center LiDAR box is (0., 0., 0.), will this cause some difference?

**Comment by Physu** [comment]
Sorry to bother you again! @Tai-Wang  I just don't know what is the reason setting (0.5, 0.5, 0) as relative coordinate of bottom center LiDAR box, the coordinate (0., 0., 0.) could be the displacement? if not, what is the reason.

**Comment by Tai-Wang** [comment]
It's all about definition. If you would like to define the relative coordinate of default center with (0, 0, 0), some other things need to be modified accordingly (e.g. the way to compute corners' coordinates).
In the current implementation, you can also specify your origin with corresponding coordinates (e.g. the gravity center is the center/origin in your setting, you can set origin=(0.5, 0.5, 0.5) and tensor[:, :3] = [the coordinates of gravity center]), and the initialization of these classes will automatically change it to the default setting. Please refer to this [line](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/bbox/structures/base_box3d.py#L65).

**Comment by Physu** [comment]
Thanks for your answer! 
When we transform CameraBox3D to LiDARBox3D, we will caculate corners, refer to [https://github.com/open-mmlab/mmdetection3d/blob/a1e04538295b02d42fc59bb7ed58c59c98220174/mmdet3d/core/bbox/structures/lidar_box3d.py#L81](url).

`        if origin != (0.5, 0.5, 0): 
            dst = self.tensor.new_tensor((0.5, 0.5, 0))
            src = self.tensor.new_tensor(origin)
            self.tensor[:, :3] += self.tensor[:, 3:6] * (dst - src)  # this line code puzzles me `

If we set the origin as (8,8,0), we get:
dst-src = (0.5,0.5,0)-(8,8,0) = (-7.5,-7.5,0)
self.tensor[:, 3:6] means the width, length, and height, self.tensor[:, 3:6] * (dst - src) means the new center location is nearly 8 times far away from the (0,0,0) coordinate location. So what is the origin meaning?

**Comment by Tai-Wang** [comment]
(8,8,0) is really a strange setting. The center transformation is usually used when the your center setting is different from the default one. For example, if your provided center is defined at (0.5, 0.5, 0.5), then this transformation will change the center coordinate to the default one (0.5, 0.5, 0) (by subtract half height along the z-axis).

**Comment by Physu** [comment]
Thansk for your response~ As you said:`provided center is defined at (0.5, 0.5, 0.5)`, I just don't know why not just set center at (0.0, 0.0, 0.0), which is more easier to calculate.

**Comment by Wuziyi616** [comment]
@Physu I think you misunderstand the term **relative coordinate**. A relative origin of `(0.5, 0.5, 0)` means `self.tensor[:, 0:3]` is calculated as `[(x1+x2)/2, (y1+y2)/2, z1]`, where `x1, x2, y1, y2, z1, z2` are the max/min coordinates of the box. This is just an encoding style of boxes, where we choose to store the bottom center of a box and its width, length, height.

As for the conversion, `self.tensor[:, 3:6] * (dst - src)` transform the difference in relative coordinate to absolute values. For example, if `src==(0.5, 0.5, 0.5)`, then `(dst - src)==(0, 0, -0.5)`, and `self.tensor[:, 3:6] * (dst - src) = (0, 0, -0.5 * height)`, so that it will transform `self.tensor[:, 0:3]` down by half the height.

**Comment by Wuziyi616** [comment]
Feel free to reopen this issue should you have any further questions :)

**Comment by Physu** [comment]
@Wuziyi616 Thanks for your explaination!
I interpert the relative orgin center as a LiDAR box(specification as picture below), its volume is 1(means w,h,l equal to 1), and the origin center is located at **[(x1+x2)/2, (y1+y2)/2, z1]**
![image](https://user-images.githubusercontent.com/32857082/125780596-da5dbef8-41e6-4830-b98d-2f8977459de2.png).

we take it as a standard metric for LiDAR box, can I just think the relative origin this way?

**Comment by Wuziyi616** [comment]
@Physu Yes, that's it! You get the point.

**Comment by CaraJ7** [comment]
> It's all about definition. If you would like to define the relative coordinate of default center with (0, 0, 0), some other things need to be modified accordingly (e.g. the way to compute corners' coordinates). In the current implementation, you can also specify your origin with corresponding coordinates (e.g. the gravity center is the center/origin in your setting, you can set origin=(0.5, 0.5, 0.5) and tensor[:, :3] = [the coordinates of gravity center]), and the initialization of these classes will automatically change it to the default setting. Please refer to this [line](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/bbox/structures/base_box3d.py#L65).

@Tai-Wang @Wuziyi616 Hi there! I wonder why the yaw angle is not considered here to derive the new (x,y,z) for the 3DBoxes. For example, if there is a yaw angle not equal to 0, and the origin input in the function is (0.5, 1, 0.5), it seems to me that this line of code https://github.com/open-mmlab/mmdetection3d/blob/962fc830daebad3f93fc7cbf970728057c64977b/mmdet3d/core/bbox/structures/base_box3d.py#L68 may fail to take into account the yaw of the box.
The image attached below may better illustrate my question.
![image](https://user-images.githubusercontent.com/61070693/204723252-b7230ab3-993e-46aa-8edf-74235da19c22.png)
Point J is src, while Point I is dst. The yaw of the box is not 0.

Hope to know where I might be wrong.
Thanks for your help!
