### ISSUE TITLE
Is mmcv correct in Dockerfile?

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#706]
Looks like [here](https://github.com/open-mmlab/mmdetection3d/blob/master/docker/Dockerfile#L16) we get `mmcv-full=1.3.5`. However minimal `mmcv` version is required to `1.3.8`.

Also do you have any plan for `torch==1.9.0` as `1.8` is annoying according to this [issue](https://github.com/pytorch/pytorch/issues/55740)?

**Comment by Wuziyi616** [comment]
Yes, we forgot to change this minimum version of MMCV in our last release. Can you kindly make an one line PR to fix it?

As for torch 1.9.0, maybe @ZwwWayne can have a look at it?
