### ISSUE TITLE
Possible bug with 'rt_mat (np.ndarray)' in coord_3d_mode

### ISSUE THREAD

**Issue by gopi231091** [open-mmlab/mmdetection3d#707]
https://github.com/open-mmlab/mmdetection3d/blob/a1e04538295b02d42fc59bb7ed58c59c98220174/mmdet3d/core/bbox/structures/coord_3d_mode.py#L246

Should it be `if rt_mat.shape[1] == 4:` to take into account both (np.ndarray | torch.Tensor) types of `rt_mat` as input 
or
convert `rt_mat` from np.ndarray to torch.Tensor before using `if rt_mat.size(1) == 4` ?

**Comment by Wuziyi616** [comment]
I agree. Can you kindly make an one-line PR to change it to `rt_mat.shape[1]`? Thanks!

**Comment by gopi231091** [comment]
I found that instead of changing to `rt_mat.shape[1]`, the second choice of converting `rt_mat` from np.ndarray to torch.Tensor helps because in further code torch.Tensor type methods are being used! I would make a PR
