### ISSUE TITLE
MVXNet pretrained img backbone.

### ISSUE THREAD

**Issue by XuyangBai** [open-mmlab/mmdetection3d#711]
Hi, thanks for this excellent codebase. I would like to know for MVX-Net, the `load_from` FasterRCNN backbone is 1. pretrained on COCO only or 2. pretrained on COCO and then finetune on KITTI? From the name `mvx_faster_rcnn_detectron2-caffe_20e_coco-pretrain_gt-sample_kitti-3-class_moderate`, I suspect the backbone is first trained on coco and then finetuned on kitti with gt sampling augmentation strategy？

**Comment by Wuziyi616** [comment]
Sorry for the late reply. This Faster R-CNN is first trained on COCO and then finetuned on KITTI (which is your `2` case). This is to stablize the training of MVXNet.
