### ISSUE TITLE
If the calib necessary when  I run the demo.py to test my own pcd file(transfer it to .bin)

### ISSUE THREAD

**Issue by clytze0216** [open-mmlab/mmdetection3d#714]
hi, open-mmlab team
I want to know If the calib necessary when  I run the demo.py to test my own pcd file(transfer it to .bin)?
It means a lot to me. Looking forward to your reply. Thanks a lot

**Comment by Wuziyi616** [comment]
It depends on what demo you want to run. If you run on point cloud only tasks (single-modality pc detection or segmentation), you don't need calib. But for tasks that involve image input (multi-modality pc detection or monocular 3d detection), the calib info is necessary to link between 2D and 3D.

**Comment by clytze0216** [comment]
> It depends on what demo you want to run. If you run on point cloud only tasks (single-modality pc detection or segmentation), you don't need calib. But for tasks that involve image input (multi-modality pc detection or monocular 3d detection), the calib info is necessary to link between 2D and 3D.

Thanks for your quickly reply！
(1) I want to test my 1 frame .pcd file with second or pointpillars model. Does it mean I can run the pcd_demo.py without calib information?
(2) If  i want to train the second model with my own data which only have pointcloud and label data. I have no calib and image data. can  I succeed？
Looking forward to your reply! Thanks again!

**Comment by clytze0216** [comment]
> > It depends on what demo you want to run. If you run on point cloud only tasks (single-modality pc detection or segmentation), you don't need calib. But for tasks that involve image input (multi-modality pc detection or monocular 3d detection), the calib info is necessary to link between 2D and 3D.
> 
> Thanks for your quickly reply！
> (1) I want to test my 1 frame .pcd file with second or pointpillars model. Does it mean I can run the pcd_demo.py without calib information?
> (2) If i want to train the second model with my own data which only have pointcloud and label data. I have no calib and image data. can I succeed？
> Looking forward to your reply! Thanks again!


Thanks for your quickly reply！
(1) I want to test my 1 frame .pcd file with second or pointpillars model. Does it mean I can run the pcd_demo.py without calib information?
(2) If  i want to train the second model with my own data which only have pointcloud and label data. I have no calib and image data. can  I succeed？
Looking forward to your reply! Thanks again!

**Comment by Wuziyi616** [comment]
Yes, you can succeed because pointpillars and second are both models that ONLY consume point cloud data. Image is not required.

**Comment by clytze0216** [comment]
@wuziyi616 
thank you very much.
but i want to train with my own data. If i have no calib information to change the coordinate as KITTI format(such as lidar_to_camera). can I get the correct AP?
sorry for bothering again.

**Comment by clytze0216** [comment]
@wuziyi616 
thank you very much.
but i want to train with my own data. If i have no calib information to change the coordinate as KITTI format(such as lidar_to_camera). can I get the correct AP?
sorry for bothering again.

**Comment by clytze0216** [comment]
@wuziyi616 
thank you very much.
but i want to train with my own data. If i have no calib information to change the coordinate as KITTI format(such as lidar_to_camera). can I get the correct AP?
sorry for bothering again.

**Comment by Wuziyi616** [comment]
For training, if you have 3D point clouds (something like `Nx3` array) and 3D boxes labels (something like `Kx6` array), then you can train the model. However, if they are like KITTI raw data, then you need calib to transform the boxes labels.

**Comment by clytze0216** [comment]
@wuziyi616 
thank you very much.
but i want to train with my own data. If i have no calib information to change the coordinate as KITTI format(such as lidar_to_camera). can I get the correct AP?
sorry for bothering again.

**Comment by clytze0216** [comment]
@wuziyi616 
thank you very much.
but i want to train with my own data. If i have no calib information to change the coordinate as KITTI format(such as lidar_to_camera). can I get the correct AP?
sorry for bothering again.

**Comment by Fungungun** [comment]
> For training, if you have 3D point clouds (something like `Nx3` array) and 3D boxes labels (something like `Kx6` array), then you can train the model. However, if they are like KITTI raw data, then you need calib to transform the boxes labels.

Hi Thanks for your reply. I'm also trying to train the point cloud only detector on my own dataset. I have converted both the point cloud and the annotation to the exact KITTI format. 

However when I always got 0 AP for every test when I was training PointPillar.

The only difference with my data is that, in the KITTI txt anno file, the location is in CAM coords but my 3d box labels are in point cloud coords. Since I only have point cloud data and no camere data and calibration data, I won't be able to convert the 3d box labels to the CAM coords.  

Could you please let me know how to deal with that ?


Thanks
