### ISSUE TITLE
Possible bug in 'bev_range' of ObjectRangeFilter

### ISSUE THREAD

**Issue by gopi231091** [open-mmlab/mmdetection3d#716]
https://github.com/open-mmlab/mmdetection3d/blob/ea846013ed0b1e561887ec1789fcaae2a0c037e8/mmdet3d/datasets/pipelines/transforms_3d.py#L702

Here, I think it is assumed that the points coordinate system is LIDAR (KITTI: Z-up) by default, but isn't this should be made consistent to points type (like LIDAR or CAMERA), because if points are loaded in CAMERA coordinate system (KITTI: Y-down), then the respective code should be `self.bev_range = self.pcd_range[[0, 2, 3, 5]]`. Did I understood correctly ?

If yes, I suggest to move the respective line to `__call__ ` so that we can check the instance of `input_dict['points']` and then initialize `self.bev_range` accordingly!

**Comment by Wuziyi616** [comment]
Yes, this really makes sense. Currently, we only use this transform in LiDAR point cloud loading so it won't cause any problems, but it's your concern is reasonable. Can you kindly raise a PR to fix it? I think your solution of checking the type of points is great!
