### ISSUE TITLE
Monocular 3D Detection FCOS3D Demo Failure due to size mismatch for neck.fpn_convs.3.conv.weight

### ISSUE THREAD

**Issue by bml1g12** [open-mmlab/mmdetection3d#719]
**Describe the bug**

I am using CUDA 11.1 on Ubunu 20.04 and docker:
`docker run --gpus all --shm-size=8g -it mmdetection3d`

**Reproduction**

Downloaded the finetuned model from here: https://download.openmmlab.com/mmdetection3d/v0.1.0_models/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210427_091419-35aaaad0.pth

And followed the demo here https://mmdetection3d.readthedocs.io/en/latest/demo.html#monocular-3d-detection:
```
root@d5a18d54d399:/mmdetection3d# python demo/mono_det_demo.py demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525.jpg demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525_mono3d.coco.json configs/fcos3d/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune.py checkpoints/fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210427_091419-35aaaad0.pth

/opt/conda/lib/python3.7/site-packages/mmcv/cnn/bricks/conv_module.py:107: UserWarning: ConvModule has norm and bias at the same time
  warnings.warn('ConvModule has norm and bias at the same time')
Use load_from_local loader
The model and loaded state dict do not match exactly

size mismatch for neck.fpn_convs.3.conv.weight: copying a param with shape torch.Size([256, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 2048, 3, 3]).
```

Would be very grateful for assistance, as this is my first time using the repo and thought the demo would be a good place to start.  Am I doing something wrong?

**Comment by Wuziyi616** [comment]
Thank you for your comment. We didn't see such issue in an older version of mmdet3d (say, v0.14.0). However, mmdet3d v0.15.0 does have such issue. @xiliu8006 is looking into it.

Update: I have run the demo and also encountered this warning. But the saved visualization result is the same as previous. Maybe this issue won't affect FCOS3D's output. So I think you can still use the codebase without bugs.

**Comment by bml1g12** [comment]
@xiliu8006  please could you confirm whether this warning can safely be ignored? (Would be reassuring as it sounds like maybe a mismatch in the default layer dimensions versus that the model was trained at, which could lead to inconsistencies)

**Comment by xiliu8006** [comment]
OK, I will check it as soon as possible, I am sorry for the delayed response.

**Comment by xiliu8006** [comment]
> @xiliu8006 please could you confirm whether this warning can safely be ignored? (Would be reassuring as it sounds like maybe a mismatch in the default layer dimensions versus that the model was trained at, which could lead to inconsistencies)

Thanks for your comments, it is a bug, because there is a [bc-breaking] in mmdet

**Comment by Wuziyi616** [comment]
Then why the model output is the same? Maybe FCOS3D doesn't use this layer in producing output?

**Comment by xiliu8006** [comment]
> Then why the model output is the same? Maybe FCOS3D doesn't use this layer in producing output?

The output is not same, if you run the tools/dist_test.sh, you will find the map is 22.2 (the right map is 29.9).

**Comment by Wuziyi616** [comment]
OK, maybe demo is a special case :)
