### ISSUE TITLE
How to plot model evaluation results during evaluation

### ISSUE THREAD

**Issue by Balazizo** [open-mmlab/mmdetection3d#721]
Hello, I'm trying to plot the model's resulting mAP on a graph to visualize how the result of the BBox3D increases and decreases from frame-to-frame. Is there a way to do this?

**Comment by Wuziyi616** [comment]
You mean testing one weight and see the mAP values between different frames? We currently don't support this function. Maybe you can save the visualization results?

**Comment by Balazizo** [comment]
What of the commands available at https://mmdetection.readthedocs.io/en/latest/useful_tools.html#result-analysis ? Can these not be used to plot mAP results for a certain model? If so, how do I specify in the command which model to plot?

**Comment by Wuziyi616** [comment]
Yes we have command to plot the mAPs of a model in different epochs (see [here](https://mmdetection3d.readthedocs.io/en/latest/useful_tools.html#log-analysis)). The command can be like:
```
python tools/analysis_tools/analyze_logs.py plot_curve exps/xxx/${some_model}.log.json --keys mAP_0.50 --out exps/xxx/map.pdf --mode eval
```
where you need to specify the `log.json` file generated by our training program and a metric to plot (e.g. `mAP_0.50` for VoteNet).

**Comment by Balazizo** [comment]
Thank you kindly for your response @Wuziyi616.
