### ISSUE TITLE
python demo.py----->Error

### ISSUE THREAD

**Issue by KangChou** [open-mmlab/mmdetection3d#723]
python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --out-dir data/output_result/ 

```
UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator`` 
  '``build_anchor_generator`` would be deprecated soon, please use '
Use load_from_local loader

```

**Comment by Wuziyi616** [comment]
This is not an **error**, just a deprecation warning. I believe the demo output is correct.
