### ISSUE TITLE
Definitions of Evaluation Results 

### ISSUE THREAD

**Issue by Balazizo** [open-mmlab/mmdetection3d#724]
Hello, I've evaluated both Second and MVXNet on some adverse weather conditions. However, I'm struggling to understand the format of the results.  My problems are as follow:

1.   I understand that AP@0.70/0.50/0.25 means IOU thresholds of 70%, 50%, and 25%, respectively; meaning overlaps have to meet these thresholds to count as true positives then why is it that the 70% is labeled as easy not hard when it should be harder to achieve IOU of 70% then 50% and 50% than 25%?

2.  The results are divided into 4 categories: BBox, Bev, 3d, and aos.  Some of these are familiar while others are not. BBox, I believe means the accuracy of estimating 2D boxes from the 3D boxes (please do correct me if I'm wrong). Bev means bird's eye view, though I'm not sure what it means in the context of object detection. 3d I believe means the accuracy of estimating 3D orientation but isn't that measured by aos?

3.  Finally, there are 2 sets of results for each class, "strict" and "loose". These terms are unfamiliar to me.

A detailed response would be greatly appreciated.

**Comment by Tai-Wang** [comment]
Please refer to #185 and the definition given by the [official website](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d).

**Comment by Balazizo** [comment]
Thank you @Tai-Wang for your response. However, it's still not explained what "strict" and "loose" metrics means. Please explain.

**Comment by Tai-Wang** [comment]
“strict” refers to more strict criteria for positive predictions. For example, IOU>0.7 is strict for car while 0.5 is the loose one. For cyclist and pedestrian, IOU>0.5 is strict and 0.25 is loose. You can observe these evaluation messages more clearly in the print results when training/evaluating a specific model.
