### ISSUE TITLE
border_align_forward miss in module _ext when run demo.py

### ISSUE THREAD

**Issue by sherylwang** [open-mmlab/mmdetection3d#727]
Hi, after I installed mmdetection3d according to the getting_started.md. When I run the demo.py "python demo/pcd_demo.py demo/data/kitti/kitti_000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth --out-dir data/output_result/".
An error occured like: 
![image](https://user-images.githubusercontent.com/10609885/125246519-78350300-e324-11eb-972a-865d96801730.png)

**Comment by wHao-Wu** [comment]
Hi, @sherylwang 

Have you installed and built mmcv, mmdet, mmdet3d successfully.

For checking, you can run python with your environment and running `import mmcv, mmdet, mmdet3d`.

**Comment by sherylwang** [comment]
> mmdet3d

No error occured after running" import mmcv, mmdet, mmdet3d".

**Comment by sherylwang** [comment]
> Hi, @sherylwang
> 
> Have you installed and built mmcv, mmdet, mmdet3d successfully.
> 
> For checking, you can run python with your environment and running `import mmcv, mmdet, mmdet3d`.

Thanks for reply. No error occured after running "import mmcv, mmdet, mmdet3d".

**Comment by wHao-Wu** [comment]
It's a strange problem. What's the version of mmcv, mmdet, mmseg, mmdet3d?

**Comment by Wuziyi616** [comment]
@sherylwang Try running `python mmdet3d/utils/collect_env.py` and put the log here? It will show your environment as well as package versions.

**Comment by sherylwang** [comment]
> @sherylwang Try running `python mmdet3d/utils/collect_env.py` and put the log here? It will show your environment as well as package versions.

The same error occured. After I commented the 2 lines in "/opt/conda/lib/python3.7/site-packages/mmcv/utils/ext_loader.py ". The log looked like:
```
sys.platform: linux
Python: 3.7.7 (default, Mar 23 2020, 22:36:06) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: GeForce GTX 1080 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2
OpenCV: 4.5.2
MMCV: 1.3.9
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: 10.2
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.15.0+e58684a
```

**Comment by Wuziyi616** [comment]
According to the error message, it seems you didn't compile some custom ops in mmcv. Did you install mmcv or mmcv-full? The compilation command for mmcv-full should be `MMCV_WITH_OPS=1 pip install -e .`.

**Comment by Wuziyi616** [comment]
@sherylwang Any updates here? Do you still have the problem and we can discuss further about how to solve it? Or is it solved and I can close the issue?

**Comment by Wuziyi616** [comment]
Feel free to reopen this issue should you have any further questions :)
