### ISSUE TITLE
Does mmdet3d support calculating the model parameters or flops?

### ISSUE THREAD

**Issue by gujiaqivadin** [open-mmlab/mmdetection3d#731]
Hello!
   I am here to ask whether mmdet3d support calculating the model parameters or flops in current version code. Thanks a lot !

**Comment by Wuziyi616** [comment]
Have a look at [this instruction](https://mmdetection3d.readthedocs.io/en/latest/useful_tools.html#model-complexity). MMDet3D can calculate flops and params just as MMDet does, though I am afraid some custom GPU ops won't be correctly calculated.

**Comment by gujiaqivadin** [comment]
Thanks for your reply! The instruction is mainly designed for mmdet models with img shapes, does it also support points input? I try to copy it to my mmdet3d directory to calculate the models, but it didn't work and produced error messages.

**Comment by Wuziyi616** [comment]
Thank you for pointing it out! Yes I discover that mmdet's `get_flops.py` can't be directly used here. I will raise a PR to support it in mmdet3d.

**Comment by Wuziyi616** [comment]
See #736 where I do a quick development. However, we don't support multi-modality models (MVX-Net, ImVoteNet) and two-stage models now (PartA^2).

**Comment by gujiaqivadin** [comment]
Thanks for your quick pr, and I will try to use it in my models tonight. Really appreciate it.

**Comment by Wuziyi616** [comment]
Glad it helps :)
