### ISSUE TITLE
can i use mmdetection3d to realize multiview 3D object detection demo?

### ISSUE THREAD

**Issue by jasmine202106** [open-mmlab/mmdetection3d#742]
Hi,
i read the doc about "Vision-Based 3D Detection". it writes that Vision-based 3D detection refers to the 3D detection solutions based on vision-only input, such as monocular, binocular, and **multi-view** image based 3D detection. 

i want to realize one demo, its input is two or three images from different views of one object and output is 3D bounding boxes of the object.
can mmdetection3d  realize this function? if OK, can you tell how to realize it? thanks very much.

**Comment by Wuziyi616** [comment]
MMDet3D doesn't support multi-view detector currently, but of course this is our planned feature. #696 is an ongoing PR targeting on some basic functions to support it. I am afraid you can't use current codebase to achieve a demo.

**Comment by jasmine202106** [comment]
OK, thanks very much!
