### ISSUE TITLE
How can I use nuscenes dataset to train models only with partial classes?

### ISSUE THREAD

**Issue by zhangtingyu11** [open-mmlab/mmdetection3d#751]
I want to use nuscenes dataset to train centerpoint,but I only need to inference partial classes(not all),how can I do this?

**Comment by zhangtingyu11** [comment]
INFO:mmdet:Epoch [1][600/10513]	lr: 1.001e-04, eta: 1 day, 21:24:03, time: 0.761, data_time: 0.007, memory: 4606, task0.loss_heatmap: 1.9267, task0.loss_bbox: 0.7909, task1.loss_heatmap: 2.5116, task1.loss_bbox: 0.9205, task2.loss_heatmap: 1.8746, task2.loss_bbox: 0.8080, task3.loss_heatmap: 0.0082, task3.loss_bbox: 0.0000, task4.loss_heatmap: 0.0128, task4.loss_bbox: 0.0000, task5.loss_heatmap: 0.0155, task5.loss_bbox: 0.0000, loss: 8.8688, grad_norm: 11.6817

**Comment by Tai-Wang** [comment]
Have you ever changed the class setting (not covered by the integrated config) in the `centerpoint_02pillar_second_secfpn_nus.py` and `nus-3d.py`?

**Comment by Tai-Wang** [comment]
Close due to inactivity.
