### ISSUE TITLE
Optimize model through c++ code integration

### ISSUE THREAD

**Issue by selmadeac** [open-mmlab/mmdetection3d#752]
Hi! I am trying to optimize a model by integrating c++ code. I created a shared library object using pybind11. Locally, on a test,py project, I can successfully access the c++ functions from python, but when I try to integrate it into mmdetection3d, and try to train a model, I get ModuleNotFoundError: No module named X.

Could you please tell me why? Or is there a tutorial on how to extend the framework through c++ code?

**Comment by Wuziyi616** [comment]
We don't have such tutorial, sorry for that. Can you post the entire error message? Your description is not enough for us to judge what the reason is. Maybe you can give us more information? Like what the module is used for, where do you put it and how do you import it.

**Comment by Wuziyi616** [comment]
@selmadeac Any updates here?

**Comment by selmadeac** [comment]
> @selmadeac Any updates here?

sure! sorry for the late reply, @Wuziyi616 ! I have seen you messages just now. I found out how on my own and I forgot to update the post. So, after getting the shared library file ( *.so) file one has to go to `setup.py `file in mmdetection3d main folder. There ,one should integrate their library by adding a make cuda ext:

```
make_cuda_ext(
                name='library name', #eg: voxel_layer
                module='path from base folder (mmdetection3d) to the folder where the so file is', # eg: mmdet3d.ops.voxel
                sources=[ # and here put the cpp sources with your custom functions
                 # for  eg:
                    'src/voxelization.cpp',
                ]),
```

after that one has to run `python setup.py develop` and now mmdetection3d will recognize your custom c library as one of its own.

Hope this will help future developers and make their work easier!

**Comment by Wuziyi616** [comment]
Hi! Thanks for your update! Hope this will help future developers :)
