### ISSUE TITLE
Kitti Dataset Datasplit Error

### ISSUE THREAD

**Issue by JasonWUCHI** [open-mmlab/mmdetection3d#753]
I have downloaded left color images, calibration, label, and velodyne dataset from the kitti 3d official website and also placed them to the folder by following the [mmdetection3d official website ](https://mmdetection3d.readthedocs.io/en/latest/data_preparation.html), I also down load the txt files for data split

However when I run the last line "python tools/create_data.py kitti --root-path ./data/kitti --out-dir ./data/kitti --extra-tag kitti", there is an error saying index out of range. Could anyone give me some help? 
<img width="942" alt="Screen Shot 2021-07-15 at 1 19 52 AM" src="https://user-images.githubusercontent.com/59639661/125664981-9ecedfa7-70eb-4e48-8c1e-77cc7c354aba.png">

**Comment by Wuziyi616** [comment]
Can list your file structures under `mmdetection3d/data/kitti/`? Are they the same as shown in the docs?
```
mmdetection3d
├── mmdet3d
├── tools
├── configs
├── data
│   ├── kitti
│   │   ├── ImageSets
│   │   ├── testing
│   │   │   ├── calib
│   │   │   ├── image_2
│   │   │   ├── velodyne
│   │   ├── training
│   │   │   ├── calib
│   │   │   ├── image_2
│   │   │   ├── label_2
│   │   │   ├── velodyne
```

**Comment by JasonWUCHI** [comment]
I solved it. It is because that I use a bad method to upload the file to ssh, so some data is missing. Thank you for your support.

**Comment by Wuziyi616** [comment]
Glad it helps :)
