### ISSUE TITLE
Backpropagating the output of dense head

### ISSUE THREAD

**Issue by AfonsoSalgadoSousa** [open-mmlab/mmdetection3d#759]
Hi. I am trying to backpropagate in a custom training routine the output losses of a dense head, namely Anchor3DHead. I analysed the MMCV toolkit for the way to do this, and in the 'after_train_iter' optimizer hook, there is the following line:
https://github.com/open-mmlab/mmcv/blob/366c628a85daf71fa26f652b402277c90d9f7d6e/mmcv/runner/hooks/optimizer.py#L36
But there should not be a _loss_ key in the dictionary, but _loss_cls_, _loss_bbox_ and _loss_dir_. Where does this _loss_ come from?

**Comment by Wuziyi616** [comment]
See [here](https://github.com/open-mmlab/mmdetection/blob/475c6bec197e6b495d48146636301590165d8f66/mmdet/models/detectors/base.py#L197) which sum up the losses.

**Comment by AfonsoSalgadoSousa** [comment]
Thank you very much. Sorry for the stupid question. I am still learning to navigate your toolkit.

**Comment by Wuziyi616** [comment]
Never mind! Feel free to open issues should you have any further questions!
