### ISSUE TITLE
How can I modify the config for point_cloud_range??

### ISSUE THREAD

**Issue by FFudi** [open-mmlab/mmdetection3d#76]
First of all, thank you for providing a great framework.

I have a problem during inference through ros using "hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py", so I would like to ask a question.

My range is currently as follows, but it does not work properly when modifying the value.

How do I write a config to detect a vehicle in 360 degrees?

![Screenshot from 2020-08-24 03-14-43](https://user-images.githubusercontent.com/30746404/90985602-0478f300-e5b8-11ea-8d73-2a02b66af239.png)

If I use the default range config, it works fine as shown below, but I can only see 180 degrees.

![Screenshot from 2020-08-24 03-17-33](https://user-images.githubusercontent.com/30746404/90985674-72251f00-e5b8-11ea-8ebf-e9b84175ddee.png)

As far as I can see, the pointpillars model using Nuscense can normally use 360 degrees.
Any help would be greatly appreciated.

**Comment by Tai-Wang** [comment]
For kitti, since the evaluation is only focused on objects that can be projected to the image, we typically use reduced point clouds that filter out those out of the front view. Also, when converting predictions to valid results, we filter out those bounding boxes out of the front view. For more details, you can refer to the 'pts_prefix' setting in configs/_base_/datasets/kitti-3d-3class.py and 'convert_valid_bboxes' in mmdet3d/datasets/kitti_dataset.py.

**Comment by Dinghow** [comment]
> First of all, thank you for providing a great framework.
> 
> I have a problem during inference through ros using "hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py", so I would like to ask a question.
> 
> My range is currently as follows, but it does not work properly when modifying the value.
> 
> How do I write a config to detect a vehicle in 360 degrees?
> 
> ![Screenshot from 2020-08-24 03-14-43](https://user-images.githubusercontent.com/30746404/90985602-0478f300-e5b8-11ea-8d73-2a02b66af239.png)
> 
> If I use the default range config, it works fine as shown below, but I can only see 180 degrees.
> 
> ![Screenshot from 2020-08-24 03-17-33](https://user-images.githubusercontent.com/30746404/90985674-72251f00-e5b8-11ea-8ebf-e9b84175ddee.png)
> 
> As far as I can see, the pointpillars model using Nuscense can normally use 360 degrees.
> Any help would be greatly appreciated.

Hi, FFudi. Have you solved this issue, I wonder a config to show the 360 prediction result, thx.

**Comment by tonywong-1115** [comment]
> First of all, thank you for providing a great framework.
> 
> I have a problem during inference through ros using "hv_pointpillars_secfpn_6x8_160e_kitti-3d-car.py", so I would like to ask a question.
> 
> My range is currently as follows, but it does not work properly when modifying the value.
> 
> How do I write a config to detect a vehicle in 360 degrees?
> 
> ![Screenshot from 2020-08-24 03-14-43](https://user-images.githubusercontent.com/30746404/90985602-0478f300-e5b8-11ea-8d73-2a02b66af239.png)
> 
> If I use the default range config, it works fine as shown below, but I can only see 180 degrees.
> 
> ![Screenshot from 2020-08-24 03-17-33](https://user-images.githubusercontent.com/30746404/90985674-72251f00-e5b8-11ea-8ebf-e9b84175ddee.png)
> 
> As far as I can see, the pointpillars model using Nuscense can normally use 360 degrees. Any help would be greatly appreciated.

Hi, FFudi, im currently deploying the mmdet3d on ROS, im wondering if its possible to share ur ros deployment showed on the screenshot to me, thanks!
