### ISSUE TITLE
I would like to ask the meaning of each field in the 'pred.obj' file after test.

### ISSUE THREAD

**Issue by stidk** [open-mmlab/mmdetection3d#762]
v -17.39366443 60.97285097 -1.53954911
v -17.39366443 60.97285097 -0.07447958
v -15.75416279 60.98621936 -1.53954911
v -15.75416279 60.98621936 -0.07447958
v -17.35991192 56.83343701 -1.53954911
v -17.35991192 56.83343701 -0.07447958
v -15.72041028 56.84680540 -1.53954911
v -15.72041028 56.84680540 -0.07447958
v 6.15023609 27.86416259 -1.19017625
v 6.15023609 27.86416259 0.29838586
v 6.24029554 29.52389490 -1.19017625
v 6.24029554 29.52389490 0.29838586
v 10.57877718 27.62386359 -1.19017625
v 10.57877718 27.62386359 0.29838586
v 10.66883664 29.28359589 -1.19017625
v 10.66883664 29.28359589 0.29838586
v -20.83521177 41.75506307 -1.88493723
v -20.83521177 41.75506307 -0.36509806
v -19.18840385 41.67552338 -1.88493723
v -19.18840385 41.67552338 -0.36509806
v -21.02796196 37.76431884 -1.88493723
v -21.02796196 37.76431884 -0.36509806
v -19.38115405 37.68477915 -1.88493723
v -19.38115405 37.68477915 -0.36509806
v -24.21283260 48.19473993 -1.61120164
v -24.21283260 48.19473993 -0.16652310
v -22.49670412 48.08827495 -1.61120164
v -22.49670412 48.08827495 -0.16652310
v -24.41509626 44.93441486 -1.61120164
v -24.41509626 44.93441486 -0.16652310
v -22.69896778 44.82794989 -1.61120164
v -22.69896778 44.82794989 -0.16652310
v 4.25005418 35.21658893 -1.54420865
v 4.25005418 35.21658893 -0.09144127
v 2.68744668 35.41141284 -1.54420865
v 2.68744668 35.41141284 -0.09144127
v 4.70765487 38.88682783 -1.54420865
v 4.70765487 38.88682783 -0.09144127
v 3.14504737 39.08165173 -1.54420865
v 3.14504737 39.08165173 -0.09144127
f 2 4 1
f 5 2 1
f 1 4 3
f 3 5 1
f 2 8 4
f 6 2 5
f 6 8 2
f 4 8 3
f 7 5 3
f 3 8 7
f 7 6 5
f 8 6 7
f 10 12 9
f 13 10 9
f 9 12 11
f 11 13 9
f 10 16 12
f 14 10 13
f 14 16 10
f 12 16 11
f 15 13 11
f 11 16 15
f 15 14 13
f 16 14 15
f 18 20 17
f 21 18 17
f 17 20 19
f 19 21 17
f 18 24 20
f 22 18 21
f 22 24 18
f 20 24 19
f 23 21 19
f 19 24 23
f 23 22 21
f 24 22 23
f 26 28 25
f 29 26 25
f 25 28 27
f 27 29 25
f 26 32 28
f 30 26 29
f 30 32 26
f 28 32 27
f 31 29 27
f 27 32 31
f 31 30 29
f 32 30 31
f 34 36 33
f 37 34 33
f 33 36 35
f 35 37 33
f 34 40 36
f 38 34 37
f 38 40 34
f 36 40 35
f 39 37 35
f 35 40 39
f 39 38 37
f 40 38 39
---------------------------------------------------------------
What do you mean by a field that starts with 'v' or 'f', may 'v' mean the  coordinates of 3d box? what about the 'f',is it a rotation matrix ? What is the size of each group ?

**Comment by THU17cyz** [comment]
Hi @stidk , `obj` is a general 3D mesh data format and you can look for detailed description on the Internet. Let me explain it for you: 'v' means the coordinate of a **'vertex'** (or point) and 'f' means the indices of the 3 vertices that form this **'face'**. For example, 'f 40 38 39' means that the 38th, 39th, 40th vertices form a face.

**Comment by Wuziyi616** [comment]
See the [wiki](https://en.wikipedia.org/wiki/Wavefront_.obj_file) for more details.
