### ISSUE TITLE
Class values must be non-negative Error

### ISSUE THREAD

**Issue by AfonsoSalgadoSousa** [open-mmlab/mmdetection3d#764]
Hi. I am having some trouble with focal loss in certain batches (some work, and some throw the following error:

> Traceback (most recent call last):
>   File "train.py", line 220, in <module>
>     losses = bbox_head.loss(*loss_inputs)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/afonso/projects/image_to_lidar/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py", line 366, in loss
>     num_total_samples=num_total_samples)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/misc.py", line 29, in multi_apply
>     return tuple(map(list, zip(*map_results)))
>   File "/home/afonso/projects/image_to_lidar/mmdetection3d/mmdet3d/models/dense_heads/anchor3d_head.py", line 218, in loss_single
>     cls_score, labels, label_weights, avg_factor=num_total_samples)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/losses/focal_loss.py", line 166, in forward
>     target = F.one_hot(target, num_classes=num_classes + 1)
> RuntimeError: Class values must be non-negative.

My config:
```
bbox_head=dict(
    type='Anchor3DHead',
    num_classes=3,
    in_channels=128,
    feat_channels=128,
    use_direction_classifier=True,
    anchor_generator=dict(
        type='AlignedAnchor3DRangeGenerator',
        ranges=[
            [0, -39.68, -0.6, 70.4, 39.68, -0.6],
            [0, -39.68, -0.6, 70.4, 39.68, -0.6],
            [0, -39.68, -1.78, 70.4, 39.68, -1.78],
        ],
        sizes=[[0.6, 0.8, 1.73], [0.6, 1.76, 1.73], [1.6, 3.9, 1.56]],
        rotations=[0, 1.57],
        reshape_out=False),
    diff_rad_by_sin=True,
    bbox_coder=dict(type='DeltaXYZWLHRBBoxCoder'),
    loss_cls=dict(
        type='FocalLoss',
        use_sigmoid=True,
        gamma=2.0,
        alpha=0.25,
        loss_weight=1.0),
    loss_bbox=dict(type='SmoothL1Loss', beta=1.0 / 9.0, loss_weight=2.0),
    loss_dir=dict(
        type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.2),
    # model training and testing settings
    train_cfg=dict(
        assigner=[
            dict(  # for Pedestrian
                type='MaxIoUAssigner',
                iou_calculator=dict(type='BboxOverlapsNearest3D'),
                pos_iou_thr=0.5,
                neg_iou_thr=0.35,
                min_pos_iou=0.35,
                ignore_iof_thr=-1),
            dict(  # for Cyclist
                type='MaxIoUAssigner',
                iou_calculator=dict(type='BboxOverlapsNearest3D'),
                pos_iou_thr=0.5,
                neg_iou_thr=0.35,
                min_pos_iou=0.35,
                ignore_iof_thr=-1),
            dict(  # for Car
                type='MaxIoUAssigner',
                iou_calculator=dict(type='BboxOverlapsNearest3D'),
                pos_iou_thr=0.6,
                neg_iou_thr=0.45,
                min_pos_iou=0.45,
                ignore_iof_thr=-1),
        ],
        allowed_border=0,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        use_rotate_nms=True,
        nms_across_levels=False,
        nms_thr=0.01,
        score_thr=0.1,
        min_bbox_size=0,
        nms_pre=100,
        max_num=50)
)
```

My code:
```
outs = bbox_head([Variable(fusion.to('cpu'), requires_grad=True)])
# print(data_batch['gt_bboxes_3d'].data[0])
loss_inputs = outs + (data_batch['gt_bboxes_3d'].data[0],
                    data_batch['gt_labels_3d'].data[0], data_batch['img_metas'].data[0])
losses = bbox_head.loss(*loss_inputs)
```

Shouldn't the use_sigmoid=True prevent this non-negative class error from happening? Do you have any insights on this issue? Thank you for any help you can provide.

**Comment by Wuziyi616** [comment]
The error comes from this line `target = F.one_hot(target, num_classes=num_classes + 1)`, which means your `target` (a.k.a. GT labels) has some negative values. Maybe your `gt_labels_3d` has some negative values? I would suggest you to use a `try-catch` to warp this code block, and print the labels which cause error to see if there are any negative values.

**Comment by AfonsoSalgadoSousa** [comment]
Thanks for the response. It actually does. When printing the gt_labels_3d it contains "-1" values. But I use the same data preparation routine as in your training script:
```
datasets = [build_dataset(cfg.data.train)]
val_dataset = copy.deepcopy(cfg.data.val)
# in case we use a dataset wrapper
if 'dataset' in cfg.data.train:
    val_dataset.pipeline = cfg.data.train.dataset.pipeline
else:
    val_dataset.pipeline = cfg.data.train.pipeline
val_dataset.test_mode = False
datasets.append(build_dataset(val_dataset))

dataset = datasets if isinstance(datasets, (list, tuple)) else [datasets]

data_loaders = [
    build_dataloader(
        ds,
        cfg.data.samples_per_gpu,
        cfg.data.workers_per_gpu,
        1,
        dist=False,
        seed=0) for ds in dataset
]
```
Then I just use a _for_ loop to iterate over the batches. What does the -1 mean and how can I avoid it?

**Comment by Wuziyi616** [comment]
The way you build `datasets` and `data_loaders` is correct, no need to worry. It's simply because the loaded `gt_labels_3d` contains `-1`, which is normal (this situation does happen in `KITTI` dataset). To make it work, I think you need to deal with these `-1` values before sending them into loss calculation. Maybe you can refer to [here](https://github.com/open-mmlab/mmdetection3d/blob/da4c3af9db571eee5b3fc7cd059eaf4764a698ca/mmdet3d/models/dense_heads/ssd_3d_head.py#L338), where we remove boxes with `-1` labels.

**Comment by AfonsoSalgadoSousa** [comment]
That fixed the problem. Thank you very much.
