### ISSUE TITLE
fcos3d :demo/mono_det_demo.py wrong visuliaztion results

### ISSUE THREAD

**Issue by DMing11** [open-mmlab/mmdetection3d#771]
I got the result as below when run demo/mono_det_demo.py in the master branch
![image](https://user-images.githubusercontent.com/44012690/126465851-18792016-dc3c-4f59-a8ba-2a700d5ba69e.png)
and run /tools/test.py  got the result as below
![image](https://user-images.githubusercontent.com/44012690/126466866-7a9af632-a834-4805-86ba-3edf62280f04.png)

I have tried setting several --score-thr to filter low confidence boxes, but don't got the same results as https://github.com/open-mmlab/mmdetection3d/pull/542
need to using NMS to filter detection results? 
Thanks

**Comment by Tai-Wang** [comment]
Could you please try with the threshold 0.15? There will also be overlapped boxes left because we do not apply nms among feature levels, but I think it should not be so many.

**Comment by DMing11** [comment]
Thanks for your reply. Yes I have tried with the threshold 0.15 and there are also be overlapped boxes left, but I think  a detected object should eventually have only one box, like https://github.com/open-mmlab/mmdetection3d/pull/542 , his results look beautiful , I want to know how he did it .Is it just adjusting the threshold?
thanks!

**Comment by Wuziyi616** [comment]
Hi @DMing11 I am the author of #542. The visualization with only one box per object is simply because I use GT instead of the predicted results from FCOS3D. You can see the 1st, 3rd and 4th images I post there also have many overlapped boxes for each object. I think your first image result is very similar to what I got in #542?

**Comment by DMing11** [comment]
So it is !  Thank you very much ! @Wuziyi616

**Comment by Treemann** [comment]
Hi, @DMing11 @Wuziyi616 @Tai-Wang 
I met the same problem of keeping so many bboxes overlap with each other and I found it's caused by the setting of 'nms_thr'. The default setting is 'nms_thr=0.8', you could set it to a lower value (like 0.2) and the visualization result will be much better.
