### ISSUE TITLE
error: command '/usr/local/cuda-10.1/bin/nvcc' failed with exit status 1

### ISSUE THREAD

**Issue by qfwysw** [open-mmlab/mmdetection3d#790]
Thanks for your great work!
I have trouble in compiling the mmdection3d. I'm interested in polintpillar, then I want to compile the voxelization Individually. 
The version of cuda and nvcc are 10.1. The vertion of torch is 1.6.0. So can you help me, I really don't know where I did wrong.
![image](https://user-images.githubusercontent.com/53482524/126903025-2744502c-2526-4b61-b7c4-1bb9ecbdbfb2.png)

####################################################################
running develop
running egg_info
writing mmdet3d.egg-info/PKG-INFO
writing dependency_links to mmdet3d.egg-info/dependency_links.txt
writing top-level names to mmdet3d.egg-info/top_level.txt
/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/utils/cpp_extension.py:335: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'mmdet3d.egg-info/SOURCES.txt'
writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
running build_ext
building 'data.voxel_layer' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/data
creating build/temp.linux-x86_64-3.7/data/src
gcc -pthread -B /home/fqu/.conda/envs/mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include -I/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/fqu/.conda/envs/mmlab/include/python3.7m -c data/src/voxelization.cpp -o build/temp.linux-x86_64-3.7/data/src/voxelization.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=voxel_layer -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from data/src/voxelization.cpp:1:
/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)

gcc -pthread -B /home/fqu/.conda/envs/mmlab/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include -I/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/fqu/.conda/envs/mmlab/include/python3.7m -c data/src/scatter_points_cpu.cpp -o build/temp.linux-x86_64-3.7/data/src/scatter_points_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=voxel_layer -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/ATen/Parallel.h:149:0,
                 from /home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/utils.h:3,
                 from /home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn/cloneable.h:5,
                 from /home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/nn.h:3,
                 from /home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/extension.h:4,
                 from data/src/scatter_points_cpu.cpp:2:
/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/ATen/ParallelOpenMP.h:84:0: warning: ignoring #pragma omp parallel [-Wunknown-pragmas]
 #pragma omp parallel for if ((end - begin) >= grain_size)

/usr/local/cuda-10.1/bin/nvcc -DWITH_CUDA -I/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include -I/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/TH -I/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/fqu/.conda/envs/mmlab/include/python3.7m -c data/src/scatter_points_cuda.cu -o build/temp.linux-x86_64-3.7/data/src/scatter_points_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=voxel_layer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75 -std=c++14
/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/ATen/record_function.h(18): warning: attribute "__visibility__" does not apply here

/home/fqu/.conda/envs/mmlab/lib/python3.7/site-packages/torch/include/ATen/record_function.h(18): warning: attribute "__visibility__" does not apply here

/usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
/usr/include/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/include/c++/7/bits/basic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/include/c++/7/bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char16_t*; _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’
/usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/7/bits/basic_string.h:6688:95:   required from here
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char16_t; _Traits = std::char_traits<char16_t>; _Alloc = std::allocator<char16_t>]’ without object
       __p->_M_set_sharable();
       ~~~~~~~~~^~
/usr/include/c++/7/bits/basic_string.tcc: In instantiation of ‘static std::basic_string<_CharT, _Traits, _Alloc>::_Rep* std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_S_create(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’:
/usr/include/c++/7/bits/basic_string.tcc:578:28:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&, std::forward_iterator_tag) [with _FwdIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.h:5042:20:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct_aux(_InIterator, _InIterator, const _Alloc&, std::__false_type) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.h:5063:24:   required from ‘static _CharT* std::basic_string<_CharT, _Traits, _Alloc>::_S_construct(_InIterator, _InIterator, const _Alloc&) [with _InIterator = const char32_t*; _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’
/usr/include/c++/7/bits/basic_string.tcc:656:134:   required from ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]’
/usr/include/c++/7/bits/basic_string.h:6693:95:   required from here
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
error: command '/usr/local/cuda-10.1/bin/nvcc' failed with exit status 1

**Comment by Wuziyi616** [comment]
Can you successfully compile mmdet3d along? I mean without any modifications? If you can, then you can directly import voxelization models from `mmdet3d`. Putting them apart from the entire codebase and compile them individually may cause some unexpected errors I guess.

**Comment by qfwysw** [comment]
I have tried to do this. However, it doesn't work. I can compile it in other enviroment, such as cuda 11.2.

**Comment by Wuziyi616** [comment]
You successfully compile what in cuda 11.2? MMDet3D or individual voxelization modules?

**Comment by qfwysw** [comment]
I can compile MMDet3D and individual voxelization modules in cuda 11.2.

**Comment by Wuziyi616** [comment]
I see. So maybe something is wrong with your cuda 10.1 config? e.g. pytorch or gcc

**Comment by qfwysw** [comment]
Yeah, I use the torch 1.7.1 before, but I even can't pip install mmcv. I find that someone use the torch 1.6.1 to install the mmdect. I use it but can't still compile the mmdect3d.  The version of my gcc is 7.5.0.

**Comment by Wuziyi616** [comment]
Maybe you should try torch 1.5.0? That's the version I am using.

**Comment by qfwysw** [comment]
Thanks for your suggestion, let me try it.

**Comment by qfwysw** [comment]
I'm sorry for my slow response. I install the torch 1.5.0 but I sitll can't compile the mmdect3d. The error is below.

ERROR: Command errored out with exit status 1: /home/fqu/.conda/envs/mmlab/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/fqu/program/mmlab/mmdetection3d-master/setup.py'"'"'; __file__='"'"'/home/fqu/program/mmlab/mmdetection3d-master/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by Wuziyi616** [comment]
Do you have multiple version CUDA installed in your server? What's your output of `nvcc --version`? It's really strange that cuda 11.2 can work but 10.1 fail.

**Comment by qfwysw** [comment]
Yeah, there are two versions of cuda in my computer. However, the version of nvcc is same as the cuda I used.

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105

**Comment by Wuziyi616** [comment]
Then keep using cuda 11.2? There could be some unexpected bugs when having two cuda installed in one server.

**Comment by qfwysw** [comment]
No, there are cuda8 and cuda10.1 on my one computer. The cuda11.3 has installed in another computer.

**Comment by Wuziyi616** [comment]
What if you uninstall cuda 8 and have try again? If uninstalling it doesn't affect other users or other applications?

**Comment by ZwwWayne** [comment]
It seems that the GCC version is too high. GCC 7.5 can only work with CUDA 11.0+.
You may try to downgrade GCC to use 5.4, it should work with CUDA 10.1.
