### ISSUE TITLE
RuntimeError:mmdet3d/ops/spconv/src/indice_cuda.cu 124

### ISSUE THREAD

**Issue by WWW2323** [open-mmlab/mmdetection3d#80]
hello，when i train pointpollar，everything is ok 
however，when i train the models with spconv，such as second,mvxnet,parta2，i get an error：
  ......
  File "/work/mmdet3d/ops/spconv/modules.py", line 130, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/work/mmdet3d/ops/spconv/conv.py", line 168, in forward
    grid=input.grid)
  File "/work/mmdet3d/ops/spconv/ops.py", line 94, in get_indice_pairs
    int(transpose))
RuntimeError: mmdet3d/ops/spconv/src/indice_cuda.cu 124
cuda execution failed with error 2

could  you help me with this problem？thanks very much！！！

**Environment**
Ubuntu16.04、TITAN V 、driver 418.56、cuda 10.1、cudnn 7
python 3.6、torch 1.4.0、torchvision 0.5.0、mmcv-full 1.0.5

**Comment by Tai-Wang** [comment]
It seems to be an out-of-memory runtime error. You can refer to #21 and #37 for possible solutions.

Please follow the template for "error report" to redescribe your issue if necessary.
