### ISSUE TITLE
How to use resnet-101 for Faster R-CNN on PASCAL VOC?

### ISSUE THREAD

**Issue by Balazizo** [open-mmlab/mmdetection3d#800]
Hello, I've downloaded a faster r-cnn resnet-101 backbone for PASCAL VOC from https://modelzoo.co/model/faster-rcnnpytorch. I've tried using it as a checkpoint and modifying the pre-trained and backbone depth arguments. I've gotten APs of 0 only, though. Is there any way I can use resnet-101 as a backbone for Faster R-CNN when testing on PASCAL VOC?

**Comment by Wuziyi616** [comment]
We don't support PASCAL VOC dataset. Maybe you should go to the MMDetection's repo and raise this issue? This is MMDetection3D which deals with point cloud data.

**Comment by Balazizo** [comment]
Oh deeply sorry, I didn't realize this was mmdetection3D. Thank you for your response.
