### ISSUE TITLE
pretrained_model : do you have the MVXFasterRCNN pretrained_model with hv config?

### ISSUE THREAD

**Issue by liyang0522** [open-mmlab/mmdetection3d#81]
Hi, you have provided dv_mvx-fpn_second_secfpn_adamw_2x8_80e_kitti-3d-3class_20200621_003904-10140f2d.pth , but do you have the prertrained_model  : MVXFasterRCNN with hard voxel? Could you please provide a copy?

**Comment by ZwwWayne** [comment]
We currently do not provide that config. We may support this in the future.

**Comment by liyang0522** [comment]
Does it mean that all the voxelization methond is dynamic voxelization even if the config is hv? Or you have both the hv and dv ,but you dont train the MVXNet with hv config. If i change the config from dv to hv and train it on my machine ,can i get the MVXNet with hv config? I just want to save the trainging time so i asked if you have the pretrainedmodel with hv config.
