### ISSUE TITLE
Test pointpillars model on different -number of layers and points per second-  lidar data from it's training data 

### ISSUE THREAD

**Issue by mohamed11981198** [open-mmlab/mmdetection3d#811]
What kind of preprocessing i need to do in point cloud  to get good detection results when i test pointpillars pretrained on lyft dataset on velodyne vlp 32 c lidar data ,
The inference code is working but the model detect many false positive objects 
Thank,

**Comment by xiliu8006** [comment]
You may need to confirm whether  your own data's coordinate system is the same as the pre-trained model's coordinate system. And we recommend that you use your own data to train an new model, more details you can refer to [this](https://mmdetection3d.readthedocs.io/en/latest/tutorials/customize_dataset.html)

**Comment by Tai-Wang** [comment]
Close due to inactivity.
