### ISSUE TITLE
Cannot debug on Pycharm

### ISSUE THREAD

**Issue by daxiongpro** [open-mmlab/mmdetection3d#816]
Hello，when I was running code about 3DSSD, I made a breakpoint in the "train.py", but the code cannot stop on the breakpoint ,and it still running, even if I make a breakpoint in `main().`  Do you know how to solve it?

**Comment by Wuziyi616** [comment]
Maybe you can use `pdb` to debug? Just `import pdb` on top of the file and then write `pdb.set_trace()` in the line that you want to set a breakpoint.
