### ISSUE TITLE
3D Object detection on S3DIS

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#817]
For now only semantic segmentation in supported on S3DIS. However there are some works applying object detection on it, e.g. https://arxiv.org/abs/2006.12356 . Is somebody working on adding bbox preprocessing for this task to this codebase? Can try to do it myself.

**Comment by Tai-Wang** [comment]
Sure, that's definitely a great contribution to the community. We do not have someone working on that, so just feel free to add new features on that. Our team will support you if there is any help needed.
