### ISSUE TITLE
Questions regarding MVX-Net for Waymo

### ISSUE THREAD

**Issue by ArthDh** [open-mmlab/mmdetection3d#823]
Hello! Thank you so much for the great repository!

I had a few questions regarding setting up Waymo for MVX-Net.

- The config file provided here [link](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/pointpillars/hv_pointpillars_secfpn_sbn_2x16_2x_waymoD5-3d-3class.py) uses MVX-Net for Waymo however as far as I understand the image data is not being used, so fusion is not being considered, is this correct or am I missing something?
- If I do intend to use MVX-Net architecture, it seems that I would need a pretrained 2d backbone network so as to extract features. I understand that mmdet provides backbones but I might have to train one from scratch as they do not have an architecture trained on Waymo, what would be the best practices to incorporate the two code bases or should I just train the model using mmdet and include the weights here or can I just write a 2D Dataset class in mmdetection3d itself? Any advice on this topic would be great!

Thank you,
Arth

**Comment by ZwwWayne** [comment]
1. Yes
2. You could refer to the configs in [nuImages dataset](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/nuimages) and take it as an example. You can just write a 2D dataset in MMDetection3D  so that you do not need to do it in multiple codebases.

**Comment by ArthDh** [comment]
Looks good, I'll try it out!
