### ISSUE TITLE
Learning rate seeting issues

### ISSUE THREAD

**Issue by ArrogantNobody** [open-mmlab/mmdetection3d#830]
Hi all, I notice that the learning rate should be changed regarding the gpu environment, but I could not found the learning rate setting in the config files, could anyone help me? 
Thanks a lot.

**Comment by Tai-Wang** [comment]
If the model config does not set the learning rate, it will adopt its inherited schedule config. For example, if the `schedule_2x.py` is involved in the `__base__`, it will use the learning rate set as [here](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/schedules/schedule_2x.py#L3).
