### ISSUE TITLE
About kitti_eval <gt vs gt> `ap_bev` and `ap_3d` not equal to 100%

### ISSUE THREAD

**Issue by lyuwenyu** [open-mmlab/mmdetection3d#838]
https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/evaluation/kitti_utils/eval.py#L643

Hi,

I have a question here.  I load kitti gt anno in val.txt, and `kitti_eval`  get the results below.  I only change `dimensions` from `hwl` to `lhw`, others keep origin in annos. Why `ap_bev` and `ap_3d` not is 100% here?

```
kitti_eval(gt_annos, gt_annos, 0)
```
---
```
Car AP@0.70, 0.70, 0.70:
bbox AP:100.0000, 100.0000, 100.0000
bev  AP:0.1339, 0.1967, 0.2594
3d   AP:0.1339, 0.1967, 0.2594
aos  AP:100.00, 100.00, 100.00
Car AP@0.70, 0.50, 0.50:
bbox AP:100.0000, 100.0000, 100.0000
bev  AP:0.1339, 0.1967, 0.2594
3d   AP:0.1339, 0.1967, 0.2594
aos  AP:100.00, 100.00, 100.00
```

**Comment by Tai-Wang** [comment]
You can try to add a small noise to the center location or the size. There will be some tricky problems when two 3D bounding boxes are exactly overlapped.

**Comment by lyuwenyu** [comment]
> You can try to add a small noise to the center location or the size. There will be some tricky problems when two 3D bounding boxes are exactly overlapped.

Done it.  It can get correct result by adding noise. So weird😳

Thanks.

**Comment by Tai-Wang** [comment]
That's mainly because the way to compute 3D IoU can't well handle those corner cases. Glad to hear the solution helps.
