### ISSUE TITLE
Training FCOS3D on custom dataset

### ISSUE THREAD

**Issue by bertoni9** [open-mmlab/mmdetection3d#841]
Hello, 
Thanks for the great work!

Do you provide any instruction on how to train on a custom dataset the monocular FCOS3D? I guess converting the new dataset into nuScenes format would be the easiest way.  Is there any tutorial? Or can you point me out the expected format of the data for monocular 3D detection?

Many thanks,
Lorenzo

**Comment by Tai-Wang** [comment]
To train on a custom dataset, you only need to prepare the data info in the coco style. That is a little different from the LiDAR-based methods because I guess it would be much easier to directly implement a coco-style converter than organizing your raw data like nuScenes. As for the specific json format, you can refer to our [nuScenes tutorial](https://mmdetection3d.readthedocs.io/en/latest/datasets/nuscenes_det.html) for detailed explanation.

**Comment by bertoni9** [comment]
Thank you for the quick reply! 
Can you please point me to the KITTI-nuScenes conversion API you are mentioning? 
Also in the nuScenes tutorial the `nuscenes_infos_train_mono3d.coco.json` has quite a lot of fields. Are they all necessary to train monocular 3D object detection? For example do I need velocities of the 3D bounding boxes? Or do I need rotation and translations if I already have annotations in camera coordinates?
Thanks

**Comment by Tai-Wang** [comment]
As presented in the nuScenes doc, the core function to organize KITTI/nuScenes info in the coco style is `get_2d_boxes`. You just need to reimplement the function and related others (such as `export_2d_annotations`) for your custom dataset.

For the unnecessary keys, just feel free to change their names or contents in the info and accordingly adjust the way to read the data in the dataset APIs like [this](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/datasets/nuscenes_mono_dataset.py).

**Comment by bertoni9** [comment]
Perfect, I will give it a try, thanks again!

**Comment by Legend94rz** [comment]
> To train on a custom dataset, you only need to prepare the data info in the coco style. That is a little different from the LiDAR-based methods because I guess it would be much easier to directly implement a coco-style converter than organizing your raw data like nuScenes. As for the specific json format, you can refer to our [nuScenes tutorial](https://mmdetection3d.readthedocs.io/en/latest/datasets/nuscenes_det.html) for the detailed explanation. Actually, you can first study how we implement monocular dataset APIs for KITTI.

the tutorial link you mentioned is 404. would you give me the new link?
btw, how to generate `nuscenes_infos_train_mono3d.coco.json` for nuscenes dataset?
