### ISSUE TITLE
visualize results without display open3d viewer

### ISSUE THREAD

**Issue by ktro2828** [open-mmlab/mmdetection3d#844]
**Describe the feature**
do you support visualize results without display open3d window and capture window as image? or any plan to support it?

**Motivation**
I want get visualize results faster as image

**Comment by Wuziyi616** [comment]
Yes. I think if you don't set the `--show` flag, then we won't display the open3d window. Only the screenshot will be saved in silent mode?

**Comment by fcakyon** [comment]
> Yes. I think if you don't set the `--show` flag, then we won't display the open3d window. Only the screenshot will be saved in silent mode?

When `show` argument isFalse, then no screenshot is saved, only obj files are saved. Is it possible to save the screenshot in silent mode?

**Comment by Yolan1013** [comment]
> > Yes. I think if you don't set the `--show` flag, then we won't display the open3d window. Only the screenshot will be saved in silent mode?
> 
> When `show` argument is False, then no screenshot is saved, only obj files are saved. Is it possible to save the screenshot in silent mode?

Have you resolved it? I meet the same problem.

**Comment by fcakyon** [comment]
@Yolan1013 @Wuziyi616 no, it is not resolved yet.
