### ISSUE TITLE
Error trying to use a two-stage image branch

### ISSUE THREAD

**Issue by AfonsoSalgadoSousa** [open-mmlab/mmdetection3d#845]
Hi. I am trying to build a late fusion model. My detector is heavily based on the MVX-Net. Here is [my config](https://github.com/open-mmlab/mmdetection3d/files/6945155/my_config.txt). I am getting the following error:

> File "/home/afonso/projects/adversarial_fusion/mmdetection3d/mmdet3d/models/detectors/late_fusion.py", line 358, in forward_img_train
>     proposal_cfg=proposal_cfg)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train
>     losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/dense_heads/rpn_head.py", line 78, in loss
> ...
> File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/misc.py", line 28, in multi_apply
>     map_results = map(pfunc, *args)
> TypeError: 'NoneType' object is not iterable

The problem seems to be with the RPNHead. My forward_img_train is based on Faster R-CNN.

```
def forward_img_train(self,
                          x,
                          img_metas,
                          gt_bboxes,
                          gt_labels,
                          gt_bboxes_ignore=None,
                          proposals=None,
                          **kwargs):
        """Forward function for image branch.

        Args:
            x (list[torch.Tensor]): Image features of shape (B, C, H, W)
                of multiple levels.
            img_metas (list[dict]): Meta information of images.
            gt_bboxes (list[torch.Tensor]): Ground truth boxes of each image
                sample.
            gt_labels (list[torch.Tensor]): Ground truth labels of boxes.
            gt_bboxes_ignore (list[torch.Tensor], optional): Ground truth
                boxes to be ignored. Defaults to None.
            proposals (list[torch.Tensor], optional): Proposals of each sample.
                Defaults to None.

        Returns:
            dict: Losses of each branch.
        """
        losses = dict()
        # RPN forward and loss
        if self.with_img_rpn:
            proposal_cfg = self.train_cfg.get('img_rpn_proposal',
                                              self.test_cfg.img_rpn)
            rpn_losses, proposal_list = self.img_rpn_head.forward_train(
                x,
                img_metas,
                gt_bboxes,
                gt_labels=None,
                gt_bboxes_ignore=gt_bboxes_ignore,
                proposal_cfg=proposal_cfg)
            losses.update(rpn_losses)
        else:
            proposal_list = proposals

        # bbox head forward and loss
        roi_losses = self.img_roi_head.forward_train(
            x, img_metas, proposal_list, gt_bboxes, gt_labels,
            gt_bboxes_ignore, **kwargs)
        losses.update(roi_losses)

        return losses
```
I do not quite understand the issue. Do you have any insights on the problem?

**Comment by Wuziyi616** [comment]
Maybe you should put the entire error message and your config file for our reference. I think your posted message
```
File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/dense_heads/rpn_head.py", line 78, in loss

...  # **there is something missed here?**

File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/misc.py", line 28, in multi_apply
map_results = map(pfunc, *args)
```

**Comment by Wuziyi616** [comment]
Close due to inactive

**Comment by AfonsoSalgadoSousa** [comment]
Hi. My config file is uploaded in my previous comment. The full error message is as follows:

> Traceback (most recent call last):
>   File "tools/train.py", line 222, in <module>
>     main()
>   File "tools/train.py", line 218, in main
>     meta=meta)
>   File "/home/afonso/projects/adversarial_fusion/mmdetection3d/mmdet3d/apis/train.py", line 34, in train_model
>     meta=meta)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
>     runner.run(data_loaders, cfg.workflow)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
>     self.run_iter(data_batch, train_mode=True, **kwargs)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
>     **kwargs)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
>     return self.module.train_step(*inputs[0], **kwargs[0])
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
>     losses = self(**data)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/afonso/projects/adversarial_fusion/mmdetection3d/mmdet3d/models/detectors/base.py", line 58, in forward
>     return self.forward_train(**kwargs)
>   File "/home/afonso/projects/adversarial_fusion/mmdetection3d/mmdet3d/models/detectors/late_fusion.py", line 290, in forward_train
>     proposals=proposals)
>   File "/home/afonso/projects/adversarial_fusion/mmdetection3d/mmdet3d/models/detectors/late_fusion.py", line 393, in forward_img_train
>     proposal_cfg=proposal_cfg)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/dense_heads/base_dense_head.py", line 54, in forward_train
>     losses = self.loss(*loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/dense_heads/rpn_head.py", line 78, in loss
>     gt_bboxes_ignore=gt_bboxes_ignore)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 164, in new_func
>     return old_func(*args, **kwargs)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/dense_heads/anchor_head.py", line 466, in loss
>     label_channels=label_channels)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/models/dense_heads/anchor_head.py", line 348, in get_targets
>     unmap_outputs=unmap_outputs)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/core/utils/misc.py", line 28, in multi_apply
>     map_results = map(pfunc, *args)
> TypeError: 'NoneType' object is not iterable

**Comment by Wuziyi616** [comment]
Sorry I miss your reply. I think you may need to add `pdb.set_trace()` there to see which input variable is None, so that we can find out where the question is.

**Comment by AfonsoSalgadoSousa** [comment]
Hi there. I found out that I was missing the 'gt_bboxes'. After adding them to the Collect3D in the config file, I am now incurring in the following error:

> Traceback (most recent call last):
>   File "tools/train.py", line 222, in <module>
>     main()
>   File "tools/train.py", line 218, in main
>     meta=meta)
>   File "/home/afonso/projects/adversarial_fusion/mmdetection3d/mmdet3d/apis/train.py", line 34, in train_model
>     meta=meta)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/apis/train.py", line 170, in train_detector
>     runner.run(data_loaders, cfg.workflow)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
>     epoch_runner(data_loaders[i], **kwargs)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
>     for i, data_batch in enumerate(self.data_loader):
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
>     data = self._next_data()
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
>     return self._process_data(data)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
>     data.reraise()
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
>     raise self.exc_type(msg)
> KeyError: Caught KeyError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/dataset_wrappers.py", line 151, in __getitem__
>     return self.dataset[idx % self._ori_len]
>   File "/home/afonso/projects/adversarial_fusion/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 356, in __getitem__
>     data = self.prepare_train_data(idx)
>   File "/home/afonso/projects/adversarial_fusion/mmdetection3d/mmdet3d/datasets/custom_3d.py", line 153, in prepare_train_data
>     example = self.pipeline(input_dict)
>   File "/home/afonso/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 40, in __call__
>     data = t(data)
>   File "/home/afonso/projects/adversarial_fusion/mmdetection3d/mmdet3d/datasets/pipelines/formating.py", line 167, in __call__
>     data[key] = results[key]
> KeyError: 'gt_bboxes'

**Comment by Wuziyi616** [comment]
Hi, this is because you don't load the 2D GT bboxes. You can refer to [this transform](https://github.com/open-mmlab/mmdetection3d/blob/057ad6ec50fcf43532f1ed5bdc1655cd5c6eccd2/configs/imvotenet/imvotenet_stage2_16x8_sunrgbd-3d-10class.py#L175) for how to load 2D GT.

**Comment by AfonsoSalgadoSousa** [comment]
Hi. Yes, that was precisely it. Thank you.
