### ISSUE TITLE
How to speed up points_ to_ img

### ISSUE THREAD

**Issue by qfwysw** [open-mmlab/mmdetection3d#846]
Thanks for your great work. The thing is that I'm interested in polintpillar, then I want to compile the voxelization Individually.  But I find that the time of that the code processes the data is long(below). So what can I do to speed the code? I have put the function and the data on the GPU.
![image](https://user-images.githubusercontent.com/53482524/128583763-ce8c3a17-6942-4e78-b9e5-a3f40e34a323.png)
![image](https://user-images.githubusercontent.com/53482524/128583886-f2abc356-a6eb-4340-adff-372689e1dce8.png)
![image](https://user-images.githubusercontent.com/53482524/128583906-38cca0e9-cc49-4120-a2a5-2a77046c991d.png)

**Comment by Wuziyi616** [comment]
It is indeed very slow, becasue you can see [here](https://github.com/open-mmlab/mmdetection3d/blob/9f0b01caf6aefed861ef4c3eb197c09362d26b32/mmdet3d/models/middle_encoders/pillar_scatter.py#L72) we iterate over each example in a batch. Not sure if the code can be converted to batch processing. Maybe you can try!

**Comment by qfwysw** [comment]
Thanks for your suggestions. I will try it at once.

**Comment by qfwysw** [comment]
Maybe there's something wrong with my description. The time of points2img is long. But I think I have no ability to optimize the voxelization. So let me see your suggestion.
![image](https://user-images.githubusercontent.com/53482524/128592398-cf79ec11-2d1a-4150-a83f-49002f0634f1.png)

**Comment by Wuziyi616** [comment]
Ahh, can you kindly point out which line of code is responsible for `points_to_img`? I support it's `feature2img` by `PointPillarsScatter` but obliviously you don't mean that.

**Comment by qfwysw** [comment]
At first we input the points to the voxelization to convert the points to the pillars. Then we use the pillarencoder to semantization the pillars. Finally we scatter the feature to the canvas. The meaning of points_to_img contains the above three steps
![image](https://user-images.githubusercontent.com/53482524/128593370-1da18d4b-d7cd-4e10-8921-09174921de00.png)

**Comment by Wuziyi616** [comment]
Maybe this is necessary time spend. If you want to speed up you should re-write the cuda operations, which is difficult.
