### ISSUE TITLE
 Is there a way to save the result without opening a window during visualization?

### ISSUE THREAD

**Issue by 2gunsu** [open-mmlab/mmdetection3d#851]
Thank you so much for sharing a great project.
When running test.py, ```--show``` and ```--show-dir``` are passed as arguments. 
In this case, the screen is displayed and saved one by one. 
Is there a way to save without opening the window?

Thank you.

**Comment by Wuziyi616** [comment]
Maybe you need to modify the code. For example, if you are testing ScanNet, you need to modify [this line](https://github.com/open-mmlab/mmdetection3d/blob/9783cda80aee2e8599d3a8e1acb423cafca0faa9/mmdet3d/datasets/scannet_dataset.py#L247) to
`show_result(points, gt_bboxes, pred_bboxes, out_dir, file_name, show=False)`
So that we won't display the window

**Comment by 2gunsu** [comment]
Thank you so much for your kind and quick reply!

**Comment by daxiongpro** [comment]
> Maybe you need to modify the code. For example, if you are testing ScanNet, you need to modify [this line](https://github.com/open-mmlab/mmdetection3d/blob/9783cda80aee2e8599d3a8e1acb423cafca0faa9/mmdet3d/datasets/scannet_dataset.py#L247) to
> `show_result(points, gt_bboxes, pred_bboxes, out_dir, file_name, show=False)`
> So that we won't display the window

I changed the code of `kitti_dataset.py`, but should I not pass `--show` and `--show_dir` when I test the model?

**Comment by daxiongpro** [comment]
I have changed the code `show=False`, but if I pass the `--show` arguments, it will still displayed one by one. If I don't pass the `--show` arguments, the `xx.obj` file will not be saved in show_dir. How to solve it ?

**Comment by Wuziyi616** [comment]
Hi, your mentioned lines are different from the original problem in this issue. I think a workaround is to comment the show code block [here](https://github.com/open-mmlab/mmdetection3d/blob/055fd973d333420ea406c7c759abbc4f8833c1e3/mmdet3d/core/visualizer/show_result.py#L95-L105)

**Comment by daxiongpro** [comment]
> Hi, your mentioned lines are different from the original problem in this issue. I think a workaround is to comment the show code block [here](https://github.com/open-mmlab/mmdetection3d/blob/055fd973d333420ea406c7c759abbc4f8833c1e3/mmdet3d/core/visualizer/show_result.py#L95-L105)

Oh that it works! 
Thank you so much for your quick reply!
Wish you have a good experience in a new job!
