### ISSUE TITLE
KeyError: 'cam_intrinsic' trying to use FCOS3D with KITTI

### ISSUE THREAD

**Issue by AfonsoSalgadoSousa** [open-mmlab/mmdetection3d#857]
Hi. I am trying to produce 3D bounding boxes from the KITTI images. For that, I am trying to use the FCOS3D model. As far as I understand, FCOS3D requires the additional 'cam_intrinsic' attribute, and that's why there is the additional LoadImageFromFileMono3D class. Yet, I am getting KeyError: 'cam_intrinsic'. The results['img_info'] dictionary only contains the 'filename' key. Do you have any insights on this error? Appreciate any help you can provide.

**Comment by AfonsoSalgadoSousa** [comment]
My dataset settings are as follows:
```
dataset_type = 'KittiDataset'
data_root = 'data/kitti/'
class_names = ['Pedestrian', 'Cyclist', 'Car']
img_norm_cfg = dict(
    mean=[103.530, 116.280, 123.675], std=[1.0, 1.0, 1.0], to_rgb=False)
input_modality = dict(use_lidar=True, use_camera=True)
train_pipeline = [
    dict(type='LoadPointsFromFile', coord_type='LIDAR', load_dim=4, use_dim=4),
    dict(type='LoadImageFromFileMono3D'),

    dict(
        type='LoadAnnotations3D',
        with_bbox=True,
        with_label=True,
        with_attr_label=True,
        with_bbox_3d=True,
        with_label_3d=True,
        with_bbox_depth=True),
    dict(type='Resize', img_scale=(1600, 900), keep_ratio=True),
    dict(type='RandomFlip3D', flip_ratio_bev_horizontal=0.5),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(
        type='GlobalRotScaleTrans',
        rot_range=[-0.78539816, 0.78539816],
        scale_ratio_range=[0.95, 1.05],
        translation_std=[0.2, 0.2, 0.2]),
    dict(type='PointsRangeFilter', point_cloud_range=point_cloud_range),
    dict(type='ObjectRangeFilter', point_cloud_range=point_cloud_range),
    dict(type='PointShuffle'),
    dict(type='DefaultFormatBundle3D', class_names=class_names),
    dict(
        type='Collect3D',
        keys=['points', 'img', 'gt_bboxes', 'gt_labels', 'attr_labels', 'gt_bboxes_3d',
            'gt_labels_3d', 'centers2d', 'depths']),
]
test_pipeline = [
    dict(type='LoadPointsFromFile', coord_type='LIDAR', load_dim=4, use_dim=4),
    dict(type='LoadImageFromFileMono3D'),
    dict(
        type='MultiScaleFlipAug3D',
        img_scale=(1280, 384),
        pts_scale_ratio=1,
        flip=False,
        transforms=[
            dict(type='Resize', multiscale_mode='value', keep_ratio=True),
            dict(
                type='GlobalRotScaleTrans',
                rot_range=[0, 0],
                scale_ratio_range=[1., 1.],
                translation_std=[0, 0, 0]),
            dict(type='RandomFlip3D'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(
                type='PointsRangeFilter', point_cloud_range=point_cloud_range),
            dict(
                type='DefaultFormatBundle3D',
                class_names=class_names,
                with_label=False),
            dict(type='Collect3D', keys=['points', 'img'])
        ])
]
# construct a pipeline for data and gt loading in show function
# please keep its loading function consistent with test_pipeline (e.g. client)
eval_pipeline = [
    dict(type='LoadPointsFromFile', coord_type='LIDAR', load_dim=4, use_dim=4),
    dict(type='LoadImageFromFileMono3D'),
    dict(
        type='DefaultFormatBundle3D',
        class_names=class_names,
        with_label=False),
    dict(type='Collect3D', keys=['points', 'img'])
]
```

**Comment by Wuziyi616** [comment]
Maybe you need to pull the newest master branch and have a try. The camera keys are refactored in this PR #805

**Comment by AfonsoSalgadoSousa** [comment]
Hi. The problem still persists. I checked the source code and even though `cam2img` is the new naming convention (in datasets/pipeline/loading.py it is now `results['cam2img'] = results['img_info']['cam_intrinsic']`), the `cam_intrinsic` key in `results['img_info']` does not exist. The `results` dictionary just contains the key `filename`. I am using the standard KITTI dataset.

**Comment by THU17cyz** [comment]
Please try using KittiMonoDataset

**Comment by Wuziyi616** [comment]
Yes @THU17cyz is correct. I think @Tai-Wang has done some work in MonoKITTI data, can you have a look here @Tai-Wang?

**Comment by AfonsoSalgadoSousa** [comment]
Thanks for the reply. It might be it. I am now struggling to find the right config format for this MonoKITTI dataset. My final intent was to fuse the 3D bounding boxes from FCOS3D and a point cloud-based 3D detector, so I require both LiDAR and camera data.
What exactly is the difference between the standard version and the mono 3D one?
Thank you so much for your attention and participation.

**Comment by Tai-Wang** [comment]
@AfonsoSalgadoSousa The data for monocular 3D detection is organized in the coco-style JSON file. For compatibility, we design a specific dataset class `KittiMonoDataset` for this format. So you have to use that class.

In addition, there are a lot of parameters that required tuning when applying FCOS3D on the KITTI. We are planning to support that in the near future (maybe in a month). So I guess you'd better wait for a while because there is quite a lot of work to do.

**Comment by AfonsoSalgadoSousa** [comment]
Thank you very much for the reply.

**Comment by FlyingAnt2018** [comment]
> KittiMonoDataset

Hi, i want to use kitti format waymo dataset to train FCOS3D model, and i have met the same problem. Should i convert the kitti format waymo dataset to fit class KittiMonoDataset to read data? I am using the master branch and met many more obstacle, such as I fail to train fcos3d model using the most recent master branch's dataset convert tool.
