### ISSUE TITLE
False evaluation results on customized kitti-format dataset.

### ISSUE THREAD

**Issue by Yaziwel** [open-mmlab/mmdetection3d#862]
Hello, I made a customized dataset with 50+ point cloud files and converted it to kitti format. However, the training results of pointpillars on it are weird.

![捕获](https://user-images.githubusercontent.com/38243190/129005030-8049f6bf-db03-464c-a798-b711cb7f2cc7.JPG)
 As is shown above, both bbox and aos are 0 accuracy, which is pretty strange. I visualized the results of several samples and found out that the predicting results are roughly acceptable so that neither 2D  nor direction evaluation result should be 0 accuracy.

Does any one know how to solve this problem? Thanks!

**Comment by Tai-Wang** [comment]
I think there are some problems with the consistency of your output and the expected input format of evaluation. Nevertheless, your provided information is far not enough for me to offer any more suggestions.

**Comment by Monday666** [comment]
> 

hello I meet same problem when I train myself dataset.Have you solved this problem？
