### ISSUE TITLE
fcos3d visualization

### ISSUE THREAD

**Issue by tonyyang1995** [open-mmlab/mmdetection3d#866]
Hello, recently I am inference with fcos3d in nuscenes dataset. I am using tools/test.py and tried the images similar to Fig5. in the paper. The visualize result is like the following:
![test_02130_pred](https://user-images.githubusercontent.com/44078072/129276622-784b9c04-ed30-40f6-b595-454aba8efcc8.png)
But when I look into it carefully, I found that the yaw of front-left camera were not correct, but in the paper:
![image](https://user-images.githubusercontent.com/44078072/129276729-f9037f75-e6f9-4c1e-9bfd-517faf4fd687.png)
The yaw was very good.
I am using fcos-finetune model, and the score thres=0.2. To correct the yaw problem, I used the mono_cam_box2vis function before draw pred bbox in the show_results function in model.detectors.single_stage_mono3d.py.

**Comment by Tai-Wang** [comment]
Do you use the latest master and corresponding checkpoints? We have just refactored the hack codes about yaw and dimension recently. Please refer to the [compatibility documentation](https://mmdetection3d.readthedocs.io/en/latest/compatibility.html).

**Comment by tonyyang1995** [comment]
Thanks for the quick reply. 
I am using the latest master (using git clone https://github.com/open-mmlab/mmdetection3d.git), mmdet==2.14.0, mmseg==0.14.1, mmcv-full==1.3.8.
The checkpoint is "fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210717_095645-8d806dc2.pth". 
The input image was "fcos3d_r101_caffe_fpn_gn-head_dcn_2x8_1x_nus-mono3d_finetune_20210717_095645-8d806dc2.pth". 
I am using the demo/mono_det_demo.py and the only modification was adding a line in
" show_bboxes = mono_cam_box2vis(show_bboxes)" under mmdet.3d.api.inference.show_proj_det_result_meshlab(). It should be near line 432.

**Comment by Tai-Wang** [comment]
We have removed the hack used in the visualization of monocular 3D detection results. So you don't need to add that line.
