### ISSUE TITLE
How to use 'sample_2d' option in ObjectSample class

### ISSUE THREAD

**Issue by jhkim-spa** [open-mmlab/mmdetection3d#868]
I think it's not implemented yet, right?
Do you have any plane to implement it?

**Comment by YangHan-Morningstar** [comment]
> I think it's not implemented yet, right?
> Do you have any plane to implement it?

Hi, have you found it? I see in [https://github.com/open-mmlab/mmdetection3d/issues/36](url) they said they had supported it but I still can't find the code...

**Comment by Byte247** [comment]
you can find it here: https://github.com/open-mmlab/mmdetection3d/pull/327/files

**Comment by Byte247** [comment]
though you need to rerun your create data and set the "with_mask" flag
