### ISSUE TITLE
Train VoteNet on s3dis?

### ISSUE THREAD

**Issue by densechen** [open-mmlab/mmdetection3d#874]
VoteNet is becoming more and more popular than PointNet2, and s3dis is also a vital dataset widely used.

Will mmdetection3d make VoteNet train on s3dis?

**Comment by Wuziyi616** [comment]
The config should be very similar to the [config](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/votenet/votenet_8x8_scannet-3d-18class.py) of ScanNet-VoteNet we support. Try replace the `scannet-3d-18class` with `s3dis-3d-5class`. You also need to modify the `num_classes` [here](https://github.com/open-mmlab/mmdetection3d/blob/cab70db5c67178aa90c7bf3aaf1ef844fe39da32/configs/votenet/votenet_8x8_scannet-3d-18class.py#L9) and `mean_sizes` [here](https://github.com/open-mmlab/mmdetection3d/blob/cab70db5c67178aa90c7bf3aaf1ef844fe39da32/configs/votenet/votenet_8x8_scannet-3d-18class.py#L15).
