### ISSUE TITLE
Question about ImVoteNet config

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#876]
These 8 [lines](https://github.com/open-mmlab/mmdetection3d/blob/master/configs/imvotenet/imvotenet_stage2_16x8_sunrgbd-3d-10class.py#L177-L184) in config contains 2 calls of `Flip` and 1 call of `Pad`. First question is why do we need `RandomFlip` call as `RandomFlip3D` does the same thing after all?

Second question, is about the order of `Pad` and `RandomFlip3D`. If I understand `mmdetection` code correctly, we usually first flip the image and then pad it on the bottom and right edges. However here we first pad and then flip. Is it a bug, or it is somehow not important in case of `ImVoteNet`?

Probably, @THU17cyz can help.

**Comment by THU17cyz** [comment]
Hi @filaPro , thank you very much for pointing out this issue. This is indeed a bug. We should first flip and then pad. And the `RandomFlip` is also not necessary. We shall fix this, and your help is also very welcome.

**Comment by filaPro** [comment]
Can make a PR and also retrain the model on 8 GPUs to see if the fix influences something.

**Comment by ZwwWayne** [comment]
Closed as the discussion in https://github.com/open-mmlab/mmdetection3d/pull/877
