### ISSUE TITLE
FCOS 3D Training Time

### ISSUE THREAD

**Issue by tianweiy** [open-mmlab/mmdetection3d#878]
Hi mmlab team, 

I wonder what is the training time for FCOS 3D on nuScenes under your setting? Could you let me know the rough time and the GPU you use? Thank you!

**Comment by Tai-Wang** [comment]
Hi Tianwei,

The provided checkpoint for baseline is obtained with 8 Titan Xp/1080Ti in about one day. The setting and training time for fine-tuning is also similar. For the submission on the nuScenes leaderboard, we use double GPUs to train the models with double epochs. So the training time is also similar.

**Comment by tianweiy** [comment]
Sounds good, thank you.
