### ISSUE TITLE
About indoor visualization

### ISSUE THREAD

**Issue by filaPro** [open-mmlab/mmdetection3d#880]
ScanNet and Sun RGB-D datasets in default pipeline use `use_dim=[0, 1, 2]`. Such design choice ignores colors of points and result rather poor visualization e.g. in `browse_dataset.py`. Will it be better to set `use_dim=[0, 1, 2, 3, 4, 5]` as for `S3DISDataset`?

**Comment by filaPro** [comment]
Btw, is this [instruction](https://github.com/open-mmlab/mmdetection3d/blame/master/docs/useful_tools.md#L71) valid?

First, with `--eval-options 'show=True' 'out_dir=${SHOW_DIR}'` I get an error about unknown `''show'` parameter. It is probably better with `--eval-options show=True out_dir=${SHOW_DIR}`.

Second question is about `--eval-options show=False` in the next line of documentation. I'm getting no visualization in this case as `show` is now `False` for `dataset.evaluate` method. I'm trying on SUN RGB-D if it is important.

Am I missing something?

**Comment by THU17cyz** [comment]
I think Ziyi is the expert on this @Wuziyi616 . Perhaps he can take a look : )

**Comment by Wuziyi616** [comment]
> 
> 
> ScanNet and Sun RGB-D datasets in default pipeline use `use_dim=[0, 1, 2]`. Such design choice ignores colors of points and result rather poor visualization e.g. in `browse_dataset.py`. Will it be better to set `use_dim=[0, 1, 2, 3, 4, 5]` as for `S3DISDataset`?

I agree that using color results in better visualization quality. I quickly scan over VoteNet paper and there seems to be both colored and non-colored visualization examples. I think users can modify the code if they want to have RGB colors, though this is a bit inflexible.

**Comment by Wuziyi616** [comment]
> 
> 
> Btw, is this [instruction](https://github.com/open-mmlab/mmdetection3d/blame/master/docs/useful_tools.md#L71) valid?
> 
> First, with `--eval-options 'show=True' 'out_dir=${SHOW_DIR}'` I get an error about unknown `''show'` parameter. It is probably better with `--eval-options show=True out_dir=${SHOW_DIR}`.
> 
> Second question is about `--eval-options show=False` in the next line of documentation. I'm getting no visualization in this case as `show` is now `False` for `dataset.evaluate` method. I'm trying on SUN RGB-D if it is important.
> 
> Am I missing something?

1. Yes, I believe your `--eval-options show=True out_dir=${SHOW_DIR}` is correct
2. That's really a bug. We actually have two `show` here: whether to visualize result and whether to show it online. If we want to perform offline visualization, we may need to add an additional params (maybe something like `online=False`)

What do you think? Do you have any good idea?

**Comment by Tai-Wang** [comment]
Close due to inactivity. I think the second issue is solved by a recent PR #1073 .
