### ISSUE TITLE
if isinstance(result[0], tuple): KeyError: 0

### ISSUE THREAD

**Issue by AllenPeng0209** [open-mmlab/mmdetection3d#89]
![Screenshot from 2020-09-04 17-45-45](https://user-images.githubusercontent.com/26760786/92226181-eaec7b00-eed6-11ea-93ac-c474a4d5583e.png)
![Screenshot from 2020-09-04 17-45-26](https://user-images.githubusercontent.com/26760786/92226191-ede76b80-eed6-11ea-8da6-0b5cb596ea20.png)

seems like after updating mmdetection2.4 version , it trigger the bug above

**Comment by Tai-Wang** [comment]
Please follow the template for bug report to describe your issue.

BTW, what commands did you run and when did the error happen? It seems that the error happened when evaluating in the training procedure?

**Comment by filaPro** [comment]
Confirm. This commit in `mmdetection` master breaks `mmdetection3d` evaluation:

https://github.com/open-mmlab/mmdetection/commit/e5072a3f75be4bc02da21ac6401e4f97d462c205#diff-49021e47adb24af571f86ef0b131a7eeR95

**Comment by ZwwWayne** [comment]
Thanks for your bug report, this is caused by the batch inference API change in MMDetection V2.4.0. We will also migrate to batch inference ASAP.

**Comment by ChunmianLin** [comment]
the same error. The version of my MMDetection is 2.4.0.
