### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by a785448726** [open-mmlab/mmdetection3d#893]
/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/cnn/bricks/conv_module.py:108: UserWarning: ConvModule has norm and bias at the same time
  warnings.warn('ConvModule has norm and bias at the same time')
Use load_from_local loader
Bus error (core dumped)

my environment is:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
pytorch=1.7.0

How to solve this problem

**Comment by Tai-Wang** [comment]
Please provide more information following the issue template for implementation questions.
