### ISSUE TITLE
Convert Ouster OS2 (PCAP file) to inference on MMDetection3D

### ISSUE THREAD

**Issue by JorritWillaert** [open-mmlab/mmdetection3d#895]
Dear,

I’ve trained the model on the NuScenes data and it performs very well. However, now I would like to use this model for inference on our own LiDAR data. How could I convert data from an Ouster OS2 (PCAP file) to work on this model?

Thanks in advance!

**Comment by Tai-Wang** [comment]
I am not familiar with PCAP format but basically, you can just write a script to convert it into the general bin format, and then use our code to load it.

**Comment by ZCMax** [comment]
Hi, Maybe you can refer this: https://github.com/sshaoshuai/PointRCNN/issues/38
