### ISSUE TITLE
Is there a function that can visualize the BEV Box in XYWHR format?

### ISSUE THREAD

**Issue by 2gunsu** [open-mmlab/mmdetection3d#897]
Hello.
Thank you so much for sharing a great project.

I want to visualize the bounding boxes obtained in LiDAR format with BEV.
I succeeded in visualizing the bounding boxes with no rotation as below using [**nearest_bev**](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/bbox/structures/lidar_box3d.py#L96-L115), 
but I'm not sure how to visualize a [**bev with yaw**](https://github.com/open-mmlab/mmdetection3d/blob/master/mmdet3d/core/bbox/structures/lidar_box3d.py#L90-L94).

![Image_00028_R70m_9c0558316d134feb8835997f8df4444d](https://user-images.githubusercontent.com/59532188/131598474-5e88db86-4f94-4c29-88c2-282a4ad93165.jpg)

Is there any function in this project that can visualize the rotated box using the parameter R? 
If it doesn't exist, can you give me the idea of ​​using this yaw to rotate the coordinates of the box?
Thank you very much.

**Comment by Tai-Wang** [comment]
We support 3D-view visualization. Please refer to our [documentation](https://mmdetection3d.readthedocs.io/en/latest/useful_tools.html#visualization) for visualization tools. If you would like to get a relative "standard" bird-view visualized result, I recommend you can refer to this function in [nuScenes devkit](https://mmdetection3d.readthedocs.io/en/latest/useful_tools.html#visualization) for some inspiration.

**Comment by 2gunsu** [comment]
Thank you very much for the quick reply.

In your answer, the **'documentation'** link and the **'nuScenes devkit'** link appear to be the same. Could you give me a link again if this is wrong?

**Comment by Tai-Wang** [comment]
Sorry for my carelessness. Links updated.

**Comment by 2gunsu** [comment]
I really appreciate your kind help. Have a nice day!
