### ISSUE TITLE
ERROR: Cannot uninstall 'llvmlite'

### ISSUE THREAD

**Issue by MinghuiJ** [open-mmlab/mmdetection3d#9]
I follow the get_start.md, but when I run the last command `pip install -v -e .`, I got the following error. 
I have already run 
`git clone https://github.com/open-mmlab/mmdetection3d.git`
`cd mmdetection3d`
`pip install -r requirements/build.txt`

Error:
`ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

**Comment by ZwwWayne** [comment]
Hi @MinghuiJ ,
It seems that your environment has already installed a `llvmlite`? You may uninstall and install it manually.

**Comment by ZwwWayne** [comment]
The installation issue should be fixed in the newest version. Therefore, this issue is closed. Feel free to reopen it if you have any further questions.
