### ISSUE TITLE
How does a 3D detection box display in a 2D image？

### ISSUE THREAD

**Issue by hhcahut** [open-mmlab/mmdetection3d#90]
Hello, this code can visualize the 3D detection box in the point cloud, may I ask if the 3D detection box can be visualized in the 2D image?

**Comment by ZwwWayne** [comment]
Thanks for your suggestion, we plan to support it in mayby v0.7.0 or v0.8.0.

**Comment by ZwwWayne** [comment]
If you want to do it now, you need to use the transformations to project 3D boxes from LiDAR to image. This [repo](https://github.com/kuixu/kitti_object_vis) might do some help to you.

**Comment by selmadeac** [comment]
Hi! Is it possible now?
