### ISSUE TITLE
networkx>=2.5 support

### ISSUE THREAD

**Issue by iubica** [open-mmlab/mmdetection3d#911]
**Describe the feature**
Add networkx>=2.5 support to mmdetection3d

**Motivation**
mmdetection3d only supports networkx<2.3 (see https://github.com/open-mmlab/mmdetection3d/blob/master/requirements/runtime.txt). 

Would be nice to have networkx>=2.5 support. Otherwise, mmdetection3d can't be used with other modules that expect a newer networkx version.

**Comment by THU17cyz** [comment]
I tested with `networkx >= 2.5` and it works fine (at least for the models I tried). Perhaps you can just upgrade the version of `networkx`? We will test on this and update the requirements if appliable

**Comment by iubica** [comment]
Thank you.
