### ISSUE TITLE
When will the coordination system refactorization branch be merged?

### ISSUE THREAD

**Issue by zhanggefan** [open-mmlab/mmdetection3d#913]
The current yaw definition used by LidarInstance3DBoxes that takes -y as zero and positive rotation is clockwise,  is really anti-intuition...

**Comment by THU17cyz** [comment]
Hello @zhanggefan , the branch is almost ready but a few models have some problem (second & pointpillars & dynamic voxelization kitti-3d-car are around 1% lower than before), and we haven't tested on Waymo yet. You can now use the v1.0.0.dev branch to use the refactored coord sys. The coord_sys_refactor branch is a deprecated one. If you use the dev branch please update the data via #774 or regenerate the xxx_infos_xxx.pkl files.

**Comment by zhanggefan** [comment]
Thanks for your kind reply!! Sounds like that the branch will be ready by the next release, and I am looking forward to it!

**Comment by Tai-Wang** [comment]
To be more specific, next we plan to only add new features to the v1.0.0 dev (maybe rc afterwards) branches. In contrast, only bug fixes and minor enhancements will be merged into the master. In this way, we can guarantee our new models are ok in the refactored coordinate systems.

Considering we still have something to do to guarantee the v1.0.0 is stable enough, we will not replace the master with it very soon. So if you would like to use the more convenient coordinate settings and develop new features on top, I recommend you can switch to v1.0.0 from now. If you find any problems, issues and PRs are also welcome!
