### ISSUE TITLE
Link 404

### ISSUE THREAD

**Issue by LicharYuan** [open-mmlab/mmdetection3d#921]
Failed Link: https://mmdetection3d.readthedocs.io/en/latest/tutorials/waymo.html. 

Can you update the latest link? Thanks.

**Comment by ZCMax** [comment]
the Link has been modified to https://mmdetection3d.readthedocs.io/en/latest/datasets/waymo_det.html, we'll create a PR to fix the link error.

**Comment by ZCMax** [comment]
Hi! We've already fix the issue.

**Comment by LicharYuan** [comment]
Thanks!

**Comment by T-Ray35** [comment]
The link cannot be open

**Comment by T-Ray35** [comment]
> Hi! We've already fixed the issue.

This page cannot be open
