### ISSUE TITLE
mmdet3d install error

### ISSUE THREAD

**Issue by 184338740** [open-mmlab/mmdetection3d#925]
” mmdet3d/ops/spconv/include/spconv/spconv_ops.h:18:10: fatal error: cuda_runtime_api.h: No such file or directory
       18 | #include <cuda_runtime_api.h>“

Envs:
        mmcv, mmdet, mmseg installed sucessful.  cuda-11.1,python-3.7,pytorh-1.8.0 installed sucess, GPU is A100. 
"conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge"

libs: 
    exists in '/usr/local/cuda-11.1/targets/x86_64-linux/include/cuda_runtime_api.h'

How can i to gcc link cuda_runtime_api.h in conda?

**Comment by Divadi** [comment]
What is shown when you do nvcc --version?
I had this issue because although nvidia-smi showed CUDA version 11.2, nvcc compiler was 10.1, so I had to install cudatoolkit 10.1, not 11.x

**Comment by Tai-Wang** [comment]
Close due to inactivity.
