### ISSUE TITLE
Format of bounding boxes in different dataset.

### ISSUE THREAD

**Issue by Abyssaledge** [open-mmlab/mmdetection3d#932]
I am going to transfer some two-stage methods in KITTI to Waymo. In the stage of RCNN, we are likely to deal with the problem of converting the format of boxes. 
My main concern is that whether the ROIHead of some methods implemented in KITTI (e.g., PartA2) can be transferred to Waymo directly.
Since mmdet3d converts the Waymo dataset to KITTI format at first, I tend to believe we do not need to care about box format in such transfer. To be cautious, I hope I can got a confirmation from the developers.

**Comment by THU17cyz** [comment]
Yes, I think you need not woory about the box format in a KITTI-Waymo conversion.
