### ISSUE TITLE
How to access lidar for real-time detection

### ISSUE THREAD

**Issue by Zanderzt** [open-mmlab/mmdetection3d#933]
First of all, thanks to Open-mmlab for the great sharing, great integration code.
In the introduction of the Readme, I only saw the forward reasoning of the .bin file.
E.g:
```
point_cloud ='./demo/data/kitti/kitti_000008.bin'
result, data = inference_detector(model, point_cloud)
```
If the laser point cloud data is transmitted through the ros node, the point cloud is transmitted in real time instead of inference through files, is there an API available, thank you.

**Comment by Tai-Wang** [comment]
Please refer to #916.
