### ISSUE TITLE
有关自定义数据集的问题

### ISSUE THREAD

**Issue by jczzp** [open-mmlab/mmdetection3d#943]
开发组您好！感谢您们提供如此优秀的开源算法库，我想询问关于自定义数据集用于训练的问题。
我自己的数据并非自动驾驶领域，现在只有kitti类型的label三维框标签与bin格式的点云文件，缺少kitti中的calib与image文件，我阅读了mmdet3d的官方文档，但仍然不清楚像我这样的（仅有bin格式的点云坐标与对应的label）三维数据能否用于训练，该怎样重写相关代码。
希望开发组看到后能给予帮助，谢谢！

**Comment by ZCMax** [comment]
Hi! You can definitely train a dataset without camera data (eg: calib / image), but you may need to slightly modify the data pre-processing scripts we provided, or you can set the calib and image information to be something random. Please refer to #429  for more details.

**Comment by daishan12** [comment]
> 
开发组您好！感谢您们提供如此优秀的开源算法库
我自己的数据集同样只有kitti类型的label三维框标签与bin格式的点云文件，缺少kitti中的calib与image文件，然后我看了几个相关的issue，仍然不是很清楚应该怎样更改pre-processing scripts，因为我们的数据坐标系和kitti官方的坐标系不同，所以我无法使用kitti提供的calib,所以想资讯一下如何更改pre-processing scripts
希望开发组看到后能给予帮助，谢谢！

**Comment by zhangxingAI** [comment]
> > 
> 
> 开发组您好！感谢您们提供如此优秀的开源算法库 我自己的数据集同样只有kitti类型的label三维框标签与bin格式的点云文件，缺少kitti中的calib与image文件，然后我看了几个相关的issue，仍然不是很清楚应该怎样更改pre-processing scripts，因为我们的数据坐标系和kitti官方的坐标系不同，所以我无法使用kitti提供的calib,所以想资讯一下如何更改pre-processing scripts 希望开发组看到后能给予帮助，谢谢！

您好，请问您的问题解决了吗，我也遇到了相同的问题

**Comment by WangJuan6** [comment]
@jczzp @daishan12 @zhangxingAI 
您好，我遇到了同样的问题，请问您的问题解决了吗？能否提供一些指导，谢谢
