### ISSUE TITLE
Second (refinement) stage of CenterPoint

### ISSUE THREAD

**Issue by wusize** [open-mmlab/mmdetection3d#962]
**Describe the feature**

**Motivation**
It seems that the current implementation of CenterPoint only includes its 1st stage. As is reported by the [paper](https://arxiv.org/pdf/2006.11275.pdf), the refinement stage contributes 1.8 mAP gain. I think the community would benefit more from the full implementation of this paper.

**Related resources**
[Official codes](https://github.com/tianweiy/CenterPoint/tree/fb4806f057dbbb1f8d9a201f7c73f7923399abeb) 

**Additional context**
My email: SIZE001@e.ntu.edu.sg

**Comment by ZCMax** [comment]
Hi, @wusize, thanks for your suggestion, this feature is currently not in our short-term plan, we will consider this in the future, Besides, the PR is also welcomed.

**Comment by Tai-Wang** [comment]
Will supported in #1470 .
