### ISSUE TITLE
How to generate txt result for KITTI test data

### ISSUE THREAD

**Issue by ChunmianLin** [open-mmlab/mmdetection3d#97]
Hi, authors, thanks for your great work.
I want to evaluate my model on KITTI test data, so how can I get the txt format file to submit to the official of KITTI website for evaluation?
Also, I cannot intuitively understand how the performance of my model is during model training and validation, and it just generates the pkl result file. Does any code provide for visualization usage, except for MeshLab?

**Comment by ChunmianLin** [comment]
Thanks in advance, and any helps would be greatly appreciated!

**Comment by ZwwWayne** [comment]
Please refer to the 6th example in the [doc](https://mmdetection3d.readthedocs.io/en/latest/getting_started.html#test-a-dataset).
Once you got the text files, you could also visualize the results via this [tool](https://github.com/kuixu/kitti_object_vis). We are planning to provide more useful and complete visualization APIs in the next month.

**Comment by ChunmianLin** [comment]
I have got it, and many thanks for your tips.

**Comment by liyang0522** [comment]
i have followed your advice , but some text files missed eg:000502.txt , so number of prediction text file is less than 7518 which is the length of official test data . so any idea can help ?

**Comment by liyang0522** [comment]
@ChunmianLin   @ZwwWayne    do you have the same problem？Thank you for your help!
