### ISSUE TITLE
CameraInstance3DBoxes origin setting

### ISSUE THREAD

**Issue by excitohe** [open-mmlab/mmdetection3d#972]
mmdet3d/core/bbox/structures/cam_box3d.py Line:72-75
```
    if origin != (0.5, 1.0, 0.5):
        dst = self.tensor.new_tensor((0.5, 1.0, 0.5))
        src = self.tensor.new_tensor(origin)
        self.tensor[:, :3] += self.tensor[:, 3:6] * (dst - src)
```
```
    Coordinates in camera:
                z front (yaw=-0.5*pi)
              /
             0 ---> x right (yaw=0)
             |
             v
        down y
```
In my opinion, Y-axis in camera coord is facing down, and the origin is the bottom center of box3d (origin=(0.5, 1.0, 0.5)), so why use `+=` instead of `-=` in Line:75?
If origin=(0.5, 0.5, 0.5), the location3d center won't farther away from bottom center toward down?

**Comment by excitohe** [comment]
@Tai-Wang @ZCMax

**Comment by ZCMax** [comment]
For CameraInstance3DBoxes, the tensor finally(actually) saved is the [x, y, z, l, h, w, roty],  while the [x, y, z] is the bottom center of the 3d box.

So if you want to represent a 3d box using this class, you can have two choices:
1. CameraInstance3DBoxes( tensor([x, y, z, l, h, w, roty]), origin = (0.5, 1.0, 0.5))
2.  CameraInstance3DBoxes( tensor([x, y-h/2, z, l, h, w, roty]), origin = (0.5, 0.5, 0.5))
So while constructing this class, if you use origin = (0.5, 0.5, 0.5), you should use the center point coordinates;  if you use origin = (0.5, 1.0, 0.5), you should use the bottom center point coordinates. The origin parameter is used to transfer the input point coordinates to 3d box center bottom coordinates.

Let's go over the process:

if origin != (0.5, 1.0, 0.5): # (0.5, 0.5, 0.5)
    dst = self.tensor.new_tensor((0.5, 1.0, 0.5))  
    src = self.tensor.new_tensor(origin)  # (0.5, 0.5, 0.5)  
    self.tensor[:, :3] += self.tensor[:, 3:6] * (dst - src)  #  (x, y- h/2, z) + (0, h/2, 0)

**Comment by ZCMax** [comment]
Meanwhile, the code of SMOKE will be released soon, maybe you can have a better understanding of this by referring to our code.
