### ISSUE TITLE
Dynamic voxelization is slow

### ISSUE THREAD

**Issue by s-ryosky** [open-mmlab/mmdetection3d#99]

**Comment by s-ryosky** [comment]
scatter_points in dynamic voxelization takes over 0.02s on cuda.
Is there a good way to speed it up?

**Comment by ZwwWayne** [comment]
We indeed observe some cases that dynamic voxelization is slow, e.g., when the points are very dense at some voxels. Currently, we do not have a very good way to speed it up. We plan to do it in the next few months.
