### ISSUE TITLE
Multiview Images on Waymo

### ISSUE THREAD

**Issue by XuyangBai** [open-mmlab/mmdetection3d#991]
Thanks for this excellent codebase. I find for Waymo Open Dataset mmdet3d currently only processes the first image during data preprocessing and there is no multi-modality method implemented on Waymo. Any plan to support all five images and multi-modality detection pipeline on Waymo?

**Comment by Tai-Wang** [comment]
Yes, that's in our plan. But maybe recently we do not have enough resources to support it very soon. PRs are welcome.
